### ISSUE TITLE
needed help with discord rpc not reconnecting

### ISSUE THREAD

**Issue by JoqniX** [th-ch/youtube-music#1000]
hi i needed help im on version 1.19.0 
tho i believe the rpc issues which were mentioned here were fixed in v1.19.0 on the official build

seems im getting this ( whenever i click on plugins > discord > reconnect.  ( note this was on my 2nd pc where i usually use ytm for music) 
![image](https://user-images.githubusercontent.com/54277349/214038375-45e3cee2-cc98-4e3d-a30b-7f16949ff787.png)

i did try uninstalling ytm, and also deleting the folder from AppData\Roaming\YouTube Music & AppData\Local\Programs\youtube-music 

but what's weird is~ i tried installing the same version on my main pc - and it works fine, + the rpc also is working well. 

if anyone knows a way to fix this do lmk? 

the only thing i remember doing was using the temp fix which was mentioned in somewhere in this repo. to fix the discord rpc one? but yea ever since i auto updated to 1.19.0 this had happend.  ( but i believe as i did remove the ytm data files from appdata folders. that would fix it right? but here it seems not to be the case~ )

**Comment by JoqniX** [comment]
edit - even tried copying the files from my main pc and pasting it  to 2nd pc. i still get the same error! 
dunno if having multiple discord clients could be the issue? if it was the case then i would have gotten error on main pc. and rpc wouldnt have worked right~

**Comment by JoqniX** [comment]
ahh! i found the issue. apparently if you run discord as admin. the rpc wont work??? is that normal?? i do use other rpc apps like customrpc. it does work well even tho the client is admin? 

if any contributors or if th-ch sees this~ could you add this to list for next update to be fixed?

**Comment by JoqniX** [comment]
as i did fix my issue i'll close it for now~  (ill update the title as well, hope it helps someone who is looking for a fix for this~ )

**Comment by Araxeus** [comment]
might be fixed by #961 , but you'd have to ask @xhayper

**Comment by JoqniX** [comment]
> Btw you probably shouldn't run anything as admin, unless you really need to
ah yea~ i had to run it as admin cuz i use a footpedal  for discord push to talk~ so other apps which uses discord also recommended to run as admin.  so had no choice~ 




> might be fixed by #961 , but you'd have to ask @xhayper
okie ill do that then~ thank you again Araxeus!

**Comment by Araxeus** [comment]
Oh I just noticed you are issue/pr number #1000 🎉🥳🎉

you don't have to contact him, he'll probably see the tag here and respond if he has anything to say

**Comment by Zo-Bro-23** [comment]
> Oh I just noticed you are issue/pr number #1000 🎉🥳🎉

That's cool 🥳🎉

**Comment by xhayper** [comment]
This might happened because you need to run the youtube app as admin if you open discord with admin, probably something related to named pipe permission (don't even know if it exist or not, need to do more research)
