### ISSUE TITLE
MacOS ARM64 File is corrupted

### ISSUE THREAD

**Issue by mkikets99** [th-ch/youtube-music#1004]
![зображення](https://user-images.githubusercontent.com/22869811/215267059-0ac725ba-d0fd-4d16-a6c5-5298d8938416.png)
It says:
```
Application "Youtube Music" is damaged, it's cannot be opened. Needed to be moved to Bin.
[Move to Bin]
[Cancel]
```
Another version working fine.

**Comment by andreicocari** [comment]
Same issue 

MBP14 M1 Max
Ventura 13.1

**Comment by Araxeus** [comment]
Read the readme guys 😅

https://github.com/th-ch/youtube-music#macos

**Comment by mkikets99** [comment]
> Read the readme guys 😅
> 
> https://github.com/th-ch/youtube-music#macos

Well... I forgot about it...
Cause its just asked me for an update...
Is there any way to fix dmg and integrate it?

**Comment by dronmaxman** [comment]
macOS 13.4.1, YT music 1.20 has same issue. 

![image](https://github.com/th-ch/youtube-music/assets/15871669/a4f4adc0-237e-4cf0-a42f-a74b4a8063dd)
