### ISSUE TITLE
MacOS music controls do not work well with YT music.

### ISSUE THREAD

**Issue by FormalSnake** [th-ch/youtube-music#1011]
This issue has been bothering me for a while.
Thunder is a 3:08 minute song and it indicates 5:07.
This happens every few songs and then they all add up in time.
I am on MacOS ventura 13.2 on a base m1 macbook air
![Screenshot 2023-01-31 at 17 07 05](https://user-images.githubusercontent.com/90651091/215832492-2383b63e-5cae-43e4-b0cd-a53f80f1b4f6.png)

**Comment by LetrixZ** [comment]
It also happens on Linux and with KDE Connect. I don't remeber if Windows also has this problem.

**Comment by FormalSnake** [comment]
It is such a small detail that just bugs me

**Comment by Araxeus** [comment]
If the app stays open so that you see the video, does it still happen?

**Comment by FormalSnake** [comment]
It's all the time.

**Comment by Araxeus** [comment]
might be fixed by #1032

**Comment by FormalSnake** [comment]
I'll try when it gets accepted
