### ISSUE TITLE
Unsupported country blocker

### ISSUE THREAD

**Issue by Fr0sTy7u7** [th-ch/youtube-music#1015]
Is it possible for a plugin that can allow you to use the app in unsupported countries

**Comment by Araxeus** [comment]
That's called a VPN friend 😋

**Comment by MrLunatic-coder** [comment]
can you pls add vpn plugin ?

**Comment by Retapich** [comment]
As far as I know, in certain (or almost all) countries, the restriction can be circumvented by removing the "**music.**" subdomain in the link to the song itself:

> music.youtube.com/watch?v=.... ➡️ youtube.com/watch?v=....

**I think this method can somehow be implemented as a plugin** 🙏😢
 
✅ Currently, you can use the already implemented **SOCKS5 Proxy** function, which is available in the following menu - `Options > Advanced options > Proxy`

**Comment by Neglectfull** [comment]
A way is to install "proton vpn" and set the location to usa (or anywhere that supports it) then click on the hamburger menu (the three dashes at the corner) then click settings -> connect on start (should be on) -> start on boot (Should also be on) after that click on the advanced menu. go down and enable split tunneling,  then restart, and go back to split tunneling and enable "only apps/ips will go through a vpn tunnel" now click on "add app" and select the youtube music, and restart the vpn... and youre done! i know it took long, but now it should never bother you again! (plus only youtube music will be using the vpn!)
