### ISSUE TITLE
Timer keep continue while the song pause

### ISSUE THREAD

**Issue by MasamuneDate99** [th-ch/youtube-music#1021]
![image](https://user-images.githubusercontent.com/24244933/217199600-e02aa785-fa92-4159-99d0-00e67d4824c1.png)
![image](https://user-images.githubusercontent.com/24244933/217199635-e80282fa-627c-4f4d-97bd-f514db967b31.png)

**Comment by DereC4** [comment]
Doesnt' seem to be happening on my side 
![image](https://user-images.githubusercontent.com/53978637/225426127-b7e727ab-9698-4a23-a441-e5c0bc415222.png)
![image](https://user-images.githubusercontent.com/53978637/225426139-554520af-92c0-40a3-a771-4e876d4fb300.png)

**Comment by DereC4** [comment]
Have you tried reproducing this

**Comment by Araxeus** [comment]
> Doesnt' seem to be happening on my side

I think this might have been fixed by #961

**Comment by JellyBrick** [comment]
Fixed at #1235
