### ISSUE TITLE
[Feature Request]: Port to Chrome Extension?

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#1026]
I was wondering if it would be easy to port `youtube-music` to a Chrome extension. After all, injecting JS and CSS is fairly similar, and all the plugins should work well. Even if it's not possible to port all the plugins, it would definitely be nice to have some of the plugins on the web. The use cases are limited, but if it's fairly easy to do, it'll be much easier to install a Chrome extension on a temporary computer or when browsing as a guest user as opposed to installing an app.

@Araxeus what do you think? Also, sorry I haven't been very active on the repo lately. Been a bit busy; hopefully I'll get more time in the coming weeks!

**Comment by Araxeus** [comment]
It's not as simple as you say. All of the plugins use either Electron features/code,  use stuff related to the os, stuff that isn't compatible with browsers in back.js, the whole structure and way of communicating, the option+popup pages, and more

A better way to look at this would be making a browser extension, then borrowing some ideas/code from this app

Take for example my extension - [Youtube-Volume-Scroll](https://github.com/Araxeus/Youtube-Volume-Scroll)

It is similar to the plugin `precise-volume` - tho it actually has many more features (and more on the way 😁)

**Comment by Zo-Bro-23** [comment]
> It's not as simple as you say. All of the plugins use either Electron features/code, use stuff related to the os, stuff that isn't compatible with browsers in back.js, the whole structure and way of communicating, the option+popup pages, and more
> 
> A better way to look at this would be making a browser extension, then borrowing some ideas/code from this app
> 
> Take for example my extension - [Youtube-Volume-Scroll](https://github.com/Araxeus/Youtube-Volume-Scroll)
> 
> It is similar to the plugin `precise-volume` - tho it actually has many more features (and more on the way grin)

Hmm, I see... If it isn't as easy as I thought, then maybe we shouldn't bother.
