### ISSUE TITLE
[Bug]: Windows media control not working

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#1033]
I'm using the latest build of `master`. `youtube-music` doesn't seem to be registering with Windows media control. It used to. Either this is an issue with the latest Windows version (Win11 Dev) or an issue with the latest version of `youtube-music`. Windows play/pause is working. I'm using [ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts) to view media playing in Windows. It's detecting videos on Chrome, but not `youtube-music`. Maybe it's an issue on their side, in which case I will open the issue there. I don't see the current song on my Windows quick access either, though that might have something to do with a new Windows version. Thoughts are appreciated.

**Comment by Araxeus** [comment]
It works fine on my end, did you maybe enable `shortcuts-Override MediaKeys?`
![image](https://user-images.githubusercontent.com/78568641/220708667-9b86a6a1-12d0-4b77-96c1-c6067e827c98.png)

**Comment by Zo-Bro-23** [comment]
> It works fine on my end, did you maybe enable `shortcuts-Override MediaKeys?` ![image](https://user-images.githubusercontent.com/78568641/220708667-9b86a6a1-12d0-4b77-96c1-c6067e827c98.png)

I didn't mean media control. I meant media as in windows showing the current song with artwork and everything. Like it doesn't show anything as playing; it pauses and plays using media keys, but it doesn't show any popup or osd either.

Also, as a related issue, override media keys doesn't work. Play/pause works, but if I have something else playing like a YouTube video, then that gets paused/played and ytm isn't affected.

**Comment by Araxeus** [comment]
`Override mediakeys` also makes the windows media OSD not show.

That's why I asked if it was enabled

**Comment by Zo-Bro-23** [comment]
> `Override mediakeys` also makes the windows media OSD not show.
> 
> That's why I asked if it was enabled

Still persists after disabling override mediakeys.

**Comment by Araxeus** [comment]
It seems "modern flyouts" don't use the native mediasession api

https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md

Can you try without it?

**Comment by Zo-Bro-23** [comment]
> It seems "modern flyouts" don't use the native mediasession api
> 
> https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
> 
> Can you try without it?

It doesn't show up on Windows Quick Actions either. Chrome music.youtube.com works, but the ytm app doesn't.

**Comment by Araxeus** [comment]
Well I find it hard to debug since it works for me and this a native youtube feature, we don't set the mediasession ourselves

Try to run in dev tools [`Navigator.mediaSession`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaSession)

To see if its correctly set, and maybe you can try disabling all plugins and see if it changes anything?
