### ISSUE TITLE
Uploaded songs provide incorrect album info to the songInfo object.

### ISSUE THREAD

**Issue by Tantusar** [th-ch/youtube-music#1035]
Was trying to get Tuna working with the app, but ran into the following issue: I have a large number of songs that I've _uploaded_ to YouTube Music (well, most of them are from the Google Play Music days, but no matter) and when I try to grab the name of the album for display on stream I instead get the artist name corresponding to the first _played_ track in the playlist.

This does not appear to be a problem with Tuna, and indeed when I had a look at the `songInfo` object in the YTM app console, it turned out the album name was wrong there. So it seems that something is going wrong with pushing album names of uploaded songs to `songInfo`.

**Comment by Araxeus** [comment]
Thank you for reporting!

It will be fixed in PR  #1032 commit [d122ffe](https://github.com/Araxeus/youtube-music/commit/d122ffe72eb0db08a06b4440dde5bb23087ffc03)
