### ISSUE TITLE
Settings menu dropdowns aren't aligned

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#1042]
Not sure if anyone has noticed this yet but navigating to settings and going to the dropdown menus in "Playback" and "Language & location" reveals that they are oddly aligned, more like plaintext. 

![image](https://user-images.githubusercontent.com/53978637/221383731-587fe70b-feef-471b-9782-4c993237fc75.png)

This is from clicking on "United States"

![image](https://user-images.githubusercontent.com/53978637/221383739-87d670f9-2e72-477c-bd0d-c40a7e73f8d4.png)

![image](https://user-images.githubusercontent.com/53978637/221383743-16433240-146b-487a-9c6e-15e6852cb42c.png)

![image](https://user-images.githubusercontent.com/53978637/221383745-7a609c1d-af17-46b2-8f2b-f8bf80de3a6f.png)

**Comment by Araxeus** [comment]
hehe those are native YouTube settings, we don't touch those
