### ISSUE TITLE
[Feedback]: Crossfade too abrupt

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#1046]
The crossfade plugin is nice, but it sometimes sounds to abrupt. The volume quickly drops, which makes it seem as if the song has suddenly stopped. Making it more gradual would be nice. Sounds great otherwise!

**Comment by Araxeus** [comment]
you can currently modify it in config.json, tho we should probably also add a menu option that launches a custom-electron-prompt to change those

https://github.com/th-ch/youtube-music/blob/476e13de9f37d697ccb70fc27ce789ee1c5fec14/plugins/crossfade/front.js#L11-L17
https://github.com/th-ch/youtube-music/blob/476e13de9f37d697ccb70fc27ce789ee1c5fec14/plugins/crossfade/fader.js#L44

**Comment by Zo-Bro-23** [comment]
Thanks that works!
