### ISSUE TITLE
[Bug]: Genius lyrics incorrect

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#1050]
The genius lyrics are incorrect for most malayalam songs.

![image](https://user-images.githubusercontent.com/62234360/222030971-82b9b8e7-daef-43d9-a1f1-78f56c796e13.png)

Any malayalam song that doesn't have genius lyrics ends up showing the lyrics for Thee Minnal. Any idea why this is? The incorrect lyrics always show this same set of lyrics, although that has nothing to do with the song I'm listening to. Is it anything to do with the Genius query algorithm?

**Comment by Zo-Bro-23** [comment]
Genius doesn't _have_ lyrics on their site for these songs.

**Comment by Araxeus** [comment]
Can you give more examples?

I tried loading this song, and the lyrics tab was disabled

**Comment by Araxeus** [comment]
I think this is a bug with genius search, because how is that query string have these results? 🧐

**Comment by Araxeus** [comment]
I've opened a PR which should fix this (#1052), could you test it?

**Comment by Zo-Bro-23** [comment]
Thanks for the PR! I would love to test it out, but since I'm working on a plugin at the moment, I can't have multiple instances running. I'm testing that version out right now. @derec4 can you try this out please? Thanks!

**Comment by DereC4** [comment]
I will after I'm done with this assembly lab 😭

**Comment by DereC4** [comment]
Can you name me some song names to test?

**Comment by Zo-Bro-23** [comment]
> Can you name me some song names to test?

Athmave Poo, Ottamuri Vakkumayi, and Thalatherichvar. Try both video and audio versions. Also try other songs by Sushin Shyam. Thanks for doing this!

**Comment by DereC4** [comment]
Doesn't seem to put the wrong lyrics anymore at least

**Comment by Araxeus** [comment]
> Not working on the latest commit.

Should work now on main since https://github.com/th-ch/youtube-music/pull/1090 was merged
