### ISSUE TITLE
Download speed slowed down

### ISSUE THREAD

**Issue by SamuraiEv** [th-ch/youtube-music#1051]
I've been using the downloader plugin for quite some time, until yesterday I noticed something really weird. Usually, when downloading songs, it took less than 5 seconds for the download percentage to go from 0 to 100%. Now, when I try to download a song, it takes more than a minute for it to download. I went to Task Manager and noticed that the download speed Youtube Music is using, ranges from 250 to 260 Kbps, which is really really slow, it feels like it is capped. Is there any issue with the download plugin?

**Comment by senolfndk** [comment]
The same problem slowed down

**Comment by Araxeus** [comment]
I've opened an experimental PR which fixes this issue (#1054)

**Comment by senolfndk** [comment]
If you explain this subject by making a video, I do not understand it in this way.

**Comment by Araxeus** [comment]
This will be fixed in the next version @senolfndk

**Comment by senolfndk** [comment]
> Bu, bir sonraki sürümde düzeltilecektir@senolfndk

ok
