### ISSUE TITLE
PiP symbol not showing up

### ISSUE THREAD

**Issue by DamianArielLerner** [th-ch/youtube-music#1057]
where is supposed to be the PiP (picture in picture) symbol?

**Comment by Araxeus** [comment]
Fixed by #964 (merged 2 months ago but still unreleased)

**Comment by DamianArielLerner** [comment]
https://github.com/th-ch/youtube-music/issues/959#issue-1527803896

**Comment by Araxeus** [comment]
just wait for next release, the fix will be included 🙌

**Comment by DamianArielLerner** [comment]
ok, thanks!
