### ISSUE TITLE
Songs in a playlist pausing at the beginning (infinite loading ?)

### ISSUE THREAD

**Issue by MaxLepan** [th-ch/youtube-music#1058]
Hi,

I've noticed a few days from now that all the songs "pause" when they start, and the playlist shows that the song is loading. It stops doing it and plays the song when I click on the player, like I would do to resume a song.

I have this bug only on one of my 2 PCs, I tried reinstalling the app, but it didn't work. The bug only occurs on my Win11 laptop.

**Comment by Araxeus** [comment]
Do you have some kind of system ad blocker installed?

Or are you maybe using a custom dns filter?

If not could you try using the app without the `adblocker` plugin, and see if it changes anything?

**Comment by MaxLepan** [comment]
I deactivated `adblocker` and `sponsorblock`, but it didn't changed nothing.
And I don't even know how to use a DNS filter.

After some tests, I deactivated `disable-autoplay`, and that was what stopped the songs. I thought this plugin just restarted a playlist when you finished it (and not launch the YT recommandations), but it seems it just completely stops autoplay, even from a same playlist.

I'll close the issue on this.

**Comment by Araxeus** [comment]
Oh yeah, I forgot about that plugin

It's a weird one for sure 😅

**Comment by yuliu** [comment]
> If you can't build yourself, just say what's your Operating System and I can build for you (Windows/mac/linux)

I'm on Windows 10 x64.

**Comment by Araxeus** [comment]
Yikes, I just discovered a major breaking bug on the main branch, will need to wait until we resolve that first #1084

**Comment by Araxeus** [comment]
Ok I have built the app including a fix for the breaking change

@yuliu you can try it here:

https://drive.google.com/drive/folders/1Kfa4USQtoUjZTZLzgToDM6kMELdkRqgC?usp=sharing

Please report if your issue is fixed in this version or not 🙂

**Comment by Araxeus** [comment]
@yuliu have you been able to try it?
