### ISSUE TITLE
Menu doesn't show the right things

### ISSUE THREAD

**Issue by DerKartdomi** [th-ch/youtube-music#1060]
The menu doesn't show the right things for me. Here is a screenshot 
https://screen.magic-pics.tk/FOku9/ZaneHaWa29.png

Thank you for helping
Yours Dominik

**Comment by Araxeus** [comment]
You selected it somehow, try maybe pressing <kbd>Tab</kbd>?

**Comment by Araxeus** [comment]
Try deleting your config,json

* Windows: `%AppData%/Youtube Music` (MyUser/AppData/Roaming/Youtube Music/config,json)
* Linux: `~/.config/Youtube Music/config,json`
* MacOS: `~/Library/Application\ Support/YouTube\ Music/config.json`

**Comment by DerKartdomi** [comment]
I just found out it happens with the discord plugin

**Comment by Araxeus** [comment]
What does that mean?

**Comment by DerKartdomi** [comment]
I don't know why exactly this happens but the menu gets this bug as soon as I activate the "discord" plugin

**Comment by Araxeus** [comment]
Can you post your config.json here?

**Comment by DerKartdomi** [comment]
I found the error in the front.js.
It was my fault but now it works fine 😄 
But I have another question. How It works with captions selector? I cant click on it if I enabled this or I need special videos?

**Comment by Araxeus** [comment]
> I found the error in the front.js.
It was my fault but now it works fine 😄

Oh well you really should have specified that you are running in dev mode and that you edited files lol

> But I have another question. How It works with captions selector? I cant click on it if I enabled this or I need special videos?

The plugin still needs some work, it only works on specific videos, but the button is always displayed

You can check it out searching for `Kv5-7kTp9m8` and clicking on the first result
that video has captions

(another problem is that the popup select doesn't automatically select the current option for some reason)

**Comment by Araxeus** [comment]
I've opened a PR which should fix the issues with the caption selector
