### ISSUE TITLE
[UI\Feature Request] Windows Taskbar Thumbnail Media Buttons

### ISSUE THREAD

**Issue by DynaZor** [th-ch/youtube-music#107]
Hi!
I really love your software and appreciate all the effort!!
The only thing missing for me at the moment is the taskbar media controls.
It exists in almost any (binary based) media player and should be simple to implement (as we always say before actually implementing a feature)

This is low priority, but should be simple.
If it's not simple or takes a long time - please close the issue until more people ask, too.

Again, I LOVE your client!

**Comment by MrDodojo** [comment]
is this the same as a flyout?

**Comment by gurt-il** [comment]
I'm really missing this feature too

**Comment by th-ch** [comment]
Hey everyone, https://github.com/th-ch/youtube-music/pull/200 has been merged and brings a new plugin `taskbar-mediacontrol` (thanks to @Araxeus) that will ship in the next version!
