### ISSUE TITLE
Move the download button from the top

### ISSUE THREAD

**Issue by Gollum69** [th-ch/youtube-music#1074]
In the original YouTube Music shuffle play is at the top, and regularly needs to be used as I believe if you use the dedicated shuffle button you encounter the classic YT bug of only shuffling the first 50 songs or so. Upon using this wonderful app I instinctively clicked the top button expecting it to shuffle and instead proceeded to download my 850 song playlist, please could you move the download button to somewhere else

**Comment by Araxeus** [comment]
We are short on space 😂

**Comment by Gollum69** [comment]
Ah, thats a shame. In the meantime I'll just disable it until the time comes to rip all the music
