### ISSUE TITLE
Remove thumbs up/down buttons

### ISSUE THREAD

**Issue by Gollum69** [th-ch/youtube-music#1075]
Previously I was able to remove them using uBlock Origin when its integrated through the browser, removing them frees up more room for the song information, since many times you can't see the year it was released or the entire album name, I also literally never use the thumbs up/down buttons so it would be nice if this could be added

**Comment by Araxeus** [comment]
Done in #1077 😉

**Comment by Gollum69** [comment]
so quick thanks so much man, excellent stuff

**Comment by Gollum69** [comment]
i am reopening it so i can receive the good news a second time

**Comment by Gollum69** [comment]
when is this gonna be added out of interest i thought it'd already been done
