### ISSUE TITLE
Lyrics from "Song" type are not being intercepted

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#1085]
I've been troubleshooting this behavior for a while and this is what I've got: It would appear for some songs, especially those of the "Song" type (not "Video"), will have their lyrics directly pulled from varying sites like Musixmatch or Lyricfind. 

Question: Is there any way we can intercept the lyrics from other sites?

For those confused about the two types I'm referring to, look at the attached photo. You'll commonly see search results separated into "Song" and "Video". Clicking on the "Song" types leads to lyrics being overridden from other sites in most cases. 

![image](https://user-images.githubusercontent.com/53978637/227063410-330ba5c0-fba8-4c29-b03f-95716ed82f9d.png)

These songs will draw lyrics from other sites. Here is an example reproduced using "As It Was". First image is the lyrics from the "Song" type, second is from the "Video" type (Notice how the source is gone as it draws from Genius)

![image](https://user-images.githubusercontent.com/53978637/227064088-c9e04c2f-f93b-425a-9312-0ceece76a0a2.png)

![image](https://user-images.githubusercontent.com/53978637/227064138-b8e2612e-7e64-4625-bbd0-5c54bc9a6c1b.png)

**Comment by Araxeus** [comment]
This is a native youtube functionality, the `lyrics-genius` plugin only expands on it by providing lyrics if youtube doesn't provide it by itself

**Comment by DereC4** [comment]
working on it woo

**Comment by DereC4** [comment]
#1092
