### ISSUE TITLE
Drag and drop in "Up next" is buggy.

### ISSUE THREAD

**Issue by ZenTunE** [th-ch/youtube-music#1088]
If you scroll down the list of the songs in queue and try to hold on to a song and sort it, the whole list scrolls all the way to the top.

It seems that it is intended behaviour that you can hold the song at the top and it scrolls by itself but if you lift the cursor at all while holding the song it starts scrolling.

**Comment by ZenTunE** [comment]
This is exaggerated in windowed mode but happens when maximized too.

**Comment by Araxeus** [comment]
Weird, it works fine for me, both in browser and in the app

**Comment by ZenTunE** [comment]
I'll post a video when I get the chance.

**Comment by ZenTunE** [comment]
I'll post a video when I get the chance.

**Comment by MiepHD** [comment]
I have this exact same issue a lot of times
