### ISSUE TITLE
Changes made to plugin menu roll back after app restart

### ISSUE THREAD

**Issue by ghettoflight** [th-ch/youtube-music#1089]
It's just like the description says.. I started experimenting with the available plugins, and configured them how I wanted at first.. everything was fine for a while, but now I want to disable the "precise volume" feature, and it works initially, but the next time I close and re-open the app, that stupid shit is back on again. I've uninstalled the program, re-downloaded it and re-installed it.. and somehow, precise-volume, and a few other nuisance-settings, all stay the same. I'm assuming the app saves a config file somewhere in it's install directory, and that's not being wiped between reinstalls.. I dunno, maybe you can help me. 

Also, being able to download an entire playlist, no matter how long it takes, would just be un-fucking-believably useful to me.. thumbs up if you can fix it.

Awesonme app! They left us no choice... thank God someone had the time skills and decency to clone the overpriced, but super useful app, and give it out for free.. you're the man, Thanks!

**Comment by Araxeus** [comment]
Very weird, it just saves a config file like you said.

For example, when you enable/disable the `precise-volume` plugin, it will change the value `plugins.precise-volume.enabled`

config.json folder path:
* Windows: `%AppData%/Youtube Music/config.json` (`MyUser/AppData/Roaming/Youtube Music/config.json`)
* Linux: `~/.config/Youtube Music/config.json`
* MacOS: `~/Library/Application\ Support/YouTube\ Music/config.json`

-----

> Also, being able to download an entire playlist, no matter how long it takes, would just be un-fucking-believably useful to me.. thumbs up if you can fix it.

You can already do that now, just enable the downloader plugin
(next release will improve the downloader plugin even more)
