### ISSUE TITLE
[Bug]: Elapsed seconds does not trigger song-info callback

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#1093]
The registerCallback for song-info does not get called for an update in the elapsed seconds of the song. This makes sense, but ideally there should be a way to manually request song-info whenever needed. That way I can use setTimeout to get regular song-info updates if I want to. I'm building a remote Android app, so this means that the slider won't automatically move unless the song is paused/played. This is not a big issue, but it would be great if there was an alternative.

**Comment by Araxeus** [comment]
The mpris plugin keeps track of the current time

https://github.com/th-ch/youtube-music/blob/master/plugins/shortcuts/mpris.js

**Comment by Zo-Bro-23** [comment]
Yup, `ipcMain.on("timeChanged")` worked! A few more questions please:

1. The album returned by `song-info` is `null` for some songs. Any idea why? The player shows a correct album name.
2. Any way to know if a song is liked or not? I think I have to get the UI icon element and see if it's filled, but how do I do this?

**Comment by Araxeus** [comment]
1. Can you give some examples? It shouldn't happen if the album is available

2. There's probably a way to do it via the api, will look into it after work

**Comment by Zo-Bro-23** [comment]
> 1. Can you give some examples? It shouldn't happen if the album is available
> 
> 2. There's probably a way to do it via the api, will look into it after work

1. Pathira Kalam is the only one I remember. It was around a 10% occurance.

2. Sure, thanks!

**Comment by Zo-Bro-23** [comment]
> > 1. Pathira Kalam is the only one I remember. It was around a 10% occurance.
> 
> Gimme a link 😅
> 
> Also what do you mean 10% accuracy?
> 
> Does it sometimes work and sometimes not?

https://music.youtube.com/watch?v=bBtAHfAcj-g&feature=share

10% accuracy as in it doesn't work for around 10% of the songs.

**Comment by Araxeus** [comment]
> 1. The album returned by `song-info` is `null` for some songs. Any idea why? The player shows a correct album name.

Well that's a bug...

https://github.com/th-ch/youtube-music/blob/05278ab6431c06ac26512e5555f502b6d52500d4/providers/song-info-front.js#L79
should be
```js
 setTimeout(sendSongInfo); 
```

**Comment by Araxeus** [comment]
fixed in https://github.com/th-ch/youtube-music/pull/1090

**Comment by Araxeus** [comment]
> this value does not update if a song is liked or disliked.

Oh sorry about that.

here's a new version:

```js
function getLikeStatus(currentVideoId = $('#movie_player').getPlayerResponse().videoDetails.videoId) {
	const playerBar = $("ytmusic-player-bar");
	const likedVideos = playerBar.getState()?.likeStatus?.videos;
	if (likedVideos) {
		for (const [id, status] of Object.entries(likedVideos)) {
			if (id === currentVideoId) {
				return status;
			}
		}
	}
	return playerBar.__data.likeButtonRenderer_.likeStatus;
}
```

`playerBar.getState()?.likeStatus?.videos` will return an object with videos whos like status changed **this session**
if it wasn't changed, then it wont be in the object, and the value will be grabbed from `playerBar.__data.likeButtonRenderer_.likeStatus`

**Comment by Zo-Bro-23** [comment]
Works 🎉 Thanks for the help 🫂
