### ISSUE TITLE
Adblock plugin makes application laggy and unresponsive

### ISSUE THREAD

**Issue by FQQD** [th-ch/youtube-music#1105]
I built the app myself a few days ago, since the releases are pretty old, but now, if I play music from my playlist after a while it gets very slow and laggy, as if my internet or CPU wasn't good enough. This is a new issue though and my internet and CPU were able to handle everything fine before.
I'm going to attach a video how it looks, note that I had the "Crossfade" plugin on. This is not the cause, but does make it worse. Also, I had to compress the video down a lot, the quality is better normally.

https://user-images.githubusercontent.com/96952506/230140583-a3840e6e-6a5c-4fd1-b703-d76a774f8b16.mp4

Also, I'm running on Feren OS x86_64 (Ubuntu)
CPU: AMD Ryzen 3 3200G (4) @ 3.600GHz
GPU: NVIDIA GeForce GTX 660
Speedtest at time of filming: 35mbps Down;  10mbps Up; 14 Ping

Installed via self-compiled .deb package

**Comment by Araxeus** [comment]
I think it has to do with the adblock plugin - after updating it in #1100

This is gonna be a headache to solve...

**Comment by FQQD** [comment]
can't one basically implement ublock origin? it doesn't have these issues

**Comment by Araxeus** [comment]
Did you try what I wrote? Did it fix the problem?

**Comment by FQQD** [comment]
Yes. Now, of course there are ads, but the app runs a lot better.

**Comment by Araxeus** [comment]
>  Now, of course there are ads

You means ads only when starting the app right? running `yarn add @cliqz/adblocker-electron@1.26.3` should just revert the last patch to the adblocker which fixed ads on app start

**Comment by FQQD** [comment]
i think there also where ads on the start of songs

**Comment by FQQD** [comment]
Hm. Was there any change on this?

**Comment by Araxeus** [comment]
It seems we either get ads on start or terrible performance

@th-ch what do you think? Should we revert the adblocker version bump?

**Comment by th-ch** [comment]
> Should we revert the adblocker version bump?

It might be better indeed, I want to release the new version soon (as said above, the previous version is old) so it would be great to have things as stable as possible

**Comment by Lucasamiel0406** [comment]
> @Lucasamiel0406 did you build from the main branch? it actually kinda works fine for me, I'm not actually sure that the new adblocker version is the culprit here

@Araxeus Yes I did, used the `release` first for a while then cloned the `main` branch to get newest features. 


Hours of usage it started to be unresponsive, found this Issue and applied the bump version revert, worked just fine and it's more responsive while playing ads in the beginning. I also tried not reverting the adblock version but enable/disable the plugin itself, could visibly see a major performance boost from still being responsive after hours and while scrolling the `Home` tab.


From all that, couldn't really think of anything other than `Adblock` plugin to be causing this. I'll do some further testing with my enabled plugins list, test combinations of them to see exactly where it all start breaking apart just to make sure.

Plugins used:
- Adblock
- BlurNavBar
- BypassAgeRestriction
- Discord
- InAppMenu
- LyricsGenius
- Notifications
- Sponsorblock

**Comment by Lucasamiel0406** [comment]
Made few tests for short periods, but it's visible the performance issues while using the `Adblock` plugin. Another plugin I saw causing a bit of performance issues together with `Adblock` was `InAppMenu`, nothing extraordinary.

Here's a video of the unresponsiveness behavior of `Adblock` and the app: https://youtu.be/3wXOVyAm6DY

**Comment by Araxeus** [comment]
@Lucasamiel0406 can you confirm that https://github.com/th-ch/youtube-music/pull/1124 fixes the issue?

**Comment by Lucasamiel0406** [comment]
Hello @Araxeus,

Performance is back and more stable in exchange for ads at the beginning.
#1124 does fixes the performance problem of this issue.

https://user-images.githubusercontent.com/49658726/234350573-2c1531b9-f851-4fdd-8239-b28e47c3c2f1.mp4
