### ISSUE TITLE
Caching lyrics? 

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#1106]
Thoughts about imementing a cache for the lyrics to improve the efficiency? Since songs are expected to be replayed multiple times it would be useful to not fetch lyrics, something that should be relatively unchanged, every playback.

I'm actually interested in trying to implement something like this if I may.

**Comment by Araxeus** [comment]
We could just use [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen), it has built in caching

**Comment by DereC4** [comment]
hmm i was thinking about that we had to make an api call every time
