### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by senolfndk** [th-ch/youtube-music#1107]
song not downloading

**Comment by SamuraiEv** [comment]
He is right. When clicking on the Download button, the downloader seems to be hanging at "Downloading...".

**Comment by senolfndk** [comment]
😕
https://user-images.githubusercontent.com/52818836/230592418-c01f4660-d95f-4f31-bde1-a3561f7e2596.mp4

**Comment by senolfndk** [comment]
😕

https://user-images.githubusercontent.com/52818836/230592577-fec0689b-77cf-4fdc-bab6-4cf093633603.mp4

**Comment by Araxeus** [comment]
This is fixed on the main branch and will be included in the next release

**Comment by senolfndk** [comment]
ok

**Comment by SamuraiEv** [comment]
Seems to be working now.

**Comment by seanhalim** [comment]
I don't knw how to build the app, don't understand how tto use the yarn and electron builder thing, please help....
