### ISSUE TITLE
Full-screen is off-center & videos get smaller over time

### ISSUE THREAD

**Issue by Technetium1** [th-ch/youtube-music#1119]
I didn't notice them getting smaller until a playlist had run through for a while. The issue in fullscreen also happens for stills of album art. Refreshing the app will fix the video size for at least the track it loads into. This happens for videos at different resolutions too.

Release 1.19.0 with Windows 11
Scale factor is 100% for all displays
Primary: 1560x1440
Secondary (x2): 1920x1080
Secondary: 1280x1024

![image](https://user-images.githubusercontent.com/9877150/232266350-9aa58f49-f0e3-43c0-83ee-2c0cad4f9051.png)
then to a new playlist:
![image](https://user-images.githubusercontent.com/9877150/232266402-cb5afdb5-6cbf-442c-aa86-fdc5f64e157d.png)
fullscreen on primary:
![image](https://user-images.githubusercontent.com/9877150/232266444-9227276e-2cf9-4082-bba3-7f6a71101d0e.png)
fullscreen on 4:3 secondary:
![image](https://user-images.githubusercontent.com/9877150/232266456-125e9599-ec62-4f4a-991b-752108dfcdd8.png)
fullscreen on 1080 secondary:
![image](https://user-images.githubusercontent.com/9877150/232266529-422669b8-f652-4519-8eab-4bdfd7e291ff.png)

**Comment by LetrixZ** [comment]
It also happens with the official web app. Don't know what it causes.

**Comment by Technetium1** [comment]
This still happens in https://github.com/th-ch/youtube-music/releases/tag/v1.20.0

**Comment by LetrixZ** [comment]
And it will keep happening until YouTube fixes it.On May 23, 2023 17:59, Technetium1 ***@***.***> wrote:
This still happens in https://github.com/th-ch/youtube-music/releases/tag/v1.20.0
