### ISSUE TITLE
Add Opus support for download + metadata

### ISSUE THREAD

**Issue by Shnxxx** [th-ch/youtube-music#112]
The app works great! I am loving it already and being used 100% of the time I am using my PC. But we can't deny that even how great the application is, there still some external problems like Internet connectivity. We lost connection for no reasons, or Google is messing us up again. The `download` plugin is great! It allows me to download the music to an `.mp3` format. But these days, there are lots of _better_ formats now that is supported widely. There's `.aac`, `.flac`, `m4a`, `.wav`, `.opus`, and such...

Opus is far superior now to `.aac` and `.mp3`, which are being widely used too. Opus is a lossy audio format yet produces far better quality and lower size compared to `.mp3`, `.aac`, and `vorbis`.

I would like to request to add an Opus support, if possible. Or at least let us choose what format what we would like to download the music for us audiophiles who wants to store the highest quality possible yet low-sized audios. Since YouTube supports already opus format. Thank you in advanced!

**Comment by th-ch** [comment]
Hey @Shnxxx, thanks for the feedback! The [latest prerelease](https://github.com/th-ch/youtube-music/releases/tag/v1.8.1) adds support for custom file extensions - using it, you can convert to opus with the following options (in `Options` > `Advanced Options`):
```json
…
"downloader": {
    "enabled": true,
    "extension": "opus",
    "ffmpegArgs": [
        "-acodec",
        "libopus",
        "-b:a",
        "128000"
    ]
},
…
```
`128000` is for 128kbits/s but you can set another bitrate - Feel free to give it a try!

Other audio formats are also possible by setting a different extension and custom FFmpeg options - a list of available encoders is available in https://github.com/ffmpegwasm/ffmpeg.wasm/issues/61 (feel free to post in this issue if you need help for another format)

**Comment by Shnxxx** [comment]
Thank you for your response! I used the code you have given and when I try to download, I am only getting 0 KB files and is still in `.mp3` extension. Any ideas? 

![image](https://user-images.githubusercontent.com/48496678/104112941-7c5d7500-532f-11eb-845b-0a48d40fe5ff.png)
![image](https://user-images.githubusercontent.com/48496678/104112945-88e1cd80-532f-11eb-9a21-0919f418155e.png)

**Comment by th-ch** [comment]
Hey @Shnxxx, thanks for the feedback! Settings look good, have you restarted after changing the setting + are you using [v1.8.1](https://github.com/th-ch/youtube-music/releases/tag/v1.8.1) (and not the latest v1.8.0)? You can check with `About YouTube Music` in the menu.
I had the same issue (0KB file) with 1.8.0, that's why I released v1.8.1 (and with `"extension": "opus"`, your final file should be a `.opus`, not a `.mp3`).

If things are still the same, then it might be another issue worth investigating!

**Comment by Shnxxx** [comment]
Thank you! After doing the fix last time, I looked at the release section but there is no new version so I did not change anything in the app except the configuration. Didn't notice there was a pre-release. My mistake 😅

The download works fine now! I am just wondering, does the download do is downloading the audio in `.mp3` and converts it to `.opus`? If yes, is it possible to download the highest possible quality of the audio? Based on a web search, YouTube Music uses `.aac` @ 256Kbps. Is it possible to download that directly then convert to `.opus`?

Also, Is it possible to add more metadata on the audio I've downloaded? For example, I just downloaded `U got that - Halogen` and the filename was only `U got that.opus`. Also, when I looked at the `details` under `properties` of the file, there were no other details except the `Name`, `Audio Sample rate`, `Length`, `Size`, and `Date`. Or is it on the YouTube Music already? They don't include metadata?

One more thing, if you are a premium user of YouTube Music, which I am not, you can stream or download `High Quality` audio by setting it up the playback settings to `High` or `Always High`. When I tried it to the app, it is the same in the browser. Is it possible in the future to allow us to stream/download high-quality music with the app like a premium?

Thank you again! I still have lots of thoughts but I think it is too much for now. 😅

**Comment by th-ch** [comment]
Hey @Shnxxx, thanks for the feedback! In [latest version 1.9.0](https://github.com/th-ch/youtube-music/releases/tag/v1.9.0), all downloaded songs should now have the artist/title metadata!
Feel free to give it a try and update the issue if necessary!

**Comment by Shnxxx** [comment]
Thank you **@th-ch**! I tried downloading a song and it works great! But is it possible to modify how the app names the filename? 
![image](https://user-images.githubusercontent.com/48496678/104802712-c3ee7000-580b-11eb-8480-cf6fa10bffd8.png)

Is it possible to add the artist too? From 'Iris.opus' to 'Iris - Goo Goo Doll.opus'.

**Comment by th-ch** [comment]
Hey @Shnxxx, thanks for the feedback!

> I am just wondering, does the download do is downloading the audio in .mp3 and converts it to .opus? If yes, is it possible to download the highest possible quality of the audio?

About quality, the highest audio quality is downloaded (seems to be 160kb/s by default) and then converted to the format you configured (so you configured opus, no intermediary mp3).

> Is it possible to add the artist too?

Sure! Added the `artist - title` file format in https://github.com/th-ch/youtube-music/commit/37289b9cbe8b585efc09f6bb5e5d105cc75775e4, it will be available in the next version!

**Comment by Crunklydunks** [comment]
I figured rather than open a new issue I would just ask here - is there some way with the new options to have it not transcode at all, just save whatever the highest quality file is that YTM is serving up? It can of course be done using youtube-dl but I would love to be able to do it from within this app, it's so convenient. Thanks!

**Comment by Richiev4** [comment]
Hi All

Could someone tell me how to add the correct code to up bit rate on MP3s, My config looks like this but I don't know which arguments to change/add

![Config](https://user-images.githubusercontent.com/89051808/225178668-28182166-d8c0-4574-862b-c368a9572845.jpg)

Many thanks
Richard

**Comment by Araxeus** [comment]
The bitrate you get is the maximum for free youtube :)

When you see youtube downloaders that gives you "320kbs" - its a lie

**Comment by Richiev4** [comment]
> The bitrate you get is the maximum for free youtube :)
> 
> When you see youtube downloaders that gives you "320kbs" - its a lie

HI, I'm a Premium subscriber, can I get a higher bit rate?

Rich

**Comment by Araxeus** [comment]
> HI, I'm a Premium subscriber, can I get a higher bit rate?

Theoretically, it's possible, but no one implemented that yet.

(I don't have a premium account and I didn't succeed in my few tries implementing this using cookie grabbing)

**Comment by Richiev4** [comment]
OK, Thanks for the info...I'll Wait, maybe it will happen

**Comment by LeonDerDr** [comment]
How do i use the ffmpegArgs to download m4a audio?

**Comment by Abhieeh** [comment]
> The app works great! I am loving it already and being used 100% of the time I am using my PC. But we can't deny that even how great the application is, there still some external problems like Internet connectivity. We lost connection for no reasons, or Google is messing us up again. The `download` plugin is great! It allows me to download the music to an `.mp3` format. But these days, there are lots of _better_ formats now that is supported widely. There's `.aac`, `.flac`, `m4a`, `.wav`, `.opus`, and such...
> 
> Opus is far superior now to `.aac` and `.mp3`, which are being widely used too. Opus is a lossy audio format yet produces far better quality and lower size compared to `.mp3`, `.aac`, and `vorbis`.
> 
> I would like to request to add an Opus support, if possible. Or at least let us choose what format what we would like to download the music for us audiophiles who wants to store the highest quality possible yet low-sized audios. Since YouTube supports already opus format. Thank you in advanced!






Hey ! have you found a way to download Flac audio files on the app???
