### ISSUE TITLE
Quits unexpectedly when downloading/converting

### ISSUE THREAD

**Issue by krigulson** [th-ch/youtube-music#1126]
- Builded app from master and for mac
- Started download ... in context menu shows 100% Downloaded and then starts Converting and then quits unexpectedly.
- 

Report:

`
Process:               YouTube Music [94239]
Path:                  /Users/USER/*/YouTube Music.app/Contents/MacOS/YouTube Music
Identifier:            com.github.th-ch.youtube-music
Version:               1.19.0 (1.19.0)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-27 10:29:07.2054 +0300
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        4DC24A09-9C62-15FC-8B0B-4C6D72E5A9EB

Sleep/Wake UUID:       B43196E4-15FD-4938-8C7A-D98633A49CDA

Time Awake Since Boot: 730000 seconds
Time Since Wake:       7080 seconds

System Integrity Protection: enabled

Crashed Thread:        34

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace ROSETTA, Code 0 

Thread 0:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff8ad11e9a8 ???
1   libsystem_kernel.dylib        	    0x7ff81dd7a5c2 mach_msg2_trap + 10
2   libsystem_kernel.dylib        	    0x7ff81dd88604 mach_msg2_internal + 82
3   libsystem_kernel.dylib        	    0x7ff81dd81635 mach_msg_overwrite + 723
4   libsystem_kernel.dylib        	    0x7ff81dd7a8a8 mach_msg + 19
5   CoreFoundation                	    0x7ff81de9400b __CFRunLoopServiceMachPort + 145
6   CoreFoundation                	    0x7ff81de92a64 __CFRunLoopRun + 1387
7   CoreFoundation                	    0x7ff81de91e7f CFRunLoopRunSpecific + 560
8   HIToolbox                     	    0x7ff827d24766 RunCurrentEventLoopInMode + 292
9   HIToolbox                     	    0x7ff827d24576 ReceiveNextEventCommon + 679
10  HIToolbox                     	    0x7ff827d242b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
11  AppKit                        	    0x7ff820f1d2f3 _DPSNextEvent + 909
12  AppKit                        	    0x7ff820f1c174 -[NSApplication(NSEvent) 
`

**Comment by krigulson** [comment]
Download and converting works perfectly in 040946ca9ee2067374f3f6417575d1bfc71931b0
So something is wrong with the latest commits where build is red and mac build fails

**Comment by Araxeus** [comment]
> Download and converting works perfectly in [040946c](https://github.com/th-ch/youtube-music/commit/040946ca9ee2067374f3f6417575d1bfc71931b0) So something is wrong with the latest commits where build is red and mac build fails

The commit you linked is the latest commit...
