### ISSUE TITLE
Ads ads ads...

### ISSUE THREAD

**Issue by colineberly** [th-ch/youtube-music#1129]
I noticed on master ads are coming thru constantly, before first song load, after 1 or 2 songs. Seems to behave like normal if there wasn't an adblocker loaded. Any way to manually remedy this?

**Comment by Lucasamiel0406** [comment]
Due to a new update on how the Adblock dependency/package works, it fixed ads in the beginning and started making the program unresponsive. In the end, a bump revert was needed.

Take a look on #1040, test it and provide feedback so we can get it soon.
