### ISSUE TITLE
Blank screen when trying to sign in

### ISSUE THREAD

**Issue by Patbott** [th-ch/youtube-music#1133]
When trying to sign in, I get the following blank screen after entering my email address.
I'm running Windows 11, using the latest release.
![image](https://user-images.githubusercontent.com/2356279/236685840-119eeb96-00df-4b7b-acca-c1f74fec1359.png)

**Comment by pavoldecky** [comment]
I had exactly the same issue with Windows 11, the latest release. 

The problem for me was most likely,  that I enabled passkeys support for my Google account. When I disable passkeys support for my Google account, the login screen was working again. At the end of this article are steps to disable it - https://www.theverge.com/23712758/google-passkey-password-2fa-security-how-to

**Comment by miner46er** [comment]
Can confirm, the problem happen when I enabled passkeys support on my Google account

**Comment by HIHIQY1** [comment]
I have the same issue, and disabling passkeys support does not fix the issue.

**Comment by lukas-burda** [comment]
> When trying to sign in, I get the following blank screen after entering my email address. I'm running Windows 11, using the latest release. ![image](https://user-images.githubusercontent.com/2356279/236685840-119eeb96-00df-4b7b-acca-c1f74fec1359.png)


> I have the same issue, and disabling passkeys support does not fix the issue.
> 
> Update: disabling "Skip password when possible" did fix it.




> I had exactly the same issue with Windows 11, the latest release.
> 
> The problem for me was most likely, that I enabled passkeys support for my Google account. When I disable passkeys support for my Google account, the login screen was working again. At the end of this article are steps to disable it - https://www.theverge.com/23712758/google-passkey-password-2fa-security-how-to

Try disabling "Skip password when possible" in https://myaccount.google.com/signinoptions/passwordoptional first then try relogging in. After you're logged in you should be able to turn the setting back on. This worked for me.
![image](https://github.com/th-ch/youtube-music/assets/49461720/de960a97-816c-4599-8a61-e178adc55b82)
