### ISSUE TITLE
TrackID for MPRIS should be unique

### ISSUE THREAD

**Issue by poly000** [th-ch/youtube-music#1140]

**Comment by QuditWolf** [comment]
If youtube-music can support the mpris tracksid and tracklist properties,
controlling and querying the queue from cli scripts and other applications will be very simple.

[mpris get tracks specification](https://specifications.freedesktop.org/mpris-spec/2.2/Track_List_Interface.html#Method:GetTracksMetadata)

queue structure export(using mpris-tracklist) might also be helpful in #1130.
If anyone has any idea how queues work, #1143
I want to help develop the queue features.

thx

**Comment by JellyBrick** [comment]
implemented at 845711510581f4603ec863825404321b15d5a444
