### ISSUE TITLE
Audio distorted when using "skip-silences"

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [th-ch/youtube-music#1141]
This does not happen on the last release
Hardware: MacBook Air M1, 8GB
OS: macOS 13.3.1 (a) (22E772610a)

https://github.com/th-ch/youtube-music/assets/30368284/c621fd02-33a4-4f80-b4d3-249b2f4096d5

**Comment by ChefKissInc** [comment]
Update: Disabling the "Skip Silences" plug-in fixes it.

**Comment by FQQD** [comment]
Happened to me today too

Cachy OS Linux (Arch Linux)
newest youtube music version from aur

**Comment by SomeAspy** [comment]
I can also reproduce this on Arch Linux with the latest AUR push

**Comment by jwhite1gh** [comment]
Reproduced issue after updating tody 3/23/23. Did not test prior to update. 2018 MacBook Pro 15. MACOS 13.1 (22C65). To test if it was isolated to the app, I used the in-app "download" to dnl the current distorting song. Played the file in Apple Music with no audio issue. Disabled "skip silences" plugin, restarted app. Appears to have resolved the issue.

**Comment by aranwe** [comment]
Repro on Windows 10 22H2 (v 1.20.0). 
The volume was boosted (compared to the same source in browser) so that it was clipping - distorting the sound in progress.

**Comment by techgamers2** [comment]
> Update: Disabling the "Skip Silences" plug-in fixes it.

but i also need skip silence feature :(

**Comment by check-m4te** [comment]
Ohh so that's why I was hearing it so saturated

**Comment by Hasselshoff** [comment]
Also just ran into this.  It was triggering at the _same_ spots in the _same_ tracks.  Eventually the pattern led me to realize that in my recent OS reinstall I had enabled the "skip-silences" plugin, which was making the difference.

**Comment by ASTRON42** [comment]
It happened to me today, just to notify you. I disabled the skip-silences plugin and it worked instant. So it is a bypass for now, but not of course not a solution.

**Comment by inson1** [comment]
same here :/ Windows 10, v3.0.2
