### ISSUE TITLE
Version 1.20.0 ARM64 build broken on M2 macOS Ventura 13.3.1?

### ISSUE THREAD

**Issue by Nezteb** [th-ch/youtube-music#1145]
My specs:
<img width="208" alt="Screenshot 2023-05-18 at 5 50 49 AM" src="https://github.com/th-ch/youtube-music/assets/3588798/a668107a-a838-444e-92eb-f7404af5ccf2">

When I right click on the app in my applications directory and click "open", I get this every time:
<img width="265" alt="Screenshot 2023-05-18 at 5 50 03 AM" src="https://github.com/th-ch/youtube-music/assets/3588798/c3f2c842-9a60-4f46-a7e7-2b810f1f9a24">

The release I tried: I was testing out https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-1.20.0-arm64.dmg

If I try the non-ARM version, it works fine but is presumably being run through Rosetta: https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-1.20.0.dmg

**Comment by GOZZZO** [comment]
run    xattr -cr /Applications/YouTube\ Music.app    in Terminal
