### ISSUE TITLE
1.20.0 Load Time

### ISSUE THREAD

**Issue by DrSuSE** [th-ch/youtube-music#1147]
Let me know how I can help, but 1.20.0 takes a really long time to load vs 1.19.0 and earlier.  For now I have downgraded and things are fine again.

In all cases I am using the installed/setup version.

I tried upgrading and fresh installs.
I did all the normal, reboot my PC type little things.

Windows 11 Pro
32GB RAM
2TB M.2 SSD

1.20.0 does eventually load, but 1.19.0 (and earlier) takes about 1.6 seconds to load from shortcut click.  1.20.0 takes about 45 seconds to load up and even then is not really ready to be used for another 15-30 seconds.

**Comment by Michtarr** [comment]
Also, 1.20 seemed much more laggy than before, hovering over songs is slow to react, minimizing/maximizing songs in queue takes like 4 seconds or more. I downgraded to 1.19 for now as well.

**Comment by 10drck** [comment]
Ran into the same issues, in addition to some songs sounding poor in quality. Reverting to 1.19.0 for the time being.

**Comment by Knigge111** [comment]
Same and more problems here. 1.20 spontaneously skip songs. Normally i use the setup version but to test i use the portable 1.20 also. Same problem. I use WingetUI to install 1.19. After the installation and the start of 1.19 i get the message to update to 1.20 via download. Then is all messed up. The installer starts but i think then happend a rollback and the window closed.

**Comment by MartinX3** [comment]
1.20 lags like hell.
I had the same problem in the past with some version of this app.
But 1.19 was definitely much faster than 1.20 now.
Feels like an accumulating memory leak.

**Comment by Sylux6** [comment]
Yup same here, looks like I'll need to downgrade as well. 
1.20 is a mistake

**Comment by Sigi3012** [comment]
Also having the same low performance issues, I'll probably downgrade to 1.19 for now

**Comment by QuditWolf** [comment]
I think I this is the relevant error:
`[2123724:0520/095910.156424:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
`

Disabling hardware acceleration seems to be a fix...
I disabled hardware acceleration from,

menu-> options -> advanced options -> disable hardware acceleration 

and this error disappeared and the performance issues and lags were gone.

![image](https://github.com/th-ch/youtube-music/assets/81188667/46b3d736-0306-47d9-91bd-6771358ef4e6)

**Comment by techgamers2** [comment]
yes 1.20 uses more sys resources and even getting sound distortion when playing music

**Comment by jang-geon** [comment]
same problem

**Comment by Araxeus** [comment]
Can anyone confirm if this is happening with specific plugins enabled or even with no plugin enabled?

**Comment by Knigge111** [comment]
> Can anyone confirm that this problem occurs with certain plugins enabled or even without plugins enabled?

No, this is not the problem with the plugins. I test a lot of configurations took the 1.19 as reference. Disabled hardware acceleration solves the problem only for a view minute. Version 1.19 took all enabled plugins as it is nothing.

**Comment by techgamers2** [comment]
> > Can anyone confirm that this problem occurs with certain plugins enabled or even without plugins enabled?
> 
> No, this is not the problem with the plugins. I test a lot of configurations took the 1.19 as reference. Disabled hardware acceleration solves the problem only for a view minute. Version 1.19 took all enabled plugins as it is nothing.

all plugins enabled!? ....it may be nothing to u but for low end users it takes a toll . youtube music web app instead is  givin better performance now and v1.19 vs v1.20 main diff is plugins updates only .. they updated adblocker plugin tht ws the main change so it is the problem with plugins only and for Disabled hardware acceleration tht i hav turned off from previous version it doesnt makes any difference

**Comment by TJW65** [comment]
> Can anyone confirm if this is happening with specific plugins enabled or even with no plugin enabled?

Currently don't have the time to test every plugin indiviudally - but turning all of them off and restarting the application definetly sped up the response time to clicks and load times of songs significantly. Mind you that this is only based on 10 mins of before and after experimenting with skipping and loading random playlists and albums.

That being said: i've experienced none ofd these issues in 1.19 with the same plugins and settings. Seems like some addon update in 1.20 makes the whole app very unresponsive to my inputs. Will propbably go back to 1.19 auswell - thanks for all the work though, still higly appreciated.

**Comment by davydof** [comment]
disable the `adblocker` option is helped
![image](https://github.com/th-ch/youtube-music/assets/10529679/070f2909-7aa8-41c6-b6e6-4cf98ddac8fa)

**Comment by DereC4** [comment]
If you guys could, use the windows performance monitor to graph the memory usage over, say, 20 minutes or something, or try to see which plugins cause certain reactions when disabled/enabled. 

![image](https://github.com/th-ch/youtube-music/assets/53978637/2ff96c3b-df93-42c8-87c6-013338caae0a)

**Comment by ajaxnotmeta** [comment]
did 1.20 has some Memory leak somewhere?
i just noticed the lag recently too

**Comment by DereC4** [comment]
> did 1.20 has some Memory leak somewhere? i just noticed the lag recently too

Check the adblock fix mentioned in multiple issues threads

**Comment by LetrixZ** [comment]
Why is adblocker enabled by default?

**Comment by DereC4** [comment]
> Why is adblocker enabled by default?

Apologies for the delay I've been visiting Taiwan lately. Adblocker is probably enabled by default because it's a pure upside for users and usually the main reason they get this third party app. Again that's my view but I'm not a main developer
