### ISSUE TITLE
[Bug Report?] Downloader has stroke after 150-200th song

### ISSUE THREAD

**Issue by xamionex** [th-ch/youtube-music#1149]
OS: Windows 11 (Tiny11)
YTM: 1.20

![image](https://github.com/th-ch/youtube-music/assets/57235791/cd72ed35-9fbe-4f1c-9662-a17bfcf89d95)
Will try getting all the errors but this is just spam at this point, would like it to log instead and not do pop-ups my pc is barely running when this happens if I don't intervene in time

You could also do a pop-up window but have it log inside it and not open subsequent pop-ups which would be way more performant

**Comment by xamionex** [comment]
```
Error: First argument should be an instance of ArrayBuffer or Buffer in Vexento - Return Of The Raver

TypeError The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined in Vexento - Return Of The Raver

Error: ffmpeg.wasm can only run one command at a time in 913060913158aa1d1bfad8f33ed6a798b28aOe78d16c2d3da12dOc2fe3c9db64

TypeError The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined in Coldplay - Viva La Vida
```

All I got so far

**Comment by TaylanTatli** [comment]
I'm having the same problem on Linux.
