### ISSUE TITLE
No "About" screen?

### ISSUE THREAD

**Issue by TheArgentinian** [th-ch/youtube-music#1153]
I can't find it on the options menus. How can I know which version am I on?

**Comment by Sigi3012** [comment]
If you're using scoop you can do `scoop info youtube-music` otherwise go to config.json in Options > Advanced options > config.json then scroll to the bottom 
![image](https://github.com/th-ch/youtube-music/assets/50233886/59b95cdf-242f-49b2-b87f-4fc73d5c1e9e)

**Comment by TheArgentinian** [comment]
> If you're using scoop you can do `scoop info youtube-music` otherwise go to config.json in Options > Advanced options > config.json then scroll to the bottom ![image](https://user-images.githubusercontent.com/50233886/239772843-27734bcc-1648-4985-84f6-c3c81e3592e2.png)

I don't even know what a scoop is.

**Comment by lukas-burda** [comment]
try download again https://github.com/th-ch/youtube-music/releases

**Comment by JustOptimize** [comment]
> I don't even know what a scoop is.
Scoop is a command-line package manager (A program that allows users to install, update, and uninstall apps from the command prompt. If you don't use it / don't know what it is, it's not required to check what version you are using and you can easly follow the steps below.

> I can't find it on the options menus. How can I know which version am I on?
As @Sigi3012 explained correctly navigate onto the youtube-music app, click on options in the top left and follow the path written in his message.

If this solves the issue please close this 👍🏻

**Comment by TheArgentinian** [comment]
> 

I shouldn't need to install anything or use a command line to see something as basic that _every_ program has. So, no, issue not solved.

**Comment by TheArgentinian** [comment]
> > I don't even know what a scoop is.
> > Scoop is a command-line package manager (A program that allows users to install, update, and uninstall apps from the command prompt. If you don't use it / don't know what it is, it's not required to check what version you are using and you can easly follow the steps below.
> 
> > I can't find it on the options menus. How can I know which version am I on?
> > As @Sigi3012 explained correctly navigate onto the youtube-music app, click on options in the top left and follow the path written in his message.
> 
> If this solves the issue please close this 👍🏻

I shouldn't need to install anything or use a command line to see something as basic that every program has. So, no, issue not solved.

**Comment by JustOptimize** [comment]
> I shouldn't need to install anything or use a command line to see something as basic that every program has. So, no, issue not solved.

Please read the entire message carefully, don't just read the beginning.

ESPECIALLY THIS PART:
As @Sigi3012 explained correctly navigate onto the youtube-music app, click on options in the top left and follow the path written in his message.

**Comment by TheArgentinian** [comment]
> > I shouldn't need to install anything or use a command line to see something as basic that every program has. So, no, issue not solved.
> 
> Please read the entire message carefully, don't just read the beginning.
> 
> ESPECIALLY THIS PART: As @Sigi3012 explained correctly navigate onto the youtube-music app, click on options in the top left and follow the path written in his message.

ok, I found it. I'm on 1.20.0

**Comment by JustOptimize** [comment]
@TheArgentinian close the issue then

**Comment by TheArgentinian** [comment]
> @TheArgentinian close the issue then

"please and thank you" first.

**Comment by JustOptimize** [comment]
> "please and thank you" first.

You're right, "please and thank you" is a courteous way to ask for something. I appreciate your reminder. Now, let's close the issue, please and thank you.

**Comment by JustOptimize** [comment]
@TheArgentinian, this is a little reminder to close the issue

**Comment by TheArgentinian** [comment]
> @TheArgentinian, this is a little reminder to close the issue

I don't like the snarky comment you made before

**Comment by Sigi3012** [comment]
> > @TheArgentinian, this is a little reminder to close the issue
> 
> I don't like the snarky comment you made before

please stop being childish and close this issue and move on thank you

**Comment by TheArgentinian** [comment]
> > > @TheArgentinian, this is a little reminder to close the issue
> > 
> > 
> > I don't like the snarky comment you made before
> 
> please stop being childish and close this issue and move on thank you

I'm waiting for an apology.

**Comment by JustOptimize** [comment]
I already wrote an apology here https://github.com/th-ch/youtube-music/issues/1153#issuecomment-1616996083

**Comment by TheArgentinian** [comment]
> I already wrote an apology here [#1153 (comment)](https://github.com/th-ch/youtube-music/issues/1153#issuecomment-1616996083)

And you added an unnecessary  passive-agressive remark.

**Comment by Sigi3012** [comment]
t

> > I already wrote an apology here [#1153 (comment)](https://github.com/th-ch/youtube-music/issues/1153#issuecomment-1616996083)
> 
> And you added an unnecessary passive-agressive remark.

there is no need for the debate, please close this issue

**Comment by JustOptimize** [comment]
I hope this message finds you well. I wanted to reach out and apologize for the passive-aggressive comment I made earlier. Upon reflection, I realize that my words were inappropriate and disrespectful, and I deeply regret my behavior.

I understand that my comment may have caused you discomfort or hurt, and for that, I am truly sorry. It was never my intention to be unkind or to create any tension between us. I take full responsibility for my words and their impact, and I sincerely apologize for any distress I may have caused.

Can we now move on with our lives?
Please and thank you,
JustOptimize

**Comment by TheArgentinian** [comment]
> I hope this message finds you well. I wanted to reach out and apologize for the passive-aggressive comment I made earlier. Upon reflection, I realize that my words were inappropriate and disrespectful, and I deeply regret my behavior.
> 
> I understand that my comment may have caused you discomfort or hurt, and for that, I am truly sorry. It was never my intention to be unkind or to create any tension between us. I take full responsibility for my words and their impact, and I sincerely apologize for any distress I may have caused.
> 
> Can we now move on with our lives? Please and thank you, JustOptimize

I appreciate this post and I hope it's not sarcasm. 

Closing and moving on.
