### ISSUE TITLE
Tray pause/play functionality stopped working in 1.20

### ISSUE THREAD

**Issue by Destroy666x** [th-ch/youtube-music#1157]
Latest version of youtube-music
Latest Windows 10

Options -> Tray -> Play/Pause on click is selected

I'm trying to click on tray icon and that doesn't do what it's supposed to - it just brings the notification up and you can play/pause there. The status of the notification can be incorrect because of this bug BTW, as in showing "pause" when it's paused because the app thinks music restarted playing while it didn't.

I tried:
- restarting the app (play works only on 1st click after that)
- turning the option off and back on
- restarting PC

Nothing helped.

**Comment by Destroy666x** [comment]
@JellyBrick ?

**Comment by JellyBrick** [comment]
> @JellyBrick ?

This issue was resolved. (a859b27)
2.0.0 has not yet been released, so please wait until it is.

**Comment by JellyBrick** [comment]
[v2.0.0](https://github.com/th-ch/youtube-music/releases/tag/v2.0.0) released!

**Comment by Destroy666x** [comment]
Nice!
