### ISSUE TITLE
Memory leak after continuous useage

### ISSUE THREAD

**Issue by dylanh724** [th-ch/youtube-music#1158]
The mem leak doesn't take long to show; give it a couple hours to see the RAM start rising. Leave music playing all day or overnight and you'll come back to a frozen computer (or YT music will crash).

This is an ongoing issue with native YT music, actually. Can we, perhaps, _auto-restart the app after x amount of time_ as a workaround?

Related: 
* https://github.com/th-ch/youtube-music/issues/797
* https://github.com/th-ch/youtube-music/issues/322
* https://github.com/th-ch/youtube-music/issues/295
* https://github.com/th-ch/youtube-music/issues/958
* https://www.reddit.com/r/YoutubeMusic/comments/vhvark/web_app_still_has_a_memory_leak/ 
* https://support.google.com/youtubemusic/thread/69139975/web-ytm-leaks-memory-and-forces-me-to-reload-the-tab-every-single-day?hl=en

**Comment by DereC4** [comment]
Perhaps an option can fix that

**Comment by TheArgentinian** [comment]
Very fucking annoying bug that makes songs stutter and skip to another one. It's the CPU % that spikes according to Process Manager. Pausing fixes for a couple of songs and then the issues start again.

**Comment by danir-de** [comment]
Are you all using Lyrics Genius? Maybe #1182 is related then.

**Comment by chadxzs** [comment]
I recently installed the app and am using last-fm plugin, navigation, and exponential volume and am experiencing this issue.

**Comment by TheArgentinian** [comment]
I have last-fm enabled, too. The rest is all what comes by default.

**Comment by DereC4** [comment]
> I recently installed the app and am using last-fm plugin, navigation, and exponential volume and am experiencing this issue.



> Reference in new iss

Did you happen to try the new fix suggested by changing adblock to in-player? Not sure why but many users are reporting it works and it seems to fix mine too.

**Comment by snowy-egret** [comment]
@DereC4
I faced the same problem, but using your method solved it.
Thanks a lot!

**Comment by chadxzs** [comment]
@DereC4 I missed that suggestion, will give it a try.

**Comment by chadxzs** [comment]
Much better experience today. I actually don't really need any kind of spam filter because I'm a YTM subscriber. Thanks for the tip @DereC4 !

**Comment by xdpirate** [comment]
> > I recently installed the app and am using last-fm plugin, navigation, and exponential volume and am experiencing this issue.
> 
> > Reference in new iss
> 
> Did you happen to try the new fix suggested by changing adblock to in-player? Not sure why but many users are reporting it works and it seems to fix mine too.

This worked for me as well, thanks for this!

**Comment by DereC4** [comment]
@TheArgentinian , check the adblock fix mentioned above. Run it for a couple of minutes of a long playlist you have; hope it helps!

**Comment by dylanh724** [comment]
@th-ch  - above shows workarounds, not solutions. This shouldn't be closed unless the user can select any option they want without a memory leak, workaround or no workaround.
