### ISSUE TITLE
"Verify it’s you" not loading

### ISSUE THREAD

**Issue by FireNation323** [th-ch/youtube-music#1161]
after pressing next it doesn't load and I cant log in
![Screenshot 2023-05-26 165916](https://github.com/th-ch/youtube-music/assets/81137631/1f27fe58-725d-4fca-9eff-5319ce669d62)

**Comment by simonbcn** [comment]
```
Arch Linux
youtube-music-bin 1.20 (installed from AUR: https://aur.archlinux.org/packages/youtube-music-bin)
```
Same problem.

**Comment by simonbcn** [comment]
I have deleted `.config/YouTube Music/` folder and then it allows me to enter the email but when I click next, where I should put the password, it remains blank like the screenshot of the first message.

**Comment by dianqing99** [comment]
I'm facing the same problem with (YouTube-Music-Setup-1.20.0.exe) release as well

**Comment by Evil-Dragon** [comment]
Try disabling "Skip password when possible" in https://myaccount.google.com/signinoptions/passwordoptional first then try relogging in. After you're logged in you should be able to turn the setting back on. This worked for me.

**Comment by simonbcn** [comment]
> Try disabling "Skip password when possible" in https://myaccount.google.com/signinoptions/passwordoptional first then try relogging in. After you're logged in you should be able to turn the setting back on. This worked for me.

Thanks, this works for me.

**Comment by lukas-burda** [comment]
> Try disabling "Skip password when possible" in https://myaccount.google.com/signinoptions/passwordoptional first then try relogging in. After you're logged in you should be able to turn the setting back on. This worked for me.

Thanks. Works 100%

**Comment by CattopyTheWeb** [comment]
> Try disabling "Skip password when possible" in https://myaccount.google.com/signinoptions/passwordoptional first then try relogging in. After you're logged in you should be able to turn the setting back on. This worked for me.

I just had the same problem and this fixed it! Thanks

**Comment by lukas-burda** [comment]
@th-ch can finish this issue
