### ISSUE TITLE
New version Lag (1.20)

### ISSUE THREAD

**Issue by LoganSandivar** [th-ch/youtube-music#1162]
Application lags on the following:

-Opening of application.
-Song selections. 
-Buffering through most of songs notices up to 10 songs. I verified it is not my Bandwidth as another user has the same problem.
- Any control function used.

Remedies tried:
-Reduced quality of music videos. (does not seem to affect the issue)
-Task kill and restart. (works 95% of the time)
-Reinstall of application.(seemed to fix the issue for first use after install. closed application  and opened issue persists)

Hopefully this is useful information just wanted to add to this project in any way since I am an avid user :)

**Comment by ramar1010** [comment]
sameeee

**Comment by holy-filipp** [comment]
Confirm.

**Comment by KombatChief** [comment]
Yeah I have had crazy amount of lag with the new update.  If it lags for long enough the songs start to skip in the middle of them

**Comment by psyonara** [comment]
Experiencing the same.

**Comment by TJW65** [comment]
I'm going to copy my response to a another issue opened about two weeks ago - titled something about the lines of 1.20 loading times - complaining about the same issue.


I could seemingly figure out a solution for my system.
The problem for me appears to be the ad-blocker via blocklists.
Setting it to "in player" makes the experience way smoother for me.
This only a quick observation for now though. Would need the others with the same problem in 1.20 to check that.
Can't remember the option to switch between "blocklists" and "in player" for 1.19 anyway. Was "in player" the old option, used before 1.20? The blocklist was the deafault for me in 1.20 though.
Where are the differences between these settings?

**Comment by NotMithical** [comment]
I had the same issue. Switched to in-player adblocking several days ago and have had no performance issues since.

**Comment by Nyxlyzers** [comment]
Same issue in the newest version, downgraded to 1.19.0 and no issues so far

**Comment by Nyxlyzers** [comment]
okay folks, maybe I discovered the source of the problem. The lag maybe happens when you install the YT Music with Winget, instead of using the Scoop Installer

**Comment by Knigge111** [comment]
> okay folks, maybe I discovered the source of the problem. The lag maybe happens when you install the YT Music with Winget, instead of using the Scoop Installer

I think you have found a solution! After 30 minutes of music playing, no lag and no skip. Many thanks! 

P.S.: To change the blocklist helps only for a view minutes.

**Comment by KombatChief** [comment]
> okay folks, maybe I discovered the source of the problem. The lag maybe happens when you install the YT Music with Winget, instead of using the Scoop Installer

If this is the case, it also happens with chocolatey

**Comment by rinfiyks** [comment]
I've been having the same issue with aur/youtube-music-bin. Turning off the adblock plugin completely fixes it for me.

**Comment by holy-filipp** [comment]
> okay folks, maybe I discovered the source of the problem. The lag maybe happens when you install the YT Music with Winget, instead of using the Scoop Installer

I have the same issues but I installed YM using scoop.

**Comment by Nyxlyzers** [comment]
> Changing the adblock plugin from blocklist to player helps me.
> 
> I don't use Winget or Scoop. I just install it with AUR in Arch Linux.

i'm gonna test it and reply to you if it works

**Comment by LoganSandivar** [comment]
> I had the same issue. Switched to in-player adblocking several days ago and have had no performance issues since.

After switching to the in player ad blocker it has resolved all my issues. Thank you to all for the contribution to my issue :)

**Comment by autoferrit** [comment]
> I'm going to copy my response to a another issue opened about two weeks ago - titled something about the lines of "1.20 loading times" - complaining about the same issue.
> 
> I could seemingly figure out a solution for my system. The problem for me appears to be the ad-blocker via blocklists. Setting it to "in player" makes the experience way smoother for me. This only a quick observation for now though. Would need the others with the same problem in 1.20 to check that. Can't remember the option to switch between "blocklists" and "in player" for 1.19 anyway. Was "in player" the old option, used before 1.20? The blocklist was the deafault for me in 1.20 though. Where are the differences between these settings?

This solved it for me on windows, using the normal setup installer. last one was `YouTube-Music-Setup-1.20.0.exe`

No more lag after fixing the adblock setting to in player

**Comment by Typ33** [comment]
@TJW65 Thank you, [this solution](https://github.com/th-ch/youtube-music/issues/1162#issuecomment-1567498209) did indeed worked.

**Comment by Jarpiino** [comment]
How do I open settings panel to change the adblocker when right clicking on the window doesn't work on my second computer??

**Comment by GoudronViande24** [comment]
What is the difference between the two adblock modes?

The in-player block reduces lag, if it's similar in functionalities to the other one, why not make it the default?

**Comment by DereC4** [comment]
> > okay folks, maybe I discovered the source of the problem. The lag maybe happens when you install the YT Music with Winget, instead of using the Scoop Installer
> 
> I have the same issues but I installed YM using scoop.

Wait you guys use command line installers

**Comment by haloflooder** [comment]
I had this issue on windows and I used the installer. I was able to fix the lag by removing the ad blocker plugin since I have YT premium anyways lol
