### ISSUE TITLE
 YouTube-Music-1.20.0-arm64.dmg "youtube music.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by joebywan** [th-ch/youtube-music#1165]
Mac M1 Pro on Ventura 13.3.1 (a).

Steps to reproduce:

1. Download the file from: https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-1.20.0-arm64.dmg
2. Double click it.
3. Drag Youtube Music into the Applications folder in the window that pops up
4. Goto Finder>Applications and try to run Youtube Music.

Have done a shasum -a 512 <filename> and receiving this as the sha: b820e765a031c2dec7eef707e56425e6ff30cc0498aafa2e0c69bf004587462e26e83b3d0c606700ac3410a4141a19ad5939873e1bf9ee1881af49a5204ee707

**Comment by matejnevlud** [comment]
@joebywan this should help: 

`xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`

**Comment by joebywan** [comment]
Thanks, that worked.
