### ISSUE TITLE
[Feature Request] Add a plugin to replace the share button with a song.link URL

### ISSUE THREAD

**Issue by SomeAspy** [th-ch/youtube-music#1167]
Many of my friends don't use YouTube music and they would prefer a link to their own service. This site does this automatically when given a share link of any service.

The API docs: https://linktree.notion.site/API-d0ebe08a5e304a55928405eb682f6741
Home Page: https://odesli.co/

Example:
https://music.youtube.com/watch?v=wuJIqmha2Hk&feature=share
turns into
https://song.link/y/wuJIqmha2Hk

![image](https://github.com/th-ch/youtube-music/assets/33640860/06a3f19c-91fd-404d-a88d-9ee4f70f411e)

**Comment by ArjixWasTaken** [comment]
And what about playlists?

**Comment by SomeAspy** [comment]
I suppose that will simply not be a feature for the time being, or someone could develop an external API to deal with that

**Comment by SomeAspy** [comment]
Closed, as I don't feel comfortable keeping a feature request open when I have no intent of PRing it in myself :P
