### ISSUE TITLE
Discord Rich presence won't work properly or be shown properly while while playing a song etc.

### ISSUE THREAD

**Issue by Milkkolaj** [th-ch/youtube-music#1173]
Extra Information:
Yt music client .deb packages
Discord Client .deb packages

**Comment by DrShahinstein** [comment]
My listening activity doesn't show up either.

**Comment by ariyin** [comment]
i can only get "youtube music" with the time spent on the app displayed

**Comment by CyfunZuZu** [comment]
I have no rich presence at all. I tried following @Zo-Bro-23's guide as well as trying the prebuilt release he linked later on in https://github.com/th-ch/youtube-music/issues/895

Neither worked.
