### ISSUE TITLE
The album cover is not showing

### ISSUE THREAD

**Issue by sinedrock** [th-ch/youtube-music#1177]
Any solution? I've already reset, installed again and it still continues like this!

![Captura de tela 2023-06-16 114100](https://github.com/th-ch/youtube-music/assets/136827719/4b5f5314-b4d0-4f4f-8dda-311e70f73129)

**Comment by stoicpenguin2234** [comment]
same

**Comment by Vixifiary** [comment]
this seems to be a recent issue. did youtube change something again? none of the album art appears in any songs while your playing music. and its only when playing music.

**Comment by pinkkuh** [comment]
a quick solution is provided in #1194.

**Comment by Vixifiary** [comment]
yeah it seems youtube is doing a complete rewrite of youtube music. eventually these temp fixes will wind up breaking completely. i do hope the devs come back to update it before it dies.

**Comment by Technetium1** [comment]
Disabling `bypass-age-restrictions` temporarily also fixed for me. If it helps anyone debug or find this issue, I noticed the video class changed to `yt-playability-error-supported-renderers` when enabled.
