### ISSUE TITLE
Lyrics Genius makes the app lag 

### ISSUE THREAD

**Issue by danir-de** [th-ch/youtube-music#1182]
Using Lyrics Genius has become a very big issue, when using the app with large playlists.

The longer you're playing inside a long playlist (1000+ tracks), the more unresponsive the UI and audio-playback becomes, even resulting in playback issues, once the UI lag becomes to big (8+ seconds to react on click anywhere).

Disabling Lyrics Genius and restarting the app completely fixes the issue.
Another temp fix, that allows to further use Lyrics Genius, is to restart the app every 20 minutes, since the lag is minimal after a restart and slowly becomes worse.

**Comment by DereC4** [comment]
Appears it's been a native yt music issue for a while, but maybe the lyrics genius plugin makes it worse. 

I'm interested in this problem since it has affected me too even before we developed the new translation options, so I shall test around with it when I have time.

**Comment by DereC4** [comment]
Could you provide any steps to recreate the problem, and perhaps logs and screenshots? Maybe as it gets more laggy compare task manager memory usage and see if it's greater than before/spiking.

**Comment by DereC4** [comment]
![image](https://github.com/th-ch/youtube-music/assets/53978637/db6ba79b-ecfe-42c6-a473-c2d57493bd78)

I dunno I've been running the thing for 20 minutes now with the lyrics genius plugin and the memory appears to be relatively the same besides a spike when I opened up the screen. I'll try for longer and let it build up

**Comment by DereC4** [comment]
Check #1187

**Comment by JellyBrick** [comment]
Fixed at https://github.com/th-ch/youtube-music/commit/375fb082f0bff90cd41d3693098d826c8a2420ae
