### ISSUE TITLE
Navigation plugin buttons are missing in the "new" youtube music

### ISSUE THREAD

**Issue by jkrei0** [th-ch/youtube-music#1186]
YouTube music recently updated its interface, at least for me - I've seen other people post recent screenshots of the old interface, so I'm probably part of some A/B test group.

This change has cause the `navigation` plugin's buttons to disappear.

(current behavior - no nav arrows)
![image](https://github.com/th-ch/youtube-music/assets/51007423/82a6be56-a717-456a-86e7-3aecb1c8a0f3)

(expected behavior - with nav arrows)
![image](https://github.com/th-ch/youtube-music/assets/51007423/a58dfd6e-352e-4198-8d6e-989383d22d2a)

**Comment by DereC4** [comment]
That is odd, my UI looks different as well

![image](https://github.com/th-ch/youtube-music/assets/53978637/48ac3435-bde4-4cec-9d09-cb8915780914)
