### ISSUE TITLE
Adblock mode causes memory issues; "In-Player" fixes memory leakage

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#1187]
## The Problem

Recent memory accumulation events have been reported. One solution working for me and a majority of users was to change the Adblock plugin mode to "In-Player" from "with blocklists"

![image](https://github.com/th-ch/youtube-music/assets/53978637/8c9f46aa-0cc9-4252-bfcd-1b294cea5bc3)

## My Findings

After running multi-hour tests with the Windows Performance Monitor, RAM usage seems to be stable (fig 1) using "in-player", but sees an accumulation of memory over time (fig 2) using "with blocklists". These findings correspond with the smooth experience while using "in-player" but laggy experience (after a period of time) using "with blocklists".

### fig 1.

![Performance Monitor 6_30_2023 04_02_24 PM](https://github.com/th-ch/youtube-music/assets/53978637/125eb175-fd8c-45a5-be20-8cdbf6824e68)

### fig 2.

![Performance Monitor 6_30_2023 04_02_28 PM](https://github.com/th-ch/youtube-music/assets/53978637/2b285a78-b41d-4012-a290-0946f6b3499c)

Related #1158 , #1147 , #1162

**Comment by th-ch** [comment]
👋 Hey @DereC4, thanks for reporting! Regarding the linked issues, is the memory leak only lead to the ad plugin and the "with blocklists" setting? One idea that comes to mind would be switching the default to "in player" if it can help people

**Comment by DereC4** [comment]
Oops sorry for the delay I've been on the other side of the globe, but it seems that the in player default would help fix a lot. Could you explain how the blocklists works and how it may be contributing to a memory leak? I thought it would just load in a predefined list and check it for every song. 

> 👋 Hey @DereC4, thanks for reporting! Regarding the linked issues, is the memory leak only lead to the ad plugin and the "with blocklists" setting? One idea that comes to mind would be switching the default to "in player" if it can help people

**Comment by mistermatrix24** [comment]
Disabling adblocker all together has greatly improved performance. I'm curious, I would only need adblocker if I didn't have a paid YT Music subscription right?

**Comment by DereC4** [comment]
> Disabling adblocker all together has greatly improved performance. I'm curious, I would only need adblocker if I didn't have a paid YT Music subscription right?

Youtube Music Premium allows you "to listen to music ad-free, offline & with your screen off" so that makes sense

**Comment by paulo-roger** [comment]
Just had a memory leak problem, I am on Linux Manjaro. I am gonna test without the adblocker to see if this fixes the issue.

**Comment by DereC4** [comment]
neat
