### ISSUE TITLE
no video or album cover 

### ISSUE THREAD

**Issue by stoicpenguin2234** [th-ch/youtube-music#1194]
since the update theres no album cover or video

**Comment by stoicpenguin2234** [comment]
awesome thanks that worked for me i just noticed that the lyrics are a little messed up

**Comment by FQQD** [comment]
yes, worked fro me as well. weird.

**Comment by Zastando** [comment]
This is not a "viable" fix, therefore the issue should technically still be open.

**Comment by FriskTemmie** [comment]
> Disabling `bypass-age-restrictions` solves this issue on my end.

why the fuck does that work?
