### ISSUE TITLE
Romanized Lyrics did not working

### ISSUE THREAD

**Issue by NantaArthur123** [th-ch/youtube-music#1195]
Am I missing something?
![image](https://github.com/th-ch/youtube-music/assets/109583020/41d395a4-4d8d-4582-a67f-319527768852)
I tried to turn on the settings, then restarted the apps but nothing work.

**Comment by HeyItsPat01** [comment]
I have the same issue, did you ever find a solution?

**Comment by JellyBrick** [comment]
It is the intended behaviour that the Genius-Lyrics plugin does not work with tracks of type "song".

See the related PR: #1092

**Comment by DereC4** [comment]
(it's being fixed dw!)
