### ISSUE TITLE
No image in player

### ISSUE THREAD

**Issue by JuanMC45** [th-ch/youtube-music#1207]
Sup, seen a few issues already, but for me it's weirder. Out of the box the image **never** appeared, with default configs. No matter what I did, it never really worked, idk why. Not fully related to #1196 and the other issues since bypass-age-restriction doesn't do anything to it. Hell, even with no plugins enabled (literally, not even adblocker) it doesn't work lol

Screenshot is here: 
![image](https://github.com/th-ch/youtube-music/assets/32444482/28cecc79-db8c-408a-907b-cdc0473b8cf9)

**Comment by DaveThuet** [comment]
Same Problem, no Video Image into Player :(

**Comment by MadMarco64** [comment]
Same issue, no video image, tried updating and resetting app configs but still the same thing :(
![image](https://github.com/th-ch/youtube-music/assets/115125120/b7dd86b3-e5d1-437d-83a9-a3159db77c9c)

**Comment by talmax1124** [comment]
> For me is temporaly Solved: Uncheck = **Bypass-Age-Restriction**

Had the same issue. This fixed it. Thanks!
