### ISSUE TITLE
extreme lag in the client

### ISSUE THREAD

**Issue by fefucho** [th-ch/youtube-music#1212]
the ui is extremely laggy, music plays but when it lags sometimes it just skips songs, its started randomly

**Comment by VelikiySebas** [comment]
same with latest version of client, so i downgraded it to 1.19

**Comment by wraskk** [comment]
Same here on 1.20.0 with macOS Ventura. The app soft locks with input lag and it will cause songs to pause for ~30 seconds when interacting with the app. Sometimes the problem clears up for a while but I haven't found a pattern. I tried disabling hardware acceleration, no difference. 

Addons enabled:
```
adblocker
bypass-age-restrictions
exponential-volume
downloader
last-fm
navigation
```

**Comment by AuracleTech** [comment]
Same here I came here to say this exact issue, not sure what is happening but this version is not it.
I experience heavy lag and many new issues

**Comment by din-grogu** [comment]
See #1208 , solved the issue for me on Arch version.
