### ISSUE TITLE
How to Use Downloader Plugin?

### ISSUE THREAD

**Issue by Stunner** [th-ch/youtube-music#122]
I can't seem to find the download option anywhere. Is there any documentation for it?

**Comment by th-ch** [comment]
Hey @Stunner, you can click on the "3 vertical dots" button near the like/dislike (image 1), there will be a "Download" button at the top of the menu (image 2) - click on it and the download will start! (the button label will auto-update to reflect progress)
Feel free to update this issue if something does not work as expected!

Image 1:
![1 cleaned](https://user-images.githubusercontent.com/8024624/104366844-43352880-551a-11eb-8012-635314617d55.png)

Image 2:
![2 cleaned](https://user-images.githubusercontent.com/8024624/104366843-429c9200-551a-11eb-883e-b443710c2cac.png)

**Comment by TaylanTatli** [comment]
There is no Download option there.
![Screenshot_20210116_155755](https://user-images.githubusercontent.com/754514/104812494-a58c7280-5813-11eb-9361-642476b5e0c1.png)

**Comment by th-ch** [comment]
Hey @TaylanTatli, thanks for the feedback! Is the downloader plugin enabled? (In the "Plugins" menu, ensure "Downloader" is checked and restart the app)
If yes and the button is still not there, you can trigger devtools (Options > Toggle devtools) and look at the Console tab to see if you have any JS error (you can repost any error here for further investigation)

**Comment by TaylanTatli** [comment]
Sorry i look everywhere, clicked every dots and tried shortcuts even to open dev tools but there is no option nothing is in there, it seems just youtube music website in a window. I'm using 1.9.0 AppImage and just started using it.

**Comment by Artan1408** [comment]
> 
> 
> Sorry i look everywhere, clicked every dots and tried shortcuts even to open dev tools but there is no option nothing is in there, it seems just youtube music website in a window. I'm using 1.9.0 AppImage and just started using it.

Hey, 
I had the same issue, make sure u checked the downloader under the plugins then restart the app.
after that it appeared for me.

**Comment by th-ch** [comment]
Thanks @Artan1408 for the feedback!
Also @TaylanTatli, if you don't see the menu (looks like it on your screenshot), ensure the `hideMenu` option is set to `false` in the config file (on Linux, it should be in `~/.config/YouTube Music/config.json` - for other platforms, see the [doc](https://www.electronjs.org/docs/api/app#appgetpathname))

**Comment by TaylanTatli** [comment]
> Thanks @Artan1408 for the feedback!
> Also @TaylanTatli, if you don't see the menu (looks like it on your screenshot), ensure the `hideMenu` option is set to `false` in the config file (on Linux, it should be in `~/.config/YouTube Music/config.json` - for other platforms, see the [doc](https://www.electronjs.org/docs/api/app#appgetpathname))

Yes sorry, it seems there was a problem with my menu. After restart problem fixed, and downloader plugins was not enabled. Everything is working now.
