### ISSUE TITLE
can't see album cover

### ISSUE THREAD

**Issue by badspoken** [th-ch/youtube-music#1224]
The app doesn't show the album cover while playing the song

![image](https://github.com/th-ch/youtube-music/assets/142241186/0b62e83c-f8e8-4fba-8069-93c96dc1a236)

**Comment by zackexplosion** [comment]
I tried to delete the whole temperate folder and restart, and the cover is back!

```
rm -rf ~/Library/Application\ Support/YouTube\ Music/
```

OS: MacOS

**Comment by affifymirza** [comment]
I have similar issues for windows, for me deleting Youtube Music folder make it work again.

here is the directory,
```
C:\Users\user\AppData\Roaming\YouTube Music
```

**Comment by badspoken** [comment]
> I have similar issues for windows, for me deleting Youtube Music folder make it work again.
> 
> here is the directory,
> 
> ```
> C:\Users\user\AppData\Roaming\YouTube Music
> ```

Thank you! Although this wasn't the exact solution, it could be very useful if someone has this issue. In my case I unchecked "bypass-age-restrictions" and it worked. Thanks again
