### ISSUE TITLE
Hardwareacceleration bug on Windows?

### ISSUE THREAD

**Issue by Shadowphoenix** [th-ch/youtube-music#1229]
Similar to several other currently open Tickets, i am having extreme lag-issues on Windows 10, specifically 22H2 on Ryzen 5 2600X wtih 16GB of RAM @3000 Mhz CL16 and an RX580, although with possibly a tat outdated drivers.

Disabling Hardwareacceleration seems to have fixed these lagissues in 1.20 and iirc there was never any issues with 1.19 and hardwareacceleration enabled.

**Comment by JellyBrick** [comment]
#1208

**Comment by Shadowphoenix** [comment]
> #1208

i thank you for the suggestion however: i never even had Adblocker enabled to begin with because i dont need it (I am subscribed to Youtube Premium)

**Comment by Shadowphoenix** [comment]
> > #1208
> 
> i thank you for the suggestion however: i never even had the Adblocker-Plugin enabled to begin with because i dont need it (I am subscribed to Youtube Premium)

so yeah i dont think adblocker itself is the problem, but since disabling hardwareacceleration fixed my issues, maybe Hardwareacceleration is worth taking a look at?
