### ISSUE TITLE
Add a portable version for Windows

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#123]
Actually, there isn't a Windows portable version, yet.
If the problem can be the load time, however electron builder supports a splash screen...

Please, add a portable version: I'd like to test the app features but without installing it.

**Comment by Lythed** [comment]
Hello,
if you really want a portable version for now you could use [UniExtract2](https://github.com/Bioruebe/UniExtract2) to extract the .exe to a portable version.

(But yea, a portable version could be really useful!)

**Comment by th-ch** [comment]
Hey @Bellisario @Lythed, thanks for the feedback! A [portable exe is available in the latest prerelease](https://github.com/th-ch/youtube-music/releases/download/v1.8.2/YouTube-Music-1.8.2.exe), feel free to give it a try and update the issue accordingly!

**Comment by Lythed** [comment]
> Hey @Bellisario @Lythed, thanks for the feedback! A [portable exe is available in the latest prerelease](https://github.com/th-ch/youtube-music/releases/download/v1.8.2/YouTube-Music-1.8.2.exe), feel free to give it a try and update the issue accordingly!

Seem to work flawlessly for me! Thank you for your work! :)

**Comment by Bellisario** [comment]
Ok thanks everybody!!!

**Comment by Bellisario** [comment]
Just tested! Wonderful work! :heart_eyes:

**Comment by th-ch** [comment]
PR merged, next release will have a portable Windows version! Closing this issue, feel free to re-open if needed!
