### ISSUE TITLE
Windows version not responding

### ISSUE THREAD

**Issue by vuld0** [th-ch/youtube-music#1231]
I tried to run the [Youtube-Music-setup-1.20.0.exe](https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-Setup-1.20.0.exe), but it crashed and stayed in a “Not responding” error for some time. Is this a common issue? I was not able to find any other issues like this, so I am opening this one.

**Comment by symonxdd** [comment]
You can provide a screenshot? Does it give the error message when opening it from the File Explorer as well?
