### ISSUE TITLE
Audio Device changing

### ISSUE THREAD

**Issue by AbsentPopcorn33** [th-ch/youtube-music#1232]
start up or restart the default device is used instead of the selected device in settings
![image_2023-08-30_000501808](https://github.com/th-ch/youtube-music/assets/62642304/63cdd428-c9a1-4fc5-9bcc-24746e62a467)
Its supposed to be using the one to the left

**Comment by Bassote** [comment]
I know this is listed as wontfix, but I'm having the same problem, I have to manually change the audio device on every soft restart
