### ISSUE TITLE
Using Visualizer Results to black video screen 

### ISSUE THREAD

**Issue by th3d3ck3r** [th-ch/youtube-music#1233]
OS: Windows 11.
I'm not using any other plugins.
In the screenshot it's paused but looks exactly the same either way.

Not sure if I'm doing something wrong or if it's broken
![Screenshot 2023-09-01 224159](https://github.com/th-ch/youtube-music/assets/55422728/34830d80-0cd1-44e2-a192-c03a3d1ef252)

**Comment by MiepHD** [comment]
I'm not sure why this appears but setting `Plugins > video-toggle > Mode > Custom toggle` fixes it

**Comment by Diego-VRFP** [comment]
The same thing happens to me, I can't see the image or the video, it appears black, and it doesn't matter if I put it in custom or native, but I was able to see it a long time ago...

**Comment by Diego-VRFP** [comment]
The same thing happens to me, I can't see the image or the video, it appears black, but I was able to see it a long time ago... And it doesn't matter if I put it in custom or native,
