### ISSUE TITLE
Themes do not work

### ISSUE THREAD

**Issue by SomeAspy** [th-ch/youtube-music#1237]
Selecting a theme does not apply it, nor does the theme selector update to reflect themes chosen.
This is on arch linux, using the AUR package https://aur.archlinux.org/packages/youtube-music-bin @ 1.20.0-5

https://github.com/th-ch/youtube-music/assets/33640860/027344af-fddf-48c0-99ac-7b8e6f4facf4

**Comment by themagicalmammal** [comment]
Can confirm it doesn't work on [1.2.0](https://github.com/th-ch/youtube-music/releases/tag/v1.20.0). It shows no theme even after taking the css.

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/c5dd8bd0-e9f4-42f2-b9c4-4766aaf1cc21)

It works on `v2.0.2`

**Comment by SomeAspy** [comment]
I am still unable to get it to work - I am using this CSS: 
https://github.com/catppuccin/youtubemusic
I click import CSS and nothing happens.

**Comment by JellyBrick** [comment]
> I am still unable to get it to work - I am using this CSS: https://github.com/catppuccin/youtubemusic I click import CSS and nothing happens.

Did you restart the application?

**Comment by SomeAspy** [comment]
> Did you restart the application?
Yes

**Comment by iryis** [comment]
I wasn't able to get this to work either, using the same methods
![image](https://github.com/th-ch/youtube-music/assets/68797873/4f1f0aa0-bba4-42f5-85ed-5c44f82819e2)

**Comment by JellyBrick** [comment]
@SomeAspy @iryis 
I think https://github.com/catppuccin/youtubemusic is corrupted.

https://draculatheme.com/youtube-music-desktop 
It works.

**Comment by iryis** [comment]
Interesting. I just worked around it by manually pasting the contents into a css file and it works.
