### ISSUE TITLE
Not working on macOS Sonoma release candidate

### ISSUE THREAD

**Issue by samwzlim** [th-ch/youtube-music#1243]
It says the app is damaged and can't be opened.

![CleanShot 2023-09-14 at 5  31 06@2x](https://github.com/th-ch/youtube-music/assets/74489037/b69d4758-3df5-443d-8d80-a7a5b22e18fe)

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music#macos

```bash
xattr -cr /Applications/YouTube\ Music.app
```

**Comment by symonxdd** [comment]
If the reply above solved your problem, please consider closing this issue, thanks!
