### ISSUE TITLE
"bypass-age-restrictions" plugin breaks videos

### ISSUE THREAD

**Issue by retamaut** [th-ch/youtube-music#1248]
Hi!

I'm using version 1.20 on Windows of youtube-music.

Whenever I have "bypass-age-restrictions" enabled, all the music videos on YT Music disappear. It comes back after disabling that.

Caused a lot of headache previously, thinking it was some cache or config issues.

Let me know if you need any more details if you aren't able to replicate. Happy to help as well!

**Comment by JellyBrick** [comment]
It was fixed due to #1221 (not released yet)

**Comment by JellyBrick** [comment]
Check out our forked version that fixes this issue: #1254

**Comment by th-ch** [comment]
A new version will be released soon! Closing as it's already fixed
