### ISSUE TITLE
Experiencing lag after playing a lot of music

### ISSUE THREAD

**Issue by its-yuu** [th-ch/youtube-music#1249]
I've been experiencing this after i played lots of music like there's a delay whenever i click something and the music stop for about a second then play again but at first it runs so smooth. restarting the app fix it but its so hassle to do it all the time.
i never experience it in youtube music in browser even when im playing and do lots of task, only in this app.
my unit is ryzen 5 5600g with 16gb of ram so i think my pc is not the problem.

hope will solve this problem thank you dev.

**Comment by JellyBrick** [comment]
Duplicated of #1208
