### ISSUE TITLE
any news about an ARM build for macOS 

### ISSUE THREAD

**Issue by avichou** [th-ch/youtube-music#1252]
would be nice to have ytm work natively on arm macs (m1,m2, pro and max)

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-1.20.0-arm64.dmg

**Comment by avichou** [comment]
> https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-1.20.0-arm64.dmg

thank you. yours ?

**Comment by JellyBrick** [comment]
> > [`v1.20.0` YouTube-Music-1.20.0-arm64.dmg (download)](https://github.com/th-ch/youtube-music/releases/download/v1.20.0/YouTube-Music-1.20.0-arm64.dmg)
> 
> thank you. yours ?

no, It's an [official release of this repository](https://github.com/th-ch/youtube-music/releases/).
