### ISSUE TITLE
We've forked this repository to resolve various issues

### ISSUE THREAD

**Issue by JellyBrick** [th-ch/youtube-music#1254]
The maintainer of this repository seems to be busy, so we've created a temporary forked version of this repository to resolve various issues and add features.

- https://github.com/organization/youtube-music-next

## Resolved issues

- resolves #962
- resolves #958 
- resolves #1240 
- resolves #1188 
- resolves #1172
- resolves #978 
- resolves #1247
- resolves #1253 
- resolves #1187 (resolves #1208, resolves #1212, resolves #1226, resolves #1227, resolves #1147, resolves #1158, resolves #1162, resolves #1249)

## Merged pull request

- #1235 
- #1234
- #1200 

## Additional Features

- Applying rollup
- Blazingly lightweight thanks to optimized dependencies and structure
- Ambient-lighting

## Download

- https://github.com/organization/youtube-music-next/releases/latest

**Comment by th-ch** [comment]
Hey @JellyBrick, thanks for being active! I'm giving you write access to the repo so that bugfixes can be merged :)

**Comment by avichou** [comment]
> Hey @JellyBrick, thanks for being active! I'm giving you write access to the repo so that bugfixes can be merged :)

does that mean that we can keep using your main project and can expect updates to be pushed ?

**Comment by JellyBrick** [comment]
> > Hey @JellyBrick, thanks for being active! I'm giving you write access to the repo so that bugfixes can be merged :)
> 
> does that mean that we can keep using your main project and can expect updates to be pushed ?

From what he says, yes.
