### ISSUE TITLE
[Bug]: Last-fm Plugin Token Expired

### ISSUE THREAD

**Issue by Ao1Pointblank** [th-ch/youtube-music#1268]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Linux Mint 21.2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.0.0

### Expected Behavior

I've never used the Last.fm plugin before v2.0.0
In fact, I've never even had an account for that website before now.

### Actual Behavior

Enabling the Last-fm plugin opens a browser window when the app is started, prompting me to sign in and verify the application. Attempting to do so sends me to https://www.last.fm/api/None and says:
 "Token expired. Please return to YouTube Music and try again."
 Ignoring this, a new tab will be automatically opened by the player every few minutes until I deactivate the plugin and restart the app.

### Additional Information

I tried to troubleshoot this by removing config.json, disabling the in-app adblock, and using a different default browser to connect the application (Brave and Firefox)

**Comment by JellyBrick** [comment]
Fixed at #1271
