### ISSUE TITLE
[Bug]: Latest update (2.0.1) causes no window to appear

### ISSUE THREAD

**Issue by tomc128** [th-ch/youtube-music#1273]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.2338

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Expected Behavior

The app works as normal, opens and shows me the YouTube music interface

### Actual Behavior

No window appears at all. The process exists in task manager (and even continued playing music) but no window ever appeared, and no icon showed in the status bar.

### Additional Information

The issue persists after system reboot and reinstall of the app. I couldn't find any log files to attach.

**Comment by JellyBrick** [comment]
Can you show me `config.json`? (`%appdata%\YouTube Music\config.json`)

**Comment by YangYangMY** [comment]
Have this issues too

**Comment by JellyBrick** [comment]
Fixed in `v2.0.2`.
