### ISSUE TITLE
Dragging window is laggy

### ISSUE THREAD

**Issue by u8Jj3** [th-ch/youtube-music#128]
Hi,
since I use this app, when I drag the window, the window is super laggy. I have no clue why this is happening, no issue so far with others apps (And I have no issue with others "Youtube Music" related apps)

I recorded the issue to show you the behavior of the window

https://user-images.githubusercontent.com/35495389/104378899-f9077380-5528-11eb-8ec3-5fe3c57524b7.mp4

I use the latest release 1.9.0 as of now (Same issue with both portable and installer version)
Windows 10 Pro 20H2 64x
Graphic card & Logitech mouse up-to-date
If you need more informations please let me know!

**Comment by ZerominerBR** [comment]
My friend on Windows 10 Home is having the same issue, but it doesn't seem to be a issue on Linux Mint 20

**Comment by Bellisario** [comment]
@Lythed, is your version portable (your version also is the first relase of Youtube Music portable) or you had to install it?
I'm currently use the portable version (that usually stress more the cpu) on W7 but it does work correctly...
Can you attach down your processor type (brand, type and cores)? Anyway, thank you for your feedback!!!

**Comment by Lythed** [comment]
> @Lythed, is your version portable (your version also is the first relase of Youtube Music portable) or you had to install it?
> I'm currently use the portable version (that usually stress more the cpu) on W7 but it works correctly...
> Can you attach down your processor type (brand, type and cores)? Anyway, thank you for your feedback!!!

Im having the same issue with both portable and installer version. (latest 1.9.0) :/

Here is my processor: Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz, 3101 Mhz, 4 Core(s), 4 Logical Processor(s)
Lemme know if you need more informations. :)

**Comment by TECHNOFAB11** [comment]
From my experience this is because they have a custom titlebar and Electron being not the most performant thing ever lags behind. A request to be able to disable this custom titlebar is in #309
