### ISSUE TITLE
[Bug]: Missing icons taskbar-mediacontrol

### ISSUE THREAD

**Issue by leroyloren** [th-ch/youtube-music#1281]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.2

### What operating system are you using?

Windows

### Operating System Version

11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Expected Behavior

See icons

### Actual Behavior

The icons cannot be seen.

![obrazek](https://github.com/th-ch/youtube-music/assets/57643470/b63af0fe-8dba-4b31-b119-5cf3f9b1b9f6)

![obrazek](https://github.com/th-ch/youtube-music/assets/57643470/069ef4a4-b8a1-4b5c-ae70-46cfa0c98131)

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/85f080a8-5b32-43dc-9d6a-f66d66020d84)

It seems to work fine for me.
Is your user account name in Windows set to something other than English or numbers?

**Comment by leroyloren** [comment]
The account name is only standard characters, the system language is Czech.

**Comment by JellyBrick** [comment]
> The account name is only standard characters, the system language is Czech.

Temporary workaround available until the 2.0.3 release:
- Enable `plugins -> notification -> Interactive Notification`. 
Activating it will resolve this issue.
