### ISSUE TITLE
[Bug]: genius lyrics not working 

### ISSUE THREAD

**Issue by avichou** [th-ch/youtube-music#1282]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS sonoma 14 stable 

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

clickable genius lyrics 

### Actual Behavior

simply shows regular lyrics without genius 

### Additional Information

mba m1 , sonoma public release. same with the last youtube music versions 
<img width="1059" alt="image" src="https://github.com/th-ch/youtube-music/assets/86660671/7005d9b6-8de9-4949-ac65-242691cdc09a">

**Comment by JellyBrick** [comment]
It is the intended behaviour that the Genius-Lyrics plugin does not work with tracks of type "song".

See the related PR: #1092

**Comment by avichou** [comment]
> It is the intended behaviour that the Genius-Lyrics plugin does not work with tracks of type "song".
> 
> See the related PR: #1092

oh that's sad . i've read the thread but not sure why the behaviour is as it is 

there's a chrome extnesion that's able to make it work even with "songs" 

https://www.reddit.com/r/YoutubeMusic/comments/11mthkv/made_a_chrome_extension_that_seamlessly/

**Comment by JellyBrick** [comment]
> > It is the intended behaviour that the Genius-Lyrics plugin does not work with tracks of type "song".
> > See the related PR: #1092
> 
> oh that's sad . i've read the thread but not sure why the behaviour is as it is
> 
> there's a chrome extnesion that's able to make it work even with "songs"
> 
> [reddit.com/r/YoutubeMusic/comments/11mthkv/made_a_chrome_extension_that_seamlessly](https://www.reddit.com/r/YoutubeMusic/comments/11mthkv/made_a_chrome_extension_that_seamlessly/)

I've asked the author of that PR to rewrite it, so please keep an eye on it.
