### ISSUE TITLE
[Feature Request]: Show app version

### ISSUE THREAD

**Issue by leroyloren** [th-ch/youtube-music#1284]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It would be good to show the current version of the application

### Proposed Solution

Modal window "About" possibly only as a listitem in menu.

### Alternatives Considered

.

**Comment by th-ch** [comment]
Thanks for the feature request, it makes sense! Added in https://github.com/th-ch/youtube-music/commit/21c45faf2043cf72a7c14d5cf6c8d848d0448528 :)
