### ISSUE TITLE
[Bug]: MPRIS Information is not available/correct

### ISSUE THREAD

**Issue by JoeJoeTV** [th-ch/youtube-music#1287]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 21.2 Cinnamon

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Expected Behavior

The Properties in the MPRIS Player interface (`org.mpris.MediaPlayer2.Player`) should report the correct values.

### Actual Behavior

Currently, the `Metadata` and `Position` properties don't work at all and are empty if read using e.g. D-Feet.

Additionally, the `LoopStatus` seems to have switched values for `Track` and `Playlist`, since these are switched with the meaning of the UI toggle.

The `PlaybackStatus` is also always `Paused`.

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/73ee8e0e-8a47-4b33-8000-faed7106e447)

Fixed in #1291
