### ISSUE TITLE
Media Keys Broken with Auto-Unpause

### ISSUE THREAD

**Issue by BLANK-TH** [th-ch/youtube-music#129]
When the plugin auto-confirm-when-paused is enabled, after a while the pause media key won't work anymore (when you push it nothing happens). I suspect this is because the app immediately unpauses thinking it's been paused by youtube. Pushing the buttons on the app still seem to work though

**Comment by th-ch** [comment]
Hey @BLANK-TH, thanks for the feedback! This was a known issue in the past but should be fixed in recent versions of the app (on my side, I think I haven't had it in a while) - are you on the latest version of the app?

**Comment by BLANK-TH** [comment]
Yeah, I'm on the latest stable version (1.9.0)

**Comment by BLANK-TH** [comment]
The tray is disabled though, so maybe I should enable that?

**Comment by Araxeus** [comment]
This has been fixed on the linked pull request 🙂
