### ISSUE TITLE
[Feature Request]: Resume last song/playlist, but don't autplay it

### ISSUE THREAD

**Issue by Destroy666x** [th-ch/youtube-music#1294]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently the "Resume last song when app starts" option autoplays the song, which isn't great. Sometimes even terrible if you have to restart the device and a song starts playing with YT music launch - you could be in public library, for instance.

### Proposed Solution

Extend the setting into a submenu with these options:
- enable - which alone only remembers the last played song/playlist
- autoplay - to control if the song should be played at startup or not

### Alternatives Considered

The only alternative is to disable the feature and miss out on remembering what was played.

**Comment by JellyBrick** [comment]
Enable `disable-autoplay` -> `Applies only on startup`

**Comment by Destroy666x** [comment]
Ah ok, thanks, missed that.
