### ISSUE TITLE
[Bug]: App not loading HTML

### ISSUE THREAD

**Issue by TheRedNet** [th-ch/youtube-music#1300]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.0.2

### Expected Behavior

The App should load the HTML at all

### Actual Behavior

The App does not load its HTML and is just black
![image](https://github.com/th-ch/youtube-music/assets/45996791/4beb6a8c-7d48-406c-aa3f-0caaf7fcd0ae)

**Comment by JellyBrick** [comment]
Can you show me your `%appdata%\YouTube Music\config.json` file?

**Comment by TheRedNet** [comment]
i now tried it in a Windows-Sandbox (Clean windows installation with nothing extra installed) and i got the same result
![image](https://github.com/th-ch/youtube-music/assets/45996791/10e2e932-8db7-42fd-b36d-aaa586a27f08)

**Comment by TheRedNet** [comment]
The Problem only occurs on fresh installs. Installing version 2.0.2 and then upgrading to 2.0.3 works.

**Comment by JellyBrick** [comment]
> The Problem only occurs on fresh installs. Installing version 2.0.2 and then upgrading to 2.0.3 works.

This issue caused by the renderer's adblocker being loaded before the main process's adblocker.
I'll release the hotfix soon. Thank you for reporting the bu
