### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sickjuicy** [th-ch/youtube-music#1302]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

master

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

master 1.20

### Expected Behavior

Npm run build:win not working.

tried npm run dist:win:x64 but in the dist folder there is only a error.html and no exe or build folder.

```
E:\Dev-Home\repos\youtube-music>npm run build:win
npm ERR! Missing script: "build:win"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\Sickj\AppData\Local\npm-cache\_logs\2023-10-10T20_08_54_011Z-debug-0.log
```

### Actual Behavior

Npm run build:win app builds.

**Comment by JellyBrick** [comment]
Use `npm run dist:win`
