### ISSUE TITLE
[Feature Request]: Launching the app from taskbar creates 2nd icon

### ISSUE THREAD

**Issue by Malakasskatakys** [th-ch/youtube-music#1303]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Whenever the app is launched from a taskbar shortcut, the EXE will launch and will look like this  (i use windows 10)

![Screenshot 2023-10-11 025643](https://github.com/th-ch/youtube-music/assets/43682361/3f508f1c-6882-4c5a-a044-8df9e88cc30b)

I did see an older post about it but didn't find a solution, when the EXE opens in the taskbar, it's located in AppData\Local\Temp\2WX8MhHIE7eHqiWOaPGbbDWJhkE, although that isn't the location i installed it on. I believe that might be the reason this happens.
![image](https://github.com/th-ch/youtube-music/assets/43682361/cd2476a5-0658-4f0b-ab20-2bed3e75e7bb)

### Proposed Solution

I don't know if its possible, but i would like it to open inside the shortcut icon that already exists in my taskbar, instead of making a new one

### Alternatives Considered

---

**Comment by Malakasskatakys** [comment]
I did see an older post about it but didn't find a solution

**Comment by JellyBrick** [comment]
- The reason for the random characters like `AppData\Local\Temp\2WX8MhHIE7eHqiWOaPGbbDWJhkE` in the path to the file is that you running the portable version. If you want to install application, please download `YouTube-Music-Web-Setup-VERSION.exe`
- Please activate `Options` → `Single instance lock`.

**Comment by Malakasskatakys** [comment]
That fixed it, thanks
