### ISSUE TITLE
[Bug]: My application stay black, after install 

### ISSUE THREAD

**Issue by Tyrozz34** [th-ch/youtube-music#1305]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.3

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

i expected the application open normaly, with all displayed 

### Actual Behavior

Nothing happen, my friend try with me, and he got everythings right, i have try all the step 3 times please help me thanks 
![image](https://github.com/th-ch/youtube-music/assets/52861115/5b81deee-b62f-463b-af66-ed211d8c10cc)

**Comment by Tyrozz34** [comment]
ok m'y bad i have see the fiox, with the adblocker loading before sorry

**Comment by JellyBrick** [comment]
Fixed at `2.0.4`
