### ISSUE TITLE
Winget displaying version 1.20

### ISSUE THREAD

**Issue by EldrinSMP** [th-ch/youtube-music#1306]
You list winget as one of the deployment options on the readme. However, using Winget gets you version 1.20.
<img width="802" alt="Screenshot 2023-10-11 170445" src="https://github.com/th-ch/youtube-music/assets/134807078/b9e17f25-0b3a-4a7c-99f0-21efc5471386">

**Comment by JellyBrick** [comment]
Blocked by https://github.com/vedantmgoyal2009/winget-releaser/issues/239
