### ISSUE TITLE
[Bug]: Download Error (Every Song/Video)

### ISSUE THREAD

**Issue by Mendungo** [th-ch/youtube-music#1308]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Download song to specific foler

### Actual Behavior

Error message pops up saying "video not found" with every song

**Comment by JellyBrick** [comment]
It works well for me. Do you have a reproduction process?

**Comment by da-anda** [comment]
downloading seems to be hit and miss for me. Like downloading a playlist (like the "thumbs up" playlist) doesn't really do anything. I have turned on "skip existing", but there is not even a folder for the playlist in the download directory, so no idea why it would skip anything.

Side note, not related to the general download errors but also a download related issue: When I change the download preset to `opus`, the result is not opus, but the raw AAC (`audio/mp4; codecs="mp4a.40.2"`) stream with a `.opus` file extension and no metadata at all. I would have expected to get the unaltered opus stream in the highest available quality. Alternatively a AAC/mp4 preset to get the unaltered highest quality available might make sense.

**Comment by JellyBrick** [comment]
> downloading seems to be hit and miss for me. Like downloading a playlist (like the "thumbs up" playlist) doesn't really do anything. I have turned on "skip existing", but there is not even a folder for the playlist in the download directory, so no idea why it would skip anything.

- Unfortunately, the 'thumb up' playlist or automatically generated playlist by the system cannot be downloaded, which is YouTube's intended behavior.


> Side note, not related to the general download errors but also a download related issue: When I change the download preset to `opus`, the result is not opus, but the raw AAC (`audio/mp4; codecs="mp4a.40.2"`) stream with a `.opus` file extension and no metadata at all. I would have expected to get the unaltered opus stream in the highest available quality. Alternatively a AAC/mp4 preset to get the unaltered highest quality available might make sense.
> 
> edit: after a "force reload" I now also get the "`video not found` error on anything I click

- The current code is designed to download the audio track with the highest quality (as possible). However, it does not consider the case where the highest quality is the 'm4a' format, so the downloader plugin downloads 'm4a' files with the wrong extension.
	- I plan to improve download features to automatically detect the format and choose the appropriate file extension.

**Comment by Mendungo** [comment]
> It works well for me. Do you have a reproduction process? (What video, what playlist, etc)

It doesn't for me, it was working perfectly previously. Non of my playlists or songs, not even any individual song, once I click download this is what pops up 

![Screenshot 2023-10-12 152212](https://github.com/th-ch/youtube-music/assets/146989474/d4300b1c-ee33-4cd2-8b3d-cba6ad58418c)

Had to downgrade to 2.0.3, and downloading works fine but now when i try to download a full playlist in bulk it downloads only the one song in playback.

**Comment by meequrox** [comment]
Same for me on 2.0.4:

![](https://ie.wampi.ru/2023/10/13/2023-10-13_19-13.png)

I added some `console.log()` to back.ts.

To downloadSong() definition:

```
console.log("downloadSong(%s, %s, %s, _)", url, playlistFolder, trackId);
```

To downloadSongUnsafe definition:

```
  console.log("downloadSongUnsafe(%d, %s, _, %s, %s, _)", isId, idOrUrl, playlistFolder, trackId); // <---

  sendFeedback('Downloading...', 2);

  console.log("Start resolving id"); // <---

  let id: string | null;
  if (isId) {
    id = idOrUrl;
    console.log("id = %s", id); // <---
  } else {
    id = getVideoId(idOrUrl);
    console.log("id = %s", id); // <---
    if (typeof id !== 'string') throw new Error('Video not found');
  }

  console.log("Id resolved"); // <---

  let info: TrackInfo | VideoInfo = await yt.music.getInfo(id);
```

Output in the situation shown in the screenshot above:

```
downloadSong(https://music.youtube.com/search?q=new+episode, undefined, undefined, _)
downloadSongUnsafe(0, https://music.youtube.com/search?q=new+episode, _, undefined, undefined, _)
Start resolving id
id = null
Error: Video not found
```

Downloading in older versions also does not work.

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/066d77d3-a384-4214-a516-012dbcb1788f)

Thank you for the detailed bug report!
This issue was caused by an invalid query selector.

**Comment by JellyBrick** [comment]
@Mendungo 

> Side note, not related to the general download errors but also a download related issue: When I change the download preset to `opus`, the result is not opus, but the raw AAC (`audio/mp4; codecs="mp4a.40.2"`) stream with a `.opus` file extension and no metadata at all. I would have expected to get the unaltered opus stream in the highest available quality. Alternatively a AAC/mp4 preset to get the unaltered highest quality available might make sense.

It should fixed on #1310

**Comment by Zahav88** [comment]
I have this issue for quite long time, its possible to download  only few songs, rest fails  yesterday installed 3.2.1 and all worked again. Today, oh look another new version... bam again does not work!

**Comment by JellyBrick** [comment]
@Zahav88 Please provide the reproduction steps

**Comment by Zahav88** [comment]
![Capture](https://github.com/th-ch/youtube-music/assets/155818766/fd6887b5-cc43-4177-9efb-2bba9551e955)
![Capture-2](https://github.com/th-ch/youtube-music/assets/155818766/32a2a8df-4632-458a-a6dc-ac3aa39f41bd)

Not sure if it helps,

**Comment by Arusu12** [comment]
![image](https://github.com/user-attachments/assets/2df456ac-e18e-40c0-92ab-1dc8152c9b32)
I am having this error. Using for the first time
