### ISSUE TITLE
[Bug]: Folder Error Popup when downloading Albums

### ISSUE THREAD

**Issue by SamuDifferent** [th-ch/youtube-music#1313]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.04.3 LTS

### What arch are you using?

x64

### Expected Behavior

The Download button creating a Subfolder underneath the selected download directory.

### Actual Behavior

When clicking the download button on an album, i get an error, that the folder is already existing, because the app tries to create the selected download folder again, rather than creating a subfolder, as usual.

**Comment by Sinodus** [comment]
it's happening with me too.
