### ISSUE TITLE
[Bug]: Adblocker does not work after update

### ISSUE THREAD

**Issue by FireDrop6000** [th-ch/youtube-music#1315]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.1.0

### What operating system are you using?

Other Linux

### Operating System Version

6.5.7-arch1-1

### What arch are you using?

x64

### Expected Behavior

Adblocker was supposed to work as it was before the update.

### Actual Behavior

After I updated to the latest version of Youtube-Music, the adblocker plugin failed to load again and again. This is what it showed after launching from the terminal.
![1697298868_grim](https://github.com/th-ch/youtube-music/assets/65220251/c942c6bc-c5aa-4be6-9ca7-59162d86f7f5)

**Comment by JellyBrick** [comment]
Which AUR package are you using?

https://github.com/th-ch/youtube-music/blob/b316aa230144107b06e99be58a67f01d61a9d7b5/plugins/adblocker/blocker.ts#L26-L32

In current logic, that directory **should be** created in the `app.getPath('userData')` directory if the app is packaged.

**Comment by FireDrop6000** [comment]
at first i was using the youtube-music-git package but when it stopped working, i thought maybe try for an updated package so installed the regular youtube-music package (not bin package).

**Comment by Bunie89** [comment]
Compiled c5d0314 , Adblocker is still not blocking ads.
