### ISSUE TITLE
[Feature Request]: Enable high quality audio stream

### ISSUE THREAD

**Issue by OmniNaut** [th-ch/youtube-music#1319]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I don't have a Premium subscription and I'm wandering if it's possible to enable the High Quality audio while streaming. 
In my account settings I'm limited to Normal or Low and I don't see an option or plugin in the app menu for this.
I also use YouTube Music ReVanced on mobile, there it's possible to set the quality to High regardless if I have a Premium subscription.

Thank you

### Proposed Solution

Enable Higher quality audio stream in or Profile settings or app menu option

### Alternatives Considered

Same as proposed.

**Comment by JellyBrick** [comment]
This is a server-side limitation of YouTube, there's no workaround for this.

https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f

Could you please check which audio codec is used when playing audio tracks in YTM-Desktop and YTM-Revanced?

**Comment by JellyBrick** [comment]
### Premium user

![image](https://github.com/th-ch/youtube-music/assets/16558115/f50c714f-3f71-4cb3-b034-66d45bba2c5a)

### Non-premium user

![image](https://github.com/th-ch/youtube-music/assets/16558115/db8ddb75-c5d1-4ac6-b9da-2d3997548c43)

**Comment by OmniNaut** [comment]
@JellyBrick Thanks for checking.
Unfortunately I don't see a setting within YouTube Music ReVanced for Statistics for Nerds. So I can't verify which codec is actually used for the different quality settings. If you have another idea will gladly check for you.

**Comment by OmniNaut** [comment]
![YTM](https://github.com/th-ch/youtube-music/assets/110312864/7b3ed532-b9a0-4db5-bd29-8480a502a6f6)
![YTM Revanced High Quality](https://github.com/th-ch/youtube-music/assets/110312864/5a68da6e-aa96-4924-b26f-2bf32099f5c1)

Found the setting to enable the statistics for nerds. 
Made sure that YTM Revanced the quality is set to high. For some songs I get only Opus, and for other songs I get MP4a.

**Comment by JellyBrick** [comment]
140 is low-quality m4a for a non-premium user

![image](https://github.com/th-ch/youtube-music/assets/16558115/22687952-17f6-4010-9409-8e6b9599e8b4)

### Premium account

![image](https://github.com/th-ch/youtube-music/assets/16558115/2fbd09de-9e15-402a-857c-acf481466b3d)


I think it's a server-side limitation of YT

**Comment by OmniNaut** [comment]
Ok understood. Thanks for looking into it.

To be honest, I did not notice much difference between high and normal quality in the ReVanced app. Now I understand why.
