### ISSUE TITLE
[Bug]: Cannot start, zygote_host_impl_linux.cc operation not permitted

### ISSUE THREAD

**Issue by map7** [th-ch/youtube-music#1320]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.1.1

### What operating system are you using?

Other Linux

### Operating System Version

Debian 10

### What arch are you using?

x64

### Expected Behavior

I expected it to start and show a GUI.

### Actual Behavior

When I start from the command line in Debian 10 64bit I get the following error;

% youtube-music                
LaunchProcess: failed to execvp:
/opt/YouTube
[9582:1016/100925.669586:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Operation not permitted (1)
[1]    9582 trace trap  youtube-music
[9585:0100/000000.716595:ERROR:zygote_linux.cc(662)] write: Broken pipe (32)

### Additional Information

I used the deb package from 2.1.1 release.

**Comment by JellyBrick** [comment]
I think it's a chromium issue.

https://stackoverflow.com/questions/76833201/how-to-run-chrome-securely-in-docker
