### ISSUE TITLE
[Bug]: No reaction when attempting to add over 5,000 playlist entries

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#1322]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Youtube playlists only go up to 5,000 songs/videos. Yes, I added to the max as a stress test to see what would happen. Here's the proof for anyone that wants to see what ive been through the past 3 hours LOL

![image](https://github.com/th-ch/youtube-music/assets/53978637/c6d3edf5-eafa-46ce-8a89-096ab0f8a3cf)

However, when attempting to use the "add all" function from a playlist at 5000 - (Number of songs in the playlist), if the total goes over 5000, nothing will happen. 

### Actual Behavior

It appears that it recognizes we cant add more than the max amount which is good, but does not display any sort of message or explanation for why the add is failing.

**Comment by JellyBrick** [comment]
This is a server-side limitation of YouTube, there's no workaround for this.

**Comment by DereC4** [comment]
> This is a server-side limitation of YouTube, there's no workaround for this.

My apologies, I think you interpreted this in another direction than i was going. I was asking for an option to display something to explain why the add was failing, rather than nothing occurring at all. Let me edit my message to make it a bit more clear.
