### ISSUE TITLE
[Bug]: Downloader plugin only downloads the first 100 songs in a playlist

### ISSUE THREAD

**Issue by NobleCanth** [th-ch/youtube-music#1327]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.0.1

### Expected Behavior

When I click download playlist, I expect the downloader plugin to download the entire several hundred song long playlist in mp3 256kbps format.

### Actual Behavior

When I click download playlist, the downloader plugin only downloads the first 100 songs in a playlist in mp3 256 kbps format and nothing more.

### Additional Information

I have tried different drives, reinstalling the application, and restarting my computer and it has not fixed this issue.

**Comment by JellyBrick** [comment]
Could you provide me with the URL of the playlist?

**Comment by JellyBrick** [comment]
It should fixed in #1329
