### ISSUE TITLE
[Feature Request]: add an option to hide the window controls when using the in-app-menu plugin

### ISSUE THREAD

**Issue by Readf0x** [th-ch/youtube-music#1330]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Window controls will always appear when using the in-app-menu plugin, which is slightly annoying for those who use tiling window managers.
mockup:
![image](https://github.com/th-ch/youtube-music/assets/57838054/0070faf5-cc44-4f33-826d-7f5ff5723df6)

### Proposed Solution

Please add an option to hide the window controls when using the in-app-menu plugin.

### Alternatives Considered

There's not really any alternatives, this is a very small feature request.

**Comment by JellyBrick** [comment]
It should fixed in #1335
