### ISSUE TITLE
[Bug]: Album Name missing from scrobbles

### ISSUE THREAD

**Issue by skypeias** [th-ch/youtube-music#1332]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When playing the first track of a playlist on Youtube Music, the scrobble of the track should include Album Name

### Actual Behavior

When playing the first track of a playlist on Youtube Music, the album name info is missing from scrobbles.

**Comment by JellyBrick** [comment]
Could you provide the URL of the audio track?

**Comment by skypeias** [comment]
here's the playlist I was talking about, this happens when the first track plays
https://music.youtube.com/playlist?list=PLs5v7gbX1rGFdO22jWSOPA5UqXwiElppS&si=hSuS1Ys2Kj2nQtJr

**Comment by JellyBrick** [comment]
It should be fixed in #1334

**Comment by skypeias** [comment]
it's happening again, specifically with albums and playlists that contain my uploaded music. the app fails to obtain the album name when scrobbling
