### ISSUE TITLE
[Bug]: Youtube Music is not working

### ISSUE THREAD

**Issue by error-semicolon** [th-ch/youtube-music#1333]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

The Youtube Music.exe should open normally

### Actual Behavior

The Youtube Music.exe from scoop downloader is not working. When i try to open the application it opens three youtube music in task manager only but there is not sign of youtube music icon in task bar.

**Comment by JellyBrick** [comment]
It should fixed in 2.1.2
