### ISSUE TITLE
[Bug]: Vudio visualizer causes audio to be louder than usual, and increasing volume distorts the audio.

### ISSUE THREAD

**Issue by Endergamer7103** [th-ch/youtube-music#1337]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22621.2359

### What arch are you using?

x64

### Expected Behavior

To be able to adjust my audio level of the music, and have it played at a lower volume.

### Actual Behavior

The audio while the visualizer is active becomes noticeably more louder than normal, and adjusting the volume in the app causes it to become distorted at higher levels.

**Comment by auyylaso** [comment]
The skip silence option also absolutely obliterates the audio quality and makes it louder as well. With both of these options on it becomes so bad it's not even listenable.

**Comment by JellyBrick** [comment]
I think it's a bug in Vudio.

**Comment by JFMugen** [comment]
+1, I thought I was going crazy while quality going down

**Comment by JellyBrick** [comment]
fixed at 8bd3b4d
