### ISSUE TITLE
[Bug]: Start at x:xx is always 0:00

### ISSUE THREAD

**Issue by SomeAspy** [th-ch/youtube-music#1339]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

commit fa4c69d

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Expected Behavior

When opening share, the "start at" button should be at the time the share button was clicked.

### Actual Behavior

The "start at" button is always at 0:00.
![image](https://github.com/th-ch/youtube-music/assets/33640860/ae750624-543e-4608-a26f-10eaf7798527)

**Comment by JellyBrick** [comment]
It can be reproducible in [YTM Website](https://music.youtube.com).
It's not YTM-Desktop's issue.

**Comment by SomeAspy** [comment]
oop my bad
