### ISSUE TITLE
[Bug]: can't enable downloader

### ISSUE THREAD

**Issue by senolfndk** [th-ch/youtube-music#1340]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

v2.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

v2.1.1

### Expected Behavior

download not enabled

### Actual Behavior

downloader must be enabled

https://github.com/th-ch/youtube-music/assets/52818836/387bd99b-2b3b-47fd-9b54-61e0c5288b98

**Comment by alvin0319** [comment]
Confirmed with 2.1.2.0, It seems the Downloader plugin state is not saved into the config.json for whatever unknown reason.
cc @JellyBrick

**Comment by alvin0319** [comment]
For a temporary solution, go to `%appdata%\YouTube Music` (`C:\Users\<USER NAME>\AppData\Roaming\YouTube Music`) and find `config.json`, find `downloader` plugin and change `"enabled": false` to `"enabled": true`.

**Comment by JellyBrick** [comment]
We fixed it in db3d7535e2d583eb220de7b8356c5277512eedcd using hack🤦...
