### ISSUE TITLE
[Feature Request]: Rename Discord Rich Presence 'Listen Along'

### ISSUE THREAD

**Issue by DubyaDude** [th-ch/youtube-music#1341]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, the Discord Rich Presence button to open on YouTube Music says 'Listen Along'. Since the button currently just opens a URL and a proper in-app listen-along hasn't been implemented yet (https://github.com/th-ch/youtube-music/issues/992), 'Listen Along' feels a bit misleading.

Current youtube-music implementation:
![Discord_k5LiSqmgZS](https://github.com/th-ch/youtube-music/assets/13679909/7b29604e-27e3-4783-b956-c1b44d0aba4b)

### Proposed Solution

I'd like the button to say something like '**Play on YouTube Music**' to match with the Discord Spotify Integration.

Spotify Discord Rich Presence integration for reference: 
![image](https://github.com/th-ch/youtube-music/assets/13679909/7b4e376d-d096-4c91-a7c1-e4cbd3b7693e)

### Alternatives Considered

None

### Additional Information

None

**Comment by nethershaw** [comment]
"Listen Along" is disappointingly misleading. It's a link only to the current track (not even the current position in the current track), and contains no information about the rest of the playlist. There's no listening along at all to be had.
