### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IkkyuDEV** [th-ch/youtube-music#1344]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

lateset ver

### What operating system are you using?

Windows

### Operating System Version

win 10 

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

np

### Expected Behavior

is so lagy when it  and loundder 

### Actual Behavior

is so lagy when it  and loundder 

### Additional Information

is so lagy when it and loundder  (.)

**Comment by JellyBrick** [comment]
What?
