### ISSUE TITLE
[Feature Request]: There is a bug that looks nice, I suggest adding it as a plugin

### ISSUE THREAD

**Issue by pioner4103** [th-ch/youtube-music#1348]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

After opening the video in full screen, sometimes a beautiful background blur appears. I wish this blur could always be turned on.
Screen recording with this: https://drive.google.com/file/d/12VLlb2wM6wqvDhFCio3Z3hFF6POfvdYR/view?usp=sharing (I don’t know if it’s possible to upload the screen recording to github)

### Proposed Solution

Fix this as a bug and add it as a plugin

### Alternatives Considered

Don't know

**Comment by progamingguide** [comment]
Sorry to bother this thread but what's the theme you're using? It looks really good.

**Comment by JellyBrick** [comment]
> Sorry to bother this thread but what's the theme you're using? It looks really good.

It's an `album-color-theme` plugin.

![image](https://github.com/th-ch/youtube-music/assets/16558115/fc78d9de-e836-4ee3-95a8-fad021d28a44)
