### ISSUE TITLE
Why discord rich presence shows "Playing" and not "Listening"?

### ISSUE THREAD

**Issue by Nyarkll** [th-ch/youtube-music#1351]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![image](https://github.com/th-ch/youtube-music/assets/70298037/e764dffe-bbce-42d7-ab12-838e7a870444)

### Proposed Solution

Using discord's "listening" rich prence instead of "playing".

### Alternatives Considered

Just that simple change tbh....

**Comment by iryis** [comment]
As far as I know, this is not possible using regular Discord RPC methods. If you use a discord client mod (against tos, fyi, not that it matters) you can intercept and change it to listening.

**Comment by JellyBrick** [comment]
Duplicate of #1123
