### ISSUE TITLE
[Feature Request]: WebNowPlaying integration for Rainmeter media player widgets

### ISSUE THREAD

**Issue by SIUUUUUUUUUU17** [th-ch/youtube-music#1354]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The desktop app would count as a NowPlaying or MediaPlayer program and doesn't return song progress and album name because of whatever Windows do

### Proposed Solution

Integrate WebNowPlaying to the program so it can return the missing informations properly

### Alternatives Considered

I've tried other Rainmeter media player widgets and they all are the same

**Comment by JellyBrick** [comment]
Duplicate of #329
