### ISSUE TITLE
[Bug]: Download button not clickable for specified area

### ISSUE THREAD

**Issue by Ash-codes18** [th-ch/youtube-music#1355]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 22H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.1.2

### Expected Behavior

The Download Button should be clickable when hovered anywhere on it be it the text or the icon

### Actual Behavior

The Download button is only Clickable when hovered at the empty area beside the text of the button.

![photo_2023-10-29_13-07-07](https://github.com/th-ch/youtube-music/assets/112748790/66a07c3e-ce60-42fa-8eed-dbb650dd19b7)

**Comment by JellyBrick** [comment]
I can't reproduce it on the YTM desktop, it seems to be an internal YouTube issue.
