### ISSUE TITLE
[Bug]:  Audio quality toggler in Settings -> Playback, appears weird

### ISSUE THREAD

**Issue by Ash-codes18** [th-ch/youtube-music#1358]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 22H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.1.2

### Expected Behavior

It should appear like this : 

![image](https://github.com/th-ch/youtube-music/assets/112748790/f370149b-cbe4-4830-88b2-b5eb98a47e77)

### Actual Behavior

But appears like this :

![image](https://github.com/th-ch/youtube-music/assets/112748790/b219774a-ee18-41bf-a70e-f32284123b32)

**Comment by JellyBrick** [comment]
Is it reproducible in https://music.youtube.com?

**Comment by Ash-codes18** [comment]
> Is it reproducible in https://music.youtube.com?

no
