### ISSUE TITLE
[Feature Request]: Add about->version (or show ver somewhere)

### ISSUE THREAD

**Issue by dylanh724** [th-ch/youtube-music#1359]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have no clue what version I'm using

### Proposed Solution

Show version somewhere in the app

### Alternatives Considered

Diving deep to find the ver; too tedious

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/6f308b8b-1573-4393-a2e9-f7d1c812780f)

![image](https://github.com/th-ch/youtube-music/assets/16558115/b848be65-e8e5-47b9-8c93-b69086431bc3)
