### ISSUE TITLE
[Feature Request]: Show App Following the Opening of the Main Executable

### ISSUE THREAD

**Issue by D-Maxwell** [th-ch/youtube-music#1367]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I have found myself unable to show the app (back from the system tray) from a Rainmeter skin I'm currently making. Note that this issue is not related to Rainmeter, as I have come to realise the app will not reveal itself even after the main executable is opened once more (the app is already running in the background).

It actually shows up about 30 seconds or so later, without presenting much feedback to the user. I wish the app would open instantly, as it is already able to do through clicking the `Show App` entry from the system tray context menu.

### Proposed Solution

It would seem `win.show()` is the method called upon clicking the corresponding tray context menu entry ; although I must admit I do not know what is slowing down the loading of the application, especially as it doesn't seem to be doing anything during that time span.

Perhaps there exists a hook related to the executable being opened (as the app is already running that is) which could be hooked to the prior method.

### Alternatives Considered

I could write an AutoHotKey script which I would integrate into my Rainmeter skin, although that would be tedious, not very responsive nor modular, and it would certainly not look as seemless as it should, making for an overall uncomfortable user experience.

### Additional Information

The wait time following the shortcut being opened seems to be much longer than that of a cold boot.
It definitely seems to me like something is not being handled properly in the background.

**Comment by JellyBrick** [comment]
Which version of Windows are you using?
Also, can you tell us the specs of your PC?

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/b1202718-f908-405c-b428-77899a0c62dc)

https://github.com/th-ch/youtube-music/assets/16558115/5f94b70e-c25a-4a34-9a04-7a6992a6522a

**Comment by D-Maxwell** [comment]
> ![image](https://user-images.githubusercontent.com/16558115/281331219-b1202718-f908-405c-b428-77899a0c62dc.png)
> 
>  works.mp4

Obviously, this feature *works*. From the tray context menu, that is.
What I am talking about is launching the app through a shortcut (or the exe directly), and in that specific scenario, the app takes a few dozen seconds before it actually shows up.

**Comment by JellyBrick** [comment]
Are you using a portable version of your application?

**Comment by inson1** [comment]
@JellyBrick same problem

**Comment by D-Maxwell** [comment]
> Are you using a portable version of your application? For portable versions, the app may take a long time to run in certain scenarios due to unpacking operations. Try installing the application using `YouTube...-Web-Setup.exe`.

This appears to have been fixed, either by installing a compiled version of the app, or by upgrading to 3.x. Either way, it now works flawlessly, with very marginal delay.

**Comment by D-Maxwell** [comment]
> @JellyBrick same problem and yes I'm using normal version

Give the winget 3.x release a try
