### ISSUE TITLE
Wierd slider

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1368]
I dont think slider should act like that. Its wierd. It should stop at the line. What do you think? 
![YouTube_Music_haUVWPwu3T](https://github.com/th-ch/youtube-music/assets/75314629/75ada18f-00f8-4822-a072-d132fec7b3f4)

v2.2.0

**Comment by JellyBrick** [comment]
Can't fix. it's an electron and YouTube's issue.
