### ISSUE TITLE
Install without opening

### ISSUE THREAD

**Issue by C4illin** [th-ch/youtube-music#137]
Is it possible to install the program without it opening after installation. The argument "/S" makes the installation silent but it still opens up after the installation which isn't very "silent".

This was the default behavior before 1.8.2.

**Comment by th-ch** [comment]
Hey @C4illin, thanks for the feedback! https://github.com/th-ch/youtube-music/commit/5b8d5d5ee41cff82585262d45f58e68691a0ebbc changes the configuration and should solve this issue, it will ship in the next version!

**Comment by C4illin** [comment]
Thank you for the fix!

**Comment by C4illin** [comment]
Hello, it seems like it still opening with /S in 1.10.0 or am I missing something?

**Comment by C4illin** [comment]
Sorry I didn't see that it was a separate file. Thanks for the fix!
