### ISSUE TITLE
[Bug]: Second menu stays, but Plugin menu disappears

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1373]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

Other (specify below)

### Expected Behavior

1. Option - dont let plugin menu disappear
2. Option - let even the second menu disappear

### Actual Behavior

If I click for example on menu in video-toggle than plugin menu disappear, but that menu stays.
![image](https://github.com/th-ch/youtube-music/assets/75314629/57958022-c6e4-46f8-98b0-d35b3b8686b3)
![brave_ZjIvUWRJyc](https://github.com/th-ch/youtube-music/assets/75314629/ac1d47c2-aa61-457b-b039-4303dce99812)

### Additional Information

I dont know what is arch.

**Comment by inson1** [comment]
@JellyBrick Isnt that electron bug?

**Comment by ArjixWasTaken** [comment]
> I dont know what is arch.

Arch is short for Architecture, there are two main Architectures, x86 and ARM.
And on-top of that, there is the bit-ness, 32bit and 64bit.

If you are not using a laptop, then your arch is most likely x86_64 or also known as amd64.
If you are using a Mac device with an M1 or M2 chip, then your architecture is arm64.

If you are on a really old desktop, then the ia32 option refers to x86
(when the bit-ness is not specified 32bits are assumed)

But either way, this issue does not appear to be specific to an architecture, so it doesn't matter.

**Comment by inson1** [comment]
this is fix at east for me

**Comment by JellyBrick** [comment]
fixed at 62410e9ee28ee686aecabe885fc02033c2b65971
