### ISSUE TITLE
Center video

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1374]
I'm not sure if its bug or feature request, but could set the video on center please? (if there isnt the video toggle button in the way)
In this screenshot it isnt in the center.
![image](https://github.com/th-ch/youtube-music/assets/75314629/ea8e86b0-6185-48fd-8f69-652403f4d5ed)

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/15412348-d64b-4a8e-9b90-84b0194e65ed)

**Comment by inson1** [comment]
@JellyBrick but that only center the custom video toggle. I meant the whole video.
