### ISSUE TITLE
[Bug]: When I do this .... More than the top bar is highlighted

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1375]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

Other (specify below)

### Expected Behavior

Highlight only the panel.

### Actual Behavior

 If I Zoom out and have cursor on Close button etc then more than the top bar is highlighted
![image](https://github.com/th-ch/youtube-music/assets/75314629/683f0311-8601-4e06-89a7-e29296226630)

### Additional Information

Do you want the plugin file?

**Comment by inson1** [comment]
What info?

**Comment by JellyBrick** [comment]
It was a contrast issue on my device

**Comment by JellyBrick** [comment]
I guess it's a result of `titleBarOverlay` not being handled properly in Windows 10.
maybe it's an issue of Electron.

**Comment by inson1** [comment]
@JellyBrick Its just zoom out, or zoom out + something else

**Comment by JellyBrick** [comment]
checked

**Comment by JellyBrick** [comment]
Could you restart the program?
Since the logic has not changed, this issue shouldn't be reproduced.

**Comment by inson1** [comment]
@JellyBrick 
Its reproducible (I restarted the app x times), I played with it (try plugin color album theme? (another buggy plugin (at least for me and if I get it correctly)))
(should I try reinstalling it?)
How to reproduce (I think)
1. Turn on album color theme
2. start video with album color
3. go to default page (page without the theme)
4. top bar doesnt have set size
![ImageGlass_bx3TdnArgB](https://github.com/th-ch/youtube-music/assets/75314629/35eec1cb-8e44-463d-a149-ba8d6ffdbd23)

plugins:
{
	"window-size": {
		"width": 180,
		"height": 90
	},
	"window-maximized": true,
	"window-position": {
		"x": 1180,
		"y": 37
	},
	"url": "https://music.youtube.com/watch?v=sPFT0sa9qe4",
	"options": {
		"tray": true,
		"appVisible": true,
		"autoUpdates": true,
		"alwaysOnTop": false,
		"hideMenu": true,
		"hideMenuWarned": true,
		"startAtLogin": true,
		"disableHardwareAcceleration": false,
		"removeUpgradeButton": false,
		"restartOnConfigChanges": true,
		"trayClickPlayPause": true,
		"autoResetAppCache": false,
		"resumeOnStart": true,
		"likeButtons": "",
		"proxy": "",
		"startingPage": "",
		"overrideUserAgent": false,
		"themes": [],
		"language": "en"
	},
	"plugins": {
		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "In player",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},
		"album-color-theme": {
			"enabled": true
		},
		"ambient-mode": {
			"enabled": false,
			"quality": 50,
			"buffer": 30,
			"interpolationTime": 1500,
			"blur": 100,
			"size": 100,
			"opacity": 1,
			"fullscreen": false
		},
		"audio-compressor": {
			"enabled": false
		},
		"blur-nav-bar": {
			"enabled": false
		},
		"bypass-age-restrictions": {
			"enabled": true
		},
		"captions-selector": {
			"enabled": false,
			"disableCaptions": false,
			"autoload": true,
			"lastCaptionsCode": ""
		},
		"compact-sidebar": {
			"enabled": false
		},
		"crossfade": {
			"enabled": false,
			"fadeInDuration": 1500,
			"fadeOutDuration": 5000,
			"secondsBeforeEnd": 10,
			"fadeScaling": "linear"
		},
		"disable-autoplay": {
			"applyOnce": false
		},
		"discord": {
			"enabled": true,
			"autoReconnect": true,
			"activityTimoutEnabled": true,
			"activityTimoutTime": 600000,
			"playOnYouTubeMusic": true,
			"hideGitHubButton": false,
			"hideDurationLeft": false,
			"listenAlong": true,
			"activityTimeoutEnabled": true,
			"activityTimeoutTime": 600000
		},
		"downloader": {
			"enabled": true,
			"selectedPreset": "mp3 (256kbps)",
			"customPresetSetting": {
				"extension": "mp3",
				"ffmpegArgs": [
					"-b:a",
					"256k",
					"-b:a",
					"256k",
					"-b:a",
					"256k",
					"-b:a",
					"256k"
				]
			},
			"skipExisting": false
		},
		"exponential-volume": {
			"enabled": false
		},
		"in-app-menu": {
			"enabled": true,
			"hideDOMWindowControls": false
		},
		"last-fm": {
			"enabled": false,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
			"api_key": "04d76faaac8726e60988e14c105d421a",
			"secret": "a5d2a36fdf64819290f6982481eaffa2"
		},
		"lumiastream": {},
		"lyrics-genius": {
			"romanizedLyrics": true,
			"enabled": true
		},
		"navigation": {
			"enabled": true
		},
		"no-google-login": {},
		"notifications": {
			"enabled": false,
			"unpauseNotification": false,
			"urgency": "normal",
			"interactive": true,
			"toastStyle": 1,
			"refreshOnPlayPause": false,
			"trayControls": true,
			"hideButtonText": false
		},
		"picture-in-picture": {
			"enabled": true,
			"alwaysOnTop": true,
			"savePosition": true,
			"saveSize": false,
			"hotkey": "P",
			"pip-position": [
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10,
				10
			],
			"pip-size": [
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275,
				450,
				275
			],
			"isInPiP": false,
			"useNativePiP": false
		},
		"playback-speed": {},
		"precise-volume": {
			"enabled": false,
			"steps": 1,
			"arrowsShortcut": true,
			"globalShortcuts": {
				"volumeUp": "",
				"volumeDown": ""
			}
		},
		"quality-changer": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": true,
			"overrideMediaKeys": false,
			"global": {
				"previous": "",
				"playPause": "Ctrl+NumDec",
				"next": "Ctrl+Enter"
			},
			"local": {
				"previous": "",
				"playPause": "",
				"next": ""
			}
		},
		"skip-silences": {
			"onlySkipBeginning": false,
			"enabled": false
		},
		"sponsorblock": {
			"enabled": false,
			"apiURL": "https://sponsor.ajay.app",
			"categories": [
				"sponsor",
				"intro",
				"outro",
				"interaction",
				"selfpromo",
				"music_offtopic"
			]
		},
		"taskbar-mediacontrol": {
			"enabled": true
		},
		"touchbar": {},
		"tuna-obs": {},
		"video-toggle": {
			"enabled": true,
			"hideVideo": false,
			"mode": "disabled",
			"forceHide": false,
			"align": "middle"
		},
		"visualizer": {
			"enabled": false,
			"type": "butterchurn",
			"butterchurn": {
				"preset": "martin [shadow harlequins shape code] - fata morgana",
				"renderingFrequencyInMs": 500,
				"blendTimeInSeconds": 2.7
			},
			"vudio": {
				"effect": "lighting",
				"accuracy": 128,
				"lighting": {
					"maxHeight": 160,
					"maxSize": 12,
					"lineWidth": 1,
					"color": "#49f3f7",
					"shadowBlur": 2,
					"shadowColor": "rgba(244,244,244,.5)",
					"fadeSide": true,
					"prettify": false,
					"horizontalAlign": "center",
					"verticalAlign": "middle",
					"dottify": true
				}
			},
			"wave": {
				"animations": [
					{
						"type": "Cubes",
						"config": {
							"bottom": true,
							"count": 30,
							"cubeHeight": 5,
							"fillColor": {
								"gradient": [
									"#FAD961",
									"#F76B1C"
								]
							},
							"lineColor": "rgba(0,0,0,0)",
							"radius": 20
						}
					},
					{
						"type": "Cubes",
						"config": {
							"top": true,
							"count": 12,
							"cubeHeight": 5,
							"fillColor": {
								"gradient": [
									"#FAD961",
									"#F76B1C"
								]
							},
							"lineColor": "rgba(0,0,0,0)",
							"radius": 10
						}
					},
					{
						"type": "Circles",
						"config": {
							"lineColor": {
								"gradient": [
									"#FAD961",
									"#FAD961",
									"#F76B1C"
								],
								"rotate": 90
							},
							"lineWidth": 4,
							"diameter": 20,
							"count": 10,
							"frequencyBand": "base"
						}
					}
				]
			}
		}
	},
	"__internal__": {
		"migrations": {
			"version": "3.1.0"
		}
	}
}

**Comment by inson1** [comment]
@JellyBrick may you reopen it or did you try it and it didnt work?

**Comment by JellyBrick** [comment]
I tested this issue.
It seems to be caused by Electron's `Window Controls Overlay` not shrinking below a certain size.
