### ISSUE TITLE
Check for updates after one second and not at application start

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#138]
Opened the v.1.8.x version, I viewed the update window (for the v.1.9.0 relase) first, then the Youtube Music main window focused. So, if I dind't watched the update window opened just 0.5 second before, I would probably ignored the update...

****I suggest to you this simple code modification:****
from this:
https://github.com/th-ch/youtube-music/blob/d6f7c543703bb5ba0b618eca831fbb88ca03658c/index.js#L214-L216
to this:
```javascript
	if (!is.dev() && config.get("options.autoUpdates")) {
		setTimeout(autoUpdater.checkForUpdatesAndNotify(), 1000);
		autoUpdater.on("update-available", () => {
```

**Comment by Bellisario** [comment]
Created new issue (#147) because this is non very good explained...

**Comment by th-ch** [comment]
Hey @Bellisario, thanks for the feedback! Closing this issue as a duplicate, progress on this will be tracked in https://github.com/th-ch/youtube-music/issues/147!
