### ISSUE TITLE
[Bug]: Navigation plugin buttons dont work

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1381]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Navigation buttons do something.

### Actual Behavior

Navigation buttons arent clickable. Do nothing.
![YouTube_Music_JR6RAFtn9m](https://github.com/th-ch/youtube-music/assets/75314629/36887582-3ff2-4f9e-8ce6-76d8e5d1c55f)

**Comment by JellyBrick** [comment]
Can't reproduce


https://github.com/th-ch/youtube-music/assets/16558115/cd88ab8b-cbf9-4781-82a3-b53bd711a0f8

**Comment by inson1** [comment]
@JellyBrick it worked one time for like 5 seconds if I "restored down" the window, but never again, its wierd

**Comment by JellyBrick** [comment]
Could you provide a list of the plugins you have enabled?

**Comment by inson1** [comment]
"options": {
		"tray": true,
		"appVisible": false,
		"autoUpdates": true,
		"alwaysOnTop": false,
		"hideMenu": true,
		"hideMenuWarned": true,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"removeUpgradeButton": false,
		"restartOnConfigChanges": true,
		"trayClickPlayPause": false,
		"autoResetAppCache": false,
		"resumeOnStart": true,
		"likeButtons": "",
		"proxy": "",
		"startingPage": "Default",
		"overrideUserAgent": false,
		"themes": []
	},
	"plugins": {
		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "In player",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},
		"album-color-theme": {},
		"ambient-mode": {
			"enabled": false,
			"quality": 50,
			"buffer": 30,
			"interpolationTime": 1500,
			"blur": 100,
			"size": 100,
			"opacity": 1,
			"fullscreen": false
		},
		"audio-compressor": {},
		"blur-nav-bar": {
			"enabled": false
		},
		"bypass-age-restrictions": {
			"enabled": true
		},
		"captions-selector": {
			"enabled": false,
			"disableCaptions": false,
			"autoload": false,
			"lastCaptionsCode": ""
		},
		"compact-sidebar": {
			"enabled": false
		},
		"crossfade": {
			"enabled": false,
			"fadeInDuration": 1500,
			"fadeOutDuration": 5000,
			"secondsBeforeEnd": 10,
			"fadeScaling": "linear"
		},
		"disable-autoplay": {
			"applyOnce": false
		},
		"discord": {
			"enabled": false,
			"autoReconnect": true,
			"activityTimoutEnabled": true,
			"activityTimoutTime": 600000,
			"playOnYouTubeMusic": true,
			"hideGitHubButton": false,
			"hideDurationLeft": false,
			"listenAlong": true
		},
		"downloader": {
			"enabled": true,
			"selectedPreset": "mp3 (256kbps)",
			"customPresetSetting": {
				"extension": "mp3",
				"ffmpegArgs": [
					"-b:a",
					"256k"
				]
			},
			"skipExisting": false
		},
		"exponential-volume": {},
		"in-app-menu": {
			"enabled": true,
			"hideDOMWindowControls": false
		},
		"last-fm": {
			"enabled": false,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
		},
		"lumiastream": {},
		"lyrics-genius": {
			"romanizedLyrics": false
		},
		"navigation": {
			"enabled": true
		},
		"no-google-login": {},
		"notifications": {
			"enabled": false,
			"unpauseNotification": false,
			"urgency": "normal",
			"interactive": true,
			"toastStyle": 1,
			"refreshOnPlayPause": false,
			"trayControls": true,
			"hideButtonText": false
		},
		"picture-in-picture": {
			"enabled": false,
			"alwaysOnTop": true,
			"savePosition": true,
			"saveSize": false,
			"hotkey": "P",
			"pip-position": [
				10,
				10
			],
			"pip-size": [
				450,
				275
			],
			"isInPiP": false,
			"useNativePiP": false
		},
		"playback-speed": {},
		"precise-volume": {
			"enabled": false,
			"steps": 1,
			"arrowsShortcut": true,
			"globalShortcuts": {
				"volumeUp": "",
				"volumeDown": ""
			}
		},
		"quality-changer": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": false,
			"overrideMediaKeys": false,
			"global": {
				"previous": "",
				"playPause": "",
				"next": ""
			},
			"local": {
				"previous": "",
				"playPause": "",
				"next": ""
			}
		},
		"skip-silences": {
			"onlySkipBeginning": false,
			"enabled": true
		},
		"sponsorblock": {
			"enabled": false,
			"apiURL": "https://sponsor.ajay.app",
			"categories": [
				"sponsor",
				"intro",
				"outro",
				"interaction",
				"selfpromo",
				"music_offtopic"
			]
		},
		"taskbar-mediacontrol": {
			"enabled": true
		},
		"touchbar": {},
		"tuna-obs": {},
		"video-toggle": {
			"enabled": true,
			"hideVideo": false,
			"mode": "disabled",
			"forceHide": false,
			"align": "middle"
		},
		"visualizer": {
			"enabled": false,
			"type": "butterchurn",
			"butterchurn": {
				"preset": "martin [shadow harlequins shape code] - fata morgana",
				"renderingFrequencyInMs": 500,
				"blendTimeInSeconds": 2.7
			},
			"vudio": {
				"effect": "lighting",
				"accuracy": 128,
				"lighting": {
					"maxHeight": 160,
					"maxSize": 12,
					"lineWidth": 1,
					"color": "#49f3f7",
					"shadowBlur": 2,
					"shadowColor": "rgba(244,244,244,.5)",
					"fadeSide": true,
					"prettify": false,
					"horizontalAlign": "center",
					"verticalAlign": "middle",
					"dottify": true
				}
			},
			"wave": {
				"animations": [
					{
						"type": "Cubes",
						"config": {
							"bottom": true,
							"count": 30,
							"cubeHeight": 5,
							"fillColor": {
								"gradient": [
									"#FAD961",
									"#F76B1C"
								]
							},
							"lineColor": "rgba(0,0,0,0)",
							"radius": 20
						}
					},
					{
						"type": "Cubes",
						"config": {
							"top": true,
							"count": 12,
							"cubeHeight": 5,
							"fillColor": {
								"gradient": [
									"#FAD961",
									"#F76B1C"
								]
							},
							"lineColor": "rgba(0,0,0,0)",
							"radius": 10
						}
					},
					{
						"type": "Circles",
						"config": {
							"lineColor": {
								"gradient": [
									"#FAD961",
									"#FAD961",
									"#F76B1C"
								],
								"rotate": 90
							},
							"lineWidth": 4,
							"diameter": 20,
							"count": 10,
							"frequencyBand": "base"
						}
					}
				]
			}
		}
	},
	"__internal__": {
		"migrations": {
			"version": "2.2.0"
		}
	}
}

**Comment by inson1** [comment]
It works!  :)
What changed?

please wait before closing :)

**Comment by JellyBrick** [comment]
> It works! :) (in new version) What changed?
> 
> please wait before closing :) lets first try to find out what changed

Electron v27 -> v28
maybe a bug in chromium

**Comment by palves** [comment]
Doesn't work for me on GNU/Linux.  Version 3.1.0, Ubuntu 22.04, KDE.  I have the navigation plugin enabled.

**Comment by palves** [comment]
If I click and hold anywhere in the area above or underneath the search box (up until the divisor line just beneath), or to the right of the search box all the way up to the login picture, inclusive, then the cursor changes to a four-directions-drag cursor, and dragging the mouse moves the window.  It's as if all that area is the window's title/header too, and then the navigation buttons and the profile picture are underneath in z order instead of above?  The search box works as expected, and so do the widgets to the left of the search box.

**Comment by JellyBrick** [comment]
We've figured out how to reproduce this bug.

1. Search for any song.
2. Now, we can't click the navigation buttons.
3. We can't click the navigation buttons before we go to the home screen.
