### ISSUE TITLE
[Bug]: If I click on icon of my account nothing happens

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1396]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

menu shows up

### Actual Behavior

title
and if I do more clicks, then the app is minimalized (partly - the window is only smaller)

### Additional Information

![YouTube_Music_5XqiAfykQn](https://github.com/th-ch/youtube-music/assets/75314629/2f476a36-fbb4-400f-a065-db351a1a3ebf)
I think its related with #1381

**Comment by inson1** [comment]
https://github.com/th-ch/youtube-music/issues/1381#issuecomment-1805677073

**Comment by Iftuga** [comment]
Can confirm, happens to me as well
Also can say that if you scroll down, then both the navigation #1381 and the profile buttons become clickable
They are non-responsive only when your scroll bar is all the way at the top
This also happens only when the in-app menu is enabled

**Comment by inson1** [comment]
@Iftuga for me its isnt clickable even then. But sometimes if my cursor moves throught the edges of profile button then the cursor changes (like if it was clickable).

**Comment by inson1** [comment]
@Iftuga Did you try new version? for me it works.

**Comment by inson1** [comment]
It works! :) (in new version)
What changed?

please wait before closing :) lets first try to find out what changed

**Comment by inson1** [comment]
https://github.com/th-ch/youtube-music/issues/1381#issuecomment-1849267639
@Iftuga still interested in your feedback

**Comment by Iftuga** [comment]
@inson1 
It has not been fixed for me as of 3.1.0.0
It still happens when "in-app menu" plugin is enabled

**Comment by JellyBrick** [comment]
> @inson1 It has not been fixed for me as of 3.1.0.0 It still happens when "in-app menu" plugin is enabled

Could you use DevTools to check if any elements are blocking the screen?

**Comment by Iftuga** [comment]
> > @inson1 It has not been fixed for me as of 3.1.0.0 It still happens when "in-app menu" plugin is enabled
> 
> Could you check using DevTools if any elements are blocking the screen?

While I was messing around with that I noticed that if I toggle compact sidebar then the bug disappears, it only happens when the sidebar is extended
Regarding your question, if I click on "inspect element" and hover my mouse over my avatar, there is no pop up at all, as if nothing is there

**Comment by Yogarpg** [comment]
> > > @inson1 It has not been fixed for me as of 3.1.0.0 It still happens when "in-app menu" plugin is enabled
> > 
> > 
> > Could you check using DevTools if any elements are blocking the screen?
> 
> While I was messing around with that I noticed that if I toggle compact sidebar then the bug disappears, it only happens when the sidebar is extended Regarding your question, if I click on "inspect element" and hover my mouse over my avatar, there is no pop up at all, as if nothing is there

For me is bugged in both ways
Only works when I resize the window

**Comment by inson1** [comment]
ok it happens again but only in minimazied window

**Comment by AbbieDoobie** [comment]
I was trying to switch profile on my account and eventually figured out that the account icon can only be clicked when the program is fullscreen (press F11).

When not in fullscreen, it can't be clicked. I tried scrolling down and clicking, but that didn't work.
