### ISSUE TITLE
[Bug]: Album name support broken in Discord Rich presence and last.fm scrobbling

### ISSUE THREAD

**Issue by skigulz** [th-ch/youtube-music#1408]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.2.0

### Reproduction steps

Discord & last.fm plugins enabled
Listening to a song in youtube-music 2.2.0
Album names no longer appear in last.fm scrobbles or in Discord Rich presence when hovering over the album cover in Discord.

### Expected Behavior

Album names used to work in 2.2.0 (in last.fm scrobbles and while hovering over the album image in Discord rich presence).

### Actual Behavior

Album names no longer appear in last.fm scrobbles or in Discord rich presence.

### Enabled plugins

1. ambient-mode
2. discord
3. last.fm
4. precise-volume
5. taskbar-mediacontrol

**Comment by JellyBrick** [comment]
fixed by 5ec7c346ca0eaeca821717130b47e2260b497de2
