### ISSUE TITLE
[Feature Request]: Add localization / translations

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1411]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Youtube music part is translated. Why not translate the app fully?

### Proposed Solution

title

### Alternatives Considered

.

**Comment by JellyBrick** [comment]
> Youtube music part is translated. Why not translate the app fully?

Because separating hardcoded strings is not easy 😅

We'll do this after we refactor (#1401) the entire app.
