### ISSUE TITLE
[Feature Request]: Taskbar controls

### ISSUE THREAD

**Issue by Unkn0wnRX** [th-ch/youtube-music#1421]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There's no buttons on the taskbar for playback control

### Proposed Solution

Add playback controls like; Play/Pause Rewind/Skip buttons when hovering over the icon in the taskbar, just like Spotify

### Alternatives Considered

X

### Additional Information

X

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/6127629a-fca2-4570-8abe-32b82da98d85)
![image](https://github.com/th-ch/youtube-music/assets/16558115/27a9fa02-92bc-4883-affc-dc05309369fb)

**Comment by JellyBrick** [comment]
Duplicated
