### ISSUE TITLE
[Bug]: discord plugin doesnt do anytthing

### ISSUE THREAD

**Issue by dokococo** [th-ch/youtube-music#1431]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Reproduction steps

discord plugin
discord active shown as status on
nothing happens

### Expected Behavior

song im listening to show in my status

### Actual Behavior

nothing happens

### Enabled plugins

discord

**Comment by bagusnl** [comment]
Same here, both on prebuilt from this repository and self built using latest commit.
Using arRPC standalone on Node v20.5.0 + Vesktop

**Comment by JellyBrick** [comment]
We'll fix this as soon as we're done with #1401

**Comment by bagusnl** [comment]
Can I get a confirmation that https://github.com/th-ch/youtube-music/commit/51e62ef47b6467cbc9090fe4fc077d0aae3cc175 actually fixes this issue? If yes then it could be an issue on my side 

https://github.com/th-ch/youtube-music/assets/28079733/57e64186-9537-4174-9a60-721460fa03fa

arRPC doesn't seem to get any message as shown in baretail window

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/610ec5b3-d60a-441e-8bb2-a84800dff83a)

This issue should fixed by https://github.com/th-ch/youtube-music/commit/51e62ef47b6467cbc9090fe4fc077d0aae3cc175
