### ISSUE TITLE
Play/Pause menu item in taskbar icon Context Menu doesn't pause

### ISSUE THREAD

**Issue by nshannon123** [th-ch/youtube-music#145]
The play/pause button in the taskbar icon's menu won't pause the current playing song. It will play the song if the track is currently paused but pausing it doesn't work.

**Comment by th-ch** [comment]
Hey @nshannon123, thanks for the report! I seem able to reproduce, first conclusions point towards the `auto-confirm-when-paused` plugin, which will unpause the video when you try to pause it if the window is not active - so if you have the `auto-confirm-when-paused` plugin enabled, disabling it should do the trick until a better solution comes out!

**Comment by nshannon123** [comment]
Thanks for the reply. At least you found the issue. Ideally it would be better to have the plugin enabled as well as being able to pause from the taskbar. Hopefully this will be a fix included in a future release!
