### ISSUE TITLE
[Feature Request]: Add support for legacy macOS 10.14/10.15 and iOS ipa build for Youtube Music

### ISSUE THREAD

**Issue by stackoverflow1024** [th-ch/youtube-music#1450]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

## Summary

YouTube Music is a great open source YouTube client for desktop platforms. However, it currently lacks support for older macOS versions (10.14-10.15) still used by many intel-based users. Additionally, an iOS ipa build would allow more iOS users to install YouTube Music on their devices without needing to jailbreak.

## Proposal

Please consider adding:

- Legacy macOS support (10.14-10.15) to allow the app to be used by users still on older Intel-based Macs
- iOS IPA build and distribution so iOS users can install without jailbreaking their devices

## Benefits

By supporting these additional platforms, YouTube Music would be accessible to many more users stuck on older devices or OS versions. 

Specifically:

- A large number of Mac users still rely on 10.14 or 10.15 on Intel-based hardware. Legacy support would allow the app to be used by these users.

- An iOS ipa would dramatically improve accessibility for iOS users, no longer requiring complicated jailbreaking procedures just to install the app. 

## Please consider 

Adding legacy macOS 10.14/10.15 and iOS ipa build support to allow YouTube Music to reach a wider audience across multiple platforms. This would be a big win for the project and users alike.

Let me know if any other information is needed!

### Alternatives Considered

Adding legacy macOS 10.14/10.15 
Adding iOS ipa build support 

To allow YouTube Music to reach a wider audience across multiple platforms. This would be a big win for the project and users alike.

**Comment by ArjixWasTaken** [comment]
This program is merely, as I like to call it, "a glorified WebView".

Electron (the WebView in question) cannot be used on iOS.

In fact iirc chromium itself cannot be used on iOS, the safari browser engine is used even for Google chrome.

For iOS you should probably just use the official app.

https://apps.apple.com/us/app/youtube-music/id1017492454

Sadly no plugins are available there, but that would be out of the scope for this project.

**Comment by stackoverflow1024** [comment]
Hi Angelos,

I appreciate your quick reply about YouTube Music. I successfully downloaded and installed YTMusicUltimate using AltStore, and it is working very well. 

Regarding support for the legacy YouTube Music desktop application on macOS, as you noted, it has an enhanced interface as well as other features like built-in ad blocking/downloading capabilities, easy enable/disable of plugins - features that the native YouTube Music webpage lacks. 

Given these benefits, it would be great if could consider adding support for older macOS versions like 10.14. The legacy desktop app provides a better overall user experience compared to the web version, so supporting legacy platforms would allow more macOS users to take advantage of its features. Please let me know if this expanded legacy support is feasible on your end.

**Comment by JellyBrick** [comment]
In macOS 10.15, `th-ch/youtube-music` is available, but not in 10.14.
This is a restriction of Electron.

https://www.electronjs.org/blog/electron-27-0#removed-macos-1013--1014-support

**Comment by heidaren0000** [comment]
To save your time, here is my build of youtube music 3.2.2 with electron v26, which supports High Sierra(10.13) and Mojave (10.14). 
Everything works fine as far as i know. 
https://drive.google.com/file/d/1KZk34wo2lBRJL9ytZo0haKe7yjK-NKp5/view?usp=sharing

**Comment by stackoverflow1024** [comment]
My goodness, @heidaren0000, you just made my day!
This is exactly what I’ve been searching for, thank you so much!

**Comment by heidaren0000** [comment]
https://www.mediafire.com/file/e5vqt0doytn6q6s/YouTube_Music-3.6.2.dmg/file 
update for youtube music v3.6.2

**Comment by ArjixWasTaken** [comment]
@heidaren0000 is that done using supermium electron or smth?
could you set up automated builds so they are more trust-worthy?

**Comment by heidaren0000** [comment]
> @heidaren0000 is that done using supermium electron or smth? could you set up automated builds so they are more trust-worthy?

wow thank you, i didn't know supermium electron is a thing. 
i solely downgraded the official electron in package.json to v26, and rebuilded the app. i have a laptop running old macOS so i did this and others don't have to. 
i will check out supermium electron and set up automated builds with it, but i'm kinda lazy, maybe serval months later :)
