### ISSUE TITLE
Add all default Developer tools shortcuts (same as in browsers)

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1460]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is already Ctrl+I, but Ctrl+J, F12 are missing. They are already default in browser. 
For example I use Ctrl+J, so I didnt even know about Ctrl+I.

But yes it does have low priority.

### Proposed Solution

.

### Alternatives Considered

.

### Additional Information

Plus #1454

**Comment by JellyBrick** [comment]
Use "Ctrl+Shift+I"
its a default shortcuts on Electron application.
