### ISSUE TITLE
[Feature Request]: Keep last song played saved like YouTube Music mobile apps

### ISSUE THREAD

**Issue by hyoretsu** [th-ch/youtube-music#1467]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We only have "Resume last song when app starts" which plays the song. I don't want to be surprised every time I open the app, I just want to continue what I was last listening to.

### Proposed Solution

Either change the current option or add a new one to play/not play the last song.

### Alternatives Considered

.

**Comment by JellyBrick** [comment]
try enabling "disable-autoplay > Applies only on startup" after enabling `disable-autoplay`
