### ISSUE TITLE
[enhancement/bug] Await 2 seconds to check updates

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#147]
Once an update is available, the app will show to you before loading the main window and, if I wasn't careful, I wouldn't have seen it and have done the update. This simple bug can be resolved with this code change:
###### from this
https://github.com/th-ch/youtube-music/blob/d6f7c543703bb5ba0b618eca831fbb88ca03658c/index.js#L214-L216
###### to this
```javascript
	if (!is.dev() && config.get("options.autoUpdates")) {
		setTimeout(autoUpdater.checkForUpdatesAndNotify(), 2000);
		autoUpdater.on("update-available", () => {
```

**Comment by Bellisario** [comment]
Created new from #138 because the old is non very good explained...

**Comment by th-ch** [comment]
Hey @Bellisario, thanks for the improvement suggestion! https://github.com/th-ch/youtube-music/commit/da61621a62953f476bb68a53e4ae05e14c5b82f2 implements this, it will ship in the next version!

**Comment by th-ch** [comment]
Closing this issue as it should be solved in the latest version, feel free to re-open in case of issue!
