### ISSUE TITLE
[Bug]:  Menu plugins and options not showing up

### ISSUE THREAD

**Issue by PannocchiaGiallo** [th-ch/youtube-music#1477]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Reproduction steps

I tried to install the app via deb package and from git command. 

### Expected Behavior

There should be options and plugins at the top

### Actual Behavior

No option or plugin show up just a blank space
![Screenshot from 2023-12-02 16-42-15](https://github.com/th-ch/youtube-music/assets/120664395/5c0c8085-f8c8-4b92-b76d-5604c63637b1)

### Enabled plugins

no plugins were enabled

**Comment by JellyBrick** [comment]
fixed in 3.0.2
