### ISSUE TITLE
[Bug]: ad blocker doesn't work in latest version

### ISSUE THREAD

**Issue by skyisthela** [th-ch/youtube-music#1478]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 20h2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.2.0

### Reproduction steps

turn on ad blocker, doesn't work

### Expected Behavior

ad blocker block ads

### Actual Behavior

doesn't block ads 

### Enabled plugins

1. ad blocker
2. playback-speed

**Comment by JoshiCodes** [comment]
Had the same thing happening, disabling and enabling the Adblocker seemed to fixed it for me.

**Comment by skyisthela** [comment]
> Had the same thing happening, disabling and enabling the Adblocker seemed to fixed it for me.

i did that, issue still persisted

**Comment by x3rt** [comment]
> fixed in 3.0.2

Just had an ad on 3.0.2.0

**Comment by divStar** [comment]
> > fixed in 3.0.2
> 
> Just had an ad on 3.0.2.0

Same (it was some iPhone 15 ad, that I could pause though and songs worked without ads).

I suppose that's YT fighting ad-blockers and there'll be many more such things coming.

**Comment by ArjixWasTaken** [comment]
> curious but what ad block does this client use? ublock or some custom one?

Two adblocking modes are available,

- WithBlocklists: Uses the following [network filters](https://github.com/th-ch/youtube-music/blob/a3104fda4b0d58b076d0c737111636a66e468acc/src/plugins/adblocker/blocker.ts#L8-L18)
- InPlayer: From my understanding, it manipulates the JSON responses to remove ads. [code](https://github.com/th-ch/youtube-music/blob/f62664b6a570b130e1fa55f11bfa447355ea97b6/src/plugins/adblocker/injectors/inject.js)

**Comment by inson1** [comment]
I had same problem 2 times today - every time after restarting the app (in player option), but after that nothing

Should I open another issue?

**Comment by divStar** [comment]
> In-player blocking, I get ads in 3.0.2, but don't get them in 2.2.0.

I can confirm this.

**Comment by inson1** [comment]
@divStar @ovidiulixandru on start or even later?

**Comment by divStar** [comment]
In Version 2.2.0 I haven't had any ads at all (I am using it regularly on two Mac's), but then I upgraded to 3.0.2 and the ads appeared at the beginning and within a playlist of the same YouTube channel (Epic Music World).

**Comment by skyisthela** [comment]
i think at this point it's better to just use 2.2.0

**Comment by JellyBrick** [comment]
We've already identified the cause of the issue and are working on a fix.

**Comment by Helios747** [comment]
This is still broken for me on v3.3.12 on Linux, MacOS Sonoma and Windows 11. In player adblocker lets ads slip. blocklists doesn't.

Unfortunately blocklists make the app notably less responsive.
<img width="851" alt="image" src="https://github.com/th-ch/youtube-music/assets/6785841/8b62902c-4a79-4aa7-a9b5-9f24bc421955">
