### ISSUE TITLE
[Bug]:(SOLVED) Can't find "Quality Changer" plugin

### ISSUE THREAD

**Issue by hjt1618** [th-ch/youtube-music#1494]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

youtube-music-3.0.2-x64.nsis.7z

### What operating system are you using?

Windows

### Operating System Version

win 11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

latest

### Reproduction steps

Can't find "Quality Changer" plugin , the plugin page tell me the quality changer plugin was at the bottom of video overlay but i cant find that setting icon at the example photo because the whole UI was diffrence from mine to the example photo
![Screenshot 2023-12-04 185815](https://github.com/th-ch/youtube-music/assets/68421732/3341803b-14bd-431d-a00e-d46b1265ab3a)
![Screenshot 2023-12-04 185746](https://github.com/th-ch/youtube-music/assets/68421732/b1de09a4-5958-4bc5-bbde-2f0a32f795b8)
![138574366-70324a5e-2d64-4f6a-acdd-dc2a2b9cecc5](https://github.com/th-ch/youtube-music/assets/68421732/0829c76f-8079-4441-bfa4-92839cf1af16)

### Expected Behavior

-

### Actual Behavior

-

### Enabled plugins

-

### Additional Information

-

**Comment by ArjixWasTaken** [comment]
Since the title was changed to `SOLVED`, does that mean that I can close this issue?
