### ISSUE TITLE
[Bug]: Can't see the app window when launching the app natively on Wayland

### ISSUE THREAD

**Issue by amir-reza-bijandi** [th-ch/youtube-music#1495]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.2

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 39

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.2.0

### Reproduction steps

Trying to run the app natively on Wayland with this two options:
--ozone-platform=wayland --enable-features=WaylandWindowDecorations

### Expected Behavior

Being able to see the app window and interact with it!

### Actual Behavior

The app window is not showing up and when I try to run the app with terminal I get no errors!
**Funny part is that I can hear the last music that I was listening to**, but I have no way of interacting with the app itself!

### Enabled plugins

ad-blocker
downloader
lyric-genius
navigation
quality-changer
sponser-block

### Additional Information

I'm using the RPM build of the app and I can run the 2.2.0 version natively under Wayland just fine, but that's not the case with the v3.0.2 version! **The app window is visible when I run it on Wayland using XWayland**, but that's not desirable because the UI is quite blurry that way because of fractional scaling!

**Comment by sakithb** [comment]
Can confirm happens to me as well

**Comment by JellyBrick** [comment]
Maybe it's a bug in the electron? 
Do you have any screenshots?

**Comment by JellyBrick** [comment]
Are you still experiencing this issue in 3.1.0?

**Comment by amir-reza-bijandi** [comment]
> Are you still experiencing this issue in 3.1.0?

Yes! Sadly the issue persists!

**Comment by amir-reza-bijandi** [comment]
I looked at "package.json" in the main branch, and it seems the app is using Electron v28.0. I installed the same version of Electron in a new project and tried running the main Electron executable with the mentioned options, and it launched perfectly! So, I guess we can assume that this isn't an Electron issue.

**Comment by JellyBrick** [comment]
> > Maybe it's a bug in the electron. Do you have any screenshots?
> 
> I looked at "package.json" in the main branch, and it seems the app is using Electron v28.0. I installed the same version of Electron in a new project and tried running the main Electron executable with the mentioned options, and it launched perfectly! So, I guess we can assume that this isn't an Electron issue. ![Screenshot from 2023-12-11 18-57-20](https://private-user-images.githubusercontent.com/107653240/289584619-d369940f-4cff-447d-843a-1e72e58284b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDE1MjgsIm5iZiI6MTcwMjM0MTIyOCwicGF0aCI6Ii8xMDc2NTMyNDAvMjg5NTg0NjE5LWQzNjk5NDBmLTRjZmYtNDQ3ZC04NDNhLTFlNzJlNTgyODRiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwMDMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzE2MjQ1YmUxNWI2NTVkZTc1NWZkOWI1NjYyMzMwNDk4NDNiN2FkNzQzZGQwNzEzNmY5YTdmOWE1NjBlOWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n24si8xBDzd5c2mDwke-1wqA4SSLs1VtxhATQqfzVmU)

Could you clone this repository and run `pnpm start`?

**Comment by amir-reza-bijandi** [comment]
I cloned the repo, and after running "pnpm install --frozen-lockfile" and "pnpm start" the application launched perfectly, but it was running on Xorg and as I said, running on Xorg is not the issue! So I tried adding command-line arguments to run the app on Wayland, but I couldn't figure out how! So I created a bash script and replaced it with the main electron executable in the "node_modules" folder, **and as was the case with the release version of the app, the application window did not appear**, but the music was playing in the background, and I had no way of interacting with the app!

![Screenshot from 2023-12-12 09-22-24](https://github.com/th-ch/youtube-music/assets/107653240/20c075b0-0207-48a2-bbb0-bd4af7d1d63d)

This is quite sad because this is a really cool app, but it's not usable on modern Linux desktop setups that use the Wayland protocol!

**Comment by ArjixWasTaken** [comment]
It is running through XWayland for me, are you unable to use XWayland?
Is that a limitation for you?

**Comment by amir-reza-bijandi** [comment]
> ~It is running through XWayland for me, are you unable to use XWayland?~ ~Is that a limitation for you?~
> 
> Edit: I launched the program using the flags you provided in the screenshot and it is running through Wayland just fine, no Xorg stuff happening.
> 
> ![image](https://private-user-images.githubusercontent.com/53124886/289780452-3fa26629-db06-480a-b89c-569f152414d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjc4NDMsIm5iZiI6MTcwMjM2NzU0MywicGF0aCI6Ii81MzEyNDg4Ni8yODk3ODA0NTItM2ZhMjY2MjktZGIwNi00ODBhLWI4OWMtNTY5ZjE1MjQxNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA3NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWE1M2MyYjkwNDc0ZDkxZDdkZWY5NzBiN2Y5ZWFhMDQ3OTY4YjBiODgwNzk1YmY5NGRlOGJjM2RkZDU3ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSvgfAkVxvY8qee72vMcaNFr6m4usvdhZE3ysBhnLUY)
> 
> I confirmed that by using xwininfo and xeyes, both couldn't detect the window, so it is natively running under Wayland...
> 
> Here is my edited launch script for this ![image](https://private-user-images.githubusercontent.com/53124886/289782215-96cdb13f-c1d2-4ad1-8e77-bf2cd6a33308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjc4NDMsIm5iZiI6MTcwMjM2NzU0MywicGF0aCI6Ii81MzEyNDg4Ni8yODk3ODIyMTUtOTZjZGIxM2YtYzFkMi00YWQxLThlNzctYmYyY2Q2YTMzMzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA3NTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmQxZDY5OTlhMjUyYWU0ODMxNDVlY2VlYzAwZmUzZDdkM2ZmZThkNzVhODVkMjgxYzA2NzQyMmQ0NDMxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2mdoAT6KI8wzhE2VTyCc2CrFvqMJ2Ptm5LwSBMJGaU)
> 
> (based on the AUR provided launch script)
> 
> PS: I am using electron27 to do this, I haven't tested with electron28, so it is a possibility of that being the fault.

I'm really confused, man... I tested launching the app with both Electron 27 and 28 (which is the version that the app is currently running on) by giving the electron executable the direct path of the "index.js" file created by running "pnpm start" (Just like you showed), and the app window was visible in both versions, **_but when using "pnpm start" and the released binary, the window still does not appear on the screen!_**

Electron 27:
![Screenshot from 2023-12-12 11-35-21](https://github.com/th-ch/youtube-music/assets/107653240/5072cc89-a347-4c44-8923-6e712fa4af89)

Electron 28:
![Screenshot from 2023-12-12 11-37-20](https://github.com/th-ch/youtube-music/assets/107653240/1cb7305d-4b9c-40d4-aeeb-ed65be59a1b7)

**Comment by amir-reza-bijandi** [comment]
I fixed it... Seeing how launching the app directly with Electron executable was working just fine gave me an idea of what is happening! As you can see in the last two screenshots when running the app Directly with Electron, I'm not logged in and the app is using default settings and plugins!

At first, I thought maybe it's a plugin that is causing this, so I launched the app on Xorg and disabled all my plugins, but it didn't fix anything.

Then I decided to delete every user data stored by application, **_so i just simply removed the "YouTube Music" folder in my "/home/user/.config" and it fixed the issue_** and now the app launches just fine under Wayland!

**Just to be sure I installed version 2.2.0 again**, logged in to my account, enabled my plugins and changed my desired settings, removed the application and installed 3.1.0 and the issue occurred again but as I said removing the "YouTube Music" folder in my "/home/user/.config" fixes the issue!

**Comment by ArjixWasTaken** [comment]
SInce you said that the music played fine...what if the program was launched in tray mode and you simply do not have the tray icon due to not having the gnome extension for tray icons?

**Comment by amir-reza-bijandi** [comment]
> SInce you said that the music played fine...what if the program was launched in tray mode and you simply do not have the tray icon due to not having the gnome extension for tray icons?

I do have the extension (you can see it in screenshots on top left of the panel) and the tray option is disabled in the app settings and as I said launching the app through XWayland was working just fine!

**Comment by amir-reza-bijandi** [comment]
The issue is fixed on the latest [v3.2.0](https://github.com/th-ch/youtube-music/compare/v3.1.1...v3.2.0) release!
