### ISSUE TITLE
[enhancement] Clear all App cache once started

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#150]
I suggest to clear all app cache once the app starts because without this change, the cache folder can be (as in my case) 200MB long...
Implementation info [here](https://stackoverflow.com/a/65202658/14997578).

**Comment by th-ch** [comment]
Hey @Bellisario, thanks for the feedback! https://github.com/th-ch/youtube-music/commit/3976d1c8627c5ca184f49296023f4dfe2a44ce5e adds an option to reset cache, it will ship in the next version.

**Comment by Bellisario** [comment]
Hey @th-ch, it's possible to delay cache erase? Because now the app (portable version) takes 13 seconds to starts...
I suggest to you to delay cache erase of about 20 seconds, when the app is completely started.
Anyway, thank you for this new functionality!

**Comment by th-ch** [comment]
Hey @Bellisario, thanks for the feedback! https://github.com/th-ch/youtube-music/commit/70973b22817059e8d81f1d3db288d0d0a77c04c5 clears the cache after 20s, it seems to work ok and will ship in the next version! If finer customization is needed, we can also have the duration in advanced configuration!

**Comment by Bellisario** [comment]
Ok, thank you @th-ch!
