### ISSUE TITLE
[Bug]: YouTube Music RPM version install cannot find libuuid.so candidate for OpenSuse Tumbleweed.

### ISSUE THREAD

**Issue by Bortechino** [th-ch/youtube-music#1508]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.2

### What operating system are you using?

Other Linux

### Operating System Version

OpenSuse Tumbleweed

### What arch are you using?

x64

### Reproduction steps

 zypper  install  youtube-music-3.0.2.x86_64.rpm
OS OpenSuse Tumbleweed.

### Expected Behavior

Youtube Music installed

### Actual Behavior

I have an issue " nothing provides 'libuuid". I have searched for the Opensuse libuuid libraries. There is libuuid1.so.6 version installed. 

### Enabled plugins

All

**Comment by JellyBrick** [comment]
Workaround: https://github.com/jgraph/drawio-desktop/issues/493#issuecomment-1185954309

**Comment by Soymilkrice** [comment]
How are we supposed to utilize this workaround ? As a novice, I'm lost, I would appreciate the help.
