### ISSUE TITLE
Hosted weblate is down

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1518]
Do you know what happened? other projects work.

https://hosted.weblate.org/projects/youtube-music/

![brave_5RaGttYjKJ](https://github.com/th-ch/youtube-music/assets/75314629/514c07ac-025a-435c-b6b0-6ac5470a7f0a)

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/222323b6-f444-436f-b679-8fdb5736d3f0)

🤦

**Comment by JellyBrick** [comment]
Fixed!

**Comment by inson1** [comment]
glossary and "needs editing" were lost :/

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
