### ISSUE TITLE
[Bug]: After using Volume Mixer in Windows 11 and closing the app.  The app will no longer output sound until re-install.

### ISSUE THREAD

**Issue by jordaninthesky** [th-ch/youtube-music#1533]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Reproduction steps

I am using multiple sound outputs with my Windows 11 setup.  1 to the tv for videos and web-content, and 2 to a sound-system for youtube-music.

After closing you-tube music, and opening it again, it will just not output any sound.  Windows won't even register it as doing so.  By reinstalling I am able to fix the issue, until I inevitably reproduce the steps.

### Expected Behavior

To output sound, regardless of channel.

### Actual Behavior

As described in the reproduction steps.

### Enabled plugins

sponser block, in-app menu, navigation

**Comment by JellyBrick** [comment]
Cannot reproduce on Windows 11 23H2.

**Comment by jordaninthesky** [comment]
Thank you for checking.  I am unable to reproduce it now.  Also using 23H2, and nothing has changed about the environment since I reported the issue.  I'll post an update within a couple days if I am able to reproduce the issue or not.

**Comment by jordaninthesky** [comment]
I haven't been able to reproduce the issue.
