### ISSUE TITLE
[Bug]: Last.fm not receiving album art or album title

### ISSUE THREAD

**Issue by devxan** [th-ch/youtube-music#1535]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Reproduction steps

1. Enable Last.fm plugin and set it up.
2. Download [Vencord](https://vencord.dev/) and enable LastFMRichPresence plugin.
3. Play music and watch Discord user profile.

### Expected Behavior

Album art & album showing on Discord profile! (Along with song title and artist, which always show)
![Screenshot of Discord client showing Discord activity, where a song is being played from last.fm with album art](https://github.com/th-ch/youtube-music/assets/57809064/2afb998e-0856-446f-bf17-1385351ca375)
Music playing from a client other than YTM Desktop for this example.

### Actual Behavior

Only song title and artist show on Discord profile. No album art is shown.
![image](https://github.com/th-ch/youtube-music/assets/57809064/df47ded6-f40d-4e9b-97cb-6cc7e471c277)
Scrobble being sent from YTM Desktop app in example above.

### Enabled plugins

Last.fm, Blur Navigation Bar, In-App Menu, Navigation, Skip Silences, SponsorBlock, Taskbar Media Control, Precise Volume, Picture in Picture

### Additional Information

Summary: last.fm plugin not outputting album art correctly as other scrobblers do. 

Songs showing on my Discord profile via [Vencord](https://github.com/Vendicated/Vencord)'s last.fm Rich Presence plugin (not th-ch/youtube-music's Discord RPC, because I want a link to my last.fm profile as a button on my profile) don't show album art from scrobbles. 
Music scrobbled from YT Music on my phone (via [Pano Scrobbler](https://github.com/kawaiiDango/pano-scrobbler)) or the YT Music website (via [Web Scrobbler](https://github.com/web-scrobbler/web-scrobbler)) in a browser show album art on my Discord profile perfectly fine, so I'm confused why scrobbles sent from YT Music desktop don't have album art (in that scenario) and if that could be fixed.

This might've already been discussed in [this comment](https://github.com/th-ch/youtube-music/issues/540#issuecomment-1100889089) and the surrounding issue.

**Comment by JellyBrick** [comment]
fixed by 5ec7c346ca0eaeca821717130b47e2260b497de2
