### ISSUE TITLE
[Bug]: Autoplay not working and player jumps back from end to start of playlist

### ISSUE THREAD

**Issue by piezza** [th-ch/youtube-music#1537]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.1.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Reproduction steps

1. Playback an album
2. enable autoplay
3. select last song of album
4. click next

### Expected Behavior

suggested song from autoplay list should be played

### Actual Behavior

player jumps back to first song in album and suggested autoplay track is not played

### Enabled plugins

Age restriction bypass
In-app menu
Navigation
Downloader
Sponsor block
Adblocker

### Additional Information

I tried same thing in music.youtube.com and there it is working as I expect. I have this behavior since some versions and already deleted the Youtube music profile folder and logged out and logged in again. Nothing changed the behavior

**Comment by JellyBrick** [comment]
In my case, it's the other way around. Even if I disable YouTube Music's autoplay, the next recommended track will play automatically.

![image](https://github.com/th-ch/youtube-music/assets/16558115/162dc6cb-e452-4fa9-ba72-fe43a1648038)
![image](https://github.com/th-ch/youtube-music/assets/16558115/a619c06a-3d1f-43ef-aafd-c4298f5955ad)

This issue is also reproducible on https://music.youtube.com. I think it's an issue in YouTube Music.

**Comment by piezza** [comment]
Maybe this issue can be closed even I don't know why it works now.

I downgraded to version 2.1.3 to find out in what version it broke on my side. Then I was logged out and was asked for my credentials. After logging in again, it worked for all versions I tried. I am not sure why my past log outs did not change anything and now everything is fine again...

**Comment by JellyBrick** [comment]
Okay, I'll close this issue for now.
