### ISSUE TITLE
[Feature Request] Add Miniplayer as a feature

### ISSUE THREAD

**Issue by ViswajithRajagopalan** [th-ch/youtube-music#155]
First off I want to say that this project is simply amazing. 

Before I stumbled upon this repo I downloaded the original YouTube Music Desktop application and saw that it had a Miniplayer feature. I think that adding such a capability to this already immensely better version of YouTube Music would make it incomparable to pretty much any other music application out there.

**Comment by PixlShocK** [comment]
That was one of my favorite features of the ytmdesktop app. It'd be great to see it on this app.

**Comment by PATAPOsha** [comment]
Any update for that?

**Comment by Araxeus** [comment]
Yes, Picture in Picture is already implemented, there is a PR open with finished touches (#685)

Will probably be included in the next release 🙂
