### ISSUE TITLE
[Bug]: Download Feature Disappears

### ISSUE THREAD

**Issue by Mendungo** [th-ch/youtube-music#1551]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.1.1

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.9.1

### Reproduction steps

1. Open App
2. Enable Download plug-in (App resets)
3. download button shows up on track/playlist options
4. Once track/playlist options are dismissed download button disappears from everywhere

### Expected Behavior

Download button is expected to stay shown even if options are dismissed for continuing downloads

### Actual Behavior

Download button disappears once track/playlist options are shown and dismissed for the first time after app launch, forced to restart app in order for download button to show again. 

### Enabled plugins

Download

**Comment by loggin5** [comment]
To me, download single song throws " [ERR_INVALID_URL]:invalid url in: #  " error and the button dissapear. Download full tracklist works ok.
Tried to go back 3.1.0, same error.
