### ISSUE TITLE
Homebrew install improvements and update fixes

### ISSUE THREAD

**Issue by indianets** [th-ch/youtube-music#1561]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

#914 added a way to install with brew
#1514 is still open and things are not optimal

### Proposed Solution

A better way to use brew to install and keep the app installed without any further problems. As I commented on last issue [#issuecomment-1869965602](https://github.com/th-ch/youtube-music/issues/1514#issuecomment-1869965602), I am copying the same text here.

There should be another repository dedicated to brew exactly named `homebrew-youtube-music` under `th-ch` (or any other github account, but this is best to identify and keep it in his account) and just have `youtube-music.rb` cask definition inside that, after which users would just need these --

```
brew install th-ch/youtube-music/youtube-music
```

**OR**

```
brew tap th-ch/youtube-music
brew install youtube-music
```

tap is needed only once on any system, Homebrew will automatically fetch the latest cask definition from github and install whatever is mentioned there.

Edit: Subsequent `brew upgrade youtube-music` or `brew upgrade --greedy` (by default brew only updates formula, not casks), will be seamless and these kind of issues can be avoided once and for all.

### Alternatives Considered

As the app is not signed, it is impossible to get it into the official homebrew/cask repo

### Additional Information

I have created a repo https://github.com/indianets/homebrew-youtube-music which you can fork and update readme just replacing `indianets` to `th-ch`. I have kept my username in the readme so that one can test it. Once you do so, I will delete the repo or archive as you suggest.

The install output from brew -

```
% brew install indianets/youtube-music/youtube-music --no-quarantine
==> Tapping indianets/youtube-music
Cloning into '/opt/homebrew/Library/Taps/indianets/homebrew-youtube-music'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 11 (delta 1), reused 11 (delta 1), pack-reused 0
Receiving objects: 100% (11/11), done.
Resolving deltas: 100% (1/1), done.
Tapped 1 cask (14 files, 7.8KB).
==> Downloading https://github.com/th-ch/youtube-music/releases/download/v3.1.1/YouTube-Music-3.1.1-arm64.dmg
Already downloaded: /Users/vijay/Library/Caches/Homebrew/downloads/cd186cf010a59a4cc70cdbb876c5a3d6118c25effc9b2a01e277889b65b958f9--YouTube-Music-3.1.1-arm64.dmg
==> Installing Cask youtube-music
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving App 'YouTube Music.app' to '/Applications/YouTube Music.app'
🍺  youtube-music was successfully installed!
```

Tap from repository

```
 % brew tap | grep youtube
indianets/youtube-music
```

Thank you

**Comment by ArjixWasTaken** [comment]
Just curious, homebrew claims that it is `"The Missing Package Manager for macOS (or Linux)"`, but from what I see only MacOS is supported by the "cask".

I also have never seen homebrew used outside of MacOS, and most likely nobody distributes linux software via homebrew.
So this got me really curious if anybody at all uses homebrew outside of MacOS.

would it even make sense to use it outside of MacOS?
does it even work outside of MacOS?

**Comment by indianets** [comment]
@ArjixWasTaken You are right about Casks. Casks are GUI programs for macOS and macOS only.

Homebrew has 2 official taps(think of these as app indexes), `homebrew/core` which consists formulae(CUI programs) and `homebrew/cask` which is GUI programs. I think the intention to add Linux layer in Homebrew has to do with the way `forumula` works.. they compile it from source on many macOS versions with CI/CD and make it available for installation, adding Linux is just about adding one more arch to compile that formula.

I agree with you on this making less sense on Linux, as package managers are the essential part of all Linux distributions. I can only think of scenarios where someone is moving from macOS to Linux, he might feel like home in that case.

> does it even work outside of MacOS?
Formulae from `homebrew/core` do work on Linux for that matter, but Casks from `homebrew/cask` don't.

That said, this issue is for macOS only! 
README in youtube-music has `brew` as the official method to install and it has many issues.

**Comment by ArjixWasTaken** [comment]
Thx for clearing up my confusion!
Yes I do understand this issue is about MacOS, and I did not intend for you to add Linux support via brew.

I was just curious and you seemed like a knowledgeable person!

**Comment by th-ch** [comment]
👋 Thanks for raising the issue! https://github.com/th-ch/homebrew-youtube-music has been created and [this repo updated](https://github.com/th-ch/youtube-music/commit/f46c431f4c303a39a7ac0bd8adf583e34f836e94)! Closing, feel free to reopen if needed 😃
