### ISSUE TITLE
[Bug]: Tuna plugin not connecting but opening ports over and over

### ISSUE THREAD

**Issue by Tyr808** [th-ch/youtube-music#1568]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.1.1.0

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 11 10.0.22631 Build 22631

### What arch are you using?

x64

### Reproduction steps

1. Enable Tuna OBS plugin

### Expected Behavior

The Tuna OBS plugin should allow the Youtube Music Desktop application to be selectable in the "Windows Media Control" section of the Tuna options within OBS.

### Actual Behavior

The selected media player bar is missing the Youtube player option, and you can see ports opening over and over in the windows resource monitor. If the Tuna plugin is removed, the port behavior no longer occurs.

![image](https://github.com/th-ch/youtube-music/assets/37057735/853eeebf-41c0-49e5-a3a2-ea81e1e9d3e5)

### Enabled plugins

1. Crossfade [beta]
2. In-App Menu
3. Navigation
4. Picture in-picture
5. Precise Volume
6. Skip Disliked Songs
7. Skip Silences
8. Tuna

(Have tried only Tuna, but this was the initial list of plugins and what I would run if no issues)

### Additional Information

As a side note, you can briefly see the correct option in the Tuna OBS options when you restart the Youtube Music Desktop app when restarting the app regardless of whether the plugin is enabled, but it won't ever connect. I also have other applications successfully operating on localhost without issues, having them enabled or not doesn't help.

As troubleshooting methods I've tried full power cycles of the PC as well as the router (and modem because why not). I've tried allowing YTM desktop through the windows firewall as well as running the application in admin and regular modes. The Tuna OBS plugin itself is behaving as expected with every other music source.

**Comment by Tyr808** [comment]
P.S. accidentally closed, meant to add the additional piece of information that I installed the application itself via the official Scoop bucket, and that in addition to reboots I also forced a reinstall of the application and deleted the appdata folder to try a fresh configuration.

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/27316f9d-e93b-467d-b235-a9b3a27eb5cf)

It's not a bug.
Your `tuna-obs` is misconfigured.
The song source of tuna-obs should be set to **`Web browser`** and `host/receive information on local webserver with port` should be set to `1608`.

![image](https://github.com/th-ch/youtube-music/assets/16558115/c51b1de0-78f4-401a-bb05-35cf5ecf981d)

**Comment by Tyr808** [comment]
> ![image](https://private-user-images.githubusercontent.com/16558115/293525545-27316f9d-e93b-467d-b235-a9b3a27eb5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDQ5NjcsIm5iZiI6MTcwNDEwNDY2NywicGF0aCI6Ii8xNjU1ODExNS8yOTM1MjU1NDUtMjczMTZmOWQtZTkzYi00NjdkLWIyMzUtYTliM2EyN2ViNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEwMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNzU4MGIyNjk5NmRiMGQ3MTY0MjJlNzNiOWYxZmYxNDYwMGRiNjYzN2E4MWFhODczNDRlZTIwMWRmOTViY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qBzl2ww01xPIesbPabwf_XSJkobmwUku6XhiaDGUNg8)
> 
> It's not a bug. The `tuna-obs` plugin uses TCP ports to "connect" to the tuna-obs server. This is normal behavior for TCP's connection process. Also, your `tuna-obs` is misconfigured. The song source of tuna-obs should be set to **`Web browser`** and `host/receive information on local webserver with port` should be set to `1608`.
> 
> ![image](https://private-user-images.githubusercontent.com/16558115/293525582-c51b1de0-78f4-401a-bb05-35cf5ecf981d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDQ5NjcsIm5iZiI6MTcwNDEwNDY2NywicGF0aCI6Ii8xNjU1ODExNS8yOTM1MjU1ODItYzUxYjFkZTAtNzhmNC00MDFhLWJiMDUtMzVjZjVlY2Y5ODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEwMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTBkNzhjNmI4MDNhYTM5YmY2YTNjODkxOTdkNjEwYTMyMGFjZjAzMDlmZDNmMGFmYTMyZTdlZDYyYjYwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7VKrnrh_4pX-ilKVw6_Psv2_dJ2QdmjR232BXEnlT8A)

Thanks! I somehow was actually getting this to work via my erroneous method in the past, and had swapped back to this app from spotify again and now it wasn't working, but I had also had something else that was causing this app to lose media key control which explains it.

This is much smoother up properly now, appreciate it!
