### ISSUE TITLE
[Feature Request]: Localization of artist name and titles

### ISSUE THREAD

**Issue by Kellen-wq** [th-ch/youtube-music#1576]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Some artists names and track titles are not localized. in YouTube some names are adjusted to the interface language.

### Proposed Solution

is it possible to choose the language in which they will be displayed? or at least have names in the same localization as the interface

### Alternatives Considered

![image](https://github.com/th-ch/youtube-music/assets/76692731/d40e4cbb-486c-41e3-a8de-f8b6f03aaa5b)
> App with japanese interface

![image](https://github.com/th-ch/youtube-music/assets/76692731/31d1dc55-92a4-4941-86f9-41d4e0f60a32)
> original youtube music with japanese interafce

**Comment by JellyBrick** [comment]
We can't solve this issue because YouTube sends us localized data.
