### ISSUE TITLE
NEW shouldnt care about patch versions

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1580]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I downloaded the new version, but I didnt see the NEW keyword, because of patch version.

### Proposed Solution

title

### Alternatives Considered

idk

**Comment by Su-Yong** [comment]
resolved at 81145b52b7c0366282a0d2d867823b1d2a4c99a3
