### ISSUE TITLE
[Bug]: is impossible to install the app in macos 10.13.6 (high sierra)

### ISSUE THREAD

**Issue by ximenamajor** [th-ch/youtube-music#1590]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

1.20.0

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

macOS

### Operating System Version

macos 10.13.6 (High Sierra)

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Reproduction steps

install the application from img or with brew 

### Expected Behavior

a working version of the app

### Actual Behavior

can't install the application, it does not work anymore :-(

### Enabled plugins

adblocker (with blocklist)
bypass age restrictions
navigation
shortcuts

### Additional Information

it is possible to compile the app for old macoses (high sierra)?
thanks for your work, anyway

**Comment by JellyBrick** [comment]
We can't. because electron and Chromium do not support it. 

see below
- https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-270
- https://chromium-review.googlesource.com/c/chromium/src/+/4629466
