### ISSUE TITLE
how do you load plugins?

### ISSUE THREAD

**Issue by anytarseir67** [th-ch/youtube-music#1598]
all the readme says is `Create a folder in plugins/YOUR-PLUGIN-NAME`

but it never actually says where the plugins folder lives, and i can't find it anywhere.

sidenote: am i blind or is there essentially no documentation for plugins?

**Comment by JellyBrick** [comment]
oops, I forgot to edit the documentation after moving the `plugins` directory to `src/plugins`.

**Comment by anytarseir67** [comment]
wait so do i have to rebuild the whole app to get a custom plugin?

**Comment by JellyBrick** [comment]
> wait so do i have to build the app to get a custom plugin?

yes.

https://github.com/th-ch/youtube-music#build
