### ISSUE TITLE
download quality

### ISSUE THREAD

**Issue by senolfndk** [th-ch/youtube-music#1600]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

![Ekran görüntüsü 2024-01-06 084132](https://github.com/th-ch/youtube-music/assets/52818836/749c119b-7c10-4aed-8bf5-05978e832e90)

### Proposed Solution

change download quality
128kbps
256bkps
320bkps

### Alternatives Considered

change download quality
128kbps
256bkps
320bkps

### Additional Information

change download quality
128kbps
256bkps
320bkps

**Comment by JellyBrick** [comment]
You can customize it in config.json.

**Comment by senolfndk** [comment]
> Config.json'da özelleştirebilirsiniz.

I'm new to this, can you explain how it's done?
