### ISSUE TITLE
[Bug]: “YouTube Music” is damaged and can’t be opened. You should move it to the Bin. [YouTube Music 3.2.2 arm64]

### ISSUE THREAD

**Issue by nbinding** [th-ch/youtube-music#1605]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2 arm64

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1.2 (23B92)

### What arch are you using?

arm64 (including Apple Silicon)

### Reproduction steps

Dragged app into Applications from dmg and opened

### Expected Behavior

App should open

### Actual Behavior

APp refuses to open an displays: “YouTube Music” is damaged and can’t be opened. You should move it to the Bin.

### Enabled plugins

None, app cannot open

### Additional Information

When I run the non arm64 version it is incredibly slow to open and run,

**Comment by pixthehe** [comment]
run `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music#macos

**Comment by livingperson** [comment]
> xattr -d com.apple.quarantine /Applications/YouTube\ Music.app

Had this issue today after updating to [v3.5.1](https://github.com/th-ch/youtube-music/compare/v3.5.0...v3.5.1) from [v3.5.0](https://github.com/th-ch/youtube-music/compare/v3.4.1...v3.5.0).  This fix fixed it, but why did v3.5.0 work and v3.5.1 didn't?

**Comment by ArjixWasTaken** [comment]
> > xattr -d com.apple.quarantine /Applications/YouTube\ Music.app
> 
> Had this issue today after updating to [v3.5.1](https://github.com/th-ch/youtube-music/compare/v3.5.0...v3.5.1) from [v3.5.0](https://github.com/th-ch/youtube-music/compare/v3.4.1...v3.5.0). This fix fixed it, but why did v3.5.0 work and v3.5.1 didn't?

when you download files using safari, it places an attribute to the files to quarantine them
dunno about other browsers

**Comment by livingperson** [comment]
> or you may have downloaded the app using chrome/firefox

Thanks, yes, downloaded via Chrome. Happened again with 3.5.2, so from what you're saying, it sounds like it will happen each time. 

I've tried using right-click options ("Run" is not one of them, I assume you may be thinking of Windows here) on older versions, but they don't seem to have the issue.  Strange - will try right-click and "Open with" on the next update.

**Comment by ArjixWasTaken** [comment]
this thread may help

https://apple.stackexchange.com/questions/373176/disable-the-use-of-the-com-apple-quarantine-extended-attribute-on-mojave
