### ISSUE TITLE
[Bug]: nav bar is larger than on the original site

### ISSUE THREAD

**Issue by ZeDarkAdam** [th-ch/youtube-music#1606]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631.2861)

### What arch are you using?

x64

### Reproduction steps

just run app
![Знімок екрана 2024-01-08 122721](https://github.com/th-ch/youtube-music/assets/80891624/4a2fcaad-41d5-4af1-b0b7-19340b90cc47)

this also extends to the sidebar
![Знімок екрана 2024-01-08 124955](https://github.com/th-ch/youtube-music/assets/80891624/8743ae29-0caa-49b0-9f82-3dab3e4a7495)

### Expected Behavior

smaller nav bar size like this in the edge web app

### Actual Behavior

nav bar is noticeably larger than in the edge web app

### Enabled plugins

1. Exponential Volume
2. Navigation
3. Blur Nav Bar
4. Music Together
5. Sponsorblock

**Comment by JellyBrick** [comment]
This is an intentional change.

https://github.com/th-ch/youtube-music/blob/2ed949920fe03ca7c6ac14bc4a368e9910165dc8/src/youtube-music.css#L22-L25
