### ISSUE TITLE
[Feature Requests] Clear Queue / Homepage & Discord Current Song Reporting Timeout

### ISSUE THREAD

**Issue by ashirbhallalevine** [th-ch/youtube-music#161]
I just found this app a few days ago and it's fantastic! I have a few feature requests that I think would be fairly easy to integrate and would make the app experience a lot better.

1. Please add the ability to clear the current queue by refreshing the app to the homepage "https://music.youtube.com/" via an on-screen button near or between the back/forward buttons. Additionally, please add a plugin/option such that the app automatically reverts back to the YouTube Music homepage upon quitting and reopening it. I have attached a screenshot for the location in the advanced options where this automatic reversion may be able to take place:
![image](https://user-images.githubusercontent.com/79185418/108160463-fb1b9f80-709d-11eb-86ff-bc3f83a674a3.png)

2. _Edit: I've removed the second feature request from this thread and started a new one as recommended by @NNowakowski._ 

Thank you for creating this wonderful app. Please do let me know if you have any questions about the above feature requests and I would be more than happy to clarify!

**Comment by NNowakowski** [comment]
> Additionally, please add a plugin/option such that the app automatically reverts back to the YouTube Music homepage upon quitting and reopening it

I've added this option in #177

**Comment by NNowakowski** [comment]
@ashirbhallalevine The update containing the "resume" option is now live.
You can disable the behaviour via the options menu, the default behaviour is to resume songs when the app is restarted.

**Comment by ashirbhallalevine** [comment]
> @ashirbhallalevine The update containing the "resume" option is now live.
> You can disable the behaviour via the options menu, the default behaviour is to resume songs when the app is restarted.
> 
> For the other feature request I suggest creating a new issue so that one can be tracked individually and this one be closed afterwards.

Thank you for letting me know! I saw the update when it came out since I subscribed to new release notifications and downloaded it on both of my devices immediately. Would you suggest that I create a new issue thread for the second feature request I had in the above message or just make them separately in the future?
