### ISSUE TITLE
[Feature Request]: Change playing to listening in discord RPC

### ISSUE THREAD

**Issue by YUG38** [th-ch/youtube-music#1613]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Playing isn't really a right word to use, listening would be better because we listen to song

### Proposed Solution

add `type: ActivityType.Listening,` to `src/plugins/discord/main.ts` in `const activityInfo: SetActivity = {}`

### Alternatives Considered

Idk

**Comment by JellyBrick** [comment]
When "Listening" is enabled, the remaining time cannot be displayed.

**Comment by YUG38** [comment]
![Screenshot 2024-01-10 at 3 48 28 PM](https://github.com/th-ch/youtube-music/assets/112211279/b6bbdc6d-caaf-4f2f-ac71-d414d62f2d74)
Spotify uses listening and it still shows the time thingy

**Comment by JellyBrick** [comment]
> ![Screenshot 2024-01-10 at 3 48 28 PM](https://private-user-images.githubusercontent.com/112211279/295723785-b6bbdc6d-caaf-4f2f-ac71-d414d62f2d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mjc2NDEsIm5iZiI6MTcwNDkyNzM0MSwicGF0aCI6Ii8xMTIyMTEyNzkvMjk1NzIzNzg1LWI2YmJkYzZkLWNhYWYtNGYyZi1hYzcxLWQ0MTRkNjJmMmQ3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQyMjU1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWY3YzgyM2MwZWI4MGI5NTdhMDhiYjZhZDE1MTI5MjJkMDI5YmFjMzMwZjlhNTQ5ZDY2NGY5MDhlMWI0OWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NyiJY7S347ZYIFHr22iMYu7zXMhY_FnOSoQ2MUyEsoU) Spotify uses listening and it still shows the time thingy

Timebars and timestamps are "only" allowed for `Spotify`.

**Comment by YUG38** [comment]
Oh ok

**Comment by JellyBrick** [comment]
We'll leave this issue open, as Discord may allow this behavior (timebar or timestamps) for other applications in the future.

**Comment by YUG38** [comment]
@JellyBrick think its possible now? 🤔, or still not there yet

**Comment by CyberRodeo** [comment]
Would be very interesting, if we had this

**Comment by YUG38** [comment]
@Covkie that's what I am saying 🗣️🗣️
