### ISSUE TITLE
[Bug]: Tray Tooltip doesn't display song info on restart

### ISSUE THREAD

**Issue by aarush-dev** [th-ch/youtube-music#1621]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2.1

### Reproduction steps

1. Start a song radio (or you could start playing a song, skip to the next song in autoplay)
2. Restart the app with "Resume last song when app starts" enabled

### Expected Behavior

The taskbar tooltip is supposed to show the song title and artist
![image](https://github.com/th-ch/youtube-music/assets/74783625/5242cb6b-f73d-4b7b-9061-0643a494abca)

### Actual Behavior

The taskbar tooltip is not showing the song or the artist
![image](https://github.com/th-ch/youtube-music/assets/74783625/27e81810-3aff-436d-8ce1-205972803835)
![image](https://github.com/th-ch/youtube-music/assets/74783625/52085f08-9bef-4563-8728-0f5bab054114)

### Enabled plugins

1. Tray
2. Resume last song when app starts

### Additional Information

I think there is some issue where it is not able to fetch the song info whenever the app restarts but at the same time it doesn't seem to affect when only a song is played rather than a radio.

**Comment by inson1** [comment]
on win10 I dont have "The taskbar tooltip is supposed to show the song title and artist" feature, how could I turn it on? or it isnt there?

**Comment by Destroy666x** [comment]
I also experienced some inconsistent problems with it while coding this, it seemed to work in the dev version in the end, but now on live version it doesn't again indeed. I think something is wrong with the callback priority causing also few other startup bugs with the app, but not sure what as I didn't dig that deep.
