### ISSUE TITLE
[Enhancement] Do not save duplicate pip sizes/positions in config

### ISSUE THREAD

**Issue by inson1** [th-ch/youtube-music#1632]
Thank you :)
> 			"pip-position": [
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				10,
> 				856,
> 				52,
> 				9,
> 				9,
> 				8,
> 				8
> 			],
> 			"pip-size": [
> 				450,
> 				275,
> 				450,
> 				275,
> 				450,
> 				275,
> 				450,
> 				275,
> 				450,
> 				275,
> 				450,
> 				275,
> 				450,
> 				275,
> 				136,
> 				63,
> 				138,
> 				65,
> 				452,
> 				276
> 			],

**Comment by JellyBrick** [comment]
This issue fixed at a3a411e19716c2ab81824b08cfb0e3862dba6952
