### ISSUE TITLE
[Bug]: Volume mutes randomly

### ISSUE THREAD

**Issue by tejonaco** [th-ch/youtube-music#1633]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Reproduction steps

Playing normaly, suddenly music stops playing, track keeps running, volume icon is shown as normal, muting and unmuting music with this button do the trick and music starts sounding again.

### Expected Behavior

volume keep in same level.

### Actual Behavior

Playing normaly, suddenly music stops playing, track keeps running, volume icon is shown as normal, muting and unmuting music with this button do the trick and music starts sounding again.

### Enabled plugins

default

**Comment by JellyBrick** [comment]
Can you provide reproduction steps?

**Comment by tejonaco** [comment]
> Can you provide reproduction steps?

Sure. Just start a new radio based on a song, minimice the app and do other stuff for 5-10 minutes.
I think this also occurs when skiping the song some times, but not always.

It happens both with bluetooth headphones and built in speakers, I used to have other apps opened but without media, right now I have only this github tab on windows and this is happening.

**Comment by waterblock79** [comment]
Same problem. Mute occurs when I pause the music and resume it again, and can recover the volume by changing the volume.

**Comment by tejonaco** [comment]
new info: it happens a lot when music is on, app is minimized and I open the window

**Comment by waterblock79** [comment]
> Same problem. It also occurs when I pause the music and resume it again, and can recover the volume by changing the volume.
> 
> Reporting this error constantly, I have no idea whether is related to the problem:
> 
> ```
> youtube-music.iife.js:1180 Uncaught TypeError: Cannot read properties of null (reading 'secondsBeforeEnd')
>     at HTMLVideoElement.m (youtube-music.iife.js:1180:13186)
> ```

The error and the problem seems disappeared after I turned off the crossfade.

**Comment by tejonaco** [comment]
> > Same problem. It also occurs when I pause the music and resume it again, and can recover the volume by changing the volume.
> > Reporting this error constantly, I have no idea whether is related to the problem:
> > ```
> > youtube-music.iife.js:1180 Uncaught TypeError: Cannot read properties of null (reading 'secondsBeforeEnd')
> >     at HTMLVideoElement.m (youtube-music.iife.js:1180:13186)
> > ```
> 
> The error and the problem seems disappeared after I turned off the crossfade.

I realised that I also have crossfade enabled, tested to turn it off and so far the problem is solved for me too.
So maybe the bug should be renamed to "Volume mutes using crossfade plugin", or by creating another issue, I don't know how this is used to be done.

**Comment by tejonaco** [comment]
Wow, very quick response. Thanks to the team!!
