### ISSUE TITLE
[Bug]: library will only partially load

### ISSUE THREAD

**Issue by Transpire4678** [th-ch/youtube-music#1634]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 10 home version 22H2

### What arch are you using?

x64

### Reproduction steps

1.open app
2. click library tab
3. list of albums continues to buffer

### Expected Behavior

 library to load

### Actual Behavior

1.open app
2. click library tab
3. list of albums continues to buffer

### Enabled plugins

1. adblocker
2. album actions
3. album color theme
4. bypass age restrictions
5. in app menu
6. Last.fm
7. navigation 
8. sponsorBlock

### Additional Information

![Screenshot (2) 1](https://github.com/th-ch/youtube-music/assets/156462712/86db6b0b-bfb0-4031-80d9-aea1111c56c7)

**Comment by JellyBrick** [comment]
This issue is also reproducible on the official web version of YTM. This is not an issue with the YTMD.
