### ISSUE TITLE
[Bug]: Plugin 'Ambiant Mode'

### ISSUE THREAD

**Issue by KLalamex59** [th-ch/youtube-music#1641]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What arch are you using?

x64

### Reproduction steps

1. Enable the plugin '**Ambiant Mode**'.
2. Play a song (_working_).
3. Play a video (_not working, need to disable/re-enable the plugin to make it work_).

### Expected Behavior

Reloading the plugin whenever links change might potentially resolve this issue, although I don't consider it an optimal optimization technique.

### Actual Behavior

When the '**Ambient Mode**' plugin is activated, it doesn't funtion properly _when playing music with a video clip_;
it only works for songs without videos.

### Enabled plugins

1. Adblocker (In Player)
2. Ambient Mode
3. Blur Navigation Bar
4. Captions Selector
5. Compact Sidebar
6. Discord Rich Presence
7. Downloader
8. In-App-Menu
9. Lyrics Genius
10. Music Together [Beta]
11. Navigation
12. Picture-In-Picture
13. Playback Speed
14. Precise Volume
15. Skip Disliked Songs
16. Taskbar Media Control
17. Video Quality Changer
18. Video Toggle

![image](https://github.com/th-ch/youtube-music/assets/125516170/79635f56-ac42-4f55-acf8-0b4e7bf123a5)

**Comment by JellyBrick** [comment]
![YouTube_Music_5ZKgoRU6Cb](https://github.com/th-ch/youtube-music/assets/16558115/d33db76d-9cc3-40fd-a62a-3a0ae1feda3c)

It seems works

**Comment by KLalamex59** [comment]
😴😴😴😴
![image](https://github.com/th-ch/youtube-music/assets/125516170/b9b0d954-c92a-46d1-9fee-f73e6f1a79fd)

**Comment by inson1** [comment]
@KLalamex59 did you restart the app?

**Comment by Hadeik** [comment]
https://drive.google.com/file/d/1fRATLaTWVXDJKBBgXFNcQIv18cWrnA98/view?usp=drive_link
I have the same issue. this link is to video i google drive.

**Comment by ArjixWasTaken** [comment]
You can directly upload videos to GitHub, is your video so big that the upload fails?

**Comment by Hadeik** [comment]
First yes it is too big 20MB (LIMIT 10)
And second i game everyone with link Access.

**Comment by KLalamex59** [comment]
> https://drive.google.com/file/d/1fRATLaTWVXDJKBBgXFNcQIv18cWrnA98/view?usp=drive_link I have the same issue. this link is to video i google drive. (Windows 11 23H2 x64)

Yeah i've the same...
Now we just have to wait for him to decide to change "**_cannot-reproduce_**" 🤣🤣

**Comment by frostybiscuit** [comment]
I've had the same issue on my end and decided to tinker with it for a bit. I ended up getting it to work by reworking the plugin a bit and using CSS purely for positioning and sizing instead of JS calculations. It also fixes the issue where the ambient size is broken after switching to the mini-player and back.
I have the branch ready locally, I would only need to get the permission to publish my branch and create the PR.

**Comment by ArjixWasTaken** [comment]
Just make a fork and open the PR?

**Comment by craftgeil** [comment]
I have the same problem and keep coming back to this bug, to see if it gets figured out lol
