### ISSUE TITLE
App continously crashing

### ISSUE THREAD

**Issue by kirk781** [th-ch/youtube-music#165]
I was fiddling with the shortcuts plugin and apparently entered wrong parameters in the text file. The next time, I tried to open the app, it thew a json error. No issues. I reinstalled it. Still, it won't open. Cleared all temporary files, restarted the PC, reinstalled the app but still, it throws an error and won't open. What should I do?

**Comment by Bellisario** [comment]
****This is a solution that erase all config files and all saved data in your app saved locally****
Try to open `%appdata%` in the Explorer (you need to enter it manually) and delete the `YouTube Music` folder.
Now you you should be able to restart the app...

**Comment by kirk781** [comment]
Thanks. That works. I was only deleting the temp files stored in the AppData\Local and neglected to check the Roaming subfolder.
