### ISSUE TITLE
[Feature Request]: Plugin: Shortcuts has shortcuts for song upvotes / downvotes

### ISSUE THREAD

**Issue by eimirae** [th-ch/youtube-music#1652]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I tried looking in the shortcuts source code, and I couldn't see a way to set a config entry up for a shortcut that will thumbs up or thumbs down a song.

### Proposed Solution

Add the correct binding to the source code

### Alternatives Considered

All the binding option to the UI

### Additional Information

Thanks!

**Comment by inson1** [comment]
local or global?

**Comment by eimirae** [comment]
Global I think

**Comment by inson1** [comment]
@eimirae https://github.com/th-ch/youtube-music/issues/783
so please close it

**Comment by eimirae** [comment]
Thanks!
