### ISSUE TITLE
[Bug]: SIGSEGV when closing the app

### ISSUE THREAD

**Issue by daguilarv** [th-ch/youtube-music#1655]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS 14.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1 . Just closing the app I got a SIGSEV error and a report ready to send it to apple

### Expected Behavior

Not error when closing the app

### Actual Behavior

A report error is shown.

### Enabled plugins

Default plugins enabled

### Additional Information

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010

VM Region Info: 0x10 is not in any region.  Bytes before following region: 61478027657200
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      Memory Tag 255           37e9f8000000-37ea00000000 [128.0M] ---/rwx SM=NUL  

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x181b09420 objc_msgSend + 32
1   Electron Framework            	       0x10daba0b8 node::FreeArrayBufferAllocator(node::ArrayBufferAllocator*) + 278104
2   Electron Framework            	       0x10dab9b04 node::FreeArrayBufferAllocator(node::ArrayBufferAllocator*) + 276644
3   Electron Framework            	       0x10da45f90 v8::CodeEvent::GetScriptName() + 6336
4   AppKit                        	       0x185ac45e4 -[NSApplication _terminateFromSender:askIfShouldTerminate:saveWindows:] + 124

**Comment by JellyBrick** [comment]
Fixed in https://github.com/electron/electron/pull/41264
