### ISSUE TITLE
How to change download folder ?

### ISSUE THREAD

**Issue by ad0792** [th-ch/youtube-music#166]

**Comment by semvis123** [comment]
If you go to advanced options under plugins, then add the download folder line it should work. For example:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/28219076/108551133-cacb3f80-72ef-11eb-876a-0b5a3968e71a.png">

**Comment by ad0792** [comment]
First of all thank you replying. I added the path but its still downloading to previous folder. Please refer to image below and tell me if I did something wrong :)
![Uploading Screenshot_76.png…]()

**Comment by ad0792** [comment]
And I started receiving this error a few minutes later.
![Screenshot_77](https://user-images.githubusercontent.com/79332478/108591129-1c75d780-738d-11eb-937d-6469d07a1590.png)

**Comment by semvis123** [comment]
Interesting, does it work if you double the backslashes (`\` -> `\\`), this probably happens because the `\` is a reserved character in JSON and needs to be escaped.

**Comment by ad0792** [comment]
Thanks a lot !! It worked. This is what I added as you told and it works perfect now. Thanks again.
![Worked](https://user-images.githubusercontent.com/79332478/108594700-84ceb400-73a1-11eb-827c-a75637dcaca0.png)

**Comment by th-ch** [comment]
Hey, thanks everyone for the question/answers! It seems to be solved so I will close the issue - lesson learned, the project will probably need an FAQ at some point, especially for advanced options!
