### ISSUE TITLE
[Bug]: Discord RPC not showing up

### ISSUE THREAD

**Issue by MeledoJames** [th-ch/youtube-music#1664]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch linux

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.0.2

### Reproduction steps

1. Enable discord plugin

### Expected Behavior

discord rpc should show up on discord

### Actual Behavior

Nothing comes up on discord

### Enabled plugins

1. Adblocker
2. Compact sidebar
3. in-app menu
4. navigation
5. notifications

### Additional Information

The rpc seems to be working on v 2.0.2 appimage version. But I can't seem to get the rpc working on the later versions and the latest version.
I'm using youtube-music bin on the AUR also.

**Comment by ArjixWasTaken** [comment]
Is discord installed using pacman (or an AUR helper) or flatpak?
flatpak applications run isolated iirc

**Comment by MeledoJames** [comment]
discord is installed using pacman

**Comment by rocord01** [comment]
I am having this same issue, but on windows. Here is a screenshot from devtools on my Discord client. 
![image](https://github.com/th-ch/youtube-music/assets/57117549/50f16e52-e4ac-46b6-abe2-3f4643a527c5)

**Comment by JellyBrick** [comment]
@rocord01 Thank you for the detailed report!
