### ISSUE TITLE
[Feature Request]: Add Lyrics Plugin (tampermonkey)

### ISSUE THREAD

**Issue by jiongjiongJOJO** [th-ch/youtube-music#1666]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current lyrics plugin is very unfriendly to Chinese music, and there is almost no available music.

### Proposed Solution

This plugin will pull the corresponding lyrics based on the music area NetEase Cloud Music, but it only supports the web version and you have to install the Grease Monkey plugin, so hopefully the plugin will be built into this app.

### Alternatives Considered

[https://github.com/ShevonKuan/Lyrics4youtube-music](https://github.com/ShevonKuan/Lyrics4youtube-music)

**Comment by ArjixWasTaken** [comment]
Already a W.I.P. although it is kinda delayed since it is exam season for me.

**Comment by jiongjiongJOJO** [comment]
Sorry, this plugin is currently disabled as well.

**Comment by JellyBrick** [comment]
what?
