### ISSUE TITLE
[Feature Request] Background playback.

### ISSUE THREAD

**Issue by kirk781** [th-ch/youtube-music#167]
The app has an option to minimize to the tray. However, the app isn't properly in the background even then. When alt tabbing, it is visible in the app switcher. Would it be possible for the app to be properly act in the background and NOT be visible when alt tabbing?

Also, the tray has two options: enabled + app visible/hidden. However, I found no difference when choosing either of them.

**Comment by MiepHD** [comment]
The difference between enabled + app visible and enabled + app hidden is how the app behaves when it's started. 
If you choose enabled + app hidden the app starts only in the tray and you have to open the ui manually through the tray.
When choosing enabled + app visible the ui starts on app start with an icon in the tray. Then you can close the ui without the app stopping.

For me when I close the ui it is hidden in alt tabbing too. Do you still have this issue in the newest version v1.20.0?
