### ISSUE TITLE
[Feature Request]: Album colour theme plugin dosent respect dark mode

### ISSUE THREAD

**Issue by Rairof** [th-ch/youtube-music#1677]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 pro  v23H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

N/A

### Reproduction steps

1. Enable `Album colour theme`
2. play any music to check if it uses light colour schemes from said music album

### Expected Behavior

the plugin should respect users having dark mode and use darker color schemes fetched by the current music album instead of blasting users with light color schemes on UI
![image](https://github.com/th-ch/youtube-music/assets/107706560/91e8c1ef-497f-4164-b94a-16673f7c9a6e)

### Actual Behavior

Plugin uses both light and darker color tones based on the album which isn't good for dark mode users
![image](https://github.com/th-ch/youtube-music/assets/107706560/3ec8ab9f-7346-4868-b386-b5edf0b76e00)
![image](https://github.com/th-ch/youtube-music/assets/107706560/077dc08a-eb38-4674-987c-644ae7f2ebe1)

### Enabled plugins

![image](https://github.com/th-ch/youtube-music/assets/107706560/04bec5e6-dd57-4076-8d17-2dfd8e8099fa)
![image](https://github.com/th-ch/youtube-music/assets/107706560/f9a82067-37d6-47ed-a758-1f7b957c1a9f)

### Additional Information

Let me know if I need to provide any more info if needed down in comments

**Comment by JellyBrick** [comment]
It's not a bug.

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1677#issuecomment-1910334450
nope, that's not editted, it is a mobile ytm mod plugin from ReVanced Extended and it works as intended
