### ISSUE TITLE
[Bug]: Last.fm lost some Scrobbles

### ISSUE THREAD

**Issue by arianasenky** [th-ch/youtube-music#1686]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Reproduction steps

1.I open app listen to a full album
2.it always will lost some scrobbles in last.fm

### Expected Behavior

I hope it will not lost scrobbles anymore.

### Actual Behavior

1.When I listen to a full album, it always will lost some scrobbles in last.fm
![screenshot-1706290687077](https://github.com/th-ch/youtube-music/assets/157824870/c4cfae41-d476-410d-99a6-27e26f25bb6e)
![screenshot-1706290648695](https://github.com/th-ch/youtube-music/assets/157824870/a2c154d6-c01d-4cc7-b187-54a153d00335)

### Enabled plugins

1.Last.fm

**Comment by JellyBrick** [comment]
Maybe fixed at f424ee5170d79b4be6b9ff939369d020c484ddda
