### ISSUE TITLE
[Enhancement]: Introduce backwards navigation from Google Sign-in to Homepage if user chooses not to sign in.

### ISSUE THREAD

**Issue by luluna02** [th-ch/youtube-music#1687]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When I click on the "Sign In" button on the homepage, I am directed to the Google sign-in page. However, If I decide to cancel, I find that there isn't an intuitive way to navigate back to the homepage. Currently, the only way to return is by using the "Go Back" button of Electron ( as shown in the following screenshot)

<img width="1440" alt="Screenshot 2024-01-27 at 10 10 36 AM" src="https://github.com/th-ch/youtube-music/assets/133816965/dbba94ad-49ba-4848-9a64-45bfe40994a4">

### Proposed Solution

Adding a visible "Return to Homepage" button on the Google sign-in page or implementing a mechanism that automatically redirects users back to the homepage if they cancel.

### Alternatives Considered

Electron's navigation bar

### Additional Information

OS: macOS 13.5.2

**Comment by luluna02** [comment]
![Uploading Screenshot 2024-01-27 at 2.43.01 PM.png…]()

**Comment by JellyBrick** [comment]
Maybe fixed at ddb99681958c1f7a285bf18918cd40ef8a02e36a
