### ISSUE TITLE
[Feature Request] Last.fm Scrobbler Integration. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [th-ch/youtube-music#169]
Hey, i just wanna say that i love these extras plugins and tools for Youtube Music and i was wondering if you could also add Last.fm Scrobbler Integration in the settings, I would defiantly love to use this for streaming and it would really help me out if this function was added. Again, thank you so much for making this and i hope i can use this to stream music in the future.

**Comment by tpurde** [comment]
I think this would be an amazing addition. Last.fm support is the only thing keeping me from using this to listen to all my music.

**Comment by Goldenfreddy0703** [comment]
Same, i just hope this will be added soon cause this could help me out alot.

**Comment by semvis123** [comment]
I don't know much about last.fm, what exactly do you mean?
something like this? https://www.last.fm/api/show/track.updateNowPlaying
Could you please link the api items that you have in mind?

**Comment by Goldenfreddy0703** [comment]
Something more like this in a way except this could be used as a plugin where it takes the information and sends it to last.fm
This link should help clear things up to understand how to scrobble the music from youtube music.
[](https://support.last.fm/t/youtube-and-youtube-music-scrobbling/173)

**Comment by semvis123** [comment]
#196 I have added last.fm integration, love and unlove are currently not added, but could be added in future releases.
Would love to hear your feedback on this

**Comment by Goldenfreddy0703** [comment]
I would love to provide feedback on this but i don't really know how i could test your modified source code. When i first found th-ch youtube-music open source, i downloaded it thru setup.exe or app image to try it out sense im using windows. How would i be able to test your source code?

**Comment by semvis123** [comment]
You can follow the `dev` section in the readme, this will require you to install git and node.js and yarn before you start though.
Hope that's not a problem, if you can't figure it out I can provide the precompiled version if you want.

**Comment by Goldenfreddy0703** [comment]
Ok thank you, I will try it out today and give you feedback over it when I get up sense it's like 9:40 am for me.

**Comment by Goldenfreddy0703** [comment]
ok hey, so i did install git and install node.js and yarn and tried the dev repo and i also tried yours too by using git clone https://github.com/semvis123/youtube-music and then using yarn and yarn start and everything is loaded but for me, i didn't notice anything different, i tried looking in the console for last.fm but i could not find it nor find the plugin for it. In the console, i did see alot of errors and i don't know if they relate to youtube api. For now, what should i do?

**Comment by semvis123** [comment]
You need to checkout the correct branch.
Yeah when you enable the plug-in for the first time it launches the last fm login page, you will need to login, but after that it  should work with the next song (shouldn't be a need for restart m). This is only needed the first time and shouldn't happen after you logged in successfully.

**Comment by Goldenfreddy0703** [comment]
oh ok, thank you. 
When i enabled it for the first time, i was not prompted with a login page for some odd reason.

**Comment by semvis123** [comment]
Ah that makes sense, because the plugins are only applied after a (program) restart, this happens with every plugin.

**Comment by Goldenfreddy0703** [comment]
I forgot about that when you enable a plugin on youtube music, the application needs a restart. Thank you for reminding me about that.

**Comment by semvis123** [comment]
No problem!
Is the plugin fully functional, does it add scrobbles (happens when the song is 50% elapsed or earlier if the song is >8 minutes) and set currently playing in your account?

**Comment by Goldenfreddy0703** [comment]
well not yet but i think it will be once i login and see on the last.fm website to see if its on there

**Comment by Goldenfreddy0703** [comment]
let me go to your latest branch incase you updated it today

**Comment by semvis123** [comment]
Login is required, once you login you should be greeted with this screen.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/28219076/111910059-13e1f100-8a60-11eb-9659-da9117f94ff2.png">
After you grant permission to YouTube music it should start to work.

**Comment by Goldenfreddy0703** [comment]
ok hey, im really sorry i was having trouble but to get to this login sceen, what would i have to do?

**Comment by semvis123** [comment]
It should open in your default browser. Do you see the lastfm folder inside the plugins, from the folder in which you do `yarn start`?

**Comment by Goldenfreddy0703** [comment]
yes i do

**Comment by semvis123** [comment]
does your command prompt print any errors?

**Comment by Goldenfreddy0703** [comment]
from when im starting the application, no errors but when looking at the console there is a bit errors 
![errors](https://user-images.githubusercontent.com/62456796/111911290-547b4380-8a3b-11eb-8f88-5b8cdf21fe7a.PNG)

**Comment by Goldenfreddy0703** [comment]
Waiitttt, im very sorry

C:\Users\jenki\Documents\projects\youtube-music-lastfm>yarn start
yarn run v1.22.5
$ electron .

Loaded plugin - navigation
Loaded plugin - shortcuts
Loaded plugin - adblocker
Loaded plugin - downloader
Loaded plugin - auto-confirm-when-paused
Loaded plugin - touchbar
Loaded plugin - last-fm
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\jenki\Documents\projects\youtube-music-lastfm\node_modules\node-fetch\lib\index.js:1305:9)
    at C:\Users\jenki\Documents\projects\youtube-music-lastfm\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\jenki\Documents\projects\youtube-music-lastfm\node_modules\node-fetch\lib\index.js:1407:9)
    at getAndSetSessionKey (C:\Users\jenki\Documents\projects\youtube-music-lastfm\plugins\last-fm\back.js:74:14)
    at lastfm (C:\Users\jenki\Documents\projects\youtube-music-lastfm\plugins\last-fm\back.js:144:18)
    at C:\Users\jenki\Documents\projects\youtube-music-lastfm\index.js:69:4
    at C:\Users\jenki\Documents\projects\youtube-music-lastfm\plugins\utils.js:41:3
    at FSReqCallback.oncomplete (fs.js:160:23)
did finish load
Clearing app cache.

**Comment by Goldenfreddy0703** [comment]
These are the errors im getting now

**Comment by semvis123** [comment]
ah, how does your config file look like, (plugins -> advanced options).

**Comment by Goldenfreddy0703** [comment]
I tried going there but it said i did not have an app to support it, I have Notepad++ tho

**Comment by semvis123** [comment]
I don't know about windows, but I suppose there should be a folder under `program files` named YouTube music which should contain a `config.json`

**Comment by Goldenfreddy0703** [comment]
i found the config n my appdata folder
{
	"window-size": {
		"width": 826,
		"height": 1040
	},
	"url": "https://music.youtube.com/watch?v=Dq7X-uloLjc&list=RDAMVMz624mpxCAOk",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": true,
		"resumeOnStart": true
	},
	"plugins": {
		"navigation": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"downloader": {
			"enabled": true,
			"ffmpegArgs": []
		},
		"auto-confirm-when-paused": {
			"enabled": true
		},
		"discord": {
			"enabled": false
		},
		"touchbar": {
			"enabled": true
		},
		"last-fm": {
			"enabled": true
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.11.0"
		}
	},
	"window-position": {
		"x": -7,
		"y": 0
	},
	"window-maximized": false
}

**Comment by semvis123** [comment]
It doesn't contain the last-fm preferences, you could delete that file, and it should automatically create a new one with the added preferences on the next launch.

**Comment by semvis123** [comment]
but I should probably change the plugin so that it is backwards compatible :)

**Comment by Goldenfreddy0703** [comment]
{
	"window-size": {
		"width": 1100,
		"height": 550
	},
	"url": "https://music.youtube.com/",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": false,
		"resumeOnStart": true
	},
	"plugins": {
		"navigation": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"downloader": {
			"enabled": false,
			"ffmpegArgs": []
		},
		"last-fm": {
			"enabled": true,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
			"api_key": "04d76faaac8726e60988e14c105d421a",
			"secret": "a5d2a36fdf64819290f6982481eaffa2"
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.11.0"
		}
	},
	"window-position": {
		"x": 260,
		"y": 245
	}
}

Here is the config when last.fm is enabled

**Comment by semvis123** [comment]
Yeah that is correct, now it should launch your browser and prompt to login.

**Comment by Goldenfreddy0703** [comment]
thats odd, does it by anychance work for you when you enable last.fm?

**Comment by semvis123** [comment]
Are you still getting the same error in cmd? When launching it again?

**Comment by Goldenfreddy0703** [comment]
Well when last.fm is enabled, im not prompted with a browser and nothing happens, when i restart the app with last.fm enabled, i get that error.

**Comment by semvis123** [comment]
I have fixed the issue, it should work now. Please download the newest version before you test :)
It is also backwards compatible now.

**Comment by Goldenfreddy0703** [comment]
Hey, im so so sorry i passed out, i was so tired that i passed out by mistake but i tested your application today and you did a good job on this, I really love this and its capturing the songs and now people can see them in my streams. This is all thanks to you and you are the best. Thank you so much

One last thing i would like you to do is to decompile this version into a setup exe and you made my favorite application work with last.fm support.

**Comment by semvis123** [comment]
You're welcome,
you can compile the app yourself with `yarn build` and grab the setup exe out of the `dist` folder or wait on the next release.

**Comment by Goldenfreddy0703** [comment]
oh nice, thank you. There is one thing i do notice tho. This does capture the song but it does not capture the thumbnail artwork. Would there be anychance to add the thumbnail artwork in the future?
![Thumbnail](https://user-images.githubusercontent.com/62456796/111920947-44c62400-8a68-11eb-8b72-aace34be4f64.PNG)

**Comment by semvis123** [comment]
The artwork is stored at the last.fm side, and I cannot provide that in a request, so sadly only songs that are recognized enough (Youtube music names songs a little different most times) will have artwork.

**Comment by semvis123** [comment]
I think the website can showing the correct information, it just does't receive enough information from last.fm because of songs named a bit differently.

**Comment by semvis123** [comment]
Actually, I can change the naming of the artist a bit, currently it has `- Topic` behind the name, if I remove that it should match more song thumbnails.

**Comment by semvis123** [comment]
I have updated the code, now it should find more thumbnails👍

**Comment by Goldenfreddy0703** [comment]
ok thank you very much, if not then it could probably be due to the website im using for overlays cause i saw a reddit post about it.

**Comment by semvis123** [comment]
before and after is clearly visible, now all songs that I tested have got thumbnails. ( all without thumbnails were before this chance)
<img width="91" alt="image" src="https://user-images.githubusercontent.com/28219076/111921500-3a6e4f00-8a95-11eb-90de-7dbf05512f57.png">

**Comment by Goldenfreddy0703** [comment]
ok then it must be the website im using for the overlays then so it was probably a glitch on there end.

**Comment by Goldenfreddy0703** [comment]
So far everything is working really well and this is all thanks to you. Your the best

**Comment by semvis123** [comment]
> ok then it must be the website im using for the overlays then so it was probably a glitch on there end. 

Have you tried the new version, try to look on the last.fm site (view profile), it should display correctly on there.

**Comment by Goldenfreddy0703** [comment]
Actually i have tried and that fix helped get more thumbnails, the website i was using for the overlays is pixelchat.tv which is connected with last.fm and pixelchat.tv was causing a glitch on there end but on last.fm, everything is working and all the thumbnails are there for me now.

**Comment by Goldenfreddy0703** [comment]
Honestly, thank so much for making this plugin possibly, i can use this for my streams now and now i can start streaming again. this is the best and im so happy to have this application designed for plugins and last.fm, You are the best and im really happy about this. Thank you so much

**Comment by matthpmore** [comment]
Hello, could you help me? I'm a total layman when it comes to programming. I'm getting the following error:

yarn run v1.22.10
$ electron .

yarn run v1.22.10
$ electron .

Loaded plugin - navigation
Loaded plugin - shortcuts
Loaded plugin - adblocker
Loaded plugin - last-fm
TypeError: Cannot set property 'enabled' of undefined
    at lastfm (C:\Users\mathe\Desktop\youtube-music\plugins\last-fm\back.js:148:18)
    at C:\Users\mathe\Desktop\youtube-music\index.js:69:4
    at C:\Users\mathe\Desktop\youtube-music\plugins\utils.js:41:3
    at FSReqCallback.oncomplete (fs.js:160:23)
did finish load
Done in 13.34s.

**Comment by Goldenfreddy0703** [comment]
Honestly i would love to but i completely forgot how to use Yarn. I think you would have to use git and then follow everything the post tells you. If you want i compiled this version, i can send you a download link to it.

**Comment by matthpmore** [comment]
Yeah, I followed everything and came up with a few solutions for other errors (missing modules), but I have no idea how to fix this one. Could you please send me a download link?

**Comment by Araxeus** [comment]
check your `youtube-musicconfig/defaults.js`
it should have in the plugin section 

```javascript
"last-fm": {
			enabled: false,
			api_root: "http://ws.audioscrobbler.com/2.0/",
			api_key: "04d76faaac8726e60988e14c105d421a", // api key registered by @semvis123
			secret: "a5d2a36fdf64819290f6982481eaffa2",
			suffixesToRemove: [' - Topic', 'VEVO'] // removes suffixes of the artist name, for better recognition
		},
```

the error you're facing seems to indicate this is missing

**Comment by matthpmore** [comment]
Yeah, it's missing. I tried deleting the file hoping it would regenerate and also adding this section, but it doesn't work. It pops up a different error:

                last-fm:true,
                    ^

SyntaxError: Unexpected token '-'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\mathe\Desktop\youtube-music\config\index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

and also:

yarn run v1.22.10
$ electron .

App threw an error during load
Error: Cannot find module './defaults'
Require stack:
- C:\Users\mathe\Desktop\youtube-music\config\index.js
- C:\Users\mathe\Desktop\youtube-music\index.js
- C:\Users\mathe\Desktop\youtube-music\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\mathe\Desktop\youtube-music\config\index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)

**Comment by Araxeus** [comment]
I dont know where did you initially clone from.
but you should clone the branch from the [Pull Request](https://github.com/semvis123/youtube-music/tree/lastfm)
and then run `yarn` or `yarn install` inside the project folder to install all dependencies

and then hopefully you should have everything needed

**Comment by matthpmore** [comment]
That's where I got it from, I think I did something wrong before... I downloaded again and now it's not giving me any error, but the last.fm login window won't show up

**Comment by Araxeus** [comment]
Try maybe deleting the last-fm options from `config.json`
which is accessed through "Advanced Options" from menu

**Comment by matthpmore** [comment]
It just won't load the plugin - then I have to turn it on again, restart the program and the login windows still won't show up. Could it be an issue with the code itself? I wish there was a way to force login or enter my credentials without the need for the window

**Comment by Araxeus** [comment]
I already said: 
> unless somehow semvis broke his branch while updating from upstream :(

But I don't even know if thats the case.
maybe @semvis123 will have more to say

**Comment by Goldenfreddy0703** [comment]
Hey guys, im really sorry. Ive been busy all day working on some other stuff but here is the download link to the Youtube files. The first file is the Application and the second one is the setup file. 

https://www.mediafire.com/file/as8t0253b4iszqk/YouTube_Music_1.11.0.zip/file

**Comment by matthpmore** [comment]
Hey, sorry for the late reply. Unfortunately it did not work, even after enabling the plugin and restarting the program. I also tried deleting everything YouTube related from Local and Roaming AppData then reinstalling, but it didn't work either. Now I'm convinced it's an issue on my end, but I don't know what to do

**Comment by semvis123** [comment]
I just checked on a fresh install, everything is working just fine for me, both the master branch and last-fm branch.
When running `yarn start` (and possibly `yarn` first for installing the dependencies),
Does it say `Loaded plugin - last-fm`?
Do you get any errors?
What platform are you on? (macOS, Windows, Linux)

**Comment by Goldenfreddy0703** [comment]
> 
> 
> Hey, sorry for the late reply. Unfortunately it did not work, even after enabling the plugin and restarting the program. I also tried deleting everything YouTube related from Local and Roaming AppData then reinstalling, but it didn't work either. Now I'm convinced it's an issue on my end, but I don't know what to do

Hey everything worked for me, I just enabled last.fm, restarted the program and launched it again and i just had to wait a few secounds and it automatically opens me a web browser to the last.fm pairing or log in page

**Comment by semvis123** [comment]
@matthpmore Won't stop helping till it works for you :)
Do you have a default browser selected?


You can create the url yourself.

1) Firstly open the YouTube music app, let it fully load (this should generate a fresh token for you).
Within the advanced config there should be fields such as `api_key` and `token` (under last-fm).

2) Close YouTube music / stop music playback, to avoid regenerating another new token (but keep the advanced options open for the information needed below).

3) Create your own url, by filling in the `api_key` and `token` on the correct place (see below) (without spaces)
    >`https://www.last.fm/api/auth/?api_key=`api_key here`&token=`token here

4) Open the url to complete the authentication.

5) Relaunch Youtube Music

6) Enjoy :)

Hope this works for you!

**Comment by matthpmore** [comment]
Sorry for being late. It worked perfectly! That's all I needed. Thank you so much for the help
