### ISSUE TITLE
[Bug]: audio quality is stuck on normal

### ISSUE THREAD

**Issue by phi-alek** [th-ch/youtube-music#1701]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What CPU architecture are you using?

x64

### Reproduction steps

just like on a webbroweser, you can not change the quality settings. it will always playback with code 140 which means 128kbit with aac codec. im a premium user, so i should be able to use high settings with 256kbits. but in the app even if you change it to low which should be 64kbits, its always stuck to 128kbits.

### Expected Behavior

the audio bitrate should change.

### Actual Behavior

its always stuck on 128kbits

### Enabled plugins

nothing to enable here. im logged in with a premium account.

**Comment by JellyBrick** [comment]
We can't fix it. It's a server-side bug.

**Comment by JellyBrick** [comment]
> It's a server-side bug.

I checked this issue, and it isn't a bug.
141 codec (AAC 256kbps) only can be used when playing "Song".

**Comment by phi-alek** [comment]
I have checked again, as i could not believe what you were writing. Nope,
my own songs officially published in every streaming services are certainly
official songs and not videos. they are played with 140. every single song
by every artist is played with 140. music from videos is played back with
251 which already is a big step up. on android or mac os, everything works
fine with 141, your app has a problem in windows.

Am Sa., 3. Feb. 2024 um 20:35 Uhr schrieb JellyBrick <
***@***.***>:

**Comment by ArjixWasTaken** [comment]
> just like on a webbroweser, you can not change the quality settings. 

this app is in fact, a web browser, we did not clone the UI, we just load the official website and inject some of our code in the form of plugins

**Comment by phi-alek** [comment]
Well there we have the issue. YouTube music for some reason can't Playback
141 on Windows Webbrowsers. On Mac it only works in safari. Chrome on Mac
and even Android doesn't work too. The only browser I could bring to
Playback at least 251 on Windows is chromium. This is very very weird.

Angelos Bouklis ***@***.***> schrieb am Mi., 7. Feb. 2024,
22:59:

**Comment by JellyBrick** [comment]
> Well there we have the issue. YouTube music for some reason can't Playback 141 on Windows Webbrowsers. 

Once again, this is a **server-side issue** on YouTube. It's **not** our fault.
Also, 251 (opus VBR 120kbps) is just 140 (aac 128kbps) encoded as `opus`.
And 141 (aac 256kbps) is only available to YT Premium who are playing music source (soundtrack). 

e.g. https://music.youtube.com/watch?v=wW2tKV920Ac&si=dKznbZd6HsauSbZW

![image](https://github.com/th-ch/youtube-music/assets/16558115/c038c49c-1aad-4cdb-9bc1-9e9d89ecaa8f)
![image](https://github.com/th-ch/youtube-music/assets/16558115/4f604927-e0f3-4b5a-8843-a08550e70b73)

**Comment by JellyBrick** [comment]
> your app has a problem in windows.

And, IT CAN REPRODUCIBLE IN OFFICAL YT MUSIC (CHROME). yes, it's not our problem.

![image](https://github.com/th-ch/youtube-music/assets/16558115/cdb090a5-4786-4720-ad1b-bab5a127b172)

**Comment by phi-alek** [comment]
I don't understand what you are saying regarding soundscores, every
officially released audio track has 256 kbit AAC with 141. Only music
videos are in 251 (160 kbits opus). Yes, they 141 is only for premium
users, but I am premium user. Android and iOS ytm apps give me 141 for
every official song and safari browser on Mac too. Only on Windows it's not
possible. I don't think it's a server issue. I think there is a bug how
chrome connects to ytm servers. And your app uses the same method as chrome
browser, that's why it doesn't work.

I use BlueStacks with ytm app now on Windows and I get full quality.

JellyBrick ***@***.***> schrieb am Do., 8. Feb. 2024, 16:01:

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/69f7ce0e-9426-43fe-bf99-77c386b08425)

https://github.com/th-ch/youtube-music/issues/1701#issuecomment-1934303183

**Comment by phi-alek** [comment]
This is from the app?

JellyBrick ***@***.***> schrieb am Do., 8. Feb. 2024, 16:25:

**Comment by phi-alek** [comment]
Anyhow, your omment about 251 is just 140 but re-endoded is false.

251 got back encoded by the file provided by the music distributor and is
nearly always loseless. Further 251 sounds much better than 140, the
difference is very noticeable.

And that 141 only applies to soundscores as you have named it, well
listening to official songs is the whole point of ytm.

If you say, you can't fix the issue because chrome on Windows has issues,
that's something that's understandable. But I don't understand the other
things you are saying.

Alex Abedi ***@***.***> schrieb am Do., 8. Feb. 2024, 17:34:

**Comment by kito30** [comment]
yup can confirm its Google fault, try on EVERY WEB BROWSER does not work. Let Google do it things and let not harrass the developer.

**Comment by Soymilkrice** [comment]
https://www.reddit.com/r/YoutubeMusic/comments/194bfqh/audio_quality_stuck_on_normal/?rdt=44626
