### ISSUE TITLE
[Bug]: Repeating Menu Bar

### ISSUE THREAD

**Issue by IncognitoFawkes** [th-ch/youtube-music#1705]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

I couldn't reproduce it. It happens at random.

### Expected Behavior

The menu bar on top has the five options, Plugins, Options, View, Navigation, About

### Actual Behavior

The menu bar with the five options repeats infinitely, like Plugins, Options, View, Navigation, About, Plugins, Options, View, Navigation, About, Plugins, Options, View, Navigation, About ....

### Enabled plugins

Adblocker
Album Color Theme
Bypass Age Restrictions
Captions Selector
Downloader
Discord Rich Presence
In-App Menu
Lyrics Genius
Navigation
Picture-in-Picture
Skip Disliked Songs
Sponsor Block
Taskbar Media Control
Video Toggle

### Additional Information

It happens at random and I wasn't able to reproduce it. Will update the issue if I manage to reproduce it.

UPDATE:::
It was an issue with the in-app menu. I see a comment below saying that they're working on revamping it. This issue also causes some of the other buttons above, like Music Together, unresponsive when YT music is in fullscreen mode.

**Comment by inson1** [comment]
I have Windows 10, it never happened to me

**Comment by JellyBrick** [comment]
We are in a major refactoring of the in-app-menu and settings panel, which we expect to resolve this issue :)

**Comment by dest4590** [comment]
> I have Windows 10, it never happened to me
Windows 11 (23h2) too

**Comment by IncognitoFawkes** [comment]
Posted an update above. It is an issue with the in-app menu. It's also making the other buttons, like Music Together, inaccessible, when YT music is in full screen mode.

**Comment by IncognitoFawkes** [comment]
Issue not fixed for me in the new 3.3.1.0 for the in-app menu. I haven't observed the repeating menu bar yet, so maybe that's fixed, but the buttons on the top-right corner are still inaccessible. I can't click on Music Together or my profile when the app is open. Do you want me to add this comment in another issue mentioning the inaccessible top-right buttons, or is this fine?

**Comment by JellyBrick** [comment]
@IncognitoFawkes As a general rule, only one bug should be tracked in an issue. This issue has already been resolved, so please open a new issue.
