### ISSUE TITLE
[Feature Request]: Listenbrainz scrobbling plugin

### ISSUE THREAD

**Issue by devxan** [th-ch/youtube-music#1708]
### Preflight Checklist
I use the latest version of YouTube Music (Application) & I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description
I want to record my music to [ListenBrainz](https://listenbrainz.org/).

### Proposed Solution
Make a plugin that submit listens to ListenBrainz 

### Additional Information
View the documentation: https://listenbrainz.readthedocs.io/en/latest/

**Comment by JellyBrick** [comment]
Already implemented. see #1640
