### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jeluxe** [th-ch/youtube-music#1715]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.1.1.0

### Reproduction steps

1.enabled compact sidebar.
2.enabled album color theme.
3.pointing the volume icon.
4.volume toolbar open.

### Expected Behavior

volume toolbar will recieve the color of the theme.

### Actual Behavior

volume toolbar not recieved the color of the theme.

### Enabled plugins

1.adblocker.
2.album-color-theme.
3.compact-sidebar.
4.crossfade.
5.discord.
6.exponential-volume.
7.in-app-menu.
8.lyrics-genius.
9.navigation.
10.precise-volume.
11.shortcuts.
12.taskbar-mediacontrol.
13.touchbar.
14.video-toggle.
15.music-together.
16.skip-disliked-songs.
17.album-actions.

### Additional Information

okay so i just notice that only when the window width is small enough to collapse all volume toolbar then that issue appears.

**Comment by Jeluxe** [comment]
okay so i just notice that only when the window width is small enough to collapse all volume toolbar then that issue appears.

**Comment by JellyBrick** [comment]
Not a bug.

**Comment by JellyBrick** [comment]
fixed at #1685

**Comment by Jeluxe** [comment]
> fixed at #1685
just checking, so is that version with the fix out or not?
also that is the problem
![Screenshot 2024-02-07 152600](https://github.com/th-ch/youtube-music/assets/59278268/5d5a5259-e487-45cb-bcaa-a189291c3bb7)

**Comment by JellyBrick** [comment]
> > fixed at #1685
>
> just checking, so is that version with the fix out or not?
> also that is the problem
> ![Screenshot 2024-02-07 152600](https://private-user-images.githubusercontent.com/59278268/303051097-5d5a5259-e487-45cb-bcaa-a189291c3bb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjk1NTcsIm5iZiI6MTcwNzMyOTI1NywicGF0aCI6Ii81OTI3ODI2OC8zMDMwNTEwOTctNWQ1YTUyNTktZTQ4Ny00NWNiLWJjYWEtYTE4OTI5MWMzYmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE4MDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZjg5YmU0OTIyMWFmYjBlZGRlZjBhYjlmMTUyODI0NDRlZTMzYTVlODU3OGRlMTIwOWQyYTk3NzI3Mzg4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Vf2-XTceSAAu1Su93slb9zbj5yC3fmnkX793Xbtb2w)

Not released yet
