### ISSUE TITLE
[Bug]: app not keeping window sizes after restarting/opening app 

### ISSUE THREAD

**Issue by Jeluxe** [th-ch/youtube-music#1716]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. opening the app.

### Expected Behavior

keep the window sizes

### Actual Behavior

for some reason its returning to specific window sizes.

### Enabled plugins

1.adblocker.
2.album-color-theme.
3.compact-sidebar.
4.discord.
5.exponential-volume.
6.in-app-menu.
7.lyrics-genius.
8.navigation.
9.precise-volume.
10.shortcuts.
11.video-toggle.
12.music-together.
13.skip-disliked-songs.
14.album-actions.

### Additional Information

https://github.com/th-ch/youtube-music/assets/59278268/77d2d142-2944-4d46-aaba-1b93898808eb

**Comment by JellyBrick** [comment]
What is the zoom scale of the screen?

**Comment by Jeluxe** [comment]
> What is the zoom scale of the screen?
125%(Recommended)

**Comment by Jeluxe** [comment]
i just checked it and in 100% it does works but it is too small for me

**Comment by JellyBrick** [comment]
There seems to be an issue with the zoom scale on the screen not being calculated.

**Comment by trueTrueman** [comment]
I have the same issue on 3.3.6.0. I have 125% display scale as well (1440p screen).

**Comment by AkshayRane05** [comment]
> I have the same issue on 3.3.6.0. I have 125% display scale as well (1440p screen).
> 
> Update: I found a semi-fix. Open the app, then switch display scale to 100%, then change the app's window size to desired, close the app, change display scale back to 125%, reopen the app and the window size should be as you made it. But don't touch the window size in 125% scale again because if you do that, after you restart the app next time, the window size will reset to small and you'll have to do the trick all over again.

Tried it. Does not work for me. Any other fix?
