### ISSUE TITLE
[Bug]: MPRIS may give incorrect `Position`

### ISSUE THREAD

**Issue by poly000** [th-ch/youtube-music#1726]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux x86_64

### What CPU architecture are you using?

x64

### Reproduction steps

1. play https://music.youtube.com/watch?v=0uhNOfBN0KA&si=8Ib5KEfNyrBSCFYq
2. run `playctl position` numerous time

### Expected Behavior

```bash
~/Repos/lyric-offset main ?1                                                        00:00:30
> playerctl position
45.000004
~/Repos/lyric-offset main ?1                                                        00:00:31
> playerctl position
46.xx
```

### Actual Behavior

```bash
~/Repos/lyric-offset main ?1                                                        00:00:30
> playerctl position
45.000004
~/Repos/lyric-offset main ?1                                                        00:00:31
> playerctl position
45.000008
```

### Enabled plugins

[YTMusic] Plugin in-app-menu::backend executed at 10.83ms
[YTMusic] Plugin shortcuts::backend executed at 12.13ms
[YTMusic] Plugin precise-volume::backend executed at 11.99ms
[YTMusic] Plugin picture-in-picture::backend executed at 11.90ms
[YTMusic] Plugin lyrics-genius::backend executed at 11.82ms
[YTMusic] Plugin adblocker::backend executed at 11.54ms
[YTMusic] Plugin "shortcuts::menu" loaded
[YTMusic] Plugin "precise-volume::menu" loaded
[YTMusic] Plugin "picture-in-picture::menu" loaded
[YTMusic] Plugin "lyrics-genius::menu" loaded
[YTMusic] Plugin "in-app-menu::menu" loaded
[YTMusic] Plugin "adblocker::menu" loaded
[YTMusic] Plugin "shortcuts::menu" loaded
[YTMusic] Plugin "precise-volume::menu" loaded
[YTMusic] Plugin "picture-in-picture::menu" loaded
[YTMusic] Plugin "lyrics-genius::menu" loaded
[YTMusic] Plugin "in-app-menu::menu" loaded
[YTMusic] Plugin "adblocker::menu" loaded

### Additional Information

Found this when play with my external lyric OSD app, and lyric jitters backwards repeatedly, so I checked `playerctl position`

**Comment by JarneDel** [comment]
I was able to reproduce this issue
```fish
#!/env/bin/fish

# loop 1000 times
for i in (seq 1 1000)
    echo (playerctl position)
    sleep 0.001
end
```

```txt
1009.028051
1009.028044
1009.028043
1009.028045
1009.028051
1009.028042
1009.028044
1009.028045
```

While looking for a different but i came across this issue. For me the position just keeps adding up untill i skip a song, so sometimes position would be 40 mins big etc. Might create seperate issue for that
