### ISSUE TITLE
[Bug]: scrollbar of music type not shown

### ISSUE THREAD

**Issue by ACaccel** [th-ch/youtube-music#1737]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

none

### Expected Behavior

![image](https://github.com/th-ch/youtube-music/assets/92323576/89aa8c31-9cff-4c5c-acaf-02210d4235ef)
the scrollbar to choose music type should be here

this is on the official YT music website

### Actual Behavior

![image](https://github.com/th-ch/youtube-music/assets/92323576/7812f2f3-47dc-459a-839e-226ce2b8da71)
the scrollbar disappears

![image](https://github.com/th-ch/youtube-music/assets/92323576/0a7f5597-ed33-46e6-9614-c1967fa30008)
but it will appear for a few seconds if I select the word accross different button boxes

this is on the windows portable yt application

Is it possible to make the scrollbar keep showing?

### Enabled plugins

none

**Comment by JellyBrick** [comment]
This issue is caused by `overlay scrollbar` (this is an intended feature), and you can redisplay it if you hover over the button
We'll consider adding a `Disable overlay scrollbar` setting.

![YouTube_Music_2q6nlBZI58](https://github.com/th-ch/youtube-music/assets/16558115/2c382177-2cfb-44eb-8691-1e22263a6a52)

**Comment by ACaccel** [comment]
But it seems to not display on mine when hovering over it
![YouTubeMusic2024-02-1601-59-25-ezgif com-crop](https://github.com/th-ch/youtube-music/assets/92323576/362fc9d0-23f4-4a49-9dad-0add9469ac4d)

**Comment by ACaccel** [comment]
The issue seems to be caused by this CSS rule, but I don't figure out why it affects
`html {
    scrollbar-color: var(--yt-spec-text-secondary) transparent;
}`

![ezgif-7-0e3868ef57](https://github.com/th-ch/youtube-music/assets/92323576/d2e63227-085a-48e9-bcda-2af7b669b540)

**Comment by JellyBrick** [comment]
In 9f5651a8ba53d39b6e9bedd02af95cecd63d8a6f, the issue appears to be resolved.

**Comment by JellyBrick** [comment]
can reproducible in 3aa9398481d3cc2022f2ae3102b523fe703023ce

I think it's a bug in Chromium 121

**Comment by JellyBrick** [comment]
Thanks for the detailed report!
