### ISSUE TITLE
Downloader not working

### ISSUE THREAD

**Issue by IsLocal** [th-ch/youtube-music#174]
The download button is not showing up in its spot
![image](https://user-images.githubusercontent.com/70923205/109746701-d0ecd600-7ba3-11eb-9d9a-c7bdd8779c61.png)

**Comment by th-ch** [comment]
Hey @IsLocal, thanks for the feedback! Issue is confirmed, it's an update of YouTube Music that changed the HTML - https://github.com/th-ch/youtube-music/commit/796a7aaaf1ecaf80b2ef113137f2222499803e29 should fix the issue and will ship in the next version (will release it very soon)!

**Comment by th-ch** [comment]
Closing this issue as it should be solved in the latest version, feel free to re-open in case of issue!
