### ISSUE TITLE
[Bug]: Non functional menu icon appearing on macos

### ISSUE THREAD

**Issue by luluna02** [th-ch/youtube-music#1746]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

Sonoma

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Run project
2. Open app, menu icon will appear on top left 

### Expected Behavior

No menu icon on MacOS since there is already a menu bar.

### Actual Behavior

Menu icon appearing without any usage or on click effect. 

![Image-1](https://github.com/th-ch/youtube-music/assets/133816965/c1ca4ead-eba5-4929-9ba4-080fad7683b7)

### Enabled plugins

None

**Comment by JellyBrick** [comment]
This is not a bug, it's an intended feature. We added it to make in-app menus available on macOS.
If you don't want to use the "in-app menu", just deactivate the plugin.

**Comment by luluna02** [comment]
How could be in-app-menu available on macOS? It wouldn't appear like on Windows

**Comment by JellyBrick** [comment]
We know. But we think it's good to let end users choose whether or not to use plugins, which is why we've made this plugin available for macOS.
If somebody don't like this plugin, they can simply disable it.
