### ISSUE TITLE
[Feature Request]: No duplication of menu bar

### ISSUE THREAD

**Issue by luluna02** [th-ch/youtube-music#1750]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is a duplication of the menu bar, the in-app-menu plugin and the bar natively given by macOS.

<img width="1047" alt="Screenshot 2024-02-17 at 3 58 12 PM" src="https://github.com/th-ch/youtube-music/assets/133816965/1098b57a-3093-45fa-8e39-1fffe9ba4eac">

### Proposed Solution

No in-app-menu plugin for macOS

### Alternatives Considered

.

**Comment by JellyBrick** [comment]
see https://github.com/th-ch/youtube-music/issues/1746#issuecomment-1950459905

> We know. But we think it's good to let end users choose whether or not to use a plugin, which is why we've made it available for macOS.
> If someone doesn't like this plugin, they can simply disable it.
