### ISSUE TITLE
[Bug]: Music Together load indefinitely neither succedding nor failing until the host closes the session

### ISSUE THREAD

**Issue by Nimzuie** [th-ch/youtube-music#1752]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable Music Together
2. Attempt to host or connect (Both have the same result)
3. Me or friend attempts to input HostID 

### Expected Behavior

Expected to join the Together session 

### Actual Behavior

Seems to load indefinitely neither succedding nor failing until the host closes the session in which case it will then fail to connect 
![image_2024-02-17_211758979](https://github.com/th-ch/youtube-music/assets/95544153/7c77abb3-2d59-497b-ac1c-cdba87ec30ed)
![image_2024-02-17_212021029](https://github.com/th-ch/youtube-music/assets/95544153/0de3daf2-724f-49e6-88eb-c8f561ab363b)

### Enabled plugins

1. Adblocker
2. Music Together

### Additional Information

Have tried running it as admin, disabling/adding a rule in the firewall to no success, can supply additional information if requested

**Comment by JellyBrick** [comment]
Music Together uses a peer-to-peer connection (WebRTC), it may not work properly in environments where WebRTC is blocked.

Could you check if this example code works?

https://sheeptester.github.io/javascripts/peerjs.html

**Comment by Nimzuie** [comment]
The example page seems to work completely fine with both of us connecting successfully and seeing each others messages

**Comment by Yogarpg** [comment]
This is happening to me too
Before moving my Windows to another drive it worked fine

**Comment by JellyBrick** [comment]
YT changed something again. 
fixed at 6f70d17
