### ISSUE TITLE
[Bug]: Login / Sign in, can't login and dosen't stay logged in

### ISSUE THREAD

**Issue by DominykasUmbrasas** [th-ch/youtube-music#1753]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.1.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

1. Press sign in.
2. Write gmali.
3. Write password.

(
1. Press sign in.
2. Write gmali.
3. Change password.
5. Confirm on the phone.
6. Cancel change password.
7. Go back to youtube music.
)

### Expected Behavior

Login in to your account.
(
Login in to your account.
)

### Actual Behavior

Gives wrong password.
(
Login in to your account but after restarting program you need to login again.
)

### Enabled plugins

None / all dosen't matter I tried it all.

### Additional Information

There is a workaround but then it dosen't stay logged in. It's explained in "()".
PS I don't know should I be able to login. In documentation didn't fined anything about this. Also sorry for bad english.

**Comment by JellyBrick** [comment]
Can you reproduce this issue in [3.2.2?](https://github.com/th-ch/youtube-music/releases/download/v3.2.2/YouTube-Music-Web-Setup-3.2.2.exe)

**Comment by DominykasUmbrasas** [comment]
Yes still same with 3.2.2 version. Can't login unless i do work around like I mentioned in the bug report and still I get logged out after reopening the app.

**Comment by Sn-Kinos** [comment]
I removed YouTube Music data directory, It works. But I tried it macOS so I can't tell you the path of data directory.

**Comment by Pouiiro** [comment]
Same issue, can log in but will always need to log in when app restarts! any workarounds ?

**Comment by domhugs** [comment]
This had happend to me but by logging in with email and password rather than verifcation by phone its resolved the problem for me hope this helps !

**Comment by Makhubelen** [comment]
How can i get plugins
