### ISSUE TITLE
[Bug]: Doubled window decoration

### ISSUE THREAD

**Issue by MartinX3** [th-ch/youtube-music#1761]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Linux hostname 6.7.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:21 +0000 x86_64 GNU/Linux

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2.2

### Reproduction steps

Starting the application

### Expected Behavior

No double window decoration

### Actual Behavior

Double window decoration

### Enabled plugins

1. Navigation
2. SponsorBlock
3. AdBlock

### Additional Information

The inner buttons do nothing.

![image](https://github.com/th-ch/youtube-music/assets/4518092/d2786e4e-0612-486a-871c-1fca57fd0d21)

**Comment by JellyBrick** [comment]
fixed at 0ae5b668f50eac2e307e019f376c2d14dd7beba4
