### ISSUE TITLE
[Bug]: Video toggle Broken in all kinds of new ways because of new update (STILL NOT FIXED)

### ISSUE THREAD

**Issue by Zyanbob** [th-ch/youtube-music#1765]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 22H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2.0

### Reproduction steps

1. Enable video toggle on a version pass 3.2.2

### Expected Behavior

Turn on video Toggle then get music video in 360p without video quality changer

### Actual Behavior

no video when pressed on native toggle mode.
no toggle button at all in custom toggle mode:
![Screenshot 2024-02-20 070323](https://github.com/th-ch/youtube-music/assets/81934264/5b3aa767-0459-43e4-875b-78ce8eea6c2f)
Only way to reverse this is to restart the app

### Enabled plugins

![Screenshot 2024-02-20 065744](https://github.com/th-ch/youtube-music/assets/81934264/22e66691-9659-42ec-b889-2ff28726c813)

**Comment by ArjixWasTaken** [comment]
Can you confirm that this affects the latest version, at the moment, [3.3.1](https://github.com/th-ch/youtube-music/releases/tag/v3.3.1)?

**Comment by ArjixWasTaken** [comment]
Funnily enough, I encountered a new bug whilst trying to reproduce yours :^)

**Comment by Zyanbob** [comment]
3.3 really is bugged to hell and back

**Comment by Zyanbob** [comment]
so anyway what bug did you find trying to fix mine?

**Comment by ArjixWasTaken** [comment]
Not really sure, investigating it rn as it only happened once.

**Comment by ArjixWasTaken** [comment]
I get the expected behaviour

https://github.com/th-ch/youtube-music/assets/53124886/80dd2609-9867-455a-b6bb-aeac2744f5ab

**Comment by Zyanbob** [comment]
try it with music to video

**Comment by Zyanbob** [comment]
https://github.com/th-ch/youtube-music/assets/81934264/6b55c4a2-df4e-42e2-b28a-27cdf2bea05c

**Comment by Zyanbob** [comment]
[bug](https://github.com/th-ch/youtube-music/labels/bug)
