### ISSUE TITLE
[Bug]: Video toggle Broken

### ISSUE THREAD

**Issue by Zyanbob** [th-ch/youtube-music#1772]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 22H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

Who the fuck knows

### Reproduction steps

Follow this video:

https://github.com/th-ch/youtube-music/assets/81934264/a31155f2-c76e-44c3-bfba-53e90fdc1c4b

### Expected Behavior

Pressing song sends you to this:
![Screenshot 2024-02-20 154835](https://github.com/th-ch/youtube-music/assets/81934264/73c56fcb-97df-49b0-b297-ca3f48bbb0a9)
and pressing video send you to this: 
![Screenshot 2024-02-20 154948](https://github.com/th-ch/youtube-music/assets/81934264/a6d93242-c3a4-4259-82bf-0e777f63ead0)

### Actual Behavior

A notification on saying "video not available"on songs:
![Screenshot 2024-02-20 155154](https://github.com/th-ch/youtube-music/assets/81934264/f3b36365-bf2b-4591-9eaa-d3757f9ebf35)
solo videos only send you to a screenshot of the Thumbnail for the music video:
![Screenshot 2024-02-20 155111](https://github.com/th-ch/youtube-music/assets/81934264/006b0fdf-5b95-47ae-b550-2a5d138fede4)

### Enabled plugins

![Screenshot 2024-02-20 065744](https://github.com/th-ch/youtube-music/assets/81934264/e244268e-c18a-4198-a711-d3776e9c1f48)

**Comment by JellyBrick** [comment]
It's not our app's bug because YouTube's servers aren't providing the data.

And, 

> ### Last Known Working YouTube Music (Application) version
> Who the fuck knows

😅
