### ISSUE TITLE
[Bug]: Taskbar Media Controls not working in latest release

### ISSUE THREAD

**Issue by nshannon123** [th-ch/youtube-music#1784]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22621.3007

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2.2

### Reproduction steps

1. Play a song
2. Hover on YouTube Music icon on taskbar to show preview window
3. Media Controls missing

### Expected Behavior

Media Controls should be in preview window

### Actual Behavior

Media Controls are not in preview window

### Enabled plugins

1. Blur Navigation Bar
2. In-App Menu
3. Ad Blocker (In Player)
4. Navigation
5. Playback Speed
6. SponserBlock
7. Taskbar Media Control
8. Video Quality Changer

**Comment by nshannon123** [comment]
Note: Working in 3.3.1 but not in 3.3.2 - I had originally upgraded from 3.2.2 so I skipped a couple of versions

**Comment by JellyBrick** [comment]
Can't reproducible

![image](https://github.com/th-ch/youtube-music/assets/16558115/0b307fc8-10f4-44f5-8d25-8daef7f008dd)

**Comment by nshannon123** [comment]
Odd - After a reinstall and checking taskbar-media-controls off and back on again - they're working again in 3.3.2. Can close issue for now. Strange one
