### ISSUE TITLE
[Bug]: The song tab not showing.

### ISSUE THREAD

**Issue by MustafaEsatTemel** [th-ch/youtube-music#1792]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11 pro

### What CPU architecture are you using?

x64

### Reproduction steps

Hello guys as you can see from image. I didn't see the song tab. Always video showing to me. How can i fix this ?
![Screenshot_4](https://github.com/th-ch/youtube-music/assets/65919257/aa9a5cf7-a23c-4f69-a6d7-8835ca6cb673)

### Expected Behavior

How can i enable song tab.

### Actual Behavior

Hello guys as you can see from image. I didn't see the song tab. Always video showing to me. How can i fix this ?

![Screenshot_4](https://github.com/th-ch/youtube-music/assets/65919257/117627e9-93e4-4e0b-b66b-85fa2b79b6b6)

### Enabled plugins

Adblocker
discord
downloader
inapp menu
navigation

**Comment by ArjixWasTaken** [comment]
Use the video toggle plugin...

**Comment by MustafaEsatTemel** [comment]
Thanks.
