### ISSUE TITLE
[Bug]: can't connect to last fm

### ISSUE THREAD

**Issue by Hadriang** [th-ch/youtube-music#1794]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.1

### Reproduction steps

Enable scrobbler plugin
Allow access through last fm pop up

### Expected Behavior

Last fm pop up closes and "youtube-music" shows up in "Connected Applications" tab in my last fm account settings and app scrobbles title to my last fm profile.

### Actual Behavior

Allow access -> Last fm pop up closes -> then reopens, asking for access again. Despite allowing multiple times it doesn't show up in my connected applications on last FM, and app doesn't scrobble.

### Enabled plugins

1. ad blocker
2. album color theme
3. ambiant mode
4. compact sidebar
5. downloader
6. exponential volume
7. in-app menu
8. Lyrics genius
9. music together
10. navigation
11. Scrobbler
12. shortcuts
13. skip disliked songs
14. video toggle

### Additional Information

Tried rolling back to 3.3.1 where the pop up opens inside my browser and not as a youtube-music pop up, but still not working.
Double checked multiple times my last fm api key.
It was all working until right before 3.3.2 release i think. 
Im really not a dev but would love to be of help, love the app!

**Comment by JellyBrick** [comment]
> ### Actual Behavior
> Allow access -> Last fm pop up closes -> then reopens, asking for access again. Despite allowing multiple times it doesn't show up in my connected applications on last FM, and app doesn't scribble.

Logically, the popup shouldn't open multiple times (assuming authentication hasn't failed).

Could you please open the config.json in `%appdata%\YouTube Music` and check if the `token` and `sessionKey` exist in `"lastfm"` in `"scrobblers"`?

**Comment by Hadriang** [comment]
> > ### Actual Behavior
> > Allow access -> Last fm pop up closes -> then reopens, asking for access again. Despite allowing multiple times it doesn't show up in my connected applications on last FM, and app doesn't scribble.
> 
> Logically, the popup shouldn't open multiple times (assuming authentication hasn't failed).
> 
> Could you please open the config.json in `%appdata%\YouTube Music` and check if the `token` and `sessionKey` exist in `"lastfm"` in `"scrobblers"`?

Token does exist, but no session key 
![image](https://github.com/th-ch/youtube-music/assets/150167462/51146447-a5cb-4bb6-8799-c932a227dca9)

**Comment by JellyBrick** [comment]
I think it was probably a bug in `v3.3.1` that caused the problem with the last-fm settings, thanks for the detailed report!
