### ISSUE TITLE
[Bug]: close button of "save to playlist" not work

### ISSUE THREAD

**Issue by ACaccel** [th-ch/youtube-music#1796]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

.

### Expected Behavior

The button is clickable on official yt music

### Actual Behavior

![image](https://github.com/th-ch/youtube-music/assets/92323576/65f5d6e4-ce50-4a67-995c-ceac3280c2ae)

close button of "save to playlist" not work (cannot click the "x" icon)

### Enabled plugins

none

**Comment by luluna02** [comment]
Could not reproduce, works fine for me on MacOS (14.3.1)
