### ISSUE TITLE
Start in tray

### ISSUE THREAD

**Issue by fernandogobah** [th-ch/youtube-music#18]
Is possible start the app in tray bar?

**Comment by Subratappt** [comment]
## The following codes will give you tray
```js
const path = require('path');
const trayIcon = path.join(__dirname, 'assets/icon.ico');
//const trayIcon = nativeImage.createFromPath("./assets/icon.png");

app.on("ready", () => {
  tray = new Tray(trayIcon)
  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Play/Pause', click: function () {
        hook_ytm("#left-controls > div > paper-icon-button.play-pause-button.style-scope.ytmusic-player-bar")
      }
    },
    {
      label: 'Next', click: function () {
        hook_ytm("#left-controls > div > paper-icon-button.next-button.style-scope.ytmusic-player-bar")
      }
    },
    {
      label: 'Prev', click: function () {
        hook_ytm("#left-controls > div > paper-icon-button.previous-button.style-scope.ytmusic-player-bar")
      }
    },
    {
      label: 'Show', click: function () {
        win.show()
      }
    },

    {
      label: 'Quit', click: function () {
        app.quit()
      }
    },
  ])
  tray.setToolTip('Youtube Music')
  tray.on('double-click', () => {
    win.show()
  })
  if (process.platform == 'win32') {
    tray.on('click', tray.popUpContextMenu)
  }
  tray.setContextMenu(contextMenu);
  createWindow();
}
)

// bla bla bla

async function createWindow() {
  win = new BrowserWindow({
    backgroundColor: "#000",
    webPreferences: { nodeIntegration: false, contextIsolation: true },
	// bla bla bla
  })

  win.on('close', (event) => {
    if (app.quitting) {
      win = null
    } else {
      if (process.platform == 'darwin') {
        app.dock.hide()
      }
      event.preventDefault()
      win.hide()
    }
  })

  await win.loadURL('https://music.youtube.com')

  return win;
}


function hook_ytm(selector) {
  win.webContents.executeJavaScript('document.querySelector("' + selector + '").click();', true)
}

**Comment by th-ch** [comment]
Hey @fernandogobah , thanks for submitting the issue! The latest version ([v1.3.1](https://github.com/th-ch/youtube-music/releases/tag/v1.3.1)) has an "options" menu, you can enable tray and set the window visible or hidden - with "Tray + hidden window", you should have the behavior "start in tray".

Feel free to re-open this issue if it does not work properly!

**Comment by Subratappt** [comment]
Version: 1.3.1
1. For **Windows**, when the **tray** is on, please change  ```close``` button behaviour of window from ```quit``` to ```hide```.
2. In the tray, ```play/pause``` is not working properly.

**Comment by th-ch** [comment]
Hey @Subratappt, thanks for reporting both issues!

[v1.3.2](https://github.com/th-ch/youtube-music/releases/tag/v1.3.2) should fix issue 1, the app should now not exit if the tray is on (unless you select "Quit" in the tray menu) + clicking on the tray icon should now show/hide the app.

For the second issue, `play/pause` seems to work fine for me (tested on Windows/Mac) unless the plugin "autoconfirm when paused" is enabled (playing is resumed automatically by the plugin just after pausing), do yo have it enabled? This plugin is still quite experimental (it also messes up with play/pause through media keys) - if you don't have this plugin enabled, then it might be another bug! - which plugins do you use in the app?

**Comment by Subratappt** [comment]
> Hey @Subratappt, thanks for reporting both issues!
> 
> [v1.3.2](https://github.com/th-ch/youtube-music/releases/tag/v1.3.2) should fix issue 1, the app should now not exit if the tray is on (unless you select "Quit" in the tray menu) + clicking on the tray icon should now show/hide the app.
> 
> For the second issue, `play/pause` seems to work fine for me (tested on Windows/Mac) unless the plugin "autoconfirm when paused" is enabled (playing is resumed automatically by the plugin just after pausing), do yo have it enabled? This plugin is still quite experimental (it also messes up with play/pause through media keys) - if you don't have this plugin enabled, then it might be another bug! - which plugins do you use in the app?

Thank you for the update. Yes for the second issue, "autoconfirm when paused" was enabled. I hope you will get the issue solved soon.

**Comment by benji009** [comment]
Is it possible to add auto start when you turn on the computer?

**Comment by th-ch** [comment]
Hey @benji009, thank you for the feedback! 

https://github.com/th-ch/youtube-music/pull/32 adds an option to autostart the application at login (YouTube Music then starts playing automatically) which is available in the [1.4.0 pre-release](https://github.com/th-ch/youtube-music/releases/tag/v1.4.0) but only works for Mac/Win (limitation of electron), would this do the job for you?

**Comment by benji009** [comment]
yes that is perfect :)

**Comment by th-ch** [comment]
It seems the last open problem in this issue is the auto-confirm-when-paused vs media keys - it seems it is fixed in the last versions but in case it's not, it will be tracked in https://github.com/th-ch/youtube-music/issues/129 - closing this one, feel free to re-open/open a new issue if needed!
