### ISSUE TITLE
[Bug]: FPS Lock/Drop when having the App run in background while playing games

### ISSUE THREAD

**Issue by SleepDaemon** [th-ch/youtube-music#1803]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Version 23H2 OS Build 22631.3155

### What CPU architecture are you using?

x64

### Reproduction steps

Just have the app running in the background while running a game, for me in Rainbow Six Siege or in any game where I get 144fps.

### Expected Behavior

Shouldn't lock or drop FPS while running in background

### Actual Behavior

It gets locked to 100fps but after closing the app it is 144fps.

### Enabled plugins

![image](https://github.com/th-ch/youtube-music/assets/88533953/16b9c7ab-51b4-41d6-9d13-d0e6dd7ffad5)
![image](https://github.com/th-ch/youtube-music/assets/88533953/fbb1faee-35c5-4cbe-9085-1c2cc0b0cd07)

**Comment by SleepDaemon** [comment]
Been having this issue probably since v3.0 or less, I am not sure since I always assume it was something with the computer itself.

**Comment by frostybiscuit** [comment]
Can you still reproduce this issue when you disable all plugins?
Also, have you tried disabling hardware acceleration to see if it still happens then? (Options -> Advanced -> Disable hardware acceleration)

**Comment by SurajBhari** [comment]
I can reproduce this bug @JellyBrick can you reopen this issue 

I tried disabling all the plugins. still same 
disabled hardware acceleration


it only happens when i connect my bluetooth speaker. on laptop speaker it works fine.

**Comment by JellyBrick** [comment]
I think it's a bug in the Windows

**Comment by JellyBrick** [comment]
What is the specifications of your PC?

@SleepDaemon @SurajBhari 

And, can you provide the reproduction steps?

**Comment by SurajBhari** [comment]
Am on a laptop r7 5800h. Rtx 3060. 16gig ram.

**Comment by JellyBrick** [comment]
> As for steps just have the app open in background running. While playing a game. 

Can you reproduce it on https://music.youtube.com? (with Chrome)

**Comment by SleepDaemon** [comment]
> > As for steps just have the app open in background running. While playing a game. 
> 
> Can you reproduce it on https://music.youtube.com? (with Chrome)
> 
> @SleepDaemon 

I don't get on browsers

**Comment by frostybiscuit** [comment]
I will try to reproduce this at home, but I've been gaming next to YT music and had no lags so far. I would assume this is either a Windows task priorization or laptop energy control issue.

@SleepDaemon @SurajBhari 
What game were you playing and what power profile were you on? Also is YT music running on the dedicated GPU or on the integrated one?

**Comment by SurajBhari** [comment]
As for the game its f1 22 for me. And no it doesn't happen same with browser (edge). For me it's only doing this on bluetooth speakers. And not on laptop speakers.

**Comment by SleepDaemon** [comment]
> I will try to reproduce this at home, but I've been gaming next to YT music and had no lags so far. I would assume this is either a Windows task priorization or laptop energy control issue.
> 
> @SleepDaemon @SurajBhari What game were you playing and what power profile were you on? Also is YT music running on the dedicated GPU or on the integrated one?

I get it on Siege, I have hardware acceleration enabled i think. My CPU is Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz

**Comment by frostybiscuit** [comment]
> I get it on Siege, I have hardware acceleration enabled i think. My CPU is Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz

I tried reproducing this with a couple of games like AC:Valhalla, Starfield, Cyberpunk 2077, GTA 5 and a few other, but nothing noticable. I also had them fully cranked up so my GPU is at 100% utilization but to no avail.
I'm running it on Win11 with an RTX3080 and an i712700K. Am I right to assume that both of you are running it on a laptop?

To me this still sounds like YT Music is running through the iGPU which is lowered to a minimum when the dedicated GPU is being used. Could you check what GPU it is running on for you?
You can check that by opening the task manager and enabling "GPU engine" by right-clicking any of the column headers and it should look like this:
![image](https://github.com/th-ch/youtube-music/assets/128132341/063ef1c5-f294-4aab-aac4-2e63fc452bae)

**Comment by SleepDaemon** [comment]
> > I get it on Siege, I have hardware acceleration enabled i think. My CPU is Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz
> 
> I tried reproducing this with a couple of games like AC:Valhalla, Starfield, Cyberpunk 2077, GTA 5 and a few other, but nothing noticable. I also had them fully cranked up so my GPU is at 100% utilization but to no avail.
> I'm running it on Win11 with an RTX3080 and an i712700K. Am I right to assume that both of you are running it on a laptop?
> 
> To me this still sounds like YT Music is running through the iGPU which is lowered to a minimum when the dedicated GPU is being used. Could you check what GPU it is running on for you?
> You can check that by opening the task manager and enabling "GPU engine" by right-clicking any of the column headers and it should look like this:
> ![image](https://github.com/th-ch/youtube-music/assets/128132341/063ef1c5-f294-4aab-aac4-2e63fc452bae)
> 
> 

It's running on my dedicated GPU, not iGPU

**Comment by frostybiscuit** [comment]
@SleepDaemon Did you check if the CPU or GPU are at 100% when this happens? Like, are you using an FPS lock in your games or do you just let them use as much as possible?

I'm honestly running out of ideas here 🙈

**Comment by SleepDaemon** [comment]
> @SleepDaemon Did you check if the CPU or GPU are at 100% when this happens? Like, are you using an FPS lock in your games or do you just let them use as much as possible?
> 
> I'm honestly running out of ideas here 🙈

I said what I experience and discovered, I'll try out today running Siege with the app. If I still get the issue just with this app and nothing I will let you know.
