### ISSUE TITLE
[Bug]: Audio Randomly Cuts Out

### ISSUE THREAD

**Issue by UserPendslol** [th-ch/youtube-music#1804]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

sonoma 14.1

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2.2

### Reproduction steps

I installed the app using the reinstall command on homebrew.

### Expected Behavior

The music plays until it is paused or the app is quit.

### Actual Behavior

The audio cuts out at random points of a song (then comes back) while it is playing. It happens most frequently when the song changes or when the app has been minimized. It happens for every song that is played. Skipping to a different point of a song or changing it does not bring back the audio.

### Enabled plugins

Album Actions
Blur Navigation Bar
Album Color Theme
Ambient Mode
Ad Blocker
Crossfade
Downloader
In-App Menu
Lyrics Genius
Navigation
Playback Speed
PiP
Skip Disliked Songs
Touchbar

### Additional Information

The audio plays correctly when I disable the crossfade plug-in. When I re-enabled it, the audio mainly cut out when the app was shown after being hidden.

**Comment by JellyBrick** [comment]
Are you having the same issue as #1775?
