### ISSUE TITLE
[Bug]: Youtube music having 50% cpu usage, when it used to be 4-5%

### ISSUE THREAD

**Issue by supertrio17** [th-ch/youtube-music#1807]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

Few versions back, don't know which one

### Reproduction steps

Starting the app seems to be okay cpu usage wise, I don't remember being this many processes, and it seems that sometimes the app will work fine even if i close the process that is taking 40-50% of cpu. Issue begins when something else is taking up some cpu space, for example when starting a game, the cpu usage of the yt music will spike to 40-50%

![image](https://github.com/th-ch/youtube-music/assets/57882120/87a23b75-8699-4b74-851e-e019150a14fe)

### Expected Behavior

Around 5% cpu usage

### Actual Behavior

50% cpu usage

### Enabled plugins

AdBlocker, Precise Volume, Shortcuts, Video toggle and Visualizer.

**Comment by supertrio17** [comment]
![image](https://github.com/th-ch/youtube-music/assets/57882120/235f6648-6ae3-4f4b-9292-2b24bd13ab90)

**Comment by supertrio17** [comment]
Hmm, I was going on around different options, and I seem to have found a temp solution. When I have tray set as 'Enabled and hide app' bug occurs, I tried changing it to 'Enabled and show app' and it seems to have worked. Now overall processes are chilling around 1-2 % with highest being around 10 %.

![image](https://github.com/th-ch/youtube-music/assets/57882120/c022f891-0fc8-4e2b-9f38-917c88b3ff4c)

PS: I aslo enabled Exponentional Volume so that might have been the fix, I'm not sure.

**Comment by supertrio17** [comment]
@JellyBrick Hey, I was wrong, seems it has to be something with visualizer plugin, I have the plugin enabled, even tho I have video disabled. I confirmed it.

This is with visualizer on:
![image](https://github.com/th-ch/youtube-music/assets/57882120/d929287a-868f-4cb7-b585-757196c1fb56)

This is with visualizer plugin disabled:
![image](https://github.com/th-ch/youtube-music/assets/57882120/bf0e5790-a534-438f-b421-692b853f2711)

PS: Keep in mind that cpu usage is normal when the app is in the background, but I have it open on my second monitor while gaming. I'm not sure if this is expected behaviour, I have i7-8700k so it shouldn't use over 10% even if I have visualizer plugin enabled, yet its utilizing over 50% of cpu.

**Comment by JellyBrick** [comment]
@supertrio17 Which type of visualizer are you using?

**Comment by supertrio17** [comment]
> @supertrio17 Which type of visualizer are you using?

I had butterchurn enabled, but like I said, I never saw it because my video is always disabled.

**Comment by JellyBrick** [comment]
Caused by butterchurn renderer
