### ISSUE TITLE
[Bug]: Unable to run the project 

### ISSUE THREAD

**Issue by luluna02** [th-ch/youtube-music#1812]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.3

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Pull the latest version 
2. Install the packages
3. Run project

### Expected Behavior

Project to run successfully. 

### Actual Behavior

Project failed to run.

[5664:0229/175415.631258:ERROR:platform_util_mac.mm(282)] Unable to set login item: Failed to register the login item
[YTMusic] Finished loading. DevTools opened

[5664:0229/175418.353537:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

<img width="1101" alt="Screenshot 2024-02-29 at 6 19 47 PM" src="https://github.com/th-ch/youtube-music/assets/133816965/78479a1e-1481-4bc8-b49a-cf6ccc1c06bb">

### Enabled plugins

None

**Comment by JellyBrick** [comment]
https://github.com/quasarframework/quasar/issues/16741

YTMD includes `electron/remote` in its dependency graph, but it's not a module we use at all in our project, so this is an error you can ignore.

**Comment by luluna02** [comment]
I am also getting this error : "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

<img width="1080" alt="Screenshot 2024-02-29 at 7 42 13 PM" src="https://github.com/th-ch/youtube-music/assets/133816965/b7e635fb-1703-408f-b1f3-d0a9c8a5fedf">
