### ISSUE TITLE
[Feature Request]: Reinitialize tray icon on scale change

### ISSUE THREAD

**Issue by limonovthesecond2** [th-ch/youtube-music#1813]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If you change the screen scale after launching the application, the resolution of the tray icon will not change. So the icon will be blurry

### Proposed Solution

Add a listener that reinitializes the tray when the scale changes

### Alternatives Considered

The implementation may differ, but the idea is the same: need to re-execute setUpTray

### Additional Information

This may be a Windows specific issue

**Comment by JellyBrick** [comment]
ref: https://www.electronjs.org/docs/latest/api/screen#event-display-metrics-changed

**Comment by limonovthesecond2** [comment]
Implementing this feature seems very simple. The tray needs to `destroy` the old one in the "tray.ts" and something like this in "index.ts":
```
screen.on('display-metrics-changed', (_, __, changedMetrics) => {
    if (changedMetrics.includes("scaleFactor")) {
      if (is.windows()) {
        setUpTray(app, mainWindow!);
      }
    }
  });
```
However, there are not many apps with this feature. Windows explicitly says after changing the scale that "Some applications will not change until they are reopened" Considering this, I find this feature to be rather useless
