### ISSUE TITLE
[Improvement] Discord RPC with song thumbnail

### ISSUE THREAD

**Issue by emigrek** [th-ch/youtube-music#182]
Is it possible to do? Even without these buttons.

![test](https://user-images.githubusercontent.com/25348531/110601320-1a7d8800-8185-11eb-9d1a-7c291637987d.png)

**Comment by emsquellen** [comment]
(Disclaimer, I’m not part of this project/collaborating on it, just enjoying it too!)

Correct me if I’m wrong, but I don't think that's possible — all images you can use as in a Discord Presence have to be already cached as assets in a registered Discord Application (not from URL). The maximum amount of them is 150 which is not quite enough (to view every album/thumbnail of the video you’re currently playing). If I’m not mistaken Spotify uses a custom way of showing every album, which is not publicly available. (Not to mention copyright!).
