### ISSUE TITLE
[Bug]: "Starting papage" is always "Home" no matter what the option is actually set to

### ISSUE THREAD

**Issue by soarpasser** [th-ch/youtube-music#1822]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Win10 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

Set starting page to anything other than "Home"
Launch/restart the application

### Expected Behavior

The application launches on the page the user specifies

### Actual Behavior

The application always starts from "Home"

### Enabled plugins

For easier troubleshooting I have attached the config.json file directly.
[config.json](https://github.com/th-ch/youtube-music/files/14473131/config.json)

**Comment by now-its-dark** [comment]
I've also been experiencing this issue on MacOS ARM version 3.3.6. 
Seems like this should just be a matter of setting the starting link to, for example, "https://music.youtube.com/library/uploaded_albums" or whichever page is desired. Attempting to manually edit the config.json file and set that link for the "url" field, it also has no effect.

**Comment by trueTrueman** [comment]
Same issue on 3.3.6.0

**Comment by teamshortcut** [comment]
I'm also experiencing this on 3.3.10.0

**Comment by now-its-dark** [comment]
Just updated to 3.3.12, this issue is still present
