### ISSUE TITLE
Program installing to temp folder

### ISSUE THREAD

**Issue by seetowsh** [th-ch/youtube-music#183]
When I install/update the program it installs into the temp folder and doesn't install the shortcuts either. It gets deleted after restarting my computer.

Platform: Windows 10 2003

**Comment by Hi1307** [comment]
Hi sorry I realised that I was opening the program itself and not the installer. Perhaps next time the "portable" installation can be packaged as a zip and not an exe that installs to the temp folder.

**Comment by emigrek** [comment]
U can unzip .exe file to a folder like this:

![10-03-2021_15-07-15](https://user-images.githubusercontent.com/25348531/110641548-74487700-81b2-11eb-97f8-8191c13ce78a.gif)

**Comment by touzel** [comment]
Thanks! I had the same issue and unzipping the .exe fixed it.
