### ISSUE TITLE
[Bug]: Windows Defender claims YouTube Music 3.0.2 is malware?

### ISSUE THREAD

**Issue by wininusthefirst** [th-ch/youtube-music#1830]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 OS Build 22631.3235

### What CPU architecture are you using?

x64

### Reproduction steps

1. Tried to open the app, and it opened
2. Windows claimed the app is malware

### Expected Behavior

1. App will open without issue

### Actual Behavior

Windows claims the application is malware
![image_2024-03-04_132200947](https://github.com/th-ch/youtube-music/assets/82335636/0ce4954c-3f8f-4ef1-ad3c-c322e42e2d40)

### Enabled plugins

1. Ad blocker

### Additional Information

So I was looking at my Windows Defender and it claimed that The Web Version (3.0.2) is a trojan known as Vigorf.A.

**Comment by JellyBrick** [comment]
It's a false positive. (Defender's bug)

see https://github.com/electron-userland/electron-builder/issues/550, https://github.com/electron-userland/electron-builder/issues/6334
