### ISSUE TITLE
[Bug]: Scrollbar appears in custom titlebar

### ISSUE THREAD

**Issue by MulverineX** [th-ch/youtube-music#1835]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable the In-App-Menu (if its not already enabled)

### Expected Behavior

scrollbar stops at the bottom edge of the titlebar; no page content should escape the boundary

### Actual Behavior

![image](https://github.com/th-ch/youtube-music/assets/12068027/f9c9e10e-6899-44fc-9172-892e6c13c998)

### Enabled plugins

1. In-App-Menu
2. Album color theme
3. Blur nav
4. If any other plugins are relevant please let me know

**Comment by colineberly** [comment]
Is there a way to have scrollbars only appear if you scroll, or maybe another way to minimize them with css?
