### ISSUE TITLE
 There is no option to return when selecting the sign-in button.

### ISSUE THREAD

**Issue by KhNediem** [th-ch/youtube-music#1845]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

Click on sign-in button.

### Expected Behavior

A button to go back should appear if user decided to not sign-in.

### Actual Behavior

No button appears

### Enabled plugins

In-App-Menu
Navigation

**Comment by JellyBrick** [comment]
Use the "Navigation" -> "Go back" button.
