### ISSUE TITLE
[Feature Request] Discord Current Song Reporting Timeout (Reposted)

### ISSUE THREAD

**Issue by ashirbhallalevine** [th-ch/youtube-music#185]
As posted in a [previous issue thread](#161) and reposted by recommendation:

Please add a Discord song-reporting timeout such that the app reports which song is being played when paused but clears the song in favor of simply reporting "Playing YouTube Music" after a certain timeout (5 minutes sounds about right to me) and then clears the entire Game Activity status after another defined amount of inactive time until activity is detected again (10 minutes sounds good for this one). I have suggested possible time-frames for these actions, however, a selectable option menu would always be preferred.

Please do let me know if you have any questions about the above feature request and I would be more than happy to clarify!

**Comment by semvis123** [comment]
I made this feature in #192, would love to hear your opinion about it.

**Comment by ashirbhallalevine** [comment]
> I made this feature in #192, would love to hear your opinion about it.

Hey, thank you for picking up this feature request! I took a look at the file changes you made in #192 and, as far as I can tell, it is an accurate reflection of the feature I requested above. Like I said in the original suggestion, an additional dropdown menu with a few different options (say 5 mins, 10 mins, 15 mins) for the "activityTimoutTime" would be even better.

**Comment by semvis123** [comment]
Thanks for your feedback, the time is configurable in the `advanced options`, so I don't think we need a dropdown menu specifically for this setting of this plugin.

**Comment by ashirbhallalevine** [comment]
> Thanks for your feedback, the time is configurable in the `advanced options`, so I don't think we need a dropdown menu specifically for this setting of this plugin.

Sounds good! I figured this may be the case, but I couldn't quite tell from the files you changed as I am still familiarizing myself with the file structure of this project. Thanks!

**Comment by semvis123** [comment]
There should be a (menu) button under `plugins` called `advanced options` which should take you to the specific file you will need to change.

**Comment by ashirbhallalevine** [comment]
> There should be a (menu) button under `plugins` called `advanced options` which should take you to the specific file you will need to change.

Ah, yes. I see that the `activityTimeoutTime` variable is defined in the `config.json` file. Thanks again for adding this feature!

**Comment by semvis123** [comment]
No problem!
