### ISSUE TITLE
[MacOS] “YouTube Music” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by andreiropotica** [th-ch/youtube-music#186]
Hello!

I am getting after first install and after todays update the folowing error on opening the app:

![image](https://user-images.githubusercontent.com/11310468/110643101-65ff5880-81bc-11eb-8725-69e23e1761cb.png)

The workarround/solution I found was executing: `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app` after each install/update.

Is there another way to avoid this error on the next update?

Thank you very much for all your hard work!
Andrei

**Comment by Bellisario** [comment]
I'm not very expert about MacOS, but if I remember correctly, you can open the app without this error (after installation) with right click on the app (I don't know if you have right click enabled, anyway, you need to open the action menu) and click "Open".

**Comment by andreiropotica** [comment]
Sorry for the late response. it worked, I did not have a new update at that moment... 

Weird macOS...

Thank you for your help!

**Comment by itzmanish** [comment]
> The workarround/solution I found was executing: xattr -d com.apple.quarantine /Applications/YouTube\ Music.app after each install/update.

This should be in pinned in issues or discussion as mac os fix. Thanks @andreiropotica this always helps after reinstall.

**Comment by JellyBrick** [comment]
see this link: https://github.com/th-ch/youtube-music#macos

**Comment by inson1** [comment]
btw if I get it correctly, fix it fully (so that user wouldnt need to do anything) would need developer account, which cost 99 dollars per year

**Comment by JsThiago** [comment]
> `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`

Does anyone know why this command works?

**Comment by ArjixWasTaken** [comment]
> > `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`
> 
> Does anyone know why this command works?

I'd assume `-d` means `delete`, so you are deleting the `com.apple.quarantine` attribute from the app

**Comment by indexxing** [comment]
> > `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`
> 
> Does anyone know why this command works?

I saw someone recommend this similar command for another app, it apparently just tells macOS to let you open it despite the creator/app being unverified/unsigned. Take this with a grain of salt because I'm only recalling from a Reddit thread on the Zen browser

**Comment by ArjixWasTaken** [comment]
> > > `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`
> > 
> > Does anyone know why this command works?
> 
> I saw someone recommend this similar command for another app, it apparently just tells macOS to let you open it despite the creator/app being unverified/unsigned. Take this with a grain of salt because I'm only recalling from a Reddit thread on the Zen browser

Thanks for saying what I already said?

**Comment by indexxing** [comment]
> > > > `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app`
> > > 
> > > 
> > > Does anyone know why this command works?
> > 
> > 
> > I saw someone recommend this similar command for another app, it apparently just tells macOS to let you open it despite the creator/app being unverified/unsigned. Take this with a grain of salt because I'm only recalling from a Reddit thread on the Zen browser
> 
> Thanks for saying what I already said?

geez sorry

**Comment by ArjixWasTaken** [comment]
Ok I came off way too rude.
I didn't mean to and I am sorry about that.

I won't give excuses, I was just confused by the GitHub notification I received.

**Comment by indexxing** [comment]
> Ok I came off way too rude. I didn't mean to and I am sorry about that.
> 
> I won't give excuses, I was just confused by the GitHub notification I received.

Ah, sorry for the notification

**Comment by kiritocode1** [comment]
yeah , lol not even the windows version does not run with rosetta

**Comment by pseonghwa200-ops** [comment]
> The workarround/solution I found was executing: `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app` after each install/update.
> 

Where am I supposed to enter this code to execute? Sorry I have no background in coding so this is all very new to me.

**Comment by indexxing** [comment]
> 
> > The workarround/solution I found was executing: `xattr -d com.apple.quarantine /Applications/YouTube\ Music.app` after each install/update.
> > 
> 
> Where am I supposed to enter this code to execute? Sorry I have no background in coding so this is all very new to me.
> 
> 

Run it in the terminal
