### ISSUE TITLE
[Feature Request]: Native Titlebar Option

### ISSUE THREAD

**Issue by D-Maxwell** [th-ch/youtube-music#1860]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am a huge fan of the 3.x menu bar look ; although I wish there were an option to have it be shown as an overlaying nav within the app, below a native titlebar, instead of mandatorily merging the two.

### Proposed Solution

This would also bring back the app's title.

### Alternatives Considered

...

### Additional Information

This would allow third party titlebar customisation.

**Comment by JellyBrick** [comment]
> an overlaying nav within the app, below a native titlebar, instead of mandatorily merging the two.

I don't understand what you mean, can you explain it with a simple (example) drawing?

**Comment by D-Maxwell** [comment]
> > an overlaying nav within the app, below a native titlebar, instead of mandatorily merging the two.
> 
> I don't understand what you mean, can you explain it with a simple (example) drawing?

Well, actually, this seems to have somehow been fixed.

Perhaps a restart helped it after I set a setting somewhere ?

Anyway, this is what it looks like now, and I much prefer it that way :
![image](https://github.com/th-ch/youtube-music/assets/98100481/335163d7-7c7e-4312-a829-9b94275e2cce)

In order to access the menu bar, it must be toggled with `alt`.

This is essentially what it looked like back in 2.x.

**Comment by JellyBrick** [comment]
Perhaps deactivating the `in-app-menu` plugin and then enabling `hide menu` will solve this issue as shown in the screenshot above. 
Can you try this?

**Comment by D-Maxwell** [comment]
> Perhaps deactivating the `in-app-menu` plugin and then enabling `hide menu` will solve this issue as shown in the screenshot above. Can you try this?

This does indeed fix it. Thank you !
