### ISSUE TITLE
[Bug]: Mediaplay back keys do not work when launched as Administrator

### ISSUE THREAD

**Issue by ktrin-u** [th-ch/youtube-music#1871]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Version 21H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Launch as Application as Administrator
2. Try to play/pause using media keys

### Expected Behavior

Pressing media keys (play/pause, previous, next) should activate corresponding function.

### Actual Behavior

Nothing happens.

### Enabled plugins

1. Album Actions
2. Bypass Age Restrictions
3. Exponential Volume
4. In-app Menu
5. Navigation
6. Skip Disliked Songs
7. Taskbar Media Control

### Additional Information

The reason why I am launching YTM as admin is because my Discord is launched as admin as well.

 The plugin `Discord Rich Presence` does not work if YTM is not run as admin.

I have tried using the `Shortcuts` plugin and while it works for local controls, global does not work so I just disabled it. Configuration for `Shortcuts` were done through `config.json` since attempting to bind media playback keys within the application gives me `undefined`. 

Any ideas on how to make this work or is there no other choice but to run both apps as non-admin?

**Comment by SomeAspy** [comment]
On a slightly unrelated note, why are you launching discord as admin? I believe this would effectively make it so *any* RPC program utilizing the websocket cannot work - Games are often process scanned by Discord, nullifying the effect you would see on most games. (You can peek at the internals of Discord's RPC system at https://github.com/OpenAsar/arrpc)

My opinion is that this issue should be closed as wontfix, as you shouldn't be running Discord nor YTMD as admin - I don't see a reasonable purpose to run Discord elevated.

**Comment by ktrin-u** [comment]
I run discord as admin out of convenience. When streaming, DiscordHookHelper (if my memory serves correctly) would ask for elevated permissions sometimes that I had to confirm manually.

I appreciate the explanation behind the issue. In that case I'll close this issue.

**Comment by ArjixWasTaken** [comment]
You shouldn't run discord as admin especially if you are using client mods like vencord.

A malicious third party plugin would also have admin permissions if discord is ran using admin permissions.

(On vencord that shouldn't be that bad as long as you are not using third party plugins)

**Comment by ktrin-u** [comment]
I see. I'm just using the official discord client vanilla, hence, why I wasn't too worried though at the end of the day that is a point of vulnerability either way.

Appreciate the headsup
