### ISSUE TITLE
[Feature Request]: Remote integration

### ISSUE THREAD

**Issue by TokenOfRespect** [th-ch/youtube-music#1893]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The old Ytmd connector app had a remote integration where I could control the audio (pause skip forward and backwards as well as view the currently playing song) and in the new version I don't see a plugin or setting for it

### Proposed Solution

A way to use remote intergration

### Alternatives Considered

No other alternatives known.

**Comment by ArjixWasTaken** [comment]
[th-ch/youtube-music](https://github.com/th-ch/youtube-music) has never had a remote integration.
You are confusing it with [ytmdesktop/ytmdesktop](https://github.com/ytmdesktop/ytmdesktop) which appears to have been purged from existence.

[Here](https://web.archive.org/web/20240221225001/https://github.com/ytmdesktop/ytmdesktop) is a web archive of their repository.

---

Although I am now curious on what happened.
I'm going to CC the public members of the now deleted org.

@adlerluiz, @NovusTheory, @rickpalmeira, @mingjun97, @Alipoodle

What happened?
Did you receive a DMCA notice from YouTube?
