### ISSUE TITLE
[Bug]: Window gets stuck on phantom display after disconnecting second display

### ISSUE THREAD

**Issue by evanwon** [th-ch/youtube-music#1894]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.5

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Reproduction steps

1. Open th-ch/youtube-music on a machine with multiple monitors connected (e.g. a laptop with an external display)
2. Move the player window to a secondary window
3. Exit th-ch/youtube-music
4. Disconnect the secondary monitor
5. Re-open th-ch/youtube-music

### Expected Behavior

The th-ch/youtube-music player window should be visible on the screen

### Actual Behavior

The th-ch/youtube-music player window is not visible on the screen - you can briefly see the animation as the app opens on the now-disconnected display, and it is not possible to move it back to another display.

### Enabled plugins

Only the defaults:

1. In-App Menu
2. Navigation

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music/blob/371805334b0d24568c20db3fae31455b2c99eea1/src/index.ts#L311-L344

I think the logic to prevent offscreen rendering was not working correctly.
Can you provide the scale and resolution of your displays?

**Comment by evanwon** [comment]
@JellyBrick 

Two external displays, both identical: 2560 x 1440, 100% scale

**Comment by ArjixWasTaken** [comment]
Is the <kbd>win</kbd> + <kbd>←</kbd> shortcut not enough to bring it back to the left monitor?

**Comment by ArjixWasTaken** [comment]
> https://github.com/th-ch/youtube-music/blob/371805334b0d24568c20db3fae31455b2c99eea1/src/index.ts#L311-L344
> 
> I think the logic that prevents offscreen rendering is not working properly. Can you provide the scale and resolution of your displays?

on that note, iirc under wayland you cannot know the position of a window
but that doesn't apply here since they said they are using Windows 10

**Comment by ChangedUser** [comment]
@ArjixWasTaken 
No, sadly the windows shortcuts did not work.
