### ISSUE TITLE
[Feature Request]: Maybe YT Music x BetterDiscord/Vencord?

### ISSUE THREAD

**Issue by patYczakus** [th-ch/youtube-music#1897]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I see [Discord plugin *SpotifyControls*](https://betterdiscord.app/plugin/SpotifyControls), which control the music from Spotify. I had an idea to make similar plugin to BetterDiscord/Vencord and maybe to YouTube Music (or built-in function).

### Proposed Solution

The best option for me would be to do the communication to the Discord plugin via some sort of API.

### Alternatives Considered

Alternatively, it can be done by reading/saving a file located in a certain place.

**Comment by akromovx** [comment]
Spotify controls powered by Spotify api, if u want this make discord plugin lol

**Comment by h-banii** [comment]
I'm not familiar with what Better Discord plugins are allowed to access, but maybe you could try using MPRIS to do it? You can play/pause, prev, next, shuffle, set position offset (+/-) with it.

Also, does it need to be inside discord? I personally just use it on my taskbar (through mpris).
![image](https://github.com/th-ch/youtube-music/assets/121690516/12307716-f7b5-4747-b847-f095f9431c43)
It feels more convenient, but it's just a suggestion, I don't know about your case...

Good luck!

**Comment by TParavani** [comment]
You can do it by using the LastFMRichPresence plugin on Vencord, then linking it to your LastFM API, that way you'll be able to share what you are listeing on Youtube Music on Discord in real time.
![image](https://github.com/th-ch/youtube-music/assets/117674444/e2d78d43-02e5-41ec-8b5e-3fa6db374b16)

**Comment by ArjixWasTaken** [comment]
Might work on it

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/2fde86a1-9eb3-4cc8-b10b-382bd55473e1)

We are creating an API server (remote control). We expect this issue to be resolved when we complete that

**Comment by patYczakus** [comment]
> Spotify controls powered by Spotify api, if u want this make discord plugin lol

Bro thinks I can make this easily 💀

**Comment by patYczakus** [comment]
> I'm not familiar with what Better Discord plugins are allowed to access, but maybe you could try using MPRIS to do it? You can play/pause, prev, next, shuffle, set position offset (+/-) with it.
> 
> Also, does it need to be inside discord? I personally just use it on my taskbar (through mpris). It feels more convenient, but it's just a suggestion, I don't know about your case...
> 
> Good luck!

1. BetterDiscord in my computer isn't that *laggy* at all
2. I only want changing it in Discord, adding it to my taskbar will cause just a mess
But thanks to proposition anyway <3

**Comment by patYczakus** [comment]
LET'S GOO!!
I will experiment on Vencord as of now (I changed to that solution), and I'll try to give an update on how I'm doing sometimes

**Comment by Johannes7k75** [comment]
@patYczakus i already did something like this but with a websocket (i extended the api-server code).
If you wana take a look here the youtube-music code https://github.com/Johannes7k75/youtube-music/tree/feat/api-server
and the Vencord code https://github.com/Johannes7k75/Vencord/tree/feat/ytm-controls
if you have any questions hit me up.

**Comment by patYczakus** [comment]
> @patYczakus i already did something like this but with a websocket (i extended the api-server code).
> If you wana take a look here the youtube-music code https://github.com/Johannes7k75/youtube-music/tree/feat/api-server
> and the Vencord code https://github.com/Johannes7k75/Vencord/tree/feat/ytm-controls
> if you have any questions hit me up.

Oh wow, faster than me XD thanks!

**Comment by Johannes7k75** [comment]
I started it i think in April or so and was already finished.

**Comment by Johannes7k75** [comment]
> @Johannes7k75 the api server has been merged to master, you might want to update ur fork

Now  https://github.com/Johannes7k75/youtube-music/tree/feat/api-server is up to date with master

**Comment by Duplicake-fyi** [comment]
> [@patYczakus](https://github.com/patYczakus) i already did something like this but with a websocket (i extended the api-server code). If you wana take a look here the youtube-music code https://github.com/Johannes7k75/youtube-music/tree/feat/api-server and the Vencord code https://github.com/Johannes7k75/Vencord/tree/feat/ytm-controls if you have any questions hit me up.

Could you possibly create a pr in vencord?

**Comment by Johannes7k75** [comment]
> > [@patYczakus](https://github.com/patYczakus) i already did something like this but with a websocket (i extended the api-server code). If you wana take a look here the youtube-music code https://github.com/Johannes7k75/youtube-music/tree/feat/api-server and the Vencord code https://github.com/Johannes7k75/Vencord/tree/feat/ytm-controls if you have any questions hit me up.
> 
> Could you possibly create a pr in vencord?

I dont think that they would accept an PR bc its to specific and relies on stuff that is not even implemented in YT Music. But i did create an seperate repo with an custom plugin https://github.com/Johannes7k75/vc-ytmControls so if you know how to use user plugins with vc you could use it.

**Comment by ArjixWasTaken** [comment]
You can easily add it to Equicord instead!
They allow pretty much anything :^)

**Comment by Johannes7k75** [comment]
> You can easily add it to Equicord instead! They allow pretty much anything :^)

Thanks for the info i created an PR and also create an PR for an websocket for youtube-music
