### ISSUE TITLE
Can't cancel signin.

### ISSUE THREAD

**Issue by pranay-simejia** [th-ch/youtube-music#191]
![image](https://user-images.githubusercontent.com/70064696/111065347-2e0b5480-84df-11eb-9752-5490ed75fa53.png)
Mistakenly, I clicked signin button, had to close the app to cancel sign-in. 
Expected: A button to cancel sign-in.

**Comment by Bellisario** [comment]
@pranay-simejia, I'm with you!
Anyway, for now, if you don't need to log in the app, you can also enable the plugin to disable login button, to prevent mistakes...

**Comment by pranay-simejia** [comment]
That's helpful! Thanks.

**Comment by th-ch** [comment]
Hey @pranay-simejia, thanks for the feedback! https://github.com/th-ch/youtube-music/commit/8cce3f4503989e6d64961cbd0722b733cc0e2937 adds menus, allowing to zoom, reload and navigate in the app - this way you will always have a way of navigating back! It will ship in the next version.

**Comment by th-ch** [comment]
Closing this issue as it should be solved in the latest version, feel free to re-open in case of issue!
