### ISSUE TITLE
Changing Playlist Thumbnails

### ISSUE THREAD

**Issue by KhNediem** [th-ch/youtube-music#1916]
Description:

Currently, users of YouTube Music have limited control over the customization of their playlists, particularly regarding playlist thumbnails. The inability to change playlist thumbnails restricts users from personalizing and visually organizing their playlists according to their preferences or themes.

Problem Statement:

Lack of Personalization: Users are unable to personalize their playlists visually, as the thumbnails remain static and often do not accurately represent the content or mood of the playlist.

Visual Organization: Visual cues play a significant role in organizing playlists efficiently. Without the ability to change thumbnails, users may find it challenging to distinguish between playlists quickly.

Proposed Solution:

Introduce the functionality for users to change playlist thumbnails within the YouTube Music platform. This feature would empower users to personalize their playlists, making them more visually appealing and easier to navigate. Users could select from a range of options including predefined thumbnails, custom images, or even thumbnails generated from the playlist content itself.

Key Features of the Solution:

Thumbnail Selection: Allow users to choose from a variety of options for playlist thumbnails, including predefined images, custom images uploaded by the user, or dynamically generated thumbnails based on the playlist content.

Customization Options: Provide users with tools to crop, resize, and adjust selected images to fit the thumbnail format effectively.

Dynamic Thumbnails: Implement an option to generate thumbnails dynamically based on the content of the playlist, such as a collage of album covers or artist images.

Consistency Across Devices: Ensure that changes made to playlist thumbnails are reflected consistently across all devices and platforms where the playlist is accessible.

Benefits:

Enhanced User Experience: Allowing users to customize playlist thumbnails would enrich their experience on YouTube Music, fostering a sense of ownership and personalization.

Improved Organization: Visual cues provided by customized thumbnails would aid users in quickly identifying and navigating their playlists, leading to a more organized and enjoyable listening experience.

Increased Engagement: The ability to personalize playlist thumbnails may encourage users to spend more time curating and sharing playlists, thereby increasing user engagement on the platform.

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/0506f0cf-3a49-43c6-89d7-78a68e1b1e17)

We don't have access to `YouTube`'s backend, which means we can't change the thumbnail of the playlist. 

PS. Are you using ChatGPT?

**Comment by KhNediem** [comment]
> ![image](https://private-user-images.githubusercontent.com/16558115/318278624-0506f0cf-3a49-43c6-89d7-78a68e1b1e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTY5NjIsIm5iZiI6MTcxMTg5NjY2MiwicGF0aCI6Ii8xNjU1ODExNS8zMTgyNzg2MjQtMDUwNmYwY2YtM2E0OS00M2M2LTg5ZDctNzhhNjhlMWIxZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE0NTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MGFkMjY3NzEzY2Y5YWE3YzViNjNiMWE3MDZhZDg4ZDc2Nzk5MGRhYjQ0YjE3OTRiNjUyNzQ0MGZlNzNmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TLbMmBj1-p7CueYQDiLt5sBRLowiTydFbJ_ZgCeLs1U)
> 
> We don't have access to `YouTube`'s backend, which means we can't change the thumbnail of the playlist.
> 
> PS. Are you using ChatGPT for writing issues?

These are issues requested from a survey i created so i can create a persona for the app, for a university project.
