### ISSUE TITLE
[Feature Request]: README french translation

### ISSUE THREAD

**Issue by luluna02** [th-ch/youtube-music#1923]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to translate the README file to french, can I do it? 

### Proposed Solution

.

### Alternatives Considered

.

**Comment by JellyBrick** [comment]
create a PR like #1806
