### ISSUE TITLE
[Bug] No GUI/window appearing

### ISSUE THREAD

**Issue by IdmiDwebe** [th-ch/youtube-music#193]
I'm not sure exactly when it happened but no window is displayed anymore. 

Now, when I launch, the application shows in the taskbar and a standard window in the windows task switcher (the alt+tab one) with all the GUI as it should, but clicking on either of these doesn't bring up the window, although other windows do lose focus as they should. I can still control audio with the media keys and I can see what's playing through the task switcher or if I hover over it's icon on the taskbar.

I only have one Windows "desktop" active, and it doesnt seem related to the fact that I'm using dual monitors. Its worked fine on my system for months, and it wasn't caused by the latest update, since it was working at one point with this version.

It happened around the time that I installed the Vulkan SDK (latest version, haven't installed any Vulkan SDK before) on my system, but I'm not sure exactly of when it happened so it may be unrelated, I also updated and installed some Visual Studio components but apart from that I can't think of what the cause could be. Renaming the vulkan SDK folder then re-launching or using the portable version doesnt change anything.

I've tested on the latest version 1.11.0 (installer and portable)

**Comment by IdmiDwebe** [comment]
For unrelated reasons I did a fresh install of Windows and re-installed the Vulkan SDK and it's working now.

**Comment by IdmiDwebe** [comment]
Without logs or anything else to go on or proof that it wasn't something I did, I guess this issue is kind of useless, I'll just close it.

**Comment by IdmiDwebe** [comment]
This issue has occurred again and it persists after installing on 1.15.1 and 1.14.1

**Comment by Araxeus** [comment]
check out #542 

(might be a problem with config)

**Comment by IdmiDwebe** [comment]
Thanks! 

Yep, 'x' in 'window-position' in 'config.json' was set to around 4000 (I have a 1080p monitor). Setting it between -1920 and 1920 made it visible on again.

**Comment by Araxeus** [comment]
@th-ch could maybe add some check that x,y is inside the [primary display](https://www.electronjs.org/docs/latest/api/screen#screengetprimarydisplay) ? https://github.com/th-ch/youtube-music/blob/ec4c2e92af70b9e4cab180e26f65cf9f072773fb/index.js#L125-L128
