### ISSUE TITLE
[Bug]: App window is blank in Korea using blocklist mode when logged out or Music Premium expires

### ISSUE THREAD

**Issue by 95426pm0m** [th-ch/youtube-music#1942]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.5

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows server 2019 / 1809 17763.5576

### What CPU architecture are you using?

x64

### Reproduction steps

1. Open YTM with my "%appdata%\YouTube Music" profile.

### Expected Behavior

Beautiful UI

### Actual Behavior

Black screen (Downgrading back to 3.3.4 won't also work, at least update works)
![240406_100955_YouTube_Music-9jiI6CiBTq](https://github.com/th-ch/youtube-music/assets/165371424/81b33e33-6849-4ae6-9a67-4bb89cbc193b)

### Enabled plugins

removing everything except config.json also causing error, so uploaded [config.json](https://github.com/th-ch/youtube-music/files/14891891/config.json).

		"notifications": {
			"enabled": true
		},
		"video-toggle": {
			"mode": "custom"
		},
		"precise-volume": {
			"globalShortcuts": {}
		},
		"discord": {
			"listenAlong": true,
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "With blocklists",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},
		"bypass-age-restrictions": {
			"enabled": true
		},
		"lyrics-genius": {
			"enabled": true
		},
		"sponsorblock": {
			"enabled": true
		},
		"quality-changer": {
			"enabled": true
		},
		"music-together": {
			"enabled": false
		}

### Additional Information  
seems like AdBlocker issue, removing below solves the problem:

		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "With blocklists",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},

What happens when signed out or premium expired(?t=24):

https://github.com/th-ch/youtube-music/assets/165371424/619e13fa-2c97-44d9-9409-6f34509dc84d

**Comment by JellyBrick** [comment]
### Additional information

adblocker (blocklist) blocking access to https://www.youtube.com/premium.
