### ISSUE TITLE
Can we have screen cast (like youtube has i guess) feature to play music on other devices?[Feature Request]: 

### ISSUE THREAD

**Issue by spectrum705** [th-ch/youtube-music#1943]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

To  play music on other devices using our desktop app

### Proposed Solution

Suggesting a screen cast feature that's present on youtube. that helps play using your desktop on other devices

### Alternatives Considered

cant really think on any alternative solution

**Comment by ArjixWasTaken** [comment]
> I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for a feature request that matches the one I want to file, without success.

lies

**Comment by ArjixWasTaken** [comment]
https://github.com/th-ch/youtube-music/issues/289
https://github.com/th-ch/youtube-music/issues/113
https://github.com/th-ch/youtube-music/issues/1820

**Comment by ArjixWasTaken** [comment]
Is this really such a hard thing to do?
![image](https://github.com/th-ch/youtube-music/assets/53124886/50724d19-e54b-49e9-9897-f5fc6cd6825a)
