### ISSUE TITLE
[MacOS] move the Title Bar Buttons (close, minimize, maximize) slightly up.

### ISSUE THREAD

**Issue by Itai-Nelken** [th-ch/youtube-music#195]
<img width="131" alt="Screen Shot 2021-03-18 at 7 20 27 PM" src="https://user-images.githubusercontent.com/70802936/111669207-39cc8300-881f-11eb-82af-c6c94e04ad7f.png">
looks to close in my opinion.
also when loading the youtube music website, the buttons overlap the logo untill the website is fully loaded.

**Comment by th-ch** [comment]
Hey @Itai-Nelken, thanks for the feedback! https://github.com/th-ch/youtube-music/commit/c926db7f130c6a293f8c07af91dfa62902a353a3 increases the margin a bit! For the launch behavior, it's a known issue due to the way the style is injected and rendered, I will give it a closer look!

**Comment by Itai-Nelken** [comment]
<img width="167" alt="Screen Shot 2021-03-18 at 11 33 13 PM" src="https://user-images.githubusercontent.com/70802936/111700620-5332f680-8842-11eb-8237-b0cf6d921f67.png">
@th-ch looks better now, and I didn't notice the buttons overlapping. <br>
Thanks!

**Comment by th-ch** [comment]
Closing this issue as it should be solved in the latest version, feel free to re-open in case of issue!
