### ISSUE TITLE
[Bug]: Discord Rich Presence not working

### ISSUE THREAD

**Issue by KaanAlper** [th-ch/youtube-music#1951]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.4.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

don't remember...

### Reproduction steps

Checking rich presence option
![image](https://github.com/th-ch/youtube-music/assets/86665266/cb2d79c6-29fc-4332-8061-94fa81c36660)
Look for Discord
![image](https://github.com/th-ch/youtube-music/assets/86665266/30ffcfc5-82e0-4cb7-a593-0099e4d99d23)
you will not see anything

### Expected Behavior

Song information thing in discord profile?

### Actual Behavior

There is not any event

### Enabled plugins

![image](https://github.com/th-ch/youtube-music/assets/86665266/1161564a-2663-4568-9b86-c5414e17cb04)
Albume Color Theme
Skip disliked
Music Together (i enabled that after issue)
Navigation
Bypass age Redi..
Discord Rich Presence

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/9ea0b48f-3b92-4c0c-b742-1545bed3c602)

It works. 
checked at `2024-04-11 00:48:57 (KST)`

**Comment by Shazgul** [comment]
Also got no Rich Presence shown :(
