### ISSUE TITLE
A side panel for quickly going to playlists

### ISSUE THREAD

**Issue by b-init** [th-ch/youtube-music#198]
Some kind of side panel or quickly-accessible menu for accessing all the saved playlists (and perhaps the custom mixes by youtube too, below the saved playlists?) would be insanely better because whenever switching from any page to the playlist I regularly play currently requires me to click on the logo on the top left (to go to the homepage)  and then going to library and selecting the playlist. Which is a bit slow and tedious.

**Comment by Araxeus** [comment]
![22-03-2021 15 03 12](https://user-images.githubusercontent.com/78568641/111993918-d6dd3380-8b1f-11eb-91fb-40703af3b561.png)

This menu is always visible for me, how did you even get rid of it?

**Comment by Yeetus3141** [comment]
> ![22-03-2021 15 03 12](https://user-images.githubusercontent.com/78568641/111993918-d6dd3380-8b1f-11eb-91fb-40703af3b561.png)
> 
> This menu is always visible for me, how did you even get rid of it?

Hm, now I can't get rid of it either. But It didn't appear during my last session yesterday, whenever I was in a playlist or an artist's page or something like that. I guess that was a bug (or perhaps I'm insanely dumb and didn't notice it (a bit unlikely)). I'll try to notice if it happens again.

But either way, a way to access particular playlists directly would be awesome, maybe if we could right-click the library button, e get to open the playlists directly. Or whatever works...
