### ISSUE TITLE
The scrollbar appears beside the minimize, maximize and close buttons.

### ISSUE THREAD

**Issue by harsh251004** [th-ch/youtube-music#1982]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

Make sure in app menu is enabled.

### Expected Behavior

The  scroll bar should be below the buttons.
![Screenshot (289)](https://github.com/th-ch/youtube-music/assets/146340558/abc0f37d-7816-47fb-8fca-04267932e83d)

### Actual Behavior

![Screenshot (289)](https://github.com/th-ch/youtube-music/assets/146340558/e5b81ab3-0e00-4a98-bf16-95ae4d260f75)
As you can see in this photo the scroll bar is placed beside the buttons.

### Enabled plugins

1. ambient mode
2. in app menu
3. crossfade
4. taskbar media control
5. Discord Rich Presence

**Comment by luluna02** [comment]
Same issue as #1835

**Comment by Su-Yong** [comment]
duplicated https://github.com/th-ch/youtube-music/issues/1835
