### ISSUE TITLE
[Bug]: full screen black bar at top And Ad blocker doesn't work

### ISSUE THREAD

**Issue by TheMasamitsu** [th-ch/youtube-music#1986]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2 (build 22631.3447)

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2.9

### Reproduction steps

Run or 1. Run as administrator
Same result: When I do full screen there is always the thick black bar at the top that really annoys me when I watch music videos
and Ad blocker doesn't work 

### Expected Behavior

that the black bar at the top is no longer gone and I can see the entire music video
and no more Ad on my video 

### Actual Behavior

No matter which video I watch in full screen, a thick black bar is at the top and the image slides downwards

### Enabled plugins

Ad blocker 
and sponsor block

### Additional Information

![image](https://github.com/th-ch/youtube-music/assets/165817740/48b2978c-1937-4f14-8063-2421270e7f60)
![image](https://github.com/th-ch/youtube-music/assets/165817740/9db21971-ea5e-4930-a978-f494fcb9d7bb)
![image](https://github.com/th-ch/youtube-music/assets/165817740/ed40df0f-2143-4811-b9e1-74d99072ed03)

**Comment by ArjixWasTaken** [comment]
> Enabled plugins
Ad blocker
and sponsor block

that is clearly false information, video-toggle is visible in the screenshot
please make sure all details you provide are correct

**Comment by TheMasamitsu** [comment]
![image](https://github.com/th-ch/youtube-music/assets/165817740/1535a372-7b0b-487c-a5a8-999a1f67b865)
![image](https://github.com/th-ch/youtube-music/assets/165817740/796d0e40-e4d5-4d2e-8a44-af460224eff5)

**Comment by TheMasamitsu** [comment]
Yes

**Comment by crispyrice526** [comment]
I also have the same issue in windows 10.

**Comment by Trixarian** [comment]
Have you tried switching Ad blocker's Blocker option from In player to With blocklist?

**Comment by AndyK28** [comment]
Hey.... Is the thick black bar in full screen view fixed before I download the update?

**Comment by TheMasamitsu** [comment]
yes only full screen

**Comment by TheMasamitsu** [comment]
> Have you tried switching Ad blocker's Blocker option from In player to With blocklist?

nop nothing changed
