### ISSUE TITLE
[Bug]: Buffering or something like that 

### ISSUE THREAD

**Issue by MountainGuy1** [th-ch/youtube-music#1988]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.0.0

### Reproduction steps

No additional steps, just start the youtube music application and the starting of the song or randomly when the song is playing, the timeline skips the song parts either too much or a little bit kinda ruins the experience for me it started after the 3.0.0 update and it has still been stuck with me every new song which plays after the old one gets some part of it skipped it happens totally randomly the only fix which only works till 1 or 2 songs is that I have to go to my playlist and click on another song which is above or below the current one I am playing and then I switch to the song  I was listening to before switching! I thought the issue will be fixed as updates dropped by, but it still has not been fixed (am not mad or anything like that, I love the one who is working on this application love you brother/sister keep providing updates). But that's the thing!

### Expected Behavior

Normal playing with wifi on!!

### Actual Behavior

Skips my songs till a certain part with the buffering like symbol instead of the play/stop button and I use wifi and my wifi is not loaded at all it's free all time so no question that it is causing this thing.

### Enabled plugins

Ad blocker, Ambient mode, Bypass age restriction, Caption selector, Downloader (it is enabled but I don't use it), Exponential volume, In-App menu, Lyrics genius, Navigation, Picture in picture, Playback speed, Precise volume, Shortcuts, Skip silences (I don't think this is the one causing the problem causing the problems still occurs even when the artist/author is singing in his/her voice full on loud), Video quality changer.

### Additional Information

Umm, what else that happens is that even when I go back to the part which got skipped after the play/stop button kinda turn into the buffering like circle icon, it still skips forward the next second after I go back to the line which got skipped it's forced ig.

**Comment by ArjixWasTaken** [comment]
might be related to https://github.com/th-ch/youtube-music/issues/1488

**Comment by MountainGuy1** [comment]
> might be related to #1488

Saw the thread but I tried doing the stuff and still it skips not only silences it skips directly to 1 mins after or more. And what it does is that if I start from the top of my playlist (have about 780 songs) it skips directly to the bottom ones after the first one gets over.

**Comment by MountainGuy1** [comment]
Oops accidently closed the thread lol

**Comment by JellyBrick** [comment]
Probably fixed in `3.4.0`.
