### ISSUE TITLE
[Bug]: When building the app, the menu bar does not change to the custom menu bar, but stays the default "file edit view window help".

### ISSUE THREAD

**Issue by NasrrS** [th-ch/youtube-music#1999]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS 14.2.1

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. git clone https://github.com/th-ch/youtube-music
2. cd youtube-music
3. pnpm install --frozen-lockfile
4. pnpm dev

### Expected Behavior

When I use homebrew to install the app the app has a custom menubar for enabling the plugins, navigation and others. I expected this menubar to appear so I could add my own Plugin.

### Actual Behavior

The menu bar showed the 'default' options "file, edit, view, window, help". And I could not enable the Plugin I created.

### Enabled plugins

None

**Comment by frostybiscuit** [comment]
It normally takes a few seconds until the custom menu is injected. Did you wait a bit to see if it does?
Either that, or it fails to do so due to an error caused by your plugin, so make sure there are no errors in the console.

**Comment by NasrrS** [comment]
Yes, I've waited a couple minutes in case there would be a delay, but it does not seem to be showing up. There are errors in the console though, but I have no clue on how to fix them. Do you have an idea? 
![image](https://github.com/th-ch/youtube-music/assets/119016297/70f6fff4-fa73-4052-89d0-111808e98a7d)

**Comment by NasrrS** [comment]
Nevermind, it was a problem with my plugin.
