### ISSUE TITLE
[Feature Request]: Plugin to disable sensitivity warnings

### ISSUE THREAD

**Issue by didas72** [th-ch/youtube-music#2006]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Youtube has a sensitivity warning for when musics include topics such as self harm. These pause the music playback, which can cause distractions if doing other tasks.

### Proposed Solution

It would be useful to have a plugin that could automatically accept the warnings and play the song.

### Alternatives Considered

As not every user would be willing to listen to these songs (the original purpose of the warning), an alternative would be to have a plugin that would automatically skip songs with this warning.

### Additional Information

Ideally both of these features would be implemented but I understand that the automatic accepting of sensitivity warnings can be troublesome.

**Comment by ArjixWasTaken** [comment]
Have you tried the "bypass-age-restrictions" plugin?

I remember it working for that.

**Comment by didas72** [comment]
Will give it a try. Hadn't considered that.

**Comment by didas72** [comment]
Yes, the 'bypass-age-restricitons' plugin did it. Thank you for the help. I assumed it only skipped the generic age restriction warning/block.
