### ISSUE TITLE
[Bug]: Music information not shown in download error notification

### ISSUE THREAD

**Issue by stellaaaaaaaaaaaaa** [th-ch/youtube-music#2008]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

Download a song/playlist using the downloader plugin and have it fail.

### Expected Behavior

In the error popup, it should say the title of the song and it's artist. I know I've seen it do that before, but now that it's stopped, its become an annoyance when trying to download a playlist, when i don't what songs it didn't download. 

### Actual Behavior

![Screenshot 2024-04-25 183511](https://github.com/th-ch/youtube-music/assets/94269157/fe980198-6594-4b63-b0e4-67aa3b89055a)

### Enabled plugins

1. Ad blocker
2. Album color theme
3. Ambient mode
4. Compact sidebar
5. Discord rich presence
6. Downloader
7. Exponential volume
8. In-App menu
9. Lyrics genius
10. Navigation
11. Notifications
12. Picture-In-Picture
13. Shortcuts
14. Taskbar Media Control

**Comment by Su-Yong** [comment]
what is the song you tried to download?

**Comment by FelipeKobra** [comment]
I'm having the same problem downloading my playlists. The only way that I made it work was by:

1. Plugins > Downloader > Presets > Mark "mp3"
2. Plugins > Downloader > Mark "Skip Existing Files"
3. Instead of downloading the Playlist by clicking the 3 dots on the playlist page, you need to go to the playlist page, then to Plugins > Downloader > Click on "Download Playlist"

This solved for me
