### ISSUE TITLE
[Feature Request]: Replace playlist image

### ISSUE THREAD

**Issue by Verssgn** [th-ch/youtube-music#2012]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Allow user to locally change art / image of a playlist.
![msedge_T53nwMwVMg](https://github.com/th-ch/youtube-music/assets/103335637/9562c0cc-a1cb-4b5e-bd26-dcad5f810421)

### Proposed Solution

- Setting images locally, the image replaces the url.

Using some kind of observer or some way where if a specific URL is supposed to be loaded it loads the altered version of the playlist image

### Alternatives Considered

- Setting images URL, user would input a link to an image

Using some kind of observer or some way where if a specific URL is supposed to be loaded it loads the altered version of the playlist image

### Additional Information

I have a trash userscript version of this but it works: https://greasyfork.org/en/scripts/493560-playlist-cover-replacer/code

**Comment by ArjixWasTaken** [comment]
Instead of an observer I'd use css for this

**Comment by Verssgn** [comment]
Well the way I would do it is to only have it for custom playlist as a way to mimic what spotify has.

Since the thumbnail of the custom playlist is determined by the first four songs, the custom thumbnail set by the user could also have an association with the URL of the playlist. And every time the user drags songs around, it would check if the custom thumbnail is applied to make sure it doesn't get changed. I'm not sure if there can be a script that would recognize the first four songs, since that would be way more efficient. So it might have to check with every drag event? That's what I gathered with my extremely basic programming knowledge.
![dXWLkOVMlS](https://github.com/th-ch/youtube-music/assets/103335637/dc225c3f-7e31-4788-8830-d58cc15074b0)

**Comment by Verssgn** [comment]
Closing because YouTube added official support for playlist images.
