### ISSUE TITLE
[Bug]: Discord Rich Presence not connecting to Discord Client

### ISSUE THREAD

**Issue by abidbmt** [th-ch/youtube-music#2016]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

11 Pro

### What CPU architecture are you using?

x64

### Reproduction steps

Install YTM and enable Discord Rich Presence

### Expected Behavior

Plugin connects to discord client and shows rich presence when playing music

### Actual Behavior

Plugin does not connect to client (no check mark next to "Connected") and does not show rich presence

### Enabled plugins

1. Discord Rich Presence 2. Lyrics Genious

### Additional Information

I suspect its because I use a modded Discord Client, or because of my client being the PTB version of discord

**Comment by zegmin** [comment]
Same thing is happening to me and I'm not using a modded Discord client, I suspect its either this latest update for Discord or it broke in this YT Music update.

**Comment by colineberly** [comment]
Mine says connected, but nothing is showing in Discord. Fresh install of both apps.
