### ISSUE TITLE
[Bug]: Liked Songs/Videos Removed

### ISSUE THREAD

**Issue by Joey451-OG** [th-ch/youtube-music#2021]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 40

### What CPU architecture are you using?

x64

### Reproduction steps

1. Like song
2. Wait
3. Video not liked anymore

### Expected Behavior

Songs/videos remained liked

### Actual Behavior

Songs seem to "unlike" themselves

### Enabled plugins

1. Ad blocker (blocklist)
2. Album color theme
3. Discord Rich Presence
4. Navigation

### Additional Information

I'm not sure if this is a base youtube problem. I made this to see if other users are experiencing this. I swear I've re-liked this song at least three times.
![image](https://github.com/th-ch/youtube-music/assets/60891047/b98d6d61-dbf8-4480-8031-a6e2b305dfc6)

**Comment by luluna02** [comment]
I tried reproducing this but it works just fine for me( macos Sonoma 14.3.1 )

<img width="1232" alt="Screenshot 2024-05-01 at 11 54 40 AM" src="https://github.com/th-ch/youtube-music/assets/133816965/847b29ab-b268-4e1c-9954-777b438650de">

**Comment by JellyBrick** [comment]
YT issue.
