### ISSUE TITLE
[Bug]: Google auth

### ISSUE THREAD

**Issue by ArcKos00** [th-ch/youtube-music#2030]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.0.0.

### Checklists

- [x] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Reproduction steps

1. open app 
2. log in

### Expected Behavior

login with google

### Actual Behavior

page code as text content

### Enabled plugins

nope

### Additional Information

![image](https://github.com/th-ch/youtube-music/assets/105163313/b0649094-8c02-4c54-884d-7c27421b89a0)

**Comment by JellyBrick** [comment]
2.0.0 is not supported. Please use latest version.
