### ISSUE TITLE
[Feature Request]: Increase padding between the top bar and window controls (macOS)

### ISSUE THREAD

**Issue by codenyte** [th-ch/youtube-music#2035]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

For some reason, on macOS the distance between the top bar which contains the hamburger menu, YouTube Music logo, serach bar and three-dot menu and the window controls (close, minimize, fullscreen) is very small. I think this looks pretty bad: 
![](https://github.com/th-ch/youtube-music/assets/39193783/29635d6c-36fe-4b73-b3f0-de7c4b2feb9d)

### Proposed Solution

Add some padding above the top bar, just like can be seen on the screenshot of the Windows version, which has some more space between the top bar and the menu bar:
![](https://github.com/th-ch/youtube-music/assets/39193783/cccde446-15b1-4f2c-9db8-f1b4cafeadf7)

### Alternatives Considered

Add title bar, but I think just adding some padding for the top app bar would be easier and look better

**Comment by luluna02** [comment]
@codenyte Don't you think the title bar (menu) is unecessary for macOS since it natively already shows up ? ( like the below screenshot )

<img width="1192" alt="Screenshot 2024-05-11 at 3 53 25 PM" src="https://github.com/th-ch/youtube-music/assets/133816965/199e8938-5eba-4363-9747-cf7ac78d058f">

**Comment by Su-Yong** [comment]
<img width="218" alt="image" src="https://github.com/th-ch/youtube-music/assets/13764936/978a280c-c54a-4512-98d9-dbb342690a00">
add more gap

**Comment by yusben** [comment]
Hello, could anyone clarify how to enable it? I have the latest version 3.7.1-arm64 on my Macbook Pro M1 with Sonoma 14.7.1 and there is no padding. 
<img width="653" alt="Screenshot 2024-12-29 at 13 14 49" src="https://github.com/user-attachments/assets/f3c9c221-1bf0-4643-a10d-a3a8c67219d3" />
