### ISSUE TITLE
[Bug]: Crossfade mutes song after 3 songs

### ISSUE THREAD

**Issue by BluesBroBo** [th-ch/youtube-music#2037]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Activate the Crossfade plugin
2. Skip or wait through 3 songs. The first swap should have no crossfade at all, the second should have the correct crossfade and the 3rd will fade out but the next song won't fade in. Skipping another song, pausing or changing the song or playlist won't reactivate the sound
3. if you toggle the speaker ih the menu bar twice, you can hear the music again, but the problem of the fading out without the next fading in will reoccur with every skip until the app is restarted

### Expected Behavior

Every song fades out and fades in correctly

### Actual Behavior

Songs don't fade in anymore after the third song

### Enabled plugins

Ad Blocker, Crossfade [Beta], In-App-Menu, Lumia Stream [Beta], Navigation, Scrobbler, SponsorBlock, Taskbar Media Control, Video Quality Changer

**Comment by Su-Yong** [comment]
duplicated https://github.com/th-ch/youtube-music/issues/1971
