### ISSUE TITLE
[Bug]: Playback speed slider is not visible

### ISSUE THREAD

**Issue by MountainGuy1** [th-ch/youtube-music#2045]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.4

### Reproduction steps

---

### Expected Behavior

The playback speed slider to be present somewhere atleast in those 3 dots

### Actual Behavior

What happened is - I recently added a song needed it to you know play fast as to enjoy the rush of it, but the playback slider is not there anywhere searched all tried restarting the app my laptop disabling the plugin itself. It just disappeared in this version of the app!!

### Enabled plugins

Ad blocker, Ambient mode, Bypass age restriction, Caption selector, Downloader (it is enabled but I don't use it), Exponential volume, In-App menu, Lyrics genius, Navigation, Picture in picture, Playback speed, Precise volume, Shortcuts, Skip silences (I don't think this is the one causing the problem causing the problems still occurs even when the artist/author is singing in his/her voice full on loud), Video quality changer.

### Additional Information

![YouTube Music 10-05-2024 18_59_19](https://github.com/th-ch/youtube-music/assets/167510562/9b1c05de-f073-43a5-9277-a66ebd1006c5)
![YouTube Music 10-05-2024 18_59_37](https://github.com/th-ch/youtube-music/assets/167510562/3211e2bd-a0af-454c-b17b-c2a3502747e4)

**Comment by SnowboundCabin** [comment]
having the same issue! occurs with no other plugins enabled.

**Comment by comkys** [comment]
hi!! I just created an acc for this.. yea me too..?? I'm on windows 10,64x and on 3.3.10

**Comment by MountainGuy1** [comment]
> hi!! I just created an acc for this.. yea me too..?? I'm on windows 10,64x and on 3.3.10 and i use the installer version.

sad brother but we can't do anything about it. It all depends on jelly brick brother

**Comment by LewisIsWorking** [comment]
I have the same issue, windows 11.

**Comment by skyisthela** [comment]
same issue here, in fact having the same issue for ages, previously on windows 10 which i reinstalled multiple times recently

**Comment by jirafey** [comment]
same issue, tried 3.0.1 3.6.1 3.3.0 issue persists. seems like this plugin doesn't even require youtube-music restart. Is this plugin ale to do changes in the app?

**Comment by SnowboundCabin** [comment]
bug appears to be present in the current version (3.3.12). It doesn't "all depend on jelly brick," though - this is open source, someone who understands what's going on here could contribute. I looked through the source myself, but I'm not familiar with web stuff enough to diagnose it at a glance. I have a guess (structure of the page has changed, so it's failing to match a pattern) but it's wildly uneducated.

**Comment by r1nh** [comment]
Same issue, tried 3.3.6 and 3.3.12. Windows 10.
