### ISSUE TITLE
[Bug]: App starts to lag when I select a playlist with alot of songs

### ISSUE THREAD

**Issue by Aahjai** [th-ch/youtube-music#2050]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Window 11 Home

### What CPU architecture are you using?

x64

### Reproduction steps

Select a playlist with alot of songs.

### Expected Behavior

App stays fluid and no lag.

### Actual Behavior

App immediately begins lagging and song selecting/scrolling has a huge delay until choosing a playlist with significantly less songs.

### Enabled plugins

Exponential Volume
In-App Menu

**Comment by ArjixWasTaken** [comment]
Can you reproduce this issue on the website https://music.youtube.com using a chrome based browser?

(e.g. chrome, Vivaldi, opera, Microsoft edge)

**Comment by Aahjai** [comment]
I'm using the app....also the lag isn't present on the browser.

**Comment by ArjixWasTaken** [comment]
> I'm using the app....

I think that's obvious.

> also the lag isn't present on the browser.

Great, that's what I wanted to confirm

**Comment by Aahjai** [comment]
What should I do now...?

**Comment by NoodleSoup** [comment]
Same here, when I select the "My Supermix" playlist the playlist overview page becomes super laggy. Noticed 2 of my CPU cores spike to 100% usage when scrolling. GPU seems to do nothing at 0% usage.

Does not happen on Chrome, music.youtube.com website.

**Comment by heIgee** [comment]
Also have this issue after updating from 3.3.6 (where adblocker stopped working) to 3.3.9. Looks like hardware acceleration is being disabled regardless of the corresponding setting.

**Comment by Gicioks** [comment]
I noticed that turning off In-App Menu fixes the problem. 3080 Ti; 5950X; 32GB RAM; should not have any issues

**Comment by Smoltallk** [comment]
> I noticed that turning off In-App Menu fixes the problem. 3080 Ti; R9 5950X; 32GB RAM; should not have any issues

Yep this fixed it for me too

**Comment by NoodleSoup** [comment]
> I noticed that turning off In-App Menu fixes the problem. 3080 Ti; R9 5950X; 32GB RAM; should not have any issues

Seems to have fixed it here as well.

**Comment by michtarxd** [comment]
Happens to me with In-App Menu enabled, disabling it makes it smooth again

**Comment by JellyBrick** [comment]
Now it tracked on #2266

See https://github.com/th-ch/youtube-music/issues/2266#issuecomment-2335198346
