### ISSUE TITLE
[Feature Request]: don't make ~/.config/YouTube\ Music/config.json world writable

### ISSUE THREAD

**Issue by caderobinson** [th-ch/youtube-music#2064]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

 ~/.config/YouTube\ Music/config.json created world writable
Setting perms to anything other than 666 and launching youtube-music resets perms to 666

### Proposed Solution

Don't set perms on files to 666. 
644 would be better
600 would be optimal

### Alternatives Considered

none

**Comment by JellyBrick** [comment]
config is managed by `electron-store`.
We can't configure it.
