### ISSUE TITLE
[Bug]: A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by farsdewibs0n** [th-ch/youtube-music#2065]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.1.0

### Reproduction steps

Program crashes on launch

### Expected Behavior

Program should run normally

### Actual Behavior

Error shows up and program runs on background

### Enabled plugins

Default settings (at least it should be because I deleted the folder on AppData)

### Additional Information

![image](https://github.com/th-ch/youtube-music/assets/13050356/1a08c846-9ebc-4417-ae15-d54d42d70c59)

**Comment by JellyBrick** [comment]
Check your config file. (config.json)
