### ISSUE TITLE
[Bug]: Cache is stored in the `.config` folder

### ISSUE THREAD

**Issue by MartinX3** [th-ch/youtube-music#2067]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What CPU architecture are you using?

x64

### Reproduction steps

Use the app.

### Expected Behavior

Storing the cache at `~/.cache/YouTube Music/`

### Actual Behavior

Storing the cache at `~/.config/YouTube Music/Cache/`.

### Enabled plugins

Nothing

**Comment by JellyBrick** [comment]
It is managed by electron (chromium).
We can't configure it.

**Comment by MartinX3** [comment]
Right and here is the upstream issue https://github.com/electron/electron/issues/8124.
Thank you!
