### ISSUE TITLE
[Bug] Discord Plugin Failing

### ISSUE THREAD

**Issue by Araxeus** [th-ch/youtube-music#208]
Keeps throwing this error:
```javascript
Error: child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]
    at RPCClient._onRpcMessage (C:\git\youtube-music\node_modules\discord-rpc\src\client.js:185:19)
    at IPCTransport.emit (events.js:315:20)
    at C:\git\youtube-music\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\git\youtube-music\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\git\youtube-music\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 4000,
  data: {
    code: 4000,
    message: 'child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]]'
  }
}
```
(no custom status set on discord, other applications usually work)

**Comment by Araxeus** [comment]
Can fix the error throwing on start by adding to the start of plugins/discord/back.js
```javascript
.
.
.

registerCallback((songInfo) => {
	if(!songInfo.title || !songInfo.artist)
		return
.
.
.
```
But obviously discord still doesn't get the rich presence

**Comment by semvis123** [comment]
My guess is that the RPC isn't ready/connected when the activity is set, but 
```js
rpc.on("ready",()=>{})
```
should prevent this. So I don't know why this error occurs. It looks like this error only occurs on the first song. Maybe we could retry (with a small delay) after a error occurs, but that doesn't fully solve the problem.

**Comment by Araxeus** [comment]
Like I said, the error message can be fixed by waiting for the first song to start before setting activity.
but even then, discord doesn't show anything (and there is no error thrown..)

**Comment by semvis123** [comment]
> To clarify - the discord plugin never worked for me 😋 

Ah okay, what platform are you using, did you install discord using a package manager?

**Comment by Araxeus** [comment]
Windows 10, Discord installed through discord.com
(all other games/applications work)

**Comment by semvis123** [comment]
Ah you are misunderstanding promises, you need to pass a function to `catch` and `then`, for ex. `.catch(()=>console.log('error'))`
This will print error if the error occurs, you could also do `.catch(console.error)` to print  the error itself.

But if you do it like this:
`.catch(console.error('error'))`
Js will simply execute immediately `console.error('error')` even if no error is thrown.

**Comment by Araxeus** [comment]
Thank you for explaining, and sorry for the confusion - both promises are ok
But still discord doesn't display anything - haven't selected  a custom status / game
