### ISSUE TITLE
[Bug]: Shows Constantly Cannot load YT Music ... Internet disconnected

### ISSUE THREAD

**Issue by aryas10** [th-ch/youtube-music#2091]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.5.0

### Reproduction steps

1. Install the setup , open the loaded icon for opening YT music Error is displayed.

### Expected Behavior

To open the application and simply having my user interface , to play music.

### Actual Behavior

app ui shows warning as attached with the image 
![Screenshot 2024-05-26 122448](https://github.com/th-ch/youtube-music/assets/98511951/647853ad-152a-4645-a9e4-49055e91d56d)

### Enabled plugins

1. ad blocker 
2. downloader
3. exponential volume
4. no sign-in
![Screenshot 2024-05-26 123307](https://github.com/th-ch/youtube-music/assets/98511951/f9af3027-9d07-4235-8cda-9f29b0977f9d)

**Comment by aryas10** [comment]
please resolve the above issue .

**Comment by JellyBrick** [comment]
Check your proxy setting.

**Comment by aryas10** [comment]
> Did you check your proxy setting?

Yes , the issue has been resolved now..
Proxy settings were reconfigured on the same date and resolved as well. 

I have been late to update it on issue .
 
Thanks 🙏🏻
