### ISSUE TITLE
[Feature Request]:  Change Discord status from Playing Youtube Music to Listening to Youtube Music (changing status value)

### ISSUE THREAD

**Issue by Siiyar** [th-ch/youtube-music#2095]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

From this: (Playing)
![image](https://github.com/th-ch/youtube-music/assets/105711506/5ee44de3-b044-4253-be17-12c7ed65168a)
 
To something like this: (Listening to ...)
![image](https://github.com/th-ch/youtube-music/assets/105711506/ba5f3e1e-63b4-4886-883e-94dd2b8c150c)

### Proposed Solution

Let Users select what status they want

### Alternatives Considered

Alternative: Set the default status setting to "Listening to"

**Comment by ArjixWasTaken** [comment]
https://github.com/th-ch/youtube-music/pull/2052#issuecomment-2116593460
@dvd-22 wrote
> I tested this, and sadly it doesn't work. It looks like activites set through IPC (not oauth activity.write scope) cannot set anything besides playing. Listening and Watching are overwritten by Discord to playing and the rest are blocked. So unless Discord changes something in their API, it won't be possible anytime soon.

**Comment by Siiyar** [comment]
oh okay, my bad
