### ISSUE TITLE
Download button not working.

### ISSUE THREAD

**Issue by DahrbUwU** [th-ch/youtube-music#210]
when you right click any music or playlist and then the download button, appears this error box.

![image](https://user-images.githubusercontent.com/81421147/112630002-c7a60080-8e13-11eb-8ef4-6f4b75280837.png)

![image](https://user-images.githubusercontent.com/81421147/112630032-d42a5900-8e13-11eb-8d87-510e3b1df452.png)

**Comment by Araxeus** [comment]
- You need to be playing the track you wanna download / a track from the playlist you wanna download

- When you are playing from a playlist and want to download, you need to have the overlay (current playing) active, or it will change the URL

I've been having problems with this too

**Comment by th-ch** [comment]
Hey @DahrbUwU, thanks for the feedback! As @Araxeus mentioned, you need to be playing the song - now that https://github.com/th-ch/youtube-music/pull/213 has been merged, in the next version, you should be able to minimize the song (see https://github.com/th-ch/youtube-music/issues/219 about the same issue)!
