### ISSUE TITLE
[Bug]: The entire app is black

### ISSUE THREAD

**Issue by SleepDaemon** [th-ch/youtube-music#2103]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.7

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.6

### Reproduction steps

Just opening the app fresh

### Expected Behavior

Should show the YTM web UI

### Actual Behavior

![image](https://github.com/th-ch/youtube-music/assets/88533953/b8e0a6e0-dfd5-4291-97e3-8dabc3715c4b)

### Enabled plugins

I can't check my list enabled plugins cause the entire app is black moment I launch it

**Comment by soarpasser** [comment]
This issue is not fully fixed and is still reproducible on my end even after the update with the following config.

`{
	"window-size": {
		"width": 951,
		"height": 628
	},
	"url": "https://music.youtube.com/watch?v=KmXxpG0fG7o&list=MLPAa_po_CLi274KPtqL1KxIFY3Jhd2s&index=0",
	"options": {
		"tray": true,
		"appVisible": false,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": true,
		"resumeOnStart": true,
		"proxy": "",
		"overrideUserAgent": true,
		"removeUpgradeButton": true,
		"startingPage": "Playlists",
		"likeButtons": "hide",
		"themes": []
	},
	"plugins": {
		"navigation": {
			"enabled": false
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "With blocklists",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},
		"shortcuts": {
			"enabled": true,
			"overrideMediaKeys": false,
			"global": {
				"previous": "Ctrl+Left",
				"playPause": "Ctrl+Space",
				"next": "Ctrl+Right"
			}
		},
		"downloader": {
			"enabled": true,
			"selectedPreset": "Custom",
			"customPresetSetting": {
				"extension": "flac",
				"ffmpegArgs": []
			},
			"skipExisting": false
		},
		"last-fm": {
			"enabled": false,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
			"api_key": "04d76faaac8726e60988e14c105d421a",
			"secret": "a5d2a36fdf64819290f6982481eaffa2"
		},
		"discord": {
			"enabled": true,
			"autoReconnect": true,
			"activityTimeoutEnabled": true,
			"activityTimeoutTime": 300000,
			"playOnYouTubeMusic": true,
			"hideGitHubButton": true,
			"hideDurationLeft": true,
			"activityTimoutEnabled": true,
			"activityTimoutTime": 60000
		},
		"notifications": {
			"enabled": true,
			"unpauseNotification": true,
			"urgency": "normal",
			"interactive": true,
			"toastStyle": 1,
			"refreshOnPlayPause": false,
			"trayControls": true,
			"hideButtonText": false
		},
		"precise-volume": {
			"enabled": true,
			"steps": "1",
			"arrowsShortcut": true,
			"globalShortcuts": {
				"volumeUp": "Ctrl+Up",
				"volumeDown": "Ctrl+Down"
			},
			"savedVolume": 61
		},
		"sponsorblock": {
			"enabled": false,
			"apiURL": "https://sponsor.ajay.app",
			"categories": [
				"sponsor",
				"intro",
				"outro",
				"interaction",
				"selfpromo",
				"music_offtopic"
			]
		},
		"video-toggle": {
			"enabled": true,
			"hideVideo": true,
			"mode": "custom",
			"forceHide": false,
			"align": "middle"
		},
		"bypass-age-restrictions": {
			"enabled": true
		},
		"disable-autoplay": {
			"enabled": true,
			"applyOnce": true
		},
		"exponential-volume": {
			"enabled": true
		},
		"in-app-menu": {
			"enabled": true
		},
		"lyrics-genius": {
			"enabled": true,
			"romanizedLyrics": true
		},
		"picture-in-picture": {
			"enabled": false,
			"isInPiP": false
		},
		"playback-speed": {
			"enabled": true
		},
		"quality-changer": {
			"enabled": true
		},
		"skip-silences": {
			"enabled": false
		},
		"taskbar-mediacontrol": {
			"enabled": true
		},
		"tuna-obs": {
			"enabled": false
		},
		"audio-compressor": {
			"enabled": true
		},
		"visualizer": {
			"enabled": false,
			"type": "wave",
			"butterchurn": {
				"preset": "martin [shadow harlequins shape code] - fata morgana",
				"renderingFrequencyInMs": 500,
				"blendTimeInSeconds": 2.7
			},
			"vudio": {
				"effect": "lighting",
				"accuracy": 128,
				"lighting": {
					"maxHeight": 160,
					"maxSize": 12,
					"lineWidth": 1,
					"color": "#49f3f7",
					"shadowBlur": 2,
					"shadowColor": "rgba(244,244,244,.5)",
					"fadeSide": true,
					"prettify": false,
					"horizontalAlign": "center",
					"verticalAlign": "middle",
					"dottify": true
				}
			},
			"wave": {
				"animations": [
					{
						"type": "Cubes",
						"config": {
							"bottom": true,
							"count": 30,
							"cubeHeight": 5,
							"fillColor": {
								"gradient": [
									"#FAD961",
									"#F76B1C"
								]
							},
							"lineColor": "rgba(0,0,0,0)",
							"radius": 20
						}
					},
					{
						"type": "Cubes",
						"config": {
							"top": true,
							"count": 12,
							"cubeHeight": 5,
							"fillColor": {
								"gradient": [
									"#FAD961",
									"#F76B1C"
								]
							},
							"lineColor": "rgba(0,0,0,0)",
							"radius": 10
						}
					},
					{
						"type": "Circles",
						"config": {
							"lineColor": {
								"gradient": [
									"#FAD961",
									"#FAD961",
									"#F76B1C"
								],
								"rotate": 90
							},
							"lineWidth": 4,
							"diameter": 20,
							"count": 10,
							"frequencyBand": "base"
						}
					}
				]
			}
		},
		"crossfade": {
			"enabled": false,
			"fadeInDuration": 1500,
			"fadeOutDuration": 5000,
			"secondsBeforeEnd": 10,
			"fadeScaling": "linear"
		},
		"captions-selector": {
			"enabled": true
		},
		"album-color-theme": {
			"enabled": false
		},
		"ambient-mode": {
			"enabled": false
		},
		"music-together": {
			"enabled": true
		},
		"album-actions": {
			"enabled": true
		},
		"scrobbler": {
			"enabled": true
		}
	},
	"__internal__": {
		"migrations": {
			"version": "3.3.8"
		}
	},
	"window-position": {
		"x": 324,
		"y": 68
	},
	"window-maximized": false
}`

Setting adblocker mode to "in player" solves this issue.

**Comment by DankestFke** [comment]
I had the same problem with 3.3.9, how do I reset my settings or put my adblocker to "in-player" only?

**Comment by soarpasser** [comment]
> I had the same problem with 3.3.9, how do I reset my settings or put my adblocker to "in-player" only?

%appdata%\YouTube Music and edit your config.json.

**Comment by SleepDaemon** [comment]
> I had the same problem with 3.3.9, how do I reset my settings or put my adblocker to "in-player" only?

I also have it on 3.3.9, still showing black screen

**Comment by JellyBrick** [comment]
@soarpasser @SleepDaemon @DankestFke Are you experiencing the same issue after deleting `%appdata%\YouTube Music\adblock_cache`?

**Comment by soarpasser** [comment]
@JellyBrick issue still persists.

**Comment by SleepDaemon** [comment]
> @soarpasser @SleepDaemon @DankestFke Are you experiencing the same issue after deleting `%appdata%\YouTube Music\adblock_cache`?

I changed it to in player in config which fixed it but I'll try this as well

**Comment by SleepDaemon** [comment]
> > @soarpasser @SleepDaemon @DankestFke Are you experiencing the same issue after deleting `%appdata%\YouTube Music\adblock_cache`?
> 
> I changed it to in player in config which fixed it but I'll try this as well 

Ye still same issue after doing this

**Comment by Rairof** [comment]
Issue still persists even after I clean installed 3.3.9

![image](https://github.com/th-ch/youtube-music/assets/107706560/3e686a75-0774-49b9-9731-ffc3ff1acaef)

**Comment by JellyBrick** [comment]
@Rairof Can you provide a screenshot of DevTools? (console)

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/2103#issuecomment-2143445842
How can I get devtools console to open again? What was the shortcut?

**Comment by JellyBrick** [comment]
@Rairof Thanks!
Can you provide a screenshot of the starting point of console texts? (DevTools console)

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/2103#issuecomment-2143528087
Will do when I am home 👍

**Comment by soarpasser** [comment]
@JellyBrick 

> Thanks! Can you provide a screenshot of the starting point of console texts? (DevTools console)

![image](https://github.com/th-ch/youtube-music/assets/74951691/bfba8014-e763-475b-86a8-e3e7cbacea8d)
![image](https://github.com/th-ch/youtube-music/assets/74951691/693d04bb-5f8d-421b-8904-c5b9491bd84b)

**Comment by ZOTX0** [comment]
i disabled ad blocker set it to false and its working fine and its smoother now

**Comment by Rairof** [comment]
can confirm it works now in 3.3.10
![image](https://github.com/th-ch/youtube-music/assets/107706560/81d6d6b9-aed0-4675-8dbf-0ad90723414e)

**Comment by MountainGuy1** [comment]
> @Rairof Thanks! Can you provide a screenshot of the starting point of console texts? (DevTools console)

Brick brother I fixed my issue (˚ ˃̣̣̥⌓˂̣̣̥)づ♡(˚ ˃̣̣̥⌓˂̣̣̥)づ♡(˚ ˃̣̣̥⌓˂̣̣̥)づ♡(˚ ˃̣̣̥⌓˂̣̣̥)づ♡(˚ ˃̣̣̥⌓˂̣̣̥)づ♡

**Comment by SleepDaemon** [comment]
The issue is back in v3.3.11 when it got fixed in v3.3.10 .-.

**Comment by SleepDaemon** [comment]
> The issue is back in v3.3.11 when it got fixed in v3.3.10 .-.

@JellyBrick

**Comment by JellyBrick** [comment]
@SleepDaemon Fixed at 3.3.12
