### ISSUE TITLE
[Bug]: Navigation bar has default configuration

### ISSUE THREAD

**Issue by TetyLike3** [th-ch/youtube-music#2105]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.7 - 3.3.8

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.6

### Reproduction steps

1. Open the navigation bar

### Expected Behavior

Plugins + Options dropdowns exist
![image](https://github.com/th-ch/youtube-music/assets/95130493/a803f4ae-c26b-4372-a2b5-e5d9c3a7287c)

### Actual Behavior

Seems to be set to default configuration, as the layout is completely different, along with a lot of missing items
![image](https://github.com/th-ch/youtube-music/assets/95130493/be51c1bb-a651-453d-8c3e-3015386dc1d7)

### Enabled plugins

1. Ad Blocker (blocklists)
2. Ambient Mode
3. Blur Navigation Bar
4. Compact Sidebar
5. Discord Rich Presence
6. In-App Menu
7. Precise Volume
8. Video Toggle

### Additional Information

Very likely to be an issue with my config since this wasn't mentioned before

**Comment by Xydem4** [comment]
Same thing for me, so it's not just you. I can't tell what settings are carried over, though, because there's no longer a tray icon but the upgrade button is still removed. I didn't experiment with much to test anything. I just went back to 3.3.6 for now.

**Comment by JellyBrick** [comment]
What is the system locale of your PC?

**Comment by Xydem4** [comment]
> What is the system locale of your PC?

me? English (United States)
figured didn't matter who you were asking, info from either of us could help since we're both having the same issue. Also on Windows 10 Pro.

**Comment by peternormann** [comment]
I experience the same issues on the linux version (currently 3.3.9).

No menus, can't set preferences, use systray, etc.

**Comment by TetyLike3** [comment]
> Same thing for me, so it's not just you. I can't tell what settings are carried over, though, because there's no longer a tray icon but the upgrade button is still removed. I didn't experiment with much to test anything. I just went back to 3.3.6 for now.

Yeah, I can definitely confirm none of the actual configs are reset, it's just that I can't access them from the app anymore. For example, DRP and Video Toggle still works.

**Comment by TetyLike3** [comment]
> What is the system locale of your PC?

Mine is English (United Kingdom)

**Comment by peternormann** [comment]
Yeah, all settings are still there. Downgrading to 3.3.6 got everything working again

**Comment by Myphz** [comment]
Same bug on Archlinux

**Comment by Skeletonek** [comment]
Same on Fedora 40 KDE, default menu and not working sys tray. Reverted to 3.3.6 and everything is working correctly there

**Comment by TetyLike3** [comment]
> Can you provide a screenshot of DevTools? (console)

![image](https://github.com/th-ch/youtube-music/assets/95130493/a62430a5-7655-4c91-bbab-c75b754f178d)

**Comment by Xydem4** [comment]
> Can you provide a screenshot of DevTools? (console)
> 
> @Skeletonek @Myphz @peternormann @TetyLike3 @Xydem4

![image](https://github.com/th-ch/youtube-music/assets/171392455/5e3e1f46-7b56-482f-b918-7b7677456380)

**Comment by Skeletonek** [comment]
> Can you provide a screenshot of DevTools? (console)
> 
> @Skeletonek @Myphz @peternormann @TetyLike3 @Xydem4

![obraz](https://github.com/th-ch/youtube-music/assets/41450243/6a576dbf-980c-4dfb-b7ac-988e89318684)

Translated [YTMusic] logs are about loading a plugin

**Comment by Myphz** [comment]
> Can you provide a screenshot of DevTools? (console)
> 
> @Skeletonek @Myphz @peternormann @TetyLike3 @Xydem4

![image](https://github.com/th-ch/youtube-music/assets/71951166/eb9ff911-233d-4fd4-8df1-b2ddca7f365e)

**Comment by Skeletonek** [comment]
Everything works correctly now on 3.3.10, but only after clean reinstall, i.e. remove all YouTube Music data inside ~/.config/YouTube Music (or %appdata%/YouTube Music if you're a Windows user).
