### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ihsan101** [th-ch/youtube-music#2107]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.9

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 V. 23H2, Build 22631.3593

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.6

### Reproduction steps

1. Download the Youtube-music-web-setup.exe
2. Run the setup.

### Expected Behavior

For the app to be downloaded

### Actual Behavior

It says "Downloading package .7yz, and once the progress bar fills up it immediately closes the installer without performing the installation. 

### Enabled plugins

None

**Comment by JellyBrick** [comment]
It's not a bug.

**Comment by Ihsan101** [comment]
But the youtube music app isnt being downloaded? If its not a bug how should I download the app?

**Comment by JellyBrick** [comment]
### If you want to install this application

- Execute YouTube-Music-Web-Setup-v3.3.9.exe`

### If you want to install this application without network connection

https://github.com/th-ch/youtube-music#how-to-install-without-a-network-connection-in-windows
