### ISSUE TITLE
Allow configuring notification urgency

### ISSUE THREAD

**Issue by SapuSeven** [th-ch/youtube-music#211]
On my system, I'd prefer the notifications plugin to send notifications with low urgency.

I took a look at [the electron docs](https://www.electronjs.org/docs/api/notification#new-notificationoptions) and noticed you could use the `urgency` parameter to specify this.

My suggestion is to add a configuration parameter to set the urgency as desired.

I'd also be happy to implement this myself and open a PR if this feature gets approved.

**Comment by th-ch** [comment]
Hey @SapuSeven, thanks for the feedback! Adding a plugin option is definitely a great idea! (with the idea of keeping the current behavior as default to keep backwards-compatibility)
Bonus: it's now even possible to add a menu item for the plugin to let users configure it without advanced options! (see `menu.js` file in downloader plugin for an example)

Contributions are welcome, feel free to open a PR!
