### ISSUE TITLE
[Bug]: Radios don't update when reaching near the end

### ISSUE THREAD

**Issue by Reycko** [th-ch/youtube-music#2112]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.10

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Build 22631

### What CPU architecture are you using?

x64

### Reproduction steps

1. Listen to a radio to it's entirety
2. Since the songs don't update, it ends up stopping.

### Expected Behavior

Just like in Official YouTube Music, in which the radio generates the next songs when near the end.

### Actual Behavior

The radio stops playback the only way to get new songs to generate is to either restart/reload the app or to reload the radio, by listening to any song which isn't from the radio then going back to said radio, for example.

### Enabled plugins

1. Album Actions
2. Compact Sidebar
3. In-App Menu
4. Navigation
5. SponsorBlock
6. Video Quality Changer

**Comment by JellyBrick** [comment]
Reproducible in the official YTM.
