### ISSUE TITLE
[Bug]: app not working on clean install ubuntu 24.04 and kubuntu 24.04

### ISSUE THREAD

**Issue by falconnnx** [th-ch/youtube-music#2123]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.10 .deb

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

nope on clean flash ubuntu 24.04

### Reproduction steps

just trying to open the app

### Expected Behavior

opening the app

### Actual Behavior

When I try to open the application, it does not open. When I try to open it from the terminal, I get the following output:
$ youtube-music
LaunchProcess: failed to execvp:
/opt/YouTube
[9730:0605/110120.260550:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Geçersiz bağımsız değişken (22)
İzleme/kesme noktası yakalayıcı (çekirdek döküldü)

### Enabled plugins

i dont know because app doesnt work. Its your 3.3.10 build.

### Additional Information

tried .deb, .snap, .appimage but no one is worked for me

**Comment by JellyBrick** [comment]
Did you use this application in virtual env? (e.g. docker)

https://github.com/electron/electron/issues/41919

**Comment by falconnnx** [comment]
> Did you use this application in virtual env? (e.g. docker)
> 
> [electron/electron#41919](https://github.com/electron/electron/issues/41919)

no i am not using any virtual env. just clean flasher ubuntu 24.04 tried kubuntu too but not worked

**Comment by huiqiangyang** [comment]
my ubuntu 24.04 not working too.

**Comment by falconnnx** [comment]
I tried it with my friend's laptop, the application was installed on him for a long time and when he upgraded to ubuntu 24.04, the application continued to work. The application was working on my computer before I reset my laptop, but since I reset and did a clean installation, the application has not been opening.

**Comment by mihaistana** [comment]
Same behavior here, I tried with `youtube-music --no-sandbox` from terminal and it works fine

**Comment by JellyBrick** [comment]
@falconnnx @huiqiangyang @mihaistana 

Caused by Ubuntu 24.04's AppArmor

See https://github.com/electron/electron/issues/41066#issuecomment-1913509942

**Comment by Su-Yong** [comment]
duplicate https://github.com/th-ch/youtube-music/issues/2007
