### ISSUE TITLE
[Bug]: how do i connect to YTMD

### ISSUE THREAD

**Issue by MAX1MDEV** [th-ch/youtube-music#2140]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Open the app
2. idk what next

### Expected Behavior

nothing

### Actual Behavior

nothing

### Enabled plugins

nothing

**Comment by JellyBrick** [comment]
What?
