### ISSUE TITLE
[Feature Request]: Addition of "youtube-ambilight" extension

### ISSUE THREAD

**Issue by Aeropro4** [th-ch/youtube-music#2144]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Is it possible to add the extension "[youtube-ambilight](https://github.com/WesselKroos/youtube-ambilight)" by WesselKroos" 
As i use it when watching amv or mv and it looks amazing.

### Proposed Solution

Addition of ambilight extension

### Alternatives Considered

N/A

**Comment by JellyBrick** [comment]
Already implemented.
