### ISSUE TITLE
[Bug]: freezes on start

### ISSUE THREAD

**Issue by gordli** [th-ch/youtube-music#2149]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12, 3.3.11, 3.3.10 (didn't test more)

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home 22H2 19045.4412

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.0.0 (could also work in later builds until 3.3.10)

### Reproduction steps

1. Start youtube music desktop app
2. Wait several seconds

### Expected Behavior

UI elements will be responsive.

### Actual Behavior

Entire app is laggy from the start, and freezes completely within 10 seconds. 
Still works fine with release 3.3.0.0, and possibly later builds, but not 3.3.12, 3.3.11, 3.3.10.

### Enabled plugins

- bypass age restrictions
- in-app menu
- precise volume
- taskbar media control
- video quality changer
- video toggle (native toggle)

**Comment by JellyBrick** [comment]
Probably fixed in `3.4.0`.
