### ISSUE TITLE
[Bug]: UI lags tremendously when forcing a UI-Refresh by doing anything (Former Title: Discord Plugin lags out UI of the newest Release version)

### ISSUE THREAD

**Issue by Shadowphoenix** [th-ch/youtube-music#2155]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Win 10 22H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.9 i think? havent used it in a while

### Reproduction steps

Enabled Discord with settings shown in picture. Nothing else is activated. Then force UI-Update by opening a new Playlist etc or resize the window.
![image](https://github.com/th-ch/youtube-music/assets/38107036/2de179e0-898d-43ec-877d-afa516246a43)

### Expected Behavior

UI not lagging when i have the Discord-RichPresence-Plugin activated.

### Actual Behavior

Whenever i have the plugin activated,  the UI regularly fails to update for a second or two, for example when resizing the window.
I havent experienced this behavior without the Plugin - but that doesnt mean the plugin is the issue, maybe it does happen but i just havent encountered it yet.

### Enabled plugins

Discord (nothing else)

### Additional Information

I tried disabling and re-enabling hardwareacceleration, similar to how i could circuumvent the semirecent issue with the adblocker lagging out the UI. But that didnt work this time. My Internetconnection isnt the best (16 mbit/s), but i doubt that is the cause - else i would probably also experience the stuttering UI the plugin is disabled.

**Comment by Pableske** [comment]
I have the same problem

**Comment by Shadowphoenix** [comment]
Turns out this also happens occasionally without any Plugin active at all.

Specifically i encountered the UI to not update when i move my mouse across several titles in a playlist: the Dislikebuttons are slow to update/appear and its a similar issue with most other UI-Elements. A Clip of this issue manifesting can be found here:

https://youtu.be/RPqf3HwnSKM

**Comment by sandarutharuneth** [comment]
Mine doesn't show anything after enabling. No status on discord

**Comment by SteveFour** [comment]
Mine lags as well.
Especially when open song list from an artist.

**Comment by Shadowphoenix** [comment]
3.4.1 fixed it for me - same experienc for you @SteveFour @Pableske ?

**Comment by SteveFour** [comment]
Nope. Still lags on my end.
You can try scrolling through the All Songs list from an artist.
This lagging issue doesn't happen on Youtube Music web
My enabled plugins include Ad Blocker, Compact Sidebar, Downloader, In-App Menu, Navigation and Video Toggle.

**Comment by Pableske** [comment]
> 3.4.1 fixed it for me - same thing for you @SteveFour @Pableske ? or still laggy?

In my case the lag was solved by disabling the option called IN APP MENU

**Comment by SteveFour** [comment]
Oh it actually works. Thanks @Pableske 
So it's actually the In app menu the issue? 😂

**Comment by Shadowphoenix** [comment]
@SteveFour @Pableske i would recommend to put your findings into a separate new issue as to not confuse the devs

**Comment by Shadowphoenix** [comment]
seems to be the issue mentioned by steve and pableske, closing because confusing
