### ISSUE TITLE
[Feature Request]: Any way to play/pause or skip using keyboard shortcuts?

### ISSUE THREAD

**Issue by LOLLETTU** [th-ch/youtube-music#2159]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I don't know if it's a bug or it's not implemented in the app but i cant use the keyboard shortcuts to skip songs in youtube music.

### Proposed Solution

Implement keyboard shortcuts to give users availability to skip songs using the app in background.

### Alternatives Considered

Don't use shortcuts 😅

**Comment by JellyBrick** [comment]
Please enable the shortcuts plugin.
