### ISSUE TITLE
[Question] Does video stream stop as in 'Song' mode of 'Video Toggle' plugin when we use 'Visualizer' plugin?

### ISSUE THREAD

**Issue by RohitSurwase** [th-ch/youtube-music#2171]
I want keeps app in Songs/Audio mode only. But since I added Visualizer plugin, I am not sure whether Video Toggle still works or not as we don't get to see the Video.
Does video stream stop as in Song mode of Video Toggle plugin when we use Visualizer plugin?

OS: MacOS: 14.3.1 (23D60)
App Version: 3.3.12 (3.3.12)
Plugins: Ad Blocker, Visualizer, Video Toggle, Navigation, Precise Volume

**Comment by JellyBrick** [comment]
No, it doesn't.
