### ISSUE TITLE
[Bug][Regression]: "Skip Disliked Song" haven't work anymore

### ISSUE THREAD

**Issue by Kerrung** [th-ch/youtube-music#2176]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

[3.3.12](https://aur.archlinux.org/packages/youtube-music)

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

Cant remember

### Reproduction steps

1. Enable "Skip Disliked Song" plugin.
2. Restart the app.
3. Listen disliked songs.

### Expected Behavior

Disliked songs always skipping.

### Actual Behavior

Disliked songs never skipping.

### Enabled plugins

[config.json](https://github.com/user-attachments/files/15942171/config.json)

### Additional Information
https://aur.archlinux.org/packages/youtube-music

**Comment by Rumahu** [comment]
Still an issue as of 3.6.2

**Comment by Kerrung** [comment]
@JellyBrick @killerbytes Hi! This bug is come back since with a recent update to this app. Reopen, please.
