### ISSUE TITLE
[Bug]: no app icon shown when using media controls in TouchBar

### ISSUE THREAD

**Issue by steel-digit** [th-ch/youtube-music#2183]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Open YouTube Music app on a MacBook with TouchBar and start playing music
2. Press on the Now Playing icon in the TouchBar Control Strip so the media controls appear in the TouchBar
3. Notice that on the far left of the media controls there is a blank icon where there should be the YouTube Music app icon

### Expected Behavior

When using the media controls on the TouchBar, there should be the logo of the app you're currently controlling on the far left

### Actual Behavior

There is a blank icon

### Enabled plugins

1. Album Color Theme
2. Compact Sidebar
3. Navigation
4. Notifications
5. Skip Disliked Songs
6. TouchBar
7. Video Toggle

**Comment by JellyBrick** [comment]
Are you experiencing the same issue as #2113?

**Comment by steel-digit** [comment]
No, I can see the plugins options just fine in the menu bar. 
The issue is on the TouchBar itself; if I want to control playback on Cider through the built-in MacOS playback controls on the TouchBar, the icon for the YouTube app is missing on the TouchBar itself. This is used to switch between media apps if you are playing media from different sources (e.g. switch between YT Music and Apple Music).

I've included an image I pulled from Google, on the left of the TouchBar you can see an app icon which I have circled in blue, for YouTube Music this is missing when I use the TouchBar.
![41816595-42b743d2-7757-11e8-910c-e607282cf9df](https://github.com/th-ch/youtube-music/assets/173679216/62f58f1a-16c1-4551-bb0b-8006db3e3914)

I'm starting to wonder  if this is a bug or just never implemented correctly.

**Comment by steel-digit** [comment]
I see the change has been implemented in the latest release, 3.4.1, but the problem persists. In general the way the media controls work on the TouchBar for this app is lackluster. When I find the time I will log a new issue with a more elaborate problem description and how this feature should be working. @JellyBrick
