### ISSUE TITLE
Improve downloader

### ISSUE THREAD

**Issue by devstra** [th-ch/youtube-music#219]
The url of the opened page is what's used to download songs with the downloader plugin. This is a problem because it means that the song needs to be "opened" to be able to download it. 
I often find my self trying to download a song from search results by clicking on the 3 dots menu on the side, only to find that the plugin is using the url of the search results and not the url of the song and therefore doesn't work.

**Comment by th-ch** [comment]
Hey @devstra, thanks for the feedback! This is a known issue that should be fixed by https://github.com/th-ch/youtube-music/pull/213 (merged, it will land in the next version), downloader will now use the current song being played instead of the current URL!
