### ISSUE TITLE
[Bug]: app freezes and cannot be closed when vsync target can't be found

### ISSUE THREAD

**Issue by chboishabba** [th-ch/youtube-music#2191]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

latest

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

latest

### Reproduction steps

i beleive it relates to the visualiser plugin being enabled. it produces visualiser for one second then freezes.

### Expected Behavior

disable visualiser if no vsync target?

### Actual Behavior

crash

### Enabled plugins

i'll launch again in a minute to confirm which

**Comment by chboishabba** [comment]
cat config.json (anon'd)
{
	"window-size": {
		"width": ,
		"height": 
	},
	"window-maximized": false,
	"window-position": {
		"x": ,
		"y": 
	},
	"url": "https://music.youtube.com/watch?v=&list=&index=0",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"alwaysOnTop": false,
		"hideMenu": false,
		"hideMenuWarned": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"removeUpgradeButton": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": false,
		"resumeOnStart": true,
		"likeButtons": "",
		"proxy": "",
		"startingPage": "Charts",
		"overrideUserAgent": false,
		"usePodcastParticipantAsArtist": false,
		"themes": []
	},
	"plugins": {
		"notifications": {
			"enabled": true
		},
		"video-toggle": {
			"mode": "custom",
			"enabled": true,
			"hideVideo": true,
			"forceHide": false,
			"align": "left"
		},
		"precise-volume": {
			"globalShortcuts": {}
		},
		"discord": {
			"listenAlong": true,
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "With blocklists",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},
		"sponsorblock": {
			"enabled": true
		},
		"album-color-theme": {
			"enabled": true,
			"ratio": 0.7
		},
		"album-actions": {
			"enabled": true
		},
		"scrobbler": {
			"enabled": true,
			"scrobbleOtherMedia": true,
			"scrobblers": {
				"lastfm": {
					"enabled": true,
					"token": "--",
					"apiRoot": "https://ws.audioscrobbler.com/2.0/",
					"apiKey": " \",
					"secret": " \"
				},
				"listenbrainz": {
					"enabled": true,
					"apiRoot": "https://api.listenbrainz.org/1/"
				}
			}
		},
		"lyrics-genius": {
			"enabled": true
		},
		
	},
	"__internal__": {
		"migrations": {
			"version": "3.3.12"
		}
	}
}

**Comment by chboishabba** [comment]
I still get the vsync error but no crashing after disabling visualiser... i think i may have edited the config above trying to get the app to start again.. wasn't happening so reinstalled. i'm not sure if it's expected behaviour but i'm not seeing community playlists in the related tab...

**Comment by JellyBrick** [comment]
Probably fixed in `3.4.0`.
