### ISSUE TITLE
[Bug]: When using DEV no song info on start

### ISSUE THREAD

**Issue by Johannes7k75** [th-ch/youtube-music#2201]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12 DEV

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Setup a dev version of ytm
2. run `pnpm run dev`
3. add a new Plugin that sends on registerCallback a console.log of songinfo

### Expected Behavior

A console.log where the songinfo is send as a json object

### Actual Behavior

No console.log of songInfo on start
After first skip / song change the song info is logged correcly

### Enabled plugins

1. CustomPlugin

### Additional Information

This only appears when using it in development when using `pnpm run start` it, the behavior disappears

CustomPlugin
```ts
// plugins/custom-plugin/index.ts
import { createPlugin } from "@/utils";
import registerCallback from "@/providers/song-info";

export default createPlugin({
  name: () => "Custom plugin",
  description: () => "Custom test plugin",
  restartNeeded: false,

  renderer: {
    onPlayerApiReady(playerApi, context) {
        context.ipc.on("testLog", (message: string) => console.log("TestLog: " + message));
    },
  },

  backend: {
    start: (ctx) => {
      registerCallback((songInfo) => {
        console.log("Song info changed", songInfo);
        ctx.window.webContents.send("testLog", `songInfo: ${JSON.stringify(songInfo)}`);
      });
    }
  }
});
```

**Comment by ArjixWasTaken** [comment]
This should be fixed by #2343 which is already merged.
