### ISSUE TITLE
[Bug]: UI Flickering without any plugins

### ISSUE THREAD

**Issue by svxer** [th-ch/youtube-music#2203]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631.3810)

### What CPU architecture are you using?

x64

### Reproduction steps

1. Open the app
2. Starts flickering from the start

### Expected Behavior

No UI flickering

### Actual Behavior

UI Flickering

### Enabled plugins

None

### Additional Information

I tried to toggle on/off every setting and i couldn't resolve this. Also, for some reason, if i use Geforce Experience recording then the flickering goes off until i stop recording.

Here's a video of the bug happening:

https://github.com/th-ch/youtube-music/assets/78035451/92fdcdac-44e1-4dbe-a79e-d5cf02fe7388

**Comment by JellyBrick** [comment]
Probably fixed in version `3.4.0`.
