### ISSUE TITLE
[Bug]: using the plugin "lumiastream" the eventType switchSong is only sent 6 times unless the connection is restarted

### ISSUE THREAD

**Issue by abdevlpr** [th-ch/youtube-music#2220]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

- Enable plugin Lumia Stream
- connect the youtube music to Lumia Stream
- activate the song switched Alert
- every time the song is switched in youtube music the alert will trigger 
- but after the 6th trigger nothing will come through
- until you restart the app then you'll get another 6 working alert triggers 

### Expected Behavior

When sending data.eventType = 'switchSong' it should always send to Lumia Stream without the need to restart the app everytime

### Actual Behavior

When sending data.eventType = 'switchSong' it stops after the 6th time from sending and no event is sent anymore until app reload manually

### Enabled plugins

- LumiaStream

### Additional Information

I can reproduce the same issue on my other devices and on windows as well

**Comment by BluesBroBo** [comment]
I wonder if the bug will be fixed anytime. I started using th-ch because of the option to display the songs on stream, but now that's the very part that is broken since months :/

**Comment by ArjixWasTaken** [comment]
The number 6 sounds really arbitrary ngl.

**Comment by ArjixWasTaken** [comment]
I spent an hour trying to make sense of this, but I give up.

1. lumiastream has shitty docs
2. the api used in the code is not documented anywhere, and adding `th-ch/youtube-music` as an integration did nothing
3. lumia's webserver does not start, even after I enabled developer mode and restarted lumia a few times

Does this even work?
Do you even get to experience this bug?

**Comment by ArjixWasTaken** [comment]
You'd expect a service like lumiastream to have good documentation since they make money off this, but looks like that ain't the case.

**Comment by abdevlpr** [comment]
Hi @ArjixWasTaken ,
It looks like there might have been some confusion with the setup process. Here’s how you can get YouTube Music working with Lumia Stream:

- Download Lumia Stream from [https://lumiastream.com/downloads](https://lumiastream.com/downloads).
- Create an account and start the app.
- Go to Connections -> **Add Connection** -> search for **YouTube Music**.
- Select **TH-CH YouTube Music**.
- Leave the IP address as `localhost` and the port as `9863`.
- Enable the Lumia extension in the YouTube Music app.
- Restart YouTube Music.

After that, go to Alerts to ensure you have it set to something that can show. A good way to test is to also connect Twitch or any platform with a chatbot integration, so you can see if the issue arises when it gets stuck.
In Alerts, under YouTube Music, set the chatbot message (or tts if you don't want to connect another platform) to: `{{youtubemusic_now_playing_song}} - {{youtubemusic_now_playing_artist}}`, so you can display the song title and artist in your chat.
Let me know if you still run into any issues, and I'll be happy to help!
