### ISSUE TITLE
Ad Blocker Not Working[Bug]: 

### ISSUE THREAD

**Issue by Tarangit1** [th-ch/youtube-music#2224]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 11 Home Single Language Version	

### What CPU architecture are you using?

x64

### Reproduction steps

While Listening after 2 -3 songs the song stops for few seconds

### Expected Behavior

The song should play normaly

### Actual Behavior

While Listening after 2 -3 songs the song stops for few seconds

### Enabled plugins

1. Ad Blocker
2. Exponential Volume
3. In-App Menu
4. Precise Volume
5. Shortcuts
6. Video Toggle

### Additional Information

I think the ad block is not working properly it block the ad audio it still plays blank ad

**Comment by TecnikOfficial** [comment]
have u tried enabling blocklist from adblocker option 
<details>
  <summary>Click to view screenshot</summary>  
![ad](https://github.com/user-attachments/assets/adb65e6c-fc35-4938-b6ff-8c8f434829bd)
</details>

**Comment by Tarangit1** [comment]
I tried it now without changing anything its working now.
