### ISSUE TITLE
[Bug]: Like/dislike icon duplication issue

### ISSUE THREAD

**Issue by Rairof** [th-ch/youtube-music#2231]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11 pro

### What CPU architecture are you using?

x64

### Reproduction steps

1. install latest YTM with web setup.exe from releases
2. open YTM and go to liked playlist

### Expected Behavior

To have single like/dislike icons instead of twice

### Actual Behavior

Has like/dislike icons twice

### Enabled plugins

1. Ad Blocker
2. Album Actions
3. Album Color Scheme Color mix ratio- 50%
4. Ambient Mode-
    Smoothness transition- During 1.5s
    Quality- 50 pixels
    Size- 100%
    Buffer- 30
    Opacity- 100%
    Blur amount- 100 pixels
5. Blur Navigation Bar
6. Bypass Age Restrictions
7. Discord Rich Presence-
    ✓ Auto reconnect
    ✓ Clear activity after timeout
    ✓ Play on YouTube Music
    ✓ Hide GitHub link Button
8. Downloader
9. In-App Menu
10. Lyrics Genius
     ✓ Romanized Lyrics
11. Music Together [Beta]
12. Navigation
13. Precise Volume
     ✓ Local Arrow-keys Controls
14. Skip Disliked Songs
15. Taskbar Media Control
16. Video Quality Changer
17. Video Toggle-
     Mode- Native toggle
     Alignment- Left

### Additional Information

![image](https://github.com/user-attachments/assets/15de8758-b4bf-4ea6-ab5f-bc9d6493613b)

**Comment by JellyBrick** [comment]
It's not a duplication.
Undislike (all), Dislike (all), Like (all), Unlike (all).

As an aside, I agree that the UX is not intuitive.

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/2231#issuecomment-2227405130
Oh I see, I might have never spotted it before to just see it now and considered it as an issue as I haven't seen it before. Thank you for the clarification!
