### ISSUE TITLE
[Bug]: Playlist Empty Error, when Downloading Albums

### ISSUE THREAD

**Issue by SamuDifferent** [th-ch/youtube-music#2234]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04 LTS

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.12

### Reproduction steps

1. Enable Download Extension
2. Click "Download" on any Album

### Expected Behavior

Album is Downloaded and put into chosen Directory

### Actual Behavior

Download fails and Error Popup appears
![image](https://github.com/user-attachments/assets/97eb0660-3d2e-4c56-982a-1c354f3514fb)
'Argh! Apologies, download failed...
Error: Playlist is Empty'

### Enabled plugins

1. Ad Blocker
2. Ambient Mode
3. Blur Navigation Bar
4. Bypass Age Restriction
5. Downloader
6. Music Together 
7. Navigation
8. Precise Volume
9. Video Quality Changer

**Comment by Atops93** [comment]
I sadly have this exact issue as well but on Arch linux.

**Comment by neolight1010** [comment]
Same here, Ubuntu 24.04, amd64, v3.4.1. As a workaround, I'm adding the album tracks to a playlist and downloading the playlist instead.

**Comment by NeekoKun** [comment]
Having the same problem here on EndeavourOS... I'm moving the default download dir to a subfolder and just downloading every song manually

**Comment by SamuDifferent** [comment]
Still a Problem on Version v3.5.0

**Comment by da-anda** [comment]
got same issue on Fedora (AppImage version) running v3.5.1. Only actual playlists can be downloaded, but not albums

**Comment by ajgo30** [comment]
I am having this same issue in Windows 10 running v 3.5.1.0. I can download songs individually, but not the album all at once. Adding to a playlist is a workaround that still works.

**Comment by waris-mohammad** [comment]
Unfortunately the same issue persists in version 3.5.3.0 on Windows 11. Adding to a playlist is a workaround that works but it seems that track number is not saved in the metadata.

**Comment by ora282** [comment]
This error is still present in 3.6.2.0 on Windows 11

the playlist workaround still works but its a bummer as the previous behavior saved a lot of time when downloading many albums consecutively

**Comment by vestyc** [comment]
I'm also seeing this issue in these last versions: 3.3.2, 3.5.3, and 3.6.2 on Debian 12. I use the AppImages.

**Comment by yarik303** [comment]
3.6.2.0 windows, same issue

**Comment by loeffelpan** [comment]
Same here 😒

**Comment by errorb0t** [comment]
This issue persists on 3.7.0.
