### ISSUE TITLE
[Feature Request]: Option to Disable Video Playback

### ISSUE THREAD

**Issue by Inlayo** [th-ch/youtube-music#2246]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If you play a video and the next song has a music video, it will play as a music video, which can be inconvenient. Is there a function to turn off video playback completely?

### Proposed Solution

Add an option in the settings to disable video playback entirely, ensuring that only audio plays regardless of whether the next track is a music video or not.

### Alternatives Considered

Thank you for considering this feature request!

**Comment by Johannes7k75** [comment]
Did you looked at the "Video Toggle" plugin?

**Comment by Inlayo** [comment]
Yes, I have looked at the "Video Toggle" plugin. However, even when this feature is enabled, there is still an issue where videos are automatically played. I have attached a video demonstrating the issue for your reference.
video : https://drive.google.com/file/d/11ta1odgD-Ir8b8MnmFsnsgh5__UhdaI5/view?usp=drive_link

**Comment by Johannes7k75** [comment]
You could use "Force remove video Tab" but then there isnt even the cover.

**Comment by Inlayo** [comment]
I know the function, but it doesn't change when I use it.
video : https://drive.google.com/file/d/1g6ROb3d2Nm2UipGOXpvJjrj2HKaFgx3z/view?usp=drive_link

**Comment by ArjixWasTaken** [comment]
Please directly upload videos to GitHub when possible

**Comment by Inlayo** [comment]
The extension of the file is .mkv, so you can only upload it after encoding.

**Comment by Inlayo** [comment]
:(

**Comment by ArjixWasTaken** [comment]
> The extension of the file is .mkv, so you can only upload it after encoding.

well....you could just encode it...

`ffmpeg -i myvideo.mkv myvideo.mp4`

**Comment by Inlayo** [comment]
I accidentally deleted all the videos..
