### ISSUE TITLE
[Bug]: Discord Can't Fetch Album Art for Uploaded Audio Files (Rich Presence)

### ISSUE THREAD

**Issue by Planto-2** [th-ch/youtube-music#2247]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Upload a an audio file found on your hard drive to youtube music.
2. Play it, discord can't display the album art for rich presence.

### Expected Behavior

![image](https://github.com/user-attachments/assets/7f5b455c-a553-4f02-a43b-912967098be4)

Here's an example of discord showing the album art for music uploaded by verified musicians.

### Actual Behavior

![image](https://github.com/user-attachments/assets/4f3eba08-c4dc-4066-b081-5b8a00f13b4b)

Here's an example of discord unable to display the image exclusively to music uploaded by the user to their personal library.

### Enabled plugins

1. Bypass Age Restriction
2. Compact Sidebar
3. Discord Rich Presence
4. Downloader
5. In-App Menu
6. Navigation

**Comment by Crul0** [comment]
I'm having a issue instead of the cover not loading the time left doesnt work

**Comment by Andrew040543** [comment]
In the same situation, I'm getting that big question mark instead of the art cover
