### ISSUE TITLE
Download plugin isnt working

### ISSUE THREAD

**Issue by BrotherKabeer** [th-ch/youtube-music#225]
![Screenshot (138)](https://user-images.githubusercontent.com/70783428/113492352-56fa8600-949c-11eb-8cc4-a50322498d75.png)

is there a dependency i need to download?

**Comment by Araxeus** [comment]
You currently need to be playing the song you want to download.
will be fixed in the next release, following #221

**Comment by arthur109** [comment]
How about if you want to download an entire playlist, what would you do then? Or is that just not possible?

**Comment by Araxeus** [comment]
@arthur109 playlist downloading is also coming in the next release

**Comment by th-ch** [comment]
Closing this issue as it should be solved in the latest version, feel free to re-open in case of issue!
