### ISSUE TITLE
[Bug]: Adblocking not working with blocklists

### ISSUE THREAD

**Issue by i-a-m-a-k** [th-ch/youtube-music#2251]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [x] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux 6.9.9

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable Adblocker
2. Set it to "with blocklists" option
3. Change this in config file (according to some previous issues)
```
"additionalBlockLists": [
	"https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt"
],
```
4. Play some song

### Expected Behavior

Songs play directly without any ads.

### Actual Behavior

I get atleast 2 ads before the music starts.

### Enabled plugins

1. Ad Blocker
2. Blur Navigation Bar
3. Bypass age restrictions
4. In-App Menu
5. Navigation
6. No Google Login
7. Video Toggle

### Additional Information

- Attaching [`config.json`](https://github.com/user-attachments/files/16272225/config.json) in case I missed mentioning something.
- In case it matters, I am in EU.
- While I don't remember the exact version when the ad blocking worked, I do remember it was around a month and a half ago.  (I used blocklists then as well)
- I installed the [`youtube-music-bin`](https://aur.archlinux.org/packages/youtube-music-bin) package from AUR

**Comment by theluminal** [comment]
I have the same problem, all blocking methods don't work.
OS: Windows 11, Pop OS (based on Debian)

**Comment by CreativeRoy** [comment]
same problem, both "with bocklists" and "in player" don't work. I updated blocklists from a previous thread, and they still don't work
OS: Arch

**Comment by xdpirate** [comment]
Same here, also Europe, running the .deb on KDE neon 6.0 user edition.

**Comment by rndmppl69** [comment]
Had same problem with it, but thanks to @gabe39 for [this](https://github.com/th-ch/youtube-music/issues/2150#issuecomment-2230574204) , now it's working good so far.

**Comment by xdpirate** [comment]
@rndmppl69 That seems to work for me as well, and it makes sense that it does since uBO blocks it in the browser.

**Comment by peter9811** [comment]
"adblocker": {
  "enabled": true,
  "cache": true,
  "blocker": "With blocklists",
  "additionalBlockLists": [
    "https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt",
    "https://adguard.com/en/filter-rules.html?id=2",
    "https://adguard.com/en/filter-rules.html?id=3",
    "https://adguard.com/en/filter-rules.html?id=14",
    "https://easylist.to/easylist/easylist.txt",
    "https://easylist.to/easylist/easyprivacy.txt",
    "https://fanboy.co.nz/fanboy-annoyance.txt",
    "https://fanboy.co.nz/fanboy-antifacebook.txt",
    "https://fanboy.co.nz/fanboy-social.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/thirdparties/easylist/easyprivacy.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/thirdparties/easylist/easylist.txt",
    "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoFilters/NanoDefender.txt",
    "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt",
    "https://raw.githubusercontent.com/yous/YousList/master/youslist.txt",
    "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt"
  ],
  "disableDefaultLists": false
}


This one is working for me. maybe is a overkill, but...

**Comment by gabe39** [comment]
> ```
> "adblocker": {
>   "enabled": true,
>   "cache": true,
>   "blocker": "With blocklists",
>   "additionalBlockLists": [
>     "https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt",
>     "https://adguard.com/en/filter-rules.html?id=2",
>     "https://adguard.com/en/filter-rules.html?id=3",
>     "https://adguard.com/en/filter-rules.html?id=14",
>     "https://easylist.to/easylist/easylist.txt",
>     "https://easylist.to/easylist/easyprivacy.txt",
>     "https://fanboy.co.nz/fanboy-annoyance.txt",
>     "https://fanboy.co.nz/fanboy-antifacebook.txt",
>     "https://fanboy.co.nz/fanboy-social.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/thirdparties/easylist/easyprivacy.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/thirdparties/easylist/easylist.txt",
>     "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoFilters/NanoDefender.txt",
>     "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt",
>     "https://raw.githubusercontent.com/yous/YousList/master/youslist.txt",
>     "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt"
>   ],
>   "disableDefaultLists": false
> }
> ```
> 
> This one is working for me. maybe is a overkill, but...

Hmm... it's interesting that it works for you. I remember trying this way some time ago, and the app would refuse to work, giving me an error. That's why I had to merge them into one list using the site that I found by accident.

**Comment by i-a-m-a-k** [comment]
This works for me as well. Thanks @peter9811 @rndmppl69 and @gabe39 
Should I close this issue?

**Comment by theluminal** [comment]
It works for me as well. Thank you all for the solution!

**Comment by i-a-m-a-k** [comment]
Since it is working for others as well, I am closing this issue.

**Comment by tarbib** [comment]
Hello there I'm using @gabe39 blocklist but since last week I have ads again :( 
Anyone else having the same issue?
