### ISSUE TITLE
[Feature Request]: "Guess" Genius lyrics from song & artist name

### ISSUE THREAD

**Issue by Reycko** [th-ch/youtube-music#2256]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

A lot of songs from the 2000s-2010s don't have any lyrics associated, causing the lyrics page to be inaccessible even if the song has some.

### Proposed Solution

Search Genius for the artist's name, followed by the song.
example: Getting lyrics for Eminem - Without Me would make a search for "Eminem Without Me".
Perhaps a check for making sure the artist is the same and the song name is similar could be useful?

### Alternatives Considered

Searching Genius manually on my browser for the song.

**Comment by Reycko** [comment]
> 😕
> 
> #2207

Isn't that PR about **syncing** lyrics though?

**Comment by ArjixWasTaken** [comment]
true

**Comment by Reycko** [comment]
Synced lyrics does this and more and this is no longer needed
