### ISSUE TITLE
[Bug]: Plugin In-App-Menu seems to lag out the UI

### ISSUE THREAD

**Issue by Shadowphoenix** [th-ch/youtube-music#2266]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

22H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.9 i think

### Reproduction steps

Enable plugin In-App-Menu

### Expected Behavior

A UI that isnt laggy to hell and back

### Actual Behavior

HUGE Stutters when UI is refreshing for example when moving the mouse across a playlist.

### Enabled plugins

In-App-Menu

**Comment by Shadowphoenix** [comment]
More Details to be found in #2155

**Comment by JellyBrick** [comment]
Could you provide the URL of playlist?

**Comment by Shadowphoenix** [comment]
> Could you provide the URL of playlist?

its basically any playlist, specifically large ones like my 900-song YTM-Curated Favorite Songs.

That being said i can not reproduce this issue reliably myself. I did some more testing and Whenever it happens there is no (know-to-me, at least) stress on the Computer - if anything i see downwardsspikes of the CPU- and Graphicsloads, as if the two of them were waiting for something else to load. This leads me to the following idea:

There was a similar bug, that was haunting KDE Plasma for a while. Certain workspaceeffects, primarily Windowswitching like "The Cube", would lead to several-second-long stutters and the workspace completely freezing up. because the underlying QML was being loaded from a drive that was already operating at IOPS-capacity. hence pushing said drive EEEEEEEEEVER so slightly over the edge of what it could do.
HOWEVER, unlike with said KDEbug, I' can not detect any significant spikes in Harddrive- or Networkactivity before or after the stutters in YTM happen.

**Comment by JellyBrick** [comment]
It was caused by #1992.

https://github.com/th-ch/youtube-music/blob/199d912823629a154711429d205265b5d336ade3/src/plugins/in-app-menu/titlebar.css#L8

For some reason, using `overflow: scroll` prevents YTM's virtual scrolling from being applied correctly.

**Comment by DereC4** [comment]
It's crazy how the css tag was causing all this performance issue 😭

can reproduce, I made this track to test with 5k songs and it shows extreme loading times 

https://music.youtube.com/playlist?list=PLmIc9g0HzInoowGaHHMXsD9UTOa90m8YB&si=XvxOWF6TktiPLnxB

**Comment by DereC4** [comment]
> It was caused by #1992.
> 
> https://github.com/th-ch/youtube-music/blob/199d912823629a154711429d205265b5d336ade3/src/plugins/in-app-menu/titlebar.css#L8
> 
> For some reason, using `overflow: scroll` prevents YTM's virtual scrolling from being applied correctly.

any fix coming up ? :0

**Comment by daika7ana** [comment]
Adding `backface-visibility: hidden;` to `ytmusic-app-layout` solves the lag.

**Comment by DereC4** [comment]
awesome, did we merge yet
