### ISSUE TITLE
app sucking too much performance in the background, even when not being used (or closed)

### ISSUE THREAD

**Issue by b-init** [th-ch/youtube-music#227]
![image](https://user-images.githubusercontent.com/55803927/114016723-c3a0c680-9888-11eb-86fc-c0de59576849.png)

Why is it sucking so much of my CPU in the background even after it's closed? 
It's on an i5-8265U processor

**Comment by Bellisario** [comment]
I think this is because if you have this app in background, the page is hidden, but it needs to stay opened to continue playing music, as in the [web version](https://music.youtube.com/).

**For project DEVs**
A beautiful thing to be implemented can be close the page (don't hide it) if not playing some music for (ex.) five minutes.
(@th-ch)

**Comment by Araxeus** [comment]
![](https://i.imgur.com/7M5M1nG.png)
I've been running it for hours/days straight with no problem. [Windows 10 build 19042]

@Yeetus3141 
- what OS are you running? 
- what plugins do you have enabled? 
- is it always like that?

**Comment by Yeetus3141** [comment]
> ![](https://camo.githubusercontent.com/581c605c62b5608fce28cf39c23740cc27059277923923ad66c1f40eb2e85327/68747470733a2f2f692e696d6775722e636f6d2f374d354d316e472e706e67)
> I've been running it for hours/days straight with no problem. [Windows 10 build 19042]
> 
> @Yeetus3141
> 
> * what OS are you running?
> * what plugins do you have enabled?
> * is it always like that?

I'm running Windows 10 (20H2)
I've attached a screenshot of enabled plugins.
That happens fairly rarely and I have not found a way to replicate it yet.

**Comment by Araxeus** [comment]
I'm also using all those plugins except 'Discord'
but I don't actually think its related to that

Hopefully it doesn't happen again..

**Comment by th-ch** [comment]
Hey @Yeetus3141, thanks for the feedback! I will try to have a look but Electron has an history of consuming many resources, especially when the app is left open, it might explain your situation - these types of bugs depend on many things (e.g. the OS but not only) so it might be hard to reproduce though. 

Electron is updated as much as possible in the project, last time I checked the only blocker to go to the next major version was the broken downloader (FFmpeg issue to be exact).

**Comment by cpiber** [comment]
I found a similar problem on Ubuntu 18.04...
![Screenshot_2021-06-03_21-50-34](https://user-images.githubusercontent.com/59023762/120759246-21f9c680-c513-11eb-9e91-e98dd4e9e726.png)
3GB of memory

**Comment by SkyD666** [comment]
Windows 10 Home 1903
CPU: i5-9300H
RAM: 24GB
![QQ截图20220216152452](https://user-images.githubusercontent.com/32453770/154216223-18e0a9e0-f970-48e7-a886-d7b19712c9d0.png)

**Comment by SkyD666** [comment]
After I disabled all plugins, the problem was solved.

**Comment by Araxeus** [comment]
I've tried replicating this, left youtube music open for 3 days 

cpu&ram&disk usage was totally normal

 (worth noting I tested with the new version v1.16.0 which has yet to be released)

**Comment by Araxeus** [comment]
can you try using the latest version?
https://github.com/th-ch/youtube-music/releases/tag/v1.16.0

**Comment by DerMueller** [comment]
Well it's been some time... maybe it has something to do with #4193 ?
