### ISSUE TITLE
Error : The server responded with a non 2xx status code 

### ISSUE THREAD

**Issue by 4096Richard** [th-ch/youtube-music#2270]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 

### What CPU architecture are you using?

x64

### Reproduction steps

Enable the downloader on the newest version 
and try to download any song it will appear with 
Error: The server responded with a non 2xxx status code 

### Expected Behavior

For it to download and not to fail but it seems youtube/google is locking this down

### Actual Behavior

You go to download music for your giant itunes libary (me ) 
and it appears that it just fails with every song 

### Enabled plugins

1. Ad blocker 
2. Album cover theme 
3. Ambient mode
4. Compact side bar
5. Crossfade beta 
6. Disable autoplay
7. Discord rich presence 
8. Downloader
9. In-app menu 
10. Lyrics Genius 
11. Notifications
12. Precise volume

**Comment by pachyderm111** [comment]
![image](https://github.com/user-attachments/assets/86f485a0-eb5d-4906-815c-09ebb8d9e51d)
same here :/

**Comment by MichaeIDeSanta** [comment]
![image](https://github.com/user-attachments/assets/b91b1231-14f8-4a3a-8c05-c89bf571da8b)
same on windows 10 too

**Comment by SamuDifferent** [comment]
![image](https://github.com/user-attachments/assets/35f9a0a2-ca88-4fdd-b62b-9859c604fc6b)
Same on Ubuntu 24.04 LTS

**Comment by codeXXjs** [comment]
It appears to be from the server side. Hopefully there's a fix rolling out soon.

**Comment by 4096Richard** [comment]
> It appears to be from the server side. Hopefully there's a fix rolling out soon.

Thanks

**Comment by AuracleTech** [comment]
In waiting for those who use python you can use this
Not ideal, but its a temporary alternative
```py
import yt_dlp as youtube_dl


def get_video(url, output_path="."):
    ydl_opts = {
        "outtmpl": f"{output_path}/%(artist)s - %(title)s.%(ext)s",
        "format": "bestaudio/best",
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "320",
            }
        ],
        "postprocessor_args": ["-ar", "48000"],
        "prefer_ffmpeg": True,
    }

    try:
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
        print("Download and conversion completed successfully.")
    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    video_url = input("Enter the YouTube video URL: ")
    output_directory = (
        input("Enter the output directory (leave blank for current directory): ") or "."
    )
    get_video(video_url, output_directory)
```

**Comment by AuracleTech** [comment]
because you can manipulate the video from code

**Comment by ArjixWasTaken** [comment]
Well, that is completely pointless since we are not using python for this project.

Heck, we are already using a library to "manipulate" video/audio from code.

**Comment by AuracleTech** [comment]
> Well, that is completely pointless since we are not using python for this project.
> 
> Heck, we are already using a library to "manipulate" video/audio from code.

Like it said it was an alternative for users who wanted to dl while its down, I just shared the script I made myself for my server
The implementation was just a recommendation if possible, if not its whatever

**Comment by ArjixWasTaken** [comment]
if you don't already know, then nowhere
it is meant for people that know how to write scripts/programs

**Comment by Dan-tk** [comment]
> if you don't already know, then nowhere it is meant for people that know how to writ

I just wanted a heads up, because I can't download songs. Also I only know JS, and not python, but I'm learning python

**Comment by neolight1010** [comment]
This issue seems to have been solved in the latest release.

**Comment by AuracleTech** [comment]
> This issue seems to have been solved in the latest release.

Just tested new update, download button doesn't do anything, I click on it and its as if there was no function/action linked to it
DL folder empty too

**Comment by avivi55** [comment]
> This issue seems to have been solved in the latest release.

Still broken.

**Comment by JellyBrick** [comment]
> > This issue seems to have been solved in the latest release.
> 
> Still broken.

@avivi55 Did you try 3.5.1?

**Comment by avivi55** [comment]
> @avivi55 Did you try 3.5.1?

The changelog doesn't mention this issue. 
Just tried it it works. my bad.

nice work :+1:

**Comment by ArjixWasTaken** [comment]
the changelog is automated, and it says to look at the commit history between the previous and the current release for more info

**Comment by 4096Richard** [comment]
Thanks guys needed it for my step dads birthday CD thanks a lot

**Comment by yarik303** [comment]
version 3.6.2.0, the issue is back

**Comment by stutopp** [comment]
Same issue & details as OP in v3.7.1.0 on x86-64 Win11Pro.

**Comment by TheBlackJack22** [comment]
is there any fix yet

**Comment by TheBlackJack22** [comment]
> is there any fix yet for 3.7.1?

Some please explain how i can fix the 2xx status code error.
Happens for any music i attempt to download, I'm crying, please......

**Comment by iserius** [comment]
same result in 3.7.2  mac intel sequoia

<img width="272" alt="Image" src="https://github.com/user-attachments/assets/303ab3f0-13cf-48ac-90e2-236144e34800" />

**Comment by arzezio7** [comment]
Why this thread is closed?? The bug still appears in recent build. smh

**Comment by botcscriptcheck** [comment]
This is definitely still happening. Just tried to download a playlist on Linux and got this madness instead.

![Image](https://github.com/user-attachments/assets/0df0e1ca-65ea-4a12-b6df-b20756532e5f)

**Comment by Grandeception** [comment]
its back again a month later

![Image](https://github.com/user-attachments/assets/7a2144dc-56da-44e1-b47d-047f97bfd456)

**Comment by oyeanu** [comment]
Same issue on intel mac os 15.2 (24C101)

**Comment by n0souls** [comment]
Same on windows 11 (3.8.0.0)

**Comment by Rockyest** [comment]
Same on Windows 10 (3.8.0.0)

**Comment by MrSalehSalem** [comment]
Same on windows 11 Home (3.8.0.0)

**Comment by Gaurav-V28** [comment]
Same here on Arch Linux

**Comment by sh2288** [comment]
**Same on Windows 10 (3.8.0.0) 2025/4/25**

**Comment by WEEZOOKARP** [comment]
Got the same issue today, I'm on latest

**Comment by IfeBusola263** [comment]
Try : Inside innertube.create, pass this player_id : 0004de42

Got this from [here](https://github.com/LuanRT/YouTube.js/issues/1044)
and it worked for me.

**Comment by ArjixWasTaken** [comment]
> Try : Inside innertube.create, pass this player_id : 0004de42
> 
> Got this from [here](https://github.com/LuanRT/YouTube.js/issues/1044) and it worked for me.

https://github.com/pear-devs/pear-desktop/commit/3a7d3ff73de49fcf7e7051dd1bdf450db4b222bf

**Comment by StyxMars** [comment]
This is still an issue, I'm on the latest patch. Windows 11 Pro
