### ISSUE TITLE
[Feature Request]: Barcode or external browser auth token login

### ISSUE THREAD

**Issue by 5andr0** [th-ch/youtube-music#2272]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Even though it's open source I don't feel safe logging into google with my password inside the app

### Proposed Solution

I would prefer to open my default browser and get an auth token or get an 8 character login code for google activate with QR-Code link (like SmartTube)

### Alternatives Considered

-

**Comment by ArjixWasTaken** [comment]
You are asking for too much.
This is an electron wrapper for https://music.youtube.com

We do not have control over the website

**Comment by ArjixWasTaken** [comment]
If this is a dealbreaker for you, then please go use an alternative client.
The level of control we have over the google authentication is zero.

What we could support is maybe importing your cookies from another browser, that way you would login w/o password.
But that wouldn't be any different if you can't trust us.
