### ISSUE TITLE
[Feature Request]: Lil Help

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [th-ch/youtube-music#2286]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I listen to youtube music on desktop and rimusic on my android device the app cant play e rated songs and also doesnt have discord rich presence. 

### Proposed Solution

Is it possible for you to either guide us to implement them in the rimusic app so it would have more featureessss

### Alternatives Considered

Alternative would be we will scape your file XD(JK) 

### Additional Information

Love your work keep going

**Comment by JellyBrick** [comment]
We are not related to the RiMusic team.

**Comment by ALMIGHTY-VC** [comment]
> We are not related to the RiMusic team.

I know but i genuinely want you guys to collab hope so it happens its better to close this till i discuss this matter with the rimusic dev

**Comment by ArjixWasTaken** [comment]
I could help guide the rimusic dev, but I assume it is something they can figure out on their own.

It ain't nice to assume others are incapable of making smth.

So you should first make an issue on their project asking for your features to be added.

If they need help or are busy, feel free to tag me on the issue.
