### ISSUE TITLE
[Bug]: application on invisible screen

### ISSUE THREAD

**Issue by Damianwayne0820** [th-ch/youtube-music#2293]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

v3.4.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

win 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.4.0

### Reproduction steps

https://github.com/user-attachments/assets/a523146f-7b3c-4b90-a4b2-890f278c7aed

https://github.com/user-attachments/assets/79ef7154-f4fb-4496-943a-051d6b0961d9

:( It becomes invisible but the sound is played
(I tried to uninstall and install but it didn't work)

### Expected Behavior

![2024-07-30 130015](https://github.com/user-attachments/assets/3baf0b58-b7c5-415c-a519-d6ee2ae45d8a)
that the image is projected when opening the application

### Actual Behavior

It becomes invisible but the sound is played :C please help me. I tried to uninstall and install but it didn't work

### Enabled plugins

all :c 

### Additional Information

I tried to uninstall and install but it didn't work
Invisible window. Audio playing... before activating some plugins it worked. It doesn't work reinstalling, it's too fluctuating, I tried more versions and the portable/installation version

**Comment by ArjixWasTaken** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/app-runs-off-screen-in-windows-11/47609284-eb59-48f2-82f8-b648a143808f

**Comment by Damianwayne0820** [comment]
ty
