### ISSUE TITLE
[Bug]: Synced lyrics never load

### ISSUE THREAD

**Issue by Bryceed** [th-ch/youtube-music#2295]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11, 23H2 (build 22631.3880)

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable the 'Synced Lyrics' extension
2. Accept the force reload of the app - to apply the changes
3. Play a song
4. Open the lyrics page

### Expected Behavior

Synced lyrics to appears at least with some songs

### Actual Behavior

None of the songs can be load, even having the lyrics in LRCLIB database
![image](https://github.com/user-attachments/assets/4bde9d45-6ebb-4bde-b0ee-2274381f7315)

### Enabled plugins

1. Album actions
2. Compact sidebar
3. Discord Rich Presence
4. Taskbar media control
5. App menu
6. Navigation
7. Skip unliked songs

### Additional Information

I also tried 'Refatch lyrics' button, but the result is the same

**Comment by ArjixWasTaken** [comment]
Just to confirm, did you switch to another song after opening the app?

Currently there is a bug that causes plugins to not detect the already playing song, usually if you re-opened the app with that song paused.

**Comment by ArjixWasTaken** [comment]
Yes they did, see step 2 of the reproduction section

**Comment by Zakalren** [comment]
I had a same problem, but solved after turning off ad blocker extension

**Comment by Reycko** [comment]
@ArjixWasTaken
`Error: Failed to execute 'json' on 'Response': Illegal invocation`

**Comment by HinataNekoNya** [comment]
Bonjour chez moi c'est a peu prés le même problème seulement c'est pire c'est juste tout noir aucun message rien du tout je ne comprend pas.
![Capture d’écran 2024-07-31 175037](https://github.com/user-attachments/assets/7c2c0c24-d9e7-4cb7-9c77-e5f9b6335487)

**Comment by Reycko** [comment]
> I had the same problem, but solved after turning off ad blocker extension

Can confirm

**Comment by Reycko** [comment]
> Bonjour chez moi c'est a peu prés le même problème seulement c'est pire c'est juste tout noir aucun message rien du tout je ne comprend pas. ![Capture d’écran 2024-07-31 175037](https://private-user-images.githubusercontent.com/54217280/353899435-7c2c0c24-d9e7-4cb7-9c77-e5f9b6335487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDEzNzIsIm5iZiI6MTcyMjQ0MTA3MiwicGF0aCI6Ii81NDIxNzI4MC8zNTM4OTk0MzUtN2MyYzBjMjQtZDllNy00Y2I3LTljNzctZTVmOWI2MzM1NDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODYzNmQ1MzAyYmRkZDgzZWZmZTRjMTFlZWIwOGUzMWExYzljZWMyYjE0OGYyMzcxNGVlY2FjZDk0NDQwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws1nUEd6Je1VOnfeXz1c7ByNK139riTlvrfRouvgOlg)

Essaye de desactiver toutes tes extensions sauf celui la

**Comment by HinataNekoNya** [comment]
> > Bonjour chez moi c'est a peu prés le même problème seulement c'est pire c'est juste tout noir aucun message rien du tout je ne comprend pas. ![Capture d’écran 2024-07-31 175037](https://private-user-images.githubusercontent.com/54217280/353899435-7c2c0c24-d9e7-4cb7-9c77-e5f9b6335487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDEzNzIsIm5iZiI6MTcyMjQ0MTA3MiwicGF0aCI6Ii81NDIxNzI4MC8zNTM4OTk0MzUtN2MyYzBjMjQtZDllNy00Y2I3LTljNzctZTVmOWI2MzM1NDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODYzNmQ1MzAyYmRkZDgzZWZmZTRjMTFlZWIwOGUzMWExYzljZWMyYjE0OGYyMzcxNGVlY2FjZDk0NDQwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws1nUEd6Je1VOnfeXz1c7ByNK139riTlvrfRouvgOlg)
> 
> Essaye de desactiver toutes tes extensions sauf celui la, est ce que c'est meilleur?

sa change rien du tout mais je me demande es qu'il serais possible de désinstaller toute l'application et son cache car je l'ai pas installer en version portable mais en version Setup peut-être qu'une reinstallation propre vue que mon Youtube-Music est installer depui presque les 1er versions.

**Comment by Reycko** [comment]
> > > Bonjour chez moi c'est a peu prés le même problème seulement c'est pire c'est juste tout noir aucun message rien du tout je ne comprend pas. ![Capture d’écran 2024-07-31 175037](https://private-user-images.githubusercontent.com/54217280/353899435-7c2c0c24-d9e7-4cb7-9c77-e5f9b6335487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDEzNzIsIm5iZiI6MTcyMjQ0MTA3MiwicGF0aCI6Ii81NDIxNzI4MC8zNTM4OTk0MzUtN2MyYzBjMjQtZDllNy00Y2I3LTljNzctZTVmOWI2MzM1NDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODYzNmQ1MzAyYmRkZDgzZWZmZTRjMTFlZWIwOGUzMWExYzljZWMyYjE0OGYyMzcxNGVlY2FjZDk0NDQwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws1nUEd6Je1VOnfeXz1c7ByNK139riTlvrfRouvgOlg)
> > 
> > 
> > Essaye de désactiver toutes tes extensions sauf celui la, est ce que c'est meilleur?
> 
> sa change rien du tout mais je me demande es qu'il serais possible de désinstaller toute l'application et son cache car je l'ai pas installer en version portable mais en version Setup peut-être qu'une réinstallation propre vue que mon YouTube-Music est installer depuis presque les 1er versions.

Pour reinitialiser le cache de l'application, vous pouvez allez dans Options -> Options Avancés -> Reinitialiser le cache de l'application quand elle redemarre (je n'ai pas verifie le nom traduit en francais, c'est peut etre pas le nom exact) puis faites un rechargement dans Vue.

**Comment by HinataNekoNya** [comment]
> > > > Bonjour chez moi c'est a peu prés le même problème seulement c'est pire c'est juste tout noir aucun message rien du tout je ne comprend pas. ![Capture d’écran 2024-07-31 175037](https://private-user-images.githubusercontent.com/54217280/353899435-7c2c0c24-d9e7-4cb7-9c77-e5f9b6335487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDEzNzIsIm5iZiI6MTcyMjQ0MTA3MiwicGF0aCI6Ii81NDIxNzI4MC8zNTM4OTk0MzUtN2MyYzBjMjQtZDllNy00Y2I3LTljNzctZTVmOWI2MzM1NDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODYzNmQ1MzAyYmRkZDgzZWZmZTRjMTFlZWIwOGUzMWExYzljZWMyYjE0OGYyMzcxNGVlY2FjZDk0NDQwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws1nUEd6Je1VOnfeXz1c7ByNK139riTlvrfRouvgOlg)
> > > 
> > > 
> > > Essaye de désactiver toutes tes extensions sauf celui la, est ce que c'est meilleur?
> > 
> > 
> > sa change rien du tout mais je me demande es qu'il serais possible de désinstaller toute l'application et son cache car je l'ai pas installer en version portable mais en version Setup peut-être qu'une réinstallation propre vue que mon YouTube-Music est installer depuis presque les 1er versions.
> 
> Pour reinitialiser le cache de l'application, vous pouvez allez dans Options -> Options Avancés -> Reinitialiser le cache de l'application quand elle redemarre (je n'ai pas verifie le nom traduit en francais, c'est peut etre pas le nom exact) puis faites un rechargement dans Vue.

Je vient de complétement supprimer l'application et de tout supprimer dans Appdata je te dit si en réinstallent sa change un truc ?

**Comment by Reycko** [comment]
> Je vient de complétement supprimer l'application et de tout supprimer dans Appdata je te dit si en réinstallent sa change un truc ?

L'application est dans `%localappdata%\Programs`, et le cache dans `%appdata%\YouTube Music`

Si vous deinstallez l'application par le panneau de configuration (parametres dans Windows 10 et plus), et que vous supprimez le dossier dans %appdata%, ca devrais retirer toutes les donnes dans le cache. Vous devrez vous reconnecter a votre compte et votre configuration sera reinitialisé

**Comment by HinataNekoNya** [comment]
> > > > > Bonjour chez moi c'est a peu prés le même problème seulement c'est pire c'est juste tout noir aucun message rien du tout je ne comprend pas. ![Capture d’écran 2024-07-31 175037](https://private-user-images.githubusercontent.com/54217280/353899435-7c2c0c24-d9e7-4cb7-9c77-e5f9b6335487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDEzNzIsIm5iZiI6MTcyMjQ0MTA3MiwicGF0aCI6Ii81NDIxNzI4MC8zNTM4OTk0MzUtN2MyYzBjMjQtZDllNy00Y2I3LTljNzctZTVmOWI2MzM1NDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODYzNmQ1MzAyYmRkZDgzZWZmZTRjMTFlZWIwOGUzMWExYzljZWMyYjE0OGYyMzcxNGVlY2FjZDk0NDQwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ws1nUEd6Je1VOnfeXz1c7ByNK139riTlvrfRouvgOlg)
> > > > 
> > > > 
> > > > Essaye de désactiver toutes tes extensions sauf celui la, est ce que c'est meilleur?
> > > 
> > > 
> > > sa change rien du tout mais je me demande es qu'il serais possible de désinstaller toute l'application et son cache car je l'ai pas installer en version portable mais en version Setup peut-être qu'une réinstallation propre vue que mon YouTube-Music est installer depuis presque les 1er versions.
> > 
> > 
> > Pour reinitialiser le cache de l'application, vous pouvez allez dans Options -> Options Avancés -> Reinitialiser le cache de l'application quand elle redemarre (je n'ai pas verifie le nom traduit en francais, c'est peut etre pas le nom exact) puis faites un rechargement dans Vue.
> 
> Je vient de complétement supprimer l'application et de tout supprimer dans Appdata je te dit si en réinstallent sa change un truc ?

C'est toujours pareil même sans être connecter et sans avoir d'autres extension c'est juste tout noir sur la version Setup de l'application.

**Comment by Reycko** [comment]
> C'est toujours pareil même sans être connecter et sans avoir d'autres extension c'est juste tout noir sur la version Setup de l'application.

Avez vous des erreurs dans les DevTools? (ctrl+shift+i ou f12)
Si ca ne marche pas et vous avez la categorie "vue", allez dedans et activez les devtools dans les parametres avances

**Comment by HinataNekoNya** [comment]
> > C'est toujours pareil même sans être connecter et sans avoir d'autres extension c'est juste tout noir sur la version Setup de l'application.
> 
> Avez vous des erreurs dans les DevTools? (ctrl+shift+i ou f12) Si ca ne marche pas et vous avez la categorie "vue", allez dedans et activez les devtools dans les parametres avances

Non mais la sa vient d'apparaitre de manière très étrange et maintenant sa marche sans que je puisse comprendre pourquoi ^^"

**Comment by HinataNekoNya** [comment]
> > > C'est toujours pareil même sans être connecter et sans avoir d'autres extension c'est juste tout noir sur la version Setup de l'application.
> > 
> > 
> > Avez vous des erreurs dans les DevTools? (ctrl+shift+i ou f12) Si ca ne marche pas et vous avez la categorie "vue", allez dedans et activez les devtools dans les parametres avances
> 
> Non mais la sa vient d'apparaitre de manière très étrange et maintenant sa marche sans que je puisse comprendre pourquoi ^^"

J'ai recharger après avoir remis une extension maintenant sa marche plus et j'ai pleins d'erreurs !

**Comment by Reycko** [comment]
> J'ai recharger après avoir remis une extension maintenant sa marche plus et j'ai pleins d'erreurs !

Vous devrais surement signaler un nouveau probleme car celui ci est a propos du plugin Synced Lyrics.

**Comment by HinataNekoNya** [comment]
> > J'ai recharger après avoir remis une extension maintenant sa marche plus et j'ai pleins d'erreurs !
> 
> Vous devrais surement signaler un nouveau probleme car celui ci est a propos du plugin Synced Lyrics.

Ben en fait sa a l'air d'être un probléme entre synsed lyric et "Barre latéral compact"

**Comment by Reycko** [comment]
> Ben en fait sa a l'air d'être un probléme entre synsed lyric et "Barre latéral compact"

Les deux ensemble marchent tres bien pour moi.

**Comment by HinataNekoNya** [comment]
> > Ben en fait sa a l'air d'être un probléme entre synsed lyric et "Barre latéral compact"
> 
> Les deux ensemble marchent tres bien pour moi.

Chez moi c'est des que j'active cette extension qu'il disparait de manière définitive.

**Comment by HinataNekoNya** [comment]
> > > Ben en fait sa a l'air d'être un probléme entre synsed lyric et "Barre latéral compact"
> > 
> > 
> > Les deux ensemble marchent tres bien pour moi.
> 
> Chez moi c'est des que j'active cette extension qu'il disparait de manière définitive.

Sinon pour le reste c'est tout comme vous il faut que je désactive le bloqueur de publicité pour que le plugin marche correctement mais pourquoi c'est en conflit avec se plugin précis chez moi j'en ai malheureusement aucune idée.

**Comment by JasonHorkles** [comment]
I'm also having the issue where it won't show anything at all, even with other extensions disabled. Not sure if it's the exact same issue as the OP's though

**Comment by Dzheremi2** [comment]
I issued the same thing, this plugin conflicts with ad blocker, when i turned it off, everything's work fine.

**Comment by PedroBuffon** [comment]
Can confirm too, ad blocker plugin messes up with the new plugin, idk why it`s related but turning it off and restarting the app makes the new plugin work.

**Comment by faishalirwn** [comment]
changing the blocker mode to ad speedup works too
