### ISSUE TITLE
[Bug]: Downloader not working at all

### ISSUE THREAD

**Issue by Zyanbob** [th-ch/youtube-music#2301]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable downloader

### Expected Behavior

Downloads playlists

### Actual Behavior

The download button in the playlist page does nothing and when i try to use the download option in the plugin i get this:
![Screenshot 2024-08-01 083844](https://github.com/user-attachments/assets/b6cc8cd6-4429-484e-a433-6ab380480d29)

### Enabled plugins

1. Ad blocker
2. Album color Theme
3. Caption selector 
4. Discord Rich Presence
5. Downloader
6. In-App Menu
7. Genius Lyrics
8. Navigation
9. Scrobbler
10. Sponsor Block
11. Taskbar Media Control
12. Video Quality Changer

**Comment by KcTec90** [comment]
Well, is your playlist public like it says? If so, then send the link and I should be able to view it. If I can't view it, then it is private.

**Comment by Zyanbob** [comment]
https://music.youtube.com/playlist?list=PL_UerZgCzqagaRsH5gi98y8168MqR704Y&si=fd0_Y-c1TMvRx8zT

**Comment by Techconix** [comment]
I created a copy of the playlist by clicking the three dots, save to playlist, and then creating a new playlist to copy it. But now the download button doesn't anything so that's as far as I can get

**Comment by ArjixWasTaken** [comment]
> I created a copy of the playlist by clicking the three dots, save to playlist, and then creating a new playlist to copy it. But now the download button doesn't anything so that's as far as I can get

Is that playlist by any chance private?

**Comment by Zyanbob** [comment]
is this just going to loop?

**Comment by Zyanbob** [comment]
downloader doesn't work > person 2 asks persons 1 "is the playlist private?" > person 1 gives person 2 the playlist > person 2 makes a copy and runs into the same problems > person 3 ask person 2 "is the playlist private". the cycle repeats until we runout of people who care about this app

**Comment by ArjixWasTaken** [comment]
Looks like youtube did some changes and broke a dependency we are using to handle the downloads.
That dependency appears to have a fix available, but has not released a new version, so we can't use it yet.

**Comment by Zyanbob** [comment]
like the one released 3 minutes ago?
https://github.com/LuanRT/YouTube.js/releases/tag/v10.3.0

**Comment by ArjixWasTaken** [comment]
most likely
