### ISSUE TITLE
[Bug]: Lyrics don't load if sync lyrics enabled

### ISSUE THREAD

**Issue by pdario** [th-ch/youtube-music#2310]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.4.x

### Reproduction steps

Enable sync lyrics

### Expected Behavior

See lyrics

### Actual Behavior

![image](https://github.com/user-attachments/assets/a1d76c08-bcdf-4414-bf1f-df131b3ab743)

### Enabled plugins

Various

**Comment by ArjixWasTaken** [comment]
Why did I close this you may ask?
Because you gave literally no fucking info, great, lemme start reading minds.

There are many similar issues that have been resolved, but how can I know if this is one of them?

**Comment by ArjixWasTaken** [comment]
Spend some more effort on your description and I will re-open this.

**Comment by pdario** [comment]
Whoa! What a reaction! Keep calm and politely ask for the information you need.
I updated to v 3.5.1, enabled sync lyrics plugin and now I see as in the screenshot. What do you need more??

**Comment by JellyBrick** [comment]
Please respect each other's opinions and keep the conversation polite...

**Comment by pdario** [comment]
Still I can't understand why this is "not planned" and "invalid" @JellyBrick

**Comment by ArjixWasTaken** [comment]
> Whoa! What a reaction! Keep calm and politely ask for the information you need.
> I updated to v 3.5.1, enabled sync lyrics plugin and now I see as in the screenshot. What do you need more??

It ain't my job to ask for info, if you want to file an issue/bug report, then provide as much info as you can.

A very very very similar issue was already reported earlier and it got resolved, how can I know if this is related to that or a completely new issue?

I do not believe that I was rude from the way I talked, the only rude part would be closing your issue before getting the details that were left out.

What I did was express frustration and close your issue for being invalid.

What is an invalid issue? It is an issue that gives no useful information.

**Comment by ArjixWasTaken** [comment]
Why was I frustrated you may ask?

Well, the only thing you can achieve by not giving details is waste our time.

I value my time as it ain't a lot.

**Comment by ArjixWasTaken** [comment]
Your config would be a good place to start
Enabled plugins, their settings, etc

**Comment by ArjixWasTaken** [comment]
A title describing the issue would also be nice

**Comment by pdario** [comment]
I'm sorry I didn't see I missed the bug's title; I added it now.

Enabled plugins:
Adblocker / Blocker In-App
Ambient mode
Audio compressor
Dowloader
Exponential volume
In-App Menu
Lyrics Genius
Navigation
Notifications
PlaybackSpeed
Precise Volume
Shortcuts
Skip Disliked Songs
Skip Silences
Synced Lyrics
Taskbar Media Control
Tuna OBS

**Comment by ArjixWasTaken** [comment]
> And for the same reason again, I don't agree it's not your job to ask for clarifications about a bug report.

asking for clarifications is indeed my job, but I do not consider it a clarification if there is nothing to clarify

**Comment by ArjixWasTaken** [comment]
(I hid the off-topic comments to make this thread easier to manage)

**Comment by 7ih** [comment]
I have the same issue. This should fix it: https://github.com/th-ch/youtube-music/pull/2318 (fixes undefined album name when searching for lyrics)
