### ISSUE TITLE
[Feature Request]: Show original lyrics if no lyrics on LRCLIB

### ISSUE THREAD

**Issue by sxxeun09** [th-ch/youtube-music#2316]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, when a song has no synced lyrics available on LRCLIB, the app displays a "⚠️ - No lyrics found for this song." message. This affects songs that previously displayed original from musixmatch, etc.... This change has reduced the usability for songs without synced lyrics.

Before:
![image](https://github.com/user-attachments/assets/d73cd99a-85e4-4b86-ac2d-3d2b52456cd7)

After:
![image](https://github.com/user-attachments/assets/2bff34c6-928c-4006-a194-42f1356588a8)

LIBLRC:
![image](https://github.com/user-attachments/assets/925878c2-e56d-4e00-a681-20ee0f5d14e0)

### Proposed Solution

If no synced lyrics are found on LRCLIB, fallback to displaying the original. This ensures that users can still see the lyrics even if synced versions are unavailable.

### Alternatives Considered

Manual Syncing: Allow users to manually search on LRCLIB and another lyrics platforms.

**Comment by ArjixWasTaken** [comment]
I don't know if I should close this issue or not.
You see, multiple lyric sources are on my TODO list for this plugin.

They were there from the start (see dead PR for refined-lyrics)

**Comment by ArjixWasTaken** [comment]
I guess I can keep it open as a tracking issue

**Comment by azzimihr** [comment]
any progress on this? wouldnt even be an issue if synced lyrics didnt require a restart

**Comment by ArjixWasTaken** [comment]
> any progress on this? wouldnt even be an issue if synced lyrics didnt require a restart

Blocked by https://github.com/th-ch/youtube-music/pull/2383

**Comment by ArjixWasTaken** [comment]
this should be safe to close, as the "original lyrics" are now a provider we support
