### ISSUE TITLE
[Bug]: Song duration left doesn't show up anymore in Discord Rich Presence

### ISSUE THREAD

**Issue by skigulz** [th-ch/youtube-music#2320]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.4.1

### Reproduction steps

Enabling the Discord Rich Presence plugin.
"Hide duration left" is left unchecked, it's not enabled.
The song duration left doesn't appear in the Discord Rich Presence.

### Expected Behavior

When listening to a song in YouTube Music, the song duration left should appear in Discord Rich Presence when "Hide duration left" is not enabled. It used to work normally in the previous version (3.4.1) I used before updating.

### Actual Behavior

The song duration left doesn't show up anymore in Discord Rich Presence.

### Enabled plugins

Ambient Mode
Discord Rich Presence
Exponential Volume
In-App Menu
Navigation
Precise Volume
Scrobbler
Shortcuts
Video Toggle

**Comment by Reycko** [comment]
![image](https://github.com/user-attachments/assets/9075000e-5c17-40f8-ab0b-b8a438cb7d7d)

Are you sure you didn't check this?

**Comment by skigulz** [comment]
![YTM](https://github.com/user-attachments/assets/85c3348f-4ced-49fd-b323-80818d327bcc)

Yes, 100% sure...
I even tried enabling it, then disabling it again, no effect.

**Comment by Crul0** [comment]
Same thing happens to me I've reset my config and everything it just doesn't work anymore

**Comment by satetbr** [comment]
After the update, the presence shows as 'listening'... this mode of presence cannot display the timestamp... to show it, the 'playing' mode is needed.

The dev of Discord Presence needs to change this.

**Comment by JellyBrick** [comment]
> After the update, the presence shows as 'listening'... this mode of presence cannot display the timestamp... to show it, the 'playing' mode is needed.
> 
> The dev of Discord Presence needs to change this.

#1588 #2052 😅

**Comment by KaanAlper** [comment]
guys my discord rich presence not works too, it doesnt pop up on discord anymore
![image](https://github.com/user-attachments/assets/f081e057-e770-4376-8145-0d7f593c3180)
![image](https://github.com/user-attachments/assets/c96f3f26-cb33-4e09-a5b1-a795ee0926be)

**Comment by DereC4** [comment]
Same thing happens here

**Comment by SixSiege** [comment]
![image](https://github.com/user-attachments/assets/870cca81-8d07-472e-b9ca-8081fb1d6a64)
So apparently, Discord has fixed the issue. 
Using the latest version of youtube-music v3.5.1

**Comment by DereC4** [comment]
w!

**Comment by DereC4** [comment]
> ![image](https://private-user-images.githubusercontent.com/62742128/367567792-870cca81-8d07-472e-b9ca-8081fb1d6a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTAwNzQsIm5iZiI6MTcyNjM4OTc3NCwicGF0aCI6Ii82Mjc0MjEyOC8zNjc1Njc3OTItODcwY2NhODEtOGQwNy00NzJlLWI5Y2EtODA4MWZiMWQ2YTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA4NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NzEwY2EyODliMWFiYTkzY2U1ZDExNGU2NDdmM2NiY2MzNjg2ZTMxOTA4NGI2ZTA1ZGM2ZTY1ZWY2YzhlMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7b2DiMlQbeGqfWOcsBr5rwoHv-ZnTHRa7JaNVZGJAZw) So apparently, Discord has fixed the issue. Using the latest version of youtube-music v3.5.1

thanks for the update! Now I can enjoy my high class music with everyone knowing how far into it I am!
![image](https://github.com/user-attachments/assets/d1a09972-556c-4c68-b524-13f3a79c8d23)
