### ISSUE TITLE
[Feature Request]: Playback buttons on the taskbar icon.

### ISSUE THREAD

**Issue by TheArgentinian** [th-ch/youtube-music#2330]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Like the ones on the Spotify app

### Proposed Solution

![image](https://github.com/user-attachments/assets/1e09fd65-2b48-4887-89b0-9551c4e1e8b7)

### Alternatives Considered

.

**Comment by ArjixWasTaken** [comment]
Duplicate issue

Search the issue tracker, I won't link it as I am too lazy to find it.

But it is definitely a duplicate.

**Comment by JellyBrick** [comment]
Already implemented.
Use the "Taskbar Media Control" plugin.

**Comment by TheArgentinian** [comment]
> Already implemented.

So you're closing issues as "not planned" without even knowing they are already implemented, "collaborator"?

**Comment by ArjixWasTaken** [comment]
I already knew they are implemented, and I already knew that this was a duplicate issue.

**Comment by ArjixWasTaken** [comment]
> I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) for a feature request that matches the one I want to file, without success.

Did you check that checkbox w/o searching the issue tracker, dear "issuer"?

**Comment by ArjixWasTaken** [comment]
you were too lazy to search the issue tracker, you lied, you don't deserve any courtesy

**Comment by ArjixWasTaken** [comment]
I was an asshole, nothing to admit, you still did not do the due diligence of searching the issue tracker.

**Comment by ArjixWasTaken** [comment]
here is the original issue, that you did not find "without success"

https://github.com/th-ch/youtube-music/issues/107

**Comment by ArjixWasTaken** [comment]
why do you think we have that checkbox asking you to find an existing issue first?

**Comment by ArjixWasTaken** [comment]
do I feel proud about that?

when dealing with low effort issues like these? yes
when dealing with actual issues? I feel ashamed

**Comment by ArjixWasTaken** [comment]
let me remind you that you were the one to attack me first, I wasn't rude or anything initially
I simply let you know that what you are asking for is a duplicate issue

since I was on github mobile I didn't want to search for the exact issue because it is harder on the mobile app

**Comment by ArjixWasTaken** [comment]
this is a screenshot from the README of this repository
![image](https://github.com/user-attachments/assets/e76da6aa-f7a5-4fbe-9b3c-b00cf46d5f82)

you did not spend any effort looking there

**Comment by ArjixWasTaken** [comment]
> I didn't attack anyone. I called a spade a spade. Stop trying to cover your ass now. It's embarrassing. And too late.

I am not trying to cover my ass, I am trying to call you an asshole

**Comment by Su-Yong** [comment]
I'm not a paid employee. and he also. We should talk to each other politely. Regardless of who was rude first, I apologize. But that doesn't mean you are right. Obviously, you attacked him first, and he just wanted to get it right. I don't want to mess this conversation. If you comment one more time, I'll be lock the conversation

**Comment by JellyBrick** [comment]
## Enough with the pointless debate, please.

I apologize on behalf of the team for any offensive language. 
**BUT**

> > Duplicate issue
> > Search the issue tracker, I won't link it as I am too lazy to find it.
> > But it is definitely a duplicate.
> 
> So you're closing issues as "not planned" without even knowing they are already implemented, "collaborator"?

First, you didn't read the question carefully enough. 
![IMG_0807](https://github.com/user-attachments/assets/01f17f98-daac-4f42-89b4-f902031ec88e)
Second, you didn't admit you were at fault and were rude to the other person.

Further pointless debate is not worthwhile, so I'll lock this issue.

**Comment by JellyBrick** [comment]
**And once again, this is a community space for everyone. Please be polite and respectful.**
