### ISSUE TITLE
[Feature Request]: (Synced Lyrics) Option to disable album_name in LRCLIB request

### ISSUE THREAD

**Issue by Dzheremi2** [th-ch/youtube-music#2331]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In some situations, if track has Unicode characters in the album name, it wouldn't parse correctly.

### Proposed Solution

Add option to disable album name in LRCLIB request.

### Alternatives Considered

None

**Comment by 7ih** [comment]
https://github.com/th-ch/youtube-music/pull/2343 will disregard album name if its undefined
