### ISSUE TITLE
Moving youtube music to HDD

### ISSUE THREAD

**Issue by thijsi123** [th-ch/youtube-music#234]
Hello,

I was wondering if it was possible to move the youtube music roaming and root folders to my second HDD.
or move the roaming folder with the config.json so I can have 2 installations with different configs.

**Comment by Araxeus** [comment]
If you want to manually fix the problem:
Clone the repo, open package.json
https://github.com/th-ch/youtube-music/blob/61e7124516571a63c7155937e827ba95dc34b9cb/package.json#L27-L29
Add here
  "allowToChangeInstallationDirectory": true,

and then build with yarn

**Comment by thijsi123** [comment]
Thank you.

**Comment by thijsi123** [comment]
I keep getting the rimraf' is not recognized as an internal or external command
any fix?

**Comment by thijsi123** [comment]
or am I doing something wrong I do ctr+l in the youtube folder then yarn build and this happens.

**Comment by Araxeus** [comment]
run `yarn` / `yarn install` in project folder to download all dependecies
and then `yarn build:win` when its finished

**Comment by thijsi123** [comment]
Thanks.

**Comment by thijsi123** [comment]
when doing yarn install I get error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
I am not a coder myself and I don't understand all this do you know what could be the problem?

**Comment by thijsi123** [comment]
i fixed it
