### ISSUE TITLE
[Bug]: Minimize, Maximize, Close buttons do not follow Color Theme

### ISSUE THREAD

**Issue by thesaikis** [th-ch/youtube-music#2365]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Linux arch 6.10.6-arch1-1

### What CPU architecture are you using?

x64

### Reproduction steps

1. Install from [youtube-music-bin](https://aur.archlinux.org/packages/youtube-music-bin) AUR.
2. Enable "In-App Menu" from plugins, which removes the title bar.
3. (Optional) Enable "Album Color Theme" which emphasizes the issue.

### Expected Behavior

The minimize, maximize, and close buttons follow the color scheme of the application.

### Actual Behavior

The minimize, maximize, and close buttons always remain the same color.

### Enabled plugins

1. In-App Menu
2. (Optional) Album Color Theme

### Additional Information

I am using the KDE Plasma desktop environment. Changing the theme of KDE (changing from light to dark theme) affects the buttons, but only the three I've mentioned and nothing else.

Besides simply changing from light to dark in the settings of KDE, I've left any other themes or config files untouched.

In fact, rather than just being the wrong color, the buttons appear to be different entirely from what the application actually shows in the screenshots. Using the "Album Color Theme" plugin isn't necessary to cause the issue, but makes it easier to see the buttons are incorrect.

Here are a few images where the color theme changes but the buttons remain the same:
![image](https://github.com/user-attachments/assets/f5889912-38f6-4a2d-9676-d3a159404767)
![image](https://github.com/user-attachments/assets/1a134162-5920-4531-ba48-e1129a3a221a)
![image](https://github.com/user-attachments/assets/c37cc468-75bb-4f34-8b23-9271dcb098a2)

**Comment by ArjixWasTaken** [comment]
> In fact, rather than just being the wrong color, the buttons appear to be different entirely from what the application actually shows in the screenshots.

I believe the screenshots (of the README) were taken on Windows 10/11
I myself am on windows 11, and I do not experience this issue.

![image](https://github.com/user-attachments/assets/b0c185c8-7103-4dd0-8577-5084400f0e7e)
![image](https://github.com/user-attachments/assets/f0df7c88-c3ab-46a6-a19e-cc89b0772d3c)

So this appears to be a platform issue.

**Comment by ArjixWasTaken** [comment]
are KDE and youtube-music running under wayland?
do you have custom KDE window decorations?
etc

**Comment by Rairof** [comment]
![image](https://github.com/user-attachments/assets/c5d5eebd-9d5f-483c-9c0d-9ac4e180e783)
I can confirm they work on win 11, it works on my end as well

**Comment by thesaikis** [comment]
> are KDE and youtube-music running under wayland?

KDE is running under Wayland, youtube-music opens under XWayland by default. Running KDE under X11, or forcing youtube-music to run under Wayland still experiences this issue.

In terms of window decorations, I do believe KDE's settings might have something to do with this. If I swap between light or dark mode, it changes the colors of the buttons. However, the style (i.e. the icons) of the buttons don't match anything that's available under KDE customization.

To reiterate, I haven't touched any customization settings besides light/dark mode.

Other electron applications, such as Obsidian, retain their own unique minimize/maximize/close buttons in the absence of a title bar. This application is the only one I experience these problems with.

One thing I noticed is that the minimize/maximize/close buttons in youtube-music are actually identical to [chromium](https://archlinux.org/packages/extra/x86_64/chromium/) (official repo). Besides having the same color, and same icons, they have the same animations. I haven't tried to customize chromium at all, either. I had chromium already installed prior to youtube-music. Maybe there's some sort of overlap happening here?

Image for reference:
![image](https://github.com/user-attachments/assets/5d5c5e94-1d0a-4fbe-9ecd-35f1f70c24e6)

**Comment by ArjixWasTaken** [comment]
I think chromium only supports gtk themes.
We might have to play around with the launch flags.

I'll install Arch Linux tomorrow and check.

**Comment by thesaikis** [comment]
I think I've narrowed down the problem somewhat.

I had initially assumed the buttons were replaced/altered, but after opening devtools I can see that the buttons from chromium are just being overlayed on top of the application. 

Here you can see the expected buttons present to the left of the panel and the extra set of buttons remain in the top right:
![image](https://github.com/user-attachments/assets/65973756-36d5-4159-9f5b-fd2f1fa6b9b9)

I'm still not sure what would cause this. I tried searching for something similar in the existing issues but didn't find anything.

**Comment by thesaikis** [comment]
I run arch on my own hardware but tested out a new install in two new VM, one with Plasma/KDE and one with GNOME. Right after finishing install, I just went and installed youtube-music.

Both still had this issue on a fresh install.

> I'll install Arch Linux tomorrow and check.

Looking forward to your results!

**Comment by ArjixWasTaken** [comment]
I could reproduce this, and thankfully there is a fix for it.

I'll shortly make a PR.
