### ISSUE TITLE
[Feature Request]: Lyrics synchronization plugin

### ISSUE THREAD

**Issue by alperyuceer** [th-ch/youtube-music#2368]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, the plugin in the app cannot find or synchronize all lyrics. The chrome plugin I have linked below can do this without any problems. If you can add this to the application, you will please both me and other users. Thank you.

### Proposed Solution

[Better Lyrics Chrome Extension](https://chromewebstore.google.com/detail/better-lyrics-lyrics-for/effdbpeggelllpfkjppbokhmmiinhlmg)

### Alternatives Considered

Only this plugin will solve the whole problem.

**Comment by ArjixWasTaken** [comment]
Nope

**Comment by ArjixWasTaken** [comment]
Also, electron is not great at loading chrome extensions.
What you proposed would most likely not work.

**Comment by JellyBrick** [comment]
We already have `synced-lyrics` plugin.
