### ISSUE TITLE
Discord Plugin Non Functional

### ISSUE THREAD

**Issue by psyight** [th-ch/youtube-music#237]
Did a full restart of both youtube music and discord. Attempted to manually add youtube music as a game activity. Rich prescence did not how up before and after each action. [](url)
![no work lol](https://user-images.githubusercontent.com/22730639/115634694-1c844c00-a2d8-11eb-9b23-e678155aeac8.png)

**Comment by Araxeus** [comment]
#208 I have the same problem. 
also im pretty sure the error code you see is because of adblock or some other plugin and probably has nothing to do with the discord problem

**Comment by psyight** [comment]
That's what I figured for error messages. Removing custom statuses didn't solve it for me.

**Comment by psyight** [comment]
This may be due to a lack of code knowledge but I believe that perhaps the discord is simply not starting up at all. I've added a few console.log() but none of them have triggered in the devtools console window. For this reason I'm believing that either the plugin's javascript file either can't be compiled or the client is simply not running the js file.

**Comment by Araxeus** [comment]
@psyight I don't really understand what did you test, 
but I can tell you that logging from back.js will log to the terminal the program was launched from, and not in devtools console (electron main process vs renderer process)

Anyways from what i've tested on my pc, the plugin supposedly works, connects to `discordRPC` without throwing an error
and `setActivity()` promise on that RPC return `promise fulfilled`

**Comment by psyight** [comment]
I was just testing that the plugin started up except what you've just told me means my tests were entirely useless. However, I did somehow fix it. I've tried a lot of things, but I'd just list the most important two in the case that one helps. (Message me at biggy#4444)
1. Try running a standalone RPC script
2. Run the discord-rpc example script

**Comment by Araxeus** [comment]
@psyight first of all, idk what the username u sent is. looks like discord but can't find you there
I would love more info on how you fixed it on your end. what outside method did you do?
what standalone RPC script did you talk about?

Thanks
