### ISSUE TITLE
[Feature Request]: Add a integration server to control the app by websocket

### ISSUE THREAD

**Issue by PedroZamecki** [th-ch/youtube-music#2387]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [ ] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I wanted a websocket controller for the app, I've searched for the web for a twitch song request for youtube and found this streamer bot extension: [extension link](https://extensions.streamer.bot/t/youtube-music-requests-and-controls/822)
This need another youtube music app, from this [repo (ytmdesktop)](https://github.com/ytmdesktop/ytmdesktop) and I even thought it was a youtube thing, but it seems to be from their repo (and app).
I thought this might be doable by the plugins, but I'm not quite sure.

### Proposed Solution

Add a plugin with this configuration to make websocket connections and make it control the app by it.

### Alternatives Considered

A propper connection with twitch/youtube chat to make a song request that controls the app

**Comment by ArjixWasTaken** [comment]
Wow, someone that didn't lie about checking the issue tracker.
That's a first.

**Comment by ArjixWasTaken** [comment]
A pull request is already open that does exactly what you want.

https://github.com/th-ch/youtube-music/pull/1909

**Comment by ArjixWasTaken** [comment]
Not really a websocket but an actual http server, but oh well, tomato tommato

**Comment by PedroZamecki** [comment]
Thanks for the response! 
I didn't lie because I searched for some keywords but I saw something related.
The thing is I didn't had much time for looking into this (there were some many issues!), sorry for bothering!

**Comment by ArjixWasTaken** [comment]
This wasn't a bother at all!
It was actually kind of refreshing to see an issuer not lie when making an issue like this!

**Comment by PedroZamecki** [comment]
Just a question, I might just bother a little more:
Is it planned for a dynamic plugin folder? I think this would be possible, no? Just asking

**Comment by ArjixWasTaken** [comment]
Are you asking if we are planning to allow loading third-party plugins?

**Comment by PedroZamecki** [comment]
Yeah, kinda

**Comment by PedroZamecki** [comment]
At least I didn't saw all the repo, but I think this is not allowed at the moment, right?

**Comment by ArjixWasTaken** [comment]
yeah you can't load third party code

**Comment by PedroZamecki** [comment]
Do you think that's a valid ideia? Can this be possibly worked on?

**Comment by ArjixWasTaken** [comment]
I am conflicted.

Would I like that feature? Yes.
Would it be easy to implement correctly? Tough question.

One solution would be to only allow renderer plugins to be sideloaded;
So the plugin would not have access to your computer, but only the website of `music.youtube.com`.

There is a lot of thought that must go into this if we want third party plugins.
Make an issue for it!

**Comment by PedroZamecki** [comment]
Ok! I think this might be a good ideia!
About the security I think that this could be kind of a problem... What does other apps do as a solution? Things like vencord and others? Well, I will open an issue. I asked this because this could be a quick solution for this issue, you know!
Thanks!
