### ISSUE TITLE
[Bug]: Music Together not working

### ISSUE THREAD

**Issue by ranuthishere** [th-ch/youtube-music#2407]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.2.0

### Checklists

- [x] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

Join a music together session with another user

### Expected Behavior

Would work as how the plugin was intended 

### Actual Behavior

Endless spinning gear OR has the UI with the parties and stuff but you are alone with no images loading

![image](https://github.com/user-attachments/assets/fb881990-87a1-45b2-a119-75b2a1062366)

### Enabled plugins

Only Music together

**Comment by JellyBrick** [comment]
Check your network settings (e.g., firewall) to make sure WebRTC is allowed.
