### ISSUE TITLE
Auto-unpause

### ISSUE THREAD

**Issue by robinhugy** [th-ch/youtube-music#241]
Music stops after time and need to unpause it.
Can we get a disable auto pause feature like in "AutoTube - YouTube nonstop" (chrome extension)?

Thanks for your work!

**Comment by Araxeus** [comment]
There is already a plugin that does exactly that.
Enable `auto-confirm-when-paused`

**Comment by robinhugy** [comment]
Oh i dont see it before.
Thanks!
