### ISSUE TITLE
How to upload lyrics 

### ISSUE THREAD

**Issue by duckaleuze** [th-ch/youtube-music#2412]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

A lot of my favorite music doesn't have lyrics because it's not very well known since my country is small.

### Proposed Solution

I would really like to be able to contribute, but I don't understand how to do it, I searched about 'LRCLIB' but I didn't find how to upload lyrics. I'm dumb and this is probably very silly, sorry.

### Alternatives Considered

I am happy to contribute in any way I can

**Comment by ArjixWasTaken** [comment]
lrclib is not user friendly, there is no user interface for uploading lyrics
you have to make a POST request to their api, which can be done via Postman/Insomnia or simple code

**Comment by ArjixWasTaken** [comment]
https://lrclib.net/docs

![image](https://github.com/user-attachments/assets/2e6b9cce-cdce-4e75-9e0f-0eb7b4af21bb)

**Comment by ArjixWasTaken** [comment]
Update: Apparently you can "publish" lyrics using lrcget, a client for lrclib.

https://github.com/tranxuanthang/lrcget

**Comment by ArjixWasTaken** [comment]
Anyways, this really has nothing to do with youtube music, you should have opened an issue over at https://github.com/tranxuanthang/lrclib

**Comment by duckaleuze** [comment]
sorry for asking this here, I don't understand very well how your app works in terms of lyrics but this is very helpful, thanks! Youtube-music is one of the best music apps out there, keep it up :3
