### ISSUE TITLE
[Feature Request]: Spatial Stereo on macOS

### ISSUE THREAD

**Issue by ismailtilki** [th-ch/youtube-music#2413]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The App is not capable to use the feature "Spatialize Stereo" on macOS

### Proposed Solution

Integrate Apple Spatial API: https://developer.apple.com/documentation/realitykit/spatialaudiocomponent

### Alternatives Considered

alternative solution is to use the official youtube music site on safari

**Comment by ArjixWasTaken** [comment]
does chrome on macOS use "SpatialAudio" for `music.youtube.com`?

**Comment by dfldylan** [comment]
> does chrome on macOS use "SpatialAudio" for `music.youtube.com`?

maybe not ?

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/36db5d61-f529-474d-af6f-daee309f755a">

**Comment by deepchandra02** [comment]
so what happened to this feature request?
