### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Big-PLonk** [th-ch/youtube-music#2417]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11  Version 23H2 (OS Build 22631.4169

### What CPU architecture are you using?

x64

### Reproduction steps

I'm not sure but it may be related to having a lot of downloads

### Expected Behavior

The app run for more than 10 seconds without completely freezing

### Actual Behavior

I'm not sure exactly how long it takes but about 10 to 12 seconds after opening the app it completely freezes

### Enabled plugins

I can't even check what plugins I have enabled

### Additional Information

It may be related to downloads because I am completely unable to press the downloads button in my library even before the app freezes and my default web version of YTM was lagging until I cleared the downloads

I have tried uninstalling and reinstalling, as well as trying to use the portable version but they all seem to hold my preferences so I can't check if it is something I have enabled

**Comment by ArjixWasTaken** [comment]
Since this is possibly a yt web issue, and you tried uninstalling w/o deleting your user data folder, how about trying that again?

We store your data in AppData/Roaming (and/or AppData/Local)

I am on my mobile so I can't check right now, but there should be a folder named `Youtube Music` or something along those lines.

If you uninstall YouTube music and delete any left over folders, it should fully reset your preferences.

**Comment by Big-PLonk** [comment]
Thank you for your response
I deleted all the files I found relating to YTM and it appears to be working perfectly
