### ISSUE TITLE
Add right click support and multi-windows support

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#242]
Can be useful add functions (ex. download music, open in a new window) from right click.
For multi-windows support, this is currently available, but it's hidden: you need to use a mouse and click to the scroll ball, it's between right and left click, (when hover a link).

**Comment by JellyBrick** [comment]
Could you please separate these issues into two issues?

**Comment by Bellisario** [comment]
Hello, just done! #1266.

I didn't open an issue for right-click context-menu as the downloader seems to support it now.

Closing this old issue.
