### ISSUE TITLE
[Bug]: No discord activity 

### ISSUE THREAD

**Issue by Xoteka** [th-ch/youtube-music#2427]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable the plugin "Discord activity"
2. Thats it, it isnt working

### Expected Behavior

I think after enabling this plugin, it must show my discord activity. If i need to do smth else to make it work, please give me a guide how to set up it. I use Vencord

### Actual Behavior

After enabling plugin nothing happens

### Enabled plugins

1. Discord Activity
2. Bypass age restriction
3. Exponental volume
4. In app menu
5. Music Together
6. Navigation

### Additional Information

So i cant find any guide how to set up it properly, mb i need to check some rich presence plugins, but idk. I belive that this function is not working at all

**Comment by ArjixWasTaken** [comment]
Do you have game activities enabled in discord's settings?

**Comment by Xoteka** [comment]
![image](https://github.com/user-attachments/assets/e529723e-d184-4204-b0fb-f61d35db746b)
It is turned on, but not working, my activities are enabled as well

**Comment by XxTHKxX** [comment]
Yea, I'm experiencing this as well, I do not see the activity shown in my profile, both the setting on discord and on the app is enabled

**Comment by RaylSs** [comment]
> Yea, I'm experiencing this as well, I do not see the activity shown in my profile, both the setting on discord and on the app is enabled



> ![image](https://private-user-images.githubusercontent.com/75161593/369605916-e529723e-d184-4204-b0fb-f61d35db746b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzkwMzUsIm5iZiI6MTcyNzM3ODczNSwicGF0aCI6Ii83NTE2MTU5My8zNjk2MDU5MTYtZTUyOTcyM2UtZDE4NC00MjA0LWIwZmItZjYxZDM1ZGI3NDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE5MjUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjkyMzNiOGVjMjliYTlhMTY3MDY4YjY0N2YxNjAyYWY5ZDEyMTY0YWFkZDc5MGZmYTg3ZGQ1OWExZTgwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MWozhIeFWfBdyNCu-tCiA2Hro-d2UnYHxagPfqnJce4) It is turned on, but not working, my activities are enabled as well

If you are running programs that affect the network in any way, try to terminate them completely and then restart ytm. Then run whatever you want. In my case the problem was due to radmin vpn I think, hope this helps someone . ^ .

**Comment by kevindevm** [comment]
i had the same error show connected and enabled, and even when i clicked enabled didn't change the "enabled" i fix it editing the config.json, there it showed that i had it disabled

**Comment by i6c** [comment]
the above works, also you can go to registered games and simply make sure it is registered thats how i fixed mine, after confirming it was enabled in cfg

**Comment by tam013001** [comment]
> It's called `Discord Rich Presence`, please check if you have this plugin enabled ![image](https://private-user-images.githubusercontent.com/107706560/369599986-dfbaf4f1-55eb-4ce2-b890-25d4b87a0a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjEwOTIsIm5iZiI6MTcyOTY2MDc5MiwicGF0aCI6Ii8xMDc3MDY1NjAvMzY5NTk5OTg2LWRmYmFmNGYxLTU1ZWItNGNlMi1iODkwLTI1ZDRiODdhMGE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwNTE5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmMzOGMzMGE5MjMwMTliN2MwYTQyYjcxYThkNjA4ZTExOWFhMzUwZWM2MzkzOTFlMzIxODRiZmFkNWZjODI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e3yC7cCvd_sw4dT8WdHI6KJ9ip1O8imyQVu5x7SAkx4)
> 
> It's working for me in v3.5.2 update PC- ![image](https://private-user-images.githubusercontent.com/107706560/369599781-a7fe4615-92e0-4a85-a7fc-514d2a14ee6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjEwOTIsIm5iZiI6MTcyOTY2MDc5MiwicGF0aCI6Ii8xMDc3MDY1NjAvMzY5NTk5NzgxLWE3ZmU0NjE1LTkyZTAtNGE4NS1hN2ZjLTUxNGQyYTE0ZWU2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwNTE5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTUyZGYxMDBjZjlhOTJmMWYzZjYzM2RkN2MxMGRlYjhiMmI0MTIyOTZjNDlkNjQ4MzJmZDA0MmVmMTE5YjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wGbwtz9oaLdgKzcFIoJ53g3tY1RE9SEJ1aZQqoKc1XU) Mobile- ![Screenshot_20240921-163238_Discord](https://private-user-images.githubusercontent.com/107706560/369600347-c01668ef-db8a-4e1b-83fe-44cba012fc5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjEwOTIsIm5iZiI6MTcyOTY2MDc5MiwicGF0aCI6Ii8xMDc3MDY1NjAvMzY5NjAwMzQ3LWMwMTY2OGVmLWRiOGEtNGUxYi04M2ZlLTQ0Y2JhMDEyZmM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwNTE5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTIwM2NlYzE3NThmNTg5OTkzNmEwZjkxOTBjNWQwYjY5MDM3OGNmOTExM2Y4MjQ1MjQ5M2ViZjc4NmEwYWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h22idVMIpb7g5NEOdw81oefvjOQPUxCpVLOofqWO9Bk)
> 
> It shouldn't matter if you use vencord or just official discord, it should just work regardless

How are you able to integrate this option on mobile? I have ReVanced, but it doesn't seem like there's an integration for Rich Presence (presumably because there's no way to add it as a registered game in Activity Settings on mobile?)

**Comment by ArjixWasTaken** [comment]
@tam013001 

They are not able to do what you think they did.
Please understand how discord rich presence works, and that you can be simultaneously on both pc and mobile...
Your discord rich presence is sent to discord's servers, that's how your friends see your presence, and that's how you can see your presence from the mobile app as well....

**Comment by tam013001** [comment]
I wasn't thinking and got confused when they showed the screenshot and assumed there was a mobile version of the app. It didn't occur to me they showed it just to show that the activity could be seen on both PC and phone. I know how Presence works, my mind just moves faster than I'd like it to. Thank you for the clarification

**Comment by ArjixWasTaken** [comment]
> I wasn't thinking and got confused when they showed the screenshot and assumed there was a mobile version of the app. It didn't occur to me they showed it just to show that the activity could be seen on both PC and phone. I know how Presence works, my mind just moves faster than I'd like it to. Thank you for the clarification 

I've had that issue as well, I think faster than I can process information 😔

**Comment by DigitalDicast** [comment]
> i had the same error show connected and enabled, and even when i clicked enabled didn't change the "enabled" i fix it editing the config.json, there it showed that i had it disabled

Hi, how can I find config.json?

**Comment by i6c** [comment]
> Hi, how can I find config.json?

options > advanced options > edit config.json

**Comment by i6c** [comment]
> > I wasn't thinking and got confused when they showed the screenshot and assumed there was a mobile version of the app. It didn't occur to me they showed it just to show that the activity could be seen on both PC and phone. I know how Presence works, my mind just moves faster than I'd like it to. Thank you for the clarification
> 
> I've had that issue as well, I think faster than I can process information 😔

is there an actual fix for it, other than registering the game manually? 
---
i don't want people to know how long my music app has been open lol but still want to show like the status. and the only settings on the app seem to pertain to the duration of the song itself for RPC

**Comment by ArjixWasTaken** [comment]
![tenor](https://github.com/user-attachments/assets/949b21a9-d31d-466d-b1f6-32e413a51b2d)

---

I do not use the discord plugin myself, so I don't have any insights to give.
