### ISSUE TITLE
[Bug]: Cannot load Youtube Music... Internet disconnected? when using Adguard Home

### ISSUE THREAD

**Issue by B4TT3RY** [th-ch/youtube-music#2435]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.3.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 (Build 19045.4894)

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable Adguard Home
2. Start Youtube Music without login

### Expected Behavior

Show login page

### Actual Behavior

Show `Cannot load Youtube Music... Internet disconnected?` message and `Retry` button

### Enabled plugins

None

### Additional Information

![photo_2024-09-21_21-58-17](https://github.com/user-attachments/assets/8e7ae903-8ca9-4cf6-a22f-834b4288ca1b)
![photo_2024-09-21_22-00-13](https://github.com/user-attachments/assets/6df024c6-acd0-40e7-9fd7-4ecf5704107e)

I successfully logged in after pausing Adguard Home.
After logging in, I was able to activate Adguard Home.

**Comment by JellyBrick** [comment]
fixed at https://github.com/th-ch/youtube-music/commit/95acbe2b65d8e45182d943204e61f65caeea3650
