### ISSUE TITLE
[Feature Request]: Implement play and pouse CLI with yargs 

### ISSUE THREAD

**Issue by horberlan** [th-ch/youtube-music#2444]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

be able to play and pause with CLI via the prompt

### Proposed Solution

use https://www.npmjs.com/package/yargs 

### Alternatives Considered

```bash
$ youtube-music-desktop-app play # or pause change playPause() boolean value
```

**Comment by ArjixWasTaken** [comment]
You can already do this...

**Comment by ArjixWasTaken** [comment]
yes, it is a toggle and not an explicit play/pause

**Comment by ArjixWasTaken** [comment]
here are the protocol operations: https://github.com/th-ch/youtube-music/blob/master/src/providers/song-controls.ts#L27-L80

**Comment by horberlan** [comment]
@ArjixWasTaken Is there currently any way to do this via the bash terminal?

**Comment by ArjixWasTaken** [comment]
are you implying that what I sent does not work with the bash shell?
(bash ain't a terminal)

**Comment by horberlan** [comment]
I solved it by making a request with curl

**Comment by ArjixWasTaken** [comment]
> I solved it by making a request with curl

that is one way of doing it, you could also directly invoke youtube-music as shown in [the snippet I gave you](https://github.com/th-ch/youtube-music/issues/2444#issuecomment-2369604273)
