### ISSUE TITLE
[Bug]: app doent start and just crash

### ISSUE THREAD

**Issue by Garcarius** [th-ch/youtube-music#2446]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.0.5

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Devuan GNU/Linux daedalus 5 x86_64

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

the previous one to this

### Reproduction steps

i just start the app

### Expected Behavior

loads the gui and play music

### Actual Behavior

![image](https://github.com/user-attachments/assets/61541ae9-227f-4b26-a11e-7aea38d8e4a9)

it just shows this pop up and thats it

### Enabled plugins

none

### Additional Information

![image](https://github.com/user-attachments/assets/78f859a8-fb45-470d-bb34-d4657a5ff489)

**Comment by JellyBrick** [comment]
You are using an outdated version of this application. Please use the latest release.
https://github.com/th-ch/youtube-music/releases
