### ISSUE TITLE
The tray icon will move by itself based on the angle at which I look at the screen.

### ISSUE THREAD

**Issue by mannfuri** [th-ch/youtube-music#2456]
For example, if I look from the left, it feels like the white triangle in the middle of the icon is positioned more to the left.

my pc is win10

**Comment by ArjixWasTaken** [comment]
is this a troll issue?

**Comment by mannfuri** [comment]
no sir。this is serious。
i think this is because this circle is to thin。

Angelos Bouklis ***@***.***>于2024年9月30日 周一22:39写道：
