### ISSUE TITLE
[Bug]: There is an strange method of confirmation.

### ISSUE THREAD

**Issue by Torin-Oak-shield** [th-ch/youtube-music#2460]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.5

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04.1 LTS

### What CPU architecture are you using?

x64

### Reproduction steps

It needs to be like this. The method of confirmation of any changes (like selecting plugins or changin language)
![image](https://github.com/user-attachments/assets/1faa64e6-0f89-4bbb-93ec-227f77913238)

### Expected Behavior

A menu with
"Text confirmation"

"Agree"  "Disagree"

### Actual Behavior

Confirmation of enabling plugins
![Screenshot from 2024-10-01 21-03-58](https://github.com/user-attachments/assets/96a02f00-b073-4618-938f-88c2942f61c8)

Changing language
![Screenshot from 2024-10-01 21-16-09](https://github.com/user-attachments/assets/5d561871-8d7d-45b0-a8db-d7cce7564dcd)

### Enabled plugins

1. Navigation
2. Ad blocker
3. Downloader
4. Skip Disliked Songs

**Comment by ArjixWasTaken** [comment]
This is not a bug :p

**Comment by farsdewibs0n** [comment]
I think this is caused by the font used doesn't have Crylic support.

**Comment by JellyBrick** [comment]
Install a font that support Crylic. It's not a bug.

**Comment by ArjixWasTaken** [comment]
did you mean cyrillic?
