### ISSUE TITLE
[Bug]: Minimised preview playback icons colour remains black

### ISSUE THREAD

**Issue by Rairof** [th-ch/youtube-music#2485]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.3

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

win 11 pro

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

N/A

### Reproduction steps

Install the app and play any music.
Minimise it and hover over the app in taskbar to see its preview.

### Expected Behavior

When hovering over the app, it shows 3 playback options, previous, play/pause, next icons.
It should show the icons in white colour or opposite colour based on windows theme?
![image](https://github.com/user-attachments/assets/928bfeaa-d45a-48a6-8a7f-041640db529a)

### Actual Behavior

It does show them but in black colour regardless of the current windows theme.

![image](https://github.com/user-attachments/assets/9b3bf4f3-2cd9-46b4-b0f8-b6f56e0e0b6b)

### Enabled plugins

1. Ad Blocker
2. Album Actions
3. Album Color Scheme Color mix ratio- 50%
4. Ambient Mode-
    Smoothness transition- During 1.5s
    Quality- 50 pixels
    Size- 100%
    Buffer- 30
    Opacity- 100%
    Blur amount- 100 pixels
5. Blur Navigation Bar
6. Bypass Age Restrictions
7. Discord Rich Presence-
    ✓ Auto reconnect
    ✓ Clear activity after timeout
    ✓ Play on YouTube Music
    ✓ Hide GitHub link Button
8. Downloader
9. In-App Menu
10. Lyrics Genius
     ✓ Romanized Lyrics
11. Music Together [Beta]
12. Navigation
13. Precise Volume
     ✓ Local Arrow-keys Controls
14. Skip Disliked Songs
15. Synced Lyrics
      ✓ Make the lyrics perfectly synced
      Line effect- Scale
      Default character between lyrics- ♪
      ✓ Show lyrics even if inexact
16. Taskbar Media Control
17. Video Quality Changer
18. Video Toggle-
     Mode- Native toggle
     Alignment- Left

### Additional Information

Maybe its the way its implemented or it is a limitation that is necessary to make it compatible with other platforms. I don't know, help and additional info on it is appreciated.

**Comment by JellyBrick** [comment]
![image](https://github.com/user-attachments/assets/7a7dcf7b-efa1-479e-997a-317e446a3187)

fixed at https://github.com/th-ch/youtube-music/commit/11c25efd47447846d5d822cb834c0d925a5633d3
