### ISSUE TITLE
[Feature Request]: Hi, could you put an option to connect to last.fm?

### ISSUE THREAD

**Issue by malavibraa** [th-ch/youtube-music#2495]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

 I was wondering if you could add a plugin to connect to last.fm so I can keep scrobble tracks what I listen to from YouTube Music Desktop as well.

### Proposed Solution

put it as a plugin, just like they did with discord (I love that feature!)

### Alternatives Considered

[*](https://github.com/asavartsov/cloudplayer-scrobbler) something like this, idk

**Comment by JellyBrick** [comment]
![image](https://github.com/user-attachments/assets/dc492913-1ce8-4cf7-8ed1-5454d7a1e436)

Already implemented
