### ISSUE TITLE
[Feature Request] (API Server): `GET api/v1/switch-repeat-mode`

### ISSUE THREAD

**Issue by Dzheremi2** [th-ch/youtube-music#2504]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The current variation of the API supports changing repeat modes only through iteration, but if the current mode is unknown, we cannot use iterations for precise mode selection.

### Proposed Solution

Add new `GET api/v1/switch-repeat-mode` to get current mode to calculate needed iteration or replace iterations with `off`, `all` and `one` modes.

### Alternatives Considered

None

**Comment by kevindevm** [comment]
yes, also to get the volume
