### ISSUE TITLE
[Feature Request]: API Server Add/Modify Song Queue 

### ISSUE THREAD

**Issue by dnecra** [th-ch/youtube-music#2506]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Is it possible to have add song/album queue feature in the API Server?. I know that the Music Together feature can do this but if we have another option I think it would be great

### Proposed Solution

I'm not a developer but I think the easiest way is to send a song/album title in text format for example, and it automatically add the top search result song then add it in the queue

### Alternatives Considered

If not we can use direct link of the song/album for the input

**Comment by kevindevm** [comment]
yes, an a option to add to play next is useful too

**Comment by rwa96** [comment]
Being able to directly control the player via API call and add songs as well would be awesome. I would love to make simple scripts to make my own social music voting thing with that. I don't really know of anything out there that is free and has an API like that.

**Comment by BluesBroBo** [comment]
It would also be great to switch playlists that way. I use different playlists during streams for different occasions, and it would be nice to have the option to switch these via api.

**Comment by JellyBrick** [comment]
It's technically possible to implement (see the code in `music-together`), but it's very difficult in practice because YTM doesn't just store URLs and thumbnails in the queue, it stores all the UI.

**Comment by cireCloud** [comment]
Does it accept playlist ID as BluesBroBr mentioned?

**Comment by dnecra** [comment]
> Does it accept playlist ID as BluesBroBr mentioned?
I dont think so at the moment. Only song/video ID. But there always a workaround.

**Comment by cireCloud** [comment]
> > Does it accept playlist ID as BluesBroBr mentioned?
> 
> I dont think so at the moment. Only song/video ID. But there always a workaround.

Workaround as in current version or code workaround?

**Comment by dnecra** [comment]
Workaround in our end. For example you need a function in your script to extract each songs IDs in a playlist then add (to queue) those IDs one by one using POST/api/v1/queue command (assuming you already know they added this command/feature in the lastest releast). But honestly I'm not sure if this what you looking for 😅

**Comment by BluesBroBo** [comment]
> oof, its already mess JSON path for single songs. Hopefully devs will add a playlist endpoint 😅

yes I hope so too. It's the thing I miss the most about the app since I first installed it about a year ago. 😅
