### ISSUE TITLE
Max downloads from a playlist is 99?

### ISSUE THREAD

**Issue by DahrbUwU** [th-ch/youtube-music#251]
I was downloading a playlist, and stopped when reached 99 downloads.
(Note: i tried downloading the same playlist 3 times and happened all the times. The playlist has 151 songs.)
![image](https://user-images.githubusercontent.com/81421147/117207125-faa3c280-adc9-11eb-9246-1b6b498f1f15.png)

**Comment by Araxeus** [comment]
@DahrbUwU 
I've fixed this problem in #252
Thanks for the feedback
