### ISSUE TITLE
[Bug]: No sound from podcasts

### ISSUE THREAD

**Issue by Gimbergsson** [th-ch/youtube-music#2510]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.4317

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

N/A

### Reproduction steps

1. Go to library
2. Click on "New episodes" playlist
3. Click to play a podcast

### Expected Behavior

Sound for the podcast should be playing.

### Actual Behavior

Podcast start playing in the player but no sound is played.

### Enabled plugins

- Album action
- API server
- Compact slider
- Downloader
- In app menu
- Navigation

**Comment by JellyBrick** [comment]
Maybe duplicate of #1620?

**Comment by Gimbergsson** [comment]
> Maybe duplicate of #1620?

Oh, most likely yes. I'm closing this ticket then!

**Comment by JellyBrick** [comment]
@Gimbergsson Are you experiencing this issue in 3.6.2?

**Comment by Gimbergsson** [comment]
> @Gimbergsson Are you still experiencing this issue in 3.6.2?

Yes I can!
