### ISSUE TITLE
[Bug]: (`ambient mode`) Barely visible "Song/Video" toggle

### ISSUE THREAD

**Issue by Rairof** [th-ch/youtube-music#2520]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [ ] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Wiindows 11 Pro

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

N/A

### Reproduction steps

1. Play any music that includes video as well.

### Expected Behavior

Showing "Song/video" toggle clearly no matter the content being played or background

### Actual Behavior

"Song/video" toggle is barely visible
![image](https://github.com/user-attachments/assets/55fb7f59-7486-41a5-8015-a1e504b27ba5)

### Enabled plugins

1. Ad Blocker
2. Album Actions
3. Album Color Scheme Color mix ratio- 50%
4. Ambient Mode-
    Smoothness transition- During 1.5s
    Quality- 50 pixels
    Size- 100%
    Buffer- 30
    Opacity- 100%
    Blur amount- 100 pixels
5. Blur Navigation Bar
6. Bypass Age Restrictions
7. Discord Rich Presence-
    ✓ Auto reconnect
    ✓ Clear activity after timeout
    ✓ Play on YouTube Music
    ✓ Hide GitHub link Button
8. Downloader
9. In-App Menu
10. Lyrics Genius
     ✓ Romanized Lyrics
11. Music Together [Beta]
12. Navigation
13. Precise Volume
     ✓ Local Arrow-keys Controls
14. Skip Disliked Songs
15. Synced Lyrics
      ✓ Make the lyrics perfectly synced
      Line effect- Scale
      Default character between lyrics- ♪
      ✓ Show lyrics even if inexact
16. Taskbar Media Control
17. Video Quality Changer
18. Video Toggle-
     Mode- Native toggle
     Alignment- Left

### Additional Information

This issue has been happening for a long time and I thought it would be fixed eventually but now its worse then before as earlier it would just show up as greyed out instead of being bright even if the video is available which is confusing for users. Now it is barely visible at all. Hence why I am posting this issue.

**Comment by h-banii** [comment]
The issue seems to be caused by the `ambient mode` plugin, the "blur canvas/image" is being rendered on top of some elements (besides the song/video toggle).

It's even more noticeable if you set the size to 300%.

![image](https://github.com/user-attachments/assets/e357952d-b9df-42ea-a9ab-13a7aeb8f428)
