### ISSUE TITLE
[Feature Request]: Windows ARM Client

### ISSUE THREAD

**Issue by davewatson91** [th-ch/youtube-music#2521]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Hi team - love your work! 

With the release of the Snapdragon processors, there is a ton of new Windows on ARM devices floating around. I'm personally running a Surface Pro 11, and would love to see a Windows ARM release. The x64 emulation works, but am trying to run natively for increased battery life etc. 

I'm hoping that given there are ARM releases for macOS & Linux, that the Windows build shouldn't be too much harder 🤞🏼 

### Proposed Solution

Compile a Windows ARM installer 🙏🏼 

### Alternatives Considered

x64 Emulation - it works, but native is better 😄

**Comment by JellyBrick** [comment]
Already supported. 
Installer and portable both are universal.
