### ISSUE TITLE
[Feature Request]: (Scrobble ALL Devices) Scrobble via History Rather than Stream

### ISSUE THREAD

**Issue by Yocracra** [th-ch/youtube-music#2522]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I use YouTube music on iOS as well as desktop, and there's no way of scrobbling what I play on iOS. A solution to this problem is [luisignaciocc/youtube-music-scrobbler](https://github.com/luisignaciocc/youtube-music-scrobbler) (now [luisignaciocc/ytmusic-scrobbler-web](https://github.com/luisignaciocc/ytmusic-scrobbler-web)). Instead of scrobbling music as it's streamed, it scrobbles the last 24 hours of music played on an account. This includes music played from any device.

### Proposed Solution

I propose an option to scrobble listening history (rather than stream) to handle scrobbling of music played on ALL devices.

### Alternatives Considered

[luisignaciocc/youtube-music-scrobbler](https://github.com/luisignaciocc/youtube-music-scrobbler) (now [luisignaciocc/ytmusic-scrobbler-web](https://github.com/luisignaciocc/ytmusic-scrobbler-web))

### Additional Information

I'd be happy to try doing this myself, but I'm a total noob.

**Comment by JellyBrick** [comment]
It is out of the scope of this project.
