### ISSUE TITLE
[Feature Request]: Add real-time translation to lyrics

### ISSUE THREAD

**Issue by py233** [th-ch/youtube-music#2525]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Add real-time translation for lyrics with multi-language support

### Proposed Solution

GitHub project for reference: 
https://github.com/boidushya/better-lyrics

### Alternatives Considered

ditto

**Comment by JellyBrick** [comment]
Duplicate of #2195
