### ISSUE TITLE
[Feature Request]: Video-Toggle Does Not Persist Across Playlist Transitions

### ISSUE THREAD

**Issue by james-1987** [th-ch/youtube-music#2526]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When using the Video-Toggle plugin in the YouTube Music app, I encountered an issue while playing a playlist that contains a mix of both audio-only tracks and tracks with accompanying videos. After finishing an audio-only track, the toggle does not revert to playing video for the next track, even if that track has a video available. Instead, it continues to play the track as audio-only, disregarding the availability of the video.

### Proposed Solution

I suggest implementing a feature that ensures the audio/video toggle state is remembered between track transitions in a playlist. This way, the plugin will check whether the user prefers video or audio when a new track begins, ensuring that the video is played if it is available and the user has previously selected that preference.

### Alternatives Considered

*

### Additional Information

The issue occurs consistently when a playlist contains a mix of video and audio-only tracks. I am using the latest version of the YouTube Music app with the Video-Toggle plugin installed.

**Comment by JellyBrick** [comment]
It's the intended behavior of (official) YTM.
