### ISSUE TITLE
[Feature Request]: Disable progress bar scrubber / handle / thumb

### ISSUE THREAD

**Issue by nanopink** [th-ch/youtube-music#2539]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Would be nice to have a feature that removes the round scrubber / handle / thumb on the music progress bar
Currently time skipping to a specific location nearby the handle is impossible due to the hitbox being too large

### Proposed Solution

Example of instant seeking at same currently playing location from a personal project

https://github.com/user-attachments/assets/652c3250-147b-4eac-8fb7-b52bdb7dca87

### Alternatives Considered

None

**Comment by ArjixWasTaken** [comment]
for a moment I thought you were making a feature request to the wrong repository, due to the different music player at the start of the video :sob:

**Comment by ArjixWasTaken** [comment]
This can be achieved using custom css

```css
#sliderKnobContainer {
    display: none !important;
}
```

in this example I completely hide the knob, since it is kinda useless either way

**Comment by nanopink** [comment]
Worked thank you
But now I have this new problem where there's a double lecture

https://github.com/user-attachments/assets/40098c2c-21da-4f41-9bea-6005973f7410

**Comment by nanopink** [comment]
Considering this issue is probably the last priority out of all issues lets just close it
