### ISSUE TITLE
Navigation plugin doesn't work after reload or force reload page

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#254]
Reload and force reload are "commands" of the latest release ([v1.12.0](https://github.com/th-ch/youtube-music/releases/tag/v1.12.0)).
Problem: navigation buttons inner the page are not shown after reload or force reload!

**Comment by Araxeus** [comment]
It seems that custom css injected by a plugin somehow gets disabled when refreshing

**Comment by Araxeus** [comment]
Thanks for the quickly spotting and reporting the problem
 I fixed it in #255
