### ISSUE TITLE
Some videos/song doesn't play in the app and appear like "not available to play" in my playlists

### ISSUE THREAD

**Issue by kontrajs** [th-ch/youtube-music#2566]
![{3E1BEF0E-DBD2-4480-BB48-EB55964FF631}](https://github.com/user-attachments/assets/a6e8375f-ddf6-446f-a5ad-66c47244e2f1)
is there an option to allow those videos? it's weird because I can normally play it on youtube, it isn't a private video.

link of that example song: https://youtu.be/glqujTmJEvo?si=kCPjYByRKbyR8Ej9

**Comment by JellyBrick** [comment]
It's not our application's issue.
