### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by wininusthefirst** [th-ch/youtube-music#2567]
Hi! Just wanted to ask if there is any documentation for the newly introduced API.

**Comment by JellyBrick** [comment]
Use `/swagger` endpoint

**Comment by LeonDProto** [comment]
> Hi! Just wanted to ask if there is any documentation for the newly introduced API.

I was confused too, found it:
`http://[Computer IP]:[Port]/swagger`  or  `http://localhost:[Port]/swagger`

for me the default port was 26538 so `http://localhost:26538/swagger` works for me
