### ISSUE TITLE
Turning on the notification plugin makes the program completely unresponsive

### ISSUE THREAD

**Issue by fine2006** [th-ch/youtube-music#257]
Issue: When I turn on the notification plugin, the program becomes unresponsive and doesn't load any song (i.e. doesn't load the next part of the song), which is persistent after restarts until I turn the plugin off using config.json

**Comment by Araxeus** [comment]
What platform are you on?
Are you using interactive plugins?
what are you notifications plugin options?

**Comment by fine2006** [comment]
Platform: Arch Linux, SwayWM (Wayland) 
Notification plugin isn't configured, turning it on just makes the program unresponsive
What is interactive notifications?
As soon as I turn on the plugin, the program's cannot access the internet, that is, it cannot play the song anymore after tha cached part is over, restarting the program leads to playing the same song but it ends after the cached part ends(I have the 'Resume last song' option ticked on)
The program isn't unresponsive completely, i.e. the UI is still working(the ui elements, the song timer etc) but I can't give any response in return, the cursor switched from 'normal' icon to 'move' icon for all of the box and it gets completely useless until I switch off the plugin using the js

**Comment by Araxeus** [comment]
I can't find anything in the code that would make that happen.

> Platform: Arch Linux, SwayWM (Wayland)
I think its related to that

What notification daemon are you using?
can you try using [mako](https://github.com/emersion/mako)?

can you try running XWayland? (run with GDK_PLATFORM=x11)

**Comment by fine2006** [comment]
hmm, seems like mako is disabled by default. Will have to try out and run mako and youtube-music together

**Comment by fine2006** [comment]
Well it really seems like that was it! But I'm still confused as to how to make make start as a service since I haven't seen a mako systemd service :/

**Comment by Araxeus** [comment]
Nice, I'm happy that fixed that for you 😀
