### ISSUE TITLE
Is there a way I can change where I download music with downloader plugin ?

### ISSUE THREAD

**Issue by sindibad363** [th-ch/youtube-music#258]
I am using linux if that might help.

**Comment by Araxeus** [comment]
Yes, if downloader plugin is active, you can choose a download location by clicking the `Choose Download Folder` button in main menu / plugins / downloader

**Comment by sindibad363** [comment]
Unfortunatly i cant see an option to "Choose Download Folder" in menu > plugins/downloader

**Comment by Araxeus** [comment]
This is only available in the preview version [v1.12.0](https://github.com/th-ch/youtube-music/releases/tag/v1.12.0)

But there are some other little bugs in that release.
if you want instead you can set it in `Advanced Config` (config.json)
```json
"plugins":
		"downloader": {
			"enabled": true,
			"ffmpegArgs": [],
			"downloadFolder": "D:\\Music\\Downloads\\Youtube Music"
		},
```
like so

**Comment by sindibad363** [comment]
thanks but could you show me a path on linux would look like ?

**Comment by Araxeus** [comment]
I dont have linux, but I think it would look the same..

**Comment by sindibad363** [comment]
so like "downloadFolder": "/home/user/myfolder" ?

**Comment by Araxeus** [comment]
yeah just try it, it shall warn you if its not a valid path

**Comment by sindibad363** [comment]
Works wonderfully
