### ISSUE TITLE
[Feature Request]: Absolute seek endpoint for API server

### ISSUE THREAD

**Issue by franz-dc** [th-ch/youtube-music#2582]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am currently creating a [remote control app](https://github.com/franz-dc/youtube-music-remote) using the new API server. Is it possible to also have an API for seeking to the exact desired time? Currently, there is only `/go-back` and `/go-forward`, which is relative, and is not ideal when scrubbing/dragging through the seek bar.

### Proposed Solution

Add a new API for seeking / setting the exact seconds to jump to.

### Alternatives Considered

Use the existing APIs, but it would not be good for the use case.

**Comment by LeonDProto** [comment]
Solution can be found here #2567 

https://github.com/th-ch/youtube-music/issues/2567#issuecomment-2459529236

**Comment by franz-dc** [comment]
> Solution can be found here #2567
> 
> [#2567 (comment)](https://github.com/th-ch/youtube-music/issues/2567#issuecomment-2459529236)

The comment you mentioned is for showing all available APIs. What I am requesting is for a new API though.

**Comment by LeonDProto** [comment]
> > Solution can be found here #2567
> > [#2567 (comment)](https://github.com/th-ch/youtube-music/issues/2567#issuecomment-2459529236)
> 
> The comment you mentioned is for showing all available APIs. What I am requesting is for a new API though.

Sorry I replied to the wrong thread

**Comment by franz-dc** [comment]
> Sorry I replied to the wrong thread

No worries!
