### ISSUE TITLE
Api Server Documentation?

### ISSUE THREAD

**Issue by BluesBroBo** [th-ch/youtube-music#2593]
Okay, I don't know if I'm just blind, but I can't find for the love of me any clear instructions on HOW to use the api server that got implemented with the last update. What apis can I call? What request types are supported for these? How do I handle the first request authorization? What header or body structure is needed for which request?

I know I am not the most experienced when it comes to working with apis and that some of these things might be more obvious with that experience, but I would AT LEAST expect some form of documentation somewhere! As of now, the plugin is not even listed in the list of available plugins.

**Comment by LeonDProto** [comment]
Solution can be found here #2567 

https://github.com/th-ch/youtube-music/issues/2567#issuecomment-2459529236
