### ISSUE TITLE
last-fm "open" npm dependency

### ISSUE THREAD

**Issue by Araxeus** [th-ch/youtube-music#261]
@semvis123
Hey, is there any reason to use [open](https://github.com/sindresorhus/open) 
https://github.com/th-ch/youtube-music/blob/5faeddb99b5601de8397a26ecfd825ad4dbcc085/plugins/last-fm/back.js#L61
Instead of the native Electron [`shell.openExternal`](https://www.electronjs.org/docs/api/shell#shellopenexternalurl-options)?

Just asking if this can be safely substituted to reduce unneeded dependencies

**Comment by semvis123** [comment]
I didn't know about the default method, that one should definitely be used instead of open (also seems to cause problem for certain users)
It can probably be substituted just fine with that.
Thanks for pointing that out :)
