### ISSUE TITLE
[Bug]: Discord Rich Presence displays "Connected" while Discord is closed

### ISSUE THREAD

**Issue by a1sop0s** [th-ch/youtube-music#2620]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.6.1

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Open Discord
2. Open YTM
3. Enable "Discord Rich Presence" YTM plugin
4. Confirm Discord Rich Presence status says "Connected"
5. Close Discord using right click + quit
6. Observe Discord Rich Presence status

### Expected Behavior

Discord Rich Presence status should be along the lines of "Disconnected" as there's nothing to be connected to.

### Actual Behavior

Discord Rich Presence status says "Connected" despite Discord being closed

### Enabled plugins

1. Discord Rich Presence
2. Album color theme
3. AdBlock

### Additional Information

I've also noticed that YouTube Music only hooks to Discord on YTM startup, which isn't ideal, as Discord has updates every now and then.

**Comment by TheAirBlow** [comment]
> Program says discord is connected for me too but clearly isn't since the activity isn't showing. I've hunted around some other topics in here and someone made a custom build that supposed fixed this.. a couple years ago and it no longer works now.
> 
> This has been an issue for years apparently, is it never going to get fixed?

Can you send me a link to the fork/commit that fixed it?
