### ISSUE TITLE
How do i launch the app in Arch?

### ISSUE THREAD

**Issue by RebazaMarcelo** [th-ch/youtube-music#263]
This may be a dumb question, I installed the app with apparently no issues with yay but i can't figure out how to actually launch it, I usually lauch programs with the terminal or dmenu but none of the seem to be able to do it

**Comment by sindibad363** [comment]
if you use dmenu it should be youtube-music or youtube-music-bin

**Comment by Flammable-Duck** [comment]
I checked the AUR comments, and luckily a user by the name of bwv549 had a solution:

> I did a fresh install and neither the old executable (youtube-music-bin) and what appears to be the new executable? (youtube-music) seem to be present. Seems like a bug in the PKGBUILD?
> A temporary fix to create a youtube-music executable is: `sudo ln -sf /opt/YouTube\ Music/youtube-music /usr/bin/youtube-music`
