### ISSUE TITLE
Now Paying Widget - Tuna

### ISSUE THREAD

**Issue by kontrajs** [th-ch/youtube-music#2631]
Hi, I'm sorry if this isn't a bug or suggestion but, where I can find more widgets to show in OBS what's playing from youtube music?

**Comment by h-banii** [comment]
You can ask questions in the **discussions** tab
https://github.com/th-ch/youtube-music/discussions/categories/q-a

Hmm I don't understand what you mean by

> where I can find more widgets to show in OBS

With Tuna, ***you*** are the one who makes the "widgets" using text/image sources

Tuna's page in the OBS forum explains how set it up
https://obsproject.com/forum/resources/tuna.843/

Example:
![image](https://github.com/user-attachments/assets/85f6433c-db07-41ea-836e-62fd8c78b88f)
