### ISSUE TITLE
[Bug]: Youtube Music Completely Freezes Seconds After Startup.

### ISSUE THREAD

**Issue by EquinoxRevolt** [th-ch/youtube-music#2645]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

N/A

### Reproduction steps

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Enabled plugins

1. Album Color Theme
2. Ambient Mode
3. API Server
4. Bypass Age Restrictions
5. Exponential Volume
6. In-App Menu
7. Music Together
8. Navigation
9. Precise Volume
10. Synced Lyrics
11. Ad Blocker

### Additional Information

Not sure if this is a coincidence, but Youtube Music started doing after I had lost my Youtube Premium subscription,
ever since then it acts like this, uninstalling it and reinstalling it does nothing. Turning off all my plugins does nothing, 
no matter what I do **it freezes after a few seconds of running.** Running as admin makes no difference, I'm lost and turning to this place for help.

Although I can interact with the minimized icon of it in my system tray. Though, only maximize, minimize or close the window, and take it out from system tray with the show window button, along with restarting it and exiting it with the system tray icon, past that all functionality of the app is taken away from me.

EDIT 1: Upon further testing, after about 20-30 minutes of leaving it alone to "load" or whatever it may be doing while frozen, it does eventually function again, I'm unsure of why it freezes for such a long time before hand, this is the case no matter what every time. I have to wait absurd amounts of times before the app begins to function.

**Comment by TheAirBlow** [comment]
Does it actually freeze or is just is stuck loading the webpage? Try opening devtools and check the network tab, maybe that would give a glue. The app works fine for me, even without Premium.

**Comment by EquinoxRevolt** [comment]
Unsure of how to describe it, but it seems frozen, I'm not exactly sure how it handles it's interface but, stuck loading the webpage sounds like it might fit the context better, I don't know what it could be stuck loading and I'm not exactly sure what I should be looking for in the network tab. It worked the first time but no refuses to show any activity, using ctrl + R to refresh it does not work, but as for what I saw within it I didn't see any exactly alarming errors, if any at all, (no red = everythings fine for me.)

**Comment by GuiAvella** [comment]
I am also having that same issue, on load it freezes, the music continues for a minute, then stops, and only comes back a few minutes later.

**Comment by TheAirBlow** [comment]
The app also sometimes freezes and stops rendering for me too. It's not often though, and doesn't have a specific trigger - it just happens randomly during playback.

**Comment by solipse** [comment]
Same thing, music interrupted after ~20 seconds. But everything works if unlogin account.

**Comment by JellyBrick** [comment]
Related issue: #2741

**Comment by JellyBrick** [comment]
# Workaround

- Disable `Override User-Agent`
