### ISSUE TITLE
[Bug]: Last.fm unwilling to connect- lost API keys?

### ISSUE THREAD

**Issue by Numerosityy** [th-ch/youtube-music#2655]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

v3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 

### What CPU architecture are you using?

x64

### Reproduction steps

I'm not exactly sure what happened. I haven't used the Scrobbler/Last.fm plugin in a while, but when I tried to reconnect it, it claims my API key is invalid. I removed the application via my last.fm account, but it does not wanna reconnect. I've tried logging out and logging in again, reenabling the plugin- no luck. I think I've just lost my API key for last.fm

How could I get the last.fm API keys back?

### Expected Behavior

.

### Actual Behavior

.

### Enabled plugins

![image](https://github.com/user-attachments/assets/00845238-2bce-4c60-b249-35cf02935549)

**Comment by elogikalaf** [comment]
hi, can I ask where you see the list of your plugins? can't find it.
