### ISSUE TITLE
[Bug]: Cannot login and not showing YouTube Music Rich Presence to Discord, Discord Rich Presence not working!

### ISSUE THREAD

**Issue by rajinstar** [th-ch/youtube-music#2660]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 24H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Open YouTube Music app
2. Go to the plugin option
3. Click on Discord Rich Presence
4. Click on Connect
5. Boom show connected but not connected actually because there are no login option pop-ups or I can not login to Discord because there is no option available for that. 

### Expected Behavior

I should log in to my Discord account and Rich Presence will show in my Discord account. 

### Actual Behavior

I tried a lot, but no option shows to me to sign in to Discord and use Rich Presence. Just shows connected but not connected, and I cannot log in and show my Discord presence. 

### Enabled plugins

Discord Rich Presence

**Comment by ArjixWasTaken** [comment]
You cannot and will not sign in to discord within youtube-music.
That would be considered a self-bot and that is against discord's TOS.

youtube-music depends on discord's RPC, so discord must be running on your computer, and preferably before youtube-music
