### ISSUE TITLE
[Feature Request]: Add 5 stars rating

### ISSUE THREAD

**Issue by crysishacker** [th-ch/youtube-music#2670]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

normal and useful

### Proposed Solution

like many music software

### Alternatives Considered

what？

**Comment by ArjixWasTaken** [comment]
stars rating for what?
please be more detailed
