### ISSUE TITLE
[Bug]: Always on Top Stopped Working After Updating to 3.6.2

### ISSUE THREAD

**Issue by OllieJames** [th-ch/youtube-music#2684]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

Unsure

### Reproduction steps

Enable Always on Top from the options menu. Open another window on the same screen.

### Expected Behavior

YT music app stays on top

### Actual Behavior

YT music app goes to the very bottom even after minimizing and maximizing.

### Enabled plugins

None

### Additional Information

Thank You for an amazing app!

**Comment by OllieJames** [comment]
To clarify when I said "YT music app goes to the very bottom even after minimizing and maximizing." by very bottom I mean the opposite of always on top, not the bottom of the screen, but the bottom of the z axis of the screen. i.e. every other window is layered over it as opposed to underneath it.

**Comment by JellyBrick** [comment]
Are you still experiencing this issue in v3.7.0?

**Comment by OllieJames** [comment]
> Are you still experiencing this issue in v3.7.0?

I am no longer experiencing this issue in v3.7.1 

Thank You!
