### ISSUE TITLE
[Bug]: Downloading gives error

### ISSUE THREAD

**Issue by niyasmohammed** [th-ch/youtube-music#2704]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.6.2

### Reproduction steps

error

### Expected Behavior

error

### Actual Behavior

error

### Enabled plugins

error

### Additional Information

error

**Comment by Eliafoxx** [comment]
same here with same specs

**Comment by JellyBrick** [comment]
Duplicate of https://github.com/th-ch/youtube-music/issues/2691, https://github.com/th-ch/youtube-music/issues/2628
