### ISSUE TITLE
[Bug]: Podcasts added via RSS feed do not play.

### ISSUE THREAD

**Issue by andreap25** [th-ch/youtube-music#2728]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

Add a podcast via RSS feed (example: https://www.spreaker.com/show/5907778/episodes/feed)

### Expected Behavior

The podcast plays without any issues, just like it does in the YouTube Music web app.

### Actual Behavior

While playing a podcast episode, the play bar advances but there's no audio.

### Enabled plugins

1. Album Color Theme
2. Ambient Mode
3. API Server
4. In-App Menu
5. Navigation
6. Video Quality Changer

**Comment by ArjixWasTaken** [comment]
Failed the preflight check
![image](https://github.com/user-attachments/assets/ccf52864-59c0-44dc-a58d-7d65fad0b7f4)

**Comment by ArjixWasTaken** [comment]
Although it is sad that this is still an issue, even after those tickets were closed.

**Comment by andreap25** [comment]
> Failed the preflight check ![image](https://private-user-images.githubusercontent.com/53124886/396509831-ccf52864-59c0-44dc-a58d-7d65fad0b7f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDUxMzUsIm5iZiI6MTczNDQ0NDgzNSwicGF0aCI6Ii81MzEyNDg4Ni8zOTY1MDk4MzEtY2NmNTI4NjQtNTljMC00NGRjLWE1OGQtN2Q2NWZhZDBiN2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE0MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NjljNDJmYmU4MGFmNDExZDhlOTVmOTFlNWI0MWM1MjEyMGU5Mzg3MmI1NzMyYTkzZjRiZmZhMjQ1MWU0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zTDwUoZGU03iODI52JJoQsc23G0dBdcubmzkJfJdiwQ)

Oooh my bad... I didn't check closed tickets, I'm new to GitHub sorry.

I found this ticket too #1620, it seems to offer a solution.
