### ISSUE TITLE
[Bug]: Downloading not working

### ISSUE THREAD

**Issue by RaksoFox** [th-ch/youtube-music#2730]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2 (OS Build 19045.5247)

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable Downloader Plugin
2. Try to download any track or playlist

### Expected Behavior

Track or playlist will be downloaded

### Actual Behavior

Error windows with "Error in download!"
Error: Unexpected token (1:71)
in \<track name\>

### Enabled plugins

1. Downloader

### Additional Information

I've tried reinstalling app, using different google account or not using account at all. Earlier downloading works just fine. But one day it stopped working while downloading playlist (in the middle of download it started throwing errors)

**Comment by spoonh** [comment]
https://github.com/th-ch/youtube-music/discussions/2726

**Comment by spoonh** [comment]
> https://github.com/th-ch/youtube-music/discussions/2726

lmk if this works for you!

**Comment by RaksoFox** [comment]
> > #2726
> 
> lmk if this works for you!

Thx for help. That worked without any problems.

**Comment by JellyBrick** [comment]
Duplicate of https://github.com/th-ch/youtube-music/issues/2691, https://github.com/th-ch/youtube-music/issues/2628, https://github.com/th-ch/youtube-music/issues/2700
