### ISSUE TITLE
[Feature Request]: VST Plugin support (to use e.g. with morphit by toneboosters for calibrated headphones sound)

### ISSUE THREAD

**Issue by nalexeyev** [th-ch/youtube-music#2739]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently the sound processing is totally on the side of OS. But you can enable integration with 3rd party plugins.

### Proposed Solution

Add VST Plugin support (to use e.g. with [morphit by toneboosters](https://www.toneboosters.com/tb_morphit_v1.html) for calibrated headphones sound)

### Alternatives Considered

Add choice for audio output to use with [VB-CABLE Virtual Audio Device](https://vb-audio.com/Cable/index.htm)

**Comment by JellyBrick** [comment]
Can't. The implementation of VSTs is fragmented (AAX, AU, VST v2, VST v3, ...etc) and platform-specific.
