### ISSUE TITLE
[Bug]: Music and videos no longer playing due to ads blocker enabled

### ISSUE THREAD

**Issue by IdiegeA21** [th-ch/youtube-music#2741]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.6.2

### Reproduction steps

1. Open Youtube music
2. Click the search bar and Search for a music
3. Click on the music or video to play the it

### Expected Behavior

The music or video should start playing without any errors or ads

### Actual Behavior

After about 5 mins load you will get an error that says "Something went wrong. Refresh  or try again later. learn more

### Enabled plugins

1. Adblocker
2. API Server[Beta]
3. Album Color Theme
4. Downloader
5. In app menu
6. Lyrics genius(which does not work)
7. Navigation
8. Picture in Picture

**Comment by JellyBrick** [comment]
Which ad-blocker mode are you using?

**Comment by kurokin** [comment]
I'm expericing the same behavior and am currently using 'With Blocklist' in the screenshot shown 
![Untitled png12312](https://github.com/user-attachments/assets/994ea1fc-3856-4398-8b52-b0ec4c9395db)

**Comment by TheAirBlow** [comment]
Disabling adblocker did not help either.

**Comment by JellyBrick** [comment]
Related issue: #2645

**Comment by Rairof** [comment]
I have experienced this issue but disabling adblocker didn't fixed the issue for me. I am speculating it's something else that's causing this issue.
I have noticed that songs plays for approx 15-30 secs on startup then playback issues starts. official youtube music works fine on my end.

**Comment by TheAirBlow** [comment]
It seems to be working fine again. I'm using adblocker with the default "in player" mode.

**Comment by TheAirBlow** [comment]
It's probably some sort of A/B testing. Not sure.

**Comment by TheAirBlow** [comment]
After checking the networking tab, it looks like it's trying to fetch the video and the server returns 200 success. Though, it seems like it doesn't return any data. It tries to fetch it 1-3 times and then just drops out.

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/2741#issuecomment-2561259777
I am not sure if it really is A/B testing as music playback works fine on official ytm website with ublock origin adblock enabled in the same account for me and the playback issue persists only within th-ch ytm app for me

**Comment by JellyBrick** [comment]
### Workaround

- Disable `Override User-Agent`
