### ISSUE TITLE
[Bug]: Discord(Canary) is not recognizing activity.

### ISSUE THREAD

**Issue by NucleoFusion** [th-ch/youtube-music#2747]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What CPU architecture are you using?

x64

### Reproduction steps

Enabling the Discord Plugin does nothing

### Expected Behavior

I expect Youtube Music to be shown in discord as an activity.

### Actual Behavior

Nothing is shown in Discord.

### Enabled plugins

only Discord plugin enabled.

**Comment by JellyBrick** [comment]
See #2427

**Comment by NucleoFusion** [comment]
> See #2427

didnt fix it. I dont have any network interrupting programs, and my config.json shows enabled.

**Comment by daika7ana** [comment]
Tested with:
![image](https://github.com/user-attachments/assets/e10e749c-4809-4b02-ad3c-90abb8055575)

```
Discord Canary 355707 (7b10d4d) 
Host 1.0.513 x64 (56983) 
Build Override: N/A 
Windows 11 64-bit (10.0.26100)
```

Can't reproduce either.

Side note 1:
Considering how Discord tags their release channels with Stable, PTB and Canary - I would tag their Canary releases as bleeding-edge, and therefore fixing any bugs that pertain to that release channel as low-priority or even wontfix.

Side note 2:
Make sure this option is enabled:
Settings > Activity Privacy > Share your detected activities with others

**Comment by NucleoFusion** [comment]
> Tested with: ![image](https://private-user-images.githubusercontent.com/11703528/397894156-e10e749c-4809-4b02-ad3c-90abb8055575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTg0ODQsIm5iZiI6MTczNDc1ODE4NCwicGF0aCI6Ii8xMTcwMzUyOC8zOTc4OTQxNTYtZTEwZTc0OWMtNDgwOS00YjAyLWFkM2MtOTBhYmI4MDU1NTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA1MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzVmNDlmNzYzNWU4YjQ3MGRjZmQ2Y2Q2ZmJiZmIxNzk1MjFmMTM5OWZkNTU3OGUxYWIwY2MwODkxNjE4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IyhwZSTheICG2K7FLFD38o15m2sUaEj4gNBPhxtRlf4)
> 
> ```
> Discord Canary 355707 (7b10d4d) 
> Host 1.0.513 x64 (56983) 
> Build Override: N/A 
> Windows 11 64-bit (10.0.26100)
> ```
> 
> Can't reproduce either.
> 
> Side note 1: Considering how Discord tags their release channels with Stable, PTB and Canary - I would tag their Canary releases as bleeding-edge, and therefore fixing any bugs that pertain to that release channel as low-priority or even wontfix.
> 
> Side note 2: Make sure this option is enabled: Settings > Activity Privacy > Share your detected activities with others

What DE are you using, one reply i got on reddit seems to say that it works for him on hyprland.

**Comment by NucleoFusion** [comment]
It seems i had previously disable discord from accessing my data. It fixed after allowing that. 
Thanks for the help.
