### ISSUE TITLE
[IMPORTANT] Please read this issue before opening an issue about download

### ISSUE THREAD

**Issue by JellyBrick** [th-ch/youtube-music#2751]
- The issue you're trying to open may be a duplicate of #2691 or #2628, which have already been resolved.
- Be sure to check before opening an issue.
- Next version will be published within 7 days.

**Comment by ImaDoor2785** [comment]
just built from latest commit and i still get the 2xx status code error
ill try the release once its out but its still not fixed for me

**Comment by digitalnomad91** [comment]
Can confirm, I'm having the same issue as @ImaDoor2785.

**Comment by ImaDoor2785** [comment]
not fixed yet sadly even tried bulding youtubei.js myself and its still broken
