### ISSUE TITLE
[Bug]: Low Quality Covers

### ISSUE THREAD

**Issue by mrrewilh** [th-ch/youtube-music#2752]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Reproduction steps

I use wallpaper engine to add a music player to my PC Wallpaper. While other players (I use Moosync and Spotify) have no problems, youtube music images are very low pixel. Is there a way to change this?

![image](https://github.com/user-attachments/assets/e34f534c-9301-4f3b-811c-58d076275ac8) (Moosync)

![image](https://github.com/user-attachments/assets/250bb2a2-dd42-4d3c-b2e9-00556bebdf4e) (YTM)

### Expected Behavior

I was expecting the song covers to be a bit higher quality.

### Actual Behavior

Song covers are in very low pixels.

### Enabled plugins

Default ones.

### Additional Information

I know, it may be related to another application. **I'm just asking how to improve the quality of the song cover that comes out.** It has nothing to do with Wallpaper Engine. You can just see it as an example.

**Comment by mrrewilh** [comment]
It is receiving data from Windows Media Overlay. Could you please tell me which code is sending the images to Media Overlay?

**Comment by JellyBrick** [comment]
> It is receiving data from Windows Media Overlay. Could you please tell me which code is sending the images to Media Overlay?

@mrrewilh Chromium

**Comment by mrrewilh** [comment]
> @mrrewilh Chromium
I'm just trying to do this. In the picture I attached, you see there is a song album. I'm asking how the data is transferred there. How can I increase the quality of the image there?
![image](https://github.com/user-attachments/assets/10374c9d-ae58-4c96-aa10-08639a31f783)
