### ISSUE TITLE
[Bug]: Taskbar and Volume freezing when changing volume

### ISSUE THREAD

**Issue by 1gn4ac10** [th-ch/youtube-music#2805]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.7.1.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

Just using Youtube Music as normal, eventually when changing the volume it freezes, can't change the volume, taskbar stops responding. 

### Expected Behavior

- Volume changes working like it's supposed to do.

- Taskbar working like always.

### Actual Behavior

Sometimes when you change the volume while having YT Music open, the volume bar freezes. 

This also ends up freezing the taskbar since they are part of the same process (explorer.exe). This affects the entire pc since when using the windows button the taskbar doesnt appear, and well, you can't change the volume. YT Music is still playing tho, the app is not frozen.

The only way to fix this is to restart explorer.exe, but if you change the volume again, it freezes... again.

### Enabled plugins

- Ad Blocker
- Album Color Theme
- Ambient Mode
- Amuse
- Bypass Age Restrictions
- Discord Rich Presence
- Exponential Volume
- In-App Menu
- Lyrics Genius
- Navigation
- Precise Volume
- Shortcuts (& MPRIS)
- Synced Lyrics

### Additional Information

I change the volume using the volume slider in my keyboard (Logitech G815)

**Comment by JellyBrick** [comment]
It's a Windows issue (bug), not ours
