### ISSUE TITLE
Adblock plugin not functioning properly

### ISSUE THREAD

**Issue by pyporn-san** [th-ch/youtube-music#282]
When **starting** a new radio/playlist, a single ad will still show up. The problem then disappears until I start another radio/playlist.
![image](https://user-images.githubusercontent.com/76444728/118251856-58689680-b4bd-11eb-8343-b3e4c2ae5ec6.png)

![image](https://user-images.githubusercontent.com/76444728/118251973-7afaaf80-b4bd-11eb-8c6c-e6d5ee68b2d5.png)

**Comment by Bellisario** [comment]
I had this problem, too, but with "normal" songs. I resolved with page reloading (form "View" menu in the latest version).
This is probably a bug of the adblocker that runs with a event that could be not the right, as #254.

**Comment by pyporn-san** [comment]
The issue is gone now with no apparent reason.

**Comment by Araxeus** [comment]
Honestly no clue why would it happen in the first place. its really weird
