### ISSUE TITLE
[Feature Request] - Is there a way to make non-playable videos/songs playable in Music App?

### ISSUE THREAD

**Issue by nshannon123** [th-ch/youtube-music#294]
Is it possible to do this? So many times in a playlist a few songs would be listed as unavailable as they don't satisfy YT Music's parameters for being a song to play... Even though the video is a song. If these could be playable in the app, that would be brilliant!

**Comment by Araxeus** [comment]
Problematic..

You could try finding another version of the song that isn't blocked
or if its 'region-blocked' you could try using a proxy/vpn

**Comment by nshannon123** [comment]
Yeah it seems to be a problem with the YT Music client itself (the official one has the problem too). The playlist plays fine on YT itself so it's not "region-blocked" etc. but when trying to play on YT Music, it's unavailable :/ And this is on community playlists, not my own.
So the only solution is to find another version I guess (or play using YouTube itself or something)

**Comment by Araxeus** [comment]
If its not a frequently updated playlist, you could 'clone' it and make it your own

you can do that by clicking on the three dots and there will be an option to add all to playlist

![image](https://user-images.githubusercontent.com/78568641/118834313-ca304e00-b8ca-11eb-97a7-cdfda0758d32.png)

**Comment by DereC4** [comment]
I third this
