### ISSUE TITLE
Serious bug causing system slowdown and crash

### ISSUE THREAD

**Issue by b-init** [th-ch/youtube-music#295]
I built a new version of YTmusic Desktop yesterday via cloning the master repo, and it's been running fine. But just recently, it started to consume too much resources and crashed other running applications, and slowed down my PC. And that happened while it was running under background processes (not playing any music). It's running again fine now. But that may need to be worked on. I wonder if it stores logs and errors anywhere in cache that I could share?

PC's specifications are:
Windows 10 20H2
i5 8265U
8 Gigs DDR4 memory

**Comment by Yeetus3141** [comment]
![image](https://user-images.githubusercontent.com/55803927/119038991-65135000-b9d1-11eb-8a68-19f3e67f0e4b.png)

**Comment by Bellisario** [comment]
Could be useful increase app performance during sleep (if no music playing after some minutes), so, some time ago I proposed this functionality: #232.

**Comment by amerodeh** [comment]
Was playing Monster Hunter World and suddenly got a crash to desktop with no error message or anything, looked at Event Viewer and the following things were there with timestamps at the time of the crash
>Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: MonsterHunterWorld.exe (17972) consumed 8878804992 bytes, YouTube Music.exe (18588) consumed 4484780032 bytes, and YouTube Music.exe (21148) consumed 3952488448 bytes.

>Application pop-up: Windows - Out of Virtual Memory : Your system is low on virtual memory. To ensure that Windows runs properly, increase the size of your virtual memory paging file. For more information, see Help. 

So I guess this app has a memory leak (Monster Hunter World ~9 GB vs YTM ~4.5 GB + ~4 GB). My PC has been running pretty much all day (booted it up in the early afternoon, it's midnight now). 
btw Not sure why it's reported twice, I have it locked down to one instance using that option within the app. Had barely any plugins enabled bar the default ones too.
