### ISSUE TITLE
App keeps restarting when Last.fm plugin is enabled

### ISSUE THREAD

**Issue by JohnCale47** [th-ch/youtube-music#302]
App keeps restarting when i enabled Last.fm plugin, reinstall wont fix it , where is the config file stored so i can manually disable the plugin ?

**Comment by JohnCale47** [comment]
> on windows 10:
> `C:\Users\myUser\AppData\Roaming\YouTube Music\config.json`

Disabled the Plugin and now its working fine..Please look into it, im using the latest v1.12

**Comment by Araxeus** [comment]
#262 Might have already fixed that problem in the main branch version
Would be nice if you could check it by building from main branch
or downloading the already compiled version from https://drive.google.com/drive/folders/1Kfa4USQtoUjZTZLzgToDM6kMELdkRqgC?usp=sharing

**Comment by th-ch** [comment]
Hey guys, latest version [v1.12.1](https://github.com/th-ch/youtube-music/releases/tag/v1.12.1) is available as a pre-release - it contains many fixes, feel free to check it out!

**Comment by BelgarionNL** [comment]
latest release did not fix the lastfx bug! I also had to disable the plugin through the json.
