### ISSUE TITLE
Cant download playlist using downloader plugin (v.1.12.1)

### ISSUE THREAD

**Issue by sindibad363** [th-ch/youtube-music#306]
I tried to download a playlist using downloader but it is just saying downloading for the past 15 min. (3 songs in the playlist) but nothing is happening. If I try to download a single song it works but not the whole playlist. I don't know if I did something wrong or not but anybody has the same problem or just me? (using Linux for more info on the matter)

**Comment by Araxeus** [comment]
did you try the [Latest Version (v1.12.1)](https://github.com/th-ch/youtube-music/releases/tag/v1.12.1) ?

Did you press download playlist from the menu while a song from the playlist is loaded?

Did you get a message that it is downloading the playlist?
> Downloading Playlist `name` - (`playlist.length` songs)

**Comment by sindibad363** [comment]
``did you try the Latest Version (v1.12.1) ?`` 
Yes I have installed the newest 1.12.1

``Did you press download playlist from the menu while a song from the playlist is loaded?`` 
Yes tried that too

``also if the taskbar progress-bar doesn't display (on newest version) : `` 
Using i3wm so I don't have taskbar

``could you tell me what is the exact name of your desktop entry file? (the one you should be launching from)`` 
I am lauchnig it from dmenu

**Comment by Araxeus** [comment]
> " it is just saying downloading  for the past 15 min" 

^ where does it say that?

Did you get a message that it is downloading the playlist when it started?
message content should be `Downloading popPlaylist - (3 songs)`

**Comment by sindibad363** [comment]
I just pressed download and it stayed at downloading

``Did it create a new folder in the download directory with playlist name?``
no

**Comment by Araxeus** [comment]
what do you mean stayed at downloading?? can you explain please where and what do you see

you also still didn't say if you received a popup message that its downloading like I already asked 2 times

**Comment by sindibad363** [comment]
sorry for not explaining enough.
So I go to plugins, downloader, and Download Playlist. It opens a window that says Download Failed, but when I try to download a single song the download button says downloading.

**Comment by Araxeus** [comment]
Why did you say ` just saying downloading for the past 15 min` if it failed on start... 😮

anyways what the error message you get? download failed message should have some details on the error

**Comment by sindibad363** [comment]
API Error- Playlist doesn't exist

**Comment by Araxeus** [comment]
Are you trying to download a private playlist?

**Comment by sindibad363** [comment]
Now it works. Downloaded # of songs. And also I had it as a private playlist. I changed it public and downloaded it seccessfuly.

**Comment by Araxeus** [comment]
Sorry, the playlist downloader cannot download private playlists as of now.

Thats because it request the playlist details from youtube without credentials, so it can't access private ones.

**Comment by nithinpm09** [comment]
I still have the issue mentioned by @sindibad363. My playlist is public. The downloading starts. It creates a folder with a playlist name but the download never completes. OS: Windows 10.
