### ISSUE TITLE
[Feature Request] Changing song order.

### ISSUE THREAD

**Issue by thijsi123** [th-ch/youtube-music#307]
Hello again.

I was just wondering if it may be possible to implement something to change song order in playlists.
I always use my Like music playlist but it's a private playlist of course and you can't select all songs and put them into a new playlist,
so this would be very helpful.

b.t.w. Is it okay for asking things like this in the issues section or is there a better place to ask this? thanks.

**Comment by Araxeus** [comment]
You are using the plugin `in-app-menu` right? it seems its bugged there

if not you should be able to drag and drop songs in playlist to change order

**Comment by thijsi123** [comment]
I'll check it out right now.

**Comment by Araxeus** [comment]
Sorry my bad, you can never re order songs inside the "liked" playlist

But you should be able to re order songs in any other playlist OR in current playing queue

**Comment by thijsi123** [comment]
Thanks. It works for normal playlists but sadly not for my liked music thank you anyways.

**Comment by thijsi123** [comment]
Should I close this issue?

**Comment by Araxeus** [comment]
Yes its not really related to the app.
by the way its not about private playlists - the problem is only with the specific `liked` playlist

**Comment by thijsi123** [comment]
Okay thank you. 

Sorry that closing took long.
