### ISSUE TITLE
Make the custom titlebar optional

### ISSUE THREAD

**Issue by TECHNOFAB11** [th-ch/youtube-music#309]
Its cool that its possible to replace the system titlebar with a custom one in Electron and all, but from my experience this is awful.
Every app that does this wants to look better, but the UX gets worse.

1. Its lagging behind, see #128 
2. On this app specifically, i dont have any real titlebar on Linux, it just looks like this:
![Screenshot_20210604_143024](https://user-images.githubusercontent.com/34860318/120801412-68feb080-c541-11eb-9310-48a100716e68.png)
3. The native titlebar of KDE is customizable. I have buttons which let me keep windows in front or in the back, etc. 
4. Desktop effects, like wobbly windows on KDE are also not working when Electron handles the window movement. Thus they feel completely out of place

There should at least be the option to disable this custom titlebar, because for me personally there are only downsides

Edit: same thing happens with Figma-Linux, see the issue [here](https://github.com/Figma-Linux/figma-linux/issues/184)

**Comment by Araxeus** [comment]
Are you talking about in-app-menu plugin that is disabled by default? 😮

**Comment by TECHNOFAB11** [comment]
If it's disabled by default then thats not what im talking about. 
I took that screenshot right after opening it and signing in. After looking through the settings i can't find any setting which brings back the native titlebar (thus i created this issue)

**Comment by JellyBrick** [comment]
Can't reproduce on Kubuntu 23.04, and Ubuntu 23.04 Desktop
