### ISSUE TITLE
Adblocker not working since update

### ISSUE THREAD

**Issue by oanadonose** [th-ch/youtube-music#310]
![image](https://user-images.githubusercontent.com/33088260/120807577-048f2180-c540-11eb-97ad-9301d5316008.png)

Checked both logged in and not logged in

Pretty sure it worked fine a few days ago

**Comment by Araxeus** [comment]
I see you closed the issue, Any idea what you did wrong?
(works for me)

**Comment by oanadonose** [comment]
Yeah, sorry - Completely my bad! File had the same name as previous version so I was using an older one instead of updated.
