### ISSUE TITLE
Notifications getting logged to Windows Action Center

### ISSUE THREAD

**Issue by sanyogthescholar** [th-ch/youtube-music#312]
After updating to 1.12.1, notifications are getting logged to Windows Action Center instead of disappearing after a few seconds.  They used to disappear after a few seconds on earlier builds.
![image](https://user-images.githubusercontent.com/50242941/120915457-54492680-c6c1-11eb-8b86-e1b2b08a037a.png)
Is this expected behavior or a bug?

**Comment by Araxeus** [comment]
This is actually really weird - I have the same bug when downloading the official 1.12.1, but when I build the app myself it doesn't happen..

here is the binaries i built from main branch if you want: https://drive.google.com/drive/folders/1Kfa4USQtoUjZTZLzgToDM6kMELdkRqgC?usp=sharing

(**should** be no difference between it and the official release..)

**Comment by JellyBrick** [comment]
https://github.com/electron/electron/issues/40133

**Comment by JellyBrick** [comment]
It should fixed by https://github.com/electron/electron/pull/40197
