### ISSUE TITLE
Found a Malware

### ISSUE THREAD

**Issue by errorsolver** [th-ch/youtube-music#313]
The day after i download Youtube Music 1.12.1, My Antivirus found Malware that infected libEGL.dll

<img src="https://user-images.githubusercontent.com/72688274/120950697-7e5a2180-c771-11eb-920d-47725c65fa9b.png" width="500">

**Comment by Araxeus** [comment]
It's not a malware, just shitty avast behavior

See the second comment in
https://forum.avast.com/index.php?topic=183825.0

**Comment by errorsolver** [comment]
OK Thanks
