### ISSUE TITLE
Error: Unknown picture MIME type

### ISSUE THREAD

**Issue by krypciak** [th-ch/youtube-music#315]
Hello,
when downloading music I came across an error.
The error says: Error: Unknown picture MIME type
![pic](https://user-images.githubusercontent.com/75359441/121065281-e0924100-c7c8-11eb-97e2-7ee955978508.png)
I am running the lastest version of this app.

**Comment by mikecodre** [comment]
Same, I started downloading a 100 song playlist and it showed me this MIME thing 5 times. Now I have to manually find the 5/100 songs that are missing...

**Comment by Araxeus** [comment]
Could you send links to songs that this error happened on?

**Comment by krypciak** [comment]
> Could you send links to songs that this error happened on?

https://music.youtube.com/watch?v=tmntIJSf0Dw&feature=share
I can give you more if that helps

**Comment by Araxeus** [comment]
Ok sorry youtube is trolling.. this is the link for the picture for that song
https://i.ytimg.com/vi/tmntIJSf0Dw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC5b9hkS4_861N7ooUq4fUGX7RLCw

you see the `.jpg`? - well thats a lie, this file is a webp - and we dont support those..

when trying to save the file it auto suggest "hqdefault.jpg.webp"

anyways ill try to fix it somehow, but youtube is making it harder than it should be T_T

**Comment by Araxeus** [comment]
Ok I made a pull request that will fix this problem (#318)

Thanks for reporting :)
