### ISSUE TITLE
[Feature request] Make playlist download not download already downloaded songs

### ISSUE THREAD

**Issue by krypciak-zz** [th-ch/youtube-music#319]
Hi,
When I'm using playlist download feature, It's downloading songs I already have downloaded, so with 200 song
playlist it takes a long time. I would like to see a feature that downloads only song not existing it the chosen directory.

**Comment by PagChompman** [comment]
This function is so useful I hope it gets added. Don't need to download the same 500 songs again or make a new playlist every time I want to download something in bulk.

**Comment by Araxeus** [comment]
#1054 will finally add this option 😏
