### ISSUE TITLE
High Ram Usage

### ISSUE THREAD

**Issue by godamanx** [th-ch/youtube-music#322]
With latest update, which is contains last.fm plugin support, this app perfect for me. Because of pandemic mostly I am at home and I left my computer open.

I have 32GB ram on my pc. Yesterday i left my computer open and Youtube Music app on background. By chance I look task manager and I saw that this app almost using 15GB of my memory. Today I test app again its start 300MB memory but 1-2 hours later ist gone to the 1GB memory.

I think electron does not support garbage collection. I think this is serious issue for apps used for a long time like music players.

**Comment by airsakarya** [comment]
#81 I want to link with this issue.

**Comment by airsakarya** [comment]
I have some proofs. I started app 18:58:38
![Ekran görüntüsü 2021-06-17 185838](https://user-images.githubusercontent.com/4149142/122641655-61c5ce00-d10f-11eb-8d8d-cf54704ade5e.jpg)

And after 6 hours ram usage
![Ekran görüntüsü 2021-06-18 014004](https://user-images.githubusercontent.com/4149142/122641656-62f6fb00-d10f-11eb-9f0f-258910c40c9d.jpg)

Active plugins
![Ekran görüntüsü 2021-06-18 014020](https://user-images.githubusercontent.com/4149142/122641657-638f9180-d10f-11eb-848d-3085c0d692e8.jpg)

**Comment by MarioGK** [comment]
Same with me
![image](https://user-images.githubusercontent.com/8379079/148665870-0eb554b8-12cf-42af-b5ed-e744da93ede3.png)

**Comment by Sciaopersone** [comment]
I fixed it using compatibility mode for windows 8
![yt music error](https://user-images.githubusercontent.com/98805033/156941338-0d44e669-23dc-4531-ac91-0b8714c98eea.PNG)

**Comment by wefalltomorrow** [comment]
> I fixed it using compatibility mode for windows 8 ![yt music error](https://user-images.githubusercontent.com/98805033/156941338-0d44e669-23dc-4531-ac91-0b8714c98eea.PNG)

Having the same issue, so will try this and will report back - thanks!

**Comment by Araxeus** [comment]
You should all install the app via [YouTube-Music-Setup-1.16.0.exe](https://github.com/th-ch/youtube-music/releases/download/v1.16.0/YouTube-Music-Setup-1.16.0.exe)

The setup is way more stable than the portable version, this memory leak might be related too

**Comment by wefalltomorrow** [comment]
> You should all install the app via [YouTube-Music-Setup-1.16.0.exe](https://github.com/th-ch/youtube-music/releases/download/v1.16.0/YouTube-Music-Setup-1.16.0.exe)
> 
> The setup is way more stable than the portable version, this memory leak might be related too

I'm running the latest version, installed not portable. Not sure why you're automatically assuming we're not?

Issue still occurs with the above 'fix', memory just keeps climbing.

![image](https://user-images.githubusercontent.com/45746576/158009856-1f4888ba-c582-4389-bad0-060d3f4072c3.png)

**Comment by Araxeus** [comment]
> I'm running the latest version, installed not portable. Not sure why you're automatically assuming we're not?

Just trying to help, wrote a *possible solution*.

I don't actually know why this seems to happen to some people, I wasn't able to reproduce this
(even after 3 days open and playing music, my memory usage was stable)

**Comment by KevinZonda** [comment]
![image](https://user-images.githubusercontent.com/33132228/170155926-8063039a-b1c6-4386-bc00-11b219b106bb.png)

500 MiB Mem usage is also quite high humm

**Comment by inson1** [comment]
@th-ch isnt this also too much ram?
![Taskmgr_5sPJwKeWmt](https://github.com/th-ch/youtube-music/assets/75314629/29e3f4d5-eeaf-4c23-b096-90bc755e8568)

**Comment by th-ch** [comment]
@inson1 latest version works fine for me (MacOS), with constant/not too high memory usage 🤔

**Comment by inson1** [comment]
@th-ch it depends on when, this was the highest, I have seen. What is the normal amount?

**Comment by JellyBrick** [comment]
> it depends on when, this was the highest, I have seen. What is the normal amount?

300-500MB RAM usage is typical for Electron applications with video.
(Note: If you have the `ambient-light` plugin enabled, it may use more memory depending on its settings)
