### ISSUE TITLE
[Feature request] WebNowPlaying integration

### ISSUE THREAD

**Issue by ghost** [th-ch/youtube-music#329]
Would be nice if it had webnowplaying for rainmeter support.

https://github.com/tjhrulz/WebNowPlaying
https://github.com/tjhrulz/WebNowPlaying-BrowserExtension
https://github.com/khanhas/spicetify-cli/blob/master/Extensions/webnowplaying.js
https://github.com/ytmdesktop/ytmdesktop/blob/master/src/providers/rainmeterNowPlaying.js

**Comment by JellyBrick** [comment]
YTMD is supported in WebNowPlaying v2 and later.
