### ISSUE TITLE
Discord integration?

### ISSUE THREAD

**Issue by C00lCr4ft24** [th-ch/youtube-music#33]
like in youtube music desktop app
pleeease

**Comment by thijsi123** [comment]
Yes I love to see an discord api.

**Comment by th-ch** [comment]
Hey @C00lCr4ft24 @thijsi123, [latest version 1.9.0](https://github.com/th-ch/youtube-music/releases/tag/v1.9.0) has a Discord plugin (credits to @semvis123), feel free to give it a try!
