### ISSUE TITLE
Can't re-enable menu

### ISSUE THREAD

**Issue by yigitsr** [th-ch/youtube-music#341]
Hello. I disabled the menu and can't enable again. I tried uninstalling and installing again but still there's no menu. How do I re-enable it? The one where the plug-ins are.

**Comment by Bellisario** [comment]
You just need to press `alt` and the menu re-appears. Now you can disable the plugin.

**Comment by Araxeus** [comment]
or `escape` if you were using the in-app-menu plugin

**Comment by yigitsr** [comment]
> You just need to press `alt` and the menu re-appears. Now you can disable the plugin.

yes, it's how it's done. Thank you for the reply

**Comment by yigitsr** [comment]
> or `escape` if you were using the in-app-menu plugin

thank you for the reply. "alt" is what I was looking for.
