### ISSUE TITLE
Alert user how to show menu after "Hide menu" enable

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#342]
Now, if you enable "Hide menu", you have some problems to show it, because you are not informed how to do. Can be very useful show to user a popup that alerts how to un-hide menu at any time, after option enabled.

**Comment by F1am** [comment]
Right clicking the small tray icon could allow you to show the menu again. That would help.

**Comment by Bellisario** [comment]
@F1am, yes, I know. This is only a suggestion to improve the app, so, I think can be useful to alert the user how to do to show menu after option enabled, just that. :wink:

**Comment by dansauve** [comment]
Now that it's hidden how DO I bring it back? I can't figure out how to get it back or how I'm supposed to access the functions without this menu.

**Comment by bshor** [comment]
I've hidden the app, and I can't figure out how to show it again. What did you do? How does the escape key help?

**Comment by Araxeus** [comment]
> I've hidden the app, and I can't figure out how to show it again. What did you do? How does the escape key help? (I'm on Linux/Gnome).

this is unrelated to this issue. answer in #409
