### ISSUE TITLE
Multiple instances created when clicking taskbar shortcut

### ISSUE THREAD

**Issue by F1am** [th-ch/youtube-music#345]
This happens in both Linuxmint & Windows: if you pin the app to the taskbar, clicking the icon will open a new instance instead of making the open instance visible.

**Comment by Araxeus** [comment]
You are probably using the portable version right?
if so - it happens because your shortcut doesn't actually point to the executable, try installing the program instead

**Comment by F1am** [comment]
Linux mint used the Deb installed version. In windows I use portable, yes. Both behave the same

**Comment by Araxeus** [comment]
I just tested with windows installed version and it works fine

**Comment by F1am** [comment]
Yes, but I cannot install it in this machine though. Any idea how to fix the linuxmint version?

**Comment by Araxeus** [comment]
Usually the OS should recognize that the shortcut leads to the open executable
I'm not really proficient in linux so I can't really help there
check that the shortcut target is actually the running executable

**Comment by F1am** [comment]
In windows if you open the portable version twice you still get a second instance, so fixing the shortcut does not work (I also tried and it does not).

**Comment by Araxeus** [comment]
Like i already said, this wont work with portable version..
it needs to be installed and the shortcut pointing to the executable in appdata

**Comment by JsephGriff** [comment]
Hey I know this is an older post, but having installed the app on the windows version with the shortcut pointing to the application in appdata, the app still opens multiple instances when set to stay in tray instead of re-opening the existing instance running in the background. Am I doing something wrong?

**Comment by aacebedo** [comment]
Same here on linux.  
If I run the command line twice, I end up with 2 instances even if it is already in the tray.

**Comment by Zo-Bro-23** [comment]
If I remember correctly, there's an option within the Options menu to force one instance only. Have you tried enabling that?

**Comment by aacebedo** [comment]
you are right, missed the parameters, it is working.
