### ISSUE TITLE
Alt key does not show menu if Alt key is used for any shortcut (in any combination)

### ISSUE THREAD

**Issue by F1am** [th-ch/youtube-music#346]
I use CTRL+Alt+S shortcut and it disables showing the menu with Alt.

**Comment by Araxeus** [comment]
what are you using this shortcut for?
how did you register it?

**Comment by F1am** [comment]
To play/pause like this:
```
{
					"shortcut": "CommandOrControl+Alt+S",
					"action": "playPause"
				}
```

**Comment by Araxeus** [comment]
global or local

**Comment by F1am** [comment]
global (thanks for the quick replies btw)

**Comment by F1am** [comment]
Ok, thanks for the feedback. Have a nice day! Love your work.

**Comment by Araxeus** [comment]
Are you guys using the `in-app-menu` plugin?

**Comment by Zo-Bro-23** [comment]
> Hey, I am currently trying to figure out how to open the global menu with bspwm, since it doesnt show up when pressing alt. Any solution?
> :D

Try Escape (the key). Works for me.

**Comment by Araxeus** [comment]
> Try Escape (the key). Works for me.

This is only with `in-app-menu` active, and also will be changed to <kbd>`</kbd> after #988

**Comment by Zo-Bro-23** [comment]
> > Try Escape (the key). Works for me.
> 
> This is only with `in-app-menu` active, and also will be changed to <kbd>`</kbd> after #988
> (since <kbd>Esc</kbd> is already used by youtube)

Right. I saw #988 and was just about to comment when you beat me to it! Somehow I thought it was `Esc` and `Alt` both with and without the plugin. My bad!
