### ISSUE TITLE
Like / dislike buttons not working

### ISSUE THREAD

**Issue by mrengy** [th-ch/youtube-music#347]
When I click "like" or "dislike" while playing a song, I see a rectangle highlight around the button, but it doesn't seem to register. There is no confirmation message like there used to be, and when I click "dislike", the song keeps playing (before, it would skip to the next song). Repeatedly clicking the "like" or "dislike" buttons just makes them change their background color but does not do anything else.

![Dislike button highlighted](https://user-images.githubusercontent.com/2223603/123831724-9cc7be80-d8d2-11eb-816c-31fef7d3b971.png)

This happened suddenly a couple of versions back (I hadn't updated and had automatic updates unchecked, so not sure what triggered it). Also I upgraded to 1.12.1 , and the issue remains.

YouTube Music v 1.12.1
Mac OS 10.15.7

**Comment by Araxeus** [comment]
https://github.com/th-ch/youtube-music/issues/336#issuecomment-868834408
(workaround for now is to disable `Options > Resume last song when app starts`)
