### ISSUE TITLE
Windows Defender blocking the exe. 

### ISSUE THREAD

**Issue by Bilan123** [th-ch/youtube-music#349]
I downloaded the client, but windows defender blocked it and it said the virus was detected.  Closing the windows defender doesn't work, too.

**Comment by thijsi123** [comment]
Yeah my web browser is also blocking it :C

**Comment by thijsi123** [comment]
B.T.W. the file got flagged as "Trojan:Win32/Emali.A!cl"

**Comment by parapsychic** [comment]
Same. What's going on?

**Comment by Araxeus** [comment]
Ill be reporting this false positive to microsoft
Does it block both installer and portable version for you guys?

**Comment by NNowakowski** [comment]
It's detecting the following for me on the Setup.exe
![image](https://user-images.githubusercontent.com/16933892/124228473-8ad16000-db0c-11eb-883f-3acfd5b736ee.png)
![image](https://user-images.githubusercontent.com/16933892/124228493-902eaa80-db0c-11eb-887d-9d0c0c0339f4.png)

**Comment by th-ch** [comment]
Hello everyone, thanks for opening the issue! It's unexpected and might be a false positive (similar to https://github.com/electron-userland/electron-builder/issues/4906), I will have a look at it in the following weeks (many dependencies were updated in the last version, that might explain this issue), in the meantime, feel free to use the previous version or build the app manually! (instructions are in the readme)

**Comment by Araxeus** [comment]
I submited the files to microsoft for review and the initial scans says its clean
![image](https://user-images.githubusercontent.com/78568641/124256906-7bfea380-db34-11eb-8eb8-07c8d750fa40.png)

https://www.microsoft.com/en-us/wdsi/submission/a673a86c-2efa-4ab3-96a3-e7ae94b4f435 (SETUP)
https://www.microsoft.com/en-us/wdsi/submission/1c65dedd-6a16-4531-b614-6f7857b77c60 (PORTABLE)

also on virustotal
https://www.virustotal.com/gui/file/c3ca88b1934a078784b15b6b68121ad34660c1d6d7568513549f8c3713797324/detection (SETUP)
https://www.virustotal.com/gui/file/5acf25406288149551ba841faf0beced0e59285c1b6a646f89e576df278c020d/detection (PORTABLE)

**Comment by Bellisario** [comment]
Now virus free from Microsoft (re-scanned from @Araxeus submission on Virustotal):
https://www.virustotal.com/gui/file/c3ca88b1934a078784b15b6b68121ad34660c1d6d7568513549f8c3713797324/detection
https://www.virustotal.com/gui/file/5acf25406288149551ba841faf0beced0e59285c1b6a646f89e576df278c020d/detection

**Comment by th-ch** [comment]
Hey everyone, thanks for the issue and the help! Closing the issue because it seems solved, I will put back the new version as the main release!

**Comment by DaveThuet** [comment]
![Screenshot 2024-09-18 084714](https://github.com/user-attachments/assets/96e9e886-9b83-4049-9115-8588e12a8544)
![Screenshot 2024-09-18 084728](https://github.com/user-attachments/assets/7b89b12d-9f14-47d7-afe0-049857b33ca9)
Hi
No chance to download and install the new Version... ☠️👾🫣
Reguards

**Comment by ArjixWasTaken** [comment]
You can temporarily disable smartscreen for Microsoft edge
