### ISSUE TITLE
No navigation after first "command"

### ISSUE THREAD

**Issue by GrzegorzWalewski** [th-ch/youtube-music#35]
After one command ex. Play I can't use shortcuts.
It's just not working. I tried changing shortcuts in keyboard settings, but non settings were working.
Linux Ubuntu 18.04

**Comment by th-ch** [comment]
Hey @GrzegorzWalewski, do you still have the issue with the [latest version 1.9.0](https://github.com/th-ch/youtube-music/releases/tag/v1.9.0)?

**Comment by GrzegorzWalewski** [comment]
Hi, now they are working.
Thanks ;)
