### ISSUE TITLE
Dark title bar for Windows Dark Mode

### ISSUE THREAD

**Issue by parapsychic** [th-ch/youtube-music#352]
On Windows Dark mode, it doesn't have Dark Title Bar. 
![image](https://user-images.githubusercontent.com/63157522/124282703-c26df580-db68-11eb-97e5-5a938d4ebb75.png)

One thing I did notice is that if I apply colors to title bars, the program also has colored title bar.
![image](https://user-images.githubusercontent.com/63157522/124282948-ffd28300-db68-11eb-93e6-4f9070270225.png)

Is this a Windows issue? 
Sidenote: will there be a Microsoft Store release down the line?

**Comment by Araxeus** [comment]
Try the plugin in-app-menu for dark title bar

**Comment by parapsychic** [comment]
> Try the plugin `in-app-menu` for dark title bar

That's much better now. Thank you.
