### ISSUE TITLE
download option not working anymore?

### ISSUE THREAD

**Issue by Artan1408** [th-ch/youtube-music#356]
Hey guys, I don't know exactly when this issue started but recently I haven't been able to get the download to work.
It says "downloading..." for a long time (like 10-15 min) then I get a error 404 saying download failed!
Tried different songs, different playlists and uninstalling/reinstalling didn't fix it either.
Appreciate it if anybody could help.

I'm using the latest version (1.12.1) - windows 10

**Comment by DahrbUwU** [comment]
i get the error 304 about 5 times when i download a playlist.

**Comment by arduinka55055** [comment]
same on manjaro using aur package. it stuck on downloading

also it says /opt/YouTube Music/resources/app.asar/node_modules/ytdl-core/lib/utils.js:175 WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".

i tried sudo npm install ytdl-core@latest, but it didnt help. also i tried injecting new ytdl-core to asar but it didnt help too


i hope you'll fix this

**Comment by arduinka55055** [comment]
UPD: injecting new ytdl-core helped

**Comment by arduinka55055** [comment]
open terminal in asar location
```bash
sudo npx asar extract app.asar destfolder             #unpack it

sudo npm install -g ytdl-core@latest                  #install good ytdl-core
sudo npm install -g --engine-strict asar              #instsall asar if you dont have it

```
move it
![https://i.imgur.com/mTgxCOd.png](https://i.imgur.com/mTgxCOd.png)

```bash
sudo mv app.asar app_old.asar

sudo asar pack destfolder app.asar
```
ENJOY downloading ur tracks

i hope i helped someone

**Comment by th-ch** [comment]
Hey everyone, thanks for the feedback! A [new version](https://github.com/th-ch/youtube-music/releases/tag/v1.12.2) has been released and should solve the issue, can you give it a try?

**Comment by Artan1408** [comment]
> 
> 
> Hey everyone, thanks for the feedback! A [new version](https://github.com/th-ch/youtube-music/releases/tag/v1.12.2) has been released and should solve the issue, can you give it a try?

The update indeed solved the issue, thank you so much :)

**Comment by th-ch** [comment]
Closing the issue as it seems solved, feel free to re-open if needed!

**Comment by arduinka55055** [comment]
btw. i cant download playlist, but can download separate songs

have u met same issue?

**Comment by Araxeus** [comment]
@arduinka55055 

if the playlist you try to download is *public*, what is the error you're getting?

**Comment by arduinka55055** [comment]
hanged on downloading... no errors in console. playlist is public https://music.youtube.com/playlist?list=PLn4IbQPBFMwjFnofhn3_R67Plpdh4gC37&feature=share (songs about git lol, for testing)

**Comment by Artan1408** [comment]
> 
> 
> hanged on downloading... no errors in console. playlist is public https://music.youtube.com/playlist?list=PLn4IbQPBFMwjFnofhn3_R67Plpdh4gC37&feature=share (songs about git lol, for testing)

Just checked and same issue here, checked with a small playlist (4 songs) too, doesn't work!
I never tried to download a whole playlist so I never noticed before, however downloading a single song still works perfectly.
