### ISSUE TITLE
apple silicon/M1 support planned?

### ISSUE THREAD

**Issue by avichou** [th-ch/youtube-music#359]
hello,this app is rly great,is there any plan on making an ARM version of it?
i know its been discussed a bit but only solution was to build it yourself and im way too dumb for it sadly...

**Comment by Bellisario** [comment]
@avichou, I don't know how to build for ARM, but for now I can say you that for Windows ARM and macOS ARM, the app is the same for no-ARM version: this is because Windows emulates the executable and macOS converts it to ARM version using Rosetta 2.
I don't know for linux...

**Comment by avichou** [comment]
> @avichou, I don't know how to build for ARM, but for now I can say you that for Windows ARM and macOS ARM, the app is the same for no-ARM version: this is because Windows emulates the executable and macOS converts it to ARM version using Rosetta 2.
> I don't know for linux...

oh i see.well if u have a mac apple seems to make things kinda easy,using xcode https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon

oh i know that it works,but its really unefficient in terms of battery usage since it uses translation .anyway its very good :)

**Comment by semvis123** [comment]
Can be build for m1 (universal or arm64) if you modify the macOS build in the package.json to this:
```json
"mac": {
  "identity": null,
  "icon": "assets/generated/icons/mac/icon.icns"
  "icon": "assets/generated/icons/mac/icon.icns",
  "target":  [
    {
      "target": "default",
      "arch": [
        "universal"
      ]
    }
  ]
},
```
