### ISSUE TITLE
No icon after locking screen

### ISSUE THREAD

**Issue by GrzegorzWalewski** [th-ch/youtube-music#36]
When i have Options -> tray -> Enabled + app hidden
After locking screen no longer app icon is in tray
Only way to close app is kill process

**Comment by th-ch** [comment]
Hey @GrzegorzWalewski, thanks for submitting the issue! I cannot reproduce on MacOS with v1.5.0, which OS are you on? Can you also test with the [latest version, 1.5.0](https://github.com/th-ch/youtube-music/releases/tag/v1.5.0)? Among other changes, electron was updated in this version so some bugs might have been fixed.
