### ISSUE TITLE
unlock unsupported regions

### ISSUE THREAD

**Issue by jojosefu** [th-ch/youtube-music#361]
I would suggest to add tor/vpn feature bcs YouTube music doesn't support my country right now it would be a nice addon

**Comment by th-ch** [comment]
Hey @jojosefu, you can configure a proxy in options (Options > Advanced options > edit config.json and then set `proxy` in `options` - a UI will land soon with https://github.com/th-ch/youtube-music/pull/243), could it solve your issue?

**Comment by jojosefu** [comment]
i've been using this method for 3 weeks everything works as intended and it's rather ez even without gui but finding a good proxy that works all the time is a pain i suggest that implementing a free vpn extension or proxy that updates itself would be a huge improvement bcs it's a lot easier and reliable for locked regions or ppl who want privacy

**Comment by konhi** [comment]
> a free vpn extension
Would you mind suggesting some extension that would fit best into this app?

**Comment by jojosefu** [comment]
sorry for being late 
i personally would suggest any form of tor implementation since it's free better for privacy and i guess it's the eziest to implement 
otherwise i use "Hoxx VPN Proxy" in firefox and it's also free
