### ISSUE TITLE
[Feature] Option to disable Windows 10 media OSD

### ISSUE THREAD

**Issue by AH-2004** [th-ch/youtube-music#371]
maybe a plugin or option in the menu to disable this:
![image](https://user-images.githubusercontent.com/84923831/128601225-afa38c1f-dea8-4209-9f72-0f84c1dd8b54.png)

**Comment by AH-2004** [comment]
Nvm I just added `app.commandLine.appendSwitch('disable-features', 'MediaSessionService');` under `const app = electron.app;` and that got the job done.

**Comment by jcl4068** [comment]
Hello,

Could you run through how you removed the WIndows 10 media OSD?

**Comment by jcl4068** [comment]
Sorry, how do I find index.js on my computer?

**Comment by Araxeus** [comment]
As of now you can just enable the `shortcuts` plugin.
It overwrites the mediakeys so the OSD will not be enabled (but the mediakeys will still work)

**Comment by Germsicle** [comment]
> PR [#243](https://github.com/th-ch/youtube-music/pull/243) added an option which can disable the overlay in menu - plugins - shortcuts - Override MediaKeys

i would never have tried that, look through all of the settings so many times and stumbled on this post.... it got rid of the annoying PIP video on the bottom right of the app. THANK YOU!!!!!
