### ISSUE TITLE
Integration with OBS Tuna

### ISSUE THREAD

**Issue by luanfsp** [th-ch/youtube-music#372]
Would be nice have this feature for streams.

![image](https://user-images.githubusercontent.com/31630621/129071214-021718a7-4a28-4423-82b3-7b4e67a18fa1.png)

**Comment by mesmerx** [comment]
i made one
https://github.com/th-ch/youtube-music/pull/397

just start webserver with default port

**Comment by mesmerx** [comment]
> Hi, when the song is playing the time left param doesn't return the correct value from YT music itself. It just returns the length of the song in both time_left and duration. I'm not sure what the issue is. Please let me know if you need any more info, I'm not sure what to include as it is a YT music (api?) problem.

yeah, i'll make a event for the progress bar, like @Araxeus  shows in the 439, maybe next week

**Comment by Araxeus** [comment]
@mesmerx I've already created a very similar event for fixes in the mpris 'plugin', so I just subscribed this plugin to that event to get updated currentTime. Could you please test if it works well ? #480

**Comment by mesmerx** [comment]
yeah i saw the PR i`ll try that ASAP, great work man

**Comment by awan-gh** [comment]
When i stop / pause the music, the status of the playback on http://localhost:1608/ just stays on 'playing', even if i close the ymusic it'll still showing the last song title and what not, how can i fix this?

**Comment by DreiLuna** [comment]
does the cover image work? becuase I can seem to get it working rn.
