### ISSUE TITLE
Downloader not working

### ISSUE THREAD

**Issue by glisteningcoder** [th-ch/youtube-music#379]
I had been using the downloader for quite a while but now it always returns with this code: 
![image](https://user-images.githubusercontent.com/66782694/129449395-0fc10c61-5635-4083-b36f-460bfe5d1339.png)
![image](https://user-images.githubusercontent.com/66782694/129449406-cfb60f26-5ad8-4659-8411-0f38cf621a0e.png)
I have tried reinstalling the app but it still didn't work.

**Comment by kineotech** [comment]
I also cannot download a playlist. I get the following:

![image](https://user-images.githubusercontent.com/16126626/129947006-9370762f-85cd-467f-add8-66b30df37edf.png)

**Comment by Araxeus** [comment]
> I also cannot download a playlist. I get the following:
> 
> ![image](https://user-images.githubusercontent.com/16126626/129947006-9370762f-85cd-467f-add8-66b30df37edf.png)
> 
> The ID will change based on, I think, the playlist I have playing.

It can only download *public* playlist, also yes - it try downloading the currently playing playlist

**Comment by kineotech** [comment]
OK, so I made the playlist public and started downloading the current (public) playlist. 

Now what I get is a dialog box that shows:

![image](https://user-images.githubusercontent.com/16126626/132063439-f6ca851b-efd3-4bb5-a322-62443e3ce775.png)

A new one appears after what I assume is the completion of a song download. I have checked filesystem permissions and all appears good. I am running this app on Arch/Manjaro.

Thanks for any help.

**Comment by kineotech** [comment]
Please? Anyone?

I made the playlist public and started downloading the current (public) playlist.

Now I get is a dialog box that shows a 403 error:

image

A new one appears after what I assume is the completion of each song download. I have checked filesystem permissions and all appears good. I am running this app on Arch/Manjaro.

Thanks for any help.
