### ISSUE TITLE
Touchbar support

### ISSUE THREAD

**Issue by k4sud0n** [th-ch/youtube-music#39]
What a useful app :D

I wish when this app supports touchbar, it would be way more better. (Like displaying song's name..like, dislike etc)

**Comment by semvis123** [comment]
Something like this?
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/28219076/102337768-3234de00-3f93-11eb-828d-5a291cb1fc20.png">
PS: It would be great, If anyone got better icons / characters to but in the buttons.

**Comment by semvis123** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/28219076/102391381-ed7e6680-3fd5-11eb-9042-dbb15fe7be25.png">
Even added images

**Comment by semvis123** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/28219076/102393371-91691180-3fd8-11eb-86e8-7cadf253a118.png">
Sorry for the spam but likes and dislikes are now also possible

**Comment by k4sud0n** [comment]
Awesome 👏

**Comment by th-ch** [comment]
Closing the issue as TouchBar has been added (credits to @semvis123)!
