### ISSUE TITLE
Stops at "Adding metadata..."

### ISSUE THREAD

**Issue by oldvalley49** [th-ch/youtube-music#390]
The downloader stops making progress at the "Adding metadata..." part. 
I downloaded 1.12.2 but it has been like this for a while for me. 
Any ideas on how to fix this?
I have a macOS with Big Sur

**Comment by AriKnight** [comment]
> The downloader stops making progress at the "Adding metadata..." part.
> I downloaded 1.12.2 but it has been like this for a while for me.
> Any ideas on how to fix this?
> I have a macOS with Big Sur

had same problem and same app version on windows 10 pro
![image](https://user-images.githubusercontent.com/43218677/130423333-8cc4273c-7330-4a0e-adbe-a9125c9f41a5.png)

stuck at converting and never finished
![image](https://user-images.githubusercontent.com/43218677/130423446-05d3b759-c601-4d82-9b1e-732d6c4b49fd.png)

**Comment by th-ch** [comment]
Hey @oldvalley49 and @AriKnight, v1.1.4.0 has been released and includes many fixes, can you give it a try and see if the issue is still there?
