### ISSUE TITLE
[Windows] App logo is low quality

### ISSUE THREAD

**Issue by pratyakshm** [th-ch/youtube-music#391]
Really no idea how nobody noticed this, but app icon is too blurry. This is how it looks on the taskbar:
![image](https://user-images.githubusercontent.com/54220235/130446317-a2f13c43-3c3e-4325-9982-5937a7b7d0ec.png)
For comparison, this is  the app icon of PWA YTMusic installed via Microsoft Edge:
![image](https://user-images.githubusercontent.com/54220235/130446498-c1848355-766f-4b3d-9cd2-7e332885dc2e.png)

**Comment by im-coder-lg** [comment]
Also could be since it's an ico file, but getting the favicon and replacing the existing image with that might work

**Comment by pratyakshm** [comment]
Well I am going to close this as it's stale.
