### ISSUE TITLE
Discord Rich Presence does not resume after timeout

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#400]
Is this intentional behavior? 

Steps: 
Play a song with the rich presence plugin enabled (it'll show you listening on discord)
Pause the song past the timeout limit defined in the config file (rich presence disappears) 
Resume song 
Rich presence does not come back 

EDIT:
Changing `			"activityTimoutTime":` to `-1` has fixed this.

**Comment by cpiber** [comment]
There is a bug in how the discord rich presence is updated, I already have a PR #380 to fix this
