### ISSUE TITLE
App disappeared into tray

### ISSUE THREAD

**Issue by bshor** [th-ch/youtube-music#409]
I have Youtube-Music installed into Garuda Linux (arch-derived) with Gnome Desktop.

I experimented with the tray and hiding the app, and now I can't see or control the app except with my keyboard shortcut keys. There is no tray icon for control. I even tried uninstalling and reinstalling, but the same problem.

![image](https://user-images.githubusercontent.com/468070/133937842-27ef8560-157f-46ee-9df0-9f0e0cf6638d.png)

The only thing I see is a small version in notifications. It looks like this:

![image](https://user-images.githubusercontent.com/468070/133937809-0428c63d-f6c5-42bc-bca0-7c4a117353ec.png)

But there's no way bring up the app. Perhaps tray doesn't work with Gnome, but in any case I want the plain old interface back.

**Comment by Araxeus** [comment]
check out `config.json` - it should be in the temporary app folder (not sure on linux but on windows its in `AppData/Roaming/Youtube Music`

in that file, find the line that says `"tray": true,` and change it to `"tray": false,`

**Comment by bshor** [comment]
Great hint! I found `config.json` in `~/.config/Youtube Music`. I had to set tray to false and visible to true. I killed all existing processes and started up the app and it all worked.

I think Tray is only for Windows, so this is a bit of a danger for Linux users.
