### ISSUE TITLE
top toolbar does not show up when "In App Menu" is turned on

### ISSUE THREAD

**Issue by gord29** [th-ch/youtube-music#410]
![image](https://user-images.githubusercontent.com/69841307/133949984-65d48e6d-6ded-48e0-b422-b445acfdab8e.png)
When i turn on "In App Menu", the bars at the top disappear. now I can't change or turn on or off the plugins. I tried clicking at the top for the menu to show up just in case if the text was just black but nothing happens.

UPDATE: It reappears when I try to play on fullscreen then close. now I have to do that every time I open the app.

**Comment by Araxeus** [comment]
Do you maybe have "hide menu" option enabled?

I have no idea why would this happen if not :O
