### ISSUE TITLE
Youtube "Switch Account" menu option broken

### ISSUE THREAD

**Issue by brennana** [th-ch/youtube-music#413]
Greetings,

It seems that under the Google/Youtube account menu, the "Switch Account" menu option, which navigates to a submenu to choose other YT accounts under the same Google account, does not open when clicked. In the image below, this behavior is shown after having clicked "Switch account" to no avail.

![image](https://user-images.githubusercontent.com/2296096/134224412-a2474735-9405-4f9e-a598-4ac879478b81.png)

As a temporary measure, I was able to copy the chromium cookie store from another YTM client I was using, but it would be nice to have the "Switch account" submenu working in case my authentication cookies expire (my YTM likes/recommendations are on a specific YT account that I was forced to create for YTM).

Versions tested: 1.12.2 and 1.13.0
Platform: x64 Arch Linux (Manjaro) on KDE

**Comment by ExpertNugget** [comment]
also got this problem

**Comment by kishikaisei** [comment]
Same issue in here and I am on windows!

**Comment by Araxeus** [comment]
It also used to not work for me, but for some reason it works on the new app version (maybe they fixed it?)

**Comment by kishikaisei** [comment]
I confirm it works on 1.14.0 (you have to build it yourself though).

**Comment by Araxeus** [comment]
My guess is that electron version made the difference. 

Anyways v1.14 should be released relatively soon

**Comment by Araxeus** [comment]
Ok v1.14 has been released and fixed this.

Could please close this issue?

**Comment by brennana** [comment]
Thanks for the update, I can also confirm that this menu behaves appropriately on 1.14.
