### ISSUE TITLE
Music pauses and prompt saying "Video Paused - Continue Watching?" appears

### ISSUE THREAD

**Issue by sanyogthescholar** [th-ch/youtube-music#417]
Just as the title say, the music will randomly pause in between and the following will appear when I open the YouTube Music app
![image](https://user-images.githubusercontent.com/50242941/134979029-2d951fbc-bbf6-49f8-9699-d8933740fd54.png)
The media keys do not work unless I manually click on "Yes"
I am using version 1.12.2 on Windows 10 20H2 with the following plugins enabled
* adblocker
* disable-autoplay
* in-app-menu
* last-fm
* navigation
* sponsorblock

**Comment by Araxeus** [comment]
have you thought to enable the `Auto confirm when paused` plugin?

**Comment by sanyogthescholar** [comment]
> enable `Auto confirm when paused` plugin? 🤣 [description on main page](https://github.com/th-ch/youtube-music#:~:text=Auto%20confirm%20when%20paused%3A%20when%20the%20%22Continue%20Watching%3F%22%20modal%20appears%2C%20automatically%20click%20%22Yes%22)

Thanks, sorry I didn't notice it
