### ISSUE TITLE
Disable volume overlay

### ISSUE THREAD

**Issue by jcl4068** [th-ch/youtube-music#424]
How do you disable volume overlay?
There was a previous issue on this but I don't understand how they did it.
Thanks

**Comment by Araxeus** [comment]
What volume overlay are you talking about?

https://github.com/th-ch/youtube-music/pull/275 the one I added wasn't even merged yet :0

**Comment by jcl4068** [comment]
The windows 10 media OSD like here: https://github.com/th-ch/youtube-music/issues/371

**Comment by jcl4068** [comment]
@AH-2004 Sorry where can I find index.js on my computer?

**Comment by AH-2004** [comment]
@jcl4068 you would need to clone the repository and add that line of code into index.js then you will need to build it using node & electron builder
