### ISSUE TITLE
Menu bar appearing during fullscreen

### ISSUE THREAD

**Issue by ejabno** [th-ch/youtube-music#43]
Hi, great app. I just have one small problem with it... the menu bar is still visible for some reason when I tell this app the go full screen. There doesn't seem to be an option to get rid of this. Running on windows 10
![fullscreenbug](https://user-images.githubusercontent.com/15706915/92346275-845b8e80-f089-11ea-9ca2-fff83f7ef38b.png)

**Comment by th-ch** [comment]
Hey @ejabno, thanks for the feedback! Latest release, [v1.6.2](https://github.com/th-ch/youtube-music/releases/latest), should auto-hide the menu bar, does that solve your issue?

**Comment by th-ch** [comment]
Closing the issue now that the option is available, feel free to re-open if needed!

**Comment by Kotaless** [comment]
> Closing the issue now that the option is available, feel free to re-open if needed!

Hi. Was `autoHideMenuBar` option removed? I don't see it in my config.

**Comment by inson1** [comment]
yes, I cant find it too + "Menu bar appearing during fullscreen" doesnt look good

**Comment by inson1** [comment]
@JellyBrick How to get rid of the menu only on full screen?

**Comment by inson1** [comment]
@JellyBrick its fixed in the new version that isnt released yet? if not may you reopen it?
