### ISSUE TITLE
System tray icon missing on Wayland

### ISSUE THREAD

**Issue by RealSaltyFish** [th-ch/youtube-music#438]
When I enable system tray in youtube-music, no icon appear in the tray. If I kill the window, the playback continues in the background but I have no way to regain access to the session.

This should be a libappindicator-related issue because I see this when I start youtube-music from the command line:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

(youtube-music:890444): libappindicator-WARNING **: 18:10:06.583: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

(youtube-music:890444): LIBDBUSMENU-GLIB-WARNING **: 18:10:06.583: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
APPIMAGE env is not defined, current application is not an AppImage
```

OS: Arch Linux (installed youtube-music-bin from AUR)
WM: Sway
System tray: Waybar

**Comment by RealSaltyFish** [comment]
Resolved by updating.

**Comment by Araxeus** [comment]
> Resolved by updating.

updating what?
