### ISSUE TITLE
Create Android app

### ISSUE THREAD

**Issue by 66Ton99** [th-ch/youtube-music#457]
Would be nice to create port for Android phones :)

**Comment by senolfndk** [comment]
try this you can download mp3 or video https://ymusic.io/

**Comment by im-coder-lg** [comment]
> @im-coder-lg don't you enjoy some of the wonderful plugins in this app?

Yes, I like a notification on my next song, a no sign-in button, and some more plugins. But I don't understand this, why do you need a YouTube Music app for Android, when you already have it? You could set up a nifty software called Pi-Hole to block ads on all apps, but what's the point of recreating an existing app?

**Comment by Araxeus** [comment]
https://youtubevanced.com/#features

**Comment by stefanschlipfi** [comment]
Use this app instead [Vanced APP](https://vancedapp.com/)

**Comment by Araxeus** [comment]
> Use this app instead [Vanced APP](https://vancedapp.com/)

thats literally what I said in my last 3 messages? O_o

**Comment by im-coder-lg** [comment]
Yeah, I don't need an app for my phone, but I definitely can use one for the laptop, so Vanced doesn't seem a good idea for phones(for me).

**Comment by LosNormalis** [comment]
Well now, since Vanced was discontinued, I would like to have an alternative for the Vanced Music once it eventually gets outdated. I would also love to have something to control my music from phone, like Spotify.

**Comment by briantho** [comment]
> Well now, since Vanced was discontinued, I would like to have an alternative for the Vanced Music once it eventually gets outdated. I would also love to have something to control my music from phone, like Spotify.

I too think that this would be quite useful, not just for android on the phone, but also android tv. android tv is something that vanced never supported, and now that's its discontinued never will support. Right now I've got this software installed on a htpc desktop, but i would absolutely love to get this working on a fire tv. What do the devs say? now that vanced is discontinued, what about actually doing this? or is this simply a pipe dream....

**Comment by MulverineX** [comment]
Everyone, [https://github.com/revanced](https://github.com/revanced)! They will be continuing the YTM mod and it will be open source this time! This project (th-ch/youtube-music), is completely irrelevant as it is web-based and the android app is a java/flutter program. Even if Vanced wasn't being continued by this group linked, a YTM Android mod request would still not belong here.

**Comment by Zo-Bro-23** [comment]
Although not an Android app, #1094 introduces an Android remote that allows you to control songs using your phone.
