### ISSUE TITLE
[Feature Request] Integration into the Windows 10 and 11 Media Service and a required restart indicator

### ISSUE THREAD

**Issue by Thisisauser6443** [th-ch/youtube-music#466]
Before I tell you what I have in mind, I have to say that this app is really nice - I don't typically like using Chrome (and its site-to-app function) to access places which really should officially have a fully-fledged Win32 or UWP app, so this really cut me some slack into going Incognito just so YT didn't clog up my recent pages, and the plugins just add to the helpfulness.

## **Windows 10 and 11 Media Service**
Basically, it's that feature where you get to have a minimalist sort of player control UI on Windows 10 and 11. 

<details><summary>Demo of the Windows 11 Media Service Player:</summary>
<br>

![Screenshot 2021-11-01 212819](https://user-images.githubusercontent.com/75092921/139744627-f5934dd8-d3bb-4c80-b078-6b4e68de989b.png)
</details>

<details><summary>Demo of the Windows 10 Media Service Player:</summary>
<br>

![sx2Wc](https://user-images.githubusercontent.com/75092921/139744704-5ba9aeff-0b53-4840-bb6f-a2fb6da33776.png)
</details>

And I know it's possible to have this work on both, as someone else who had done a YT Music desktop client had got this working on both 10 and 11 from prolonged personal usage (Maybe the service wasn't altered at all by Microsoft?), although I'm not sure if Adler Luiz actually tried to adapt YTMD to Windows 11, in the first place - Either way, it is a helpful feature to have if you don't want to find yourself going to the tray frequently, or (if like me) your media control keys were partially dysfunctional.

## **Required restart indicator (for changes to enabled/disabled plugins/settings)**
I also couldn't help noticing that there wasn't (or at least I couldn't, unless I'm just incredibly dumb) a prompt to restart the app on some settings like 'Disable hardware acceleration' which from past experience I knew would require a restart to apply that change.

_(For the record, idk if anyone else suggested these 2 features, but they've benefitted me quite a bit, and I would like to see it in the app)_

**Comment by Araxeus** [comment]
> Windows 10 and 11 Media Service

The windows 10 one is enabled by defualt, and i except the win11 one to work too

You probably enabled the old version of `shortcuts` plugin which disable that feature
(Will be fixed in next app release)

> Required restart indicator

You should know that 99% of the options here (including all plugins) take effect only on restart, its just how everything was coded

**Comment by Thisisauser6443** [comment]
> You should know that 99% of the options here (including all plugins) take effect only on restart, its just how everything was coded

Ok, fair enough, I probably should have known that. Besides, it's fine, I'm sure it's probably not THAT useful (slightly in general, but I guess it REALLY helped me out.)

> (But anyways the osd is displayed only when using the media keys so I dont know how its helpful)

Not in Windows 11 (maybe that was only applicable to the pre-alpha builds?). They completely moved the whole thing from the vertical volume bar to the new Action Centre. Tbh, I kind of prefer just going to there instead of going to the icon drawer several times (I don't like several apps open in the virtual desktop, personally), although I perfectly understand why people may have a different viewpoint on that.

> You probably enabled the old version of shortcuts plugin which disable that feature

I see. I should probably consider closing this out then... Danke for the clear-up.

**Comment by Araxeus** [comment]
So that was it? is your media center working fine now?

**Comment by Thisisauser6443** [comment]
Seems like it, other than my dysfunctional media keys acting up again xD (I can leave that alone, Dell doesn't do well anyway)
Again, thanks m8 :)

**Comment by Araxeus** [comment]
Could you close this issue? 🙂

**Comment by Thisisauser6443** [comment]
Oh, sure :)
(Guess I probably forgot to in the first place)

**Comment by Thisisauser6443** [comment]
And yeah, I've updated - Things are working smoothly 
:)
