### ISSUE TITLE
Discord doesn't get music info right after the app is minimized to tray

### ISSUE THREAD

**Issue by FiestaLake** [th-ch/youtube-music#472]
## Issue
The app reports info to Discord correctly whether it is minimized or not. However when I close the app's window and it gets minimized to tray icon, Discord removes the status of music info. It gets music info again when the next music begins.

## Environment
Gnome 40.5, Arch Linux, with appindicator extension.
youtube-music-bin 1.14.0-1

## How to reproduce
1. Discord should be opened, whether it is minimized to tray or not. 
2. Enable tray option in youtube-music app.
3. Restart the music app, play some music, and check Discord whether it's getting correct music info.
4. Close youtube-music (= Minimize to tray icon), and check Discord again.

**Comment by Araxeus** [comment]
I have opened a PR which will fix and automatically close this issue.

thanks for the feedback :)

**Comment by FiestaLake** [comment]
> I have opened a PR which will fix and automatically close this issue.
> 
> thanks for the feedback :)

Thanks ^^

**Comment by DereC4** [comment]
Thanks, this was something I noticed too
