### ISSUE TITLE
Discord Presence 

### ISSUE THREAD

**Issue by SenseiNero** [th-ch/youtube-music#48]
I love this soo much... thank you <3
Can you please integrate a discord presence.
Please 🙇

**Comment by BLANK-TH** [comment]
Wasn't this requested here? #33

**Comment by semvis123** [comment]
#124

**Comment by th-ch** [comment]
Hey @SenseiNero, [latest version 1.9.0](https://github.com/th-ch/youtube-music/releases/tag/v1.9.0) has a Discord plugin (credits to @semvis123), feel free to give it a try!

**Comment by JustOptimize** [comment]
@th-ch why didn't you close this issue?
