### ISSUE TITLE
Discord Plugin

### ISSUE THREAD

**Issue by RaveVR** [th-ch/youtube-music#482]
Can you tell me exactly where to get this plugin and what is it called?

**Comment by Araxeus** [comment]
![image](https://user-images.githubusercontent.com/78568641/141191164-10688e7b-0957-4bca-8c44-984413096581.png)

**Comment by RaveVR** [comment]
OK and why i dont have any of these in my youtube music App?

**Comment by Araxeus** [comment]
please explain more clearly... what don't you have

**Comment by RaveVR** [comment]
I dont have tabs Plugins Options View Navigations

**Comment by Araxeus** [comment]
what OS are you on?
try pressing `alt` or `escape`

**Comment by RaveVR** [comment]
SHEESH thanks xD

**Comment by Araxeus** [comment]
you had "hide menu" enabled in the options. you should probably disable that

**Comment by RaveVR** [comment]
i didnt know, so i downloaded plugins from Better Discord page

**Comment by RaveVR** [comment]
ok i will check and then i will close issue

**Comment by RaveVR** [comment]
OMG thanks a lot xD, it working, you are the best =D
