### ISSUE TITLE
ShortCut Key & System Tray Control Broken

### ISSUE THREAD

**Issue by criticalsoft** [th-ch/youtube-music#483]
Previous Track Is Pause Now
Next Track Is Previous 10 Second

**Comment by Araxeus** [comment]
what are you talking about?

if you press `j` does it switch to the next track?
 `k` previous track?

**Comment by criticalsoft** [comment]
What are you talking about YouTube Next Song shortcut key is Shift + n Previous shortcut key is Shift + p.
Ok, I Submited A Fix About This.
https://github.com/th-ch/youtube-music/pull/485

**Comment by Araxeus** [comment]
obviously you have different keybinds for some reason...

can you say what OS are you on?

**Comment by criticalsoft** [comment]
> 
> 
> obviously you have different keybinds for some reason...
> 
> can you say what OS are you on?

Windows 10

**Comment by Araxeus** [comment]
Well that's weird since i'm only win10 too. no idea why you have different keybinds but ill make a pr that control the songs without using any keybinds

**Comment by Araxeus** [comment]
any other currently existing shortcuts that don't work as intended on your machine?

**Comment by criticalsoft** [comment]
> 
> 
> any other currently existing shortcuts that don't work as intended on your machine?

I Just Need Play Pause Next Previous So Far. Sorry I didn't test other keys.

**Comment by criticalsoft** [comment]
> 
> 
> Well that's weird since i'm only win10 too. no idea why you have different keybinds
> 
> but anyways ill make a pr that control the songs without using any keybinds

What's the year ?

**Comment by Araxeus** [comment]
> I Just Need Play Pause Next Previous So Far. Sorry I didn't test other keys.

Could you please test all shortcuts whenever you have time so that I know which actions to change?

> What's the year ? Are We in the same time zone ?

2021? what kind of question is that? O_O
timezone is gmt +2 but I don't see why that would be relevant either

**Comment by criticalsoft** [comment]
> 
> 
> > I Just Need Play Pause Next Previous So Far. Sorry I didn't test other keys.
> 
> Could you please test all shortcuts whenever you have time so that I know which actions to change?
> 
> > What's the year ? Are We in the same time zone ?
> 
> 2021? what kind of question is that? O_O timezone is gmt +2 but I don't see why that would be relevant either

I mean are we in the year.

**Comment by criticalsoft** [comment]
https://support.google.com/youtube/answer/7631406?hl=en

**Comment by criticalsoft** [comment]
Normal YouTube ShortCut Key Is Shift + P / N
YouTube Music Premium ShortCut Key Is J / K

**Comment by criticalsoft** [comment]
And thanks for your patience.

**Comment by Araxeus** [comment]
> YouTube Music Premium ShortCut Key Is J / K

correction: Youtube Music Shortcut keys are J / K (this isn't premium related at all)

**Comment by criticalsoft** [comment]
> 
> 
> > YouTube Music Premium ShortCut Key Is J / K
> 
> correction: "Youtube Music Shortcut keys are J / K"
> 
> This isn't premium related at all

https://github.com/th-ch/youtube-music/pull/485#issuecomment-967161270

**Comment by criticalsoft** [comment]
Information Get From https://github.com/th-ch/youtube-music/pull/485#issuecomment-967148463 Is:
The ShortCut Key Is The Same.
