### ISSUE TITLE
Fading blur navbar

### ISSUE THREAD

**Issue by Ibaii** [th-ch/youtube-music#490]
Hi, i just love the app.

I love the blurry navbar but I am the only one that´s noticing that the blur fades out when going upwards?

![image](https://user-images.githubusercontent.com/30672316/141694978-931852c3-384f-441f-99b3-0c83ff25f684.png)

**Comment by Araxeus** [comment]
Thank you for the bug report, I've now made a pull request that fixes this issue :)

**Comment by Ibaii** [comment]
Hi again!

I just updated to the pre-release 1.15.0.

The blurry navbar looks good. But it have a bug when I am in homepage.

https://user-images.githubusercontent.com/30672316/147856562-68bdfae1-0c17-4028-9377-d3a904bdbc94.mp4
