### ISSUE TITLE
Ad-Blocker Doesn't seem to work

### ISSUE THREAD

**Issue by Roshians** [th-ch/youtube-music#494]
After The Latest Update, The Ad-blocker has Stopped Working For Me. I have it checked but still I get Ads.

**Comment by JoshAtticus** [comment]
Use the last version

**Comment by r1di** [comment]
Can confirm. 
Doesn't work, at least here in Germany I get ads

**Comment by c3101** [comment]
Ditto, version 1.14.0, getting bombarded by ads.

**Comment by Araxeus** [comment]
> Ditto, version 1.14.0, getting bombarded by ads.

v1.15.0 pre-release works perfectly for me
