### ISSUE TITLE
Discord plug-in doesn't work

### ISSUE THREAD

**Issue by Lysime** [th-ch/youtube-music#496]
I use the latest release of the app and Ubuntu 21.10.
I activated the Discord plug-in on the app but it doesn't show up on my DIscord profile, and when I try to reconnect this pop-up appears.
![image](https://user-images.githubusercontent.com/94706327/142667740-d772e4ff-28c6-4bc9-a5e0-67287b29357d.png)
Is there anything I might have not done properly?

**Comment by Araxeus** [comment]
If you're willing to help me troubleshoot this (by either building yourself or I could send you compiled binaries)
add me on discord Araxeus#0819

**Comment by Lysime** [comment]
What's the last digit of your tag?

**Comment by Araxeus** [comment]
Araxeus#0819

sorry i just clicked my discord name and it automatically copied it like this

**Comment by Lysime** [comment]
Request sent

**Comment by Araxeus** [comment]
For future reference the error code is
```cmd
Error: Could not connect
    at Socket.onerror (youtube-music/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
at
https://github.com/discordjs/RPC/blob/6f83d8d812c87cb7ae22064acd132600407d7d05/src/transports/ipc.js#L35-L39

that means the discord rpc encountered an error while doing `net.createConnection(path)`
which means discord-rpc could not connect to discord-desktop
