### ISSUE TITLE
Error: No playlist ID found

### ISSUE THREAD

**Issue by ryuuseeii** [th-ch/youtube-music#497]
Hello, im trying to download a playlist but it always fails. Downloading songs individually works though. I've set the playlist public and restarted the app. App version is 1.14.0. 
![image](https://user-images.githubusercontent.com/81773456/142727851-0a35211d-f996-478b-8bbc-3618f982bf2b.png)

**Comment by Araxeus** [comment]
send here the playlist link please

**Comment by ryuuseeii** [comment]
https://music.youtube.com/playlist?list=PLUm7c_VCZ8dAAfZqDEC1KKcf6XYhwe2Fe&feature=share

**Comment by Araxeus** [comment]
Ok so this bug is happening because one the latest updates to `song-info.js` removed playlist info from the url (the point was that discord shouldn't send to the playlist when clicking the play-along button)

Thanks for the report, it will be fixed soon 🙂

**Comment by ryuuseeii** [comment]
Okay thanks! Looking forward to it.
