### ISSUE TITLE
Some keys don't work with shortcuts plugin

### ISSUE THREAD

**Issue by francislavoie** [th-ch/youtube-music#499]
I'm trying to set up a shortcut for play/pause with this shortcut:

```
Ctrl + `
```

But instead, it displays `Ctrl + "` in the input box. The shortcut doesn't do anything after saving. Something weird is going on there.

I'm on Windows 10, ENG US keyboard layout. The backtick key is the one to the left of the `1`, above `TAB` on my keyboard.

**Comment by francislavoie** [comment]
Aha, found the problem, it was actually setting the hotkey to `Ctrl + "`, so hitting `Ctrl + Shift + '` on my keyboard (which is effectively `Ctrl + "` because `Shift + '` -> `"`) would trigger the shortcut instead. Upstream bug in https://github.com/Araxeus/custom-electron-prompt I think.

**Comment by Araxeus** [comment]
Thanks, your pull request has been merged and published

PR #476 should fix this issue
