### ISSUE TITLE
Display current song in volume bar

### ISSUE THREAD

**Issue by Wxrlds** [th-ch/youtube-music#50]
Currently when music plays and you increase the volume you only see the volume like this:
![grafik](https://user-images.githubusercontent.com/42120270/95740865-8a96e900-0c8d-11eb-9f02-128e30ac0f27.png)

It would be nice if the currently playing song could be displayed there.
Groove Musik for example adds songs to there.
![grafik](https://user-images.githubusercontent.com/42120270/95741571-c3838d80-0c8e-11eb-8f34-aa17b75093b9.png)

I don't know if this is possible with Linux or Mac but I know it's possible with Windows 10

**Comment by th-ch** [comment]
Hey @Wxrlds, thanks for submitting the issue! This [next release - v1.6.0](https://github.com/th-ch/youtube-music/releases/tag/v1.6.0) adds a notifications plugin, feel free to test it out (it's a pre-release at the moment) and update the issue!

**Comment by Wxrlds** [comment]
The notification plugin works but still has some minor bugs.
When a playlist runs everything seems to work fine. If a playlist is running and you search for a specific song and play that song, it fails to display the song and only shows the cover of the previously played song. (In this case the cover is from "Alone" but I searched and played "Scared to Be Lonely")
![grafik](https://user-images.githubusercontent.com/42120270/98813293-3d409f80-2424-11eb-8cc8-24abf81943fa.png)
Furthermore, it says "electron.app.YouTube Music" instead of probably only "YouTube Music".
Moreover, the cover is stretched and looks a little weird.
While the notification is on screen the Playlist and Shuffle Playlist buttons don't work.
Those: 
![grafik](https://user-images.githubusercontent.com/42120270/98820390-649c6a00-242e-11eb-9d7c-6a5ac6d44ccd.png)


That's it for now. If I find any more issues I'll report them.

**Comment by 4DEATH** [comment]
The fix released is not the one asked by the OP. OP wanted this: https://www.tenforums.com/sound-audio/134123-windows-10-volume-bar-top-left-huge.html

I think its called "Windows 10 Media Control Overlay"

**Comment by Wxrlds** [comment]
As 4DEATH said, the notification wasn't what I originally suggested but I assume th-ch just wanted to let me know that this feature exists because they're somehow related to each other

**Comment by rafaeloliveira00** [comment]
Hello there, I think you are referring to the Media Session API, here is a simple example: https://googlechrome.github.io/samples/media-session/audio.html

It would also display an layout to control the song when the screen is locked (at least on Windows 10) and perhaps fixing the following issue: #36 

It would be indeed a good feature and this feature is not related to the notifications plugin, they are 2 different things.

**Comment by Araxeus** [comment]
I will try to implement this as a custom plugin for now, if Electron supports it
