### ISSUE TITLE
Error after installing the setup

### ISSUE THREAD

**Issue by CallMeAl3x** [th-ch/youtube-music#501]
Hello, I'm having a trouble to install the app, I downloaded the last version of it and after I launch it says this and again if I relaunch it (the .exe)
(sorry for my bad english i'm french)

![image](https://user-images.githubusercontent.com/94863994/142916960-cd21881b-ac2e-44a0-a983-0d9c02482c0a.png)

**Comment by Araxeus** [comment]
Can you please send here the content of `C:\Users\Alexandre\AppData\Roaming\YouTube Music\config.json`

**Comment by CallMeAl3x** [comment]
{
	"window-size": {
		"width": 1042,
		"height": 834
	},
	"url": "https://music.youtube.com/watch?v=XlrWmtUdoOk&list=LM&index=0",
	"options": {
		"tray": true,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": true,
		"startAtLogin": true,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": true,
		"resumeOnStart": true,
		"proxy": "",
		"hideMenuWarned": true
	},
	"plugins": {
		"navigation": {
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"shortcuts": {
			"enabled": true
		},
		"downloader": {
			"enabled": true,
			"ffmpegArgs": [],
			"downloadFolder": "E:\Musiques"
		},
		"last-fm": {
			"enabled": false,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
			"api_key": "04d76faaac8726e60988e14c105d421a",
			"secret": "a5d2a36fdf64819290f6982481eaffa2",
			"token": "HJxFS3fMUwtcrph25HHyg_Abq126MkGF"
		},
		"discord": {
			"enabled": true,
			"activityTimoutEnabled": true,
			"activityTimoutTime": 600000,
			"listenAlong": true
		},
		"notifications": {
			"enabled": true,
			"unpauseNotification": false,
			"urgency": "normal",
			"interactive": false
		},
		"precise-volume": {
			"enabled": true,
			"steps": 1,
			"arrowsShortcut": true,
			"globalShortcuts": {
				"enabled": false,
				"volumeUp": "Shift+PageUp",
				"volumeDown": "Shift+PageDown"
			},
			"savedVolume": 45
		},
		"in-app-menu": {
			"enabled": true
		},
		"touchbar": {
			"enabled": true
		},
		"taskbar-mediacontrol": {
			"enabled": true
		},
		"auto-confirm-when-paused": {
			"enabled": true
		},
		"video-toggle": {
			"enabled": true,
			"forceHide": true
		},
		"audio-compressor": {
			"enabled": true
		},
		"lyrics-genius": {
			"enabled": true
		},
		"quality-changer": {
			"enabled": true
		},
		"sponsorblock": {
			"enabled": true
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.14.0"
		}
	},
	"window-position": {
		"x": 388,
		"y": 168
	},
	"window-maximized": false
}

**Comment by Araxeus** [comment]
Are you saying you never touched this file?

this section is really weird, pretty sure it wasn't made like this by itself
```json
"precise-volume": {
  "enabled": true,
  "steps": 1,
  "arrowsShortcut": true,
  "globalShortcuts": {
    "enabled": false,
    "volumeUp": "Shift+PageUp",
    "volumeDown": "Shift+PageDown"
  },
"savedVolume": 45
},
```

globalshortcuts section shouldn't have this "enabled" line, and im pretty sure there are other errors here

so you could just delete this file and it should re-generate for you a default config

**Comment by CallMeAl3x** [comment]
Thanks, It worked i don't know why the file got changed maybe because I wanted to install the new version and it keeped the previous setting
Is there a fast way to check if i'm in the good version?

**Comment by CallMeAl3x** [comment]
Thanks, It worked, I think the fact that I had a previous version before fucked up all, thanks anyway i'm using your app from a long time and really appreciate it!
