### ISSUE TITLE
Stuck on repeat of a single song

### ISSUE THREAD

**Issue by mrengy** [th-ch/youtube-music#502]
When I search for an artist and click "start radio" or when I go to Home > mixed for you: moods, and press play on one of the mixes, it shows many songs under "up next" but just repeats the first one in the list after it finishes. I have to click "next song" to advance to the next one. 

This behavior is new. It used to advance to the next song in the list automatically. Did I activate some "repeat" mode unknowingly?

Console is showing nothing that seems relevant at first glance.

YouTube Music Version 1.14.0
Mac OS 10.15.7

Plugins enabled:

1. adblocker
2. navigation
3. shortcuts
4. video toggle

**Comment by Araxeus** [comment]
Thats really weird since our app (and those plugins) don't interact with your playlists so it really shouldn't happen (Also I can't replicate this)

Can you check if maybe you have the same behavior in the browser?

or maybe by some chance you activated repeat mode in youtube?
![image](https://user-images.githubusercontent.com/78568641/144281790-348ec35c-3c98-4094-a37f-95087443699b.png)

**Comment by mrengy** [comment]
Oh, I see. The repeat mode was activated (per your earlier screenshot).
That control just wasn't visible in the app at the width I typically have
YouTube Music set at:

[image: Screen Shot 2021-12-01 at 2.08.20 PM.png]
So I widened the window and saw and deactivated it:
[image: Screen Shot 2021-12-01 at 2.11.37 PM.png]

I see now that you can mouse over the "<" icon and reveal those controls
even at the narrower width. Might eliminate some confusion to *not* hide
them under the "<" at the above width.

Thanks for pointing me in the right direction.

--

**Comment by mrengy** [comment]
Oh, I see. The repeat mode was activated (per your earlier screenshot).
That control just wasn't visible in the app at the width I typically have
YouTube Music set at:

<img width="1090" alt="Screen Shot 2021-12-01 at 2 08 20 PM" src="https://user-images.githubusercontent.com/2223603/144299014-9fcded7c-54da-49ae-aba1-1aa15ca392e9.png">

So I widened the window and saw and deactivated it:

<img width="1162" alt="Screen Shot 2021-12-01 at 2 11 37 PM" src="https://user-images.githubusercontent.com/2223603/144299042-a25a3903-2009-40db-b967-3fa1a7565d6b.png">

I see now that you can mouse over the "<" icon and reveal those controls
even at the narrower width. Might eliminate some confusion to *not* hide
them under the "<" at the above width.

Thanks for pointing me in the right direction.

**Comment by Araxeus** [comment]
Yeah that window resize feature is just a native youtube music feature that we don't control
(also it makes sense since there isn't enough space to render everything)
