### ISSUE TITLE
Global shortcut do not work on games

### ISSUE THREAD

**Issue by doublep21** [th-ch/youtube-music#505]
Global hotkeys don't work on games, on desktop it works fine.

**Comment by Araxeus** [comment]
Well we are using electron [globalShortcut](https://www.electronjs.org/docs/latest/api/global-shortcut) module

That bug belongs there. I found [this issue](https://github.com/electron/electron/issues/27240) about it but it was closed

Maybe open a new one in the electron repo?

**Comment by doublep21** [comment]
no one responds on electron repo , is it possible to add a new library or plugin for this?

**Comment by Araxeus** [comment]
You could just use media key controls (If you dont have any physcal keys, you could use microsoft's [Powertoys](https://github.com/microsoft/PowerToys) Keyboard Managers to bind other hotkeys to mediakeys

I can confirm it still works even if in-game

**Comment by doublep21** [comment]
ok thank you , for the media keys works but for the global keys for the precise volume there's no solution for now i think.

**Comment by Araxeus** [comment]
For now we'll just have to hope they will fix it next year 😅

**Comment by Araxeus** [comment]
@doublep21 
BTW I tested in 10 different games and it worked in all of them... could you please share 

- what game did you try ?
- what keybinds did you try?
- what is your operating system?

**Comment by doublep21** [comment]
> @doublep21 BTW I tested in 10 different games and it worked in all of them... could you please share
> 
> * what game did you try ?  League of legends TFT
> * what keybinds did you try? Function keys like F14 F15 and so on
> * what is your operating system? WIndows 11 last stable build

**Comment by Araxeus** [comment]
Well I downloaded League of legends and can confirm that it doesn't work there for some reason

But still like I said there are many other games in which it does work 😛

**Comment by doublep21** [comment]
@Araxeus it was not necessary, I appreciate it very much, thanks, we will see if there is some way to solve this.

**Comment by Accelyte** [comment]
@doublep21 Should also mention that setting custom volume step shows a flashing window for a second and nothing else

**Comment by Araxeus** [comment]
@Accelyte #476 fixed that too 😘
