### ISSUE TITLE
[Manjaro] Unsupported Browser

### ISSUE THREAD

**Issue by WhiteHusky** [th-ch/youtube-music#507]
Using the AUR package `youtube-music-bin` and cannot login due to the unsupported browser error.

So whatever fix mentioned in #17 didn't stick.

**Comment by Araxeus** [comment]
maybe the user agent needs updated version

https://github.com/th-ch/youtube-music/blob/a14d27da70caba3fcdfc104f04aeef15646fa1b5/index.js#L207-L211

**Comment by WhiteHusky** [comment]
@Araxeus 
Looks like it's gonna be a pain to fix. I did a patch in an attempt to circumvent but,
![image](https://user-images.githubusercontent.com/3196371/144471672-cdec76d1-769d-45b8-b9ed-37b50be87f1d.png)
```js
const userAgents = {
	mac: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0",
	windows: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
	linux: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
}

const userAgent = 
	is.macOS() ? userAgents.mac :
	is.windows() ? userAgents.windows :
	userAgents.linux;

// Also overwrite the user agent to prevent finding the actual user agent
win.webContents.userAgent = userAgent;
```

**Comment by WhiteHusky** [comment]
Wait what
![image](https://user-images.githubusercontent.com/3196371/144472348-cb69d5c4-fbf8-4f18-9377-c1af688a932f.png)
Okay so _maybe_ my patch works. Sorta. I'll publish it in a PR and someone much more of a guru can figure out what's going on. Electron is not in my wheelhouse.

**Comment by mimaketi** [comment]
On Arch, opening the developer tools, and running the below in the console allowed me to login no problem.

`Object.defineProperty(navigator, 'userAgent', {
    get: function () { return 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'; }
});`

**Comment by obvionaoe** [comment]
Please fix this and #17 , as the app is completely unusable for someone who only uses the library part of Youtube Music

**Comment by Araxeus** [comment]
> Please fix this and #17 , as the app is completely unusable for someone who only uses the library part of Youtube Music

Working on it 😅

meanwhile if you are on windows
you can install this version: https://www.mediafire.com/folder/fvjiihmu3ka2z/Youtube-Music+useragents-patch+v3

warnings:
* disable-autoplay & downloader plugins don't really work in this version, but login should work
* If you don't install via the setup,  after logging in you might experience a temporarily broken navbar and have to `Alt+F4` the program and start again to fix it (just once)

**Comment by obvionaoe** [comment]
sadly, I'm on Linux

**Comment by superbonaci** [comment]
Having this issue with latest snap on Ubuntu.

**Comment by superbonaci** [comment]
> On Arch, opening the developer tools, and running the below in the console allowed me to login no problem.
> 
> `Object.defineProperty(navigator, 'userAgent', { get: function () { return 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0'; } });`

THANKS A LOT, that worked for me on Ubuntu with snap 1.14. I had to enter twice that code on the console. Enter once on email login, then gave the error, then retry and re-enter again. Then worked.

**Comment by mesmerx** [comment]
i use arch (not manjaro) and this problem dont occur, this is strange, what is thee electron version in manjaro?

**Comment by Araxeus** [comment]
> i use arch (not manjaro) and this problem dont occur, this is strange, what is thee electron version in manjaro?

Its not about the OS, some accounts just have some kind of "shadowban" which causes this issue

**Comment by mesmerx** [comment]
> > i use arch (not manjaro) and this problem dont occur, this is strange, what is thee electron version in manjaro?
> 
> Its not about the OS, some accounts just have some kind of "shadowban" which causes this issue

ohhh this makes sense, thx for explanation

**Comment by obvionaoe** [comment]
Hi, I know the PR has been merged, but is there a way to push the new version to the AUR? That version is still broken

**Comment by mesmerx** [comment]
> Hi, I know the PR has been merged, but is there a way to push the new version to the AUR? That version is still broken

why dont use the git version, this package should be updated

**Comment by obvionaoe** [comment]
I'm not sure it is... `aur/youtube-music-git 1.14.0.r0.gf40ed04-1 [+0 ~0.00]`, it might be, I'm not very familiar with versioning in git based packages

But I also prefer to have a fixed version of a package installed, it's easier to troubleshoot. I'll just wait til 1.15.0 gets released!

**Comment by mesmerx** [comment]
> I'm not sure it is... `aur/youtube-music-git 1.14.0.r0.gf40ed04-1 [+0 ~0.00]`, it might be, I'm not very familiar with versioning in git based packages
> 
> But I also prefer to have a fixed version of a package installed, it's easier to troubleshoot. I'll just wait til 1.15.0 gets released!

the git versions get the master branch to build so its always updated :) i created the first version of this package :)
it should release the 1.15 soon :)
