### ISSUE TITLE
Quit

### ISSUE THREAD

**Issue by thijsi123** [th-ch/youtube-music#51]
When ytmusic displayed in tray and I right click it then quit nothing hapens. I need to use Taskmngr to do this.
![quit](https://user-images.githubusercontent.com/64159148/96333422-28156280-106a-11eb-99dd-42b446225a1f.jpg)

**Comment by th-ch** [comment]
Hey @thijsi123, thanks for submitting the issue! Out of curiosity, is YTM playing when you try to quit? It seems quitting does not work until you pause music (I will keep that issue opened to keep track of this).

**Comment by thijsi123** [comment]
I keep it in mind again Thank you.

**Comment by th-ch** [comment]
For the record, it's still in testing but https://github.com/th-ch/youtube-music/commit/023f5b6bc3b3693fedd671dc0631bc2c57ac8ec4 should fix the issue!

**Comment by thijsi123** [comment]
Thank you I check it out.

Op wo 21 okt. 2020 om 10:22 schreef th-ch <notifications@github.com>:
