### ISSUE TITLE
[Feature Request] Get colored background based on cover art

### ISSUE THREAD

**Issue by experiacc** [th-ch/youtube-music#512]
It would be really cool if we can get colored backgrounds just like [ytmdesktop](https://github.com/ytmdesktop/ytmdesktop) has it. The background changes according to the song playing.
Something like this:

![Shot_2021-12-09_01-24](https://user-images.githubusercontent.com/82676586/145275173-3165d652-7bd4-444c-83ed-f9330f755229.png)

**Comment by Araxeus** [comment]
Works for me.. try logging in maybe?

**Comment by experiacc** [comment]
Doesn't seem to work for me even after logging in. I even tried on a fresh install but no luck.

**Comment by Araxeus** [comment]
weird

![image](https://user-images.githubusercontent.com/78568641/145883360-04d4338f-986c-429c-bf6f-455dd2935190.png)

Maybe it will work for you after the new version is released

**Comment by JsephGriff** [comment]
Running the Compiled Binaries, there seems to be no feature present which would enable this colored background. Is the setting somewhere specific that could be enabled? Or is it supposed to be enabled automatically?

**Comment by Araxeus** [comment]
Its something that youtube does automatically when playing some songs

**Comment by JellyBrick** [comment]
Close due to 063ba1b6c7c7f8e3454e3b4536705f6399c217ab
