### ISSUE TITLE
[Feature request] Is it possible to implement sharing the progress bar/album art using MPRIS?

### ISSUE THREAD

**Issue by VBtheFirbolg** [th-ch/youtube-music#514]
I use KDE Connect (usually) to control audio players on my computer. So it would be very nice if there was a way to implement the sharing of the progress bar/album art via the MPRIS plugin.

Additionally, the music player is listed as "Chromium" when there already is a "YouTube Music" music player which seems to be a dummy audio player that is listed.

One music player which has this implemented is [MellowPlayer](https://gitlab.com/ColinDuquesnoy/MellowPlayer) for reference.

**Comment by Araxeus** [comment]
Did you try the latest changes on the main branch?

#480 added progress bar functionality and fixed some bugs

(about the "dummy player", I know it exist but don't know how to do anything about it atm)

**Comment by VBtheFirbolg** [comment]
No, I did not. And I must confess, I don't know how to do that either (I am quite a noob when it comes to git and coding in general 😅).

I would love to try it, though, if you could point me to where I can learn to try out latest changes.

**Comment by mesmerx** [comment]
> No, I did not. And I must confess, I don't know how to do that either (I am quite a noob when it comes to git and coding in general 😅).
> 
> I would love to try it, though, if you could point me to where I can learn to try out latest changes.

what linux did you use? in arch have the packages for git base, if not are a lot of ways

**Comment by VBtheFirbolg** [comment]
I use Ubuntu (20.04.3 LTS). I was able to build from source but I could not see a progress bar/album art on KDE connect.

**Comment by Araxeus** [comment]
@VBtheFirbolg did you enable the `shortcuts` plugin? right now this functionality is bundled with it for some reason 😅

**Comment by hacker1024** [comment]
It's not very obvious that the shortcuts plugin improves MPRIS features like album art.

Perhaps Chromium's default MPRIS functionality should be disabled in all cases, to force people to use the better implementation in the plugin?

**Comment by Araxeus** [comment]
To be fair, I don't even know why this is an optional plugin. It should just be an integrated feature that is enabled by default
