### ISSUE TITLE
Tuna-OBS and video-toggle incompatible

### ISSUE THREAD

**Issue by Aquariax1** [th-ch/youtube-music#522]
Hello, I use Tuna-OBS to get music info through the app, but unfortunately it download the cover of the current music. However, even with the "video-toggle" plugin enabled and the "force video remove video" enabled, it keeps using the 16:9 thumbnail instead of the 1:1.

![bad display](https://user-images.githubusercontent.com/55443332/146811554-2fc548b7-4d14-4932-b8a2-44548c4da97d.png)
>here is an example of bad display of the thumbnail

![good display](https://user-images.githubusercontent.com/55443332/146811594-c5d76814-a77e-4c04-85ae-0c90c1708dea.png)
>the usual one, when there is no clip

a bit annoying i hope you know how to solve that. if not... if you have a way to crop the image depending on his width, this will help me a lot

**Comment by Araxeus** [comment]
@Aquariax1 Can you give the url for example please?

**Comment by mesmerx** [comment]
@Aquariax1  maybe when you are playing a video the thumbnail image are different ratio, i`ll try this today, if so i can work on that

**Comment by Aquariax1** [comment]
Sorry for the delay, Christmas took me away.
@Araxeus Usually the youtube supermix is really video friendly (no video at all) but sometimes youtube choose to play a "video version" of the music like this one : 
> https://music.youtube.com/watch?v=xpVfcZ0ZcFM

the cover downloaded by tuna will be in 16:9 instead of 1:1 like the "music only" version : 
> https://music.youtube.com/watch?v=FrsOnNxIrg8

fixed it temporarily by using the scroll filter in OBS on the cover source and by limiting the size to 544x544 (no scroll)
I hope it helped you

**Comment by Araxeus** [comment]
From what I understand, you want the "Music version" thumbnail when playing the "Video version"

You have to understand that the thumbnail is provided by youtube, so we get the video thumbnail if its a video

Tho I have to say that I don't understand your "temporary fix",
