### ISSUE TITLE
Unsupported Browser Issue On Mac

### ISSUE THREAD

**Issue by Golfview** [th-ch/youtube-music#526]
<img width="1440" alt="Screen Shot 2021-12-24 at 2 37 44 AM" src="https://user-images.githubusercontent.com/18638863/147330247-e326efcd-5ca6-40d2-9edb-ca7289683c80.png">

**Comment by Golfview** [comment]
And for some reason it magically works now?

**Comment by Araxeus** [comment]
Issue is known and has been fixed (after trying again if it doesn't work) in #515
