### ISSUE TITLE
"Resume last song when app starts" behavior inconsistent

### ISSUE THREAD

**Issue by Rodancoci** [th-ch/youtube-music#528]
- OS: Arch Linux 5.15.11-arch2-1
- DE: GNOME 41.2
- App version: [yotube-music-bin 1.14.0-1](https://aur.archlinux.org/packages/youtube-music-bin/)

I've been getting unreliable behavior from the "Resume last song when app starts" feature.

It seems the app only remembers/updates the currently playing song when manually skipping songs either by clicking on the "next song button" or clicking on a song on the queue.

However, if a song finishes playing and the app automatically moves to the next song in the queue, upon quitting and starting the app the first song will start playing.

So, for example, suppose the queue looks like

- Song 1 ▶
- Song 2
- Song 3

Where Song 1 is currently playing.

If I either click the "next song" button or directly click Song 2 in the queue, Song 2 will start playing. If I then close the app and open it again, Song 2 will play automatically.

However, if Song 1 finishes playing and Song 2 starts playing automatically, and if I then close the app and open it again, Song 1 will play instead.

**Comment by Araxeus** [comment]
#477 should have fixed this

(new version that include this fix wasn't released yet as of 27/12/2021)
