### ISSUE TITLE
[Feature request] Album Art in Discord Presence

### ISSUE THREAD

**Issue by PixlShocK** [th-ch/youtube-music#532]
Discord Rich Presence should show the album art of the current song - this a feature I like about the PreMiD extension. (Screenshot of PreMiD presence)
Works via largeImageKey URL support
![image](https://user-images.githubusercontent.com/73503404/147787632-2a48e0cb-8f02-48cd-ae83-4a16403eb2e6.png)

**Comment by C00lCr4ft24** [comment]
yeeeeeess please, this is literally what im waiting since 2020 march!

**Comment by C00lCr4ft24** [comment]
> Discord Rich Presence should show the album art of the current song - this a feature I like about the PreMiD extension. (Screenshot of PreMiD presence) Works via largeImageKey URL support ![image](https://user-images.githubusercontent.com/73503404/147787632-2a48e0cb-8f02-48cd-ae83-4a16403eb2e6.png)

how did you do it tho?

**Comment by Araxeus** [comment]
#524 was merged and added this functionality

**Comment by PixlShocK** [comment]
Awesome, thanks.
