### ISSUE TITLE
Bug in blurry navbar

### ISSUE THREAD

**Issue by Ibaii** [th-ch/youtube-music#534]
Hi again!

I just updated to the pre-release 1.15.0.

The blurry navbar looks good. But it have a bug when I am in homepage.

https://user-images.githubusercontent.com/30672316/147856562-68bdfae1-0c17-4028-9377-d3a904bdbc94.mp4

_Originally posted by @Ibaii in https://github.com/th-ch/youtube-music/issues/490#issuecomment-1003590618_

**Comment by Araxeus** [comment]
I  can't replicate this, it works fine for me

**Comment by Ibaii** [comment]
Try it in window mode.

In fullscreen works also for me.

**Comment by Araxeus** [comment]
I'm always in windowed mode 🤔

**Comment by JellyBrick** [comment]
Can't reproduce on latest commit (https://github.com/th-ch/youtube-music/commit/375fb082f0bff90cd41d3693098d826c8a2420ae)
