### ISSUE TITLE
Can't sign in, says "This browser or app may not be secure"!

### ISSUE THREAD

**Issue by Speakable1** [th-ch/youtube-music#538]
Basically what the title suggests, I can't login into my google account, it says "This browser or app may not be secure" and suggests to use a different browser. I couldn't open a console so couldn't see exactly what the error was.

(sorry if this problem has already been solved/brought into attention)

![image](https://user-images.githubusercontent.com/43817108/148000889-4dafd23b-a666-439c-97f0-a0e3f5d7dee1.png)

**Comment by amsyarasyiq** [comment]
#515 fixed this and was merged, it should be included in the latest [pre-release](https://github.com/th-ch/youtube-music/releases/tag/v1.15.0).
