### ISSUE TITLE
Discord Presence Incorrect Time Remaining

### ISSUE THREAD

**Issue by trevorraney** [th-ch/youtube-music#541]
First track of an album will appear with a proper time out in the Discord presence, but subsequent tracks will show the wrong time remaining, regardless of length.

![image](https://user-images.githubusercontent.com/64988493/148085858-c27aecd6-8c37-480d-a36a-03de3a8b036b.png)
![image](https://user-images.githubusercontent.com/64988493/148085887-adea2fb5-e781-4957-b461-edfed2fca7e1.png)

**Comment by Sensokaku** [comment]
i'm using the 1.15.0 pre release and the time issue still happens for me

**Comment by FiestaLake** [comment]
Probably I should test this again lol

**Comment by thijsi123** [comment]
Force reload would fix this (maybe reload would too).
but sometimes when force reloading the app lets me listen to a song I listened to half an hour before.
