### ISSUE TITLE
App not showing when you run it

### ISSUE THREAD

**Issue by Starboy345** [th-ch/youtube-music#542]
I run the .exe file and previously, it worked fine. But now when i try open it, the icon shows up on my task bar but the app wont show on my screen. When i right click the tray icon and click show, it does not do anything. The app is playing music and i right click the tray icon and use the pause/play, previous, skip etc buttons.

I have tried deleting and downloading it again. The issue seems to be the same for v1.14 and v1.15 as well.

Any suggestions? Thanks

**Comment by Araxeus** [comment]
try making a backup of your `config.json` and deleting that file

> config.json folder path:
> * Windows: `%AppData%/Youtube Music` (MyUser/AppData/Roaming/Youtube Music)
> * Linux: `~/.config/Youtube Music`
> * MacOS: `~/Library/Application\ Support/YouTube\ Music/config.json`

also note that v1.15 should be installed via setup.exe

**Comment by Starboy345** [comment]
how do you create a backup of the config.json file (sorry, im not the most experienced in this kinda stuff)?

**Comment by Araxeus** [comment]
just rename it to `config_BACKUP.json` and that should be enough.

you dont actually have to delete it sorry 😅

**Comment by Starboy345** [comment]
i didnt delete it. I thought i would wait until i knew exactly what i was doing

but it did work! i renamed to config_BACKUP.json and the issue was sorted. thanks for your help!

also, is the download playlist function being fixed for v1.15 or is there a fix for it in v1.14?

**Comment by Araxeus** [comment]
can you please post here this file? config_BACKUP.json?

please try v1.15 and tell if playlist downloading works for you, because it does for me :)

**Comment by Starboy345** [comment]
it won't let me upload that file type unfortunately...

and you said i need to download the setup .exe for 1.15 and then run the .exe for the normal application?

**Comment by Araxeus** [comment]
For future reference:
This problem was caused because `window-position` (x value in particular) in config.json was set to a negative value that was offscreen

 (reasons unkown but probably not related to this app since it never changes the window position on its own)
