### ISSUE TITLE
A quick question! (about customzing .config, downloader segment)

### ISSUE THREAD

**Issue by Speakable1** [th-ch/youtube-music#543]
This issue (not really an issue) is based on/inspired by #112.
I wanted to customize the downloader function by add ffmpeg args, as you can see in the photo below.
![image](https://user-images.githubusercontent.com/43817108/148115289-81b468f0-748f-4ceb-9d08-f4eb07e485d3.png)
The options were taken from the ffmpeg documentation; [ffmpeg](https://ffmpeg.org/ffmpeg.html) and [ffmpeg-codecs](https://ffmpeg.org/ffmpeg-codecs.html#libopus-1)
I want to know I have added them correctly to the config file, and if not, how they should be arranged.

The following error is the result with this current setup: 
![image](https://user-images.githubusercontent.com/43817108/148115139-8ba261c1-edd2-4069-a2de-c68701892d84.png)
Says to "Check if path exists"

Thanks for the help!
My favorite and best app ever btw.

**Comment by th-ch** [comment]
Hey @Speakable1, you don't need to specify `--enable-libopus` (it's only to build FFMpeg, not to execute it) and you need to specify your bitrate + use `-` for args - for example for 96 kBit/s:
```json
"downloader": {
    "enabled": true,
    "extension": "opus",
    "ffmpegArgs": [
        "-acodec",
        "libopus",
        "-b:a",
        "96K",
        "-vbr",
        "on",
        "-compression_level",
        "10",
        "-application",
        "audio"
    ],
```

**Comment by th-ch** [comment]
Closing the issue  for easier tracking, feel free to re-open if needed :)
