### ISSUE TITLE
No adblock before login

### ISSUE THREAD

**Issue by bypequeno** [th-ch/youtube-music#55]
Hey, I have been using this program with no account and everything worked awesome. Now that I have logged in the adblock seems to not work anymore.

**Comment by th-ch** [comment]
Hey @bypequeno, thanks for submitting the issue! Adblock works for me after logging in - can you try disabling/re-enabling the adblock plugin (you will need to restart the app each time) to see if it solves the issue on your side?

Next version will add an option to toggle devtools, for easier debug (in devtools, you can see `net::ERR_BLOCKED_BY_CLIENT` for blocked requests)

**Comment by bypequeno** [comment]
Hey bro, I have discovered that it works when the hide video player plugin is off. When I have it with account and hide video plugin on, the adblock seems to not work properly.

**Comment by bypequeno** [comment]
Now randomly appears some ads, but not as much as without the adblock. The adblocker seems to only work without any account logged.
![image](https://user-images.githubusercontent.com/73602853/98601852-9fc35f80-22ad-11eb-9954-2efbdd4efd46.png)

**Comment by bypequeno** [comment]
I still have the same problem, adblock only works when I don't have an active session also in this latest version. Here you can see what appears to me on the console.
![image](https://user-images.githubusercontent.com/73602853/100282612-f087b900-2f39-11eb-8815-3bcc3907b05d.png)

**Comment by MikuDroid** [comment]
> Hey @bypequeno, thanks for submitting the issue! Adblock works for me after logging in - can you try disabling/re-enabling the adblock plugin (you will need to restart the app each time) to see if it solves the issue on your side?
> 
> Next version will add an option to toggle devtools, for easier debug (in devtools, you can see `net::ERR_BLOCKED_BY_CLIENT` for blocked requests)

Same thing happened, just tested. signed with account, ads shows up. Logged out, no ads.

**Comment by th-ch** [comment]
Hey @bypequeno @MikuDroid, [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly!

**Comment by MikuDroid** [comment]
> 
> 
> Hey @bypequeno @MikuDroid, [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly! If you changed adblock settings, you can revert to the default:
> 
> ```json
> "adblocker": {
>     "enabled": true,
>     "cache": true,
>     "disableDefaultLists": false,
>     "additionalBlockLists": []
> },
> ```
adblocking works on 1.7.4! Thanks!

**Comment by bypequeno** [comment]
Works pretty well bro, thanks 👍

**Comment by bypequeno** [comment]
Fixed on 1.7.4
