### ISSUE TITLE
Getting unsupported browser error when trying to sign in from Mac

### ISSUE THREAD

**Issue by jazir5** [th-ch/youtube-music#552]
I'm using the latest version on GitHub and trying to sign in, but I'm getting an unsupported browser error when I try to log in. How do I fix this?

**Comment by Araxeus** [comment]
are you sure that you are using https://github.com/th-ch/youtube-music/releases/tag/v1.15.0?

**Comment by jazir5** [comment]
It just randomly started working, weird
