### ISSUE TITLE
Bug when clicking the yt logo (or any link inside of the program) with the cursor wheel.

### ISSUE THREAD

**Issue by bypequeno** [th-ch/youtube-music#56]
If you click on any link inside the program with the cursor wheel, it opens a new "tab" but with some bugs caused by the plugins (like a conflict between both tabs.
![image](https://user-images.githubusercontent.com/73602853/98455060-da0bf000-2139-11eb-9c9e-31853d39261c.png)

**Comment by th-ch** [comment]
Hey @bypequeno, thanks for reporting! This issue is confirmed and should be fixed in the [next release - v1.6.0](https://github.com/th-ch/youtube-music/releases/tag/v1.6.0), feel free to test it out (it's a pre-release at the moment) and update the issue!

**Comment by bypequeno** [comment]
In the last version 1.6.3 is already fixed. Sorry for the delay.
