### ISSUE TITLE
Possible widget for the xbox game bar?

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#563]
On windows computers the windows + g button brings up the xbox game bar where there are a many widgets for recording or volume control. 

Spotify has a built in plugin allowing you to pause and resume music on this menu and I was wondering if it was possible to add a widget for the youtube music app as well so we could pause our music or resume it while we were in fullscreen games instead of having to alt tab out.

**Comment by Araxeus** [comment]
From what I know, only UWP apps can create widgets inside the Xbox game bar.

(This isn't a UWP app)

**Comment by thijsi123** [comment]
Ahh yes, I completely forgot that, I once used "wemod" that had a wemod overlay extension app on the Windows store for the game bar.
This is not possible unless this project goes uwp or gets its external uwp extension. (most likely not gonna happen, and I don't blame them)

**Comment by DereC4** [comment]
Sad

**Comment by DereC4** [comment]
But thx for letting me know

**Comment by Araxeus** [comment]
Ask microsoft to add a native media control the xbox game bar :D
