### ISSUE TITLE
Title Bar on Windows isn't Dark in Dark Mode

### ISSUE THREAD

**Issue by SebastianOliva** [th-ch/youtube-music#568]
<img width="570" alt="Screenshot 2022-01-23 134302" src="https://user-images.githubusercontent.com/16869486/150693159-a7e27bbc-3fd7-473c-bd47-b58246451904.png">
Hello,
The title bar in the Windows release isn't dark with dark mode on.
Thank you

**Comment by Araxeus** [comment]
use `in-app-menu` plugin for a dark bar
