### ISSUE TITLE
Playlist not downloading..this time it's like this.

### ISSUE THREAD

**Issue by vihaan1234567** [th-ch/youtube-music#569]
<img width="274" alt="Screenshot 2022-01-24 181839" src="https://user-images.githubusercontent.com/88080742/150785717-6cafe307-ac4b-4cf1-9eeb-22749cb458cf.png">

What do I do about this?

**Comment by CTalvio** [comment]
Had to log in to download playlists. This was not possible on 1.14, had to get the pre-release 1.15 .appimage and then force a reload in the app, after which logging in worked.

**Comment by Araxeus** [comment]
You probably tried to download a private playlist / custom mix

you can only download public playlists that aren't auto-generated

**Comment by vihaan1234567** [comment]
Its my playlist.. And it is public..

**Comment by vihaan1234567** [comment]
> Had to log in to download playlists. This was not possible on 1.14, had to get the pre-release 1.15 .appimage and then force a reload in the app, after which logging in worked.

I have logged in..

**Comment by Araxeus** [comment]
Can you send a link to the playlist?

also how did you try and download? 
menu-plugins-downloader-download-playlist or popup menu and download button?

**Comment by vihaan1234567** [comment]
Here it is.. https://music.youtube.com/playlist?list=PLf4ttPANe1OsWnBKLmzJsbUBnbqLyxunP&feature=share

I downloaded it through menu-plugins-downloader-playlist download

> Can you send a link to the playlist?
> 
> also how did you try and download? menu-plugins-downloader-playlistDownload OR popup menu and download button?

**Comment by Araxeus** [comment]
![image](https://user-images.githubusercontent.com/78568641/151178286-2692d5a3-13b8-4b7c-8ee7-07bea67a7375.png)

works for me

**Comment by vihaan1234567** [comment]
OK I will check it out again and get back. Thank you.
