### ISSUE TITLE
Some songs aren't displayed in the taskbar

### ISSUE THREAD

**Issue by Wxrlds** [th-ch/youtube-music#57]
I've noticed when searching for songs that the title isn't displayed in the taskbar. This only seems to happen for the first song you play after having searched for it. At first I assumed it has something to do with the amount of characters which are displayed (>15 Characters) but this isn't correct for some songs.
Step by Step Guide as this helps to understand what's happening:

1. Search for a non selected song with a long title (For example "In The Name Of Love" (19 Characters) or "Scared to Be Lonely" (19 Characters) or "Where Are Ü Now" (16 Characters))
2. Play this song
3. The Taskbar shows this
![grafik](https://user-images.githubusercontent.com/42120270/98815681-d329f980-2427-11eb-96fb-b8faecc91a07.png)
4. Repeat 1., 2. and 3. but now play a song with 15 Characters (Like "Don't start now" (make sure you play the Music Video duration is 3:02))
5. The Taskbar now shows the same as in 3.
6. Now open the results for "Don't start now" again but select the Lyrics Video (Duration 3:24)
7. Taskbar shows this
![grafik](https://user-images.githubusercontent.com/42120270/98817608-a1fef880-242a-11eb-9d8e-ad69bb0837b0.png)

Up until I wrote 1. - 4. everything seemed clear that the issue was with songs over 15 Characters but after that I'm now even more confused on what's happening.

This is using Version [1.6.0 Pre Release](https://github.com/th-ch/youtube-music/releases/tag/v1.6.0)

**Comment by MiepHD** [comment]
This issue still persists but it isn't an issue of this app. The title shown in the taskbar is the title of the webpage you're on. You can reproduce this bug on any browser with the title of the tab. I've reported this issue to Youtube Music now so this issue can be closed,
