### ISSUE TITLE
High Ram usage issue

### ISSUE THREAD

**Issue by MahmoudOkasha17** [th-ch/youtube-music#572]
![image](https://user-images.githubusercontent.com/39097475/150827209-52afc251-2e89-45b5-aa27-d7113a168b0a.png)

I left my pc on overnight and forgot youtube music was playing and then I saw this ram issue, I dunno if it is fixable on your part but thought I would share this.

**Comment by Araxeus** [comment]
could you post what plugins were enabled? (just in case someone can fix this)

**Comment by MahmoudOkasha17** [comment]
![image](https://user-images.githubusercontent.com/39097475/150828540-94938150-4c0c-4cef-9c54-eafb14b5a674.png)
the ones with arrows are also enabled

**Comment by ZeroCool940711** [comment]
Hi there, I also noticed this issue almost after installing Youtube Music using the setup, I enabled a couple of plugins and restarted the app a couple of times and got the same issue with high RAM usage and also the app been unresponsive, I decided to run the app as admin and change a couple of settings on the compatibility tab from the Property window on the YouTube Music shortcut and the issue seem to be solved, now I the app is using just about 150-200mb of RAM and its not freezing anymore. I'm not 100% sure which of the changes fixed this but I will just share it so in case you want to give it a try, if it also solves the issue for you let me know.
![image](https://user-images.githubusercontent.com/5977640/151824249-30c2bf28-520b-4a7d-9638-6a373760f246.png)
![image](https://user-images.githubusercontent.com/5977640/151824351-6a9edc46-2bbe-4019-85a6-ec6d0036c738.png)

**Comment by Araxeus** [comment]
can you try the latest version?
https://github.com/th-ch/youtube-music/releases/tag/v1.16.0
