### ISSUE TITLE
Show window if app already running

### ISSUE THREAD

**Issue by bkanuka** [th-ch/youtube-music#576]
I have the tray icon enabled. I sometimes close the main window by habit (clicking the x) and then click the icon in my launcher. This launches another instance of the application.  Idealy the currenly running instance is shown instead of opening a new one.

This could be solved by checking if an instance is running and showing it, or by allowing a "minimize on close" option.  If the window only minimized when closing the window, then clicking the app in the laucher would bring it forward (instead of launching a new instance)

**Comment by Araxeus** [comment]
https://github.com/th-ch/youtube-music/blob/61eb23614a27a50e6901306f039cc7c0aed446db/tray.js#L26-L32

Clicking the tray button only show/hide the window. it shouldn't create a new instance?

**Comment by bkanuka** [comment]
the tray icon works as intended, but the when it's minimized to the tray and I 'launch' the program again (I'm using Gnome, or from the terminal), a new instance of the program starts (and creates a new tray icon!).  Instead the existing app should be brought forward.

I totally understand this could be fixed by "well dont do that", but it's a habit from other programs that act in this way (Slack and other previous music players I've used)

**Comment by Araxeus** [comment]
That's because this app doesn't block multiple instances

I'm personally glad it doesn't - if a user wants multiple instances he can.

(btw it should launch a new instance regardless of if the app is in tray mode)

**Comment by Araxeus** [comment]
Nevertheless I will add an option "single instance mode" which will block multiple instances

**Comment by Araxeus** [comment]
#578 adds an option "Single instance lock" which will solve your problem ^^

**Comment by bkanuka** [comment]
Thanks! A "single instance mode" is exactly what I was thinking of.  I really appreciate you adding the option - especially when you wouldn't personally use it :smile:

**Comment by Araxeus** [comment]
not really important but do you think "Single instance mode" is more understandable than "Single instance lock" ?

I named the option in the menu lock since that's what electron calls it but its up for debate 😅

**Comment by bkanuka** [comment]
I do like "mode" better, but :shrug: .  This is how VLC does it:

![Screenshot from 2022-01-27 13-25-14](https://user-images.githubusercontent.com/2676579/151420901-5f1e1f28-f3e0-4794-a8d7-3bdd450f9c23.png)
