### ISSUE TITLE
Consistently getting "The application is unresponsive"

### ISSUE THREAD

**Issue by renatolond** [th-ch/youtube-music#579]
Hi! First of all, thanks for the work on this!

I've been experiencing a consistent "The Application is Unresponsive" error 
![image](https://user-images.githubusercontent.com/173791/151347657-89519356-3931-469b-af57-8f41d832ad49.png)

It seems to happen when I scroll after the fold, as youtube music is about to browse for more music. I tried opening developer tools but it also seems to get blocked when it happens. I tried disabling all plugins, restarting and the issue still happens.

I'm on Arch Linux, using `youtube-music-git` package in the latest commit `61eb236`, but I was having the issue on a previous version too `44aa62c`.

If I don't try to scroll, the issue does not happen and music plays normally.

**Comment by Araxeus** [comment]
what do you mean by "when I scroll after the fold"?

could you make a video showing the problem maybe?

also to show more debugging could you run the app locally?
aka clone the repo, install yarn+nodejs and then in youtube-music folder run `yarn` to install all dependencies and then `yarn start` to start the app

**Comment by renatolond** [comment]
Interestingly, running it locally I don't have the issue :thinking: 

here's a video of the issue with the packaged version:

https://user-images.githubusercontent.com/173791/151350647-35c4ea2b-2444-4599-99e3-7e13eac55a11.mp4

Running it locally I have a 500 error to a browse url:
```
https://music.youtube.com/youtubei/v1/browse?ctoken=<big_token_here>%253D%253D&continuation=<another-token>%253D%253D&type=next&itct=CAMQybcCIhMIyJqfjOrR9QIVkyEGAB0piwuT&key=<a-key>```
```
I managed to see once this error appear on the packaged version as well, and it seems to be last request before it froze

**Comment by renatolond** [comment]
I tried the packaged version from Arch Linux, from the `youtube-music-git` package.

It seems to me that it started breaking after I updated to the latest version, but I can't pinpoint exactly, I definitely noticed after I last upgraded my system, which bumped the version to `44aa62c`.

**Comment by Araxeus** [comment]
can you try the latest version? https://github.com/th-ch/youtube-music/releases/tag/v1.16.0

(as im writing this, the arch package wasn't updated yet)

**Comment by renatolond** [comment]
Sorry, took me a bit to come back to this. I tested from the latest package (`youtube-music-bin 1.16.0-1`) and it seems to be solved :tada: Thanks a lot!
