### ISSUE TITLE
Album image in "Now Playing" on macOS Big Sur

### ISSUE THREAD

**Issue by TimNedvyga** [th-ch/youtube-music#58]
<img width="449" alt="Screen Shot 2020-11-20 at 8 19 41 PM" src="https://user-images.githubusercontent.com/16063002/99835827-d894eb80-2b6d-11eb-98d9-a37a120971ed.png">

**Comment by Itai-Nelken** [comment]
I have the same bug

**Comment by TimNedvyga** [comment]
hey @th-ch, any updates on this one?

**Comment by Araxeus** [comment]
Can anyone confirm if this happens with **every** song?
or does it sometimes work? (try maybe an old video with bad resolution from youtube)

**Comment by Itai-Nelken** [comment]
this still happens for every song I tried. I'm on 1.12.0.

**Comment by marmichalski** [comment]
I've build the latest release (fe0f213919084f9e0bd95ce626ec711fb522d436) and it's still an issue. Anyway, except for the album icon, Is is possible to see the current playtime? 🤔 

<img width="296" alt="Screenshot 2021-09-01 at 07 40 10" src="https://user-images.githubusercontent.com/57528542/131617904-54268064-e611-47aa-a2f7-768210b621ef.png">
