### ISSUE TITLE
Getting ads 

### ISSUE THREAD

**Issue by MundaneJournalist** [th-ch/youtube-music#582]
<img width="960" alt="Screenshot 2022-01-29 104259" src="https://user-images.githubusercontent.com/98633007/151648468-a1cf6242-fd4d-49b5-93fb-0322ec8eca0b.png">
Getting ads. I don't know why. Adblocker is on.

**Comment by Araxeus** [comment]
Did you get a single ad just after launching the app or do you constantly get ads?

**Comment by vihaan1234567** [comment]
Single ad.

**Comment by Araxeus** [comment]
Personally not sure how to fix it.

it sometimes happen when "Resume last song on start" option is enabled,
the video is loaded before the adblocker can be loaded - resulting in a single ad

**Comment by vihaan1234567** [comment]
How do I disable resume last song on start?

**Comment by Araxeus** [comment]
its the 2nd option in the Options menu

**Comment by vihaan1234567** [comment]
Thanks a lot

**Comment by Araxeus** [comment]
I might have fixed it in #583 

would be nice if you could test if it actually fix the problem for you

**Comment by vihaan1234567** [comment]
Yeah it works. Thank you.
