### ISSUE TITLE
Cannot log in, "This browser or app may not be secure"

### ISSUE THREAD

**Issue by Tenshinen** [th-ch/youtube-music#594]
This is with 1.15.0, completely unable to log in no matter what I do.
![image](https://user-images.githubusercontent.com/36275083/152643086-0f2bb1e0-8a84-42d8-a27d-4dc0b49a5fe8.png)
![image](https://user-images.githubusercontent.com/36275083/152643083-68b6efd1-f623-45ef-8399-755a3902a990.png)

**Comment by Araxeus** [comment]
You press try again and it shows the same login screen?

**Comment by Tenshinen** [comment]
> You press try again and it shows the same login screen?

It takes me back to the same login screen. Logging in again results in the exact same issue. I've attempted login 9 or 10 times by now. Exact same issue each time, so it is reproduceable on my end.

**Comment by Araxeus** [comment]
Well its weird because in v1.15 if login fails and you press "Try Again" it should redirect you to an alternative login page which works

could you try this version? 
https://drive.google.com/file/d/1h6jkh_G1WMMSPZNtn53PQAhSjp31QgoG/view?usp=sharing

(this version should always display the alternative login page which should work)

**Comment by Tenshinen** [comment]
> could you try this version? https://drive.google.com/file/d/1h6jkh_G1WMMSPZNtn53PQAhSjp31QgoG/view?usp=sharing
> 
> (this version should always display the alternative login page which should work)

This version worked, and only gave me a single sign in page.

**Comment by Araxeus** [comment]
Thanks for testing, I opened a pull request with the changes

(#595 make useragent override *optional* from advanced-options)

**Comment by Araxeus** [comment]
https://github.com/th-ch/youtube-music/releases/tag/v1.16.0 was released and include this fix :)
