### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by MINECODEMATE** [th-ch/youtube-music#604]
When I try to sign in it says 'This browser or app may not be secure.'
![image](https://user-images.githubusercontent.com/51512808/154052685-b2482a9c-e7d3-46a9-aaf6-d4fa894c0384.png)

**Comment by Araxeus** [comment]
try https://github.com/th-ch/youtube-music/releases/tag/v1.15.0

**Comment by MINECODEMATE** [comment]
thx

**Comment by naeemba** [comment]
Is there any plan to release `1.15.0` as a stable version?

**Comment by naeemba** [comment]
> If you still have issues with that ,then click on the buy premium and it'll log you in without issues.

Didn't work for me, the same issue...

**Comment by Araxeus** [comment]
> Is there any plan to release `1.15.0` as a stable version?

well v1.16 should be released soon and will fix/improve alot of things

**Comment by Vikaash301** [comment]
turn less secure apss access feature as "yes" on your google account . this option is located in your google account under security .wait for a few minutes and then try to sign in again. it should work .

**Comment by Vikaash301** [comment]
if you have two factor authentication turned on , you need to disable it temporarily and then only you can use use less secure apps option.

**Comment by anytarseir67** [comment]
reloading the login page worked for me, with 2fa on

**Comment by Vikaash301** [comment]
> reloading the login page worked for me, with 2fa on

**Comment by Araxeus** [comment]
https://github.com/th-ch/youtube-music/releases/tag/v1.16.0 new version was released, should solve the problem

**Comment by th-ch** [comment]
👋 Closing this PR as it appears to be solved with the latest version, feel free to re-open if needed!
