### ISSUE TITLE
macOS: Icon size

### ISSUE THREAD

**Issue by Suplanus** [th-ch/youtube-music#606]
The icon size for macOS has changed in the guideline:
![image](https://user-images.githubusercontent.com/2002916/154628716-1c06fbde-2929-4055-adbc-2f8f8d2c5c91.png)

<img width="47" alt="image" src="https://user-images.githubusercontent.com/2002916/154628637-f3c5533b-dc51-4677-88f9-ed8b7779325e.png">

**Comment by Mateus109** [comment]
Also, the current icon, although correctly matches Music's officially branding, is way too bright.  It's shockingly red compared to other macOS icons.  Something like this might be better:
![YouTube Music icon](https://github.com/th-ch/youtube-music/assets/11629946/7bfc8696-41e0-4644-93d5-72fe5fdecdcb)
