### ISSUE TITLE
Couldn’t sign you in

### ISSUE THREAD

**Issue by ubreathtaking** [th-ch/youtube-music#607]
I were using soft before without any issues, after reinstalling OS - i am getting this error after opening soft and clicking on "Sing in"

This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in. 

In google account i have enabled the login though less secure softs 
 
![image](https://user-images.githubusercontent.com/8896375/154695168-1ca68a84-e23c-455e-8b70-44fe097f2875.png)

**Comment by Araxeus** [comment]
Try using https://github.com/th-ch/youtube-music/releases/tag/v1.15.0 or wait for v1.16

**Comment by ubreathtaking** [comment]
@Araxeus understood, tested with v1.15 still same happens, why do you think this will be changed in v1.16 ? maybe there are other options?

**Comment by ubreathtaking** [comment]
btw actually in 1.12.1 version i could login without any "not secure" , everything works @Araxeus  appreciated for fast reply and help, love you.

**Comment by Araxeus** [comment]
see #594 and #595

if you are on windows you can try the files I [compiled](https://drive.google.com/file/d/1h6jkh_G1WMMSPZNtn53PQAhSjp31QgoG/view?usp=sharing), if not then you can clone the repo and run in dev / build the app yourself to test those changes (add me on discord if you need help with that)

**Comment by Araxeus** [comment]
can you try the latest version?
https://github.com/th-ch/youtube-music/releases/tag/v1.16.0
