### ISSUE TITLE
google shows that this app is a less secure app

### ISSUE THREAD

**Issue by Vikaash301** [th-ch/youtube-music#609]
when I tried to sign in to youtube music  it was asking whether I am using a browser or a secure app 
.I continuously pressed try again .It displayed the same error again and again.
It only disappeared  after on turned allow less secure apps access to your google account as "yes".

**Comment by Araxeus** [comment]
see #594 and #595

you can try using https://github.com/th-ch/youtube-music/releases/tag/v1.15.0 or wait for v1.16 or if you are on windows you can try the files I [compiled](https://drive.google.com/file/d/1h6jkh_G1WMMSPZNtn53PQAhSjp31QgoG/view?usp=sharing) with the changes, if not then you can clone the repo and run in dev / build the app yourself to test those changes (add me on discord if you need help with that)

**Comment by Araxeus** [comment]
https://github.com/th-ch/youtube-music/releases/tag/v1.16.0 was released and should solve this
