### ISSUE TITLE
Plugins bar gone in version 1.6.2

### ISSUE THREAD

**Issue by xenzer** [th-ch/youtube-music#61]
The plugin option is no longer at the top of the screen in the version 1.6.2 on windows. 
![where](https://user-images.githubusercontent.com/74574555/99922764-d199e480-2cf7-11eb-86a8-22ff1e7ea4cc.png)

**Comment by th-ch** [comment]
Hey @xenzer, thanks for submitting the issue! [v1.6.3 (pre-release)](https://github.com/th-ch/youtube-music/releases/tag/v1.6.3) should fix the issue and adds a test to prevent future regressions, feel free to give it a try and update the issue accordingly!

**Comment by xenzer** [comment]
Yes, it is there now, thank you!

**Comment by C4illin** [comment]
I really liked how it was in the last version when you needed to press ALT to show it, I thought that was an intended feature :)

**Comment by sphr2k** [comment]
I'd like to be able to hide the menu bar, too and how it upon pressing `Alt`´.

**Comment by th-ch** [comment]
Hey @C4illin & @sphr2k, thanks for the feedback! https://github.com/th-ch/youtube-music/pull/67 adds an option to hide the menu, available in the [v1.6.4 prerelease](https://github.com/th-ch/youtube-music/releases/tag/v1.6.4) - feel free to test it out and update the issue accordingly!

**Comment by C4illin** [comment]
It required to restart the program after enabling it but otherwise it worked great!
Thank you @th-ch !
