### ISSUE TITLE
"improve your recommendation" on youtube music setting  crashes youtube music and working only after forcefully ending task  or in task manager 

### ISSUE THREAD

**Issue by Vikaash301** [th-ch/youtube-music#611]
whenever i keep scrolling in the choose your preferred artist menus after certain number of artist passes it freezes till I kill the process in my task manager or use restart app / exit app . It is the latest version  and i use latest version of windows 11 stable

**Comment by Araxeus** [comment]
Sorry but from my experience this is a bug with music.youtube.com (the bug exist even if you open the normal website in the browser)

so unfortunately I don't think we can fix this by ourselves, youtube need to fix their website :(
