### ISSUE TITLE
(Plugin) Custom song volume if needed

### ISSUE THREAD

**Issue by Bellisario** [th-ch/youtube-music#613]
Recently I found a very beautiful song, but that it's too low of sound, so, would be great a plugin that permits a custom volume if needed to a song (for example, using a slider on the three dot menu, or something similar).

If you like my idea, please like  :+1:  below!!!

**Comment by thijsi123** [comment]
You mean something like an amplifier?

**Comment by AuracleTech** [comment]
Oh my gosh please yes the sound control sometimes jump around, its not precise, also it's impossible to go like 2% minimum is probably like 10%, youtube volume is so bad

**Comment by Araxeus** [comment]
There are already 3 plugins for this...

+ `precise-volume` Control the volume precisely 

+ `exponential-volume`  Make volume slider exponential

+ `audio-compressor`  Apply compression to audio (similar to exponential-volume)

**Comment by AuracleTech** [comment]
https://user-images.githubusercontent.com/40531871/155345671-7a20808e-eed9-4eef-9ee4-418e703b1822.mp4

**Comment by AuracleTech** [comment]
Indeed it now seems to work, thank you 
![image](https://user-images.githubusercontent.com/40531871/155359474-b87e5b72-defc-4865-9254-ed3a3299ed0e.png)
