### ISSUE TITLE
MacOS arm64 release faulty

### ISSUE THREAD

**Issue by danshapir** [th-ch/youtube-music#614]
#566

On an M1 Max, can't open once installed, states the program is faulty and needs to be moved to the trash.

**Comment by Araxeus** [comment]
@th-ch @arunim2405

**Comment by arunim2405** [comment]
Experiencing the same problem when I install the release, however when I run `yarn build:mac:arm64` and use the app in the dist, it runs fine.

**Comment by Araxeus** [comment]
could be related to code signing?

https://github.com/electron-userland/electron-builder/issues/5850

**Comment by tessi** [comment]
Thanks @Araxeus 💛 

> sudo xattr -r -d com.apple.quarantine "/Applications/*.app"

This worked for me after experiencing the same error

**Comment by Araxeus** [comment]
Well this pretty much confirm that the problem is caused by the "macOS gatekeeper" because the app isn't signed/+notarized

**Comment by Araxeus** [comment]
> Might be wise to change the `*.app` to `<app name>.app` or `YouTube Music.app` just so people don't accidentally unquarantine every app they have.

thanks, I've never used mac so I thought it would keep the version attached to its name, fixed it 😅
