### ISSUE TITLE
Notification Controller

### ISSUE THREAD

**Issue by bakinazik** [th-ch/youtube-music#615]
I can't see the notification controller when I pause or play the music. I only see the controller after changing the volume. Can you fix this issue?

![resim](https://user-images.githubusercontent.com/64368231/155053265-a6c4887f-6491-4d5c-a20e-ca88f77f9113.png)

**Comment by Araxeus** [comment]
Are you using the `shortcuts` plugin?
If so, Is the `Override MediaKeys` option enabled?

**Comment by voxrie** [comment]
![resim](https://user-images.githubusercontent.com/64368231/155126102-b68b9378-126e-4a3c-b821-ce9fa3c147a5.png)

**Comment by Araxeus** [comment]
Weird because it works for me, are you sure that you're using the pause/play media keys?

Can you check that you're actually using the media play/pause key?

In https://keycode.info/ it should show `179` (play/pause) when you click the button

Also what happens if you press next/previous track? Does it work then?

(`176`/`177` keycodes)

**Comment by voxrie** [comment]
![resim](https://user-images.githubusercontent.com/64368231/155143498-a7b2bcd0-7178-408b-a3ea-3830a29ebb4f.png)
![resim](https://user-images.githubusercontent.com/64368231/155143523-ff541390-ea78-4215-9c5c-8067a673571f.png)

**Comment by Araxeus** [comment]
Oh wait I just realized thats how it worked all along

Windows only show the volume OSD when **changing volume**

so play/pause/next/previous wont show that OSD, its just windows behavior

you can search google for "Windows volume OSD" and see for yourself. so there isn't actually any bug here

**Comment by Araxeus** [comment]
But if you want, you can use the `Notifications` plugin and if you also want to be able to control it from there, `Interactive Notifications`

**Comment by voxrie** [comment]
When I create web app with edge browser, there is no such problem like this..

**Comment by Araxeus** [comment]
> When I create web app with edge browser, there is no such problem like this..

pretty sure you're wrong, i've tested with 6 different programs and also the documentation says it only shows up when changing volume
also the official name is "Volume OSD"...

**Comment by voxrie** [comment]
![explorer_2lshO8LfxF](https://user-images.githubusercontent.com/64368231/155167787-b65729e5-622c-4f22-bdf6-db5c3e457cf9.gif)

**Comment by voxrie** [comment]
this is from web app on edge browser

**Comment by voxrie** [comment]
and this is from original spotify app
![explorer_DqNsBy7qXb](https://user-images.githubusercontent.com/64368231/155168915-2b53f2a8-8549-4adb-8a04-b3797f2d6027.gif)
