### ISSUE TITLE
FN + f9 only plays YT Music

### ISSUE THREAD

**Issue by ryuuseeii** [th-ch/youtube-music#616]
Pressing fn+f9 (Play) while a YT video is playing only pause/play the music on YT music.

**Comment by ryuuseeii** [comment]
Ver. 14.0 below don't have this problem

**Comment by Araxeus** [comment]
I personally don't understand your problem

**Comment by ryuuseeii** [comment]
The play button prioritizes Youtube music, not the media that is currently playing. So I cant pause a youtube video if my youtube music is opened. (Not native English speaker .-.)

**Comment by ryuuseeii** [comment]
Same issue as #647
