### ISSUE TITLE
Cannot disable autoplay without breaking simple music transition

### ISSUE THREAD

**Issue by Diamondemon** [th-ch/youtube-music#618]
Hello there,
I started using this app yesterday, I really like it, and google does not complain either. I am on version 1.16.0, my OS is `Linux 5.16.7-1-MANJARO GNU/Linux`

However, I have a problem when it comes to autoplay: 

I noticed that when disabling autoplay the transition between musics gets completely broken and I have to reset the music manually in order for it to work.

Switching autoplay back to enabled makes everything work fine again.

Do you have any idea how to fix this?

**Comment by Araxeus** [comment]
are you talking about the plugin `disable-autoplay`?

because thats exactly what this plugin does, disable autoplay = makes the music 'paused' when the song changes

**Comment by Diamondemon** [comment]
Yes that's what I'm talking about. I thought the autoplay, as it is in browsers like Firefox, would only take effect on playing the music you recover when opening the application.
I may have been mistaken then.

**Comment by Araxeus** [comment]
the application wont resume the last song unless you have the `Resume last song when app start` option enabled
