### ISSUE TITLE
Restart App close the app

### ISSUE THREAD

**Issue by AuracleTech** [th-ch/youtube-music#620]
Irony

https://user-images.githubusercontent.com/40531871/155430178-27a000c8-1218-46c2-a885-f0de32376240.mp4

**Comment by Araxeus** [comment]
Pretty weird, works for me

**Comment by AuracleTech** [comment]
Seems to have fixed the issue, but not for the portable version 😢

**Comment by Araxeus** [comment]
I've fixed the issue in the portable version in #605 

Thanks for reporting :D

**Comment by AuracleTech** [comment]
Thank you!
I will then close this issue now a PR is open

**Comment by Araxeus** [comment]
FYI You didn't have to close this, the PR would have closed this issue automatically when merged

Doesn't really matter tho :wink:

**Comment by AuracleTech** [comment]
> FYI You didn't have to close this, the PR would have closed this issue automatically when merged
> 
> Doesn't really matter tho 😉

Thank you for the information, I did not know, I always work alone, rarely used PR
