### ISSUE TITLE
[Feature Request] arm64 (Windows) support

### ISSUE THREAD

**Issue by null-von-sushi** [th-ch/youtube-music#623]
I just wanted to ask if a build for the arm64 version of windows could be added. [It seems electron supports this](https://www.electronjs.org/docs/latest/tutorial/windows-arm/). It would be hugely helpful as, while x86 apps do work under emulation/compatibility layer, performance is terrible (especially for web content).

**Comment by JellyBrick** [comment]
YTM is now a universal app
