### ISSUE TITLE
Video Player UI messed up

### ISSUE THREAD

**Issue by churchymayer** [th-ch/youtube-music#631]
The video panel has this massive black space above it and the video is being pushed down by it and then cut off at the bottom of the field. it looks like a video on a vertical screen where its being centered in the middle of the screen but the bottom half of the "screen" cant be shown This issue started with v1.15 and is the same in 1.16. I'm on Windows 10

**Comment by Araxeus** [comment]
what plugins are enabled for you? what os are you on?

could you post your config,json file?

config.json containing folder path:
* Windows: `%AppData%/Youtube Music` (MyUser/AppData/Roaming/Youtube Music)
* Linux: `~/.config/Youtube Music`
* MacOS: `~/Library/Application\ Support/YouTube\ Music/config.json`

**Comment by churchymayer** [comment]
[files.zip](https://github.com/th-ch/youtube-music/files/8180414/files.zip)
Uploaded my config and a screenshot with my plugins. Furthermore, i'm on Windows 10 Pro 21H2

**Comment by Araxeus** [comment]
I've used your config and  haven't experienced any problem, maybe provide a screenshot/video of the issue?

maybe disable video-toggle plugin and see if it changes anything? (or backup config.json by renaming it which will create a default config on the next launch)

**Comment by zvyap** [comment]
I have same thing happened to me

sometime it fix with reloading the player, but something it just broke for a whole day

https://user-images.githubusercontent.com/52874570/157379884-9da06367-ec88-4d2e-9380-47aff28fae71.mp4
[config.zip](https://github.com/th-ch/youtube-music/files/8211971/config.zip)

**Comment by Araxeus** [comment]
I'm not sure whats causing this, I can't replicate this bug

But I have a feeling that disabling the `video-toggle` plugin might fix this issue for you

**Comment by zvyap** [comment]
I tried disable all my plugins it still had this problem, and also sometime my chrome also will happen this
and I tried to debug my chrome extension and nothing change, it sometime glitch 0.5sec and auto come back to normal position.

**Comment by churchymayer** [comment]
Sorry for the late follow-up, when I disable the `video-toggle` it seems to be working with the exception when starting the app. When switching songs it's fine afterward. I also noticed that YT has the video toggle now built-in (exclusive to YT Premium I believe) so that might cause some interference.
![YouTube_Music_aVeD3CUEbD](https://user-images.githubusercontent.com/18197550/158166136-8323eaf1-cc6f-4bc3-a400-95e19c48ca6b.png)
As you can see the Video Toggle appears twice (with the `video-toggle` plugin enabled)

**Comment by Araxeus** [comment]
lmao they copied my styling or what

@churchymayer to fix it I probably need temporary access to a premium account, if you would be willing to let me test on yours, dm on discord

**Comment by zvyap** [comment]
> YT has the video toggle now built-in (exclusive to YT Premium)
OK, this is my problem bruh
