### ISSUE TITLE
Proxy settings UI does not work

### ISSUE THREAD

**Issue by rasoulMrz** [th-ch/youtube-music#633]
When i click proxy from options menu, a white empty popup opens and nothing works!

![image](https://user-images.githubusercontent.com/28677424/156883959-4beb9bfa-b533-4d42-99bd-961025421cdb.png)

**Comment by Araxeus** [comment]
Sorry about that, it was fixed in #619 (will be included in the next release)

meanwhile you can fix this issue by enabling the `in-app-menu` plugin

**Comment by rasoulMrz** [comment]
Thanks for your response. in-app-menu fixed the issue
