### ISSUE TITLE
[Feature Request] Fade between Songs (Crossfade)

### ISSUE THREAD

**Issue by xdaWolf** [th-ch/youtube-music#634]
Fade between Songs (like Crossfade in Spotify for example)

**Comment by ForlornWolf** [comment]
Yes

**Comment by TemDevz** [comment]
bump

**Comment by xdaWolf** [comment]
Dude, that's awesome!! Just wanted to let you know that I absolutely love this software! Thanks for always adding more features. Keep it up!! Very appreciated!! :)
