### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by rasoulMrz** [th-ch/youtube-music#636]
Is there a way to see download progress?
I press Download, and it says "Downloading" but nothing happens! how can i see if its downloading or is stuck?

**Comment by rasoulMrz** [comment]
This problem gets more annoying when downloading a playlist, as downloading a song does not take too long.

**Comment by Araxeus** [comment]
There is both an indicator in the taskbar on all OS and badge on mac/linux

There's also a progress bar inside the download menu

**Comment by rasoulMrz** [comment]
Thanks for your answer, But I can't find the progress:

![image](https://user-images.githubusercontent.com/28677424/157668978-963402cc-da85-4d46-8cec-dd2c77c8c1e4.png)

**Comment by rasoulMrz** [comment]
The progress showed up after a while! but it would be nice if I knew what was happening before this stage.

Another thing about the indicator: When you click download on a song, the text changes to "Downloading..." for all other songs as well!!
It should be "Downloading.." only for the song that is really being downloaded not other ones!
