### ISSUE TITLE
problem with plugin "downloader"

### ISSUE THREAD

**Issue by 13MrBlackCat13** [th-ch/youtube-music#637]
all time i see this error
 ![image](https://user-images.githubusercontent.com/69348201/157532879-9d71369d-b8f5-4022-a1fb-fa2f327f06c7.png)

**Comment by 13MrBlackCat13** [comment]
but when i click on ... and select download, the song doesn't appear in the selected folder

**Comment by Araxeus** [comment]
You can't download auto-generated playlists
( I know you tried to download one because the url starts with `RDTMAK`

**Comment by rasoulMrz** [comment]
That would be awesome to have a plugin for that as well! 

Another option is a plugin to create a real playlist out of the auto-generated ones!
