### ISSUE TITLE
[Feature Request] Add items from queue to playlist

### ISSUE THREAD

**Issue by takecmd** [th-ch/youtube-music#649]
Although it's wonderful that youtube's AI recommends music I like, it's nasty to add them to my own playlist one by one. If there would be a plugin that could free my hands, it would be convenient to download them. Thanks.

**Comment by TommyHrablo** [comment]
Hallelujah, you wrote exactly what I missing in the app too so much! 
I spent like 10 mins. here to finding  if anyone does not have this improvement request already created, and I found it yours :)

**Comment by JellyBrick** [comment]
Duplicate of #1130
