### ISSUE TITLE
[Enhancement] Discord Integration - Show and Hide

### ISSUE THREAD

**Issue by ForlornWolf** [th-ch/youtube-music#658]
A configurable delay for show and hide feature to enable to see other activities in discord profile.
Example: Turn ON for 10 seconds and Turn OFF for 4 seconds

**Comment by Araxeus** [comment]
This option already exist

`Set inactivity timeout` in discord plugin option

(if it shows you an empty white window, enable in-app-menu first)

**Comment by ForlornWolf** [comment]
It just set the delay to hide when the song is not playing/paused.

**Comment by Araxeus** [comment]
In discord f you go to a server, right click your name and then click on `profile` then go to the `activity` tab
you will see all current activities (everyone can see it if they click on your profile)

I hope this helps

**Comment by ForlornWolf** [comment]
Discord will not show you all activities but only one, which will be Youtube Music. If you see all running activities, you are using modified Discord such as BetterDiscrod or Lightcord.

**Comment by Araxeus** [comment]
That's just wrong, did you even try the steps I wrote?

native desktop discord app:
![image](https://user-images.githubusercontent.com/78568641/160866073-393b82ae-dd06-4a91-a8f9-50474388ce28.png)

browser:
![image](https://user-images.githubusercontent.com/78568641/160866506-03aba4f1-3c63-4e1a-ace5-9b5b74e10e46.png)
