### ISSUE TITLE
Download Plugin seems to be not working

### ISSUE THREAD

**Issue by deeplywithin** [th-ch/youtube-music#66]
Do you have any idea, how I could get this to work?

![image](https://user-images.githubusercontent.com/4288893/100443094-5fcfeb00-30a9-11eb-8a42-a733804fed9d.png)

**Comment by th-ch** [comment]
Hey @deeplywithin, thanks for the feedback! The download plugin works only when playing a music in the foreground (not when exploring with the player being minimized), with URLs like `https://music.youtube.com/watch?v=XXX&list=XXX` (it will then download the music being played).

Does that answer your question? As for the ability to download a music being played while exploring YouTube Music, that's definitely a good improvement (and should be easy to implement) that I have in mind.

**Comment by AbhishekSehwag** [comment]
![Desktop Screenshot 2020 12 02 - 08 58 43 38](https://user-images.githubusercontent.com/75349547/100824731-ca53a300-347c-11eb-9d02-722375a54ea0.png)
Can't download music and i am curious to know where the music is saved.

**Comment by th-ch** [comment]
Hey @AbhishekSehwag, thanks for reporting the issue! Next version 1.6.4 should fix it with the merge of https://github.com/th-ch/youtube-music/pull/76.
As for the folder where files are saved, it should be in [the Downloads folder](https://www.npmjs.com/package/downloads-folder#algorithm), depending on your OS.

v1.6.4 will be released soon, feel free to re-open the issue if needed!

**Comment by AbhishekSehwag** [comment]
> Hey @AbhishekSehwag, thanks for reporting the issue! Next version 1.6.5 should fix it with the merge of https://github.com/th-ch/youtube-music/pull/76.
> As for the folder where files are saved, it should be in [the Downloads folder](https://www.npmjs.com/package/downloads-folder#algorithm), depending on your OS.
> 
> v1.6.5 will be released soon, feel free to re-open the issue if needed!

Yeah man you are great, keep the good work going.

**Comment by AbhishekSehwag** [comment]
> Hey @AbhishekSehwag, thanks for reporting the issue! Next version 1.6.5 should fix it with the merge of https://github.com/th-ch/youtube-music/pull/76.
> As for the folder where files are saved, it should be in [the Downloads folder](https://www.npmjs.com/package/downloads-folder#algorithm), depending on your OS.
> 
> v1.6.5 will be released soon, feel free to re-open the issue if needed!

Also It would be great if we can choose the quality of ****mp3**** file (144kbps/320kbps)

**Comment by th-ch** [comment]
> Also It would be great if we can choose the quality of mp3 file (144kbps/320kbps)

Hey @AbhishekSehwag, custom options have been added in [v1.7.0](https://github.com/th-ch/youtube-music/releases/tag/v1.7.0)! You can go to Plugins > Advanced options and edit the configuration, for example to have 320kbps:
```json
"downloader": {
    "enabled": true,
    "ffmpegArgs": ["-b:a", "320k"]
},
```

Feel free to re-open the issue if something does not work as expected!

**Comment by AbhishekSehwag** [comment]
> > Also It would be great if we can choose the quality of mp3 file (144kbps/320kbps)
> 
> Hey @AbhishekSehwag, custom options have been added in [v1.7.0](https://github.com/th-ch/youtube-music/releases/tag/v1.7.0)! You can go to Plugins > Advanced options and edit the configuration, for example to have 320kbps:
> ```json
> "downloader": {
>     "enabled": true,
>     "ffmpegArgs": ["-b:a", "320k"]
> },
> ```
> 
> Feel free to re-open the issue if something does not work as expected!

Thanks man, you are the most eager developer i have ever seen. Also the downloader is working well now.
