### ISSUE TITLE
Discord Rich Presence not connecting

### ISSUE THREAD

**Issue by ryuuseeii** [th-ch/youtube-music#663]
I have restarted the app after disabling and re-enabling the plugin. Tried to reconnect but failed
![Screenshot 2022-03-28 130952](https://user-images.githubusercontent.com/81773456/160336754-8dcbb338-6e22-4a11-b197-3601d92a4d09.png)
.

**Comment by MulverineX** [comment]
Cannot reproduce

**Comment by valkyrienyanko** [comment]
Does rich presence only work if you have the discord desktop app? I assume it will not work if you only have Discord open in your browser.

**Comment by MulverineX** [comment]
Correct, Discord Activity/Rich Presence works over system RPC which the website version of discord cannot access.

**Comment by lloyd99901** [comment]
Same issue here:
![YouTube_Music_0T3jrG71xk_'Connection_failed'](https://user-images.githubusercontent.com/12370535/205514019-4cfa9cae-98a2-4682-9f5b-8f2cc625c3c6.png)
OS: Windows 10 Pro
Discord Desktop App
Not logged into Google Account.
