### ISSUE TITLE
Lyrics from Genius are incomplete

### ISSUE THREAD

**Issue by brodouevnlyft** [th-ch/youtube-music#664]
Comparing the lyrics in app to those on the Genius website, it seems they're cut off by the featured video. Everything after the video is missing within the app.

**Comment by Araxeus** [comment]
Any example?
Screenshots?

**Comment by brodouevnlyft** [comment]
![genius 1](https://user-images.githubusercontent.com/22804924/161443892-b142ad1e-c965-4ea6-a496-43962c834f4b.png)
![genius 2](https://user-images.githubusercontent.com/22804924/161443909-4d066bfc-afb9-4de3-90c7-d1a300a9ac70.png)

These were taken on two separate days, and you can see that the point where the lyrics cut off changed when the location of the featured videos portion changed.

Song is Velvet Waltz by Built To Spill. This has happened on other songs too, though, usually longer ones.

**Comment by Araxeus** [comment]
Hey I finally found some time to isolate the issue and fix it, I've opened a PR in #671
