### ISSUE TITLE
RPC_CONNECTION_TIMEOUT showing when trying to connect to discord

### ISSUE THREAD

**Issue by notAxion** [th-ch/youtube-music#665]
idk what is the problem this software or my account 
but the rich presence for discord isn't working for some reason 
yesterday it sometimes was disconnecting but it was fixed after reconnecting again from the plugin options 
but today it was connecting but showing `RPC_CONNECTION_TIMEOUT` error after like 2 or 3 mins (my inactivity timeout is set to 600 mins.)
and now it is straight up declining to connect at all and showing the error after 10 secs or so

 i am running on macOS 10.15.7
 youtube-music - Version 1.16.0 (1.16.0)

**Comment by ELowry** [comment]
I am experiencing a similar issue:

Discord RPC isn't showing anything from YT music.

I get the `RPC_CONNECTION_TIMEOUT` after about 10 seconds when I try to reconnect manually.

I am running Windows 11 21H2
youtube-music V1.17.0

**Comment by notAxion** [comment]
Apparently it gets fixed when i restart both discord and yt-music 🤔
