### ISSUE TITLE
Apple Silicon (arm64) version cannot be opened

### ISSUE THREAD

**Issue by jianglai** [th-ch/youtube-music#666]
When I tried to launch it the error message said:

"YouTube Music" is damaged and can't be opened. You should move it to the Trash.

If I `xattr -c` on the app I can open it, but obviously this is not a proper solution...

Can you please sign the app properly and release it? The Intel version works (without being signed) under Rosetta.

**Comment by Araxeus** [comment]
It cost 100$ monthly to code sign on apple

Who's going to pay that?

**Comment by DanDobrick** [comment]
> It cost 100$ monthly to code sign on apple

@Araxeus it's actually $100/yr

**Comment by Araxeus** [comment]
> @Araxeus it's actually $100/yr

You're right, my bad


https://developer.apple.com/support/compare-memberships/

**Comment by jianglai** [comment]
I'm not sure if it's something particular to amr64 builds, but with Intel unsigned apps I usually just need to go to Gatekeeper and allow it. The "damaged app" error requires me to use `xattr -c` to run it, and if I click on "learn more" when the error is shown, it directs me to a FAQ page where it talks about the app maybe tampered with after it's signed.

I certainly was not asking anymore to fork over their own money, and I appreciate the work that was put into this free software.
