### ISSUE TITLE
RAM rises Youtube Music App 1.1.16

### ISSUE THREAD

**Issue by soccer1904** [th-ch/youtube-music#667]
on Win 10 Pro as time goes by till the app doesn't work anymore after about 4 h. Is there a solution?
kind regards...

**Comment by amerodeh** [comment]
Ah, is it a bug with the new version then? I just reported a RAM issue here, but now that I think about it I've been using the app without issues for many weeks.
https://github.com/th-ch/youtube-music/issues/295#issuecomment-1095714094

**Comment by soccer1904** [comment]
I think it may depend on how long the playlist is? Did you try long Playlists with more than 400 songs?
