### ISSUE TITLE
[Feature Request] Discord Settings

### ISSUE THREAD

**Issue by EdwinForero** [th-ch/youtube-music#683]
I would like to be able to configure these parameters(or similar) for discord rich presence. Good jod and thanks in advance.

![imagen](https://user-images.githubusercontent.com/90881245/162593837-02553af4-3b4a-41cc-9687-3576a16aec31.png)

**Comment by Araxeus** [comment]
you can set an inactivity timeout of 0 to mimic "Show track when playback is paused - Off"

if you want I can add options to hide title/artist/tracktime. but what should be displayed there instead? should the line just be empty?

![image](https://user-images.githubusercontent.com/78568641/162634826-a166b3e2-3cf0-472e-ba10-dbc8bdc5e0e3.png)

also out of curiosity, why would you want to disable the title/artist/time ?

**Comment by EdwinForero** [comment]
Yeah, the line might be empty and i guess something must happen with the album cover, as you prefer. 

> also out of curiosity, why would you want to disable the title/artist/time ?

Sometimes I just put the track time and the artist. Other times just track time. 
I think maybe other people turn off all options.
