### ISSUE TITLE
YT Music closes and dosen't start up after installing

### ISSUE THREAD

**Issue by ItzRainbowMC** [th-ch/youtube-music#687]
YT Music closes then never opens. I checked it on Task Manager if it's running in the background, and it isn't

I'm using Windows 10 on ASUS.

**Comment by ItzRainbowMC** [comment]
BTW I installed YT music 1.14.0 and tried 1.16.0- just a tip

**Comment by Araxeus** [comment]
try deleting config.json in `%AppData%/Youtube Music` (MyUser/AppData/Roaming/Youtube Music/config.json)

**Comment by th-ch** [comment]
Hey everyone, closing from lack of activity (I guess the issue is resolved with the latest version), feel free to re-open if needed!
