### ISSUE TITLE
SHA512 do not match

### ISSUE THREAD

**Issue by hbarsaiyan** [th-ch/youtube-music#69]
The SHA512 checksum of the AppImages releases are different from that mentioned in latest-linux.yml. For eg. in 1.6.4:

in latest-linux.yml:
`sha512: 2bdeFR5gm96WlMlg97n/QPFoHTOLV12GlIeApvR6WlgYO1UG6eDCKzlZRoLTn+obQNlp3746Mu3hFJKwbJa/yw==`

```
$ sha512sum YouTube-Music-1.6.4.AppImage
d9b75e151e609bde9694c960f7b9ff40f1681d338b575d86948780a6f47a5a58183b5506e9e0c22b39594682d39fea1b40d969dfbe3a32ede11492b06c96bfcb  YouTube-Music-1.6.4.AppImage
```

**Comment by hbarsaiyan** [comment]
Or do these SHA512 hashes refer to something else?

**Comment by th-ch** [comment]
Hey @hbarsaiyan, thanks for submitting the issue! The release/update process comes from [electron-builder](https://github.com/electron-userland/electron-builder) - you can verify checksums in different ways:
- CLI (see [this StackExchange question](https://unix.stackexchange.com/questions/3675/how-can-i-get-a-base64-encoded-shax-on-the-cli) for details): 
```sh
$ sha512sum YouTube-Music-1.6.4.AppImage | cut -f1 -d\  | xxd -r -p | base64 -w 0
2bdeFR5gm96WlMlg97n/QPFoHTOLV12GlIeApvR6WlgYO1UG6eDCKzlZRoLTn+obQNlp3746Mu3hFJKwbJa/yw==
```
- node.js script (see this [electron-builder issue](https://github.com/electron-userland/electron-builder/issues/3913#issuecomment-504698845)):
```js
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const YOUR_FILE_PATH = 'YouTube-Music-1.6.4.AppImage';

function hashFile(file, algorithm = 'sha512', encoding = 'base64', options) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash(algorithm);
    hash.on('error', reject).setEncoding(encoding);
    fs.createReadStream(
      file,
      Object.assign({}, options, {
        highWaterMark: 1024 * 1024,
        /* better to use more memory but hash faster */
      })
    )
      .on('error', reject)
      .on('end', () => {
        hash.end();
        console.log(hash.read());
        resolve(hash.read());
      })
      .pipe(
        hash,
        {
          end: false,
        }
      );
  });
}

const installerPath = path.resolve(
  __dirname,
  YOUR_FILE_PATH
);

hashFile(installerPath);
```
```sh
$ node hash.js
2bdeFR5gm96WlMlg97n/QPFoHTOLV12GlIeApvR6WlgYO1UG6eDCKzlZRoLTn+obQNlp3746Mu3hFJKwbJa/yw==
```

Does it answer your question?

**Comment by hbarsaiyan** [comment]
@th-ch thanks for the detailed explanation. I didn't about Base64 hash encoding.
