### ISSUE TITLE
Songs Have To Be Manually Started Everytime

### ISSUE THREAD

**Issue by VaxYourDamnKids** [th-ch/youtube-music#690]
All of a sudden, a week or two ago the app refuses to play the last played song. No biggie, I click on the play button manually. But when each song is done the entire playlist stops and you must manually click play again. Every. Single. Time. 

I tried different settings but nothing. I reinstalled, tried the installed and portable version and neither works anymore. Ideas?

Thanks for the awesome app, btw!

**Comment by Araxeus** [comment]
Are you sure that you don't have the `disable-autoplay` plugin on?

Can't really think of anything else that could cause this..
