### ISSUE TITLE
Video Toggle Issue

### ISSUE THREAD

**Issue by thijsi123** [th-ch/youtube-music#692]
The Video Toggle plugin interferes with the new feature baked into youtube music to toggle video or song only.
![image](https://user-images.githubusercontent.com/64159148/163676632-952ab4bb-624c-440c-b341-7aefa715355f.png)
Edit: The feature from youtube music itself doesn't work when the video toggle is enabled or disabled, So I have to use the video toggle plugin, which causes the video to be lowered.

**Comment by Araxeus** [comment]
From what I understand this native feature is only available to Premium users.

So you can disable `video-toggle` plugin if you have a premium account

**Comment by thijsi123** [comment]
> From what I understand this native feature is only available to Premium users.
> 
> So you can disable `video-toggle` plugin if you have a premium account

Ahh that's why it didn't work, thanks.

**Comment by thijsi123** [comment]
Thanks for working on it : ).
I'll now close this issue.

**Comment by Araxeus** [comment]
Hey, would you prefer the plugin or the native implementation?

**Comment by Araxeus** [comment]
Because I'm pretty sure I can enable the default native implementation for everyone. 
which makes the `video-toggle` plugin kinda redundant?

**Comment by thijsi123** [comment]
I'll prefer native.

**Comment by thijsi123** [comment]
I think it's better that way now with youtube their own implementation.

**Comment by Araxeus** [comment]
😭 all the hours I spent coding this plugin 😭

**Comment by Araxeus** [comment]
Ok I decided against deleting the plugin, but there will now be an option called "Mode" which lets you choose between
* "Custom" - the plugin version
* "Native" - the native youtube implementation'
* "Disabled" - disable all video toggles

That pr will also fix this issue by automatically hiding native button if the custom button is enabled
