### ISSUE TITLE
no metadata/cover art being added when downloading with custom ffmpeg args

### ISSUE THREAD

**Issue by IPushedU** [th-ch/youtube-music#705]
When downloading with custom args, by changing them in the config files, no metadata such as the cover art is effectively added, i.e. the `Adding metadata...` does show up at the end of a download but when viewing the file in a player, no metadata/cover art is visible, its just empty. This issue doesn't affect the mp3 preset. Is it a known issue or just a problem with my downloader configuration? Or I suspect that `libopus` doesn't support metadata (yet). 

P.S. Trying to add metadata externally with an app, on some programs an error regarding something like `Java IO.HeadStream and (header) stream not found` is given.

`Downloader` configuration currently in use: 
``` json
"downloader": {
		"enabled": true,
		"extension": "opus",
		"ffmpegArgs": [
			"-acodec",
			"libopus",
			"-b:a",
			"256000",
			"-vbr",
			"on",
			"-compression_level",
			"10",
			"-application",
			"audio",
			"-mapping_family",
			"1"
			],
...
}
```

**Comment by Araxeus** [comment]
@th-ch

**Comment by qtotter** [comment]
I use flac for output, but it's the same that no meta data is added, either. Anyway, thanks for the great app! It crashes once in awhile when multiple albums are beinng downloaded, but it works great other than that.

**Comment by Zo-Bro-23** [comment]
Try `-id3v2_version 3`

**Comment by qtotter** [comment]
thanks, but it didn't work...

`		"downloader": {
			"enabled": true,
			"extension": "flac",
			"ffmpegArgs": [
				"-acodec",
				"flac",
				"-f",
				"flac",
				"-id3v2_version",
				"3"
			]
		},
`

**Comment by Zo-Bro-23** [comment]
I am unfamiliar with this, sorry. I've only worked with `youtube-dl`.
