### ISSUE TITLE
Add option to only play audio

### ISSUE THREAD

**Issue by valkyrienyanko** [th-ch/youtube-music#707]
Please add an option to only listen to the audio, I do not want to waste internet bandwidth on video I almost never look at.

**Comment by Araxeus** [comment]
If its about the internet bandwidth, you can use the `quality-changer` plugin to reduce the quality to 480p
(360p will also reduce your audio quality)

And then if you want to hide the video you can use the `video-toggle` plugin to switch to "Song mode"
(keep in mind that the video will still be cached locally, the audio is part of the video - and I personally don't think its possible to access the audio without downloading the video

**Comment by Araxeus** [comment]
My comment above apply only when you are watching a video

To really achieve what you want, just play the "Song version" instead

For example:

This is a video
https://music.youtube.com/watch?v=H1HdZFgR-aA

this is a pure song:
https://music.youtube.com/watch?v=zgZ52M4a_R0

**Comment by devnoname120** [comment]
Actually there is a plugin to hide the video: `Video Toggle: Adds a button to switch between Video/Song mode. can also optionally remove the whole video tab`

**Comment by rsmyst** [comment]
> 

Hello @Araxeus, i am aware this issue it closed. I just wanted to now if i can entirely disable video loading. Because a lot of CPU is being consumed on processing the music video in the background and my laptop is pretty weak. some help would be appreciated!
