### ISSUE TITLE
Tons of dowload issues.

### ISSUE THREAD

**Issue by kwc23** [th-ch/youtube-music#708]
Hi, I'm trying to download a playlist with 1.5k songs (I don't really know if that's possible but if it isn't please tell me) but have gone through a lot of errors.

Erorr: aborted
Error status 410
Error: socket hang up
Error: ETIMEDOUT and random numbers
Error: read ECCONRESET

The given above are the errors I've received. It popped up a lot on my screen so I decided to abandon the download and came here to report the problem. 

I don't have any problem downloading one song at a time but I can't dowload the playlist. I did both methods on downloading the playlist and also restarted the app but nothing different happened.

**Comment by altruistdevil** [comment]
same here

**Comment by Araxeus** [comment]
might be fixed by https://github.com/th-ch/youtube-music/pull/1054

there will still be an error popup if a song can't be downloaded (not available in your region for example)
