### ISSUE TITLE
Remove/disable video auto pause

### ISSUE THREAD

**Issue by ubreathtaking** [th-ch/youtube-music#71]
Morning, would like to understand how to remove/disable "video playback - autopause". 

Searched in toggle dev option .. without success. Hope someone can help me.

**Comment by th-ch** [comment]
Hey @ubreathtaking, thanks for submitting the issue! Are you talking about the `Auto confirm when paused` plugin (it resumes playing automatically when the "Continue Watching?" modal appears)? If yes, you can un-check it in the "Plugins" menu (you will need to restart the app for the change to take effect).
Or is it something else?

**Comment by ubreathtaking** [comment]
@th-ch  yes that was it, the plugins .. next to the options/toggle dev mode (that's the place where i was searching/modifying stuff to make it work ). Thank you kind sir.
