### ISSUE TITLE
Gapless playback

### ISSUE THREAD

**Issue by MaximUm47** [th-ch/youtube-music#715]
I try to find a way to avoid gaps between songs. I tried **skip-silences** plugin but still I have gaps between tracks.

Is there a way to achieve this or there is no such feature yet?

**Comment by Araxeus** [comment]
What do you mean "gaps"?

Are you talking about the time it takes to load a song?

To fix that, we would have to completely rewrite youtube music so that it works like spotify (downloading tiny parts and caching them)

That would be very complicated and pretty much out of scope IMO

> the above is my opinion and might be wrong

**Comment by MaximUm47** [comment]
> Are you talking about the time it takes to load a song?

Yep. Because the player needs some time to load next song we have such gaps between tracks. It is very annoying when you listen some long Trance mix where songs are softly spills over another. In some players the feature is called "gapless".

I do not know how the app is build internally but what if add a listener which gets notified when let's say 5 seconds left of current track and it triggers a pre-downloading the next song?

**Comment by JellyBrick** [comment]
https://github.com/th-ch/youtube-music/tree/master/plugins/crossfade
