### ISSUE TITLE
Download button glitch

### ISSUE THREAD

**Issue by GabiGunner** [th-ch/youtube-music#716]
Hello!
Activated "downloader" plugin, then clicked "More actions" button (three dots), Then, I saw the downloads button beeing very big.
![Screenshot 1](https://user-images.githubusercontent.com/101864779/167916073-5ff3bf35-800f-4af9-a0aa-d398a5b53340.png)
![Screenshot 2](https://user-images.githubusercontent.com/101864779/167916083-c0eb6b21-31a3-495a-aeda-909b15acb0e0.png)
**(so big in fact that it exited the menu black rectangle)**

**NOTE**: Forgot to mention that I use the AppImage version.

Thanks for dedicating your time to this project!                                                                                                             Regards, Gabriel

**Comment by Araxeus** [comment]
Woah that's very weird...

If you enabled the `playback-speed` plugin, is the slider in the menu also big?

Could you open devtools (Advanced Options - Toggle devtools or <kbd>ctrl</kbd><kbd>shift</kbd><kbd>i</kbd>)
and inspect the download button and see if it have the correct height and width in the inject stylesheet?

![image](https://user-images.githubusercontent.com/78568641/167921645-bed92fc8-b13a-4e9e-aed1-dd62b082a5cb.png)

you can DM me on discord `Araxeus#0819` if you need help

**Comment by GabiGunner** [comment]
> Woah that's very weird...
> 
> If you enabled the `playback-speed` plugin, is the slider in the menu also big?
> 
> Could you open devtools (Advanced Options - Toggle devtools or <kbd>ctrl</kbd><kbd>shift</kbd><kbd>i</kbd>)
> and inspect the download button and see if it have the correct height and width in the inject stylesheet?
> 
> ![image](https://user-images.githubusercontent.com/78568641/167921645-bed92fc8-b13a-4e9e-aed1-dd62b082a5cb.png)
> 
> you can DM me on discord `Araxeus#0819` if you need help

After some time the button magicly fixed itself... Even in the older version...
