### ISSUE TITLE
exponential-volume not working?

### ISSUE THREAD

**Issue by ryanbuening** [th-ch/youtube-music#718]
I have enabled exponential-volume on 1.16.0, but it does not seem to be applied:

![image](https://user-images.githubusercontent.com/812974/168299048-67cbabbc-086e-40a8-bbd2-bdc73b98a516.png)

I'm assuming that plugin is using [this script](https://greasyfork.org/en/scripts/426684-youtube-music-logarithmic-exponential-volume/code), which does seem to work when I navigate to YouTube Music via a regular browser:

![image](https://user-images.githubusercontent.com/812974/168299354-95877367-47cc-4f91-8c92-701c886acfb9.png)

**Comment by Araxeus** [comment]
that plugin is a port of https://greasyfork.org/en/scripts/397686-youtube-music-fix-volume-ratio/
see #488 

My advice: try out the precise volume plugin 😉

**Comment by ryanbuening** [comment]
I enabled that and tried to set custom steps, but I get a dialog that looks like the following:

![image](https://user-images.githubusercontent.com/812974/168301385-811aa8da-b9e6-461f-a143-1417f7fc89be.png)

**Comment by Araxeus** [comment]
Sorry, it's a bug that was fixed months ago but a new version including it has yet to be released 😢 @th-ch 

You can fix it temporarily by enabling the `in-app-menu` plugin
