### ISSUE TITLE
plugins not working really well

### ISSUE THREAD

**Issue by MeGaNeKoS** [th-ch/youtube-music#72]
i need to restart the app for enable/disable the pulg-in. i think it's better to make it realtime or force reload the page.

**Comment by th-ch** [comment]
Hey @MeGaNeKoS, thanks for the feedback! [v1.7.1](https://github.com/th-ch/youtube-music/releases/tag/v1.7.1) adds an option to automatically restart the app (default set to `false` to keep backwards-compatibility) when options or plugins are changed!
Feel free to give it a try and re-open the issue if needed!
