### ISSUE TITLE
shortcuts crashing

### ISSUE THREAD

**Issue by sp0ok3r** [th-ch/youtube-music#720]
Sometimes shortcuts don't respond and if i try to change the key it crashes with a white window..
![erroyoutubemusicgithub](https://user-images.githubusercontent.com/7952298/168441868-e969ca22-b32b-47c4-bb88-e21dd2e2ce17.png)

**Comment by sp0ok3r** [comment]
I can play/stop until I open the app, i cant play and pause with the shortcut but can select next

**Comment by Araxeus** [comment]
sorry you need to enable the `in-app-menu` plugin to fix the white window bug

Don't really understand the rest of your problem tho

**Comment by sp0ok3r** [comment]
works thanks

**Comment by Araxeus** [comment]
@th-ch we really need a new version 😅
