### ISSUE TITLE
In-app-menu increases top of page.

### ISSUE THREAD

**Issue by renatocfrancisco** [th-ch/youtube-music#723]
When activated, the **In-app-menu plugin** increases the top of the home/explore/library shelf.
Yeah, i know, it's not breaking anything, but it's something weird i saw.

![YouTube_Music_fMQpcDuHng](https://user-images.githubusercontent.com/56325092/169426811-adca728c-ed17-4167-9f30-3544969b159d.png)

**Comment by Araxeus** [comment]
I've opened a PR which will fix this issue 🙂 #734
