### ISSUE TITLE
Application Update window issue

### ISSUE THREAD

**Issue by Starboy345** [th-ch/youtube-music#726]
Every time I open the app using the taskbar pinned shortcut, a popup opens that says there is a new update (there is not a new update whenever I check). But when I open the app via the .exe file in my downloads, it does not come up with the update window. This happened on v1.16 and now on v1.17 as well. 

![image](https://user-images.githubusercontent.com/83980608/169652445-4a94aa1c-27bb-4236-9009-80532f0aa836.png)

**Comment by Araxeus** [comment]
did you install this? https://github.com/th-ch/youtube-music/releases/download/v1.17.0/YouTube-Music-1.17.0.exe
is the target of your shortcut `C:\Users\MyUser\AppData\Local\Programs\youtube-music\YouTube Music.exe`?

**Comment by Starboy345** [comment]
Didn't install the setup .exe and I'm not sure how to check the target of the shortcut because it is on the taskbar. When I open the app, I just pin the icon to my taskbar.

**Comment by Starboy345** [comment]
I've downloaded the setup .exe and ran it. The update window issue seems to have been fixed but now on my taskbar, the youtube music icon does not show. It shows a blank page icon. I can still open and run the app using it though.

**Comment by Starboy345** [comment]
I don't know how but all issues have been fixed by restarting the computer so nevermind :)
