### ISSUE TITLE
Issue with downloading whole playlist 

### ISSUE THREAD

**Issue by ubreathtaking** [th-ch/youtube-music#731]
Hello, i have enabled plugin - download , and i can download one song at a time, yet while i try to download whole list of songs - it gets this message :

![image](https://user-images.githubusercontent.com/8896375/170248626-0b903560-22ec-4904-89c4-75d4ae789ecc.png)

**Comment by Araxeus** [comment]
The downloader plugin can only download public playlists that are not auto-generated

You are trying to download a private auto-generated playlist. that isn't supported currently

**Comment by ubreathtaking** [comment]
@Araxeus  it's liked music 
![image](https://user-images.githubusercontent.com/8896375/170278863-de21178d-d655-47c0-8db2-4fd081781f9a.png)

**Comment by ubreathtaking** [comment]
@Araxeus  understood, than you

**Comment by Moe1369** [comment]
I'm sorry for reopening but it is possible to download your liked playlist with youtube-dlp or youtube-dl-gui(the electron one)
export your youtube music cookie and then download the playlist.
Here's an example guide

https://github.com/jely2002/youtube-dl-gui/wiki/Tutorial:-Private-videos-&-playlists

**Comment by Araxeus** [comment]
You're actually right, ytdl-core seems to have an option to pass cookies

https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js

**Comment by Araxeus** [comment]
Progress update:

I've managed to enable downloading private playlists and songs

But! Playlists that are longer than 100 songs requires a second API call which I cannot make work using cookies right now
