### ISSUE TITLE
tried lots of SOCKS5 proxy but not a single one worked.

### ISSUE THREAD

**Issue by ItsIsmailRobin** [th-ch/youtube-music#736]
@th-ch Sir help me to find working SOCKS5 Proxy.

**Comment by th-ch** [comment]
Hey @ItsIsmailRobin, this repo provides software but hosts no proxy, not sure there is anything actionable here unfortunately! Closing, feel free to open issues for bugs or features!

**Comment by ItsIsmailRobin** [comment]
I Got proxy already thanks for reply and your are doing great bro.
i hope you will update discord rpc more better.
Overall thanks for this !!!
