### ISSUE TITLE
Feature Request: Remote Control Android App or remote control API/webserver

### ISSUE THREAD

**Issue by briantho** [th-ch/youtube-music#739]
Hi, I just discovered this app, and it works great. I'm so happy that it supports ad blocking, and plugins without issues. The only feature missing for me, is a way to control it from an android phone. My suggestion would be to create a remote control API, and maybe an android remote control app, so I could control music playback without having to go to my computer downstairs every time I want to skip tracks. If not an android app, then perhaps a web remote? something that hosts web server within the app, and can be controlled from anything in the local subnet via a web browser. Either way, this is a must in my opinion.

**Comment by DaNeoPenguin** [comment]
i think this is a cool idea ! 
Devs should try this 😄

**Comment by BhaturaGuy** [comment]
Cool feature

**Comment by thijsi123** [comment]
See #704 
Use it as an alternative for now.

**Comment by Zo-Bro-23** [comment]
Will be fixed by #1094.

**Comment by JellyBrick** [comment]
Keep tracking on #1270
