### ISSUE TITLE
Add the disable hardware acceleration toggle

### ISSUE THREAD

**Issue by matheusfillipe** [th-ch/youtube-music#74]
This feature is already available on the official app and is pretty important to some linux users with nvidia gpu's like me. If is not disable after suspending my machine youtube-music is always unusable and I have to restart it then.

**Comment by th-ch** [comment]
Hey @matheusfillipe , thanks for the feedback! Next version 1.6.5 will add the option with the merge of https://github.com/th-ch/youtube-music/pull/77.

v1.6.5 will be released soon, feel free to give it a try and update the issue accordingly!

**Comment by matheusfillipe** [comment]
Thanks! It works!
