### ISSUE TITLE
The YouTube Music app does not show the content on Hebrew

### ISSUE THREAD

**Issue by OmerPhilo1205** [th-ch/youtube-music#740]
In the YouTube Music app, it is not possible to see the content of the playlists / singers in the Hebrew language.

I have been using YouTube Music on the phone for two years now and since the March update the content could not be seen on the pages of YouTube Music.

I spoke to one of the people in support of your plan in March and he did not come back to me until :(

During this time I switched a phone from LG G7 (where the problem started) to samsung galaxy s21 fe and it also means I switched from Android 10 to 12, it did not help.

Today I decided to try going back a version from the latest version to version 4.64.52 which came out in late February and it helped.

I switched to a reverse version through this site (https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-4-64-52-release/youtube-music-4-64-52-2-android-apk-download/download/?forcebaseapk=true)

**Comment by OmerPhilo1205** [comment]
And I submitted the bug to Google but of course they did not answer me
https://issuetracker.google.com/issues/232060577

**Comment by Araxeus** [comment]
Uuuh this is a desktop app - we are not related in any way to the Google Team / Youtube Team / Official Youtube App

**Comment by maxneedspats** [comment]
@Araxeus 
Might I suggest to close this?

**Comment by Araxeus** [comment]
Im just a contributor, I can't close issues myself

**Comment by OmerPhilo1205** [comment]
I closed it
@OmerPhilo


‫בתאריך יום ה׳, 18 באוג׳ 2022 ב-1:26 מאת ‪maxneedspats‬‏ <‪
***@***.***‬‏>:‬
