### ISSUE TITLE
Play/pause dbus control does not work until play button is clicked

### ISSUE THREAD

**Issue by lukaszg84** [th-ch/youtube-music#741]
**Steps to reproduce**

1. Turn off "Resume last song when app starts" option
2. Turn on "shortcuts" plugin to enable dbus interface
3. Restart application, start any playlist.
4. Verify with dbus that status is "playing":

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.youtube-music \
  /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
  string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' \
  | grep '"Playing"'
   variant       string "Playing"
```

5. use dbus command to stop the playback:

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.youtube-music \
  /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
```

**Expected behaviout:**
Playback stops

**Actual behaviour**
Application is still playing music, but the dbus status is "Paused":

```
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.youtube-music \
  /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
  string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'
method return time=1654605627.143655 sender=:1.2169 -> destination=:1.2180 serial=15 reply_serial=2
   variant       string "Paused"
```

**Workaround**

If you click on "pause" button with mouse, the issue is fixed and the app works ok until the next restart

**Comment by Araxeus** [comment]
If you try to pause using the tray button instead of the mpris interface, do you face the same problem?

(logically you should)

**Comment by Araxeus** [comment]
Well I'm on windows and can tell you two things:
1. This bug doesn't happen on my pc
2. `semicolon` is not a play/pause shortcut (it actually doesn't do anything on my PC)

But I will look into changing the `playPause` function to programmatically pause the video instead of emulating the space key

**Comment by Araxeus** [comment]
I've edited my previous message too many times, anyways would be nice if you could test the semicolon change locally

**Comment by lukaszg84** [comment]
Changing to ";" fixed the problem.

**Comment by Araxeus** [comment]
Well you could open a PR with this change, or if you don't want to, I could open it myself later
