### ISSUE TITLE
Album cover label on Discord off by one

### ISSUE THREAD

**Issue by etomasic** [th-ch/youtube-music#744]
With the Discord rich presence, the name of the album when hovering the cover displays the previous song's album.
![ex](https://user-images.githubusercontent.com/45695696/172762265-90336f03-f559-472f-9a16-2a5555a2930d.png)

**Comment by Araxeus** [comment]
Works fine for me, does this happen every time for you or just occasionally?

**Comment by etomasic** [comment]
Yes, it seems to happen every time. The first song in the queue works fine though, presumably because there's no previous song.

**Comment by TemDevz** [comment]
Same issue here; only occurs when in autoplay. 
![image](https://user-images.githubusercontent.com/25987110/201398581-236990e1-5788-468b-9d40-5d2b57a782b8.png)

**Comment by iliqiliev** [comment]
I get this constantly on Linux too

**Comment by Araxeus** [comment]
The album name is the only thing that is captured through dom elements instead of through youtube api (because it doesn't seem to exist there)

So probably somehow on your pc's album name in the dom gets updated late

Not quite sure how to fix it for you

**Comment by ArgoWarsmith** [comment]
Hi everyone. Is there a way to disable the hover over feature? I also have this glitch. Thank you.

**Comment by Zo-Bro-23** [comment]
Currently, no, but it's probably easy to implement. I currently don't have much free time on my hands though (unfortunately), so would @Araxeus or @xhayper like to take it up?

**Comment by Araxeus** [comment]
Well if you read my last comment, I have a solution in mind. But it requires #946 to be merged first (like many other things I think about doing 😝)

**Comment by Araxeus** [comment]
btw here are 2 better ways to get the album name:
```js
navigator.mediaSession.metadata.album
```
```js
$('ytmusic-player-page').getState().playerPage.playerOverlay.playerOverlayRenderer.browserMediaSession.browserMediaSessionRenderer.album.runs[0].text
```
