### ISSUE TITLE
Queries on video toggle and hardware acceleration

### ISSUE THREAD

**Issue by TripleK2004** [th-ch/youtube-music#748]
Is the video being downloaded in background even after switching to song only mode ?
My network traffic spikes when changing songs similar to caching/downloading a video

About the HW accel, i dont see any video decoding happening in intel_gpu_top. Is it because the app is sandboxed or is it not decoding the vp9/8 videos

**Comment by Araxeus** [comment]
Yup sorry video download cannot be avoided, tho you can use `quality-changer` plugin to reduce the video resolution and subsequently the download size (it saves the quality in cookies so doing it once is enough)

**Comment by Araxeus** [comment]
> > you can use `quality-changer` plugin to reduce the video resolution
> Does this setting affect audio quality as well?

I'm not actually sure, but if it works like normal youtube then you get max audio quality at 480p
