### ISSUE TITLE
How to build for linux without installing wine.

### ISSUE THREAD

**Issue by programerr01** [th-ch/youtube-music#75]

**Comment by th-ch** [comment]
Hey @programerr01, thanks for the question! Wine should not be needed to build the app for Linux, you can either download the [latest release for Linux](https://github.com/th-ch/youtube-music/releases/latest) or build it yourself (you will need node.js/yarn):
```sh
git clone https://github.com/th-ch/youtube-music
cd youtube-music
yarn
yarn build:linux
```

Closing the issue, feel free to re-open if needed!
