### ISSUE TITLE
Bitdefender started blocking it/says it's a virus.

### ISSUE THREAD

**Issue by JustEbu** [th-ch/youtube-music#757]
Since today (17.06.2022) i can't launch "YouTube-Music-1.17.0.exe" anymore because BitDefender is blocking "app-64.7z" which is being used when launching the application. BitDefernder says it's "Gen:Variant.Lazy.163984"
VirusTotal link to the 7z file: https://www.virustotal.com/gui/file/6f59398cd9966ff02478ec4179e0763a775d00d14541de1fd5bd61e5ec8b66cf

**Comment by NoHidSe** [comment]
Its probably a false positive
Thats why virustotal show multiple scan with diffrent antivirus so you can check if its a false positive

**Comment by JustEbu** [comment]
Virustotal now only shows 2 detections instead of 8 which is a good sign. However the other problem i see now is in a file named ".rdata". If you used the installer version it's accessible when you right click the "YouTube Music.exe" and open it with 7-zip. Inside the file .rdata" when viewed via editor there are some weird lines with cryptocurrencies mentioned in it and some weird products. Proof: https://i.imgur.com/DjooXHK.png
This should be a YouTube Music app and seeing such weird lines is a bit odd for my taste or am i just paranoid?

Here is the Youtube Music.exe file when installed and scanned via VirusTotal: https://i.imgur.com/5pVaQno.png & https://www.virustotal.com/gui/file/e1bd99e42f5e2bc5430e50eedb4558e9e8398e76756ebce3321cb435dc0b62ad

**Comment by JustEbu** [comment]
> Not sure what the `.rdata` file is exactly, the app is built using [Electron](https://github.com/electron/electron)/[Electron Builder](https://github.com/electron-userland/electron-builder)
> 
> it includes some other weird keywords like `AT&T Go Phone` ` Wireless Optical Mouse` `Digital Camera Pocket` `My Passport Ultra` `Consumer Headset Wireless Dongle` `MP3 Player` and many more seemingly unrelated stuff
> 
> anyways the app is completely open-source, you can see all the code and build it yourself (I can help with that if you want)

Thanks for mentioning Electron/Electron Builder! The .rdata file is also included in the electron.exe and has the weird lines with bitcoin and other stuff too. For me this issue is closed since BitDefender isn't blocking it anymore.

Thanks for the great work and Application, really appreciate it!
