### ISSUE TITLE
YouTube Music can't open

### ISSUE THREAD

**Issue by Anifyuli** [th-ch/youtube-music#758]
Hello, Mister.
I have problem with youtube-music on Fedora 36 from RPM package. Previously, that app can launch flawlessly. But, after I try to activate again navigation extension to bring back navigation button, this app can't launch. 
I try to fix with erase this package and install again with much method. But it can't help to solve this problem. If I open this app, this app can't show a window but it run on background. This pict can give a description about this problem.
![Screenshot from 2022-06-18 21-41-50](https://user-images.githubusercontent.com/73734843/174443654-1830c99a-0e06-48d0-9498-e438ea325b37.png)
I wish you can fix this problem. I only give a contribution with make this issue due to my programming skill is low. Thanks for your patient. Sorry my English

**Comment by Araxeus** [comment]
Your config file might have gotten corrupted somehow, try resetting your config

config location on linux is `~/.config/Youtube Music/config.json`

you can either straight up delete it or rename it which will make it a backup

if that doesn't work try deleting the whole folder

**Comment by Anifyuli** [comment]
> Your config file might have gotten corrupted somehow, try resetting your config
> 
> config location on linux is `~/.config/Youtube Music/config.json`
> 
> you can either straight up delete it or rename it which will make it a backup
> 
> if that doesn't work try deleting the whole folder

Your suggestion help me to solve this problem. Thanks, Mister
