### ISSUE TITLE
Program skipping parts in multiple songs

### ISSUE THREAD

**Issue by MxjorZ** [th-ch/youtube-music#759]
So, I interfere with an issue on this program, tested it on standard YouTube Music and the issue didn't appear in both web and desktop versions.
So today I have updated the program from build 1.13 to build 1.17 and from then it started to skip parts of multiple songs.
Let's say the length of a song is 3:08 (3 minutes and 8 seconds), and there is a part starting a 2:17 and ends at 2:25.
The program totally skips that part like it doesn't exist in the song and it really gets annoying from time to time.
I have to point out that this particular part is being skipped after the song is playing again and again, so it's not a 1 time issue, it happens constantly.

I would like to know if there is a possibility a plugin of the custom program is causing the problem to happen, and if there is any fix for it.
I don't know if I'm the only one experiencing this.

**Comment by Araxeus** [comment]
What are your enabled plugins?
from the top of my head the only one which can cause this is `Sponsorblock`

Also can you give a specific example to see if this can reproduced?

**Comment by MxjorZ** [comment]
> What are your enabled plugins? from the top of my head, the only one which can cause this is `Sponsorblock`
> 
> Also, can you give a specific example to see if this can be reproduced?

The plugins I have enabled currently:
adblocker, bypass age restrictions, downloader, in-app menu, navigation, playback speed, precise volume, quality changer, shortcuts, sponsorblock, taskbar media control, video toggle
I have disabled sponsorblock and it worked! Thanks a lot
If you meant an example for a song, I have listened to Hate the Way by G-Eazy, it usually skipped to 17 seconds mark and then from 2:48 to 3:19, but it's all good right now :D
