### ISSUE TITLE
Music Video still being rendered when app is in background, causing higher CPU usage 

### ISSUE THREAD

**Issue by rsmyst** [th-ch/youtube-music#760]
For the music videos, when playing it, the entire video is still apparently being rendered in the background even though i'm not looking at it. can something be done about this? i'd like to save some CPU for other tasks thanks
also, I am not able to see the video toggle despite having it enabled

**Comment by Araxeus** [comment]
The video toggle has 3 different modes: "Custom" "Native" and "Disabled"

did you try out both custom and native?

**Comment by rsmyst** [comment]
> The video toggle has 3 different modes: "Custom" "Native" and "Disabled"
> 
> did you try out both custom and native?

The button has magically appeared suddenly in the native form and works as intended. I am not aware why it is working now and not before. 

Also, it would seem that there was a rogue youtube-music process running in the background that was eating up my CPU. I only discovered it after fully exiting the application but still finding a youtube music process open in task manager that was using 25% of my cpu without any music at all. After terminating that, it's back to normal.
