### ISSUE TITLE
Theme not following windows 11

### ISSUE THREAD

**Issue by AuracleTech** [th-ch/youtube-music#762]
![image](https://user-images.githubusercontent.com/40531871/175836880-a9474700-b1dc-41d6-ad44-c28ab94111fa.png)
The title bar is white, every other application looks neat this kind of ruins it :(
Could you fix it :)?

**Comment by Araxeus** [comment]
My advice would be to use the `in-app-menu` plugin, I created it for this very reason

**Comment by AuracleTech** [comment]
Epic thank you!
Most plugins don't have a short description, I have to guess what does what, if the name isn't precise enough it's confusing ;/
