### ISSUE TITLE
No album metadata when downloading a song

### ISSUE THREAD

**Issue by matemato** [th-ch/youtube-music#768]
When downloading an album, the downloaded songs do not have the album name tag. Is this a bug or not added yet?

**Comment by Araxeus** [comment]
can you give an example?

**Comment by matemato** [comment]
> can you give an example?

Sure, here I download Sabaton - The War to End All Wars album. And upon further inspection, songs are missing "number" tag as well.

![sabaton](https://user-images.githubusercontent.com/47794629/177053443-acf9f4c8-b935-43ab-ae66-37b9bacfc2b2.png)
![sabaton_no_data](https://user-images.githubusercontent.com/47794629/177053446-26a5c33a-34d6-4cc9-9b8e-2379de52969a.png)
I edited the file, since I have names of columns in my own language hah. In the second picture you can see missing data for song number - (#) and album title. I don't remember if this is after the update or since I started using this app sorry :/.

Thank you for you help!

**Comment by Araxeus** [comment]
I've opened a PR which will add the album field to downloads (when available)

The song number `#` isn't currently possible to get since youtube doesn't supply it at all
(try finding the song number anywhere in the youtube music ui)
