### ISSUE TITLE
[Feature Request] Extensive and dynamic themes

### ISSUE THREAD

**Issue by kerichdev** [th-ch/youtube-music#770]
Since CSS/HTML injection plugins require rebuilding the whole client, which is highly impractical, it would be really nice having an already existing theme engine, like stylus, added to the client, BUT ideally - [this](https://chrome.google.com/webstore/detail/themesong-for-youtube-mus/bgfiegdbajagebogifobkhambpljbfmk) would be the best one, if there's a way to contact the developer for the source code, or decombile the extension - it would be totally worth it, since it includes dynamic album cover based themes for both light and dark mode.

[Link to the reddit post of the developer](https://www.reddit.com/r/YoutubeMusic/comments/t8x9e1/im_not_a_big_fan_of_the_default_black_theme_so_i/)

[Developer's reddit profile](https://www.reddit.com/user/GraphiteEaterArt/)

**Comment by Araxeus** [comment]
You could maybe ask him if he wants to contribute here?

**Comment by KristofferTroncoso** [comment]
Oh hey guys, it's me the ThemeSong dev (reddit: GraphiteEaterArt).
Thanks for reaching out to me @kerichdev . Glad you like the extension.
I just downloaded this YouTube Music desktop app and am browsing the code now. This is awesome!
My ThemeSong (beta) extension is currently spaghetti and is wildly changing every month so for now I'll look into contributing the core features of ThemeSong so we can get the basic dynamic theme features into this desktop app asap. 
Thanks for putting this on my radar. Great work from all the contributors!

- KT
