### ISSUE TITLE
i can't access the configuration menu

### ISSUE THREAD

**Issue by Yootz** [th-ch/youtube-music#775]
i set it so that it the config is only accessible using the alt button, and then i set something in the config menu so that the title bar looks like this (picture link) but i forgot what it is, and now i can't access the config menu at all. I tried reinstalling it, but it's still using the old configuration i had, is there a way to reset the config without accessing the config menu in the app at all?
https://cdn.discordapp.com/attachments/773064448637141039/993172305842806854/unknown.png

**Comment by Yootz** [comment]
nvm i figured it our

**Comment by Araxeus** [comment]
When you enable `in-app-menu` the hide/show key becomes <kbd>esc</kbd>
also config location can be found in this comment https://github.com/th-ch/youtube-music/issues/410#issuecomment-952060709=

**Comment by Yootz** [comment]
I already figured it out lol
