### ISSUE TITLE
[Feature Request] Interact via Command Line

### ISSUE THREAD

**Issue by ray-pH** [th-ch/youtube-music#776]
Like in CMUS, user can interact with the playback, volume, etc using a command line tool
```
cmus-remote --next
cmus-remote --prev
cmus-remote --pause
cmus-remote --volume +5%
cmus-remote --volume -5%
cmus-remote -C status
```
Is this possible in youtube-music?

**Comment by Araxeus** [comment]
if you are using linux you could use the mpris plugin + some external command line tool like [playerctl](https://github.com/altdesktop/playerctl)

**Comment by ray-pH** [comment]
Oh nice, it worked well except for volume control. Is there any way to make the volume control works as well?

**Comment by Araxeus** [comment]
Sorry, it just wasn't setup for volume control yet, someone needs to add it in https://github.com/th-ch/youtube-music/blob/master/plugins/shortcuts/mpris.js

maybe @foonathan since he has already an open pr targeting mpris

**Comment by foonathan** [comment]
Sure, I'll implement it.

**Comment by briantho** [comment]
any chance we could get documentation for this cli feature? How do you do it? I'm running windows 10 and can't seem to figure this out. I'd ideally like some way to remote control youtube music, via cli or via web remote, or even get commands if possible. My goal is to somehow be able to control youtube music on my computer via my phone.

**Comment by foonathan** [comment]
The API I've implemented is not available on Windows AFAIK; it's a Linux only protocol.

**Comment by briantho** [comment]
ah ok.

**Comment by Araxeus** [comment]
#946 adds support for protocol `youtube://COMMAND`
in cmd:
```
start youtubemusic://pause
```
