### ISSUE TITLE
MPRIS support needs improvements (player name, metadata)

### ISSUE THREAD

**Issue by dionorgua** [th-ch/youtube-music#779]
I've used another Youtube music desktop UI and switched to this one due to feature difference. 

But one of weak points of this project is incomplete MPRIS support. Firstly player doesn't have human-readable name:

```
% playerctl -l                                   
chromium.instance30516
```
It might be just visual issue, but when a few other MPRIS capable players are running (for example video player), it's much more difficult to distinguish between them.  Plus scripting requires extra effort to guess proper player id (30516 is actually pid of one of electron processes). I think it's good idea to rename it to 'youtube-music'

Another issue is that information is incomplete:

```
% playerctl -p chromium.instance30516 metadata
chromium xesam:artist              Jeremy Camp
chromium xesam:title               He Knows
```
That's all. From another player I'm getting followed:
```
% playerctl -p youtube-music-desktop-app metadata
youtube-music-desktop-app mpris:trackid             '/org/node/mediaplayer/youtube_music_desktop_app/track/0'
youtube-music-desktop-app mpris:length              228000000
youtube-music-desktop-app mpris:artUrl              https://lh3.googleusercontent.com/-VPy6bdkYeN9FvQtQPYUSpI9tu-y2CHMaFnw1gnRTEBtWGxcVQ-4GE9x7DCFCT720sVOHZzEydCRd1JoDA=w544-h544-l90-rj
youtube-music-desktop-app xesam:title               Holier Than Thou (Remastered)
youtube-music-desktop-app xesam:album               Metallica (Remastered)
youtube-music-desktop-app xesam:artist              Metallica
``` 

Why it's important? Desktop environments may provide own 'GUI' for MPRIS-compatible players (playback control, popup notifications, seeking, etc). For example this is screenshot of KDE's UI:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/534357/178236801-94401699-0bcf-4d7b-8df8-39aa2e02779a.png">

And now compare it with another player:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/534357/178237011-bd4a5820-8e51-4e21-b815-aa80daafa055.png">

**Comment by Araxeus** [comment]
pretty sure that you are accessing the wrong mpris instance
you are accessing the native one created automatically instead of the one specially created

did you enable the `shortcuts` plugin? you should have a different mpris instance running

**Comment by dionorgua** [comment]
No, I have not enabled shortcuts plugin. 

After enabling and restart I've got different mpris intance that seems to be much much better. 

So it works. Just not so easy to find it
