### ISSUE TITLE
quick controls in windows menus don't work

### ISSUE THREAD

**Issue by TheBossMagnus** [th-ch/youtube-music#781]
![image](https://user-images.githubusercontent.com/92474350/178555503-73a6957f-f9c4-43f1-ba7a-1c921713b217.png)
something wrong with windows api

**Comment by Araxeus** [comment]
is this a new win11 feature?

I'm still using win10 so don't have this 😆

**Comment by Araxeus** [comment]
well I can't really find any documentation as to how it works

its worth noting that the media keys work as intended so its probably a bug on their part

**Comment by THEBOSSMAGNUS** [comment]
I think it's integrated into windows APIs because; also in 3rd party apps, YTM has issues with quick controls.

**Comment by JellyBrick** [comment]
fixed in v2.0.2

https://github.com/th-ch/youtube-music/assets/16558115/fa5a41d6-88c1-4f83-b48b-6c7060a3d5f0
