### ISSUE TITLE
(FEATURE REQUEST) Library Button in the Navigation Bar

### ISSUE THREAD

**Issue by Quakerjackers123** [th-ch/youtube-music#784]
![Screenshot 2022-07-18 173231](https://user-images.githubusercontent.com/34214709/179559318-05d4a5e9-e6d2-45f1-b3c9-2a662d983111.png)

Having A Library Button would help so much with finding my Playlists. I keep pressing the home button a couple of times until it pops up so having a dedicated button would be amazing. Thank you for your time

**Comment by Araxeus** [comment]
uuuuh but there already is?
![image](https://user-images.githubusercontent.com/78568641/179781795-21ac91d1-12a9-4ec3-ba0d-3c68c5d895be.png)

if you visit [music.youtube.com](https://music.youtube.com/) does it show up for you?

**Comment by Quakerjackers123** [comment]
On the website it does but not on the app. All I get is what's above. this has to be a fault on my end so ill look into it.

**Comment by Quakerjackers123** [comment]
Still couldn't figure it out. I've tried using older versions and its the same. any reason why this would be?

**Comment by Araxeus** [comment]
I truly have no idea... its very weird
