### ISSUE TITLE
[Feature request] Config option for css styling

### ISSUE THREAD

**Issue by DrunkenToast** [th-ch/youtube-music#785]
I know you can create a plugin but it would be convenient if you can simply point to a css file(s) in the config file.
This would also make it easier for users would don't want to build it.

**Comment by th-ch** [comment]
Hey @DrunkenToast, thanks for the feedback! The feature should actually be straightforward to implement (other parts of the code already inject CSS), I opened https://github.com/th-ch/youtube-music/pull/800 to allow users to pass custom CSS files:
```json
"options": {
    …
    "cssFiles": [
        "path-to-file-1.css",
        "path-to-file-2.css"
    ]
}
```

**Comment by th-ch** [comment]
I renamed the option to `themes`, and there is now a menu entry to set it! PR is merged, it will ship in the next version - closing the issue, feel free to re-open if needed :)
