### ISSUE TITLE
help for installation 

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [th-ch/youtube-music#791]
Hi, I'm a new zorin os user. How do i install this project on my pc from the asset section. Is there any installation steps available? Please do tell. Thanks.

**Comment by PercyDLR** [comment]
If I remember correctly, Zorin OS is base don buntu, so you could download the [. deb package](https://phoenixnap.com/kb/install-deb-files-ubuntu)on the releases page. With that it'll integate with your package manager and will be updated with all your applications.

If you can't install the .deb file, try the [Appimage](https://www.makeuseof.com/what-is-appimage-and-how-to-run-it-linux/). The only disadvantage of this option is that it won't auto-update, requiring you to download again the next update from releases.
