### ISSUE TITLE
sides of album art is cut off

### ISSUE THREAD

**Issue by Twongus** [th-ch/youtube-music#792]
the sides of the album art is cut off on 1.13 and 1.17. 
1.17:
![image](https://user-images.githubusercontent.com/105463716/183479707-ddbce1bb-6032-45fa-8470-1335c219f257.png)
![image](https://user-images.githubusercontent.com/105463716/183479739-79912b6c-b8bb-4fb2-a09d-d3f0dc9f72eb.png)
1.13:
![image](https://user-images.githubusercontent.com/105463716/183479858-a2f3e1a2-a161-40b8-8eb0-a3aef223e8c7.png)
![image](https://user-images.githubusercontent.com/105463716/183479879-2440a8d3-5359-4c00-b78d-4482663dff40.png)

**Comment by LetrixZ** [comment]
It's a YT Music problem

![image](https://user-images.githubusercontent.com/25001812/184404517-735bac84-fcc8-4bfc-b8e8-2da66e30fb2f.png)

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/f1e31711-692a-49fa-9e71-d22490871c85)

Fixed
