### ISSUE TITLE
Listen Along

### ISSUE THREAD

**Issue by Dushuav2** [th-ch/youtube-music#793]
When I click "Listen Along" it opens youtube music on web.

**Comment by Araxeus** [comment]
Yeah sadly thats how it works, unless the app set itself as handler for music.youtube links
 
(from what I understand this would require the app to register itself as a handler for all https link which is a problem)

https://electronjs.org/docs/latest/api/protocol

https://electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app

**Comment by Dushuav2** [comment]
> Yeah sadly thats how it works, unless the app set itself as handler for music.youtube links
> 
> (from what I understand this would require the app to register itself as a handler for all https link which is a problem)
> 
> https://electronjs.org/docs/latest/api/protocol
> 
> https://electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app

**Comment by Dushuav2** [comment]
> Yeah sadly thats how it works, unless the app set itself as handler for music.youtube links
> 
> (from what I understand this would require the app to register itself as a handler for all https link which is a problem)
> 
> https://electronjs.org/docs/latest/api/protocol
> 
> https://electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app

it looks like the developers are not working on this project anymore so yeah..

**Comment by JellyBrick** [comment]
> > Yeah sadly thats how it works, unless the app set itself as handler for music.youtube links
> > (from what I understand this would require the app to register itself as a handler for all https link which is a problem)
> > [electronjs.org/docs/latest/api/protocol](https://electronjs.org/docs/latest/api/protocol)
> > [electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app](https://electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app)
> 
> it looks like the developers are not working on this project anymore so yeah..

We don't get "paid" for this project.

**Comment by JellyBrick** [comment]
If an API exists to get chapters from YTM, this might be possible.

**Comment by JellyBrick** [comment]
Duplicated of #992
