### ISSUE TITLE
no clear way to connect discord? (windows)

### ISSUE THREAD

**Issue by ranenvious** [th-ch/youtube-music#794]
I have the discord plugin enabled but the section that says "Connected" is greyed out and doesn't have a checkmark next to it. I haven't been able to find any connection procedure I need to go through, it just isn't connected. I might be missing something but I've spent the last 30 minutes trying to figure it out and haven't found anything, so I feel like if I am it should probably be better conveyed to the end user. For that matter, am I even missing something, or is it supposed to be automatic and just not working for some reason?

**Comment by evan1026** [comment]
I know this is bumping an old-ish thread but just in case anyone else finds themselves here, I was having an issue like this where it didn't appear to be connecting. Simply restarting the YouTube Music App fixed the issue

**Comment by Midnightmadwalk-coder** [comment]
well for  me it's saying connection failed. could not connect.
