### ISSUE TITLE
Next song in same minute with last song

### ISSUE THREAD

**Issue by Ayysz** [th-ch/youtube-music#795]
Im use youtube-music v1.17.0.deb in ubuntu 22.04 LTS, when im play song and i want click next button the minute position is same with song before (illustrasion is when i play song bruno mars - 24K magic in minute 2:05 and i click next button to next song the song start in minute 2:05 and sometimes skip the next song)
can you help me to fix this?
pluggin i'm turn on just 
- adblocker
- bypass-age-restrictions
- downloader
- notifitcations
- picture in  picture 
- precise volume
- shortcut
- video toggle

Thank you for all your hard work on this project!
sorry for my bad english  `-`

**Comment by Araxeus** [comment]
That's weird... i cant replicate this

Could you check if this also happen in the browser? Just open music.youtube.com

If not then could you try disabling plugins and see if it helps?

**Comment by Ayysz** [comment]
i recently try in music.yotube.com and i've same issue
do you have any solutions for me?
if not it's okay i'm still can stream music

**Comment by Ayysz** [comment]
i've found the issue it's from my google account,
i'm test with other google account and everything works fine :)
thanks issue closed.
