### ISSUE TITLE
App becomes very laggy after more than 30 mins of continous playing?

### ISSUE THREAD

**Issue by Shnxxx** [th-ch/youtube-music#797]
I always listen to music on this app, and I usually play it through my speakers so I can hear it wherever I go in our house. After about 30 minutes of continuous play, it takes too long to respond and is very laggy.

**Comment by kerichdev** [comment]
Can +1 this one, although it may be related to a memory leak issue in Youtube Music itself (has been once discussed on the subreddit, confirmed by various users)

**Comment by sh0inx** [comment]
+1, what thread is that on? I'd like to take a look and see, as I switched from a different client to this one because of the same issue (this one is better, if you're wondering)

**Comment by MulverineX** [comment]
@sh0inx well if its an issue with the web app itself; not this electron wrapper/mod (which is probably the case according to kerich), then there's not much that can really be done without complex patching of the JS bundle or a full web replacement. Currently, this mod works with raw DOM manipulation and JQuery (😬), so doing modifications like this isn't really feasible.
