### ISSUE TITLE
Sign-in doesn't work

### ISSUE THREAD

**Issue by yarnweaver** [th-ch/youtube-music#8]
Video playback works but sign-in currently doesn't work for me in version 1.1.5. It doesn't work for me in version 1.1.4 either, but it previously worked for me in version 1.1.4. GUI message says "Cannot load YouTube Music... internet disconnected?"

I also can't find anything in my Google account security settings to suggest it's blocked a sign-in from an insecure device or application.

Don't know if it's related but also ad-blocker plugin doesn't block ads.

**Comment by yarnweaver** [comment]
alternative application MaverickMartyn/youtube-music-desktop does not have this issue, sign-in works correctly on this one, which makes me think the problem is with the th-ch/youtube-music app rather than Youtube's authentication mechanisms.

**Comment by th-ch** [comment]
Hey @yarnweaver, thanks for reporting the issue! Sign in should be fixed now, can you try again with the latest version (v1.1.6)?

**Comment by yarnweaver** [comment]
Yes, that's great, works for me now.

**Comment by Bitsy-Chuck** [comment]
Sign-in not working in v1.5.0 
It does nothing when I click on it

**Comment by Bitsy-Chuck** [comment]
Ok so It works when I disabled the ad-block plugin. I logged it, then enabled it back and then restarted and everything's find.

**Comment by th-ch** [comment]
Hey @Bitsy-Chuck! Thanks for flagging the issue, glad you could get it working! -> I'm re-opening the issue to give it a closer look when I have time (it might be fixable without needing to disable the ad-blocker plugin).

**Comment by th-ch** [comment]
Hey @Bitsy-Chuck, login seems ok even with the adblocker now, do you still have the issue with the [latest version 1.9.0](https://github.com/th-ch/youtube-music/releases/tag/v1.9.0)?

**Comment by Petemir** [comment]
fyi, I got this problem also on 1.18. Disabling the adblocker worked :).
