### ISSUE TITLE
Cant start the app

### ISSUE THREAD

**Issue by knalltuete69** [th-ch/youtube-music#80]
Hy I followed your instructions and I get 
yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

**Comment by th-ch** [comment]
Hey @knalltuete69, thanks for the feedback! This looks like a yarn error - from [this comment](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365), it looks like you may have the wrong yarn package from `cmdtest`?

**Comment by knalltuete69** [comment]
Thanks now it works.
