### ISSUE TITLE
menu.js submenu radio options from navigator.mediaDevices.enumerateDevices

### ISSUE THREAD

**Issue by Azureit** [th-ch/youtube-music#805]
Is it possible to load submenu radio options from navigator.mediaDevices.enumerateDevices at menu.js?

(newbie here, limited knowledge of javascript)

**Comment by Araxeus** [comment]
should be pretty easy to do after those:
1. https://developer.chrome.com/blog/audiocontext-setsinkid/
2.  https://github.com/th-ch/youtube-music/pull/951

Anyone want to give it a shot?
