### ISSUE TITLE
Tuna OBS status 

### ISSUE THREAD

**Issue by awan-gh** [th-ch/youtube-music#811]
https://github.com/th-ch/youtube-music/blob/a0543d15a6113e581c1443bb4dffa42f67806e89/plugins/tuna-obs/back.js#L48

I've been using Youtube Music since a long time but recently i'm trying to get the tuna plugin to work properly for my OBS. The only problem that i'm having is that whenever i stop / pause the music, the status on the webserver doesn't change. It's just stuck on playing, anybody facing the same issue?

**Comment by mesmerx** [comment]
the problem is the ~pause~ dont have a event for that, my sugestion is to set a timmer and look for that for now

**Comment by JellyBrick** [comment]
Fixed at #1235
