### ISSUE TITLE
autoplay not working

### ISSUE THREAD

**Issue by KawaiiTemDev** [th-ch/youtube-music#827]
https://user-images.githubusercontent.com/25987110/190024792-d9ae15a6-14d5-46ec-ad10-ac5385e4bcb0.mp4

disable-autoplay is not enabled

**Comment by TemDevz** [comment]
epic embed fail, eres the same vid but actually embedded


https://user-images.githubusercontent.com/25987110/190024792-d9ae15a6-14d5-46ec-ad10-ac5385e4bcb0.mp4

**Comment by Proulxs** [comment]
Same issue here, I tried updating to 1.18 from 1.17 and the issue stayed. It was working on 1.17 and stopped working recently on its own so I assume something changed Youtube's side.

**Comment by TemDevz** [comment]
> Same issue here, I tried updating to 1.18 from 1.17 and the issue stayed. It was working on 1.17 and stopped working recently on its own so I assume something changed Youtube's side.

regressing to 1.17 fixed the issue for me so until this issue gets closed i'll be using 1.17

**Comment by th-ch** [comment]
Hey folks, I can't seem to reproduce, is the bug still there?

**Comment by TemDevz** [comment]
appears to be fixed!

**Comment by Proulxs** [comment]
Working here too.

**Comment by KawaiiTemDev** [comment]
Nevermind, bump. Broken yet again?
