### ISSUE TITLE
AdBlock won't work anymore

### ISSUE THREAD

**Issue by triplecan** [th-ch/youtube-music#83]
I get ads on almost every song I play, I uninstalled it and cleared every bit remaining. Then I installed the latest version again. But the ads are still playing. Restarting the PC doesn't help either. Here is an image of the config. Am I missing something here?

EDIT: I just found out that when I'm not logged in with my Google account, the ads are blocked. I will update again if something changes.

Best regards
![image](https://user-images.githubusercontent.com/15697875/101246411-7c0c0180-3713-11eb-9077-c2c1efbe25da.png)
Here is an image, with the ad
![image](https://user-images.githubusercontent.com/15697875/101246565-75ca5500-3714-11eb-9bbd-9cabafba23b5.png)

**Comment by martinjoeledwards** [comment]
I'm having the same problem. The ad-blocker worked fine until this morning. It does work when I'm not logged in though.

**Comment by th-ch** [comment]
Hey @triplecan & @martinjoeledwards, thanks for the issue! It _might_ be the same issue as https://github.com/th-ch/youtube-music/issues/55 - from the screenshot, config looks ok - out of curiosity, what OS are you using? I don't have the issue (logged in or not) on MacOS so it could be linked to the OS and/or the country you are in.
One idea could be that the default filters are not enough - I will try to reproduce on my end, if you want to experiment on your side, you can:
- toggle dev tools in options to see blocked requests and identify the domains the ads come from
- add other filter lists in the adblocker config by setting `cache` to false and adding adblocking lists to `additionalBlockLists` (e.g. https://easylist.to/easylist/easylist.txt)

**Comment by martinjoeledwards** [comment]
I'm using Windows 10. USA.
Here's a screenshot of the dev tools log, in case that's helpful. Also the text in my options right now.

{
	"window-size": {
		"width": 1432,
		"height": 927
	},
	"url": "https://music.youtube.com/watch?v=eqV8vxI0u-Q&list=OLAK5uy_n6jG9pX-JJy8T3tPyA4ph7ZWMj2CGEYeg",
	"plugins": {
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"downloader": {
			"enabled": true,
			"ffmpegArgs": []
		},
		"shortcuts": {
			"enabled": true
		},
		"navigation": {
			"enabled": true
		},
		"auto-confirm-when-paused": {
			"enabled": true
		},
		"hide-video-player": {
			"enabled": true
		},
		"no-google-login": {
			"enabled": false
		}
	},
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": false,
		"startAtLogin": false,
		"restartOnConfigChanges": true
	},
	"window-position": {
		"x": -8,
		"y": -8
	},
	"window-maximized": true,
	"__internal__": {
		"migrations": {
			"version": "1.7.1"
		}
	}
}
![ytm_1](https://user-images.githubusercontent.com/47152230/101267871-df4d6200-371a-11eb-9bb5-3adc113500b2.jpg)

**Comment by triplecan** [comment]
> Hey @triplecan & @martinjoeledwards, thanks for the issue! It _might_ be the same issue as #55 - from the screenshot, config looks ok - out of curiosity, what OS are you using? I don't have the issue (logged in or not) on MacOS so it could be linked to the OS and/or the country you are in.

So as I read the other thread, I think it is exactly the same issue as #55. Today I can't even reproduce the issue any more. No settings changed. 

I will keep updating if something changes.

**Comment by ricardo404** [comment]
I am also having problems with Adblocker in my Brazil region. Early on Saturday morning, when I opened the app, an ad started popping up for every song played. I tried to follow the steps of adding Blocklists, but I had the same problem that the previous friend presented. When placing the cache in "false" the application opened but with a javascript error related to the modified JSON.

**Comment by th-ch** [comment]
From [this AdBlock page](https://help.getadblock.com/support/solutions/articles/6000109702-i-m-seeing-ads-in-youtube-videos) and [this reddit thread](https://www.reddit.com/r/uBlockOrigin/comments/fdkcmp/youtube_ads_not_being_filtered/fji34g4/), it seems it's a known issue that appears randomly (still unable to reproduce on my end even on Windows) - you can try the following:
- being logged out seems to be enough if that's ok for you
- otherwise, as mentioned in https://github.com/th-ch/youtube-music/issues/83#issuecomment-739416860 you can try to set `cache` to false and add some known lists like `https://easylist.to/easylist/easylist.txt` to `additionalBlockLists` to see if it helps (not sure it will, though)

-----

> the application opened but with a javascript error

@ricardo404 thanks for the feedback! can you share your edited JSON config? If it's a simple JSON error, it should be fixable!

**Comment by ricardo404** [comment]
{
	"window-size": {
		"width": 1100,
		"height": 550
	},
	"url": "https://music.youtube.com/watch?v=r5-qPZdT9pA&list=OLAK5uy_mhbIHrfp5Tw3f-qfaH4d-zfsXAnulfqTE",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false
	},
	"plugins": {
		"navigation": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": false,
			"additionalBlockLists": "https://easylist.to/easylist/easylist.txt"
		},
		"downloader": {
			"enabled": false,
			"ffmpegArgs": []
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.7.1"
		}
	},
	"window-position": {
		"x": 410,
		"y": 250
	}
}

**Comment by th-ch** [comment]
@ricardo404 Blocklist must be an array so config should look like:
```json
…
"adblocker": {
    "enabled": true,
    "cache": false,
    "additionalBlockLists": [
        "https://easylist.to/easylist/easylist.txt"
    ]
},
…
```

With that, it should work fine! 🤞

**Comment by ricardo404** [comment]
{
	"window-size": {
		"width": 1100,
		"height": 550
	},
	"url": "https://music.youtube.com/watch?v=Wz3PD8c4eSo&list=OLAK5uy_mhbIHrfp5Tw3f-qfaH4d-zfsXAnulfqTE",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false
	},
	"plugins": {
		"navigation": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": true
		},
		"adblocker": {
			"enabled": true,
			"cache": false,
			"additionalBlockLists": [
				"https://easylist.to/easylist/easylist.txt"
			]
		},
		"downloader": {
			"enabled": false,
			"ffmpegArgs": []
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.7.1"
		}
	},
	"window-position": {
		"x": 410,
		"y": 250
	}
}

I put it that way but the error persists. The error is of the type: ENOENT: There is no such file or directory. And it keeps showing directories that link to "adblock engine.bin" and app.asar

**Comment by th-ch** [comment]
Definitely a bug, good catch, thanks for the report! [Pre-release 1.7.2](https://github.com/th-ch/youtube-music/releases/tag/v1.7.2) should fix it, allowing to test additional blocklists like "https://easylist.to/easylist/easyprivacy.txt", feel free to give it a try!

**Comment by ricardo404** [comment]
It is now possible to add the easy lists without presenting the Javascript problem. Meanwhile, boring ads continue to circumvent the list.

**Comment by triplecan** [comment]
Just a quick update: Now it's even playing ads when not logged in:

![image](https://user-images.githubusercontent.com/15697875/101330339-c48e0100-3872-11eb-8a16-48c701280c69.png)

I have added easylist to the config and disabled cache.

**Comment by martinjoeledwards** [comment]
Same here.

**Comment by th-ch** [comment]
@triplecan I played a bit with adblock settings, it seems adding easylist to additional blocklists does not play well with default settings and might be responsible for the ads when being logged out - you can try removing easylist from settings to see if it improves things for you!

@martinjoeledwards thanks for the feedback! It's unfortunate that you are affected too - this issue is being slowed down by the inability to reproduce on my side but I will keep this issue open to track progress on this. Feel free to post updates if you think it can help!

**Comment by BLANK-TH** [comment]
Still getting ads, currently on version 1.7.2., adblocker is on, I'm signed into my google account. Tried it with both easylist in and not in additional blocklists.

**Comment by krthr** [comment]
I'm experiencing this issue too. But I'm logged in.

**Comment by C4illin** [comment]
Doesn't work here either. With ublock origin in the browser it works perfectly.

**Comment by th-ch** [comment]
@C4illin thanks for the feedback! Could you share your ublock list of filters? They should be supported by the integrated adblock so we might have a potential solution here! (and if the default list does not play well with it, I will add an option to disable it and only use user-provided blocklists)

**Comment by C4illin** [comment]
[**@th-ch**](https://github.com/th-ch) commented on [8 dec. 2020 20:59 CET](https://github.com/th-ch/youtube-music/issues/83#issuecomment-740942828 "2020-12-08T19:59:57Z - Replied by Github Reply Comments"):
> [@C4illin](https://github.com/C4illin) thanks for the feedback! Could you share your ublock list of filters? They should be supported by the integrated adblock so we might have a potential solution here! (and if the default list does not play well with it, I will add an option to disable it and only use user-provided blocklists)  
> (You can export ublock settings as JSON, the list of filters will be in `externalLists`)

Does your adblocker supper adblockplus filters? These seems to be the ones that have any impact:
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt

**Comment by th-ch** [comment]
It _should_ be [supported](https://github.com/cliqz-oss/adblocker/wiki/Compatibility-Matrix) - [Pre-release 1.7.3](https://github.com/th-ch/youtube-music/releases/tag/v1.7.3) allows to disable default lists so you can try these settings:
```json
"adblocker": {
    "enabled": true,
    "cache": false,
    "disableDefaultLists": true,
    "additionalBlockLists": [
        "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt",
        "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt"
    ]
},
```

And other combinations with your different blocklists (use `raw.githubusercontent.com` URLs instead of `github.com` ones) to check if it works!

**Comment by C4illin** [comment]
Thanks, It seems to work now!
This worked the most consistently with the fewest extra block-lists enabled, but it was quite a pain to test so it could definitely be improved.
```
"adblocker": {
	"enabled": true,
	"cache": false,
	"disableDefaultLists": true,
	"additionalBlockLists": [
		"https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt"
	]
},
```

**Comment by triplecan** [comment]
},
		"adblocker": {
			"enabled": true,
			"cache": false,
			"disableDefaultLists": true,
			"additionalBlockLists": [
				"https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt",
				"https://raw.githubusercontent.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt",
				"https://easylist.to/easylist/easylist.txt",
				"https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt",
				"https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt",
				"https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt"
			]
		},

I tried, but not a single ad gets blocked for me.

**Comment by th-ch** [comment]
Just to give a heads-up, this issue is actively being tracked and I am now able to reproduce, will work on it!

**Comment by benji009** [comment]
i am getting ads today as well. I am on the latest version 1.7.3.

**Comment by hackel** [comment]
No luck for me either.  `youtube.com/get_video_info` (for a valid song video_id) returns all of the ad video information.  Possibly this request could be intercepted and the ad information stripped from it.  I don't think a standard blocklist will be able to accomplish this.

**Comment by th-ch** [comment]
Hey everyone, [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly!

**Comment by martinjoeledwards** [comment]
Seems to work for me! Thanks a bunch.

**Comment by krthr** [comment]
> Hey everyone, [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly! If you changed adblock settings, you can revert to the default:
> 
> ```json
> "adblocker": {
>     "enabled": true,
>     "cache": true,
>     "disableDefaultLists": false,
>     "additionalBlockLists": []
> },
> ```

It's working now! Thank you!

**Comment by triplecan** [comment]
> Hey everyone, [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly! If you changed adblock settings, you can revert to the default:
> 
> ```json
> "adblocker": {
>     "enabled": true,
>     "cache": true,
>     "disableDefaultLists": false,
>     "additionalBlockLists": []
> },
> ```

Seems to work, Thanks!!
