### ISSUE TITLE
App not working M1 MacBook 

### ISSUE THREAD

**Issue by rimonhanna** [th-ch/youtube-music#830]
I tried downloading the latest version and whenever I run it I get the error “YouTube Music” is damaged and can’t be opened. You should move it to the Bin.

**Comment by th-ch** [comment]
Hey @rimonhanna, it's indeed a known issue, have you tried https://github.com/th-ch/youtube-music#macos ?

**Comment by rimonhanna** [comment]
yeah that workaround worked, thanks! Are you working on a more permanent solution?

**Comment by th-ch** [comment]
Signing could work but requires paying an annual fee afaik (and I don't have the budget for it), so no better solution so far 😬  Closing as not sure there is anything actionable for now
