### ISSUE TITLE
[Feature Request] Like all songs in an Album

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#831]
I think the title says it all. I think it would be great to have a "like all songs" option for an album, instead of the "add to library" option which is currently there. I like to shuffle my "Liked songs" every once in a while, so I think this will be better than to play the albums I like one-by-one.

**Comment by MiepHD** [comment]
`for (like of document.querySelectorAll("#button-shape-like")) {
    if (like.getAttribute("aria-pressed") === "false") {
        like.children[0].click();
    }
}
`
Add a button that runs this

**Comment by Zo-Bro-23** [comment]
> ```
> for (like of document.querySelectorAll("#button-shape-like")) { //Gets all buttons
>     if (like.getAttribute("aria-pressed") === "false") { //Checks if it's pressed
>         like.children[0].click(); //Clicks the button
>     }
> }
> ```
> 
> Add a button that runs this

Thanks. I'll try it out when I have some free time and get back to you!
