### ISSUE TITLE
win10 notification 

### ISSUE THREAD

**Issue by Cope9560** [th-ch/youtube-music#832]
![img](https://i0.hdslb.com/bfs/article/0089bd84024a3c824038eb7ec863758f55306fa2.png@870w_489h_progressive.webp)

Hi, after I use your software in win10, pressing the media key on the keyboard to switch between previous and next song will show an ugly notification in the top left corner, I found out by searching that it is a setting in chrome, could you please add the option to turn off this notification in the next update?
The solution I found is to change the setting of chrome://flags/#hardware-media-key-handling to disabled

**Comment by EinTheMidle** [comment]
It says fix available, but I don't know to to use it to remove the notification
