### ISSUE TITLE
discord connection on fedora not working

### ISSUE THREAD

**Issue by villagerrrrrrrrr** [th-ch/youtube-music#836]
heya, i am using fedora 37 (beta)
discord activity does not work, when reconnecting it just shows this
![image](https://user-images.githubusercontent.com/74655777/190896534-50a302c3-c883-4e99-9eb9-a7ed25332570.png)

i'm using flatpak's discord, that can be an issue..?

**Comment by TheArcaneBrony** [comment]
Having a similar issue but not related to snaps.
![image](https://user-images.githubusercontent.com/13570458/207901753-cd12d2f7-65b1-47bd-b5b9-da7e85df8d4e.png)
Seems the application id tied to the app got terminated

**Comment by Zo-Bro-23** [comment]
> Having a similar issue but not related to snaps. ![image](https://user-images.githubusercontent.com/13570458/207901753-cd12d2f7-65b1-47bd-b5b9-da7e85df8d4e.png) Seems the application id tied to the app got terminated

It's a known issue. Either do a custom build or install from [here](https://github.com/Zo-Bro-23/youtube-music/releases) (pre-built by me).

**Comment by BigicecreamTaken** [comment]
> > Having a similar issue but not related to snaps. ![image](https://user-images.githubusercontent.com/13570458/207901753-cd12d2f7-65b1-47bd-b5b9-da7e85df8d4e.png) Seems the application id tied to the app got terminated
> 
> It's a known issue. Either do a custom build or install from [here](https://github.com/Zo-Bro-23/youtube-music/releases) (pre-built by me).

Hi if you have a fix maybe open PR for it?
or you already did that?

**Comment by Araxeus** [comment]
might be worth looking into https://www.npmjs.com/package/@xhayper/discord-rpc if snap/flatpack doesn't work
