### ISSUE TITLE
Adblock Plugin not working on Windows 10

### ISSUE THREAD

**Issue by BaconCatBug** [th-ch/youtube-music#837]
![image](https://user-images.githubusercontent.com/4897163/190992641-2b6b655e-a78a-480a-a5e6-e0d4dee5c32a.png)
![image](https://user-images.githubusercontent.com/4897163/190992686-36a9adf5-17c1-4e58-9552-3276ce1d81ce.png)

**Comment by TheBossMagnus** [comment]
I think I have the same issue. It's somehow related to the "resume last song when app start" being enabled. 
It should be fixed with #583 , but I still have this issue

**Comment by Araxeus** [comment]
I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker

Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me)

**Comment by TheBossMagnus** [comment]
> I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker
> 
> Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me)
> 
> 
> 

Could you precompile and release it?

**Comment by Zo-Bro-23** [comment]
> > I have an experimental faster adblocker here: https://github.com/Araxeus/youtube-music/tree/experimental-faster-adblocker
> > Looking for people to test it (I don't get any ads with it enabled, but that might be just luck since they are pretty rare for me)
> 
> Could you compile and release it?

Release available [here](https://github.com/Zo-Bro-23/youtube-music/releases/tag/v1.19.0).

**Comment by Araxeus** [comment]
Thank you @Zo-Bro-23 !

I see that you committed a special manual release workflow, neat. I might copy it 😁

**Comment by Zo-Bro-23** [comment]
> another songs ware skipping 10-30s sections every 5-10 second

That might be because of the `skip-silences` plugin. Is that enabled?

**Comment by Araxeus** [comment]
@Zo-Bro-23 Your release has 37 downloads but we have almost no feedback except the one comment by Magnus

can you edit the description at https://github.com/Zo-Bro-23/youtube-music/releases/tag/v1.19.0 so that it instructs users to report how it works for them at https://github.com/th-ch/youtube-music/pull/1040 (or something like that)

**Comment by Zo-Bro-23** [comment]
Done.
