### ISSUE TITLE
Auto-play not working when a song is searched.

### ISSUE THREAD

**Issue by Obscuredzh** [th-ch/youtube-music#838]
First of all, i really appreciate your work on this!!! 
Basically, the autoplay only work when i play song in the recommend section but not in the searched song section.
Thanks with gratitude!!!

**Comment by KawaiiTemDev** [comment]
still occurs, bump!

**Comment by nitsuzxz** [comment]
still occurs, bump!

**Comment by JellyBrick** [comment]
This appears to be a YouTube issue.

**Comment by KawaiiTemDev** [comment]
it appeared to be fixed but downloading the latest build again broke it. unfortunate :(
![image](https://github.com/th-ch/youtube-music/assets/25987110/9c38a479-2b98-4241-ae72-9527ae464e1b)

**Comment by KawaiiTemDev** [comment]
fixed by cleaning out AppData\Roaming\YouTube Music
