### ISSUE TITLE
Doesn't download some music

### ISSUE THREAD

**Issue by Itai-Nelken** [th-ch/youtube-music#84]
when I want to download music without video I get this error:
<img width="277" alt="Screen Shot 2020-12-06 at 10 53 04 PM" src="https://user-images.githubusercontent.com/70802936/101292082-ff158080-3815-11eb-8d81-8a87c4a08918.png">

If I understand correctly youtube-dl is used to download, and in that case it is understandable why it doesn't work (because I think youtube-dl can only download music from youtube not youtube music, and most video-music on youtube music is also on youtube.
If that's the case, than this issue is for people who don't know that.

Anyway thanks for this great app.

**Comment by th-ch** [comment]
Hey @Itai-Nelken, thanks for the issue! It seems to be a playlist URL - downloader only supports video URLs at the moment, not playlists, hence the error.

The feature to download playlists should be easy to implement (e.g. with https://github.com/TimeForANinja/node-ytpl that works well with https://github.com/fent/node-ytdl-core currently being used) - keeping this issue opened to track progress on this

**Comment by Itai-Nelken** [comment]
I think I found what was causing the error (I wasn't trying to download a playlist), for some reason the Downloader tried to download the playlist the song was in, but I tried again and it worked.

**Comment by Itai-Nelken** [comment]
@th-ch I found something: when trying to download a song in your library for example it gives a error because its trying to download the _whole_ library:
<img width="1101" alt="Screen Shot 2021-03-25 at 7 26 09 PM" src="https://user-images.githubusercontent.com/70802936/112517005-81fc2000-8da0-11eb-9275-59b528e5dcea.png">

the downloader only works when for example searching a song, playing it, and then using then using the players 3dot menu to download.

**Comment by Araxeus** [comment]
@Itai-Nelken This should hopefully be fixed in the next versio, following #221

**Comment by Itai-Nelken** [comment]
Great!
