### ISSUE TITLE
Cannot install ver 1.18 on MacOS Ventura

### ISSUE THREAD

**Issue by rhoconlinux** [th-ch/youtube-music#841]
Hello there, just trying to install the last update, and Ventura doesn´t allows me to move the app into the apps folder. 
Here is snapshot: 
[link](https://www.dropbox.com/s/9bxofh52tpzau58/Captura%20de%20pantalla%202022-09-22%20a%20la%28s%29%2012.22.44.png?dl=0)
Thanks for the help!
Cheers,

PS. Version 1.17 works just fine.

**Comment by notAxion** [comment]
I am on MacOS 10.15.7
the same thing is showing to me on version 1.18
but mine is getting copied but not running 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/67577744/192130668-10bdeede-492c-45c6-8756-92de560c481c.png">
Its showing this ^

but the thing is i have used 1.17 and it worked just fine but for some reason that version isn't running as well, Its showing the same error

**Comment by notAxion** [comment]
@rhoconlinux hey could you check which type of dmg you are trying to install ?
arm64 or the normal(which i think is the intel one) one ?

**Comment by rhoconlinux** [comment]
@notAxion is the normal one, intel.
