### ISSUE TITLE
Picture-in-picture hotkey isn't ignored when type in search bar

### ISSUE THREAD

**Issue by Proulxs** [th-ch/youtube-music#843]
The default hotkey for Picture-in-picture plugin is P. If you try to do a search and type P it will activate picture-in-picture... I feel like a text box where you are expected to type alot of various things should be ignored from the hotkey lookup.

**Comment by MarzAttax** [comment]
this issue is also bugging me, I'm just tryna search for songs and it ends up popping out the window, hope this catches the attention of the devs

**Comment by LetrixZ** [comment]
You can always disable the hotkey on `config.json` file
