### ISSUE TITLE
Problems with the AppImage build

### ISSUE THREAD

**Issue by ketronix-dev** [th-ch/youtube-music#844]
I downloaded the official build of AppImage, and tried to integrate it into the system with my own console utility appimage installer, but got an error, after investigating the reasons I found that you have an empty desktop file. I am attaching a screenshot.

![Screenshot from 2022-09-24 09-06-49](https://user-images.githubusercontent.com/111521698/192082948-e7df9021-0bef-4071-ace3-9295bbc78d0c.png)

**Comment by Higor123123** [comment]
Hi, @ketronixdev!

If you have a debian based OS use the specific one in .deb
Download: https://github.com/th-ch/youtube-music/releases/download/v1.18.0/youtube-music_1.18.0_amd64.deb
