### ISSUE TITLE
Startup the app minimized

### ISSUE THREAD

**Issue by jhossettstalinn** [th-ch/youtube-music#847]
Please, add this feature

**Comment by Willy-JL** [comment]
I went and forked this awesome project to add this myself, but realized while implementing it that it already exists!

`Menu > Options > Tray > Enabled + app hidden`

Could be named a bit better, it is quite ambiguous, but still it is already there!

**Comment by jhossettstalinn** [comment]
It doesn't work for me

**Comment by Willy-JL** [comment]
> It doesn't work for me. I'm on Ubuntu 22.04 with Gnome 42.4

By minimized we’re talking about being in the system tray, NOT being minimized to the taskbar, just so we’re talking on the same page. Do you get the windows showing on screen anyway?

**Comment by jhossettstalinn** [comment]
> > It doesn't work for me. I'm on Ubuntu 22.04 with Gnome 42.4
> 
> By minimized we’re talking about being in the system tray, NOT being minimized to the taskbar, just so we’re talking on the same page. Do you get the windows showing on screen anyway?

Yeah... in the system tray. Yes, I get the window showing at startup every time I restart my system.
