### ISSUE TITLE
snoretoast-x86.exe detected as a trojan by McAfee Endpoint Security

### ISSUE THREAD

**Issue by chernobog** [th-ch/youtube-music#848]
Whether or not snoretoast-x86.exe is malware, this creates a poor user experience, and compromises trust with this repo. 

McAfee ENS detects the following file as a trojan (RDN/Generic.dx):
%userprofile%\AppData\Local\Temp\nsoBF47.tmp\7z-out\resources\app.asar.unpacked\node_modules\note-notifier\vendor\snore\snoretoast-x86.exe

**Comment by ve3** [comment]
YouTube-Music-1.18.0.exe Also detected in Virus total website scanned by Trend micro ( https://www.virustotal.com/gui/file/f64aa95b6778a61cf9e50f6f4b8d28fc64fe08980c4ded44b48f8a0420e6622f?nocache=1 )
**TROJ_GEN.R002H06IR22**

**Comment by th-ch** [comment]
Hey folks, that seems weird indeed 🤔 Snoretoast is [compiled from source](https://github.com/th-ch/youtube-music/blob/be3a2880eb63394c862abf617ac5fca52f4bf763/.github/workflows/build.yml#L56-L81) in the repo (also applying a missing patch along the way) and nothing was changed recently in that area, not sure why some antiviruses suddenly detect it (false positive?) - if you prefer, you can compile it yourself by setting up the repo (cloning and install dependencies with yarn) then building snoretoast (see the linked CI file for instructions - it consists in cloning the repo, applying the patch then compiling it), then building the app (`yarn build:win`) - hope that helps!

**Comment by chernobog** [comment]
Reinstalled today, and McAfee did not protest.

**Comment by Araxeus** [comment]
New snoretoast version was officialy released 

https://download.kde.org/stable/snoretoast/0.9.0/

[release notes](https://invent.kde.org/libraries/snoretoast/-/tags/v0.9.0)

waiting for @mikaelbr to update node-notifier (I even emailed him 😅)

> note: https://github.com/th-ch/youtube-music/pull/600 will have to be reverted,
