### ISSUE TITLE
album art of now playing song is bigger than actual size and sinking to bottom of screen

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [th-ch/youtube-music#861]
my issue is that the album art of a song ususally is digging deeper to bottom of screen. differences have been provided below for comparision of stock yt music and th-ch yt music.
![Screenshot from 2022-10-16 23-44-36](https://user-images.githubusercontent.com/78001660/196051570-84f69f1f-97ba-4c85-a849-5ba663b6f8c3.png)
![Screenshot from 2022-10-16 23-44-26](https://user-images.githubusercontent.com/78001660/196051575-3bd0ec4b-5951-4824-bdad-f03eb7ff9dda.png)

**Comment by paulo-roger** [comment]
This might be solvable with some CSS
