### ISSUE TITLE
[Bug] Infinite loading

### ISSUE THREAD

**Issue by yLordMagnus** [th-ch/youtube-music#864]
When I start a playlist it always plays the first song normally but after that it has a random chance of getting stuck loading forever a song, like the gif below (sometimes it plays only 1 song, and sometimes it only get's stuck after playing 10+ songs, it seems pretty random):

![17_19-39-25_XOzo5](https://user-images.githubusercontent.com/20267487/196297054-c7583e45-6405-4c52-9ab2-ac06f1a1e0fd.gif)

I already have uninstalled the app and installed it again but the problem persists, does anyone know why this is happening?
PS: I have been using the app for a long time, but only now it started doing this.

**Comment by Araxeus** [comment]
do you maybe have the plugin `disable-autoplay` enabled?

see #1058
