### ISSUE TITLE
"skip-silences" plugin skips songs that are manually muted

### ISSUE THREAD

**Issue by valkyrienyanko** [th-ch/youtube-music#871]
Steps to Reproduce
1. Enable the "skip-silences" plugin
2. Play a song
3. Mute it

**Comment by th-ch** [comment]
Hey @valkyrienyanko, good catch, https://github.com/th-ch/youtube-music/commit/335d515e22e4fe721ad73b919871c5656e7bd4c5 should fix it! Closing the issue, feel free to re-open if needed!
