### ISSUE TITLE
Discord activity timeout does not trigger on pause

### ISSUE THREAD

**Issue by Nixxen** [th-ch/youtube-music#878]
**Issue:** 
Discord activity is not cleared when songs are just paused

**How to reproduce:**
Enable discord integration both in YTM and discord.
Enable "Clear activity after timeout" in YTM discord plugin.
Set the "Set activity timeout" variable in YTM discord plugin to 10.
Start playing music and observe the discord status updating.
Pause the music. Wait 10+ seconds. The status is still active, but with the time left set to "00:00" (refer to screenshot)
![image](https://user-images.githubusercontent.com/14964915/201493901-403cbd5a-7b97-4db4-b82e-4b17ab0b7689.png)

**Expected result:**
When paused, the activity timeout should start counting, then clear the activity if paused for more than the activity timeout variable.

**Comment by Zo-Bro-23** [comment]
Which version are you using? Discord only works in custom builds right now, since an issue was fixed only in https://github.com/th-ch/youtube-music/commit/ee01ae1c00c73b0dfd5db8c6e7ff7352783987da. Try building the application using ```yarn build``` and report if the issue persists.

**Comment by JellyBrick** [comment]
Fixed at #1235
