### ISSUE TITLE
Discord RPC not connecting

### ISSUE THREAD

**Issue by zoeeechu** [th-ch/youtube-music#879]
Gives error message Connection closed!

things i have tried :
disabling and renabling it 
reconnecting it

**Comment by zoeeechu** [comment]
Yeah I tried running as Admin too ;-;

**Comment by YuiKyojin** [comment]
is everyone experiencing still this too?

**Comment by tottoszsolt** [comment]
Same here, reinstalled the whole app, not working

**Comment by Jelgnum** [comment]
I'm experiencing this on linux too, so not just limited to windows

**Comment by Crawron** [comment]
From what I can tell, the application used for the RPC no longer exists on Discord

I'm guessing it'd be enough to replace the app ID with an existing one
https://github.com/th-ch/youtube-music/blob/073ea27bbab01dbdf12ebebc3e41f55e570f7b4d/plugins/discord/back.js#L8

**Comment by zoeeechu** [comment]
> From what I can tell, the application used for the RPC no longer exists on Discord
> 
> I'm guessing it'd be enough to replace the ID with an existing one. I would also request for it to not be hardcoded
> 
> https://github.com/th-ch/youtube-music/blob/073ea27bbab01dbdf12ebebc3e41f55e570f7b4d/plugins/discord/back.js#L8

Alrightttt so- I forked it and fixed it for the time being although I am sure they will fix it themselves later this is just a temporary solution > [youtube-music-RPC-FIX](https://github.com/zoeeechu/youtube-music-RPC-FIX)

**Comment by Crawron** [comment]
I would leave this open until it's fixed on here

**Comment by VeikkoLehmuskorpi** [comment]
A small nitpick, could you capitalize the app name to "Youtube Music"? 😄

**Comment by Kxsumi** [comment]
> A small nitpick, could you capitalize the app name to "Youtube Music"? 😄

true
