### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by TimNedvyga** [th-ch/youtube-music#88]
Hey, I just picked up a new Mac mini with M1. The app is working fine, but startup time is noticeable longer, so no pressure, but I wonder if there any plans for a new Apple Silicon supported build?

**Comment by semvis123** [comment]
Is this fixed if you update the version of electron?

This should do it.
```yarn upgrade --latest```

note: you will need to compile the app yourself to test this, check out the Dev section first in readme.md

**Comment by th-ch** [comment]
Hey @TimNedvyga, thanks for submitting the issue! You can have a look at https://github.com/th-ch/youtube-music/issues/85 that explains how to build for ARM (only the downloader is reported to be broken) - as @semvis123 mentioned, upgrading dependencies might help too, I plan on upgrading the project to electron 11 soon but feel free to give it a try on your side!

**Comment by himankpathak** [comment]
I was able to build for Apple Silicon from `master` without any issues.

Package upgrade required: `electron-builder@22.10.5`
Built with Node `14.16.1 arm64`
