### ISSUE TITLE
Downloader update playlists

### ISSUE THREAD

**Issue by xamionex** [th-ch/youtube-music#882]
When downloading playlists with downloader, it'll successfully download the full playlist in it's folder and all it's songs unless they're unavailable on yt (then it'll throw an error).

My issue is on the 2nd download, it'll just say the playlists folder exists and won't even try to download, this should be made a confirmation dialog if you want to update or abort and then it'll skip songs you have downloaded and download whichever songs you don't have in the folder

**Comment by th-ch** [comment]
Hey @xamionex, it's expected (it makes it easier to handle the case where the folder exists) - though there is room for improvement indeed :)
