### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by shahar015** [th-ch/youtube-music#884]
I got logged out, and when I try to log back in, I get the "Couldn’t sign you in This browser or app may not be secure." message.

**Comment by th-ch** [comment]
Hey @shahar015 , which version are you using? It seems to work fine with the latest version.

**Comment by shahar015** [comment]
I have found that the "override useragent file" was causing this issue

**Comment by b-risk** [comment]
same here, im on v1.20.0 and it says wrong password everytime, and when i tried to do the forget password thing it finally logged in than it crashed and started over again at signed out

**Comment by b-risk** [comment]
just tried installing v1.19.0 and have the same issue
