### ISSUE TITLE
[bug] Can't skip suicide warning

### ISSUE THREAD

**Issue by Technetium1** [th-ch/youtube-music#886]
> The following content may contain suicide or self-harm topics.
Viewer discretion is advised. [Learn more](https://support.google.com/youtube/answer/2802245?hl=en)

I choose "I understand and wish to proceed", then it goes to a playlist with only that track, and it still refuses to play.

Example track:
https://music.youtube.com/watch?v=p0lbm5J0uUs

**Comment by LetrixZ** [comment]
That's a YT Music problem.

**Comment by th-ch** [comment]
Hey @Technetium1 , you can enable the "bypass-age-restrictions" plugin, it should work! Closing the issue, feel free to re-open if it does not work as expected!

**Comment by Technetium1** [comment]
Thanks @th-ch, I didn't see that plugin! I've enabled it, relauched, and there is slightly different behavior. It does change the playlist when I click that I wish to proceed, but it now provides autoplay recommendations after. The video is still unplayable:
![image](https://user-images.githubusercontent.com/9877150/202931395-40c32c76-3428-412c-bf9f-a1ebf30fc621.png)

I'd reopen this if I could, but I don't have permission :upside_down_face:

**Comment by Technetium1** [comment]
I just noticed https://github.com/th-ch/youtube-music/commit/3fb219fcd14f6ebe05ad99069b753d2fe925d9c5

I use [this AUR package](https://aur.archlinux.org/packages/youtube-music-git) through Chaotic-AUR. During the build of the latest commit to test this, I noticed a couple odd errors in the build. Maybe it'd be good to look at them, though they don't seem critical, *at least for now*, as the modules are apparently optional: [youtube-music-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/youtube-music-git.log)

**Comment by Technetium1** [comment]
We have a new form of failure as of https://github.com/th-ch/youtube-music/commit/3fb219fcd14f6ebe05ad99069b753d2fe925d9c5 - playback controls disappear
![image](https://user-images.githubusercontent.com/9877150/202933085-06b9ccdc-d06e-4cb4-9e42-2bbda2e807d7.png)

**Comment by Technetium1** [comment]
@th-ch It got me again. Still kills the queue and completely changes what's playing.
![image](https://user-images.githubusercontent.com/9877150/208227920-1768aa22-ad69-4f3c-b68c-cebdb36328f8.png)

**Comment by Technetium1** [comment]
Solved in https://github.com/th-ch/youtube-music/releases/tag/v2.0.0
