### ISSUE TITLE
My Adblock is still not working

### ISSUE THREAD

**Issue by ENDMod** [th-ch/youtube-music#89]
![Screenshot 2020-12-10 093026](https://user-images.githubusercontent.com/71812176/101709551-a28ebb80-3aca-11eb-8d08-15e4e5d28043.jpg)

This is the config
{
	"window-size": {
		"width": 1100,
		"height": 550
	},
	"url": "https://music.youtube.com/watch?v=4z3D0XObcgk&list=PLdAALL-ipQaEPfw5mV2k5N6fdTRayYnXX",
	"plugins": {
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"downloader": {
			"enabled": false,
			"ffmpegArgs": []
		},
		"navigation": {
			"enabled": true
		},
		"auto-confirm-when-paused": {
			"enabled": true
		}
	},
	"options": {
		"tray": true,
		"appVisible": false,
		"autoUpdates": true,
		"startAtLogin": false
	},
	"window-position": {
		"x": -7,
		"y": -7
	},
	"window-maximized": true,
	"__internal__": {
		"migrations": {
			"version": "1.7.3"
		}
	}
}

**Comment by ENDMod** [comment]
![Screenshot 2020-12-10 093317](https://user-images.githubusercontent.com/71812176/101709619-c4883e00-3aca-11eb-819a-7c0d3ed30894.jpg)

**Comment by maurperez** [comment]
I'm in the same situation

**Comment by th-ch** [comment]
Hey @maurperez @ENDMod, thanks for the feedback! [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly!

**Comment by SeyMotor** [comment]
> 
> 
> Hey @maurperez @ENDMod, thanks for the feedback! [v1.7.4](https://github.com/th-ch/youtube-music/releases/tag/v1.7.4) is in pre-release and should fix ad blocking! It seems to work fine for me, free free to give it a try and update this issue accordingly! If you changed adblock settings, you can revert to the default:
> 
> ```json
> "adblocker": {
>     "enabled": true,
>     "cache": true,
>     "disableDefaultLists": false,
>     "additionalBlockLists": []
> },
> ```

Hi, i just updated from a previous version to this one, and the adblock still doesnt work, help

![image](https://user-images.githubusercontent.com/75854840/101936161-f8449000-3bbe-11eb-8e85-ff77f517c22a.png)

CONFIG:

```
{
	"window-size": {
		"width": 1366,
		"height": 768
	},
	"url": "https://music.youtube.com/watch?v=iM5EZTOn7Ik&list=PL9BgD_Yj00fELAVhaDfkEtKLO0nKFusrl",
	"plugins": {
		"adblocker": {
			"enabled": true,
			"cache": true,
			"disableDefaultLists": false,
			"additionalBlockLists": []
		},
		"downloader": {
			"enabled": true,
			"ffmpegArgs": []
		},
		"navigation": {
			"enabled": true
		},
		"shortcuts": {
			"enabled": true
		},
		"auto-confirm-when-paused": {
			"enabled": true
		}
	},
	"options": {
		"tray": true,
		"appVisible": true,
		"autoUpdates": true,
		"startAtLogin": false
	},
	"window-position": {
		"x": -8,
		"y": -8
	},
	"window-maximized": true,
	"__internal__": {
		"migrations": {
			"version": "1.7.2"
		}
	}
}
```

**Comment by th-ch** [comment]
Hey @SeyMotor, thanks for the feedback! Can you check you are running the latest version (1.7.4 - with autoupdates enabled, you will receive a notification if you are running an older version) and have restarted the app once installed? With options > toggle devtools, you can also see blocked requests in the "Network" tab, to ensure adblocking is working.

**Comment by SeyMotor** [comment]
> 
> 
> Hey @SeyMotor, thanks for the feedback! Can you check you are running the latest version (1.7.4 - with autoupdates enabled, you will receive a notification if you are running an older version) and have restarted the app once installed? With options > toggle devtools, you can also see blocked requests in the "Network" tab, to ensure adblocking is working.

This is weird, but now it started working, because i have restarted the app a couple of times before, and i uninstalled it more times, even reinstalled it just to test this, and yes it seems to be blocking requests now.
The only thing i changed was turning on notifications, which i didn't have on.

![image](https://user-images.githubusercontent.com/75854840/101947508-56796f00-3bcf-11eb-886f-96f431b94c72.png)

**Comment by th-ch** [comment]
Hey @SeyMotor, [latest version 1.9.0](https://github.com/th-ch/youtube-music/releases/tag/v1.9.0) has a Discord plugin (credits to @semvis123), feel free to give it a try!
