### ISSUE TITLE
User identification

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#892]
I'm working on a plugin that allows you to control the application using a REST API, so I need a way to identify a user. That is, a unique identifier for each user. Can I get the user's Google email or User ID from the plugin? What happens if the user isn't logged in? Do you have any ideas for how I can uniquely identify users? Thanks!

**Comment by LetrixZ** [comment]
You could generate one when enabled and let the users change it.

**Comment by Zo-Bro-23** [comment]
Yes, that's exactly what I planned on doing. There's no way I can get the user's email or Google ID though right? That would be much easier to work with. Thanks anyways!
