### ISSUE TITLE
Discord RPC not working

### ISSUE THREAD

**Issue by rlygudprayer** [th-ch/youtube-music#895]
![image](https://user-images.githubusercontent.com/101914197/203773940-53202244-7ad3-41b7-9075-8f3419b38e6e.png)

**Comment by Zo-Bro-23** [comment]
Version please. I fixed this in https://github.com/th-ch/youtube-music/commit/ee01ae1c00c73b0dfd5db8c6e7ff7352783987da but it'll take some time to show up in a release. For now, all you can do is do a custom build using `yarn build`. Sorry for the inconvenience 😕

**Comment by rlygudprayer** [comment]
v 1.18.0

**Comment by Kxsumi** [comment]
> Version please. I fixed this in [ee01ae1](https://github.com/th-ch/youtube-music/commit/ee01ae1c00c73b0dfd5db8c6e7ff7352783987da) but it'll take some time to show up in a release. For now, all you can do is make a custom build using `yarn build`. Sorry for the inconvenience 😕

for some reason whenever I try to build using yarn I get an error.

    This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at pQ.getCandidates (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:435:5146)
    at Wf.getCandidates (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:391:1264)
    at C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:7695
    at Rf (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8965)
    at ge (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:7675)
    at async Promise.allSettled (index 0)
    at async eo (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8293)
    at async C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:8205
    at async ni.startProgressPromise (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:45507)
    at async He.resolveEverything (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:6238)
    
    updating the lockfile just spits and error (using yarn install)

**Comment by rlygudprayer** [comment]
Sorry for sounding dumb but I know nothing about GIthub. How do I make the custom yarn build?

**Comment by Zo-Bro-23** [comment]
Don't apologize for asking questions! You're on Windows right? Here's how you do a build:

- Download and install [NodeJS](https://nodejs.org/en/) (make sure add to path is selected)
- Download [this](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip) zip file
- Unzip it (extract all)
- Open the extracted folder (should contain many files)
- Right click the folder in Explorer and select Open Command Prompt Here (or Windows Terminal)
- Type the following one by one:
- - `npm i -g yarn`
- - `yarn`
- - `npm i rimraf`
- - `yarn build:win`
- Wait a while
- There should be a setup file created in `./dist/`
- Use that to install the app

**Comment by rlygudprayer** [comment]
![image](https://user-images.githubusercontent.com/101914197/203932832-7ae7214d-e7dd-4ecd-92b5-f8c59d89cadf.png)
When I right click the folder, only the following options appear?

**Comment by Zo-Bro-23** [comment]
Click the Start button and type Command Prompt. Hit enter. Type `cd` followed by the path of the folder. For example: `cd C:\\Users\zohan\youtube-music\`. You can also copy this path from Explorer if you want.

**Comment by rlygudprayer** [comment]
It's working now. Thanks @Zo-Bro-23 .

**Comment by Teraisu** [comment]
> Don't apologize for asking questions! You're on Windows right? Here's how you do a build:
> 
> * Download and install [NodeJS](https://nodejs.org/en/) (make sure add to path is selected)
> * Download [this](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip) zip file
> * Unzip it (extract all)
> * Open the extracted folder (should contain many files)
> * Right click the folder in Explorer and select Open Command Prompt Here (or Windows Terminal)
> * Type the following one by one:
> * * `npm i -g yarn`
> * * `yarn`
> * * `npm i rimraf`
> * * `yarn build:win`
> * Wait a while
> * There should be a setup file created in `./dist/`
> * Use that to install the app

when trying this it said that I needed permissions to run "npm i -g yarn" is there a reason ? i have everything installed and running the cmd.

**Comment by Zo-Bro-23** [comment]
`npm i -g yarn` installs `yarn` globally on your computer, so it is possible that you might need extra permissions. Try running `cmd` as Administrator (right-click in the Start Menu).

**Comment by Teraisu** [comment]
I think I was able to install yarn, but now its telling me this after typing " yarn ."
![Capture](https://user-images.githubusercontent.com/95589812/204607133-1cd5ace0-51c8-4013-b2b4-f7709d8102f9.PNG)

**Comment by Teraisu** [comment]
> I think I was able to install yarn, but now its telling me this after typing " yarn ." I also have the execution policies "allSigned" when i checked. ![Capture](https://user-images.githubusercontent.com/95589812/204607133-1cd5ace0-51c8-4013-b2b4-f7709d8102f9.PNG)

ive gotten the commands to work... but the last one " yarn build:win " keeps failing and says error command failed.

**Comment by Kxsumi** [comment]
> > I think I was able to install yarn, but now its telling me this after typing " yarn ." I also have the execution policies "allSigned" when i checked. ![Capture](https://user-images.githubusercontent.com/95589812/204607133-1cd5ace0-51c8-4013-b2b4-f7709d8102f9.PNG)
> 
> ive gotten the commands to work... but the last one " yarn build:win " keeps failing and says error command failed.

Run this: Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy UnRestricted

**Comment by Teraisu** [comment]
> * npm i rimraf

thank you! it worked!

**Comment by Destroy666x** [comment]
I don't know what's the release flow of this repo, but I feel like this deserves a minor version hotfix as it's basically a broken feature. Hopefully the regular release won't take too long.

**Comment by superstarx** [comment]
> Don't apologize for asking questions! You're on Windows right? Here's how you do a build:
> 
> * Download and install [NodeJS](https://nodejs.org/en/) (make sure add to path is selected)
> * Download [this](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip) zip file
> * Unzip it (extract all)
> * Open the extracted folder (should contain many files)
> * Right click the folder in Explorer and select Open Command Prompt Here (or Windows Terminal)
> * Type the following one by one:
> * * `npm i -g yarn`
> * * `yarn`
> * * `npm i rimraf`
> * * `yarn build:win`
> * Wait a while
> * There should be a setup file created in `./dist/`
> * Use that to install the app

I tried to do this too, as I was having the same issue with the Discord Rich Presence thing. I still can't get the last command to work, `yarn build:win` , it gives me an error message and I have no idea what to do with it. I'm new to github so I hope I did this reply comment correct.
![image_2022-12-05_141233865](https://user-images.githubusercontent.com/119865271/205645631-829f2e38-2c90-4f68-9ef1-dc183d5eb485.png)

**Comment by Zo-Bro-23** [comment]
Try going inside another level: `cd C:\Users\evibi\Downloads\youtube-music-3605e32b2531efa3d124ef509ac2612347bf4679\youtube-music-3605e32b2531efa3d124ef509ac2612347bf4679`. Typing in `dir` should list many files and folders, not just one or two.

**Comment by superstarx** [comment]
> Try going inside another level: `cd C:\Users\evibi\Downloads\youtube-music-3605e32b2531efa3d124ef509ac2612347bf4679\youtube-music-3605e32b2531efa3d124ef509ac2612347bf4679`. Typing in `dir` should list many files and folders, not just one or two.

Thank you, this helped and it now works! 😄

**Comment by 0Namaste0** [comment]
> Don't apologize for asking questions! You're on Windows right? Here's how you do a build:
> 
> * Download and install [NodeJS](https://nodejs.org/en/) (make sure add to path is selected)
> * Download [this](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip) zip file
> * Unzip it (extract all)
> * Open the extracted folder (should contain many files)
> * Right click the folder in Explorer and select Open Command Prompt Here (or Windows Terminal)
> * Type the following one by one:
> * * `npm i -g yarn`
> * * `yarn`
> * * `npm i rimraf`
> * * `yarn build:win`
> * Wait a while
> * There should be a setup file created in `./dist/`
> * Use that to install the app

I was trying to `npm i rimraf` and got this errors while running windows terminal as an administrator
![err](https://user-images.githubusercontent.com/111089212/207876557-83dcb258-acd4-4c86-8676-8da38a993a81.png)
am I doind something wrong? 
how can I solve the problem?

**Comment by Zo-Bro-23** [comment]
> > Don't apologize for asking questions! You're on Windows right? Here's how you do a build:
> > 
> > * Download and install [NodeJS](https://nodejs.org/en/) (make sure add to path is selected)
> > * Download [this](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip) zip file
> > * Unzip it (extract all)
> > * Open the extracted folder (should contain many files)
> > * Right click the folder in Explorer and select Open Command Prompt Here (or Windows Terminal)
> > * Type the following one by one:
> > * * `npm i -g yarn`
> > * * `yarn`
> > * * `npm i rimraf`
> > * * `yarn build:win`
> > * Wait a while
> > * There should be a setup file created in `./dist/`
> > * Use that to install the app
> 
> I was trying to `npm i rimraf` and got this errors while running windows terminal as an administrator ![err](https://user-images.githubusercontent.com/111089212/207876557-83dcb258-acd4-4c86-8676-8da38a993a81.png) am I doind something wrong? how can I solve the problem?

This is an error that's been popping up recently. Are you doing a build just to fix the Discord plugin? If so, I would recommend downloading a setup file from [this](https://github.com/Zo-Bro-23/youtube-music/releases) link. It's pre-built by me.

**Comment by 0Namaste0** [comment]
yup, working. tnx a lot
