### ISSUE TITLE
Trying to build using yarn spits errors.

### ISSUE THREAD

**Issue by Kxsumi** [th-ch/youtube-music#896]
C:\Users\xfred\youtube-music>yarn
➤ YN0000: ┌ Resolution step
➤ YN0014: │ Simple-YouTube-Age-Restriction-Bypass@https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?[...]: Only some patterns can be imported from legacy lockfiles (not "https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?v2.5.4#4cdc95d7614baa3fdfe334ebf6b8a99b0d8347f0")
➤ YN0001: │ Error: Simple-YouTube-Age-Restriction-Bypass@https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?[...] isn't supported by any available resolver
    at Wf.getResolverByDescriptor (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:391:1647)
    at Wf.bindDescriptor (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:391:1036)
    at Z (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:6905)
    at async Promise.allSettled (index 0)
    at async eo (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8293)
    at async C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:8205
    at async Ke.startProgressPromise (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:45507)
    at async He.resolveEverything (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:6238)
    at async C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:442:2038
    at async Ke.startSectionPromise (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:409:3252)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 144ms

C:\Users\xfred\youtube-music>yarn build
Internal Error: youtube-music@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at pQ.getCandidates (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:435:5146)
    at Wf.getCandidates (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:391:1264)
    at C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:7695
    at Rf (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8965)
    at ge (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:7675)
    at async Promise.allSettled (index 0)
    at async eo (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8293)
    at async C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:8205
    at async ni.startProgressPromise (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:45507)
    at async He.resolveEverything (C:\Users\xfred\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:6238)

**Comment by Zo-Bro-23** [comment]
Which version are you using? I'm assuming you're using the latest. I think the error happens because you haven't installed the necessary dependencies. Run `yarn` first to install everything. (I also needed to run `npm i rimraf` for some reason (I'm on Windows).

**Comment by Kxsumi** [comment]
> Which version are you using? I'm assuming you're using the latest. I think the error happens because you haven't installed the necessary dependencies. Run `yarn` first to install everything. (I also needed to run `npm i rimraf` for some reason (I'm on Windows).

Latest, installed rimraf, didn't fix. Running yarn spits error 2, same with error 1 when running yarn install

**Comment by Zo-Bro-23** [comment]
The Age Restriction plugin was recently updated (https://github.com/th-ch/youtube-music/commit/3fb219fcd14f6ebe05ad99069b753d2fe925d9c5), so the issue could be because of that. Try building from an earlier version (I used https://github.com/th-ch/youtube-music/commit/3605e32b2531efa3d124ef509ac2612347bf4679). Also, try deleting the local folder and using `git clone` to try the process all over again. I'm not sure, but if you already have `npm` plugins in the same directory, there could be a chance for conflict.

**Comment by Kxsumi** [comment]
> The Age Restriction plugin was recently updated ([3fb219f](https://github.com/th-ch/youtube-music/commit/3fb219fcd14f6ebe05ad99069b753d2fe925d9c5)), so the issue could be because of that. Try building from an earlier version (I used [3605e32](https://github.com/th-ch/youtube-music/commit/3605e32b2531efa3d124ef509ac2612347bf4679)). Also, try deleting the local folder and using `git clone` to try the process all over again. I'm not sure, but if you already have `npm` plugins in the same directory, there could be a chance for conflict.

can you explain the step-by-step on installing, etc.? Feel like I'm missing something here.

**Comment by Zo-Bro-23** [comment]
Download the zip file for commit https://github.com/th-ch/youtube-music/commit/3605e32b2531efa3d124ef509ac2612347bf4679 from [here](https://github.com/th-ch/youtube-music/archive/3605e32b2531efa3d124ef509ac2612347bf4679.zip). Unzip the file (extract all on Windows). Open a terminal or command prompt window inside the unzipped folder (use `cd` to navigate folders). Run `yarn`. Run `yarn build`. If it asks you to install rimraf, do that, using `npm i rimraf` or `npm i -g rimraf`. I'm not used to `yarn`, so I don't know the alternative command in `yarn`, which is why I suggested `npm`, but you can use `yarn` to install `rimraf` too. Run `yarn build` again, and the setup file should be created in `./dist/`.

**Comment by Kxsumi** [comment]
Ok, I tried a different computer, and I have now gotten to here:

  • electron-builder  version=23.0.3 os=10.0.22000
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  ⨯ Build for macOS is supported only on macOS, please see https://electron.build/multi-platform-build
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Zo-Bro-23** [comment]
Yes, that's expected. It happens because you're on Windows, and the command `yarn build` is trying to build for all three platforms, when you can only build Mac apps from a Mac. Try `yarn build:win` and let me know if you face any issues.

**Comment by Kxsumi** [comment]
Yep, took a while but it eventually finished and started. Thanks!
