### ISSUE TITLE
I'm getting the "connection closed" error when trying to connect YouTube Music 

### ISSUE THREAD

**Issue by MikiBat** [th-ch/youtube-music#898]
The error appears when I try to use the "reconnect" function.
I use the latest version 1.18.0
![image](https://user-images.githubusercontent.com/119011700/204111596-4cf644ee-cd5e-4ae4-bc15-4a53d37c60df.png)

**Comment by Keegan-Sutcliffe** [comment]
I had the same problem and building from source fixed it. 

His client ID was updated in [this commit](https://github.com/th-ch/youtube-music/commit/d199a5fce94e58df78ffceb58aa5c3bf1b3e07bc) after the 1.18.0 release. This is needed for the RPC login and I guess its failing to use the old ID.
