### ISSUE TITLE
ad blocker stopped working

### ISSUE THREAD

**Issue by Urgeistenergie** [th-ch/youtube-music#9]
YouTube changed something so that the ad blocker is bypassed. Can you fix that? Great app, by the way. Love it.

**Comment by th-ch** [comment]
Hey @Urgeistenergie, thanks for submitting the issue! It seems to be working fine on my app so there might something we are missing here, a few questions that can help us troubleshoot this:
- Is the plugin correctly enabled? (I guess so if it was working fine before, just checking!)
- what OS do you run the app on? 
- What language is YouTube Music in? (there could be ads specific to some countries)
- more advanced, do you know the DNS the ads come from? (you can find them with electron devtools) - Maybe the adblock list is missing some entries and needs an update

**Comment by Urgeistenergie** [comment]
Hey @th-ch ! Thanks for your replay. 17. days ago they appeared on every 3. Video. The ads are gone now. So I would say time to relax. :-)
If they reappear I'll let you know.

Anyway:
- Plugin is enabled
- Manjaro Linux and macOS Hackintosh
- German
- Don't know the DNS they came from. I will check with electron devtools if the reappear
