### ISSUE TITLE
Last.FM scrobbling issue. (and Discord RPC 00:00)

### ISSUE THREAD

**Issue by Vilsol** [th-ch/youtube-music#902]
I noticed that the last.fm scrobbling doesn't seem to work at all, except for the very first song of the day.

I dug into the issue, and I've realized that it's due to the fact that the `elapsedSeconds` field that gets taken from `video.currentTime` on the video element returns a huge number instead of 0 when switching to a new track. When that happens, [this](https://github.com/th-ch/youtube-music/blob/master/plugins/last-fm/back.js#L151-L152) calculation fails, as the plugin thinks we are past the halfway part of the song, so it never starts the scrobbler timeout. 

Fixing this should also fix the issue where discord lists 00:00 as the current progress of the song.

I don't have any proposals at the moment how this could be fixed, other than just overriding the field with `0` whenever `video-src-changed` event is fired, which I will be using as a workaround for now. 

It seems like the `video.currentTime` keeps going up as a sum of all song lengths played instead of resetting to 0 when a new song starts playing. I think it's not reliable to depend on this either way, as it seems they've implemented their own stream that the player just listens to.

**Comment by Zo-Bro-23** [comment]
That seems reasonable, considering #878 had a similar issue. I personally don't face this issue though, and I use a custom build of the latest version. Any ideas on how I can replicate the issue?

**Comment by Zo-Bro-23** [comment]
Other users seem to be facing the same issue (#930). Would it be possible for you to create a PR with the fix? Thanks a lot!

**Comment by wadegbow** [comment]
> That seems reasonable, considering #878 had a similar issue. I personally don't face this issue though, and I use a custom build of the latest version. Any ideas on how I can replicate the issue?

Okay this is weird, I was having the same issue as @Vilsol -- the first track would get scrobbled then the rest of the album wouldn't. This was using the most recent dmg (1.19.0) on the releases page. 

I tried to fix the issue using the info in this thread but wasn't having luck. Decided to just try building from source rather than using the version on the releases page and it just works now. Really no idea why but maybe this information will help someone smarter than me figure it out.

**Comment by Araxeus** [comment]
If the problem is indeed the intial `elapsedSeconds` being wrong, we can probably just set it to 0

https://github.com/th-ch/youtube-music/blob/master/providers/song-info-front.js#L54

Once again probably after #946 adds a `cause` parameter to the songInfo callback
