### ISSUE TITLE
No setup.exe for v1.18

### ISSUE THREAD

**Issue by SleepDaemon** [th-ch/youtube-music#911]
How v1.18 has no setup.exe but v1.17 does?

**Comment by Zo-Bro-23** [comment]
What do you mean? 1.18.0 has a setup file [here](https://github.com/th-ch/youtube-music/releases/download/v1.18.0/YouTube-Music-Setup-1.18.0.exe).

As a side note, the Discord plugin doesn't work for that version, so use the setup file that I created ([here](https://github.com/Zo-Bro-23/youtube-music/releases)) if you want to use the Discord plugin.

**Comment by SleepDaemon** [comment]
> What do you mean? 1.18.0 has a setup file [here](https://github.com/th-ch/youtube-music/releases/download/v1.18.0/YouTube-Music-Setup-1.18.0.exe).
> 
> As a side note, the Discord plugin doesn't work for that version, so use the setup file that I created ([here](https://github.com/Zo-Bro-23/youtube-music/releases)) if you want to use the Discord plugin.

bruh where, all it has is .exe
![image](https://user-images.githubusercontent.com/88533953/206628039-7e6f2f4e-0323-44fd-8d29-f6b1f967082b.png)

**Comment by SleepDaemon** [comment]
update you need to click on the version to see full list
