### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#912]
The predefined themes don't seem to work (I tested two):

![image](https://user-images.githubusercontent.com/62234360/206824565-25c3fbb9-7c4f-4571-ba93-8bfe1679ac62.png)

![image](https://user-images.githubusercontent.com/62234360/206824620-277771a9-3f44-4f2d-97f4-0ab748e727a0.png)

They look really weird for some reason. I think it's because different divs are different colors, so divs that are supposed to be invisible look different.

I don't mind writing my own CSS, but there are no instructions in the README on the format for custom themes. Please (@th-ch) add this to the README, or kindly (@kerichdev) fix the predefined themes.

**Comment by kerichdev** [comment]
Thanks for mentioning me! That was the intended behavior by the original developer, however I'll look into making a cleaner looking alternative!

**Comment by Zo-Bro-23** [comment]
Okay thanks! Also, what's the simplest way I can create my own CSS? I just want to add HEX Codes for colors, and it should work. I don't want to edit positioning and styling - just colors. Can you perhaps post a CSS template here for editing just the colors? Thanks!

**Comment by kerichdev** [comment]
As far as I'm concerned, the CSS files currently touch colors, and colors only - I'll work on simplifying them so they can be self-explanatory, but in the meantime, you can look for the colors, or the elements you wish to edit.

**Comment by kerichdev** [comment]
Happy to notify that I pushed some fixes that should have solved both of the problems! The first one was because of a Youtube Music update that added a gradient as the background, while the lists were an oversight.

**Comment by Zo-Bro-23** [comment]
Working! As a side note, the file names need to have `.css` appended to them to be able to be imported. I've created a pull request [here](https://github.com/kerichdev/themes-for-ytmdesktop-player/pull/3) that would make it easier for others to use themes. Please approve it. Thanks!

**Comment by FormalSnake** [comment]
For some reason importing the CSS files does nothing, and the No Theme is always selected.
I am on macOS Ventura on a M1 macbook air

**Comment by FormalSnake** [comment]
Ok, so the directory was not allowed apparently, and I didn't realize i needed to restart the app, maybe importing the theme should automatically load the theme in? And maybe just a dedicated directory with the option of using a custom one.

**Comment by Zo-Bro-23** [comment]
> Ok, so the directory was not allowed apparently, and I didn't realize i needed to restart the app, maybe importing the theme should automatically load the theme in? And maybe just a dedicated directory with the option of using a custom one.

Options > Advanced Options > Restart on config changes

**Comment by FormalSnake** [comment]
> > Ok, so the directory was not allowed apparently, and I didn't realize i needed to restart the app, maybe importing the theme should automatically load the theme in? And maybe just a dedicated directory with the option of using a custom one.
> 
> Options > Advanced Options > Restart on config changes

That's better!

**Comment by colineberly** [comment]
Is there a way to add the themes you've imported to the Visual Tweaks > Theme menu somehow?

**Comment by kerichdev** [comment]
> Is there a way to add the themes you've imported to the Visual Tweaks > Theme menu somehow?

I highly suggest you open a separate issue for this.
