### ISSUE TITLE
Install youtube-music via brew

### ISSUE THREAD

**Issue by mehdichaouch** [th-ch/youtube-music#914]
Hello,

I hope you are doing well?

In order to be able to install YouTube Music via [brew install youtube-music](https://brew.sh/), I created the `cask` file needed in [my fork](https://github.com/mehdichaouch/homebrew-cask/tree/youtube-music), but before opening a Pull Request, I need an action from you, your app need to be signed otherwise it will be not accepted.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/861701/206880870-c558e52b-e205-456b-a222-260133c90673.png">

<details>
<summary>error</summary>

```
audit for youtube-music: failed
 - Signature verification failed:
/private/tmp/d20221211-74825-nrcloz/YouTube Music.app: code object is not signed at all
In architecture: x86_64

macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.
Error: 1 problem in 1 cask detected
```
</details>

Do you think signing the app is possible for you?

As example, you can maybe check [Insomnia](https://github.com/Kong/insomnia/) app or [Kap](https://github.com/wulkano/kap/) app.

BR,

**Comment by th-ch** [comment]
👋 Indeed, signing requires a paying subscription so is not available at the moment! Though it should not prevent the cask afaik, some others like Stubby Manager are not signed:
```
$ brew install stubbymanager
$ codesign -dv --verbose=4 /Applications/StubbyManager.app 
/Applications/StubbyManager.app: code object is not signed at all
```

Trying locally to `brew install youtube-music`, it works - one just needs to disable quarantine for the app, or install it with `brew install youtube-music --no-quarantine`

**Comment by devnoname120** [comment]
@th-ch As far as I know the official Homebrew Cask repository accepts ad-hoc signatures. So you can just do the following on the future macOS binaries that you release:
```shell
codesign --sign - --deep --force *.dmg
```

**Comment by mehdichaouch** [comment]
> @th-ch As far as I know the official Homebrew Cask repository accepts ad-hoc signatures. So you can just do the following on the future macOS binaries that you release:
> 
> ```shell
> codesign --sign - --deep --force *.dmg
> ```
> 
> You can then add the following install instructions in the `README.md` file as you mentioned:
> 
> ```shell
> brew install youtube-music --no-quarantine
> ```

@devnoname120 it also mean that we can test this on our side 🤔

**Comment by mehdichaouch** [comment]
In WIP: https://github.com/Homebrew/homebrew-cask/pull/148404 ...

**Comment by mehdichaouch** [comment]
Hi there !

I heard that @th-ch as new maintainers to this repository, that great news 🎉 and thanks for the latest release 2.0 😉.

So if someone want to achieve this issue with me, it would be nice to maintain local version of `youtube-music` with just a `brew update youtube-music`.

Waiting from your help.
Best

**Comment by avichou** [comment]
is the issue stalled ?

**Comment by JellyBrick** [comment]
> is the issue stalled ?

I can't help this issue because I'm not using macOS...

**Comment by JellyBrick** [comment]
Resolved by #1357

**Comment by JellyBrick** [comment]
> Experencing a problem when upgrading/installing using provided brew command.
> 
> Get error:`Error: No such file or directory @ rb_sysopen - https://api.github.com/repos/th-ch/youtube-music/releases/latest`
> 
> Tried to remove it still showing. Was working at some time in the past and now I just install via GUI APP.
> 
> Anyone else experience this? Used this code to install `brew install --cask https://raw.githubusercontent.com/th-ch/youtube-music/master/youtube-music.rb`
> 
> and also tried the old `brew install youtube-music`
> 
> Any suggestions? Thanks

I think it's related to #1514

**Comment by indianets** [comment]
#issuecomment-1869965602
