### ISSUE TITLE
Plugin Bar

### ISSUE THREAD

**Issue by rendyzou89** [th-ch/youtube-music#919]
anyone have a probelm with plugin bar now show when presitn ALT on 1.18.0?

**Comment by Zo-Bro-23** [comment]
I have the "hide menu" option enabled, so when YTM starts, it's hidden. When I press `alt` or `esc`, it becomes visible, but then it doesn't autohide. I have to restart the app to hide the menu again. Is that what you meant?

**Comment by rendyzou89** [comment]
> I have the "hide menu" option enabled, so when YTM starts, it's hidden. When I press `alt` or `esc`, it becomes visible, but then it doesn't autohide. I have to restart the app to hide the menu again. Is that what you meant?

Woah, i forget ESC can do that to, ALT didn't work on me (Windows 11), but ESC work, thanks Zo-Bro
