### ISSUE TITLE
Application hanging after a while of playback

### ISSUE THREAD

**Issue by soarpasser** [th-ch/youtube-music#923]
I usually leave the application running in the background when using it, and it's not infrequent that it will hang when a new song is about to play. The entire interface becomes unresponsive, and only an app restart will get it working again.

From the dev console I can see that the dialogues that always pops up when the application hangs:
![image](https://user-images.githubusercontent.com/74951691/208245074-9af27980-51f5-460b-afba-07311fa885ad.png)

The logs of all the events in the console are here.
[music.youtube.com-1671284572951.log](https://github.com/th-ch/youtube-music/files/10251835/music.youtube.com-1671284572951.log)

If anybody could identify the issue from what's available here/provide a potential fix to the problem it'll be greatly appreciated.

**Comment by JellyBrick** [comment]
This is an issue with the YT server.
