### ISSUE TITLE
Dev build applications menu shortcut

### ISSUE THREAD

**Issue by Equinoxx4978** [th-ch/youtube-music#927]
Im using Gnome 43.2 on EndavourOS and I am  bit annoyed. I am required to use the dev build for discord support, which is annoying. Since I am using the dev build, when I install the program with yarn, it doesn't generate any desktop/app menu shortcut. The shortcut not being present is annoying because of 2 things.
1. There is no icon for the app in my taskbar/shelf, so it looks bad graphically.
2. I can't pin the app for quick access, so I have to run a command every time i wish to start the app.

If anybody has a solution for these issues, please tell me.

(Can't wait for the fixed rich presence to be added in the next release, so I can go back to using the standard version)

**Comment by Zo-Bro-23** [comment]
Dev Build should technically work exactly the same way that the standard version does. How did you create this build? Did you use the installable or did you use the portable version?

I've made some builds (with working Discord) for Linux [here](https://github.com/Zo-Bro-23/youtube-music/releases), and I personally use the `.deb` version to install and run the app on Ubuntu (20.04). I'm not sure how you install apps on EndavourOS, but can you try using an installable from there? Thanks!

**Comment by Equinoxx4978** [comment]
I installed it by this method:
```
git clone https://github.com/th-ch/youtube-music
cd youtube-music
yarn
yarn start
```

If there is a way that I can istall your fork through the AUR/PacMan? (Since im on an arch based distro)

Note: Ill give the `.deb` a go. If it doesn't work ill come back here.

**Comment by Equinoxx4978** [comment]
There are 2 ways I can install packages on my OS.
1. Through my package manager (`pacman` or `yay`)
2. Through building it from source

**Comment by Zo-Bro-23** [comment]
> I installed it by this method:
> 
> ```
> git clone https://github.com/th-ch/youtube-music
> cd youtube-music
> yarn
> yarn start
> ```
> 
> If there is a way that I can istall your fork through the AUR/PacMan? (Since im on an arch based distro)
> 
> Note: Ill gave the `.deb` a go and it wasn't compatible since I'm on an arch based distro.

Ah, I see what the problem is! `yarn start` only runs the program temporarily, which means that it isn't actually installed on your system. This is why you are not able to start it from the menu.

I have four files available: `.deb`, `.freebsd`, `.snap`, and `.appimage`. Do any of those work for you?

If not, you have to build it for yourself:
> ```
> git clone https://github.com/Zo-Bro-23/youtube-music
> cd youtube-music
> yarn
> ```
Then, do the following:
1. Edit `./package.json` at line 51 and add `pacman` to the list
2. Run `yarn build:linuxactions`
3. A pacman file should be created in the `./dist/` folder

You can also do this with a clone of this repo instead of mine, but you might run into an error (I sometimes do) regarding `rimraf`. I've raised a PR for this bug, but it doesn't seem to have been accepted.

**Comment by Equinoxx4978** [comment]
I followed your instructions and ran the `yarn` command, which worked. But when I used the `yarn build:linuxactions` command it worked for a bit until I came across this output:
```
yarn run v1.22.19
warning ../package.json: No license field
$ electron-builder --linux -p never
  • electron-builder  version=23.0.3 os=6.0.12-arch1-1
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=register-scheme@0.0.2 platform=linux arch=x64
  • rebuilding native dependency  name=register-scheme version=0.0.2
  • packaging       platform=linux arch=x64 electron=20.1.1 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v20.1.1/electron-v20.1.1-linux-x64.zip size=89 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v20.1.1/electron-v20.1.1-linux-x64.zip duration=13.24s
  • building        target=AppImage arch=x64 file=dist/YouTube Music-1.18.2.AppImage
  • building        target=snap arch=x64 file=dist/youtube-music_1.18.2_amd64.snap
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z size=1.5 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z duration=1.448s
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=2.699s
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=4.369s
  • cannot move downloaded into final location (another process downloaded faster?)  path=/home/josh/.cache/electron-builder/appimage/appimage-12.0.1
                                                                                     tempFile=/home/josh/.cache/electron-builder/appimage/654601807
                                                                                     error=rename /home/josh/.cache/electron-builder/appimage/654601807 /home/josh/.cache/electron-builder/appimage/appimage-12.0.1: file exists
  • building        target=pacman arch=x64 file=dist/youtube-music-1.18.2.pacman
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=4.77s
  ⨯ cannot execute  cause=exit status 127
                    errorOut=/home/josh/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
    
                    command=/home/josh/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir --force -t pacman -d c-ares -d ffmpeg -d gtk3 -d http-parser -d libevent -d libvpx -d libxslt -d libxss -d minizip -d nss -d re2 -d snappy -d libnotify -d libappindicator-gtk3 --pacman-compression xz --architecture amd64 --after-install /tmp/t-guSUjP/0-after-install --after-remove /tmp/t-guSUjP/4-after-remove --description '
     YouTube Music Desktop App - including custom plugins' --version 1.18.2 --package /home/josh/youtube-music/dist/youtube-music-1.18.2.pacman --name youtube-music --maintainer 'th-ch <th-ch@users.noreply.github.com>' --url 'https://github.com/th-ch/youtube-music#readme' --vendor 'th-ch <th-ch@users.noreply.github.com>' --license MIT '/home/josh/youtube-music/dist/linux-unpacked/=/opt/YouTube Music' /home/josh/youtube-music/assets/generated/icons/png/16x16.png=/usr/share/icons/hicolor/16x16/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/24x24.png=/usr/share/icons/hicolor/24x24/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/32x32.png=/usr/share/icons/hicolor/32x32/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/48x48.png=/usr/share/icons/hicolor/48x48/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/64x64.png=/usr/share/icons/hicolor/64x64/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/128x128.png=/usr/share/icons/hicolor/128x128/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/256x256.png=/usr/share/icons/hicolor/256x256/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/512x512.png=/usr/share/icons/hicolor/512x512/apps/youtube-music.png /home/josh/youtube-music/assets/generated/icons/png/1024x1024.png=/usr/share/icons/hicolor/1024x1024/apps/youtube-music.png '/tmp/t-guSUjP/8-YouTube Music.desktop=/usr/share/applications/youtube-music.desktop'
                    workingDir=
error Command failed with exit code 1.
```

**Comment by Zo-Bro-23** [comment]
I can't replicate the issue because you can only build for `pacman` on archlinux, not ubuntu, so it anyways doesn't work for me.

Try deleting the `./dist/` folder and making sure it's empty. Also try running `sudo pacman -Syu libxcrypt-compat` to install the missing dependency it's complaining about.

**Comment by Equinoxx4978** [comment]
It works! (sort of)

By the looks of things you got everything correct, so thanks, but I did notice something.
Arch `pacman` installer files don't end in `.pacman` instead it should end it `.pkg.tar.xz`

I read [here](https://www.reddit.com/r/archlinux/comments/8oivz2/comment/e04glya/?utm_source=share&utm_medium=web2x&context=3) that some other applications have made that mistake.

Everything ended up working, I just needed to rename the outputted file from `.pacman` to `.pkg.tar.xz`

Thanks for all your help :+1:

**Comment by Equinoxx4978** [comment]
# So in total all I had to do was:
1. Run these commands
```
sudo pacman -Syu libxcrypt-compat
git clone https://github.com/Zo-Bro-23/youtube-music
cd youtube-music
yarn
```

2. Add `pacman` to Line 51 of `package.json`

3. Run this command:
```yarn build:linuxactions```

4. Go into the `./dist/` folder and rename `youtube-music-1.18.2.pacman` to `youtube-music-1.18.2.pkg.tar.xz`

5. Run `youtube-music-1.18.2.pkg.tar.xz` to install

Thats all I had to do.

**Comment by Zo-Bro-23** [comment]
> # So in total all I had to do was:
> 1. Run these commands
> 
> ```
> sudo pacman -Syu libxcrypt-compat
> git clone https://github.com/Zo-Bro-23/youtube-music
> cd youtube-music
> yarn
> ```
> 
> 2. Add `pacman` to Line 51 of `package.json`
> 3. Run this command:
>    `yarn build:linuxactions`
> 4. Go into the `./dist/` folder and rename `youtube-music-1.18.2.pacman` to `youtube-music-1.18.2.pkg.tar.xz`
> 5. Run `youtube-music-1.18.2.pkg.tar.xz` to install
> 
> Thats all I had to do.

Thanks - this will be useful for other users with the same issue!
