### ISSUE TITLE
Glitchy music only when playing Brain Stew

### ISSUE THREAD

**Issue by askiiart** [th-ch/youtube-music#929]
When playing [Brain Stew, by Green Day](https://music.youtube.com/watch?v=IPeJ7iM55hc&feature=share), the music plays and pauses very rapidly, and skips around a bit. But **only** when playing Brain Stew, not on *any* other songs.

[Here's a video showing it (no audio, sorry)](https://user-images.githubusercontent.com/90910526/209455668-118af50c-5116-482f-9fd7-3eabf884b4a6.webm)

Edit: More details...
Enabled plugins:
- adblocker
- bypass-age-restrictions
- discord
- lyrics-genius
- navigation
- skip-silences

The song is stable, and works fine after 37 seconds (after 0:37)

**Comment by Zo-Bro-23** [comment]
Hmm. Do you have the playback speed plugin enabled?

**Comment by askiiart** [comment]
> Hmm. Do you have the playback speed plugin enabled?

No, I don't. Here's my list of enabled plugins:
```
adblocker
bypass-age-restrictions
discord
lyrics-genius
navigation
skip-silences
```

**Comment by askiiart** [comment]
@Zo-Bro-23 I also just added some more details in the [original comment](https://github.com/th-ch/youtube-music/issues/929#issue-1510196366)

**Comment by Zo-Bro-23** [comment]
Try going to https://music.youtube.com and playing the same song. It might be a bug with YouTube Music. If the issue is _**only**_ present with this one song, it might not be worth it to debug it, but please let me know if the issue is present for any other song. Thanks!

**Comment by askiiart** [comment]
It works on https://music.youtube.com (and on YT Music Vanced on my phone), and it seems to only happen with this song. It also stays across reinstalls and reboots. BTW, I'm using Fedora 36.

**Comment by Zo-Bro-23** [comment]
Hmm. I honestly have no idea why that is. We'll see if someone else can figure it out 😕

**Comment by askiiart** [comment]
I'll try it out in some virtual machines to see if it's specific to my computer, and will report back here.

**Comment by th-ch** [comment]
👋 I can reproduce, the `skip-silences` plugin is responsible for it, due to the repeated silences in the music - as of now, your best bet might be to disable it, otherwise https://github.com/th-ch/youtube-music/pull/931 will add an option to only skip silences at the beginning of the song!

**Comment by askiiart** [comment]
> :wave: I can reproduce, the skip-silences plugin is responsible for it, due to the repeated silences in the music

Ah, that makes sense. Thanks! :heart: 

---

By the way, it seems like a plugin for SponsorBlock's "Skip to Highlight" would be a great alternate option, as not only would that skip silences, but would skip stuff at the beginning of music videos, like in [Wake Me Up When September Ends](https://www.youtube.com/watch?v=NU9JoFKlaZ0), or [We're Not Gonna Take It](https://www.youtube.com/watch?v=4xmckWVPRaI).

I'd love to make a pull request integrating this myself, but this *really* isn't my area of expertise (what little expertise I do have :P).

**Comment by th-ch** [comment]
There is a `sponsorblock` plugin! You can enable it, by default, the [following categories](https://github.com/th-ch/youtube-music/blob/a1bed628f47bc3032bacbe7c3e04930b20ef6e10/config/defaults.js#L74-L79) are blocked but you can override the setting in the app config to pick the categories of your choice :)

**Comment by askiiart** [comment]
> There is a `sponsorblock` plugin! 

Well I feel stupid. Thanks!
