### ISSUE TITLE
Discord Connection is fine but the song timer after the first is 00:00

### ISSUE THREAD

**Issue by MasamuneDate99** [th-ch/youtube-music#930]
![image](https://user-images.githubusercontent.com/24244933/209455687-e8d67731-1485-43b8-8417-0cafb9e7769f.png)

#925 

Im using zobro pre build YT music, the one from [this](https://github.com/th-ch/youtube-music/issues/925#issuecomment-1360635739)

The discord integration already working but, after the first song was played, the next song will show the time always 00:00

*Editted :
Only bugged with autoplay feature, if we select which song to be played it will be played and shown normally, but autoplay like playlist and auto playlist will show 00:00 instead

**Comment by Zo-Bro-23** [comment]
The same issue is mentioned in #878 and #902. It's most likely a bug, and a potential fix was described in #902. @Vilsol, you're more than welcome to create a PR with the fix!

**Comment by MasamuneDate99** [comment]
I dont know what's change but maybe its a good thing to mention

![image](https://user-images.githubusercontent.com/24244933/211978503-c90d6fde-7b37-473c-bea8-ef4eb7169059.png)
![image](https://user-images.githubusercontent.com/24244933/211979128-7a5709e9-8f46-4ac8-bc48-d99492da1a8a.png)


Now instead immediately to 00:00, it starts from 00:06 ( picture 1 )
I dont know what cause this ( Picture 2 ), what i did was to try moving the song back and forward to test the discord RPC. ( I skipped like 2/3 songs, but skipping by forwarding the song ( not pressing the next button ) )

**Comment by JellyBrick** [comment]
Fixed at #1235
