### ISSUE TITLE
GitHub Actions Building - Releases?

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#934]
I see that the GitHub Actions Workflow for auto-building the app is working, and electron-builder is building the app for all three OSs. Why not use the github-releases action workflow to auto-push a new release? If you don't want to do this for all changes, maybe you can do it only when version is updated in `package.json`, or when the changes are pushed with a particular message (or tag). Having no releases for the latest version means that old bugs (Discord plugin) persist, and new features (skip-silences plugin) are unavailable.

PS: Right now I'm running my own GH Actions to build releases, and they're available [here](https://github.com/Zo-Bro-23/youtube-music/releases), but it would be useful if the main repo did this too.

**Comment by Araxeus** [comment]
resolved by https://github.com/th-ch/youtube-music/pull/936
