### ISSUE TITLE
Touchbar plugin like buttons

### ISSUE THREAD

**Issue by l-laziz** [th-ch/youtube-music#935]
Mac Touchbar plugin Like buttons act the opposite way - Like button actually dislikes and dislike button acts as Like.

**Comment by th-ch** [comment]
👋 Indeed, it was fixed in https://github.com/th-ch/youtube-music/pull/822 but the new version has not been released yet - it will be soon!

**Comment by l-laziz** [comment]
New release v.19 still has this issue. It's not fixed.
