### ISSUE TITLE
issue with moving songs in queue, and buttons in the context menu not actually affecting anything after latest update

### ISSUE THREAD

**Issue by FloofyTanuki** [th-ch/youtube-music#937]
when attempting to use the context menu, none of the buttons seem to do anything besides closing the context menu, and i'm unable to move songs in the queue by clicking and dragging, installer version if that matters

**Comment by Araxeus** [comment]
All works well on my side, context menu and dragging songs. which OS are you on?

Not sure how to help here… any one else experience this?

**Comment by FloofyTanuki** [comment]
Randomly fixed itself
