### ISSUE TITLE
Some keys not able to to be used with YouTube Music open due to Hotkeys taking priority.

### ISSUE THREAD

**Issue by Kxsumi** [th-ch/youtube-music#938]
The numbers 9, /, and a few others are unusable with the application open. They continue to work after it is closed

**Comment by Araxeus** [comment]
What did you bind those to?

It all works fine for me

**Comment by Kxsumi** [comment]
> What did you bind those to?
> 
> It all works fine for me

I didn't. And I don't know how to turn them off.

**Comment by Araxeus** [comment]
can you post your config.json?

`Options` - `Advanced options` - `Edit config.json`

**Comment by Kxsumi** [comment]
> can you post your config.json?
> 
> `Options` - `Advanced options` - `Edit config.json`
{
	"window-size": {
		"width": 1920,
		"height": 1040
	},
	"url": "https://music.youtube.com/watch?v=YzlAfrDON9w&list=RDAMVMEY7YIlIh-qU&index=0",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": false,
		"resumeOnStart": false,
		"proxy": "",
		"alwaysOnTop": false,
		"removeUpgradeButton": true,
		"ForceShowLikeButtons": true,
		"hideMenuWarned": true
	},
	"plugins": {
		"navigation": {
			"enabled": false
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"shortcuts": {
			"enabled": false,
			"overrideMediaKeys": false
		},
		"downloader": {
			"enabled": true,
			"ffmpegArgs": [],
			"preset": "mp3"
		},
		"last-fm": {
			"enabled": true,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
			"api_key": "04d76faaac8726e60988e14c105d421a",
			"secret": "a5d2a36fdf64819290f6982481eaffa2",
			"token": "iYIcA0H_FnI1OkWA5Fd01UZETfYxd3Rl",
			"session_key": "7VTgwx2V18Dw5CNGwzwZPPotkjyyK_rE"
		},
		"discord": {
			"enabled": true,
			"activityTimoutEnabled": true,
			"activityTimoutTime": 600000,
			"listenAlong": true
		},
		"notifications": {
			"enabled": false,
			"unpauseNotification": false,
			"urgency": "normal",
			"interactive": false
		},
		"precise-volume": {
			"enabled": true,
			"steps": 1,
			"arrowsShortcut": true,
			"globalShortcuts": {
				"volumeUp": "9",
				"volumeDown": ""
			},
			"savedVolume": 25
		},
		"sponsorblock": {
			"enabled": true,
			"apiURL": "https://sponsor.ajay.app",
			"categories": [
				"sponsor",
				"intro",
				"outro",
				"interaction",
				"selfpromo",
				"music_offtopic"
			]
		},
		"video-toggle": {
			"enabled": true,
			"mode": "native",
			"forceHide": false,
			"hideVideo": false
		},
		"bypass-age-restrictions": {
			"enabled": true
		},
		"exponential-volume": {
			"enabled": true
		},
		"lyrics-genius": {
			"enabled": true
		},
		"quality-changer": {
			"enabled": true
		},
		"taskbar-mediacontrol": {
			"enabled": false
		},
		"no-google-login": {
			"enabled": false
		},
		"tuna-obs": {
			"enabled": false
		},
		"in-app-menu": {
			"enabled": true,
			"hideIcon": false
		},
		"blur-nav-bar": {
			"enabled": true
		},
		"picture-in-picture": {
			"enabled": true,
			"isInPiP": false
		},
		"playback-speed": {
			"enabled": true
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.19.0"
		}
	},
	"window-position": {
		"x": -8,
		"y": 8
	},
	"window-maximized": true
}

**Comment by Kxsumi** [comment]
> can you post your config.json?
> 
> `Options` - `Advanced options` - `Edit config.json`


{
	"window-size": {
		"width": 1920,
		"height": 1040
	},
	"url": "https://music.youtube.com/watch?v=YzlAfrDON9w&list=RDAMVMEY7YIlIh-qU&index=0",
	"options": {
		"tray": false,
		"appVisible": true,
		"autoUpdates": true,
		"hideMenu": false,
		"startAtLogin": false,
		"disableHardwareAcceleration": false,
		"restartOnConfigChanges": false,
		"trayClickPlayPause": false,
		"autoResetAppCache": false,
		"resumeOnStart": false,
		"proxy": "",
		"alwaysOnTop": false,
		"removeUpgradeButton": true,
		"ForceShowLikeButtons": true,
		"hideMenuWarned": true
	},
	"plugins": {
		"navigation": {
			"enabled": false
		},
		"adblocker": {
			"enabled": true,
			"cache": true,
			"additionalBlockLists": []
		},
		"shortcuts": {
			"enabled": false,
			"overrideMediaKeys": false
		},
		"downloader": {
			"enabled": true,
			"ffmpegArgs": [],
			"preset": "mp3"
		},
		"last-fm": {
			"enabled": true,
			"api_root": "http://ws.audioscrobbler.com/2.0/",
			"api_key": "04d76faaac8726e60988e14c105d421a",
			"secret": "a5d2a36fdf64819290f6982481eaffa2",
			"token": "iYIcA0H_FnI1OkWA5Fd01UZETfYxd3Rl",
			"session_key": "7VTgwx2V18Dw5CNGwzwZPPotkjyyK_rE"
		},
		"discord": {
			"enabled": true,
			"activityTimoutEnabled": true,
			"activityTimoutTime": 600000,
			"listenAlong": true
		},
		"notifications": {
			"enabled": false,
			"unpauseNotification": false,
			"urgency": "normal",
			"interactive": false
		},
		"precise-volume": {
			"enabled": true,
			"steps": 1,
			"arrowsShortcut": true,
			"globalShortcuts": {
				"volumeUp": "9",
				"volumeDown": ""
			},
			"savedVolume": 25
		},
		"sponsorblock": {
			"enabled": true,
			"apiURL": "https://sponsor.ajay.app",
			"categories": [
				"sponsor",
				"intro",
				"outro",
				"interaction",
				"selfpromo",
				"music_offtopic"
			]
		},
		"video-toggle": {
			"enabled": true,
			"mode": "native",
			"forceHide": false,
			"hideVideo": false
		},
		"bypass-age-restrictions": {
			"enabled": true
		},
		"exponential-volume": {
			"enabled": true
		},
		"lyrics-genius": {
			"enabled": true
		},
		"quality-changer": {
			"enabled": true
		},
		"taskbar-mediacontrol": {
			"enabled": false
		},
		"no-google-login": {
			"enabled": false
		},
		"tuna-obs": {
			"enabled": false
		},
		"in-app-menu": {
			"enabled": true,
			"hideIcon": false
		},
		"blur-nav-bar": {
			"enabled": true
		},
		"picture-in-picture": {
			"enabled": true,
			"isInPiP": false
		},
		"playback-speed": {
			"enabled": true
		}
	},
	"__internal__": {
		"migrations": {
			"version": "1.19.0"
		}
	},
	"window-position": {
		"x": -8,
		"y": 8
	},
	"window-maximized": true
}

**Comment by Araxeus** [comment]
Look at the option
`precise-volume` - `global hotkeys`

You registered the key <kbd>9</kbd>

**Comment by Kxsumi** [comment]
> 

I didn't change that so that's really weird. Thanks!
