### ISSUE TITLE
Windows Defender flagging app as Trojan "Wacatac.B!ML"

### ISSUE THREAD

**Issue by CpazR** [th-ch/youtube-music#939]
![image](https://user-images.githubusercontent.com/6466091/210275073-a1d03d05-e311-4e5f-806a-2382210d3942.png)

Unsure if anyone else has had this issue. But starting today windows defender seems to be catching this app.

Looks like it's related to `snoreToast`

![image](https://user-images.githubusercontent.com/6466091/210275361-38bef412-a396-4420-8e8c-f6c327d46013.png)

**Comment by Araxeus** [comment]
See https://github.com/th-ch/youtube-music/issues/848#issuecomment-1351749320

Meanwhile we can ask microsoft to remove the false positive
