### ISSUE TITLE
Windows / Bypass Age Restriction

### ISSUE THREAD

**Issue by lvlts** [th-ch/youtube-music#940]
The latest build (1.19) does not seem to bundle the bypass restrictions plugin:

```
Uncaught Error: Cannot find module 'simple-youtube-age-restriction-bypass/Simple-YouTube-Age-Restriction-Bypass.user.js'
Require stack:
- C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\bypass-age-restrictions\front.js
- C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\preload.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\bypass-age-restrictions\front.js:3:2)
    at C:\Users\user\AppData\Local\Programs\youtube-music\resources\app.asar\preload.js:54:4
    at C:\Users\userAppData\Local\Programs\youtube-music\resources\app.asar\plugins\utils.js:48:3
```

**Comment by Araxeus** [comment]
not sure what is going on here, it is included, and also from my testing it works in both
https://github.com/th-ch/youtube-music/releases/download/v1.19.0/YouTube-Music-Setup-1.19.0.exe
and in dev mode

https://github.com/th-ch/youtube-music/blob/v1.19.0/package.json#L99

https://github.com/th-ch/youtube-music/blob/v1.19.0/plugins/bypass-age-restrictions/front.js#L1-L4

**Comment by lvlts** [comment]
@Araxeus 

I uninstalled. Pulled the same link you provided and reinstalled. Same issue in the developer tools.


MD5 of the installer:
```
008e08b05e92a6604dff00babbf39e9c  /home/user/Downloads/YouTube-Music-Setup-1.19.0.exe
```


I can confirm no antivirus (Windows Defender) is doing anything weird. I unpacked the app.asar file, and I cannot see the `simple-youtube-age-restriction-bypass` in the `node_modules` folder, which means it's not included in the release bundled with the installer.

As far as I see, the actual plugin, which you mentioned in the `package.json` file is not there.

**Comment by Araxeus** [comment]
> As far as I see, the actual plugin, which you mentioned in the `package.json` file is not there.

What does that mean?
is it not written in package.json?
is it not in the plugins menu?
![image](https://user-images.githubusercontent.com/78568641/212100165-8f638119-d685-40c5-9816-3c8c70940482.png)
![image](https://user-images.githubusercontent.com/78568641/212101038-56990924-f54f-4832-b378-250fdc7fe260.png)
![image](https://user-images.githubusercontent.com/78568641/212101226-1858e796-689f-468f-aa40-f0345f218668.png)


I really don't know what's going on here...
if you go to this link https://gitpkg.now.sh/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/dist?v2.5.4
does it download?
