### ISSUE TITLE
Feature Request: Zoom

### ISSUE THREAD

**Issue by SHU-red** [th-ch/youtube-music#95]
Hello everyone,
im not into Java and dont know if someone else also would like to be able to scale/zoom the content of the page --> If noone wants it, you can discard this request.

Thanks

**Comment by hackel** [comment]
This would be useful.  I believe it's built-in to Electron, just a matter of adding ctrl +/-/0 keybindings and remembering the zoom level.  I find the UI is just way too big and often want to zoom it out so that I can see full song titles.

**Comment by Araxeus** [comment]
This feature exists in the latest version, issue can be closed

**Comment by SHU-red** [comment]
> This feature exists in the latest version, issue can be closed

Hey @Araxeus 
Thanks for the information
Can you tell me how to use it?

Could not find it in the options and ctr+(+/-/0) doesnt do anything

Im Using Linux Mint 20.1

**Comment by Araxeus** [comment]
@SHU-red  Its all in the `View` submenu, make sure your application is updated
Zoom In = `Ctrl `+ `Shift `+ `=`
Zoom Out = `Ctrl` + `-`
Reset Zoom = `Ctrl `+ `0`

**Comment by SHU-red** [comment]
> @SHU-red
> Its all in the `View` submenu, make sure your application is updated
> Zoom In = `Ctrl `+ `Shift `+ `=`
> Zoom Out = `Ctrl` + `-`
> Reset Zoom = `Ctrl `+ `0`

Not reacting when im using thes hotkeys
Im using 1.11.0
Screenshot of Menu attached

System info here:
```
System:    Kernel: 5.4.0-70-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
           Desktop: Cinnamon 4.8.6 wm: muffin 4.8.1 dm: GDM3 3.36.3, LightDM 1.30.0 
           Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
```

![YTM](https://user-images.githubusercontent.com/68030498/112725379-340a2800-8f18-11eb-840f-149f8b3688cf.jpg)

**Comment by Araxeus** [comment]
Im actually extremely confused... I dont understand how is it possible that you are missing 2 submenu's
You have the first 2 but not the following 2 
https://github.com/th-ch/youtube-music/blob/cbd7a132757c066737abd2458b0ec41ec2745cf9/menu.js#L25
https://github.com/th-ch/youtube-music/blob/cbd7a132757c066737abd2458b0ec41ec2745cf9/menu.js#L59
https://github.com/th-ch/youtube-music/blob/cbd7a132757c066737abd2458b0ec41ec2745cf9/menu.js#L193
https://github.com/th-ch/youtube-music/blob/cbd7a132757c066737abd2458b0ec41ec2745cf9/menu.js#L204

It really seems to me like you are somehow using an older version somehow, please recheck in advanced config you have this line
```json
"__internal__": {
		"migrations": {
			"version": "1.11.0"
		}
```

@semvis123 @th-ch any idea what might be going on here?

**Comment by semvis123** [comment]
The code is in the master branch but not in the precompiled release. So if you wanted to use this function now, you would have to compile it yourself (see the dev section in the readme), or you could wait for it to appear in the next release.

**Comment by Araxeus** [comment]
Oh sorry I was sure it was in the release, got mixed up

**Comment by SHU-red** [comment]
Ok thanks guys!
If i got it right: These functions will be available for each and every OS in the coming releases.

Thx
