### ISSUE TITLE
[Feature Request] Automatically reconnect to Discord

### ISSUE THREAD

**Issue by NotMithical** [th-ch/youtube-music#952]
Love the discord integration, but if I open youtube music before discord, or close and re-open discord while youtube music is open, I have to manually reconnect. It would be great if the app automatically attempted to reconnect every few seconds or minutes without the need for user interaction.

**Comment by Araxeus** [comment]
I just thought about this the other day.
a package that does this already exists https://github.com/saucesteals/discord-auto-rpc

should be easy to do @Zo-Bro-23

**Comment by xhayper** [comment]
uto reconnect is actually easy! and you can do it yourself! just listen to the `disconnect` event and call the `connect` function on the client!

The reason why I won't add it is because i want the developer to make their own reconnect logic!

**Comment by Zo-Bro-23** [comment]
> I just thought about this the other day.

Yes, me too! I even added it to my to-do list, but sadly been a bit busy lately! I'll do it when I get some off-time (probably late Jan). (You can assign the issue to me if you want)

**Comment by xhayper** [comment]
Just a side🎵, i can work on a PR that change from discordjs's discord-rpc to mine, i have nothing to do at this moment.

**Comment by Zo-Bro-23** [comment]
> Just a side:musical_note:, i can work on a PR that change from discordjs's discord-rpc to mine, i have nothing to do at this moment.

Sure. Does that mean that I don't have to work on the auto-reconnect feature? Or does your rpc package not support auto-reconnect?

**Comment by xhayper** [comment]
My RPC package doesn't support auto-reconnect out-of-the-box, but it's easy to implement it by using the code i provide.

**Comment by Araxeus** [comment]
> Just a side🎵, i can work on a PR that change from discordjs's discord-rpc to mine, i have nothing to do at this moment.

You're welcome to contribute 🙌

**Comment by xhayper** [comment]
closed in #961
