### ISSUE TITLE
Last.FM scrobble doesn't work

### ISSUE THREAD

**Issue by reyquito** [th-ch/youtube-music#957]
Hi!

Thanks for your work on the app, it's great :)

I just noticed last.fm scrobble doesn't seem to work. I get one first scrobble every session, and then nothing. I'd like to know if this is a known issue and if there is any fix or workaround I could try.

I'm using the .deb version on Linux Mint.

**Comment by Zo-Bro-23** [comment]
It's a known issue (#902). Surprisingly, though, the issue doesn't exist for me personally. I've used both Ubuntu and Windows, and my Last.FM works just fine.

As for fixes, @Vilsol mentioned a potential fix in #902. If you know code, you can try to fix it yourself and create a PR. If not, I'm a bit busy right now, but I'll try to fix it myself later on.

**Comment by reyquito** [comment]
Thank tou! I don't code myself, so I'll wait for you to look into it.
