### ISSUE TITLE
Logging out issue

### ISSUE THREAD

**Issue by XeroHero** [th-ch/youtube-music#960]
Hi, 

I am facing an issue currently. I had originally signed in to the th-ch YT Music app on my Mac (runs latest version of macos) using my old university account (Google SSO G-Suite account). However, this account recently got shut down as I have graduated. 

I am however unable to return to the "normal Google" account sign-in page from the app. 

I have tried clearing the cache, uninstalling and reinstalling the app and many reboots between each of these, but when I click "Login" button on the top right corner, I'm always brought back to the SSO page. It's as if something is being cached in the disk that's automatically redirecting it to that SSO page. 

If anyone has faced this issue before, or knows of workarounds, please let me know. I have recently installed the latest update of YT Music.

Thanks very much.

**Comment by Zo-Bro-23** [comment]
Try doing the following:
- Uninstall YT Music
- Go to `~/.config/` in Finder and delete the `YouTube Music` folder
- Try installing YT Music again
- Let us know if the issue persists!

> It's as if something is being cached in the disk that's automatically redirecting it to that SSO page.

The app caches data and preferences in the `~/.config/YouTube Music/` folder, and I suspect that's what is leading to the issue. Please let me know if the above steps worked!

**Comment by Araxeus** [comment]
> tried clearing the cache, uninstalling and reinstalling the app

Huh... That doesn't make a whole lot of sense considering login secrets are stored in the 'cache'

**Comment by XeroHero** [comment]
@Zo-Bro-23 I tried a similar approach to what you suggested and it worked. In my case, however, the data and preferences were in `/Library/Application Support/YouTube Music`.

However, after removing the entire folder, I was able to get past the issue. 

Thank you very much for the assistance prorvided. KInd regards.

**Comment by Zo-Bro-23** [comment]
> @Zo-Bro-23 I tried a similar approach to what you suggested and it worked. In my case, however, the data and preferences were in `~/Library/Application Support/YouTube Music`.
> 
> However, after removing the entire folder, I was able to get past the issue.
> 
> Thank you very much for the assistance prorvided. KInd regards.

I'm on Ubuntu right now, so I just assumed the config file paths will be the same on Mac (since they're both Linux based). My bad. Anyways, it's good news it's working!

**Comment by Araxeus** [comment]
> I just assumed the config file paths will be the same on Mac

https://www.electronjs.org/docs/latest/api/app#appgetpathname

Always check docs 😸
