### ISSUE TITLE
Migration to Typescript

### ISSUE THREAD

**Issue by xhayper** [th-ch/youtube-music#962]
Will be doing this
Please assign me to this.

**Comment by Zo-Bro-23** [comment]
@th-ch?

**Comment by xhayper** [comment]
Might as well as use vite

**Comment by Araxeus** [comment]
Damn that's a gigantic assignment.

Might atleast double the amount of lines in this project...

**Comment by xhayper** [comment]
I manage to get it to work, we just need to add typing now.
https://github.com/xhayper/youtube-music/tree/patch-2

**Comment by xhayper** [comment]
one big problem is plugins doesn't work correctly... hmm..

**Comment by Araxeus** [comment]
> I manage to get it to work, we just need to add typing now. [xhayper/youtube-music@`patch-2`](https://github.com/xhayper/youtube-music/tree/patch-2?rgh-link-date=2023-01-12T07%3A06%3A57Z)

Would have been nice to first Move to ESM – and publish that as a PR
then afterward, based on that branch move to TS which is a much bigger endeavor

**Comment by th-ch** [comment]
Migrating to ESM and TS would definitely be awesome, though it's indeed a lot of work 😅 The best way forward would probably be to introduce ts along js, then migrate file by file until everything is done

**Comment by xhayper** [comment]
Very good idea

**Comment by xhayper** [comment]
Very good idea

**Comment by Araxeus** [comment]
I would also argue that changes should be merged on separate experimental branch, to avoid breaking stuff for the end user
(which will probably happen)

**Comment by ArjixWasTaken** [comment]
Lmao, looks like xhayper gave up on this?

I am up for the task, although I don't have a lot of free time, so it may take a while :^)

**Comment by xhayper** [comment]
yeah i gave up on this, got another project going on, sorry.

**Comment by ArjixWasTaken** [comment]
Was experimenting on a splash screen, what do you think of it (as a concept)?


https://github.com/th-ch/youtube-music/assets/53124886/75d8aab2-4a2d-43dc-8457-03769700fb1f

**Comment by ArjixWasTaken** [comment]
Calling everyone interested in the typescript re-write ||*(the code is too much spaghetti to just port it over)*|| to discuss over at my fork.

https://github.com/ArjixWasTaken/youtube-music-ts/discussions/1

**Comment by ArjixWasTaken** [comment]
@th-ch maybe pin this issue?

that way more people would see it and join in on the effort

**Comment by JellyBrick** [comment]
Migration to TypeScript is complete! (#1235)
