### ISSUE TITLE
Make last.fm support better

### ISSUE THREAD

**Issue by xRealNeon** [th-ch/youtube-music#967]
Hey I am using your client for a while now and like it a lot but the last.fm plugin could be improved.

* Add a filter to the songs so that for example (Official Video) gets filtered, or the channel name is not the artist name.
https://github.com/web-scrobbler/metadata-filter
* When I listen to a song it shows up twice on last.fm and when the next one plays it just shows up once

**Comment by Araxeus** [comment]
> Add a filter to the songs so that for example (Official Video) gets filtered, or the channel name is not the artist name.
 
We already do that. see
https://github.com/th-ch/youtube-music/blob/35bd62cc0d8856ed161bbd865255c88e15a08855/providers/song-info.js#L111-L128

> When I listen to a song it shows up twice on last.fm and when the next one plays it just shows up once

Could use the new `video-src-changed` argument when #946 is merged. might fix it
https://github.com/th-ch/youtube-music/blob/35bd62cc0d8856ed161bbd865255c88e15a08855/plugins/last-fm/back.js#L145-L146
