### ISSUE TITLE
Menu option to copy current URL

### ISSUE THREAD

**Issue by kotx** [th-ch/youtube-music#975]
The share function doesn't provide the whole URL, so you can't share what playlist you're on, etc.

**Comment by Araxeus** [comment]
Should that actually be a button in the already cluttered menu?

maybe there's some better discreet place for that

**Comment by kotx** [comment]
> maybe there's some better discreet place for that

I don't think there would be a better place for it since it needs to be accessible everywhere in the app. It being in the Navigation menu (like in the above PR) seems fine.
