### ISSUE TITLE
Using butterchurn visualiser type stops audio playback

### ISSUE THREAD

**Issue by ChefKissInc** [th-ch/youtube-music#981]
Built latest master (a51ed89281bfa2df41835a94dd4f6293dfe1e9d5) to test out the new visualiser plugin.
Vudio and Wave work, Butterchurn renders, but makes the audio go silent.
Not sure if that's known, I apologise if you're already aware.
```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
```

**Comment by th-ch** [comment]
Hey @ChefKissInc, thanks for the feedback - I'm on the same setup but I can't reproduce 🤔 Can you try again with latest master? https://github.com/th-ch/youtube-music/commit/d44fb5c840a8deb4df361e7f305ec9b52ae7fe45 _might_ have fixed it.

**Comment by ChefKissInc** [comment]
Yup, it works now. Thanks!
