### ISSUE TITLE
[Issue] Adblocker plugin does not work...

### ISSUE THREAD

**Issue by TheSoulWizard** [th-ch/youtube-music#983]
I've been getting ads even though adblock is enabled. I tried to toggle On & Off the feature **(Restarting the app after each toggle)**, but didn't seem to help at all.

Version: 1.19.0
Region: GR

![image](https://user-images.githubusercontent.com/40411642/212735922-44dc53fd-09b1-4cad-ba15-18ee301f8963.png)

**Comment by Araxeus** [comment]
try this release and please do tell if it work

https://github.com/Zo-Bro-23/youtube-music/releases/tag/v1.19.0
