### ISSUE TITLE
Don't autoplay on startup, do autoplay past that

### ISSUE THREAD

**Issue by OmegaLambda1998** [th-ch/youtube-music#985]
Is it possible to not autoplay music when you open the app, but once music starts playing, then you autoplay? This is the behaviour of the browser version.

Obviously I can enable `disable-autoplay` to stop it playing music on startup, but then I have to manually start each song. And I can't dynamically enable and disable autoplay, I have to disable it then restart youtube-music.

**Comment by DereC4** [comment]
I'm a bit confused, what do you mean by once the music starts playing, you autoplay? Do you mean autoplay as in the youtube function where each song continues to play after the next?

**Comment by Araxeus** [comment]
I think he just means disable autoplay only on the first song

**Comment by DereC4** [comment]
oh

**Comment by OmegaLambda1998** [comment]
So, at the moment if autoplay is on, then on opening the application music starts playing, and will continue playing after each song finishes. If autoplay is off, then you have to press play on application startup and on every song after that.

What I'd like is the option to start up the application, have the music wait till I press play, then continue playing past that. I.e autoplay-off on startup and autoplay-on after the first song starts

**Comment by Araxeus** [comment]
Can't you just disable `Resume last song when app start`?

Why do you want to start with the last played song, but paused?

**Comment by OmegaLambda1998** [comment]
Ah, I did not realise that was an option. That does indeed solve my issue!

**Comment by Araxeus** [comment]
Ah yes it's one of the few options that are enabled by default - I see how that can be confusing since you didn't enable it

**Comment by DereC4** [comment]
yay

**Comment by Destroy666x** [comment]
@Araxeus it's confusing and not a great choice. I would love to remember last song but without autoplaying, especielly when there's startup with Windows.
