### ISSUE TITLE
Installation question 

### ISSUE THREAD

**Issue by ubreathtaking** [th-ch/youtube-music#991]
Good day, wanted to know how is it possible to install youtube-music on android phone ?

**Comment by Zo-Bro-23** [comment]
Unfortunately, no, since youtube-music uses Electron, which only supports Windows/Linux/Mac. For Android, I would recommend Vanced, which although discontinued, is still available through archives and unofficial mirrors. Other alternatives like ReVanced also seem to work well for others (I haven't personally tested them).

**Comment by ubreathtaking** [comment]
@Zo-Bro-23 understood, as of now i was using vanced 4.60, it's a just a music player which acts like suggestion song track list device. You actually find the song you want, press "like"   song is played and afterwards you get similar songs all nigh long. I just installed ReVanced and it feels like it's a youtube video player not the music player (which base your music suggestion by the music style you are listening to).

**Comment by Zo-Bro-23** [comment]
> @Zo-Bro-23 understood, as of now i was using vanced 4.60, it's a just a music player which acts like suggestion song track list device. You actually find the song you want, press "like" song is played and afterwards you get similar songs all nigh long. I just installed ReVanced and it feels like it's a youtube video player not the music player (which base your music suggestion by the music style you are listening to).

Right. Based on my personal experience, Vanced works just as well as the desktop app does, obviously without features like plugins. It works more than well for my use cases, and I'm afraid that's all we have for android at the moment. If you find anything else, please feel free to let others know by replying to this thread!

**Comment by Araxeus** [comment]
> @Zo-Bro-23 understood, as of now i was using vanced 4.60, it's a just a music player which acts like suggestion song track list device. You actually find the song you want, press "like"   song is played and afterwards you get similar songs all nigh long. I just installed ReVanced and it feels like it's a youtube video player not the music player (which base your music suggestion by the music style you are listening to).  

You might be confusing the youtube music app with the normal youtube app

Vanced & Revanced both offer modded versions of the youtube music app
