### ISSUE TITLE
[Feature Request] Lyrics language priority option

### ISSUE THREAD

**Issue by jang-geon** [th-ch/youtube-music#993]
First of all, thank you to the developers who made it a great experience

Lyrics-Genius works well
However, most of them are in English or only with lyrics that fit the language of the music.
Sites such as Musicmatch and Genius also support multiple lyrics for different countries.
I think it would be great if there was an option to select the lyrics language
(ex. A way to show a list of lyrics searched for in a plugin and select them)

In particular, I think the 'romaji' and 'romanized' options for Asian songs are very necessary!

**Comment by DereC4** [comment]
I was actually thinking about working on this since there are romanized lyrics already out there

**Comment by DereC4** [comment]
Progress is being made

**Comment by Araxeus** [comment]
Hit me up if you need help with anything

Available on discord

**Comment by DereC4** [comment]
> Hit me up if you need help with anything
> 
> Available on discord

Oh yay thx

**Comment by DereC4** [comment]
Sent a friend request

**Comment by DereC4** [comment]
#1039

**Comment by DereC4** [comment]
our update was just pushed to the main branch of which a romanization option was added so yay gj everyone
